### ISSUE TITLE
codeceptjs run errors with Could not load helper WebDriverIO

### ISSUE THREAD

**Issue by wolfadex** [Codeception/CodeceptJS#100]
After following the installation steps and creating my first test. When I run `codeceptjs run --steps` I get an error of
`Could not load helper WebDriverIO from module './helper/WebDriverIO':`
`Required modules are not installed.`
1RUN: [sudo] npm install -g webdriverio`
I then run`sudo npm install -g webdriverio`which successfully installs. I then attempt to run`codeceptjs run --steps` again but get the same error.

**Comment by DavertMik** [comment]
Somehow CodeceptJS doesn't detect globally installed webdriverio in your case. What OS do you use?
Alternatively please install codeceptjs and webdriverio locally by adding them to package.json

**Comment by wolfadex** [comment]
I'm on Ubuntu 14.04. Also I'm using Node Version Manager.

**Comment by DavertMik** [comment]
> I'm using Node Version Manager.

That's probably the case. We use `requireg` to locate globally installed packages. It's not perfect, so as I said you may try to use local installation.

**Comment by wolfadex** [comment]
I ended up installing WebDriverIO both locally and globaly an linking them `npm link webdriverio` which seems to have done the trick. Though I would say it's not a solution.

**Comment by DavertMik** [comment]
Thanks for reporting. I will try to come with something more handy in next release

**Comment by wolfadex** [comment]
Thank you, both for the tool and the quick response!

**Comment by APshenkin** [comment]
Now nvm is supported by `requireg` so, close this issue
