### ISSUE TITLE
How i can set cookie before suite in helper class

### ISSUE THREAD

**Issue by jehord** [Codeception/CodeceptJS#1001]
Mine issue is set cookie before run all test suite I read the documentation and understanding so for that to solve mine issue me need use helper classes. Maybe I'm wrong but still. Perhaps you need to use a different approach if so let me know.

It mine helper

```js
'use strict';

class SetCookie extends Helper {

    constructor(config) {
        super(config)
    }

    _beforeSuite() {
        this.getCookies('https://site.com').then(function(x){
            console.log(x)
        })
    }

getCookies(url)
{
    var client = this.helpers['Nightmare'].browser;
    return new Promise(function (resolve) {
        client
            .goto(url)
            .cookies.get() // get the cookies
            .end()
            .then(resolve)
    });
}

}
module.exports = SetCookie;

```

### Details

* CodeceptJS version: codeceptjs@1.1.5 
* NodeJS Version:v9.6.1
* Operating System: MacOS High sierra 10.13.3
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file: 

```js
{
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": "https://site.com",
      "show": true,
      "restart": false
    },
    "SetCookie": {
      "require": "./setcookie_helper.js"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "tests": "./*_test.js",
  "timeout": 10000,
  "name": "CodeceptJs"
}
```

**Comment by reubenmiller** [comment]
Nightmare already has a `.setCookie()` function that you can use directly in your test. So you can use it directly in your tests.

```js
// example_test.js
Feature('My feature');

BeforeSuite((I) => {
  I.amOnPage('/');
  I.setCookie({name: 'auth', value: true});
});

Scenario((I) => {
    I.see('something');
});
```

Or if you want to implement it is a helper then you could do something like this.

```js
'use strict';

let Helper = codecept_helper;

class MyHelper extends Helper {
  
  _beforeSuite() {
    const helper = this.helpers['Nightmare'];
    return helper.setCookie({name: 'auth', value: true});
  }
}

module.exports = MyHelper;
```

However I would prefer the first option because it is more obvious that the cookie is being set before the Feature is being tested, rather than buried inside a helper.

**Comment by jehord** [comment]
Thank you!

**Comment by jehord** [comment]
Can I ask one more question, which does not concern this topic?

> I did not fully understand how to fail the test using the library assert in helper class
example
