### ISSUE TITLE
Any advice about finding elements with Shadow DOM by webdriverio？

### ISSUE THREAD

**Issue by junguchina** [Codeception/CodeceptJS#1003]
Hi guys,
We use codeceptjs + webdriverio to test our webpage products, this couple works well.
But now our developer team start use **Shadow DOM** to develop the product.
This makes our e2e code can not work anymore, because can not find elements with Shadow DOM.
We searched the result on **WebdriverIO** homepage, but it seems they can not support anymore.
So someone can give some advices to resolve the problems.

**Comment by DavertMik** [comment]
Just follow updates in webdriverio repo https://github.com/webdriverio/v5/issues/44

**Comment by junguchina** [comment]
Hi @DavertMik and @PeterNgTr ，

Do you have any plan to support locator about shadow dom.
As I know, the version 5.5.0 of webdriverio has support this command.
You can refer this feature https://github.com/webdriverio/webdriverio/pull/3586#issue-254670941.
With shadow dom and web component are popular in React, Vue and other architectural patterns.

**Comment by gkushang** [comment]
I am working on adding this support. I will update soon

**Comment by codejamninja** [comment]
@gkushang how do I reference shadow dom from a class name or id?

**Comment by gkushang** [comment]
@codejamninja 

Would this help?

https://codecept.io/shadow/#locating-shadow-dom-elements

You can add the locators as is to the Array, e.g. [“ShadowTag”, “.className”]

**Comment by codejamninja** [comment]
@gkushang ok, thanks

**Comment by codejamninja** [comment]
@gkushang I verified I am able to see it, but I am not able to fill the field. I get the following error.

```
Element <input id="input-guid-1002" class="input-field" type="text"> is not reachable by keyboard
```

**Comment by codejamninja** [comment]
I filed more details about it here #2373
