### ISSUE TITLE
Chromedriver sits on data;, page

### ISSUE THREAD

**Issue by andrewhl** [Codeception/CodeceptJS#101]
Running selenium-server-standalone-2.53.0.jar, with the simplest possible test (`I.visit('/')`), and Chromedriver 2.21, and the globally installed npm packages:
`selenium-webdriver@2.53.1`, `webdriverio@4.0.5`

Chrome launches but takes me to the data;, page (which is, according to [this post](https://bugs.chromium.org/p/chromedriver/issues/detail?id=733), the default Chromedriver page). Nothing else happens. Not sure what's wrong or how to proceed. Below is my codecept.json config.

```javascript
{
  "tests": "./tests/codecept/*_test.js",
  "timeout": 10000,
  "output": "./tests/output",
  "helpers": {
    "WebDriverIO": {
      "url": "https://myapp.app",
      "browser": "chrome"
    },
    "FileSystem": {}
  },
  "include": {
    "I": "./tests/codecept/steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "myapp"
}
```

**Comment by DavertMik** [comment]
```js
I.visit('/')
```
is invalid command )

```js
I.amOnPage('/');
```
should be used instead

**Comment by andrewhl** [comment]
Thanks! My mistake.
