### ISSUE TITLE
Is there any way to record video while running test?

### ISSUE THREAD

**Issue by starunova** [Codeception/CodeceptJS#1015]
#### What are you trying to achieve?
I need to attach some kind of video recorder to record my test runs and save them to directory.

#### What do you get instead?
Been searching and trying `protractor-video-recorder` but apparently it only works for Protractor(btw I am using WebDriverIO helper). Also tried `wd-recorder` but it can't cooperate with WebDriverIO  wrapper.

@APshenkin @DavertMik help me, please.

**Comment by mingfang** [comment]
If you use Docker then you can add this script to your package.json.
```    "docker-test": "docker run -v `pwd`:/tests -w /tests --rm registry.rebelsoft.com/headless sh -c 'npm run clean && mkdir -p output; xvfb-run -s \":99 -auth /tmp/xvfb.auth -ac -screen 0 1920x1080x24\" ffmpeg -y -f x11grab -video_size 1920x1080 -i :99 -codec:v libx264 -pix_fmt yuv420p  -draw_mouse 0 -r 12 -loglevel panic output/video.mp4& DISPLAY=:99 npm test; killall ffmpeg; sleep 5'"
```
Then you can record you tests by running
```nom run docker-test```
The video will be in your output directory called video.mp4.

I use this with Jenkins and attach the video to the Jenkins job.

**Comment by DavertMik** [comment]
I'd recommend you to use Selenoid - a containerized alternative to Selenium Grid. 
It has nice UI and it can record videos for you. Works like a charm! (esp if you run it with its configuration manager)

Really. Just use Selenoid :)
