### ISSUE TITLE
Download file function

### ISSUE THREAD

**Issue by phanect** [Codeception/CodeceptJS#102]
I appreciate if CodeceptJS get file downloading function.

I'm currently trying to create test that:
1. Login to the service
2. Open a URL to download CSV which is only available for the currently logging-in user
3. Read CSV string and verify it

but CodeceptJS seems to have no functionality to download file.

**Comment by csgruenebe** [comment]
I also really like to have that. 
I will try to use `I.seeFile('foo.csv');` after the click on download.

Since I use the selenium-standalone-docker chrome instances this could get tricky ...

**Comment by anperez78** [comment]
Any feedback on this ? I also think it's a really interesting feature.

**Comment by DavertMik** [comment]
Yes, it is interesting. Do you have some suggestion of its implementation? I know it's not possible to do that in plain selenium so I don't know how it should be implemented.

**Comment by phanect** [comment]
Well, now I noticed that my implementation is bad and I should reconsider that.

In current implementation I was working for, the download link is implemented using `<button>` tag. When `<button>` is pressed, `onClick` event fires and JavaScript code (something like `window.location = /path/to/csv`) opens URL for CSV.
(Yep, it's kind of very legacy code with no test code.)

I should replace <button> to <a>, and retrieve `href` attribute value to verify if link URL is correct.
To retrieve CSV content and verify it, you can use `fetch` or `XMLHttpRequest`.

I noticed that may be why Selenium (and other E2E testing libraries) doesn't support that.
So it's OK to close this issue *for me*.
If there is other use cases and anyone is willing to implement that, please keep it open.

**Comment by WooDzu** [comment]
It may be possible to achieve with Puppeter.
Some background https://kb.apify.com/actor/handling-file-download-with-puppeteer

**Comment by PeterNgTr** [comment]
`downloadFile` is now implemented.
