### ISSUE TITLE
Cant click on modal elements

### ISSUE THREAD

**Issue by vigneshwar-v** [Codeception/CodeceptJS#1025]
#### What are you trying to achieve?
Clicking a button on a modal
#### What do you get instead?
Element not visible / not found
> Provide console output if related. Use `--verbose` mode for more details.
 Interactive debug session started
 Use JavaScript syntax to try steps in action
 Press ENTER to continue
 I.click('Okay, Got it');
 FAIL  element not visible
 I.click('#afterLaunch input[type=button]');
 FAIL  Clickable element #afterLaunch input[type=button] was not found by text|CSS|XPath
 I.click('//*[@id="afterLaunch"]/div/div/div[2]/div[3]/button')
 FAIL  element not visible
 I.click('//[@id="afterLaunch"]/div/div/div[2]/div[3]/button')
 FAIL  invalid selector: Unable to locate an element with the xpath expression //[@id="afterLaunch"]/div/div/div[2]/div[3]/button because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//[@id="afterLaunch"]/div/div/div[2]/div[3]/button' is not a valid XPath expression.
 I.click({xpath:'//*[@id="afterLaunch"]/div/div/div[2]/div[3]/button'})

### Details

There are 2 modals with same structure in the sameDOM, one gets activated for an action and thats get visible. But the click action is not working on a button from the modal thats visible

* CodeceptJS version: 1.x
* NodeJS Version: 8.11.1
* Operating System: mac OS X
*  WebDriverIO 
* Configuration file:

**Comment by DavertMik** [comment]
Sorry, I can't tell why some elements on your page are invisible or can't be accessed via webdriver.
It's not a CodeceptJS issue.
