### ISSUE TITLE
WebDriverIO helper waitUntil accepts timeout in milliseconds instead of seconds

### ISSUE THREAD

**Issue by lohmatiy-lapa** [Codeception/CodeceptJS#1026]
#### What are you trying to achieve?

`waitUntil` from WebDriverIO does not work properly.

#### What do you get instead?

According to documentation this step accepts timeout in seconds. It should then convert it to ms for WebDriverIO — but it does not.

### Details

* CodeceptJS version: 1.1.7
* NodeJS Version: 8.9.3
* Operating System: Win10
* WebDriverIO: 4.12.0

**Comment by truesrc** [comment]
This solution https://github.com/Codeception/CodeceptJS/pull/1104 for this issue

**Comment by DavertMik** [comment]
Fixed in #1104
