### ISSUE TITLE
document/window is not defined in waitUntil

### ISSUE THREAD

**Issue by truesrc** [Codeception/CodeceptJS#1029]
#### What do you get instead?

 
**document is not defined**
  Scenario Steps: 
  - I.waitUntil(() => document.readyState == "complete", 10) at Test.<anonymous> (help_test.js:69:12)
  - I.amOnPage("https://codecept.io") at Test.<anonymous> (help_test.js:68:13)

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
        I.amOnPage('https://codecept.io')
        I.waitUntil(() => document.readyState == "complete", 10)

```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by GREENpoint** [comment]
What helper do u use?

**Comment by truesrc** [comment]
WebDriverIO
This solution https://github.com/Codeception/CodeceptJS/pull/1115 for this issue
