### ISSUE TITLE
BeforeAll, Init before Tests

### ISSUE THREAD

**Issue by fabioel** [Codeception/CodeceptJS#103]
Hi @DavertMik 
Is there a possibility like BeforeAll or Init to be run prior to the tests, but only once. The current implementation of `Before` runs before every `Scenario`.

**Comment by smozely** [comment]
Been looking at this today and seems like it shouldn't be that hard to implement, seems like most of the things are there to be dispatched, but just not hooked into call the `helper.js` ... though seems like `all.before` is never called

**Comment by Nighthawk14** [comment]
@fabioel Would that be solved with the beforeSuite hook on https://github.com/Codeception/CodeceptJS/pull/167 ?

**Comment by APshenkin** [comment]
There is BeforeSuite and AfterSuite hooks in scenario. They runs only one time before/after feature testing
