### ISSUE TITLE
[Puppeteer] seeElement, click... etc functions doesnt work not in initial tab when more than 1 tabs opened 

### ISSUE THREAD

**Issue by ngadiyak** [Codeception/CodeceptJS#1034]
Case:
At the time of execution of the test the new tab appears.
Use I.switchToNextTab ()
Try to find element or click
Fail

When in Puppeteer several tabs, search of elements are opened (or any interaction with elements) in the second (on given the moment active) a tab it is impossible since the framework tries to look for elements in an initial (first) tab.

**Comment by allenhwkim** [comment]
Translation in English?

**Comment by ngadiyak** [comment]
@allenhwkim ok

**Comment by ngadiyak** [comment]
@DavertMik any news?

**Comment by DavertMik** [comment]
I hope that was fixed in 1.3.0
I heavily updated Puppeteer source and I hope this actually solves it.
