### ISSUE TITLE
codeceptjs init should create valid webdriverio config

### ISSUE THREAD

**Issue by pablopaul** [Codeception/CodeceptJS#1035]
#### What are you trying to achieve?
Follow the quickstart guide -> use webdriverio -> run a sample test

`codeceptjs init` does not generate the webdriverio helper config in `codecept.json` at all.

#### What do you get instead?
```bash
paul@PaulsDiore24MBP  ~/projects/test  node_modules/codeceptjs/bin/codecept.js run --steps --verbose
CodeceptJS v1.1.8
Using test root "/Users/paul/projects/test"

Init --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
 test something
   Emitted | test.before
   Emitted | test.start ([object Object])
   [1] Queued | throw error TypeError: I.amOnPage is not a function
   [1] Queued | fire test.passed
   [1] Queued | finish test
   [1] Error | TypeError: I.amOnPage is not a function
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
 ✖ FAILED in 2ms

   [2] Starting recording promises
   Emitted | test.after
   Emitted | suite.after ([object Object])

-- FAILURES:

  1) Init
       test something:
     I.amOnPage is not a function
  ypeError: I.amOnPage is not a function
      at Test.Scenario (init_test.js:5:7)
      at Context.test.fn (node_modules/codeceptjs/lib/scenario.js:82:26)


  FAIL  | 0 passed, 1 failed   // 9ms
   Emitted | global.result ([object Object])
   Emitted | global.after ([object Object])
```

```js
Feature('Init');

Scenario('test something', (I) => {
    I.amOnPage('/');
    I.see('Login');
});
```

### Details

* CodeceptJS version: v1.1.8
* NodeJS Version: v9.11.1
* Operating System: Mac OS X 10.13.4
* WebDriverIO
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {},
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "test"
}
```

**Comment by DavertMik** [comment]
Looks like you didn't select WebDriverIO option when you had a list of helpers.

You can either select a helper or edit the config manually afterwards. What we can do from our side is to show notice that no helpers were selected so please update the config manually. 

Thanks

**Comment by pablopaul** [comment]
@DavertMik You are right, I did not select WebDriverIO option when I had the list because just pressing enter does not select it, it only continue the init process without selecting the current helper.

My expectation was: Pressing enter would select the current helper in the list, can this be made or is a selection via "space key" and then pressing enter necessary?
