### ISSUE TITLE
Step object docs are inconsistent

### ISSUE THREAD

**Issue by pablopaul** [Codeception/CodeceptJS#1055]
https://codecept.io/pageobjects/ states "Technically they are the same as PageObjects but with no locators inside them. StepObjects can inject PageObjects and use multiple POs to make a complex scenarios"

`codeceptjs go --type step`

creates a boilerplate file with the contents 

```js
// insert your locators and methods here
```

should "locators" be removed from boilerplate code or is the above docu wrong?

**Comment by DavertMik** [comment]
It's easier to remove them from documentation)
It's really up to you how to organize code. 
I would use step objects to combine Page objects into a scenario
