### ISSUE TITLE
Response Assertion DSL API for REST testing 

### ISSUE THREAD

**Issue by javigomez** [Codeception/CodeceptJS#1059]
Hi, I am using codecept for testing an API. Checking the REST module documentation https://codecept.io/helpers/REST/ I am missing some of the API available at **codeception.com** (the PHP older brother of codecept.io) for doing asserts over the responses (for example: I.seeHttpHeader, I.seeResponseEquals, seeResponseCodeIs...)

I am currently doing this way, but I am not sure if is the right way or there is a better one:

```js
var assert = require('assert')

Feature('Health Check Endpoints')

Scenario('returns an HTTP 200 if if all the required dependencies are reachable and work as expected', async (I) => {
  const response = await I.sendGetRequest('https://mydomain.com/ready')
  assert.equal(response.code, '200')
})
```

I am happy to contribute code or documentation if there is room for improving it but I need some direction.

### Details

* CodeceptJS version: v1.1.8
* NodeJS Version: v8.9.1
* Operating System: MacOS 10.12.5 
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "REST": {
      "config": {
        "endpoint": "localhost:1337"
      }
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "toltec"
}
```

**Comment by DavertMik** [comment]
Hi, @javigomez, btw welcome to our Slack https://join.slack.com/t/codeceptjs/shared_invite/enQtMzA5OTM4NDM2MzA4LTNiMTE5YzNlMjQyNWYwZjAzODE3ZTI1MmVkYjY0YTYyNDZmMWJjM2VlODg3NTQzYzM2OGE5ZmIwODFjODk1MzI

The reason there are no response helpers is that unlike Codeception, CodeceptJS is focused on end to end testing only. So we use REST only for data management and not for API testing. So it stands out of my focus but if you want to do full REST API testing withing CodeceptJS, you are welcome to contribute

**Comment by javigomez** [comment]
Thanks. I am going to experiment with it.
