### ISSUE TITLE
A test failure or `I.saveScreenshot('...', true)` causes browser window to shrink

### ISSUE THREAD

**Issue by apomortsev** [Codeception/CodeceptJS#1060]
#### What are you trying to achieve?

Run a test suite.

#### What do you get instead?

After each test failure, or every time `I.saveScreenshot('...', true)` is called, the browser window gets smaller, which in turn might cause additional failures due to some page elements ending up outside of the viewport boundaries.

I believe the problem is in `saveScreenShot()` code (WebDriverIO.js:1203), it seems there is a a workaround for a really small browser size `if (height < 100)` but it does not really solve the issue.
Setting `exports.config.helpers.WebDriverIO.fullPageScreenshots: false` in `codecept.conf.js` and not calling `I.saveScreenshot()` with `fullPage = true` stops the issue form happening.

```
    let { width, height } = await this.browser.execute(function () {
      return {
        height: document.body.scrollHeight,
        width: document.body.scrollWidth
      };
    }).then(res => res.value);

    if (height < 100) height = 500; // errors for very small height
    /* eslint-enable */

    await this.browser.windowHandleSize({ width, height });
```

### Details

* CodeceptJS version: 1.1.7
* NodeJS Version: 8.2.1
* Operating System: MacOS 10.12.6
* WebDriverIO
* Browser: Chrome 66.0.3359.139 (Official Build) (64-bit)

Thank you.

**Comment by LukoyanovE** [comment]
The same problem, when run tests in main macbook monitor (15,4" (2880 x 1800)).
After failure, chrome tries to resize. Shrink, then expand.

Moreover, 
when run on second monitor 1920*1200, chrome just resizes one time and became maximized (page height is about 5000px). After this chrome does not change size to previous.

Tried to modify Webdriverio. _before method to manualy change size to options.windowSize:
```

  async _before() {
    this.context = this.root;
    if (this.options.restart && !this.options.manualStart) return this._startBrowser();
    if (!this.isRunning && !this.options.manualStart) return this._startBrowser();
    
    if (this.options.windowSize === 'maximize') {
      await this.resizeWindow('maximize');
    } else if (this.options.windowSize && this.options.windowSize.indexOf('x') > 0) {
      const dimensions = this.options.windowSize.split('x');
      await this.resizeWindow(dimensions[0], dimensions[1]);
    }
    return this.browser;
  }
```

does not help. 
only "failed to change window state to normal, current state is maximized" error is given.

**Comment by DavertMik** [comment]
Looks like we need to disable fullSize option screenshots for investigation. I got this error while developing multi session testing and it wasted like 2 days of my time when I discovered that the issue was in browser stuck doing screenshots and not in new features.

**Comment by DavertMik** [comment]
This issue started to fail on both WebDriverIO and Protractor so I suspect that can be Selenium or ChromeDriver issue. So no estimates to fix it. Disabling this feature by default.
