### ISSUE TITLE
when clicking a link and it open in new tab how to go to new tab???

### ISSUE THREAD

**Issue by zeeshan774r** [Codeception/CodeceptJS#1076]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
`I.switchToNextTab()`

**Comment by zeeshan774r** [comment]
let linkLogin = await I.grabAttributeFrom('.smartstore-login', 'href')
  I.click('login')
  I.switchToNextTab()
  let url = await I.grabCurrentUrl()
  assert.equal(url, linkLogin)
when writing this tests, it failed and giving following error
JSHandles can be evaluated only in the context they were created!
