### ISSUE TITLE
Need logs to get printed for assertions 

### ISSUE THREAD

**Issue by vigneshwar-v** [Codeception/CodeceptJS#1091]
#### What are you trying to achieve?
Need logs to get printed for seeTextEquals / see or any other assertions
#### What do you get instead?
No logs.. getting logs only if it gets failed
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Sorry, I didn't get it. Each step is printed when executed in `--steps` mode
