### ISSUE TITLE
await is ignored when used with pause()

### ISSUE THREAD

**Issue by vigneshwar-v** [Codeception/CodeceptJS#1092]
#### What are you trying to achieve?
Debugging in asynchronous methods 
#### What do you get instead?
Could not debug since the statements are not executed after await statement and the execution ends. This happens only when pause() is used
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Sorry I didn't get it. 
Could you show me the code? And the actual output of execution

**Comment by vigneshwar-v** [comment]
I think its my problem... Sorry for bothering
