### ISSUE TITLE
Puppeteer / getPageTimeout: add timeouts as for Protactor

### ISSUE THREAD

**Issue by ko4ergins** [Codeception/CodeceptJS#1095]
### Description
When a user use amOnPage method 
And page loading more than 30 sec 
Then a user has an error "Navigation Timeout Exceeded: 30000ms exceeded"

Expected result: a user can edit the get page timeout
Actual result: a user can't edit the get page timeout

@DavertMik Please, add for puppeteer timeouts as in protractor. Thanks! 

* CodeceptJS version: v1.2.1
* Puppeteer version: v1.4.0

**Comment by ontytoom** [comment]
The purpose of this issue is to request `getPageTimeout()` function in the Puppeteer helper.

**Comment by DavertMik** [comment]
Should be solved with adding `waitForNavigation` function and the same config option. See release notes for 1.3

**Comment by ko4ergins** [comment]
Thank you so much!
