### ISSUE TITLE
How to press Down arrow key and then enter 

### ISSUE THREAD

**Issue by zeeshan774r** [Codeception/CodeceptJS#1097]
How to press down arrow key to select from dropdown coming and hit enter to select that one??? and also how to simultaneously pressing two different keys like SHIFT+TAB or anything lyk that

**Comment by LukoyanovE** [comment]
I see for webdriverio, but others should be the same.
You can try to use :
```
I.pressKey("ArrowDown");
I.pressKey("Enter");
```

If you wanna use a multiple key down, use array:
```
I.pressKey(["Shift", "Tab"]);
```


All normalized keys there: https://w3c.github.io/webdriver/#keyboard-actions

**Comment by LukoyanovE** [comment]
There are documentation on the site:
https://codecept.io/helpers/WebDriverIO/#presskey

If you use something other than WebDriverIO, see corresponding Helper's doc

**Comment by zeeshan774r** [comment]
Thanks for you stern help.Now its working fine

**Comment by poonamagashe** [comment]
Hi all, How can I press two keys at a time?
For example ctrl+v?

**Comment by zeeshan774r** [comment]
you can use it and pass keys as an array
I.pressKey(['Control','v']);

**Comment by poonamagashe** [comment]
My bad, I was writing Control all in small cases. Thanks for your help.

**Comment by poonamagashe** [comment]
Hello all, can anyone suggest me the way to store the content of clipboard in a variable in codeceptjs?

**Comment by aarunsharma** [comment]
Hi @LukoyanovE
I am not able to press the 'esc' key. I am using 
I.pressKey("esc");
