### ISSUE TITLE
DragAndDrop not working

### ISSUE THREAD

**Issue by vigneshwar-v** [Codeception/CodeceptJS#1098]
#### What are you trying to achieve?
using draganddrop method to drag a li element to position between other li elements
#### What do you get instead?
getting dropped at the same place
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```
I.dragAndDrop(locate('.dragSortList').find('li').withText('Mobile').find('div'),locate('.dragSortList').find('div').withText('heyya'));

I have multiple li with different texts and all li-s are draggable 
I am trying to reorder the list using draganddrop, but the element gets dropped at the same source
### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Sorry, this is not enough to reproduce your issue
If native drag and drop not working for you, try to simulate it with JavaScript

**Comment by vigneshwar-v** [comment]
its happening between different divs which are visually far, but if it happens to be in same <div>, the draganddrop is not working as expected
