### ISSUE TITLE
waitForText raises "Cannot read property 'then' of undefined"

### ISSUE THREAD

**Issue by antonioribeiro** [Codeception/CodeceptJS#11]
waitForVisible works fine, but raises this error
 
![codecept](https://cloud.githubusercontent.com/assets/3182864/11613873/ac355efc-9c17-11e5-9c3d-0ebddf19dd46.png)

**Comment by adrianblynch** [comment]
Re `waitForVisible`: Not a fix, but an answer as to why it's happening. Remove the `.` from `This is me.` - Does it start working for you?

`lib/helper/WebDriverIO.js:withStrictLocator()` passes text straight through and my guess is that any special characters cause issues.

You might get around it by modifying the text you search for. No ideal but hey...

**Comment by antonioribeiro** [comment]
@adrianblynch, it doesn't seems to be that, tried a different string, without special characters

![image](https://cloud.githubusercontent.com/assets/3182864/11628002/f26d2c74-9cd5-11e5-9eaf-631d7e0609c3.png)

**Comment by adrianblynch** [comment]
What about the spaces? I thought I tried a string with spaces but maybe it was just the `.`.

**Comment by antonioribeiro** [comment]
Nope. Not even with a single spaceless word.

**Comment by adrianblynch** [comment]
Strange.

If you switch to `I.see("This is me.")`, what happens?

**Comment by antonioribeiro** [comment]
Green.

```
Scenario('test login', (I) => {
    I.amOnPage('/auth/login');
    I.see('Entrar');
    I.fillField('email', 'acr@antoniocarlosribeiro.com');
    I.fillField('password', 'foda-se');
    I.click('Entrar');
    I.see('This is me.');
    I.see('Painel de Controle');
    I.waitForVisible('.widget', 10);
    I.see('OPERADORES');
    I.see('ATENDIMENTOS');
    I.see('MENSAGENS');
});
```

![image](https://cloud.githubusercontent.com/assets/3182864/11631898/811558ce-9ceb-11e5-951b-b7dffb3eb8fa.png)

**Comment by roadhump** [comment]
It looks like missing return in waitForText function here https://github.com/Codeception/CodeceptJS/blob/master/lib%2Fhelper%2FWebDriverIO.js#L502

**Comment by DavertMik** [comment]
Thanks for investigation and fix
