### ISSUE TITLE
Does not wait for Protractor to finish launching Selenium Server before running tests using Protractor's "local" driverProvider

### ISSUE THREAD

**Issue by DustinDSchultz** [Codeception/CodeceptJS#110]
Related issue: #99 -- I think these both have the same solution.

Here is the relevant part of my `config.json`:

```
"helpers": {
  "Protractor": {
    "url": "http://docker:8888/",
    "driver": "local",
    "browser": "firefox",
    "rootElement": "html",
    "scriptsTimeout": 30000,
    "seleniumServerJar": "./tests/utils/selenium-server-standalone-2.53.0.jar",
    "localSeleniumStandaloneOpts": {
      "port": 4444
    }
  }
}
```

Here is the output:

```
Starting selenium standalone server...

Login --
 Log In Successfully
 • I am on page "login"
 ✖ FAILED in undefinedms


-- FAILURES:

  1) Login Log In Successfully:
     Uncaught ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
```

If I have a standalone server already started when this runs I get output that looks like this:

```
Starting selenium standalone server...

Login --
 Log In Successfully
 • I am on page "login"
Selenium standalone server started at http://10.20.5.0:4444/wd/hub
 • I see element "body"
   Within div.log-in-form:
...
```

As you can see, the tests begin running before the server is finished starting. Protractor's driverProviders all return Promises from their `setupEnv` function, but the `_init` function of the `Protractor` class doesn't bother doing anything with it -- it just keeps on executing around it.

I don't mind coding it in, I'd just like to know if you guys were planning on handling driverProviders in a different way in the future.

**Comment by APshenkin** [comment]
Please test it in 1.0.0 and if the issue still exist, create a new issue
