### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined

### ISSUE THREAD

**Issue by zeeshan774r** [Codeception/CodeceptJS#1100]
some time test run smoothly and some time show this error...dont know why this happening
plz suggest why some time test case pass and some time give this error
I am running test with puppeter

**Comment by DavertMik** [comment]
We are running a workaround for this issue... 
It retries the last step when it happens for 3 times. 
Also, you may try to change config option `waitForNavigation` which comes in CodeceptJS 1.3 to wait for different strategies to wati for page to be loaded.

**Comment by timja-kainos** [comment]
@DavertMik any docs on waitForNavigation for codecept?
is it on puppeteer helper config or codecept?
i.e. this was what I found:
https://github.com/aslushnikov/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions
