### ISSUE TITLE
Error os.tmpdir() depreciated

### ISSUE THREAD

**Issue by xeonarno** [Codeception/CodeceptJS#1107]
#### What are you trying to achieve?
Just a launch of the Test (codeceptjs run)

#### What do you get instead?
(node:46229) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
codeceptjs run
```

### Details

* CodeceptJS version:1.2.1
* NodeJS Version:9.7.1
* Operating System:OSX Sierra 10.12.6
* Protractor || WebDriverIO || Nightmare version (if related) Protractor
* Configuration file:
```js
{
  "tests": "./e2e/*_test.js",
  "timeout": 10000,
  "output": "./reports",
  "helpers": {
    "Protractor": {
      "url": "https://myURL.io/",
      "driver": "hosted",
      "browser": "chrome",
      "rootElement": "body"
    }
  },
  "include": {
    "I": "./utils/steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "lessy-front"
}
```

**Comment by DavertMik** [comment]
This is a bug of Protractor. We can't fix it (

**Comment by xeonarno** [comment]
Ok I will create an issue in protractor repo
