### ISSUE TITLE
Can't use WebDriver grab methods - unexpected identifier

### ISSUE THREAD

**Issue by andrewhl** [Codeception/CodeceptJS#111]
I'm using Selenium and Firefox. I'm trying to use I.grabTextFrom or I.grabAttributeFrom, and I get the error:

``` bash
CodeceptJS v0.3.3
Test root is assumed to be /Users/andrew/code/myapp

Unexpected identifier

SyntaxError:
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/andrew/.nvm/versions/node/v5.1.1/lib/node_modules/codeceptjs/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/andrew/.nvm/versions/node/v5.1.1/lib/node_modules/codeceptjs/node_modules/mocha/lib/mocha.js:216:14)
```

I've defined an element in my dom, with an id 'test', and a value 'foo':

``` html
<div id="test">Foo</div>
```

And I try to grab the value:

``` javascript
    var test = yield I.grabTextFrom('#test');
```

This causes the above error. Not sure why.

**Comment by DavertMik** [comment]
Could you provide your test scenario? 
Stack trace doesn't seem to point to the scenario itself nor to any of codeceptjs files

**Comment by neil-s** [comment]
I am reproducing this same error.

```js
Feature('Hello');

Scenario('test something', (I) => {
	I.amOnPage('/');
	var title = yield I.grabTitle();
});
```

```json
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://www.google.com",
      "browser": "chrome"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "somename"
}
```

So simply going to Google and getting the title causes this issue. Removing the `grabTitle` line makes the error go away. Stacktrace is the same as OP.

```
Unexpected identifier

SyntaxError:
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\codeceptjs\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\codeceptjs\node_modules\mocha\lib\mocha.js:217:14)
```

Versions:
Codecept: 0.3.5
Node: 4.4.5
Windows: 10

**Comment by neil-s** [comment]
I think I may have found an underlying cause, unless this is an unrelated issue. I tried creating a custom helper to expose the WebDriverIO methods:

```js

'use strict';

class Wdio extends Helper {


  // add custom methods here
  // If you need to access other helpers
  // use: this.helpers['helperName']
	getTitle() {
		let client = this.helpers['WebDriverIO'].browser;
		return browser.getTitle();
	}
}

module.exports = Wdio;
```

Now, navigating to a page, pausing to enter the shell, and then entering `I.getTitle()` causes the following error:
```
 FAIL  browser is not defined
```

**Comment by neil-s** [comment]
@andrewhl , I've figured out the reason, at least for my instance of the bug, and it's entirely user error. When I RTFM, I realized that I wasn't using a generator function for the scenario. From the documentation:

> All actions starting with grab prefix are expected to return data. In order to synchronize this step with a scenario you should pause test execution with yield keyword of ES6. To make it work your test should be written inside a generator function (notice * in its definition):

```js
Scenario('use page title', function*(I) {
  // ...
  var password = yield I.grabTextFrom('#password');
  I.fillField('password', password);
});
```

Without it being a generator function, that yield keyword is nonsense to the JS engine, hence the unknown identifier error.

**Comment by rohitshetty** [comment]
The above solution works. May be this should go into the official documentations. The grabbing API's are little confusing for now. 
The above example should be good enough.

**Comment by APshenkin** [comment]
Closing due inactivity

**Comment by oztek22** [comment]
Thanks @neil-s 
I was doing the same mistake 😆
