### ISSUE TITLE
WebDriverIO commands wait longer than described timeout

### ISSUE THREAD

**Issue by LukoyanovE** [Codeception/CodeceptJS#1116]
#### What are you trying to achieve?
When step cannot be passed (there are no element for action on page, for example), Implicit timeouts should use timeout equal to described in codecept.json file.

#### What do you get instead?
When step waits it's failure, codeceptjs waits timeout greater than described, but proportional to the one

For example for `I.click("div.something_not_existing")`
waiting for described 3000 ~ 12 sec
for 4000 - ~16 sec 
for 5000 - ~20 sec

> Provide console output if related. Use `--verbose` mode for more details.

for timeout.implicit = 3000
```bash
Script capirs_main --
 should click
 • I am on page "/" ("1.597 sec")
 • I click "input.dz-hidden-input" ("12.151 sec")
 > Screenshot has been saved to /Users/e.lukoyanov/workbase/project/testing/Codeceptjs/should_attach.failed.png
 ✖ FAILED in 14277ms
```

for timeout.implicit = 4000
```bash
Script capirs_main --
 should click
 • I am on page "/" ("1.499 sec")
 • I click "input.dz-hidden-input" ("16.175 sec")
 > Screenshot has been saved to /Users/e.lukoyanov/workbase/project/testing/Codeceptjs/should_attach.failed.png
 ✖ FAILED in 18199ms
```

for timeout.implicit = 5000
```bash
Script --
 should click
 • I am on page "/" ("1.574 sec")
 • I click "input.dz-hidden-input" ("20.103 sec")
 > Screenshot has been saved to /Users/e.lukoyanov/workbase/project/testing/Codeceptjs/should_attach.failed.png
 ✖ FAILED in 22271ms
```

> Provide test source code if related

test.Spec.js
```js
"use strict";
Feature("Script");

Scenario("should click", (I) => {
  I.amOnPage("/");
  I.click("input.dz-hidden-input");
});
```

### Details

* CodeceptJS version: 1.1.8
* NodeJS Version: 8.9.1
* Operating System: mac high sierra 10.13.4
* WebDriverIO 
* Configuration file:

codecept.json
```
{
  "output": "../../../testing/Codeceptjs",
  "helpers": {
    "WebDriverIO": {
      "url": "https://formsviewertest.azurewebsites.net",
      "browser": "chrome",
      "windowSize": "maximize",
      "restart": "false",
      "timeouts": {
        "implicit": 5000
      },
      "waitForTimeout": 2000
    }
  },
  "tests": "../../../testing/Acceptance/*.Spec.js"
}
```

> P.S.

Something similar found for `attachFile` function. Other did not searched

**Comment by DavertMik** [comment]
Yeah, this is the reason you should not use implicit waits. 
Use smartWait instead, which actually enables implicit waits but only for reasonable cases. I.e. when the locator is specified and element is expected on the page: https://codecept.io/acceptance/#smartwait
