### ISSUE TITLE
Cannot find global module 'protractor/node_modules/selenium-webdriver'

### ISSUE THREAD

**Issue by yjaaidi** [Codeception/CodeceptJS#112]
CodeceptJS doesn't seem to be compatible with npm 3 as protractor's dependency selenium-webdriver will not be installed under "node_modules/protractor/node_modules/selenium-webdriver" but "node_modules/selenium-webdriver/" except if a selenium-webdriver is present in the package.json with a version mismatching the one expected by protractor.

Maybe we should simply require CodeceptJS's 'selenium-webdriver' at codeceptjs/lib/helper/Protractor.js:77

**Comment by DavertMik** [comment]
> CodeceptJS doesn't seem to be compatible with npm 3

yep, didn't have a chance to test

> Maybe we should simply require CodeceptJS's 'selenium-webdriver' at codeceptjs/lib/helper/Protractor.js:77

yes, this should be an option. The idea behind this was to use the same selenium-webdriver as protractor does, because it may be incompatible with some versions.

Thanks for the report, I will update locating of selenium-webdriver

**Comment by yjaaidi** [comment]
I understand.

Maybe we should contribute to protractor and make it export the webdriver
it's using.

Meanwhile, we could try to get it from
node_modules/protractor/node_modules/selenium_webdriver/ then fallback to
selenium_webdriver if it fails.

Thanks Michael !

**Comment by cuckoopt** [comment]
you can allways use `npm install --global-style` for a quick fix

**Comment by DavertMik** [comment]
Thanks. Fixed this with

```
    try {
      this.webdriver = requireg('protractor/node_modules/selenium-webdriver');
    } catch (e) {
      this.webdriver = requireg('selenium-webdriver');
    }
```
