### ISSUE TITLE
Different exception string thrown: 'no such alert'

### ISSUE THREAD

**Issue by czeraldg** [Codeception/CodeceptJS#1120]
https://github.com/Codeception/CodeceptJS/blob/620cb959231c50fc254e32cdcfbc99372daca3b7/lib/helper/Protractor.js#L1072

While trying to execute my tests, I encountered the following exception:
`   [1] Error | NoSuchAlertError: no such alert
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)
NoSuchAlertError: no such alert
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)`

Used selenium-standalone 2.40-x64-chromedriver.

Suggest to add `'no such alert'` to be anticipated in addition to `'no alert open'`.

**Comment by DavertMik** [comment]
Thanks. This was fixed in #1104 
Please wait for a release
