### ISSUE TITLE
switchTo returns Type error

### ISSUE THREAD

**Issue by keyclaim** [Codeception/CodeceptJS#114]
Hello! I did some simple test with CodeceptJS and WebdriverIO and got this error:

 Login test
 • I am on page "/"
 • I see in title "Welcome! | VK"
 • I fill field "#quick_email", "#####"
 • I fill field "#quick_pass", "####"
 • I click "#quick_login_button"
 ✖ FAILED in 8699ms

-- FAILURES:

  1) VK test Login test:
     I.switchTo is not a function

Does "switchTo" supported now?

**Comment by APshenkin** [comment]
`switchTo` is supported and works as expected. Closing due inactivity
