### ISSUE TITLE
Add option --exit-success

### ISSUE THREAD

**Issue by thiagodp** [Codeception/CodeceptJS#1142]
Make an option like `--exit-success` to force CodeceptJS to exit with `0`.

CodeceptJS returns `1` when a test fails. Using it as a NPM script, breaks the life-cycle after finishing:

Example:
```js
...
	"scripts": {
		"codeceptjs": "codeceptjs run --reporter mocha-multi --colors"
	},
...
```

Then:
```bash
npm run codeceptjs
```
and then when some test does not pass:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@1.0.0 codeceptjs: `codeceptjs run --reporter mocha-multi --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@1.0.0 codeceptjs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...-debug.log
```

So adding such option will allow to solve this problem like this:

```js
...
	"scripts": {
		"codeceptjs": "codeceptjs run --reporter mocha-multi --colors --exit-success"
	},
...
```
It will not interfere the life-cycle.

**Comment by DavertMik** [comment]
Very strange request. You can just add  or operator `||` to return true in case of failure

```
codeceptjs run || true
```

**Comment by thiagodp** [comment]
How to do
```bash
npm run codeceptjs -- test/mytest,js
```
???

**Comment by thiagodp** [comment]
@DavertMik `|| true` also does not work on Windows.

So, I would like to suggest reopening this Issue in order to solve it. Thx.
