### ISSUE TITLE
Codecept didn't see custom steps when execute bdd scenario

### ISSUE THREAD

**Issue by VladToporkov** [Codeception/CodeceptJS#1143]
#### What do you get instead?
I saw this error( I.checkLink is not a function).
But If I use simple test scenario codecept saw my step. 

> Provide console output if related. Use `--verbose` mode for more details.

  1) LawPage
       Check Small Paper @43 {"site":"'http://krsk.reg-port-rt.1glp.ru'"}:
     I.checkLink is not a function
  ypeError: I.checkLink is not a function
      at Then (step_definitions\steps.js:181:20)
      at runSteps (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\interfaces\gherkin.js:43:17)
      at Test (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\interfaces\gherkin.js:74:89)
      at Context.test.fn (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\scenario.js:76:14)
``bash
# paste output here
```

> Provide test source code if related
test scenario: 
Scenario: test @123
  Given Open google
  Then check link

Given('Open google', () => {
  // From "features\lawPage.feature" {"line":72,"column":7}
  I.amOnPage('https://www.google.ru/webhp?hl=ru&sa=X&ved=0ahUKEwjY7rWfrPjbAhUHFiwKHas5DCMQPAgD');
});

Then('check link', async () => {
  // From "features\lawPage.feature" {"line":73,"column":7}
  let elemCss =  '#gbw > div > div > div.gb_qe.gb_R.gb_Pg.gb_Fg > div:nth-child(2) > a' ;
  assert(await I.checkLink(elemCss)); 
  I.see('Google');
});


custom step: 
 checkLink: async function (elemCss) {

              let link  = await this.grabAttributeFrom({css:elemCss}, 'href');
              let response = await this.sendGetRequest(link);
              return response.statusCode === 200;
          
      }


### Details

* CodeceptJS version: 1.3.1
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Sorry for the delay. 
The reason is obvious. If you initialize I like `I = actor()` this will load only actor steps, without custom steps.
In this case you need to require custom_steps file:

```
const I = require('./custom_steps');
```
