### ISSUE TITLE
Toggle a boostrap-switch

### ISSUE THREAD

**Issue by cristian-sima** [Codeception/CodeceptJS#116]
Hi mates,

I have started to use this tool and I got to a problem:

I want to check a checkbox, but my checkbox is a [bootstrap-switch](http://www.bootstrap-switch.org/) one.

Any idea how to do it?

(I have tried with wrapperClass, click, toggle --> nothing)

**Comment by cristian-sima** [comment]
I got a workaround using this code:

```
  I.executeScript(() => {
    $("#login-remember-me").bootstrapSwitch("toggleState");
  });
```

Any other idea?

**Comment by ZZaphod** [comment]
If your id is "myId" for example, the following line works for me:
`I.click(".bootstrap-switch-id-myId div")`
I'm using angular-bootstrap-switch though. The behavior might be different.

**Comment by APshenkin** [comment]
Close due inactivity

**Comment by cristian-sima** [comment]
Yep. Not longer using JQuery
