### ISSUE TITLE
Extract semantic functions that find elements by text

### ISSUE THREAD

**Issue by denis-sokolov** [Codeception/CodeceptJS#117]
In the WebDriverIO helper there are awesome functions that build complex xpath selectors by text: [`findClickable`](https://github.com/Codeception/CodeceptJS/blob/5a74d1c645751a1f585f771449c287de7653d2e7/lib/helper/WebDriverIO.js#L941), [`findFields`](https://github.com/Codeception/CodeceptJS/blob/5a74d1c645751a1f585f771449c287de7653d2e7/lib/helper/WebDriverIO.js#L974), [`findCheckable`](https://github.com/Codeception/CodeceptJS/blob/5a74d1c645751a1f585f771449c287de7653d2e7/lib/helper/WebDriverIO.js#L1051), and others. Would you accept a PR that extracts these functions and exposes them to the outer world to use?

Implementation might vary from simply making them public static methods of the helper, to moving it into a stand-alone npm module.

**Comment by DavertMik** [comment]
Thanks for the suggestion!

> In the WebDriverIO helper there are awesome functions that build complex xpath selectors by text: findClickable, findFields, findCheckable, and others. Would you accept a PR that extracts these functions and exposes them to the outer world to use?

Actually they should not be used in tests but can be used in other helpers. So I'm ok to make them available but only to helpers, and not to I object. And I think yes, they could be `module.export`ed, and documentation updated with few words on how to use them.

**Comment by DavertMik** [comment]
As an alternative idea, is to have dash-prefixed method to find elements by their semantic, like we have for [`_locate`](https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/WebDriverIO.js#L272), we can have `_locateFields`, `_locateCheckboxes`, etc. Those methods will be available for use in custom helpers
