### ISSUE TITLE
CodeceptJS saucelabs configuration file example 

### ISSUE THREAD

**Issue by abgaryanharutyun** [Codeception/CodeceptJS#1186]
#### What are you trying to achieve?
I want to integrate `Codeceptjs`  with Saucelabs but I can't find any examples for that
#### What do you get instead?
I'm getting an error with web driver
> Provide console output if related. Use `--verbose` mode for more details.

```bash
Can't connect to WebDriver.
Error: Unexpected server error.

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
```

> Provide test source code if related

Tests is worked without Saucelabs with appium now I want to move to Saucelabs

### Details

* CodeceptJS version: 1.3.2 
* NodeJS Version: v8.5.0
* Operating System: MacOs
* Protractor || WebDriverIO || Nightmare version (if related): Im using Appium
* Configuration file:  i want this file example for sauselab

**Comment by diogowbrito** [comment]
@abgaryanharutyun I'm running into a similar problem with connecting Travis with Sauce Labs while using WebDriver IO. Have you been able to find a solution for this issue?

**Comment by puneet0191** [comment]
@diogowbrito @abgaryanharutyun try using https://www.npmjs.com/package/codeceptjs-saucehelper to connect to saucelabs and be able to publish test names and results. Let me know if you need more info on this.

**Comment by nilanjansiromani** [comment]
@puneet0191 Could you please share a sample configuration file.

**Comment by nilanjansiromani** [comment]
I keep getting the error :
```
Error: No matching helper found. Supported helpers: WebDriver/Appium/WebDriverIO
```

my config file looks like :
```
exports.config = {
  tests: "./*_test.js",
  output: "./output",
  helpers: {
    SauceHelper: {
      require: "codeceptjs-saucehelper",
      url: "http://localhost",
      user: "foobar",
      key: "adad"
    }
  },
  include: {
    I: "./steps_file.js"
  },
  bootstrap: null,
  mocha: {},
  name: "codecept-playground"
};

```

**Comment by puneet0191** [comment]
@nilanjansiromani you are missing Helper in your configuration, try adding WebdriverIO/Webdriver in the helper section, something like this: https://github.com/percona/pmm-qa/blob/master/codecept.json

**Comment by arifkhanaj** [comment]
Add following Appium helper to your Codeceptjs config file(I am doing it for Mobile App using real mobile devices in saucelabs test object):

```
Appium: {
            protocol: 'https',
            host: 'eu1.appium.testobject.com',
            // host: 'us1-manual.app.testobject.com', // your device is located in the US ? , then uncomment this line and remove the previous one.
            port: 443,
            path: '/wd/hub',
            app: 'sauce-storage: appname',
            capabilities: {
                testobject_api_key: '',
                platformName: 'Android',
                platformVersion: '9', // Optional
                deviceName: 'Samsung Galaxy S10', // Optional, if not specified then will pick up any device with the specified OS version
                name: 'Mobile App Test',
            }
        },

```
Following example was used for help:

https://wiki.saucelabs.com/display/DOCS/Examples+of+Appium+Test+Setups+for+Real+Device+Testing
