### ISSUE TITLE
problems with quickstart guide

### ISSUE THREAD

**Issue by acthp** [Codeception/CodeceptJS#119]
First, when asked the location of the tests, if user enters a directory, `codeceptjs gt` will fail with an obscure message. It's running a pattern match against `config.tests` and assuming a non-null result.

Second, running `codeceptjs run --steps` with the suggested first script results in this error:

```
  1) Foo test something:
     I.amOnPage is not a function
```

The `I` object is empty.

**Comment by acthp** [comment]
So, one missing step in the quickstart is npm install of webdriverio. Perhaps if it's installed the generated config would include the webdriver config? If not, then quickstart also needs directions on adding the webdriver config to ```codecept.json```.

After resolving these two issues, it's working for me.

**Comment by schmkr** [comment]
@acthp Can you post your config for webdriver? I'm running into the same issue.

**Comment by acthp** [comment]
@schmkr I could never get codecept to work reliably, switched to chimp, and then wdio. The promise / generator design of codecept was impossible for me to debug, and never quite worked.
