### ISSUE TITLE
Appium driver swipe not worked

### ISSUE THREAD

**Issue by abgaryanharutyun** [Codeception/CodeceptJS#1190]
#### I'm trying to do swipe but doesn't work

> Provide test source code if related

```js
 I.swipeDown('//XCUIElementTypeOther[@name="SECURITY"]');
```

### Details

* CodeceptJS version: 1.3 
* NodeJS Version: v8.5.0
* Operating System: MacOs
* Protractor || WebDriverIO || Nightmare version (if related) Appium
* Configuration file: 

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Appium": {
      "platform": "iOS",
      "restart": false,
      "desiredCapabilities": {
        "deviceName": "iPhone X",
        "app": "app.zip",
        "automationName": "XCUITest"
      }
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "aaaa"
}
```

**Comment by LukoyanovE** [comment]
How about swipe instead of swipeDown ?

**Comment by ichanmrg** [comment]
This is frequently happening. I do touchPerform as a workaround but it is not as elegant.
