### ISSUE TITLE
login before every test

### ISSUE THREAD

**Issue by zeeshan774r** [Codeception/CodeceptJS#1192]
how to avoid login before every test..I have 20 **Scenario** in my test file ..and I have written login function in **Before**  so every time login happens..is there any method we just login once and after that all test run...I am runnig codecept puppeeteer..

Feature('Customers Details')

Before((I) => {
  I.login()
  I.amOnPage('/operations/customers')
  I.see('Customers')
  I.waitForElement('.table-container', 10)
  I.resizeWindow(1300, 500)
  I.waitForElement('.table-container', 10)
  I.click('.table-container .table-row:nth-child(2) .customer-table-name .customer-name')
  I.waitForElement('.customerDetails')
})

Scenario('Initial view', (I) => {
  I.waitForElement('.tabWithCustomerCard', 5)
  I.see('Total Orders')
  I.see('Purchase worth')
  I.see('Joined On')
  I.see('Last Purchase')
})

Scenario('Add valid phone number', (I) => {
  I.waitForElement('.tabWithCustomerCard .tab-container .tab', 5)
  I.click('.tabs .tab:nth-child(3)')
  I.click('Add Phone Number')
  I.seeElement('.editPopup')
  I.fillField('phone', '+919988776655')
  I.click('Submit')
  I.waitForElement('.dialogPopup', 10)
  I.dontSeeElement('.editPopup')
  I.see('Phone number added successfully')
  I.click('OK')
  I.dontSeeElement('.dialogPopup')
})

**Comment by LosEagle** [comment]
I named my login test like "1-login.test.js" so that it's always on top of all tests and runs first and in codecept.json set
> "restart": false,
> "keepCookies": true,
Which prevents automated browser from restarting and keeps cookies between all tests. This way I only login once through the login test and run other tests in same browser session.

**Comment by PeterNgTr** [comment]
You can try
`
BeforeSuite(async (I) => {
    I.amOnPage('/login');
    common_steps.login();
});
`

**Comment by GSasu** [comment]
@zeeshan774r you can try setting your puppeteer config options "restart": from false to true. This will keep your browser open so you don't need to wait for it to restart everytime. This way, your before hook will log you in once and stay that way unless you log out specifically.

**Comment by GSasu** [comment]
@zeeshan774r if you want to keep your restart set to false, you can set keepBrowserState to true and keepCookies to true to maintain logged in state, see [this](https://codecept.io/helpers/WebDriverIO/)

**Comment by PeterNgTr** [comment]
This plugin is on air -> https://codecept.io/plugins/#autologin
