### ISSUE TITLE
[New Feature Request] Make steps more easier to follow in the console output

### ISSUE THREAD

**Issue by vensa-albertgao** [Codeception/CodeceptJS#1197]
Thanks for the beautiful lib! Love it!

#### What are you trying to achieve?
See this as an output:
`I fill field "month", "10"`

#### What do you get instead?
I saw this in the output:
`I fill field "//*[@id="date-input"]/div[2]/input", "10"`

It works, but figuring out which line causes the error is quite hard, an alias could be a big help here.

#### What is the code?
```js
const monthXPath = "//*[@id="date-input"]/div[2]/input";

I.fillField(
  "month",
  monthXPath,
  "10",
);
```
An extra first parameter for methods like `I.fillField` as the alias to display in the console will make things much more clear.

### Details

* CodeceptJS version: 1.3.3
* NodeJS Version: 8.11.3
* Operating System:
* Configuration file:

```js
{
  "tests": "./tests/e2e/**/*_test.js",
  "timeout": 10000,
  "output": "./tests/e2e/output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "chrome",
      "smartWait": 5000
    }
  },
  "include": {
    "I": "./tests/e2e/steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "storm-ui"
}
```

**Comment by DavertMik** [comment]
Hey, this is already there! 

You can use locator object https://codecept.io/locators/#locator-builder

```js
I.fillField(locate("//*[@id="date-input"]/div[2]/input").as('month'), 10);
```
This will be printed as `month`
