### ISSUE TITLE
Wrong 'require' for custom helpers

### ISSUE THREAD

**Issue by roadhump** [Codeception/CodeceptJS#12]
It seems like there is a bug in code which allows to use custom helpers. I suppose this config `codecept.json` was planned to work nice
```json
{
  "helpers": {
    "MyCustomWebdriver": {
        "require": "my-custom-webdriver"
     }
  }
}
```
but now it seeks `require` key in main `helpers` config.

Also, it would be nice if `require` path here is resolved relatively to `codecept.json` location, like
```json
{
  "helpers": {
    "MyCustomWebdriver": {
        "require": "./lib/my-custom-webdriver"
     }
  }
}
```
because now it will work only with 
```json
{
  "helpers": {
    "MyCustomWebdriver": {
        "require": "./../../../lib/my-custom-webdriver"
     }
  }
}
```

I am ready to make PR, but I wonder why there are no tests here, are they not written yet, because I feel wrong to write PR without tests :smiley:

**Comment by DavertMik** [comment]
Thanks, actually looks I did a fix for this issue while writing tests :)

Same as #10 

Thanks, I'm pushing my tests and fixes right now

**Comment by DavertMik** [comment]
https://github.com/Codeception/CodeceptJS/blob/master/test/unit/container_test.js#L69
