### ISSUE TITLE
Testing complex element, how to get it's state?

### ISSUE THREAD

**Issue by Akxe** [Codeception/CodeceptJS#1204]
#### What are you trying to achieve?
I would like to test our video player integration. But I am strugeling, due inability to find any documentation. For example how to get Element. 

I need the element to be able to access to element, I need to test, that pausing really paused the video etc...

#### What do you get instead?
Headache... I have on idea where to look. I tried to make a helper:

```js
'use strict';
//@ts-check

class VideoHelper extends Helper {
	async _getVideo() {
		return this.helpers.Puppeteer._locate(`.videojs video`);
	}

	async seeVideoIsPaused() {
		const video = await this._getVideo();
		console.log(video);
	}
}

module.exports = VideoHelper;
```

### Details

* CodeceptJS version: 1.3.3
* NodeJS Version: 9.11.1
* Operating System: Win / Linux
* Puppeteer (using original chrome, but chromium ain't any better)
* Configuration file:

```js
# paste suite config here
```

PS: class `Helper` don't have any definition, this could be possibly improved.

**Comment by LukoyanovE** [comment]
Can you give page, for testing on it?

Maybe you have error on _getVideo method,
You do not return result of _locate, only _locate itself.

Maybe you should try to use await before return ```return await this.helpers.Puppeteer._locate(`.videojs video`);```

see https://codecept.io/helpers/Puppeteer/#_locate

**Comment by Akxe** [comment]
M bad this can be closed, but I still think class `Helper` need some type definition.

**Comment by LukoyanovE** [comment]
@Akxe , did you tried [this](https://codecept.io/commands/#typescript-definitions)?
Or there are no Helpers definition in this generator ?

**Comment by Akxe** [comment]
Well maybe not, I got something like an element, but for some reason calling `addEventListener` on it is invalid. Any thoughts? I need to seek and resolve only when seek is truly done.

**Comment by Akxe** [comment]
@LukoyanovE I have done this, it will produce wrong types (it gives `string` type for everything, regales of JSDoc). Also Helper isn't defined there.

**Comment by LukoyanovE** [comment]
[This doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselector-1) says that Puppeteer return array of [ElementHandle](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-elementhandle)

Did not worked with puppeteer, maybe you should call [getProperties](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlegetproperties) on element in returned array of elements and `console.log` all it's methods/properties to find out which method it has

**Comment by Akxe** [comment]
Helper... just write one on your own...

**Comment by LukoyanovE** [comment]
@Akxe, you always can commit your fixes
