### ISSUE TITLE
Can I change the viewport size same to window inner size with Puppeteer helper?

### ISSUE THREAD

**Issue by junguchina** [Codeception/CodeceptJS#1209]
### Details
* CodeceptJS version:1.3.3
* NodeJS Version:10.8.0
* Operating System: Macos
* Protractor || WebDriverIO || Nightmare version (if related): Puppeteer 1.8.0
* Configuration file:

```js
  helpers: {
    Puppeteer: {
      url: cf.testDomain,
      show: true,
      restart: false,
      keepCookies: true,
      windowSize: '1920x1080',
      chrome: {
        defaultViewport: {
          width: 1920,
          height: 1080
        },
        handleSIGINT: false,
      },
    },
  }
```
In the `codecept.conf.js` file, I set `windowSize` and `defaultViewport` with the same value, but when I run test test suite:
* The viewport size of chrome is still 800x600.
* The window inner size of the webpage is 1920x1080.
This is not convenient to debug by viewport.
![jietu20180917-175801-hd](https://user-images.githubusercontent.com/14007943/45616949-6e6ef080-baa3-11e8-8a4e-a513467e5109.gif)

**Comment by junguchina** [comment]
You can refer the issue from puppeteer [1183](https://github.com/GoogleChrome/puppeteer/issues/1183).

**Comment by junguchina** [comment]
@APshenkin and @DavertMik Do you have any idea?

**Comment by PeterNgTr** [comment]
```
   Puppeteer: {
      url: 'https://app-develop.mcmakler.com',
      restart: false,
      keepBrowserState: true,
      keepCookies: true,
      fullPageScreenshots: true,
      show: true,
      windowSize: '1440x700',
      waitForNavigation: ['networkidle2', 'domcontentloaded'],
      waitForAction: 1000,
      chrome: {
        args: ['--no-sandbox', '--window-size=1440,700'],
      },
    },
```
This works fine for me.

**Comment by junguchina** [comment]
@PeterNgTr Thanks, I will try it later.

**Comment by markjackson02** [comment]
I am experiencing same issue as OP:  very small viewport (~800x600) and very large inner webpage size (~1920x1080). Setting these value has no effect when Chromium launches.

 ```
helpers: {
        Puppeteer: {
            url: codeceptURL,
            windowSize: '1280x960',
            chrome: {
                args: ['--no-sandbox', '--window-size=1280,960'],
                defaultViewport: {
                     width: 1280,
                     height: 960
                }
            }
        }
}
```

Codecept 2.1.2
Node 10.15.0

**Comment by junguchina** [comment]
@markjackson02 You can refer the below comment:
https://github.com/GoogleChrome/puppeteer/issues/1183#issuecomment-499722320
So you can actually disable viewport emulation with `defaultViewport: null` option.
You can try this in your local:
```
helpers: {
       Puppeteer: {
           url: codeceptURL,
           windowSize: '1280x960',
           chrome: {
               args: ['--no-sandbox', '--window-size=1280,960'],
               defaultViewport: null
           }
       }
}
```
or remove the option `defaultViewport` like this:
```
helpers: {
       Puppeteer: {
           url: codeceptURL,
           windowSize: '1280x960',
           chrome: {
               args: ['--no-sandbox', '--window-size=1280,960'],
           }
       }
}
```
I think it will work well.

**Comment by mystic-poet** [comment]
Any solution to this?
I tried updating the codecept.conf.js file, but it did not help.
