### ISSUE TITLE
Click for link is not work

### ISSUE THREAD

**Issue by celalettinc** [Codeception/CodeceptJS#1217]
#### What are you trying to achieve?
In page, there is a table and more links in each cell. 
I.executeScript("let linkFind = document.links;" +
        "let linkNb = linkFind.length;" +
        "for(let i=0;i<linkNb;i++){" +
        "if('Paper' === linkFind[i].parentNode.nextSibling.childNodes[2].innerText){" +
        "linkFind[i].click;}}");

#### What do you get instead?
Firtsly, i find all links and finding related links then click on it, but not working, nothing happen, script is passing the other script and not give any error.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 1.3.3
* NodeJS Version: 8.10.0
* Operating System: windows 10
* Protractor || WebDriverIO || Nightmare version (if related): 
* Configuration file: 

```js
{
  "output": "./target/errorscreens",
  "helpers": {
    "Puppeteer": {
      "url": "http://blabla",
      "waitForNavigation": "load",
      "windowSize": "1367x960",
      "show": true,
      "waitForAction": 300
    }
  },
  "include": {
    "I": "./steps_file.js",
    "recordOrder": "./pages/RecordOrderPage.js"   
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "target/testresult"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {},
  "tests": "./tests/*/*/*.js",
  "timeout": 10000,
  "page load": 3000,
  "name": "CodeceptJS"
}
```
My tests run on Chrome

**Comment by LukoyanovE** [comment]
`click` is a function, to execute it, You should use call by adding round brackets `click()`

```let linkFind = document.links;
let linkNb = linkFind.length;
for (let i = 0; i < linkNb; i++) {
  if ("Paper" === linkFind[i].parentNode.nextSibling.childNodes[2].innerText) {
    linkFind[i].click();
  }
}
```

PS your script is overloaded, use `map` and `foreach` for simplifing

```let linkFind = document.links;
linkFind
  .map(link => "Paper" === link.parentNode.nextSibling.childNodes[2].innerText)
  .foreach(link => link.click());
```

**Comment by celalettinc** [comment]
Thanks, I updated my script as your referring, now it is working.
