### ISSUE TITLE
CodeceptJS request interception

### ISSUE THREAD

**Issue by jordiponsllaurado** [Codeception/CodeceptJS#1226]
#### What are you trying to achieve?
Enable request interception using CodeceptJS with puppeteer
https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-pagesetrequestinterceptionvalue

#### What do you get instead?
I don't see how it could be done using codeceptJS

### Details

* CodeceptJS version: 1.3.3
* NodeJS Version:
* Operating System: macOS Sierra
* Protractor || WebDriverIO || Nightmare version (if related): Puppeteer "1.8.0"

**Comment by mralexho** [comment]
Have you tried setting -

```
  "helpers": {
    "Puppeteer": {
      "url": "http://localhost,
      "waitForNavigation": [ "domcontentloaded", "networkidle0" ],
      "setRequestInterception": true,
      "chrome": {
        "args": [
          "--no-sandbox",
          "--disable-setuid-sandbox"
        ]
      }
    }
  },
```

**Comment by jordiponsllaurado** [comment]
I've realised I had an error in my helper so there is no need to setup `setRequestInterception` to true. 

Thanks
