### ISSUE TITLE
how to add a method

### ISSUE THREAD

**Issue by acthp** [Codeception/CodeceptJS#123]
Trying to do a 'hello world' method that waits on a promise, but am getting nowhere. It looks like helper methods return promises, so I'm trying just returning a promise that is passed in.

In the helper file, I define a method like

```javascript
  waitForPromise(p) {
	  return p;
  }
```

and in a test case, invoke it like so:

```
Scenario.only('test promise.', function*(I) {
	var resolve;
	var x = yield I.waitForPromise(new Promise(r => resolve = r));
	console.log('x is ', x);
	I.amOnPage('/');
});
```

... expecting it will hang, waiting on the promise to resolve, but instead it exits before the console.log call.

Anyone have a clue?

**Comment by DavertMik** [comment]
Not sure what might be wrong. Let me try it

**Comment by acthp** [comment]
Got it working. I believe the problem is there are no events scheduled, and so node exits. Further, if you use ```setTimeout``` to resolve the promise, but put it after the ```yield```, the same problem occurs. ```yield``` eliminates the linear flow of js, so you have to think about where in the block you lose the cpu.

Putting the setTimeout before the yield, it works as expected.

**Comment by michahell** [comment]
@acthp could you please elaborate with a modified example? not entirely clear what you did in the end.
