### ISSUE TITLE
Front end ide like testcafe

### ISSUE THREAD

**Issue by technoartista** [Codeception/CodeceptJS#1235]
#### What are you trying to achieve?
https://testcafe-studio.devexpress.com

Easy to use ide

#### What do you get instead?

Manual code writing

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Yes, we have it: https://easytesting.io
Stay tuned!
