### ISSUE TITLE
How can i upload the file using codeceptJS

### ISSUE THREAD

**Issue by dwnavatha** [Codeception/CodeceptJS#1240]
I want to automate a functionality where I can upload a document and download a document.

I found no option.

Please let me know if some function is there to do same?

**Comment by GSasu** [comment]
Hi @dwnavatha, I would suggest looking at https://codecept.io/helpers/WebDriverIO/#attachfile, this should solve your need

**Comment by elukoyanov** [comment]
Use `attachFile` method.
