### ISSUE TITLE
calling function defined in steps_file gives an '... not a function' error

### ISSUE THREAD

**Issue by celalettinc** [Codeception/CodeceptJS#1242]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 1.3.3
* NodeJS Version: 8.10.0
* Operating System: windows 10
* Protractor || WebDriverIO || Nightmare version (if related) : Puppeteer
* Configuration file:
{
  "output": "./target/errorscreens",
  "helpers": {
    "Puppeteer": {
      "url": "blabla",
      "waitForNavigation": "load",
      "windowSize": "1920x1080",
      "show": true,
      "waitForAction": 300
    }
  },
  "include": {
    "I": "./steps_file.js",    
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "target/testsonuclari"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {},
  "tests": "./tests/**/*.js",
  "timeout": 10000,
  "page load": 3000,
  "name": "CODECEPTJS"
}
```js
# paste suite config here
```
I have two js file. In steps_file.js I defined function like
'use strict';
// in this file you can append custom step methods to 'I' object
module.exports = function () {
    return actor({
        // Define custom steps here, use 'this' to access default methods of I.
        // It is recommended to place a general 'login' function here.         
        dropdownInputChoose: function (lbl, text) {
            this.click({xpath: "//label[contains(.,'" + lbl + "')]/following::div[@role='button'][1]"});
            this.fillField({xpath: "//label[contains(.,'" + lbl + "')]/following::div[1]//input"}, text);
            this.pressKey('Enter');
        }
   });
};
and the other file i export the steps_file function like;
const I = actor();
const pg = require('./steps_file');
module.exports = {
  pg.dropdownInputChoose(lbl,text);
};
when running test the system gives an pg.dropdownInputChoose is not a function.
How can i solve this problem?

**Comment by xMutaGenx** [comment]
In your test file (I assume the second one is a test file?) you don't need to require anything, it's already handled by the codeceptjs configuration file, all you would need to do is call `I.dropdownInputChoose(mylbl, mytext);`

P.S. I'd suggest trying to use css selectors rather than xpath...

**Comment by celalettinc** [comment]
In fact, we have 3 files. One of them is steps_file.js, second one is test.js file and third one is page.js file. As you said, in test file there isn't any problem but in page file even if we define require function when running test, it gives an not a function error

**Comment by GSasu** [comment]
@celalettinc it is the way you call your ```dropdownInputChoose```. In your test you call it using the require constant name ```pg```. Custom steps written inside an actor instance such as your need to be called using ```I``` such as ```I.dropdownInputChoose(mylbl, mytext);``` just as @xMutaGenx mentioned.

**Comment by celalettinc** [comment]
We solved this problem by writing custom_helper script file that is included codecept.json. So now it's  working. Thanks to everybody.
