### ISSUE TITLE
unable to run allure on codeceptjs

### ISSUE THREAD

**Issue by vitaly87** [Codeception/CodeceptJS#1254]
#### What are you trying to achieve?
I am running  codeceptjs run --plugins allure
added plugins attribute on codecept.json 

#### What do you get instead?
error: unknown option `--plugins'

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
error: unknown option `--plugins'

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: codeceptjs@1.4.3
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related) WebDriverIO 
* Configuration file:

```js
# paste suite config here
```

**Comment by PeterNgTr** [comment]
Are you sure you're using the updated CodeceptJS version?

**Comment by vitaly87** [comment]
"codeceptjs": "^1.3.2",

**Comment by PeterNgTr** [comment]
okay, if you put like that in your package.json, it would not guarantee you're using the latest version. Starting from 1.4.0, allure is introduced

**Comment by xMutaGenx** [comment]
As Peter said, you might not be using the latest version, you can double-check if you are, by looking into your generated `package-lock.json` file or in `node_modules/codeceptjs/package.json` file.

**Comment by vitaly87** [comment]
10x! it was installed -g and I was looking on local path
