### ISSUE TITLE
[Enhancement] Introduce run-multiple into CODECEPT_ARGS in Docker-Compose

### ISSUE THREAD

**Issue by kinlu** [Codeception/CodeceptJS#1264]
#### What are you trying to achieve?

Currently, the arguments placed in ```CODECEPT_ARGS``` is only attached to the command ```codeceptjs run```.  
```
environment:
      - CODECEPT_ARGS=--debug
```
It would be great to have some way to run ```codeceptjs run-multiple``` to do parallel testing with docker with Docker-Compose.

**Comment by kinlu** [comment]
I would suggest make "-multiple" as a separate argument, like "run -multiple".

**Comment by DavertMik** [comment]
I would not run multiple inside one container. 
I think it's better to have multiple containers for that.

**Comment by DavertMik** [comment]
But If you implement it I will accept such PR

**Comment by PeterNgTr** [comment]
@kinlu @DavertMik Implemented it here https://github.com/Codeception/CodeceptJS/pull/1285
