### ISSUE TITLE
Screenshot on fail does not include additional sessions

### ISSUE THREAD

**Issue by GerroDen** [Codeception/CodeceptJS#1266]
#### I only get a screenshot of the main session and none of the additional.

> Feature with failing test inside a session:
```js
Feature("Screenshots on fail in session");

Scenario("Failing in session", (I) => {
	session("new session", () => {
		I.amOnPage('http://google.com');
		I.dontSeeInCurrentUrl('http://google.com');
	});
});
```

### Details

* CodeceptJS version: 1.4.3
* NodeJS Version: v10.12.0
* Operating System: Ubuntu 16.04
* Puppeteer: 1.9.0

**Comment by koushikmohan1996** [comment]
Fix is merged
