### ISSUE TITLE
Problem when using arrow functions callbacks with no parentheses syntax 

### ISSUE THREAD

**Issue by ghost** [Codeception/CodeceptJS#127]
If I use this syntax (no parentheses surrounding the 'I' object)

``` javascript
Scenario('test if the welcome is shown', I => {
  I.amOnPage('/');
  I.see('Hello');
});
```

When using the 'SeleniumWebdriver' plugin the tests simply don't run, they get stucked on line that shows the first Feature's name. No errror is shown.

When using the 'WebDriverIO' plugin the tests run, but I got an 'Object of type '/' is not defined in container' error.

If I surround the 'I' object with parenthesis everything run just fine.

**Comment by GA1** [comment]
Try to use parentheses around `I`, like `(I)`. We had to stop use a naked `I` for other reason. I hope it solves it.
