### ISSUE TITLE
No such Session when running 200+ scripts

### ISSUE THREAD

**Issue by dlopespg** [Codeception/CodeceptJS#1280]
#### What are you trying to achieve?
Run several scripts at a time using mochawesome as a report tool

#### What do you get instead?
Script starts fine but after some time, I get this error message:

Error: no such session (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.2.9200 x86_64)

Error: Promise was rejected with the following reason: no such session (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.2.9200 x86_64)

After this error no more scripts work and all of them return the same error.

Problem allways start when a one test fail, then all the next tests fail with the "no such session" problem..

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Mochowesome report image with the error

```
![image](https://user-images.githubusercontent.com/34516628/47380180-39257600-d6d3-11e8-861c-93f9d2d5c3ac.png)

![image](https://user-images.githubusercontent.com/34516628/47380210-49d5ec00-d6d3-11e8-9bed-fea2e353f18b.png)

> Provide test source code if related

The only thing different from the default codecept engine is a hook to add the captured immage to mochawesome report.
Here is the code of the hook.
```js
'use strict';
var event = require('codeceptjs').event;
const addContext = require('mochawesome/addContext');

module.exports = function() {
  event.dispatcher.on(event.test.failed, function (test, error) {  
    var testTitle = test.title
    testTitle = testTitle.replace(/ /g, '_');
    addContext( test.ctx, './'+testTitle+'.failed.png')
  });
}
```

### Details

* CodeceptJS version: v1.4.2
* NodeJS Version:v8.11.4
* Operating System:Windows server 2012
* WebDriverIO 4.13.2
* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "chrome",
      "windowSize": "maximize",
      "restart": false,
      "keepBrowserState": true
    },
    "TestHelper": {
      "require": "./testhelper_helper.js"
    }
  },
  "include": {
    "I": "./steps_file.js",
    "cadastros": "./cadastros"
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "output",
      "uniqueScreenshotNames": "true"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [
    "/hook.js"
  ],
  "gherkin": {},
  "tests": "./*/*_test.js",
  "timeout": 10000,
  "name": "sts"
}
```

**Comment by LukoyanovE** [comment]
Is it work for "restart: true"?

I saw some time ago one problem with running hooks with "restart: false"

**Comment by dlopespg** [comment]
I was using restart true a while ago, the same problem was happening, with restart false it seems to me a little more stable, but i could not find what cause this issue.

**Comment by dlopespg** [comment]
Investigating I could narrow down the problem.
The thing is that I have a script that change tabs some times.

```
Scenario('Validate evaluation 1', (I) => {
    I.waitForVisible(I.translate('LBL_STEP_ASSESSMENT',30));
    I.click(I.translate('LBL_STEP_ASSESSMENT'));
    I.switchToNextTab();
    I.waitForVisible('#areaQuestao',30);
    I.closeCurrentTab();
});
```

If this line fails 
```
    I.waitForVisible('#areaQuestao',30);
```
The script lose the current session and is not able to continue.
Is there any way to change to the default browser session when starting a test?

Thank you for everyone in advance.

**Comment by LukoyanovE** [comment]
It's look like, second tab is not opened on click, then closeCurrentTab closes current one and all browser.

Could you share `translate` method's code?

**Comment by LukoyanovE** [comment]
Maybe, you should wait for `grabNumberOfOpenTabs` => 1 before `switchToNextTab `

**Comment by dlopespg** [comment]
Translate only simplfy the click for a default regurar expression.
```
clickTranslate(lbl){
            this.click('//*[@translate="'+lbl+'"]');
        },
```

I will certainly implement a validation to check the number of open tabs.

Thank you @LukoyanovE

**Comment by LukoyanovE** [comment]
@dlopespg, is there is any progress?
Did you add tabs number check? And how it affected your suite?

**Comment by dlopespg** [comment]
Hello @LukoyanovE  created a test to check the number of open tabs and leave only the main tab open.

`
Scenario('Close open tabs', async (I) => {
    let tabs = await I.grabNumberOfOpenTabs()
    if (tabs >1) {
        while (tabs >= 2) {
            I.closeCurrentTab();
            tabs = await I.grabNumberOfOpenTabs();
            if (tabs >1) {
                I.switchToNextTab();
            }
        }
    }
});
`
