### ISSUE TITLE
Cannot debug with Visual Studio Code

### ISSUE THREAD

**Issue by elranu** [Codeception/CodeceptJS#1295]
#### What are you trying to achieve?
I'm trying to debug with VS Code as it says on: https://codecept.io/advanced/#debug
#### What do you get instead?
I get: "setting the outFiles attribute might help":

![vscode](https://user-images.githubusercontent.com/873616/47752852-672b2d00-dc74-11e8-8163-225d15a7d98f.PNG)

### Details

* CodeceptJS version: 1.4.4
* NodeJS Version: 9.5.0
* Operating System: Win 10
* Puppeteer 
* Configuration file:

```
{
    "tests": "src/*-tests.js",
    "timeout": 10000,
    "output": "./output",
    "helpers": {
        "Puppeteer": {
            "url": "http://localhost:8080/",
            "show": true
        }
    },
    "include": {
        "I": "./steps_file.js"
    },
    "bootstrap": false,
    "mocha": {},
    "name": "BTRE2ETests"
}
```

**Comment by PeterNgTr** [comment]
I guess you could try with 
`${workspaceFolder}/node_modules//codeceptjs/bin/codecept.js`

**Comment by elranu** [comment]
yes, thanks is working. I have modified to:
```
         {
            "type": "node",
            "request": "launch",
            "name": "codeceptjs",
            "args": ["run"],
            "program": "${workspaceFolder}/node_modules/codeceptjs/bin/codecept.js"
          }
```
