### ISSUE TITLE
run-multiple, retry, and only, don't fully work together

### ISSUE THREAD

**Issue by xMutaGenx** [Codeception/CodeceptJS#1299]
#### What are you trying to achieve?

Trying to run a single test with `run-multiple`, on a single chrome browser just to validate the functionality of `retries` and `only`.

#### What do you get instead?

There are multiple issues here:
1. `retry` and `only` don't mix together as it seems like the test doesn't actually get retried multiple times, if you only have `retry` the test will get retried multiple times ref other issue raised: #1256 
2. We're also using mochawesome reporter with unique screenshots, when both `rety` and `only` are set, the additional context where the screenshot would be attached is not there (even though the screenshot is taken)

> Provide test source code if related

```js
Feature('Failing').retry(3);

Scenario.only('Failing test @live @desktop', (I) => {

    I.amOnPage('/');
    I.see('this is going to fail');

});
```

### Details

* CodeceptJS version: 1.4.4
* NodeJS Version: 8.9.1
* Operating System: OSX
* WebDriverIO: 4.14.0

Basic example config file

**Comment by PeterNgTr** [comment]
Point 2 -> I think this is happening when not using either retry or only. I make a PR here to fix this https://github.com/Codeception/CodeceptJS/pull/1303
