### ISSUE TITLE
Check AJAX/Javascript requests?

### ISSUE THREAD

**Issue by BlaM** [Codeception/CodeceptJS#13]
Is there a way to check invisible things going on on the page? 

For example if I have a webpage that sends a tracking pixel request (not adding the <img> to the DOM) / AJAX request can I run checks on the requested URL?

If not, are you thinking about adding that as a feature?

**Comment by DavertMik** [comment]
Nothing like that is ready yet. Can you suggest how this feature may look like?

**Comment by stanjer** [comment]
@BlaM can you check it looking into overall html or via js?

**Comment by BlaM** [comment]
One note in advance: I'm not yet using CodeceptJS, so anything I say now may not fit into the CodeceptJS mindset. So far we're still investigating which tool to use for our usecase.

@stanjer In my case I can find the image tag in a JavaScript object but not in the page's html code. 

    window.x = new Image();
    window.x.src = 'http://placehold.it/350x150';

So: Yes.

That would not work however if the page had AJAXed home to the server.

@DavertMik I have never used Selenium so I don't know if there is something like PhantomJS' [onResourceRequested](http://phantomjs.org/api/webpage/handler/on-resource-requested.html). CodedeptJS would have to keep track of outgoing requests with that.

Maybe something like this?

    I.startMonitoringWebRequests();
    I.click(this.submitButton);
    I.wait(1);
    I.sawWebRequestUrlContaining('placehold.it');

Where the last command checks if there was at least one web request to a URL containing the specified string (since the last time we started monitoring).

Not sure if that makes any sense and if it is in scope for CodeceptJS - but it would make things easier for us.

**Comment by goschevski** [comment]
This would be very helpful.

**Comment by DavertMik** [comment]
Yeah, good idea but I think this should be implemented as custom helper and not a general purpose method. If someone is interested they can develop and publish such helper on NPM or propose it with pull request
