### ISSUE TITLE
how to select file from file upload dialog automatically

### ISSUE THREAD

**Issue by celalettinc** [Codeception/CodeceptJS#1300]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

CodeceptJS version: 1.3.3
NodeJS Version: 8.10.0
Operating System: windows 10
Protractor || WebDriverIO || Nightmare version (if related) : Puppeteer
Configuration file:
{
"output": "./target/errorscreens",
"helpers": {
"Puppeteer": {
"url": "blabla",
"waitForNavigation": "load",
"windowSize": "1920x1080",
"show": true,
"waitForAction": 300
}
},
"include": {
"I": "./steps_file.js",
},
"mocha": {
"reporterOptions": {
"reportDir": "target/testsonuclari"
}
},
"bootstrap": false,
"teardown": null,
"hooks": [],
"gherkin": {},
"tests": "./tests/**/*.js",
"timeout": 10000,
"page load": 3000,
"name": "CODECEPTJS"
}

```js
# paste suite config here
```
I want to select a specified file automatically after clicking upload named button. In my desktop there is a loaded excel file. In test, firstly click the upload button and open file upload dialog, secondly I want to select file from specified path automatically but don't do this, just passing this step. I tried lots of npm modules, like file-select, file-dialog, express-fileupload etc., but didn't select the file. How can i do this?

**Comment by LukoyanovE** [comment]
Does attachFile work?
https://codecept.io/helpers/Puppeteer/#attachfile

**Comment by celalettinc** [comment]
I tried it but not working.

**Comment by LukoyanovE** [comment]
What did not worked?
There are no soothsayers in Codecept. Share your full results.

Please, add test with attachFile (and paste code here) and add "not working" description.
If there was error, then it and it's stacktrace.
If not, what behavior did you see?
Run test with `--verbose` option and paste result here.

**Comment by celalettinc** [comment]
Test scenario:
Scenario('Upload File', (I) => {
     I.click('Btn1'); //opening parent menu
     I.click('Btn2'); //opening upload page
     I.see('Upload File Page'); //verify the page open
     I.click('Upload'); // after clicking open window file upload dialog
     I.attachFile("input[type='file']", "/files/filename.xlsx");
});
Before trying attachFile, I tried some npm modules but nothing happen to select and upload file. After my first try attachFile, nothing happened test passed but the file not uploaded but after running with --verbose option it works, I didn't understand how this happen. Now it works but if i use click('Upload') step system attach file but window file upload dialog not closed, so i deleted I.click('Upload'); step from test.
Is there a way to see selecting file as visual after opening file upload dialog

**Comment by hatngg** [comment]
Hi. I'm newbie. I have an issue same with above question. Can you help me?
I run basic script with attachFile and it worked. But in my project can not do it and show error message "error: cannot focus element"
Ex: Worked
Scenario('test something', (I) => {
    I.amOnPage('http://reactdropzone.azurewebsites.net/example/')
    I.attachFile('//input','shipmentplanning_1.csv')
    pause() 
});
Ex: Not Work
Scenario('test something', (I) => {
...
I.waitForElement('.//*[@class="page-container"]//ul/li[5]//span[contains(text(),"Warehouse")]',6);
I.click('.//*[@class="page-container"]//ul/li[5]//span[contains(text(),"Warehouse")]');
I.waitForElement('.//*[@class="title"][contains(text(),"Inbound Planning")]',6);
I.click('.//*[@class="title"][contains(text(),"Inbound Planning")]');
I.wait(7);
I.waitForElement('.//*[@class="fa fa-edit my-float"]',6);
I.click('.//*[@class="fa fa-edit my-float"]');
I.wait(5);
I.waitForElement('.//*[@class="fa fa-upload my-float"]',10);
I.wait(3);
I.attachFile(".//*[@class='fa fa-upload my-float']",'shipmentplanning_1.csv');
});
Thanks
After run script, it failed.
-------
I attach file ".//*[@class='fa fa-upload my-float']", "shipmentplanning_1.csv"
    » Uploading C:\Codeceptjs\Test\Demo_TCMA\shipmentplanning_1.csv
    [1] Error | Error: unknown error: cannot focus element
    Emitted | step.failed (I attach file ".//*[@class='fa fa-upload my-float']", "shipmentplanning_1.csv")
    Emitted | step.finish (I attach file ".//*[@class='fa fa-upload my-float']", "shipmentplanning_1.csv")
