### ISSUE TITLE
Codeceptjs can not find option `--plugins'

### ISSUE THREAD

**Issue by KaterynaGubar** [Codeception/CodeceptJS#1309]
#### What are you trying to achieve?
I'm trying to enable allure reporting for my UI tests

#### What do you get instead?
error: unknown option `--plugins'

I've installed allure-commandline package, added plugins to config file and use command
> codeceptjs run --plugins allure

and get an error:

> error: unknown option `--plugins'

### Details

* CodeceptJS version: 1.4.4
* NodeJS Version: 8.11.3
* Operating System: Windows 10
* Protractor: 5.3.2
* Configuration file:
```js
# paste suite config here

codecept.json:

{
  "output": "./output",
  "helpers": {
    "Protractor": {},
    "REST": { }
  },
  "include": {
    "I": "./steps/custom_steps.js",
     ...
  },
  "mocha": {
    "reporterOptions": {
      "mochaFile": "./output/result.xml"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {},
  "plugins": {
    "allure": {
      "enabled": true
    }
  },
  "tests": "./tests/*/*_test.js",
  "timeout": 10000,
  "name": "ui"
}
```

**Comment by vitaly87** [comment]
its looks like you don't use the last version of codeceptjs , please make sure that you are on the last version. maybe you have one locally and one global please check it.

**Comment by KaterynaGubar** [comment]
> its looks like you don't use the last version of codeceptjs , please make sure that you are on the last version. maybe you have one locally and one global please check it.

Yes, I haven't updated the global one, thanks.
