### ISSUE TITLE
Creating async test cases

### ISSUE THREAD

**Issue by tjoskar** [Codeception/CodeceptJS#132]
Hi,

Is it possible write async testcase?

Lets say I want to make a HTTP request in a test case:

``` javascript
function httpRequest() {
    // Make a fake http request
    return new Promise(resolve => {
        setTimeout(() => {
            console.log('Data from server');
            resolve('some data');
        }, 5000);
    });
}

Scenario(`Test case`, function*(I) {
    const data = yield httpRequest();
    console.log('Test continues');
    // Some asserts
});
```

I expected the output to be:

```
Data from server
Test continues
```

but it is:

```
Test continues
Data from server
```

I would also want the cast case to wait for a returning promise to resolve/reject:

``` javascript
Scenario(`Test case2`, function(I) {
    return httpRequest()
        .then(() => {
            console.log('Test continues');
            // Some asserts
        });
});
```

It would also be nice if the `Before` method waits for the promise to resolve/reject:

``` javascript
Before(I => new Promise(resolve => setTimeout(resolve), 5000));
```

Similar, I expect the testcase to fail if a promise rejects. Is this possible?

Maybe duplicate of: #46

**Comment by ecampii** [comment]
Was this solved???

Im trying to use console.logs to separated my scenario steps but it all gets written before the steps gets executed.

**Comment by tjoskar** [comment]
@ecampii, I don't think this was ever solved. I was looking into the matter but could not find a simple solution (without rewriting the current async-handler).

**Comment by harkinj** [comment]
@tjoskar - was this ever progressed? I'd like to do some async setup in a test case before doing the tests but can't find a way to do this in Codeceptsjs. Thanks for youre time.

**Comment by tjoskar** [comment]
@harkinj, unfortunately not. Not from my side anyway. I went over to [nightmare](http://www.nightmarejs.org/) (and [testcafe](https://devexpress.github.io/testcafe/)) to be able to write async setups.

**Comment by harkinj** [comment]
@tjoskar - thanks for your prompt response.I like codeceptjs but this lack of ability to write async setup code is a big missing.Just curious - have u moved off codeceptjs completely for this main reason? Thanks for youre time.

**Comment by DavertMik** [comment]
Hey, sorry, I didn't notice this issue, and didn't provide response in time. 

I think what you are trying to achieve can be easily done with CodeceptJS however you will need to stick to its abstractions like Helpers.

Everything in CodeceptJS is scenario-driven so any calls like `httpRequest` should be called inside `I.` chain, like: `I.sendHttpRequest()`. To make this function inside of `I` you will need to [create a helper](http://codecept.io/helpers/) and enable it in config. Once you do it the method is available. All methods of `I.` are grouped into a promise chain, this way we ensure that everything is executed synchronously.

There is no need to work with promises the way you did it in Mocha or whenever else. The idea of CodeceptJS test is to hide the technical implementation and focus on test scenarios.

Once again: Everything inside `I.xxx` calls is synchronous and executed inside promise chain. To implement custom logic on top of that use helpers

**Comment by shamusharkin** [comment]
@DavertMik (follow up question from @harkinj) 
I created a helper with an async function (using set timeout), but it doesn't run sync, do I need to return a promise?

**Comment by tjoskar** [comment]
@harkinj: The reason that I stopped using codeceptjs was a combination of several issues (all of which seems to be solved now) and the fact that I didn't have time to help and fix the issue at the time. What I really love with codeceptjs is however the fact that you can change the target-client (selenium, nightmare, etc) with very little/none effort (and the support of x-path). 

And as @DavertMik pointed out, it is possible to write test cases with custom async methods (I have however not tried yet), so I will give codeceptjs an another chance.

**Comment by DavertMik** [comment]
> do I need to return a promise?

yes. 

@tjoskar thanks! :+1: 

Anyway, this project needs some love from community. I wish I had more time to work on it, and implement all the good ideas out there and reply on all issues. Anyway, we are moving forward step-by-step but moving :)

I think I can try to implement the idea you suggested: handling of returned promise in `Before`/`Scenario` for async execution. That is how Mocha works, so probably it can be implemented here as well

**Comment by harkinj** [comment]
@DavertMik - Thanks for your responses and the response to @shamusharkin  helped.
