### ISSUE TITLE
Start selenium standalone when running codecept

### ISSUE THREAD

**Issue by BenoitAverty** [Codeception/CodeceptJS#133]
Hi,

I'm moving from chimp because the syntax provuded by codecept seems nicer to write tests. However, I liked the ability to start and stop a local selenium server (with [selenium-standalone](https://github.com/vvo/selenium-standalone)).

Would it be possible to add such an option to codeceptjs ? Otherwise it needs a lot of boilerplate code to work.

**Comment by DavertMik** [comment]
Probably we can do this in future. Right now I think the same feature can be done if you use Protractor helper. 

Personally I had lots of issues with Selenium Standalone. It didn't upgrade Selenium for the latest version for me and I always had to do it and start the server manually :(

**Comment by APshenkin** [comment]
https://github.com/Codeception/CodeceptJS/issues/334
