### ISSUE TITLE
after query, write [object Promise] into the text field not write the correct data

### ISSUE THREAD

**Issue by celalettinc** [Codeception/CodeceptJS#1340]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

CodeceptJS version: 1.4.5
NodeJS Version: 8.10.0
Operating System: windows 10
Protractor || WebDriverIO || Nightmare version (if related) : Puppeteer
Configuration file:
{
"output": "./target/errorscreens",
"helpers": {
"Puppeteer": {
"url": "blabla",
"waitForNavigation": "load",
"windowSize": "1920x1080",
"show": true,
"waitForAction": 300
}
},
"include": {
"I": "./steps_file.js",
},
"mocha": {
"reporterOptions": {
"reportDir": "target/testresult"
}
},
"bootstrap": false,
"teardown": null,
"hooks": [],
"gherkin": {},
"tests": "./tests/**/*.js",
"timeout": 10000,
"page load": 3000,
"name": "CODECEPTJS"
}

```js
In database.js file:
module.exports = {
   db:  {
             getData: async function (sql) {
                            const {Client} = require('pg');
                            const config = new Client({
                                      host: '****',
                                      user: '****',
                                      password: '****',
                                      port: '5432',
                                     database: '****',
                             });
                        await config.connect((err) => {
                                 if (err) {
                                            console.error('Connection error', err.stack);
                                } else {
                                           console.log('Connected.');
                                 }
                        });
                       await config.query(sql, (err, result) => {
                               if (err) throw err;
                              config.end();
                              return result;
                      });
                  }
           }
   }
```
When i call this function like I.fillField('id', database.vt.getData(sql)); in test file, connection has done but it gives an 'text is not iterable' error. How to solve this problem.

**Comment by celalettinc** [comment]
After changing test file code like,
let data = (database.vt.getData(sql)).toString();
I.fillField('id', data);
It didn't gave any error but in text field, it wrote [object Promise] so it didn't get the correct value

**Comment by LukoyanovE** [comment]
Looks like `(database.vt.getData(sql))` return Promise,

To get it result try
```
let data = (await database.vt.getData(sql)).toString();
I.fillField('id', data);
```

**Comment by celalettinc** [comment]
My scenario is:
Scenario('Search ID', (I, database) => {
   I.amOnPage('/login');
   I.fillField(username, password);
   I.click('Login In');
   let data = (database.vt.veriGetir("SELECT id FROM customer ORDER BY date DESC;")).toString();
   I.fillField('id',data);
   I.click('Search');
});
When i tried as you said, it gives an 'await is not defined' error. 

Is there anything to do something in database file?

**Comment by LukoyanovE** [comment]
I think you problem in `getData` method.
It does not return anything.
```
await config.query(sql, (err, result) => {
  if (err) throw err;
  config.end();
  return result;
});
```

You are awaiting function execution end, but not return something
Do not worked with `pg` module, but I think, it should look like 
```
return await config.query(sql, (err, result) => {
  if (err) throw err;
  config.end();
  return result;
});
```

or 
```
let result = await config.query(sql, (err, result) => {
  if (err) throw err;
  return result;
});
config.end();
return result;
```

**Comment by celalettinc** [comment]
I tried as you said but same thing happened. Can you advice any module? Which one is the proper? I tried codeceptjs-dbhelper module, the result was the same

**Comment by celalettinc** [comment]
After some changes it works. Nothing any problem.

**Comment by LukoyanovE** [comment]
@celalettinc, please, add your solution here for future searchers

**Comment by celalettinc** [comment]
In database.js file:
async function queryData(sql) {
                            const {Client} = require('pg');
                            const config = new Client({
                                      host: '****',
                                      user: '****',
                                      password: '****',
                                      port: '5432',
                                     database: '****',
                             });
                        await config.connect((err) => {
                                 if (err) {
                                            console.error('Connection error', err.stack);
                                } else {
                                           console.log('Connected.');
                                 }
                        });
                      let promise = new Promise((resolve, reject) => {
                                config.query(sql).then(result => {
                                resolve(Object.values(result.rows[0]));  //It returns the query
                               }).catch(err => {
                                      console.log(err.stack);
                                    reject('Control your query');
                              }).then(()=>{
                                config.end();
                          });
                   });
                 let res = await promise;
                 return res;

                let dt = getData(sql).then( x => {
                       return Promise.all(x.toString());
                 });

              return dt;
       }
