### ISSUE TITLE
Feature request >> make skipped tests appear in Allure report

### ISSUE THREAD

**Issue by SchnuckySchuster** [Codeception/CodeceptJS#1367]
This is not a bug, it is feature request.
Sadly I can not code well enough to implement the feature request nor do I know any one who is able to.

As an agile QA consultant I want my teams to specify the tests first and then develop the functionality and subsequently code the test. 
In order to be able to see what tests are planned but not jet implemented they need a possibility to mark tests as to be skipped or to be pending.
This tests should show in the Allure test report.

Im using following versions
    "allure-commandline": "^2.8.1",
    "codeceptjs": "1.4.4",
    "puppeteer": "^1.11.0"

I had to downgrade to "codeceptjs": "1.4.4" as "codeceptjs": "1.4.6" did not report steps propperly

**Comment by AdamOakman** [comment]
I am also looking forward to seeing this feature in next releases

**Comment by cchiaverini** [comment]
I would like to see this feature as well.

**Comment by PeterNgTr** [comment]
https://github.com/Codeception/CodeceptJS/pull/1448

It is added. Wait for the new release.

**Comment by Guria** [comment]
@PeterNgTr I still don't see skipped tests in allure reports
