### ISSUE TITLE
`codeceptjs def` generates incorrect steps.d.ts

### ISSUE THREAD

**Issue by trinhpham** [Codeception/CodeceptJS#1370]
#### What are you trying to achieve?
Make the definition file to write test in TypeScript

#### What do you get instead?
```bash
steps.d.ts:48:9 - error TS7006: Parameter 'test' implicitly has an 'any' type.
48   _test(test): void
           ~~~~

steps.d.ts:64:7 - error TS1086: An accessor cannot be declared in an ambient context.

64   get helpers(): any
         ~~~~~~~
```
![image](https://user-images.githubusercontent.com/9128061/49645241-b91e5a00-fa4d-11e8-9cb1-972c57aa6982.png)

### Details

* CodeceptJS version: 1.4.6
* NodeJS Version: 8.11.1
* Operating System: Windows 10
* Protractor: 5.4.1
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Protractor": {
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "something"
}
```

**Comment by LukoyanovE** [comment]
@trinhpham , looks like you hav fixed issue, and it could be closed

**Comment by trinhpham** [comment]
Close as @LukoyanovE suggested.
