### ISSUE TITLE
mochawesome screenshots not saving if report directory is changed.

### ISSUE THREAD

**Issue by null-saad** [Codeception/CodeceptJS#1371]
#### What are you trying to achieve?
I changed the report directory when running codeceptjs with mochawesome report.

#### What do you get instead?
The failed screenshots get saved in the "output" default report directory and not the in the new directory and hence the report is unable to access is when served.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
There is no error on console.

> Provide test source code if related
codeceptjs run --reporter mochawesome --reporter-options reportDir='./myreport' sample_test.js

```js
// paste test
```

### Details

* CodeceptJS version: 1.4.6
* NodeJS Version: 10.9.0
* Operating System: Windows 10
* Protractor || WebDriverIO || Nightmare version (if related) Pupeeteer
* Configuration file:
{
  "output": "./output",
  "helpers": {
    "Mochawesome": {
      "uniqueScreenshotNames": "true"
  },
    "Puppeteer": {
      "url": "http://localhost",
      "show": "show",
      "restart": "false",
      "waitForNavigation": "networkidle0",
      "waitForTimeout": "60000",
      "windowSize" : "640x480"
    },
    "Rhodium": {
      "require": "./rhodium_helper.js"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "output"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {},
  "tests": "./*_test.js",
  "timeout": 10000,
  "name": "CC"
}

```js
# paste suite config here
```

**Comment by PeterNgTr** [comment]
The fix is coming here https://github.com/Codeception/CodeceptJS/pull/1372
