### ISSUE TITLE
I am not able to press 'esc' key

### ISSUE THREAD

**Issue by aarunsharma** [Codeception/CodeceptJS#1376]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by PeterNgTr** [comment]
Did you use 'Esc' or 'Escape'?
```
    Emitted | step.before (I am on page "https://www.google.com")
    Emitted | step.after (I am on page "https://www.google.com")
    Emitted | step.before (I press key "Escape")
    Emitted | step.after (I press key "Escape")
    Emitted | step.before (I see "hello")
    Emitted | step.after (I see "hello")
    Emitted | step.start (I am on page "https://www.google.com")
```

**Comment by aarunsharma** [comment]
Please use "Escape" instead of "esc", thanks @PeterNgTr
