### ISSUE TITLE
How can I close driver after each scenario?

### ISSUE THREAD

**Issue by KaterynaGubar** [Codeception/CodeceptJS#1380]
#### What are you trying to achieve?

Close webdriver after each scenario

#### What do you get instead?

Lots of webdrivers open

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here

exports.config = {
  output: "./output",
  helpers: {
    Protractor: {
      url: "http://*****************",
      driver: "hosted",
      browser: "chrome",
      windowSize: "maximize",
      waitForTimeout: 60000,
      angular: false,
      fullPageScreenshots: true,
      capabilities: {
        chromeOptions: {
          args: [
            "--no-sandbox"
          ]
        }
      }
    },
    REST: {
      endpoint: "http://************",
      defaultHeaders: {
       ***********************
      }
    }
  },

  teardown: function() {
    this.helpers['Protractor'].browser.close();
  },
...
}
```

Wen running tests webdriver does not closed, so I have lot of them opened and need to close them manually in 'Task Manager'

**Comment by PeterNgTr** [comment]
https://github.com/PeterNgTr/amazon-ui-tests/blob/master/codecept.conf.js

Can you try to start and kill selenium this way?

**Comment by DavertMik** [comment]
You can just use `restart: true` config option
