### ISSUE TITLE
ENAMETOOLONG error with data driven tests

### ISSUE THREAD

**Issue by vitalykorolev** [Codeception/CodeceptJS#1384]
#### What are you trying to achieve?
Trying to run data driven tests as per https://codecept.io/advanced/#data-driven-tests
The data consists of multiple columns of data including cookie value.

#### What do you get instead?
When one of the scenarios fails, the entire script fails with the following error:
Error: ENAMETOOLONG: name too long, open '/Users/.../output/Verify_presence_of_disable_option_for_a_user_-_Administrator___{ACC_uname_qatest10,ACC_fname_Org2,ACC_lname_Admin,ACC_email_qatest10@org2.com,ACC_country_Canada,ACC_password_SomePass#123,ACC_role1_SEC-ADMN,ACC_role2_SERV-ADMN,ACC_role3_ACCT-ADMN}.failed.png'

### Details

* CodeceptJS version: 1.4.6
* NodeJS Version: 6.4.1
* Operating System: MacOS
* Protractor

Looks like there were issues opened for this, but both were closed referencing each other.
https://github.com/Codeception/CodeceptJS/issues/1106
https://github.com/hubidu/bifrost-io/issues/2

**Comment by PeterNgTr** [comment]
Fix is here https://github.com/Codeception/CodeceptJS/pull/1385
