### ISSUE TITLE
WebDriver await I.grabAttributeFrom() returns an array after v2.0.1 upgrade

### ISSUE THREAD

**Issue by xMutaGenx** [Codeception/CodeceptJS#1401]
#### What are you trying to achieve?

Grab an attribute value using `await I.grabAttributeFrom()`

#### What do you get instead?

After v2.0.1 upgrade `await I.grabAttributeFrom()` returns the attribute as an array

> Provide test source code if related

```
...
I.amOnPage('/');
const url = await I.grabAttributeFrom({ css: 'a[data-qa="something"]' }, 'href'); // returns ['url'] instead of 'url'
...
```
### Details

* CodeceptJS version: 2.0.2
* NodeJS Version: 10.13.0
* Operating System: OSX
* WebDriverIO: 5.1.1

**Comment by PeterNgTr** [comment]
it returns an array as it was. Are you sure it returned not an array before?

**Comment by xMutaGenx** [comment]
Yeah previous iteration was returning the value of the attribute rather than an array of attributes using wdio@4, I'll update our tests to work with arrays, cheers @PeterNgTr
