### ISSUE TITLE
Error: Cannot find module 'chai' with Dockerfile / protractor

### ISSUE THREAD

**Issue by lepadellec** [Codeception/CodeceptJS#1419]
Hi,

I have a set of codeceptjs protractor tests that I want to run in the codeceptjs docker environment.
My tests use the node module soap, I therefore need to rebuild the codecetpion/codeceptjs docker image to add this new module. I have done this, by cloning the codeceptjs repo, adding "soap" to the package.json and building my docker image - all fine.
I then try to run the image with my tests, mapping, as indicated the location of my testsuite to /tests.
I encounter errors when trying to load my helpers, for helpers that require 'chai' I see:
codecept_protractor_1  | CodeceptJS directory has been found.
codecept_protractor_1  |
codecept_protractor_1  | Could not load helper Iw_authentication from module '/tests/iw_authentication_helper.js':
codecept_protractor_1  | Cannot find module 'chai'
codecept_protractor_1  |
codecept_protractor_1  | Error:
codecept_protractor_1  |     at createHelpers (/codecept/lib/container.js:152:13)
codecept_protractor_1  |     at Function.create (/codecept/lib/container.js:32:25)
codecept_protractor_1  |     at Codecept.init (/codecept/lib/codecept.js:55:15)
codecept_protractor_1  |     at Command.module.exports (/codecept/lib/command/run.js:35:14)
codecept_protractor_1  |     at Command.listener (/codecept/node_modules/commander/index.js:315:8)
codecept_protractor_1  |     at Command.emit (events.js:182:13)
codecept_protractor_1  |     at Command.parseArgs (/codecept/node_modules/commander/index.js:654:12)
codecept_protractor_1  |     at Command.parse (/codecept/node_modules/commander/index.js:474:21)
codecept_protractor_1  |     at Object.<anonymous> (/codecept/bin/codecept.js:142:9)
codecept_protractor_1  |     at Module._compile (internal/modules/cjs/loader.js:688:30)

My helper:
let Helper = codecept_helper;
let fs = require('fs');
var chai = require('chai');

Please advise how to run codeceptjs with docker and to add extra modules to codeceptjs, for example the soap node module.

**Comment by DavertMik** [comment]
Extend our defaul docker image and install all required packages:

Sample Dockerfile:
```
FROM codeception/codeceptjs
RUN npm i "chai" "soap" --prefix /
```

**Comment by lepadellec** [comment]
Thanks - I did this - I also needed to add to my Dockerfile:

`ENV NODE_PATH=/codecept/node_modules
`

**Comment by aesyondu** [comment]
> Extend our defaul docker image and install all required packages:
> 
> Sample Dockerfile:
> 
> ```
> FROM codeception/codeceptjs
> RUN npm i "chai" "soap" --prefix /
> ```

Thanks for this. I'd just like to note that the repo was renamed to [codeceptjs/codeceptjs](https://hub.docker.com/r/codeceptjs/codeceptjs)
