### ISSUE TITLE
Launch browser with installed extension

### ISSUE THREAD

**Issue by rrodriguesdashlane** [Codeception/CodeceptJS#142]
Hi everyone,

I've been trying for a while to start Firefox or Chrome with a preinstalled extension without any success. Could someone explain me how to configure codeceptjs and webdriverIO to be able to do that please?

Thank you in advance for your help.

**Comment by gidsi** [comment]
Hi!

add something likes this to your codecept.json file:

```
helpers: {
  SeleniumWebdriver: {
    capabilities: {
      chromeOptions: {
        extensions: [
          'the crx file, base64 encoded'
        ]
      }
    }
  }
}
```

Regards

**Comment by APshenkin** [comment]
Closing due inactivity
