### ISSUE TITLE
I.pressKey with multiple keys does not work

### ISSUE THREAD

**Issue by ndrsfrr** [Codeception/CodeceptJS#1420]
#### What are you trying to achieve?

I want to select the whole content of a field.
Given the following test

```bash
Scenario('I want to select the content of a field', (I) => {
  I.amOnPage('https://www.google.com/search?q=abc');
  I.click('[name=q]');
  I.pressKey(['Control','a']);
});
```

#### What do you get instead?

Instead of 'abc' beeing selected, I saw following behaviours in different tests:
* nothing happens
* as shown with google, it's pasted in the field
![image](https://user-images.githubusercontent.com/39731774/50818531-8a82f000-1327-11e9-8308-6666ef8aba73.png)

### Details

* CodeceptJS version: 2.0.1
* NodeJS Version: 8.9.4
* Operating System: Windows
* WebDriverIO version: 5.2.0
* Configuration file:

```js
WebDriver: {
      host: isDocker() ? 'selenium-chrome' : 'localhost',
      port: isDocker() ? 24444 : 4444,
      url: config.url,
      browser: 'chrome',
      desiredCapabilities: {
        chromeOptions: {
          args: [
            '--enable-automation',
            '--disable-extensions'
          ]
        }
      },
      windowSize: '1920x1080',
      disableScreenshots: true
    },
```

**Comment by xMutaGenx** [comment]
Seems like a bug in Webdriver rather than the CodeceptJS framework, as:
```
  I.pressKey('Control');
  I.pressKey('a');
  I.pressKey('Control');
```
will not work, but the following will:
```
  I.pressKey('\uE009');
  I.pressKey('a');
  I.pressKey('\uE009');
```

Seems to be a translation to unicode issue, also note that CodeceptJS currently doesn't support `I.pressKey(['\uE009', 'a']);`

Maybe a potential enhancement?

**Comment by mirao** [comment]
@ndrsfrr Please reopen the bug. Current behavior doesn't correspond with the docs https://codecept.io/helpers/WebDriverIO/#presskey.
It worked for me with CodeceptJS 1.4.4 and WebDriverIO 4. So it's a regression in new version of CodeceptJS 2.0 or WebDriverIO 5.
Both Chrome/Firefox are affected.

**Workaround:** `I.pressKey(["\uE009", "a", "\uE009"]);`

The list of unicode code points is [here](https://w3c.github.io/webdriver/#keyboard-actions).

**Comment by LukoyanovE** [comment]
@mirao , could you say your OS

**Comment by mirao** [comment]
@LukoyanovE : Tested on Windows 10 and Linux Ubuntu 18.10. Both are affected.

**Comment by LukoyanovE** [comment]
@mirao , I see in Webdriverio repo, that they have no `'Control'` 
They use `Control Left` somewhy for `\uE009`
https://github.com/webdriverio/webdriverio/blob/b970e0a2c2eda9b0c570a5f9ead4add5853711d5/packages/webdriverio/src/constants.js#L301

**Comment by LukoyanovE** [comment]
Made PR to WDIO. It should help
https://github.com/webdriverio/webdriverio/pull/3680

**Comment by mirao** [comment]
@LukoyanovE `I.pressKey(["Control Left", "s", "Control Left"]);` works, thank you. The second "Control Left" must be there otherwise the Control key isn't released.

**Comment by mirao** [comment]
@LukoyanovE The issue is fixed in [webdriver@5.7.1](https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#571-2019-03-07), thank you.

**Comment by ndrsfrr** [comment]
Thanks guys! Didn't know what to do and nobody seemed interested. Thanks @LukoyanovE for your PR!

**Comment by AiretiKelala** [comment]
Is the key value for "command" same as "control"?

**Comment by elukoyanov** [comment]
> Is the key value for "command" same as "control"?

Nope, these are two different key values
