### ISSUE TITLE
Could not connect to WebDriver  if trying to run tests on browser stack

### ISSUE THREAD

**Issue by KaterynaGubar** [Codeception/CodeceptJS#1423]
#### What are you trying to achieve?
I want to test site on mobile device, using browserstack

#### What do you get instead?
Can't connect to WebDriver

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here

Can't connect to WebDriver.
Error: getaddrinfo ENOTFOUND http http:80

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

**output with verbose:**

  [1] Starting recording promises
    Emitted | suite.before ([object Object])
  "Previous" CTA on Select Shop page to become Back Button @mobile @BKM-223
    Emitted | test.before ([object Object])
    [1] Error | Error: Can't connect to WebDriver.
Error: getaddrinfo ENOTFOUND http http:80

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
    Emitted | test.failed ([object Object])
  × "before each" hook: codeceptjs.before for ""Previous" CTA on Select Shop page to become Back Button @mobile @BKM-223" in 9049ms
    [1] Error | Error: Can't connect to WebDriver.
Error: getaddrinfo ENOTFOUND http http:80

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
Error: Can't connect to WebDriver.
Error: getaddrinfo ENOTFOUND http http:80

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])
```

### Details

* CodeceptJS version: 1.4.4
* NodeJS Version: 8.11.3
* Operating System: Windows 10
* Protractor: 5.4.1
* Configuration file:

**appium.conf.js:**

exports.config = {
    output: "./output",
    helpers: {
        REST: {
            endpoint: "****************************",
            defaultHeaders: {
                appId: "***********************************"
            }
        },
        Appium: {
            browser: "iPhone",
            device: "iPhone 8 Plus",
            realMobile: true,
            os_version: "11.0",
            user: "*******",
            key: "********",
            host: "http://hub-cloud.browserstack.com/wd/hub",
            baseUrl: '****************************',
            waitForTimeout: 60000
        },
        MyHelper: {
            require: "./page_objects/helpers/MyHelper.js"
        }
    },

    include: {
        I: "./steps/custom_steps.js",
        ....
    },
    mocha: {},
    bootstrap: false,
    teardown: null,
    hooks: [],
    gherkin: {},
    plugins: {
        allure: {
            enabled: true
        }
    },
    tests: "./tests/*/*_test.js",
    timeout: 10000,
    name: "ui"
}

**Comment by KaterynaGubar** [comment]
I changed my config file and seems that now it seems to be configured to Browserstack

exports.config = {
    output: "./output",
    helpers: {
        REST: {
            endpoint: "URL",
            defaultHeaders: {
                appId: "APP-ID"
            }
        },
        Appium: {
            desiredCapabilities: {
                platformName: "iOS",
                deviceName: "iPhone 8 Plus",
                platformVersion: "11.0",
                browserName: 'iPhone',
                realMobile: true
            },
            browser: "chrome",
            device: "iPhone 8 Plus",
            os_version: "11.0",
            host: "hub-cloud.browserstack.com",
            port: 4444,
            user: 'USER',
            key: 'KEY',
            automationName: "Appium",
            baseUrl: 'URL',
            waitForTimeout: 60000
        }
    },

    include: {
        I: "./steps/custom_steps.js",
     ...
    },
    tests: "./tests/*/*_test.js",
    timeout: 10000,
    name: "ui"
}

But now I wonder is it possible to paralyze mobile tests? And if yes- how to do that?

**Comment by yusufilkeroguz** [comment]
I had same error for ie11 and i fixed with;

```javascript
      'user' : '[USERNAME]',
      'key' : '[KEY]',
      'url': 'https://www.mybestsite.com',
      'browser': 'Edge',
      'protocol': 'http',
      'host': 'hub-cloud.browserstack.com',
      capabilities: {
        'browserName' : 'Edge',
        'os' : 'Windows',
        'os_version' : '10',
        'browser_version' : '18.0',
        'resolution' : '1366x768',
        'browserstack.local' : 'false',
        'browserstack.selenium_version' : '3.5.2',
        'browserstack.user' : '[USERNAME]',
        'browserstack.key' : '[KEY]'
      }
```

**Comment by pablopaul** [comment]
@KaterynaGubar can we close the issue?
