### ISSUE TITLE
Custom parameters on the cli

### ISSUE THREAD

**Issue by gideonairex** [Codeception/CodeceptJS#143]
Is there a way to have additional parameters that I could use on the cli?
Example:

```
npm run codeceptjs -- run --steps --testcase=1
```

I tried this but you have validation for parameters. Im going to use this so that I can have a data driven test. So I can change the values of the data.

**Comment by APshenkin** [comment]
@gideonairex I think, you can pass your parameters throw environment vatiables
```testcase=1 npm run codeceptjs -- run --steps``` and use them in your test via `process.env.testcase`.

Is it OK for you?

**Comment by gideonairex** [comment]
@APshenkin yup thats what Ive done. Closing this.

**Comment by sirsimonson** [comment]
@gideonairex This does not work with script aliases, i.e. `"test:testrail:acceptance": "testrail=true npx codeceptjs run --grep @pw"`

Do you have a solution in mind?
