### ISSUE TITLE
WebDriver plugin needs 'logLevel' option since CodeceptJS v2.0.3

### ISSUE THREAD

**Issue by tsuemura** [Codeception/CodeceptJS#1436]
Since version 2.0.3, WebDriver plugin needs 'logLevel' option.

On v2.0.2, with this setting works good.

```codecept.conf.js
WebDriver: {
    host:  'localhost',
    port: 4444,
    url: 'localhost',
    browser:  'chrome',
    smartWait:  5000,
    waitForTimeout:  15000,
}
```

But from v2.0.3, it results an error.

```bash
Can't connect to WebDriver.
Error: Option "logLevel" doesn't match expected values: /(trace|debug|info|warn|error)/
```

Adding this setting will work fine.

```codecept.js
WebDriver: {
    logLevel: 'trace',
    // ...
}
```

**Comment by DavertMik** [comment]
please update webdriverio library to latest one

**Comment by PeterNgTr** [comment]
`  _validateConfig(config) {
    const defaults = {
      logLevel: 'silent',

      // codeceptjs
      remoteFileUpload: true,
      smartWait: 0,
      waitForTimeout: 1000, // ms
      capabilities: {},
      restart: true,
      uniqueScreenshotNames: false,
      disableScreenshots: false,
      fullPageScreenshots: false,
      manualStart: false,
      keepCookies: false,
      keepBrowserState: false,
      deprecationWarnings: false,
      timeouts: {
        script: 1000, // ms
      },
    };
`

It was there :)

**Comment by tsuemura** [comment]
Thank you for advice. I've updated WebdriverIO and now it works fine :+1:
