### ISSUE TITLE
I.waitForElement() not Working after last Update in Android

### ISSUE THREAD

**Issue by eduardofinotti** [Codeception/CodeceptJS#1437]
#### What are you trying to achieve?
About this bug:
https://github.com/Codeception/CodeceptJS/pull/1434

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by narlei** [comment]
Same problem :(

When use `I.waitForElement('#com.android...')` return the error: 

`Promise was rejected with the following reason: Error: selector needs to be typeof string or function`

**Comment by narlei** [comment]
Please aprove the PR: https://github.com/Codeception/CodeceptJS/pull/1442

Working with Android now 🙏
