### ISSUE TITLE
Puppeteer - cannot switch to the iframe without an ID

### ISSUE THREAD

**Issue by iljao** [Codeception/CodeceptJS#1439]
I'm trying to wait for an element inside an iframe using puppeteer helper.
The thing is that the iframe doesn't have an ID attribute.
I tried both switchTo and within, but waitForElement() fails with timeout in both cases.
It looks like switching is not happening, because I can locate elements outside the target iframe after switchTo(...).
It works with webdriver and nightmare though, so the issue is with puppeteer I guess.

Has anybody encountered this issue?

### Details

* CodeceptJS version: 2.0.2
* NodeJS Version: 10.13.0
* Operating System: win10

**Comment by hekard2l** [comment]
I ran into StaleElementExceptions with WebDriver, so decided to take a look at this again.

This doesn't work if you don't have names on your frames. It will never check by url.
https://github.com/Codeception/CodeceptJS/blob/d28a3e0aca5f8370aa349af209928a94b6734903/lib/helper/Puppeteer.js#L1835

I think, this function should look by url if it can't find anything by name.

**Comment by franklsm1** [comment]
Adding the name field to my iframe allowed me to switch between my iframe and the main page with no trouble. Before the URL of the iframe was changing behind the scenes so I could never enter into the iframe at the right time, but with name it does not matter I can call `waitForElement` calls again.

**Comment by GPITRTD** [comment]
Please fix this issue, it is open for a long time. It is currently impossible to do any tests in an iFrame with Puppeteer. Both functions: within() and switchTo() are not working (even with an iframe id). As stated before after the switch function, it is possible to find elements outside the iFrame.

**Details**

- CodeceptJS version: v2.3.0
- Node version: v10.16.0
- Operating System: Windows 10

Example:

```
 I.click('button');
 I.waitForVisible('#iframe',8);
 I.switchTo('#iframe');
 I.waitForVisible('#element-outside-iframe', 5);
 I.waitForVisible('#element-in-iframe', 5);
```

Output:

```
"before each" hook: Before for "Check velden zoekscherm":
element (#element-in-iframe) still not visible after 5 sec
waiting for selector "#element-in-iframe" failed: timeout 5000ms exceeded
```

**Comment by johnyb** [comment]
I actually ran into this with a snippet like:

```
    I.waitForElement('.mail-detail-frame');
    within({ frame: '.mail-detail-frame' }, () => {
        I.waitForText('This mail has no content', 3);
    });
```

which uses I.switchTo internally. At least in my situations this patch fixes the problem.
