### ISSUE TITLE
Teardown in Travis CI

### ISSUE THREAD

**Issue by fabioel** [Codeception/CodeceptJS#144]
Hi
I have run into a very strange issue. When I am running my tests on Travis CI, the teardown of CodeceptJS does not work properly. For instance if my first test is logging in into a given page and the second test tries to login with wrong credentials, I am already logged in in the second test.
When I am running the tests locally the teardown is executed properly.

How can this happen?

This issue is problematic if one of my tests is failing, because the log-out that I am executing at the end of my tests is not called, when one test fails

**Comment by DavertMik** [comment]
What you use for backend, Phantom or Selenium?

Looks like session is not started or cookies from old session are used

**Comment by fabioel** [comment]
I use Phantom.
But as long as the tests are passing everthing is fine, but the teardown for failed tests does not work

**Comment by DavertMik** [comment]
I think this should be fixed in #162
