### ISSUE TITLE
[Question] Configure screenshotOnFail plugin to highlight an element which failed the test case

### ISSUE THREAD

**Issue by AdamOakman** [Codeception/CodeceptJS#1440]
Is there any way to configure screenshotOnFail plugin to highlight an element on screenshot which failed the test case?

For example, when I.see(); results in expected is different than actual, or clicking an element failed because of element inactivity, or textfield is not editable at the moment etc.

**Comment by kobenguyent** [comment]
highlight element is introduced with https://codecept.io/changelog/#_3-5-0
