### ISSUE TITLE
_locator doesn't work

### ISSUE THREAD

**Issue by rheydenr** [Codeception/CodeceptJS#145]
Inside steps_file.js I've placed the following method:

```
callMyTestMethod: function(modelId) {
          this.helpers['Protractor']._locate({model: modelId});
}
```

My testcript fails at this line:

```
I.callMyTestMethod('modelIdFromPage');
```

with this error message:

```
TypeError: Cannot read property 'Protractor' of undefined
      at Object.actor.callMyTestMethod(steps_file.js:10:17)
      at Test.<anonymous> (specs/102_01_MySpecFile.js:30:8)
      at Context.test.fn (/home/vagrant/Downloads/node-v4.4.4-linux-x64/lib/node_modules/codeceptjs/lib/scenario.js:27:24)
```

Other lines in this SpecFile are working correctly. I've configured my test with Protractor. If I remove the call from spec file the test succeeded. What's wrong with this? The documentation said that this is the correct syntax (see http://codecept.io/helpers/Protractor/#_locate).

**Comment by chozzz** [comment]
+1

**Comment by APshenkin** [comment]
you can't use `_locate` in steps file, you have to use it only in custom helper as described in documentation
