### ISSUE TITLE
Error running init command (Setup in README)

### ISSUE THREAD

**Issue by hollowbit** [Codeception/CodeceptJS#1458]
#### What are you trying to achieve?
I am trying to get started with CodeceptJS with Puppeteer by following the guide in the root README. I also got the same error from follow the quickstart guide (https://codecept.io/quickstart).

#### What do you get instead?

```
hollowbit@localhost:~/Documents/codeceptjs-test$ codeceptjs init
/home/s4s/.nvm/versions/node/v6.15.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/utils.js:281
module.exports.fileToBase64Zip = async function (localPath) {
                                       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/s4s/.nvm/versions/node/v6.15.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/config.js:3:34)
```

### Details

* CodeceptJS version: Latest on NPM (2.0.3)
* NodeJS Version: v6.15.1
* Operating System: Ubuntu 18.04.1 (Linux version 4.15.0-43-generic)

I noticed that the CI uses NodeJS v8, is version 6.15 not supported? The README only says v6.11+ is required (but it has been 2 years since the required version has been updated: https://github.com/Codeception/CodeceptJS/commit/33f382179a605186452733d4c8afc6ae91cb3cbf).

Thanks!

**Comment by hollowbit** [comment]
I updated to node js v8.14.1 and it worked. Maybe the README should be revised.

**Comment by hollowbit** [comment]
I tested various versions and it seems that 8.3 is the minimum needed. I would like to make a PR but I do not have permissions to make a branch on remote.

**Comment by PeterNgTr** [comment]
@hollowbit fork this project then you could make a PR.
