### ISSUE TITLE
Cannot pass variables to executeScript()

### ISSUE THREAD

**Issue by vitoo** [Codeception/CodeceptJS#1463]
Hello,

With Codeceptjs v2.0.3
System : windows 10
```js
When('i set value {string} in the field {string}',  (text, css) => {
    I.waitForVisible(css);  
    I.executeScript(function(text,css)  {
        document.querySelector(css).value = text;
    });
});
```
I got : 
`     unknown error: Cannot set property 'value' of null`
text & css variables are undefined inside the executeScript function 
I got same error with gherkins or classic tests. 

How can i achieve this  ?

Thanks!

**Comment by karunandrii** [comment]
You have to pass those to executeScript() first.
```
When('i set value {string} in the field {string}',  (text, css) => {
    I.waitForVisible(css);  
    I.executeScript(function(text,css)  {
        document.querySelector(css).value = text;
    }, text, css);
});
```
