### ISSUE TITLE
Mochawesome/mocha not reporting test output 

### ISSUE THREAD

**Issue by troycrews** [Codeception/CodeceptJS#1477]
#### Goal
Hi, we are trying to run simple end to end tests using mochawesome to generate the nice, simple HTML results page.

#### What do you get instead?
When we run `codecept.js run --reporter mochawesome`, we get the screenshot of a test failure in the ./output directory, but no HTML is generated. If we change the run command to `codecept.js run --reporter mochawesome html=true`, HTML with blank results is saved to ./output and console shows `0 passing`.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
  0 passing (6ms)

[mochawesome] Report JSON saved to [path]/mochawesome.json

[mochawesome] Report HTML saved to [path]/mochawesome.html
```
### Details

* CodeceptJS version: ^2.0.4
* NodeJS Version: 10.15.0
* Operating System: Fedora Linux
* Protractor || WebDriverIO || Nightmare version (if related): Puppeteer ^1.11.0
* Configuration file:

```js
exports.config = {
  tests: './src/tests/*_test.js',
  output: './output',
  helpers: {
    Puppeteer: {
      url: 'http://10.59.20.22:8001',
      show: false,
      waitForNavigation: ['domcontentloaded', 'networkidle0'],
      chrome: {
        "args": ["--no-sandbox"]
      }
    }
  },
  include: {
    I: './src/steps_file.js',
    loginPage: './src/pages/loginPage.js',
    spaceMenuFragment: './src/fragments/spaceMenu.js',
    createSpaceModalFragment: './src/fragments/createSpaceModal.js',
    createPageModalFragment: './src/fragments/createPageModal.js'
  },
  plugins: {
    allure: {
      "enabled": true
    }
  },
  bootstrap: null,
  mocha: {
    reporterOptions: {
        mochawesome: {
            stdout: './output/console/console.log',
            options: {
                reportDir: './output/mochawesome/',
                reportFilename: 'report',
                quiet: false,
                json: false,
                html: true,
                overwrite: true
            },
        },
    },
},
  name: 'tests'
}
```

**Comment by GSasu** [comment]
Hi @troycrews,

I'll start by saying that this isn't necessarily the the best answer to your question but rather a solution/workaround.
Personally I've never used only one reporter, I always appreciated the fact that I could have multiple reporters so I have them setup as such, try giving it a shot and see if this solves your problem.

before we start make sure you have the right packages installed:
```
npm i --save mocha mocha-junit-reporter mocha-multi mochawesome allure-commandline
// alternatively
npm i --save-dev mocha mocha-junit-reporter mocha-multi mochawesome allure-commandline
```

My config.js file is setup in part like this when it comes to reporters:
```
mocha: {
        reporterOptions: {
            'codeceptjs-cli-reporter': {
                stdout: './output/result.xml',
                options: {
                    verbose: true,
                    steps: true,
                },
            },
            mochawesome: {
                stdout: './output/console/console.log',
                options: {
                    reportDir: './output/mochawesome/',
                    reportFilename: 'report',
                    quiet: true,
                    json: false,
                    html: true,
                    overwrite: true,
                },
            },
        },
    },
.................................................

plugins: {
        allure: {
            enabled: true,
            outputDir: './output/allure',
            useCucumberStepReporter: true,
        },
```

This key `useCucumberStepReporter: true,` is there mainly because I have BDD setup and I want allure to report everything nicely no matter what type of test I run wether it's API/E2E/Negative etc.

Let me know if this helped or if there is more that I can help with

**Comment by troycrews** [comment]
@GSasu thanks for the quick reply!

My teammate found that replacing our AfterAll() call with AfterSuite() that calls a cleanup routine seemed to do the trick. Mocha was able to pick that up and generate the HTML. I'll keep your solution in mind if we run into problems in the future!

**Comment by yashrvy** [comment]
> mocha: {
>         reporterOptions: {
>             'codeceptjs-cli-reporter': {
>                 stdout: './output/result.xml',
>                 options: {
>                     verbose: true,
>                     steps: true,
>                 },
>             },
>             mochawesome: {
>                 stdout: './output/console/console.log',
>                 options: {
>                     reportDir: './output/mochawesome/',
>                     reportFilename: 'report',
>                     quiet: true,
>                     json: false,
>                     html: true,
>                     overwrite: true,

this helped me , thankyou
