### ISSUE TITLE
Test execution fails even if exception is caught using Protractor helper's grabTextFrom()

### ISSUE THREAD

**Issue by lepadellec** [Codeception/CodeceptJS#1478]
I am trying to grab text from a toast, clearly from time to time the test doesn't sync up with the toast and cannot grab the toast's content. I want to be able to catch such situations and to NOT fail test execution.
I am therefore enclosing my call to grabTextFrom() with a try / catch block, but even if the exception is encountered, the test ends.

Here is my code to read the text from the toast:
async getToastMessage() {
        try {
              const msg = await I.grabTextFrom(this.toastMessage);
              return msg;
        } catch(err) {
        }
        return '';
    }

I have also tried the following:
async getToastMessage() {
        try {
          const msg = await I.grabTextFrom(this.toastMessage);
          return msg;
        } catch(err) {
            return '';
        }
    }
Both examples end my test, I don't want test execution to be terminated. Please advise!

**Comment by lepadellec** [comment]
Any news here, it would be useful to be able to catch execptions within codeceptjs, please advise how to do this, particularly in asynchronous calls.

**Comment by PeterNgTr** [comment]
@lepadellec why don't you just do `I.grabNumberOfVisibleElements` and check if toast is there, do something, this won't cause the test execution to be terminated.

**Comment by lepadellec** [comment]
This did the job (code added to a Helper class):
async readToastMessage(){
  let ph = this.helpers['Protractor'];
  return new Promise(function(resolve, reject) {
    // Do async job
    ph.grabTextFrom('.toast-message')
    .then(function(toastMsg) {
      resolve(toastMsg);
    }).catch(function(err) { 
      reject(''); 
    })
  });
}
  
async getToastMessage () {
  let results = '';
  
  for (let i = 0; i < 10; i++) {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    this.readToastMessage()
    .then(function(str){
      if (!results.includes(str))
        results = results.concat(str);
    })
    .catch((err) => { 
    });
  }
  return results;
}
