### ISSUE TITLE
Cannot find selenium-webdriver module

### ISSUE THREAD

**Issue by AltarBeastiful** [Codeception/CodeceptJS#149]
I got a test project working fine using webdriverio. I tried selenium-webdriver and protractor but each time codecept is unable to find the selenium-webdriver module.

```
benoitre@lcybsdod:/d/testcodecept [qt-3.3 master]$ sudo -E npm install -g selenium-webdriver
/usr/lib
`-- selenium-webdriver@2.53.2 

benoitre@lcybsdod:/d/testcodecept [qt-3.3 master]$ codeceptjs run                           
CodeceptJS v0.3.5
Test root is assumed to be /home/ldap/benoitre/Projects/testcodecept

Could not load helper SeleniumWebdriver from module './helper/SeleniumWebdriver':
Required modules are not installed.

RUN: [sudo] npm install -g selenium-webdriver
```

Exact same behaviour with protractor. I tried to add the path where node install the module (`/usr/lib`) to NODE_PATH variable but it didn't work.
I also tried to install both module locally.

I'm on RH6 using node 6.x from Node entreprise repositories.

**Comment by DavertMik** [comment]
Sorry, looks like path guessing is not perfect.
Please try to install selenium-webdriver and codeceptjs locally to see if it works correctly.

**Comment by APshenkin** [comment]
close due inactivity
