### ISSUE TITLE
Multiremote in options

### ISSUE THREAD

**Issue by alfirin** [Codeception/CodeceptJS#15]
Is-it possible to implement the [multiremote](http://www.webdriver.io/guide/usage/multiremote.html) inside the WebDriverIO helpers options ?
WebdriverIO allows you to run multiple Selenium sessions in a single test.

Maybe, something like:

``` javascript
"helpers": {
    "WebDriverIO": {
      "url": "http://localhost:3000/#",
      "multiremote": {
        "myChromeBrowser": {
          "desiredCapabilities": {
            "browserName": "chrome"
          }
        },
        "myFirefoxBrowser": {
          "desiredCapabilities": {
            "browserName": "firefox"
          }
        }
      }
    }
  },
```

Thanks a lot for your work.

**Comment by DavertMik** [comment]
Right now I'm concentrated on more basic features.
If you have opportunity you can help getting this implemented faster )
But yes, this feature is in my personal roadmap.

**Comment by alfirin** [comment]
Sure, if you want I can help you develop some features.
Do you have some roadmap / blog / forums we can talk about them ?

Thanks for your work.

**Comment by DavertMik** [comment]
> Do you have some roadmap / blog / forums we can talk about them ?

Not yet :) But we can talk in Skype if it is an option: `davert.ua`. I should probably start Gitter chat as well

**Comment by DavertMik** [comment]
https://gitter.im/Codeception/CodeceptJS

**Comment by gokaygurcan** [comment]
Any update on this? It'd be really nice to use multiremote.

**Comment by DavertMik** [comment]
@gokaygurcan sure, it is there http://codecept.io/helpers/WebDriverIO/#multiremote-capabilities
