### ISSUE TITLE
I.checkFocusIsOn

### ISSUE THREAD

**Issue by cristian-sima** [Codeception/CodeceptJS#151]
Hi.

How can I check the focus of the page is on a particular input?

Thanks

**Comment by rezen** [comment]
You can extend functionality by adding your own custom helpers. Below is a quick example of how you would get started.

```
'use strict';

const assert = require('assert');

// Global set by codecept
const Helper = codecept_helper;

class MoreHelp extends Helper {

  checkFocusIsOn(selector) {
    const client = this.helpers['WebDriverIO'].browser;

    return client.elements(selector).then((res) => {
     // logic here ....
    });
  }
}

module.exports = MoreHelp;
```

**Comment by DavertMik** [comment]
Thanks @rezen

**Comment by yhoiseth** [comment]
Hi @DavertMik, 

I'm a bit lost on this. May I ask you to share how you ended up achieving `I.checkFocusIsOn()`?

**Comment by ezhlobo** [comment]
I came to this issue from google and found the direction here — use custom helper which will check if element has focus or not.

I managed to solve this issue for me with Playwright, but I believe the approach is applicable to other adapters:

```js
async seeElementIsFocused(selector) {
  const { Playwright } = this.helpers

  const numberOfElements = await Playwright.page.$$eval(selector, elements => elements.length, 0)

  assert.notStrictEqual(numberOfElements, 0, 'No elements')
  assert.notStrictEqual(numberOfElements > 1, true, 'Too many elements')

  const isActive = await Playwright.page.$eval(
    selector,
    element => element === document.activeElement,
    false,
  )

  assert.ok(isActive, 'Element is not active')
}
```

What matters here is that we compare `element` found with selector and `document.activeElement` (stands for currently focused element: https://developer.mozilla.org/ru/docs/Web/API/Document/activeElement).

How to use:

```js
I.amOnPage('/')
I.seeElementIsFocused('input[name="username"]')
```

Not sure if it's the best way to do the assertion, but I hope it will help you find out the approach for your tensions.

**Comment by Clindbergh** [comment]
Any idea how to achieve the same with locators instead of a css selector?
