### ISSUE TITLE
[Appium helper] I.sendDeviceKeyEvent and I.setOrientation didn't work anymore with webdriver@5.x.x

### ISSUE THREAD

**Issue by Solganis** [Codeception/CodeceptJS#1527]
#### What are you trying to achieve?
Subject is simple - I.sendDeviceKeyEvent and I.setOrientation didn't work anymore with webdriver @5.x.x

#### What do you get instead?
```
Malformed type for "keycode" parameter of command sendKeyEvent
Expected: string
Actual: number

For more info see https://github.com/appium/appium-base-driver/blob/master/docs/mjsonwp/protocol-methods.md#appium-extension-endpoints
  
Scenario Steps:
  - I.sendDeviceKeyEvent(4) at Test.Scenario (tests/smokenext_test.js:22:5)
```

### Details

* CodeceptJS version: 2.x.x (2.0.6)
* NodeJS Version: 11.10.0
* Operating System: MacOS
* Protractor || WebDriverIO || Nightmare version (if related) webdriver @5.x.x
* Configuration file: doesn't matter

**Comment by Solganis** [comment]
@thanh nguyen (from slack CodeceptJS channel) helped me with this and he solve a problem with `I.sendDeviceKeyEvent();`
Solution is simple - put number inside single quotes .. 

Before - `I.sendDeviceKeyEvent(4);`
After -  `I.sendDeviceKeyEvent(‘4’);`
v4: http://v4.webdriver.io/api/mobile/deviceKeyEvent.html
v5: https://webdriver.io/docs/api/appium.html#sendkeyevent

but for I.setOrientation - “it seems that v5 doesn’t have same api for `setOrientation`“.
So there is still room to dig deeper.

**Comment by LukoyanovE** [comment]
There are no `setOrientation` in webdriverio 5
Maybe `rotate` will help you?

**Comment by Solganis** [comment]
@LukoyanovE does it not only for iOS? I am currently working on the Android platform.

**Comment by LukoyanovE** [comment]
You should describe either browser or app and platform in config.
No matter, ios or android

**Comment by Solganis** [comment]
@LukoyanovE I will try `rotate` then and come back with my experience with it :) Thanks.

**Comment by PeterNgTr** [comment]
https://webdriver.io/docs/api/appium.html#rotatedevice seems like it only supports iOS!

**Comment by mirao** [comment]
@PeterNgTr 
[WebDriver 5.7.3](https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#573-2019-03-17) fixes type for `pressKeyCode` (string => number).

However CodeceptJS uses `sendKeyEvent` ([deprecated?](https://github.com/admc/wd/issues/480)) instead of `pressKeyCode` in the Appium's helper method `sendDeviceKeyEvent`.

If I replace
```js
return this.browser.sendKeyEvent(keyValue);
```
by
```js
return this.browser.pressKeyCode(keyValue);
```
in `sendDeviceKeyEvent` method definition in `codeceptjs/lib/helper/Appium.js`, then `I.sendDeviceKeyEvent(4)` or `I.sendDeviceKeyEvent(187)` works well for me. So could it be possible solution?

**Comment by PeterNgTr** [comment]
https://github.com/Codeception/CodeceptJS/issues/1574

I‘ll update that in my PR.

**Comment by kashban** [comment]
Appearently driver.setOrientation sends the wrong parameters to the API. From my Appium-Logs:

> [0-0] 2019-05-07T06:51:30.492Z INFO webdriver: COMMAND setOrientation("LANDSCAPE")
> [0-0] 2019-05-07T06:51:30.492Z INFO webdriver: [POST] http://127.0.0.1:4724/wd/hub/session/1912f76c-5f97-49f0-88f7-04d2
> 54c9adc1/orientation
> [0-0] 2019-05-07T06:51:30.492Z INFO webdriver: DATA { engine: 'LANDSCAPE' }

But required is:

> [debug] [W3C (1912f76c)] Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted {"required":["orientation"]} and you sent ["engine"]

Sending the correct parameter to the API via axios works, so it still there but somehow with WDIO 5 not addressed properly.

```
    browser.addCommand('changeOrientation', orientation => {
      const apiUrl = `http://${this.config.appium.args.address}:${this.config.appium.args.port}`;
      axios({
        method: 'post',
        url: `${apiUrl}/wd/hub/session/${browser.sessionId}/orientation`,
        data: { orientation: orientation }
      });
});
```

> [debug] [W3C (d8968e74)] Responding to client with driver.setOrientation() result: "Rotation (LANDSCAPE LEFT) successful."
> [HTTP] <-- POST /wd/hub/session/d8968e74-d3e7-4f4d-82f2-b2b1f8637b03/orientation 200 202 ms - 49

So there is definately a bug somewhere between Appium and WDIO.

**Comment by PeterNgTr** [comment]
@kashban did you try with latest codeceptjs version? I believe the fix is live https://github.com/Codeception/CodeceptJS/pull/1574

**Comment by mirao** [comment]
Now `I.sendDeviceKeyEvent()` works as expected, e.g.: `I.sendDeviceKeyEvent(187);`
It requires a number argument and if you try to pass a string, you get the correct error:
"Malformed type for "keycode" parameter of command pressKeyCode, Expected: number, Actual: string"

Tested with CodeceptJS 2.3.6 and WebDriverIO 5.16.13
