### ISSUE TITLE
Clicking the second element found

### ISSUE THREAD

**Issue by matansh** [Codeception/CodeceptJS#153]
Hi all, im writing a test scenario where i need to click a button (simple right?) the thing is that there is another button in the screen that is identical to the one i want to click.

After a lot of searching online i have found that protractor allows to specify what element  you would like to click (or any other action) using- 
`element.all(by.css("button")).first()` or `.last()`

Does CodeceptJS support such functionality ? any help would be great :)

**Comment by rezen** [comment]
If you dig into the helpers documentation you can find the click directive.

http://codecept.io/helpers/WebDriverIO/#click

`I.click({css: '.parent button:first-child})`

**Comment by DavertMik** [comment]
Currently you can use XPath or CSS to point to the first or last elements.
