### ISSUE TITLE
autoLogin plugin In the case of async/await function

### ISSUE THREAD

**Issue by Umryuan** [Codeception/CodeceptJS#1544]
#### What are you trying to achieve?
Use autoLogin plugin In the case of using an async/await function to log in
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```js
Scenario('test-autoLogin', (I, login) => {
  login('tester');
  I.waitForText('tester', 3);
});
```

```bash
  test-autoLogin
    I am on page "/"
    I set cookie [{"domain":"accounts.xxx.com","expiry":1552990565.204357,"httpOnly":true,"name":"_session.sig","path":"/","secure":false,"value":"uN7sslnh_dFvUxFfXw2-xaKMMZ8"},{"domain":"a…
    I wait for text "tester", 3
 › <screenshotOnFail> Test failed, saving screenshot

```

> Provide test source code if related

This is my login Scenario:
```js
Scenario('login', async (I, loginPage) => {
  ...
  const verifycode = await I.getverifycode();
  ...
});
```

### Details

* CodeceptJS version: v2.0.6
* NodeJS Version: v11.5.0
* Operating System: Ubuntu16.04
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:
**codecept.conf.js**
```js
...
autoLogin: {
      enabled: true,
      saveToFile: true,
      inject: 'login',
      users: {
        tester: {
          login: async (I, loginPage) => {
                   ...
                   const verifycode = await I.getverifycode();
                   ...
                 },
          check: (I) => {
            ...
          }
        }
      }
    }
...
```

**Comment by Umryuan** [comment]
I know the way to use autoLogin. :100:
And this example has a little errors on syntax :bug:  ![example](https://i.loli.net/2019/03/06/5c7fa10c88743.png)

**Comment by yogainalift** [comment]
Why was this issue closed? The response was not touching the issue not even on one point.
I experience the same issues. If you use an async function for logging in, then the autologin plugin fails to execute in the correct order.
Please **investigate** before closing issues.

**Comment by yogainalift** [comment]
This issue talks about **async** functions. The reply has nothing to do with async functions. 
In cjs 2.2.0 this issue is solved.
