### ISSUE TITLE
No undef INtelij Idea

### ISSUE THREAD

**Issue by stychu** [Codeception/CodeceptJS#1549]
#### What are you trying to achieve?
I hate when my IDE screams for undefs. SO here I come. Im using Intelij Idea and it highlight me all the time `feature` `scenario` and newly added method for `steps_file` also custom helper is highlighting `Helper` extender. Can someone maybe point me how to solve this ? I tried to regenerate the defs but it doesnt help :(
#### What do you get instead?
<img width="439" alt="Zrzut ekranu 2019-03-9 o 00 43 06" src="https://user-images.githubusercontent.com/9383657/54062288-7400f400-4205-11e9-90f2-f0c16188c92f.png">

> Provide test source code if related

```js
`/// <reference path="./steps.d.ts" />

Feature('CHROME_TEST');

BeforeSuite((I) => I.loginAsBuyer());

Scenario('test something', (I) => {
    I.see('Set area')
});



Scenario('i can click area', (I) => {
    I.click('Set area', '#hierarchyLink');
    I.waitForRequestToFinish();
    I.wait(3)
});
`
```

### Details

* CodeceptJS version: 2.0.7
* NodeJS Version: 8.9.0
* Operating System: MAC OS
*  WebDriverIO

**Comment by Vorobeyko** [comment]
You may use [eslint-plugin-codeceptjs](https://www.npmjs.com/package/eslint-plugin-codeceptjs)

**Comment by stychu** [comment]
Silly me I didn't think of that... Thanks @Vorobeyko it works now.
