### ISSUE TITLE
CodeceptJS Protractor - one instance of the browser

### ISSUE THREAD

**Issue by DioNNiS** [Codeception/CodeceptJS#156]
By default each scenario starting new instance of the browser. Is there any chance to change it and run all scenarios and features in one instance of the browser?

P.S. this is performance concern.

**Comment by DioNNiS** [comment]
Is there any workaround for not reloading the browser?

**Comment by Nighthawk14** [comment]
Hey @DioNNiS did you find a solution for that?
Thanks!

**Comment by DioNNiS** [comment]
@Nighthawk14 no, thank you for RP.
