### ISSUE TITLE
Locator questions

### ISSUE THREAD

**Issue by GSasu** [Codeception/CodeceptJS#1573]
#### What are you trying to achieve?

Curiosities related to locators and if they can be used in various ways.
I am using WebDriver helper for my tests.
From past experience with wdio the way it manages locators is by using $ for single selection and $$ for an array of elements.

Does codeceptjs have something similar? How do you distinguish between single locators and locators in an array?.

I.e: I want to loop through an array of elements built based on a single selector.

is it enough to just do:
```js
exampleLocator: [ {css: '.some.class.of.an.element'} ]
OR
withLocate: [ locate('.some.locator').as('Buttons array') ]
```

more concise example:

```js
locatorArr: locate('.some.locator').as('Array of Ids')

locatorArr.forEach(element => {
    I.click(element);
})
```

Also for simplicity in wdio you can do simple calls such as 
```js
locator.click();
instead of 
browser.click(locator);
```

Is  there a possibility to make use of $ and $$ for easy migrations from wdio to codeceptjs and vice-versa?

Is this something that can be achieved with codeceptjs by any chance?

**Comment by goncalo1995** [comment]
Hey! were you able to solve the issue?
