### ISSUE TITLE
Run many scenarios in one feature.

### ISSUE THREAD

**Issue by SantoMarcelo** [Codeception/CodeceptJS#158]
I need to run many scenarios in one feature. When I execute the feature with many scenarios, the codeceptJs run the first scenario and close the browser, when go execute the second scenario do not open the browser to execute the steps.

**Comment by DioNNiS** [comment]
I believe this is a duplication of https://github.com/Codeception/CodeceptJS/issues/156

**Comment by ecampii** [comment]
I also have one feature file with several scenarios on it.  it gets run one at a time though.  it loads a window and closes it on each scenarios.  In my case its what I want it to since its scenario is an end to end.

**Comment by Nighthawk14** [comment]
Hey, same problem here, any chance you found any solution? :) Thanks!
