### ISSUE TITLE
Can I do calculations with CodeceptJS

### ISSUE THREAD

**Issue by TestdeTester** [Codeception/CodeceptJS#160]
Is it possible to do some calculations with CodeceptJS?

The following case occurred:
On page X: There is a price for a single product that is 10.
I want to grab the single price per product (so grabbing the number 10).
Then click on 2 products and check on another page if the value becomes (2*10) 20.

Same question for other calculations:)

Thanx in advance.

**Comment by DavertMik** [comment]
I think you can use on of the grabbers to get data, then use `yield` to execute JavaScript

```js
let price = yield I.grabTextFrom('#price');
let expectedPrice = price*2
```
