### ISSUE TITLE
Unable to attach a file on firefox

### ISSUE THREAD

**Issue by stychu** [Codeception/CodeceptJS#1628]
In my scenario, I have to attach a file which works fine on the chrome browser but when I run it on the firefox I am unable to attach a file. I get this message

```
File can't be transferred to remote server. Set `remoteFileUpload: false` in config to upload file locally.
this.browser.uploadFile is not a function
```

Setting `remoteFileUpload: false` would work but it breaks my logic of the scenario when a file is uploaded the spinner indicator shows on upload which would not show when I set the remotefielupload to false and thus break the test

**Comment by PeterNgTr** [comment]
well, seems like this method is only supporting chromium protocol: https://webdriver.io/docs/api/chromium.html#uploadfile

**Comment by marius-wieschollek** [comment]
This used to work before, so something has probably changed.

**Comment by stychu** [comment]
So how can I overcome this issue ???? @PeterNgTr have any ideas?  I suppose this should work across all supported browsers so this is kinda breaking bug for codeceptjs

**Comment by PeterNgTr** [comment]
https://webdriver.io/blog/2019/06/25/file-upload.html

> If you automate a browser that is running on a remote machine this approach won't work anymore because the file that is located locally (or wherever the tests are running) does not exist on the remote machine where the browser is running. For these scenarios the Selenium project created a file that is currently only supported when running Chrome or using a Selenium Grid with the Selenium standalone server.
