### ISSUE TITLE
How come none of your support tools for CodeceptJS work?

### ISSUE THREAD

**Issue by wmilton211** [Codeception/CodeceptJS#1635]
#### What are you trying to achieve?
The add-ons for Chrome dont work and are poorly implemented
The easytesting.io website has dead links (create an account, terms of service, privacy policy)
I've sent out 3 requests for demo from the website; no response

What gives? Are you guys in business? CodeceptJS is a great product but you gotta get the ancillary layers up to snuff.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Hi, sorry, EasyTesting.io is on hold right now. I'm trying to make some of its parts open sourced.
Sorry, again.
