### ISSUE TITLE
Puppeteer: downloadFile hangs

### ISSUE THREAD

**Issue by allquixotic** [Codeception/CodeceptJS#1637]
#### What are you trying to achieve?

I'm trying to use the Puppeteer helper's downloadFile method. It hangs.

#### What do you get instead?

I supply it with an XPath string for a very standard `<a>` link that downloads a file, then I see the file download in Chrome when running it with `show: true`; the file shows up on my filesystem under the download directory; but the downloadFile method hangs forever at the line `const xRequest = await new Promise((resolve) => { ...`. I copied the implementation of `downloadFile` to a local helper with a different name and put a `this.debug()` after every line of code, and the line that never gets reached (even after waiting about 15 minutes) is the line after `await`ing the xRequest.

My code is identical to the example in the 2.0.8 release notes. I have a Scenario with an `async (I) => { ... }` that calls a Step defined as `foo: async function(parm) { ... }`. There is nothing unusual or different about my code; the only other helper I have calls `page.setExtraHTTPHeaders` at the very beginning of the test suite. All of my steps are a boring and typical combination of `I.click()`, `I.wait()`, `I.fillField`, `I.attachFile`, etc. 

### Details

* CodeceptJS version: 2.1.0
* NodeJS Version: 11.14.0
* Puppeteer Version: 1.15.0
* Operating System: macOS Mojave
* Configuration file: Chrome invoked with `--no-sandbox --disable-setuid-sandbox`; waitForNavigation set to `networkidle2`; using codeceptjs-cli-reporter, mochawesome and mocha-junit-reporter, screenshotOnFail, stepByStepReport, autoDelay, retryFailedStep, almost all with default settings.

**Comment by allquixotic** [comment]
I confirmed that it hangs on RHEL 7.3 also, with a headless browser. So, the issue is *not* macOS-specific, and it is also reproducible when the browser is headless.

**Comment by DavertMik** [comment]
Yeah, happens with me too. Replaced `downloadFile` with `handleDownloads` in 2.1.4
See changelog https://codecept.io/changelog#214
