### ISSUE TITLE
dontSee with context fails when context not found

### ISSUE THREAD

**Issue by mattin4d** [Codeception/CodeceptJS#1646]
I'm not sure if this is intended behavior or not but when I have a dontSee with context and that context element doesn't exist on the page it fails.

```js
I.see('Foo Bar', '.alert'); // OK
I.click('.close-alert'); // removes .alert element
I.dontSee('Foo Bar', '.alert'); // FAILS: Element ".alert" was not found by text|CSS|XPath
```
I would expect this scenario to pass because it doesn't find the given text within the given context.

### Details
* CodeceptJS version: 2.1.0
* NodeJS Version: 10.15.3
* Operating System: Gentoo / Linux 4.19.27-r1
* WebDriverIO: 5.7.15

**Comment by PeterNgTr** [comment]
https://codecept.io/helpers/WebDriverIO#dontsee

@mattin4d 
I think that's the way it is. This is just to make sure the text is not presented on given element. Not to not see text on not found element.

**Comment by mattin4d** [comment]
I can accept that if truly the case.
Should in most scenarios be able to give higher context to dontSee.
