### ISSUE TITLE
how can I fail a test by throwing out an Error in page.on listener?

### ISSUE THREAD

**Issue by Manwzy** [Codeception/CodeceptJS#1649]
#### What are you trying to achieve?
I want to fail a test by throwing out an Error in a page.on listener's callback
#### What do you get instead?
the test still goes on 
> Provide console output if related. Use `--verbose` mode for more details.
![image](https://user-images.githubusercontent.com/28730927/57605077-6286f000-7598-11e9-9e70-1e888e465602.png)
![image](https://user-images.githubusercontent.com/28730927/57605123-80545500-7598-11e9-979d-4fcaf4cf5c6a.png)

**Comment by PeterNgTr** [comment]
@Manwzy Can you provide a sample repo which is easier to reproduce?
