### ISSUE TITLE
No uncheck checkbox command for Protractor and Nightmare

### ISSUE THREAD

**Issue by evgeniy-mh** [Codeception/CodeceptJS#1653]
#### What are you trying to achieve?

Uncheck checkbox using Protractor and Nightmare

#### What do you get instead?

I didn't found any commands in Protractor and Nightmare helpers that can uncheck checkbox.

### Details

* CodeceptJS version: 2.1.2

**Comment by PeterNgTr** [comment]
I guess you can do it referring to this https://github.com/Codeception/CodeceptJS/blob/371ce198e3a908b6eeb69d698da65a9c4e66c4bc/lib/helper/WebDriver.js#L896

**Comment by evgeniy-mh** [comment]
@PeterNgTr that you for your answer, but this issue it rather a feature request. It would be nice if CodeceptJS will have `uncheckOption` command implemented for all helper frameworks, not only for Puppeteer and WebDriver.

**Comment by PeterNgTr** [comment]
@evgeniy-mh I think it's possible, you can create a PR or I'll do when I have some times.

**Comment by PeterNgTr** [comment]
@evgeniy-mh it's ready. https://github.com/Codeception/CodeceptJS/pull/1654
