### ISSUE TITLE
support object API changed with 2.1.3 release

### ISSUE THREAD

**Issue by johnyb** [Codeception/CodeceptJS#1679]
#### What are you trying to achieve?

One of our support objects used to be an array. It looks similar to this:

```JavaScript
module.exports = ['user number 1', 'user number2'];
```

It's included as "users" and was used in tests:

```JavaScript
Scenario('Test login', function (users, I) {
    I.login(users[0]);
});
```

#### What do you get instead?

The support object is not an array any longer, after the upgrade to 2.1.3. Related commit would be https://github.com/Codeception/CodeceptJS/commit/314fcc13ed4ddbe80f8af3b6fb44712ff3aee12d - this changes the support object to always be an object and just copy all attributes using `Object.assign`. Regarding the commit message, I'm not sure this was intended. Especially since the upgrade was just on "patch level", not a major version bump.

### Details

* CodeceptJS version: 2.1.3
* NodeJS Version: any
* Operating System: any
* Configuration file:

```js
# relevant part is:
    include: {
        users: './e2e/users'
    }
```

Any hints on how to solve this issue? I'm totally fine with changing code on our side but currently have no clue on how to best solve this.

**Comment by DavertMik** [comment]
Ok, I will tell the reasoning and probably we can come up with the solution.

Here is the thing. I'm pushing the idea to use `inject` as a single way to require actors and support objects. However, this has issues when page object requires an actor or another page object which was not initialized yet. This way all objects initialized as empty objects so they can be referenced by others.

So maybe you may find a more elegant solution for this?

**Comment by johnyb** [comment]
> So maybe you may find a more elegant solution for this?

Sure :) It just means a larger change in our code base and I wanted to make sure this change was by intention. I'm all in for pushing the inject idea forward, since I really like the concept.

**Comment by johnyb** [comment]
Mhhh, after playing around with this a little more, I think there should be a very simple solution which does restore the old behaviour. Besides that, it's closer to actual dependency injection, because the reference to the original module is not lost. I'm going to test this a little more and open a MR with the change.
