### ISSUE TITLE
Mocha jUnit reporter file not created when path is specified

### ISSUE THREAD

**Issue by Nighthawk14** [Codeception/CodeceptJS#169]
When using mocha-junit-reporter with a specific path for the ouput file: 
`--reporter-options mochaFile=test-results.[hash].xml`

The file is not created.  It works fine when running tests directly with mocha and the command line like that :
`mocha --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/api/test-results.[hash].xml`

Not sure if the issue is with CodeceptJs but as it is working directly with mocha I think is good to get it here anyway.

ps: When the option is not specified the file is created but in root directory.

Thanks!

**Comment by DavertMik** [comment]
Thanks, I will take a look

**Comment by aldarund** [comment]
I have similar problem. But on circleci test results doesnt appear at all no matter what i try to do

**Comment by aldarund** [comment]
On windows test-results.xml appears when both specify env var and skipping it. On linux i cant make it create test no matter what, so i cant make it work on circleci

**Comment by aldarund** [comment]
Ok, even more. Sometime test result created, sometime they are not. same code same test. Its very unreliable.  And its not only with mocha junit. Also with other reporters like mocha-multi etc.

**Comment by DavertMik** [comment]
Fixed in #193
