### ISSUE TITLE
Cannot attach file

### ISSUE THREAD

**Issue by andra-voinea** [Codeception/CodeceptJS#170]
Filling in forms works, but not attaching files. For example on this page https://endouble.com/vacancies/vacancy-team-lead-support-team-endouble-amsterdam/
my code 
`I.attachFile('input[type="file"]', 'TestCVpdfSmall.pdf');`
passes but no file is attached
(I check this by I.see('THANKS FOR YOUR APPLICATION!') which doesn't show up, and in the screenshot I can see that the mandatory file was not attached and that is why.

**Comment by DavertMik** [comment]
What helper are you using? 
Where the file is located? 
Did you try to execute it in real browser, what do you see on screen?

**Comment by andra-voinea** [comment]
- helper: WebDriverIO
- file is located in same directory as codecept.json
I attach screenshots: 
<img width="1428" alt="screen shot 2016-07-27 at 23 51 10" src="https://cloud.githubusercontent.com/assets/14975098/17194419/3316545a-5458-11e6-8ff6-4d0cfde3cb58.png">
<img width="1435" alt="screen shot 2016-07-27 at 23 51 44" src="https://cloud.githubusercontent.com/assets/14975098/17194420/331b0eb4-5458-11e6-93f2-57d6a53ec849.png">


- i tried to use selenium server instead of phantomjs to test in real browser but i got connection refused (using firefox) - firefox tries opening but quits unexpectedly (i have to research more how to establish the connection)
Thank you very much!

**Comment by DavertMik** [comment]
Looks you are doing everything right. This could be an issue of PhantomJS (it is really bad in handling file uploads).

**Comment by DavertMik** [comment]
Btw you can try to use [Nightmare helper](http://codecept.io/nightmare/), modern alternative to PhantomJS. Maybe it will work better for you

**Comment by andra-voinea** [comment]
Thank you very much, I will let you know!

**Comment by andra-voinea** [comment]
i also tried running it in browser but still no file is uploaded (firefox didn't work, but it worked in chrome)

**Comment by DavertMik** [comment]
I have a guess that you are using some sort of JavaScript-based file uploader that is not handled by webdriver. Non-standard file uploader it is a problem, actually.

**Comment by andra-voinea** [comment]
yes, it is a standard upload. it is handled through gravity forms in wordpress..

**Comment by yogieputra8** [comment]
Hei, I'm having the same issue here https://github.com/Codeception/CodeceptJS/issues/483
