### ISSUE TITLE
Request to feature CodeceptJS on Docusaurus user page

### ISSUE THREAD

**Issue by ericbuss** [Codeception/CodeceptJS#1710]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) page.

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by DavertMik** [comment]
Sure https://codecept.io/img/logo.png
Thanks for reaching out!

**Comment by ericbuss** [comment]
Thank you sir!
