### ISSUE TITLE
Http calls interception Webdriver

### ISSUE THREAD

**Issue by stychu** [Codeception/CodeceptJS#1747]
Hello,
I'm using Codeceptjs along with WebDriverIO and looking for a way to intercept the http calls to be able to mock the response in some use cases. Is it possible with WebDriverIO or should I look for a solution maybe with Puppeteer ??

**Comment by PeterNgTr** [comment]
how about trying this service https://webdriver.io/docs/wdio-intercept-service.html

**Comment by stychu** [comment]
hmm After seetting up the config I get this:
```

Could not load plugin wdio from module './plugin/wdio':
Couldn't initialize service intercept from wdio plugin config.
It should be available either in '@wdio/intercept-service' package
```

**Comment by vitaly87** [comment]
any updates?

**Comment by idxn** [comment]
There is an on-going pull request to implement mock request using polly #1852
