### ISSUE TITLE
Stalling for some time trying to click links or buttons with 'data-' selector

### ISSUE THREAD

**Issue by yogainalift** [Codeception/CodeceptJS#1748]
Trying to click a button or link, selecting it with a data attribute takes too long on codecept 2.1.5 and 2.1.4. 
This behavior is not there on codecept 2.0.8. 
If you wrap the button with a locate then it works fast again.

> Related source code
```js
I.click(`button[data-test='my-button']`);
```

### Details

* CodeceptJS version: 2.1.4 | 2.1.5
* NodeJS Version: 10.15
* Operating System: linux, mac
* WebDriverIO: 5.6.0

**Comment by LukoyanovE** [comment]
how fast it works, when use `{ css: "button[data-test='my-button']" }` ?

**Comment by yogainalift** [comment]
@elukoyanov the `{css: ...}` solution works fast again. I guess this issue can be closed if people don't want to investigate the issue.

**Comment by yogainalift** [comment]
Narrowed it down to the :
`els = await locateFn(Locator.clickable.wide(literal));` line in WebDriver.js
and then this line in locator.js 
`.//*[@aria-labelledby = //*[normalize-space(string(.)) = ${literal}]/@id ]`
