### ISSUE TITLE
Using appium custom helper from docs, does not give access to appium functions, "is not a function" error occurs for most functions under appium docs. 

### ISSUE THREAD

**Issue by PHUITesting** [Codeception/CodeceptJS#1749]
What am I missing?

I'm trying to write a custom helper that checks for 4 elements, and then sends a different command based on which element is present.

In order to do this, we needed a custom helper per the codeceptjs documentation https://codecept.io/helpers/Appium.

So we call:

let client = this.helpers['Appium'].browser

But that unfortunatly does not work as documented, it does not give access to almost any of the Appium functions documented on their website http://appium.io/docs/en/about-appium/api/

So when we try:
```
async checkElement(locator) {
let client = this.helpers['Appium'].browser;
        let elementResult = await client.$$(locator).isEnabled();
}
```
All of these commands throw an error that says something like this:

client.$$(...).isEnabled is not a function

Per the codeceptjs docs... that should be an appium client with all of those functions included...

**Comment by LukoyanovE** [comment]
Appium helper is wrapper for WebDriverIO Appium wrapper

See all available functions here:
https://webdriver.io/docs/api/appium.html

**Comment by LukoyanovE** [comment]
`client.$$(locator)` returns an array of elements found.
Array in js does not have `isEnabled()` function.

Use `$` to find first element, or `map`/`filter`/`[<position of element in array, for example 0>]`

**Comment by PHUITesting** [comment]
Thanks for your help here are your ideas in my solution. It's working for me. 
``` /**
   * Checks the specified locator for existence, if it exists, attempt to click it
   * @param locator accepts xpath elements
   */
  async appiumClick(locator) 
  {
    let driver = this.helpers["Appium"].browser;
    let elementResult = await driver.$$(locator);
    if (elementResult === undefined || elementResult.length == 0) 
    {
      return console.log("Locator: " + locator + " Not Found");
    } 
    else if (elementResult[0].elementId) 
    {
      return await elementResult[0].click();
    }
  }```

**Comment by LukoyanovE** [comment]
Good

Now, you can close the issue
