### ISSUE TITLE
Crash when using xScenario with tag 

### ISSUE THREAD

**Issue by ngadiyak** [Codeception/CodeceptJS#1751]
if we mark test with `.tag('@tag');` as `xScenario`, codeceptjs throw  `TypeError: Cannot read property 'tag' of undefined`

Example:
```js
xScenario('title', async (I) => {
    ...
}).tag('ISSUE-001');
```

**Comment by VikalpP** [comment]
What version of codeceptJS are you using?

**Comment by ngadiyak** [comment]
@VikalpP 2.1.5

**Comment by VikalpP** [comment]
Sorry for the late response but I've found the problem behind it and fixed in # 1792. 😄
