### ISSUE TITLE
[Feature Request]: Mocking HTTP/HTTPS Requests/Responses.

### ISSUE THREAD

**Issue by deepak-monotype** [Codeception/CodeceptJS#1771]
1. Can we have support for API mocking with Webdriver?
2. In existing api mocking with Puppeteer, need below mentioned supports -
   a> Mocking based upon condition like query parameters.
   b> Wait for mocked request to respond. This means first my request should get mocked but wait to return the response until I have executed few more steps on webpage.

**Comment by PeterNgTr** [comment]
this would fulfil your need https://codecept.io/webdriver#mocking-requests
