### ISSUE TITLE
Couldn't initialize service intercept from wdio

### ISSUE THREAD

**Issue by deepak-monotype** [Codeception/CodeceptJS#1774]
I am getting below error while trying to run wdio - intercept service. 

npx codeceptjs run.

Could not load plugin wdio from module './plugin/wdio':
Couldn't initialize service intercept from wdio plugin config.
It should be available either in '@wdio/intercept-service' package

**Comment by PeterNgTr** [comment]
you can try the mocking request for now https://codecept.io/webdriver#mocking-requests
