### ISSUE TITLE
[Feature Request]: Mock part of data WebdriverIO 

### ISSUE THREAD

**Issue by vitaly87** [Codeception/CodeceptJS#1781]
#### What are you trying to achieve?

Hi
 I want a way to mock all data or paper of data on response from server and be able to stop the mock when needed.

**Comment by cviejo** [comment]
Do you specifically need to use webdriverio? Sounds like you could accomplish exactly that using the polly and puppeteer helpers

**Comment by vitaly87** [comment]
I started my project with webdriverio as I understand I cant mix it with puppeteer helper...

**Comment by cviejo** [comment]
Hm..you can sure mix them and/or exchange them. For most cases it should just work.

**Comment by vitaly87** [comment]
It's to general... can you give example...how to do call and change it also how to stop if wanted

**Comment by cviejo** [comment]
You mean the polly part? You decide what to mock for a test and call `I.stopMocking()` when done. [The docs](https://codecept.io/helpers/Polly#docsNav) are pretty straightforward.

**Comment by vitaly87** [comment]
This mock is not supported by webdrio

**Comment by PeterNgTr** [comment]
@vitaly87 why don't you separate those tests that need to be executed with mock data to run against puppeteer?

**Comment by vitaly87** [comment]
To separate it will be bad , because I have a lot helpers that using webdriver. I think need some how to implement the mock with supporting webdriver.

**Comment by PeterNgTr** [comment]
https://webdriver.io/docs/wdio-intercept-service.html#browsersetupinterceptor
wdio provides this service, however, codeceptjs is not fully working with all of the services. Waiting for someone to make it work 💪

**Comment by vitaly87** [comment]
Wow that looks nice did you check it? Is it working on webdriver ?

**Comment by PeterNgTr** [comment]
@vitaly87 I tried to load with service but it's not working. So codeceptjs service should make some changes, I think.

**Comment by PeterNgTr** [comment]
it's there https://codecept.io/webdriver#mocking-requests
