### ISSUE TITLE
In v2.2.0 broken generating the typescript definitions for PageObject (and another supports)

### ISSUE THREAD

**Issue by Vorobeyko** [Codeception/CodeceptJS#1795]
#### What are you trying to achieve?
I trying generate typescript definitions 

#### What do you get instead?
For Support object not generated definitions

And broken `container.support()`. It not return support object

It happened after https://github.com/Codeception/CodeceptJS/pull/1701 

### Details

* CodeceptJS version: 2.2.0
* NodeJS Version: 
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    Puppeteer: {
      url: 'http://localhost'
    }
  },
  include: {
    I: './steps_file.js',
    public: './pages/public.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'test-support-def'
}
```

**Comment by Vorobeyko** [comment]
@johnyb Can you help fix it?

**Comment by johnyb** [comment]
I don't have a clue, but I'll give it a try tomorrow :) Thanks for bringing this to my attention!

**Comment by johnyb** [comment]
At least I got a broken test, now … :)

**Comment by Vorobeyko** [comment]
@johnyb  Good! Thanks for help!
