### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by DavertMik** [Codeception/CodeceptJS#1808]
For Data management we need a GraphQL helper which operates similarly to REST. 

Such helper should be able to:

* receive data from GraphQL
* save data to GraphQL 
* delete data from GraphQL

So there should be 2 methods:

* `I.sendQuery()`
* `I.sendMutation()`

Query and mutations can be put inline as string or taken from a file. Connection to GraphQL should be set in config, similarly as how it is done to REST.

Later we will need to think how this can be combined with ApiDataFactory

**Comment by radhey1851** [comment]
Hi!
I will be taking up this issue.

**Comment by PeterNgTr** [comment]
isn't it supported by axios to make grapql call? (https://medium.com/@stubailo/how-to-call-a-graphql-server-with-axios-337a94ad6cf9)

**Comment by DavertMik** [comment]
Probably yes.
