### ISSUE TITLE
amOutsideAngularApp is printing the Webdriver Object in console output

### ISSUE THREAD

**Issue by abner** [Codeception/CodeceptJS#181]
As we would  see in [lib/helper/Protractor.js](https://github.com/Codeception/CodeceptJS/blob/704a7fe12651cc38d15fd1a35074a89bd3e2e8e9/lib/helper/Protractor.js#L167) the call to  `amOutsideAngularApp` is printing the `Webdriver` Object in console output

![image](https://cloud.githubusercontent.com/assets/42773/17342475/e4139616-58cf-11e6-913a-fc210e18f29f.png)

**Comment by DavertMik** [comment]
Could you send it as PR to Codeception/CodeceptJS? ;)

**Comment by abner** [comment]
Threre is a channel where i would ask few questions about codecept to you?

I work as a System Analyst in the major Governament IT Company in  Brasil, called [SERPRO](http://www.serpro.gov.br/). Actually i'm working  as a consultant in web frontend technologies (at this time AngularJS, Angular 2 [both Javascript and Typescript])   and yesterday casually i found the codecept project and quickly tried it and liked so much.


I would like to use the navigation helper methods in Brazillian Portuguese, so this tests scenarios will serve as our stories documentation too. 

I just came out with this setup:

1 - In the codecept.json file i include a step file like this:

```
"include": {
    "Eu": "./e2e/steps/steps_file.js"
  },
```

> `Eu` is `I` in portuguese

And in the steps_file i created proxy methods in portuguese just calling the corresponding methods:

```
 estouNaPagina: function(url) {
      return this.amOnPage(url);
 },
 
vejo: function(text) {
   return this.see(text);
},

naoEstouEmAplicacaoAngular: function() {
    return this.amOutsideAngularApp();
 }
```

There is some path into the codeceptjs to achieve the translation of all the helpers methods codecept already provides?
