### ISSUE TITLE
 url.substr is not a function using Polly and I.mockRequest

### ISSUE THREAD

**Issue by loadbrain** [Codeception/CodeceptJS#1815]
#### What are you trying to achieve?
I call I.mockRequest("/google-analytics/*path", 200);

#### What do you get instead?
     url.substr is not a function

  Scenario Steps:
I call I.mockRequest("/google-analytics/*path", 200);

> Provide console output if related. Use `--verbose` mode for more details.

```bash
    url.substr is not a function

  - I.mockRequest("/google-analytics/*path", 200) at Test.<anonymous> (Wiley_test.js:11:6)
```

### Details

* CodeceptJS version: 2.2.1
* NodeJS Version: 12.7.0
* Operating System: Windows 10
* Puppeteer || Polly
* Configuration file:

**Comment by VikalpP** [comment]
You need to pass the HTTP method of that Url
like, 
```
I.mockRequest('GET', '/google-analytics/*path', 200)
                ^
```

For more context checkout official [doc](https://codecept.io/helpers/Polly#mockrequest).

**Comment by loadbrain** [comment]
Thanks!
And sorry...
