### ISSUE TITLE
I need to understand the proper way to implement the grab API . because of async manner I couldn't able to handle it . 

### ISSUE THREAD

**Issue by sumiagar** [Codeception/CodeceptJS#1817]
I am trying to get the text from one place and verify it in second place. 

#### I am getting promise object instead of grabbed text 

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
Scenario('FAV add & deletion from MIni guide and verify from settings fav list',(I) => {
    var text = "";
    I.navigateTo('watchTv')
    //for (var i =0 ; i<2;i++)
    {
           text = I.grabTextFromXpath();
           console.log("Sumiran within :: Channel name and number "+text); 
           I.navigateTo('watchTv','options','addChannel');
            I.pressKey("Enter")
            console.log("after within :: Channel name and number "+text);
            I.navigateTo('settings','favorites','favoritesList')
            within({frame: "#SETTINGS"},() => {
                console.log("before checking:: Channel name and number "+text);
                I.seeTextEquals(text,'//*[@id="secondSubMenuList"]/div[2]/p[1]');
            })
    }
});

In Custom step file, I have written the function 
 grabTextFromXpath : function() {
        var text;
          within({frame: "#ZAPPER"}, async() => {
          text = await I.grabTextFrom('//*[@id="animatedMiniguide"]/div[6]/div[1]/span[1]');
          console.log("EXACT :: Channel name and number "+text);
              
      });
      return text;
        }
```

### 
In my test I am not getting text variable data. 

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by PeterNgTr** [comment]
I guess you can try to write your method using async:
```
async function grabTextFromXpath()
...
```

Then in your test file:
```
Scenario('FAV add & deletion from MIni guide and verify from settings fav list', async (I) => {
    var text = "";
    I.navigateTo('watchTv')
    //for (var i =0 ; i<2;i++)
    {
           text = await I.grabTextFromXpath();
           console.log("Sumiran within :: Channel name and number "+text); 
...
```

**Comment by sumiagar** [comment]
> I guess you can try to write your method using async:
> 
> ```
> async function grabTextFromXpath()
> ...
> ```
> 
> Then in your test file:
> 
> ```
> Scenario('FAV add & deletion from MIni guide and verify from settings fav list', async (I) => {
>     var text = "";
>     I.navigateTo('watchTv')
>     //for (var i =0 ; i<2;i++)
>     {
>            text = await I.grabTextFromXpath();
>            console.log("Sumiran within :: Channel name and number "+text); 
> ...
> ```

Same thing happened , 

because of async function, I got the text result in later stage and code executed first .

**Comment by cviejo** [comment]
Check the docs for [within](https://codecept.io/basics#within), please. There's an example about how to return a value.

**Comment by sumiagar** [comment]
Many Thanks to all . .
