### ISSUE TITLE
`mocha` dependency triggers security alert for `diff`

### ISSUE THREAD

**Issue by kevinzang** [Codeception/CodeceptJS#1823]
#### What are you trying to achieve?

I am trying to resolve a security alert that I'm getting from GitHub.

#### What do you get instead?

I am getting a GitHub security alert in my repo that is using CodeceptJS.

### Details

I used `yarn` to install CodeceptJS. My yarn.lock file has:

```
diff@3.3.1:
  version "3.3.1"
```

which is triggering the following GitHub security alert:

-----

Remediation
Upgrade diff to version 3.5.0 or later. For example:

```
diff@^3.5.0:

  version "3.5.0"
```

Details
WS-2018-0590
high severity
Vulnerable versions: < 3.5.0
Patched version: 3.5.0
A vulnerability was found in diff before v3.5.0, the affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) attacks.

-----

As I understand, the reason I'm getting this alert is most recent version of CodeceptJS says it needs `mocha "^4.1.0"`:

https://github.com/Codeception/CodeceptJS/blob/48bd379421156275fda4dba2420190ee429ef497/package.json#L59

All mocha 4.x versions use `diff@3.3.1`:

https://github.com/mochajs/mocha/blob/6b9ddc64e27d8700aa6d2cc8d0bb4b47b32d6768/package.json#L316

The earliest version of mocha that uses `diff>=3.5.0` is `mocha@6.0.0`:

https://github.com/mochajs/mocha/blob/42303e2acba217af554294b1174ee53b5627cc33/package.json#L496

So I guess in this repo, the options are
1) upgrade mocha to `>=6.0.0`, or
2) maybe mocha can be moved to devDependencies, if it's only being used to run tests for CodeceptJS itself?

**Comment by pablopaul** [comment]
@kevinzang there is already a PR in progress, see !1802
