### ISSUE TITLE
How can I verify the icon image 

### ISSUE THREAD

**Issue by sumiagar** [Codeception/CodeceptJS#1832]
#### I have explored to any API like I.seeEqualText() is there same kind of API to verify the Image Icon .

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by xMutaGenx** [comment]
This is probably best asked in the forums... Have you looked into visual testing helpers? I believe that's what you're looking for https://codecept.io/visual
