### ISSUE TITLE
[CLI]: Having a dedicated command to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [Codeception/CodeceptJS#1838]
Instead of asking the user to manually provide information concerning his local environment, we could employ a dedicated command `codeceptjs info` which shows up the respective information and the `ISSUE_TEMPLATE` can be updated accordingly.

**Comment by jamesgeorge007** [comment]
Happy to submit a PR :clap: 
cc @pablopaul

**Comment by jamesgeorge007** [comment]
Check out [envinfo](https://npmjs.com/package/envinfo)

**Comment by DavertMik** [comment]
Thanks, a good idea. Please send PR!
