### ISSUE TITLE
remove experimental detox-helper from required dependencies

### ISSUE THREAD

**Issue by RohanHart** [Codeception/CodeceptJS#1840]
#### What are you trying to achieve?
I don't need detox at the moment

#### What do you get instead?
detox-helper is installed along with native build for dtrace-provider

### Details

* CodeceptJS version: 2.2.1

**Comment by DavertMik** [comment]
Sorry, my bad. Detox helper was never expected to be a direct dependency in CodeceptJS but accidentally landed in package.json. Thanks, I will fix this in next release

**Comment by DavertMik** [comment]
Fixed in 2.3.0
