### ISSUE TITLE
Dockerfile in codecept needs to be updated to node 12.8.0 to use workers

### ISSUE THREAD

**Issue by emmonspired** [Codeception/CodeceptJS#1853]
Recently the run-workers feature was added to Codecept, but the current Dockerfile in master points to using node 10. This is incompatible with node workers and needs the most updated version.

**Comment by PeterNgTr** [comment]
so Dockerfile has been updated. https://github.com/Codeception/CodeceptJS/blob/master/Dockerfile#L1

**Comment by emmonspired** [comment]
Thank you sir @PeterNgTr
