### ISSUE TITLE
`codeceptjs def` cannot generate definitions for custom helper

### ISSUE THREAD

**Issue by quekshuy** [Codeception/CodeceptJS#1857]
#### What are you trying to achieve?

Trying to generate definitions for a custom helper using `codeceptjs def`.

#### What do you get instead?

An error message on the console. 

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Could not load helper MyHelper from module '/Users/myuser/codeceptjs/src/my_helper.js':
HelperClass is not a constructor
```

> Provide test source code if related

```js
const Helper = codeceptjs.helper;
class MyHelper extends Helper {
  help() {}
}
module.exports = MyHelper;
```

### Details

* CodeceptJS version: 2.3.0
* NodeJS Version: 10.16.0
* Operating System: macOS 10.14.5
* Protractor || WebDriverIO || Nightmare version (if related): TestCafe 1.3.3 (probably unrelated)
* Configuration file:

```js
exports.config = {
  tests: './src/**/*.spec.js',
  output: './output',
  helpers: {
    TestCafe: {
      url: 'https://google.com',
      browser: 'chrome',
      show: true
    },
    MyHelper: {
      require: './src/my_helper.js',
    }
  },
  bootstrap: null,
  mocha: {},
  name: 'myhelpertest'
}
```

**Comment by quekshuy** [comment]
Probably has to do with my code. Closing.

**Comment by ekolga** [comment]
Duuude, you should have written your issue here!

**Comment by nicostubi** [comment]
+1
