### ISSUE TITLE
"fuzzy" locators benchmark

### ISSUE THREAD

**Issue by mbelsky** [Codeception/CodeceptJS#1890]
Hey,

I've found an interesting note in locator docs:

> Be warned that fuzzy locators can be significantly slower than strict locators. If speed is a concern, it's recommended you stick with explicitly specifying the locator type via object syntax.

Do you have any benchmarks for that or more detailed description?

**Comment by DavertMik** [comment]
No benchmarks, sorry, they may vary for an HTML page and a locator.

But where a strict locator or XPath/CSS locator will use exactly one query to a browser to find an element, a fuzzy locator can perform up to 4 queries (with complex xpaths) to find an element.

**Comment by mbelsky** [comment]
Got it, thank you!
