### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by Jafo232** [Codeception/CodeceptJS#1893]
I am trying to run tests on a realm that requires basic auth.  I see it sort of explained here: https://github.com/Codeception/CodeceptJS/issues/305  however, this does cause issues when trying certain assertions like "I.seeCurrentUrlEquals" and trying to use the relative path as it will not contain the basic auth credentials.  Is there any other way to configure basic auth?

**Comment by webaggregat** [comment]
hi there:
unfortunately #305 works realy not for me

**Comment by PeterNgTr** [comment]
https://github.com/Codeception/CodeceptJS/pull/1962 solved this hopefully.
