### ISSUE TITLE
[regress] I.executeScript() Evaluation failed

### ISSUE THREAD

**Issue by storenth** [Codeception/CodeceptJS#1894]
#### What am I trying to achieve?
Execute script in `test.js` via built in `executeScript`
```javascript
// css like selector
let myArg = '[data-test-selector="news"] [data-test-id="701340"]';
let element = await I.executeScript(function(selectorLocator){
       return document.querySelector(selectorLocator);
    }, myArg);
```
#### What do I get instead?
```bash
Error: Evaluation failed: DOMException: Failed to execute 'querySelector' on 'Document': : '[object HTMLBodyElement]' is not a valid selector.
    at __puppeteer_evaluation_script__:3:35
```
### Details
Found this Regress after upgrade to `puppeteer 1.20.0`, because of `1.19.0` successfully executed same test scenario.
* CodeceptJS version: 2.3.1
* NodeJS Version: v12.2.0
* Operating System: Ubuntu 18.04.3 LTS
* Puppeteer 1.20.0

#### Workaround
1. Use `executeScript` without parameter:
```javascript
let selector = await I.executeScript(function(){
        return document.querySelector('[data-test-selector="news"] [data-test-id="701340"]');
    });
```
2. Downgrade to `"puppeteer": "~1.19.0"`

**Comment by DavertMik** [comment]
Yes, we saw this in our CI server. 
Will work on a fix today

**Comment by orihomie** [comment]
Hi, I have same problem on codecept+TestCafe but with this code: 
```javascript

        emailFooter: {
		email: "//*[id='email']",
		sendEmail: "//*[id='email']/following::button",
		close: "//*[id='email']/following::div[4]"
	},

	saveCurrentOrderStateByEmail(email) {

		I.waitForVisible(this.emailFooter, 1);
		I.see(this.emailFooter.email);
		I.fillField(this.emailFooter.email, email);
		I.click(this.emailFooter.sendEmail);
		I.dontSee(this.emailFooter.email);
		I.waitToHide(this.emailFooter.email, 1);
	}
```

> SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '//*[id='email'],//*[id='email']' is not a valid selector.

I've tried both 'id' and '@id' - exception generated in both cases.
