### ISSUE TITLE
When using webdriverio helper configured for saucelab scenario name not passed to saucelab

### ISSUE THREAD

**Issue by aldarund** [Codeception/CodeceptJS#190]
In saucelab all test are named as Unnamed job instead of scenario name
http://c2n.me/3AW2fsa
its not very easy to find right test when there no name for it.
Is there a way to pass scenario name to saucelab ?

**Comment by aldarund** [comment]
To do this its needed to pass `name` param to the desiredCapabilities of webdriver.io
I tried to do it in _before but despite in jsdoc its specified that test param is passed, its not passed, so i cant get a test name there.

**Comment by DavertMik** [comment]
Yes, unfortunately due to restrictions in mocha I didn't manage to run `before`/`after` hooks inside a test, so they do not have test name in it. I will think how this can be improved

**Comment by DavertMik** [comment]
To be honest I'm not sure how to make it work. Browser session is started before the actual test executed, and probably desired capabilities can't be updated during test execution.

**Comment by cnworks** [comment]
I have the same problem trying to give meaningful names to sessions on browserstack.

The most promising approach was to create a custom helper and set the name in the _before() or _beforeSuite() hook.
`this.helpers["WebDriverIO"].options.desiredCapabilities.name = "foo";`
Unfortunately I couldn't find a solution to access the name of the suite/feature or the scenario. Also  be aware that this solution depends on the sorting in the configuration file, cause it needs to be run before the WebDriverIO Helper _before() / _beforeSuite() hook.

Maybe someone can improve on that.

**Comment by APshenkin** [comment]
https://github.com/Codeception/CodeceptJS/issues/190
