### ISSUE TITLE
Docker image uses old version of node

### ISSUE THREAD

**Issue by triforcely** [Codeception/CodeceptJS#1900]
It seems that CodeceptJS docker image depends on Node 10.14.0, therefore "run-workers" functionality cannot be used there. Could this be updated or do you use current LTS versions for your images?

**Comment by PeterNgTr** [comment]
you're right it's 10.14.0 as you can see it here https://github.com/Codeception/CodeceptJS/blob/master/Dockerfile#L1

maybe you could create a PR to bump the node version for docker image.
