### ISSUE TITLE
How to handle Basic-Authentication required popup please

### ISSUE THREAD

**Issue by webaggregat** [Codeception/CodeceptJS#1901]
#### What am i trying to achieve?
hi there, i am beginning test-automation at Test-stage. There is an Basic-auth.
I have to trouble you because i am still far away from resolving my problem by myself

#### My problem is:
I have a problem with htaccess-Authentication popup. How to input username and password into the Authentication popup with codeceptjs sdk automatically?
#1893, #305 unfortunately realy has not any effect.
- Please help me to resolve this issue.
![2019-09-24 10_58_45-VirtualBox](https://user-images.githubusercontent.com/31275529/65503190-af72bf80-dec4-11e9-9201-a4113a334104.png)

#### What do i get instead?
![2019-09-24 12_15_06-Filme   TV](https://user-images.githubusercontent.com/31275529/65503351-0b3d4880-dec5-11e9-91b9-c7b070b10cc8.png)

### Details
* CodeceptJS version:
(?) How to figure out that: codeceptjs --version not working in console
* NodeJS Version: 10.16.3
* Operating System: ubuntu lts 18.xy
* Protractor || WebDriverIO || Nightmare version (if related)
(?) How to figure out that: webdriverio --version not working in console

## Thanks in advance!

**Comment by PeterNgTr** [comment]
hey @webaggregat I'm also using basic-auth embedded in url, and it's working fine.

**Comment by idxn** [comment]
I think the reason is that the server redirect you to www.autode-dev.de. Try set url in config to https://user:password@www.autode-dev.de

**Comment by webaggregat** [comment]
thnx! @PeterNgTr and @idxn 

@idxn:
Your aprovement is correct, and it works in my Vbox for the testrunner
May i ask U: Why your aprovement works for codeceptjs But if I start an fresh google-chrome and surf your https://usr:pwd@www.autode-dev.de with hand the basic-auth-popup occures and has to be filled
(?) how codecept.js is doing this?

**Comment by idxn** [comment]
Actually, codeceptjs doesn't do anything specific. It's just the chrome api doing that. The reason you open manually doesn't work is probably how chrome handle the human input on the locatioin bar.

**Comment by webaggregat** [comment]
tippitoppi (thnx)
