### ISSUE TITLE
The config file need to accept regex if multiple step definition file are there  

### ISSUE THREAD

**Issue by kkarthickom** [Codeception/CodeceptJS#1911]
#### What are you trying to achieve?
The config file need to accept regex if multiple step definition file are there  as of now we need to mention all the stepdef files in the config file, which makes the config bulkier. Please support this feature.
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

### Details

* CodeceptJS version:2.3.1
* NodeJS Version:10.16.3
* Operating System: Windows 10,MAC
* WebDriverIO 
* Configuration file:
gherkin: {
    features: './features/*.feature',
    steps: [
      './step_definitions/login_stepdefs.js',
      './step_definitions/login_department_stepdefs.js',
      './step_definitions/ax_test_stepdefs.js'
    ]
  },

**Comment by kkarthickom** [comment]
could any one help with this issue.

**Comment by vatsan34** [comment]
This feature has been added via this [PR](https://github.com/Codeception/CodeceptJS/pull/2043).
