### ISSUE TITLE
command $codeceptjs gh worksnot but $npx codeceptjs gh works (why?)

### ISSUE THREAD

**Issue by webaggregat** [Codeception/CodeceptJS#1918]
Hi ccjs-team,
for my first setup of codeceptjs i followed P.V. Beigangs practical guide which is linked as tutorial at codecept.io. 
So I can run my first automation steps with command:
And i would like to mention I use this command without _knowing_why_ using this _npx_
```
$ npx codeceptjs run ...
```

So, please dont feel fooled by my **question** (Until now I dont have better ones)

### What I am trying to achieve:
- I try to build a custom helper based on Codeceptjs Helper docu [CodeceptJS - Helpers](https://codecept.io/helpers#webdriver-example)
- For that in your doku is written:
Helpers can be created by command:
```
codeceptjs gh
```

### My Problem is (question):
- but this command is not running for me:
```
codeceptjs gh
```
inspite of i´m in right folder codeceptjs says in console: command not found

## Question
**Why command _codeceptjs gh_ is not running but _npx codeceptjs_ is running?**
 
### Details
* CodeceptJS version: 2.3.0

**Comment by PeterNgTr** [comment]
Hi, cause you’re doing the npm i which is installed everything locally in your project, under node_modules. You can try to do npm i -g to install everything globally. And then you can use codeceptjs run as you wish.

**Comment by webaggregat** [comment]
thnx @PeterNgTr 
i realy did not expect an answer about 'i'.. then i undertstood.
thnx for your replay
