### ISSUE TITLE
Test results not always generated 

### ISSUE THREAD

**Issue by aldarund** [Codeception/CodeceptJS#192]
Test results from both junit and mochawesome not always generated. They like 3 times they are generated, one time not. Same code same test. Nothing changed. Was running on local selenium first on circleci with such behaviour,  now switched to saucelab and still same and i see following in saucelab ->
http://c2n.me/3AVOMQm so it seems codecept somehow lost connection\stuck for some reason sometime on test and this leads to no test results at all.

**Comment by DavertMik** [comment]
Currently I'm not able to reproduce them. Probably my last pacthes will accidentally fix this )

**Comment by aldarund** [comment]
@DavertMik let me know when i can test this patches and see if it resolves the issue.

**Comment by aldarund** [comment]
@DavertMik have today same issue with browserstack . http://c2n.me/3B9SiUe
No test results were generated  ( only assets from mochaawesome but no actual report files)

**Comment by Zougi** [comment]
This PR might help https://github.com/Codeception/CodeceptJS/pull/263
