### ISSUE TITLE
Use of 'session'

### ISSUE THREAD

**Issue by orihomie** [Codeception/CodeceptJS#1922]
I'd like to open a link which I recieve by email during my test in another browser (nor current) and for that purpose I'm tryin to do (codecept on testCafe)

```js
session('Open link from mail', { browser: 'chrome' },  () => {
		I.amOnPage(href);
	});
```

but that fails with 
> Configured helpers do not support starting sessions. Please use a helper with session support.

I cant google anything on that, could you explain me whats going on here?

**Comment by PeterNgTr** [comment]
cause `TestCafe helpers do not support starting sessions. Please use a helper with session support.` 😄
