### ISSUE TITLE
Webdriver + docker => Error: not found: java

### ISSUE THREAD

**Issue by jbellmore** [Codeception/CodeceptJS#1928]
#### What are you trying to achieve?
I am trying to run tests using Codecept/Webdriver utilizing the codeception/codeceptjs docker image. Testing using both chrome and firefox.

#### What do you get instead?

Whenever I run my tests, the first test to execute errors out with the following:

```bash
✖ "before all" hook: codeceptjs.beforeSuite for "User logs in with valid username & password" in 812ms              Error: not found: java 
```

This happens regardless which test executes first (tested by commenting out all but one test).

### Details

This is due to the docker image not having a java runtime installed. I am able to test and fix the issue by installing a jre in the container on startup.

Obviously this can be fixed by creating your own docker image using the one you guys provide as a base but it might make sense to include a JRE in the base image as well, or at least provide a separate image on a specific tag that does contain it.

Having to manage your own Docker image and keep it up to date when you release new versions can be a tedious task so it would be a lot more convenient if there was a pre-baked image that had everything needed to run Webdriver based tests.

Btw, loving the framework!

Thanks!

**Comment by PeterNgTr** [comment]
@jbellmore so I created a PR to install java. Hope this helps :)
