### ISSUE TITLE
codeceptjs init error

### ISSUE THREAD

**Issue by PeterNgTr** [Codeception/CodeceptJS#1930]
#### What are you trying to achieve?
Trying to using `codeceptjs init` to initiate the project.

#### What do you get instead?

```js
Thanhs-MacBook-Pro:applitools-example thanhnguyen$ npx codeceptjs init

  Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

Installing to /Users/thanhnguyen/Desktop/applitools-example
? Where are your tests located? ./*_test.js
? What helpers do you want to use? WebDriver
? Where should logs, screenshots, and reports to be stored? ./output
? Would you like to extend the "I" object with custom steps? Yes
? Where would you like to place custom steps? ./steps_file.js
? Do you want to choose localization for tests? English (no localization)
Configure helpers...
? [WebDriver] Base url of site to be tested https://applitools.com/helloworld
? [WebDriver] Browser in which testing will be performed chrome

Steps file created at /Users/thanhnguyen/Desktop/applitools-example/steps_file.js
Config created at /Users/thanhnguyen/Desktop/applitools-example/codecept.conf.js
Directory for temporary output files created at './output'
Intellisense enabled in /Users/thanhnguyen/Desktop/applitools-example/jsconfig.json
(node:18259) UnhandledPromiseRejectionWarning: Error: Could not load helper WebDriver from module './helper/WebDriver':
Required modules are not installed.

RUN: npm install --save-dev webdriverio@^5.2.2
    at createHelpers (/Users/thanhnguyen/Desktop/applitools-example/node_modules/codeceptjs/lib/container.js:153:13)
    at Function.create (/Users/thanhnguyen/Desktop/applitools-example/node_modules/codeceptjs/lib/container.js:33:25)
    at Codecept.init (/Users/thanhnguyen/Desktop/applitools-example/node_modules/codeceptjs/lib/codecept.js:55:15)
    at module.exports (/Users/thanhnguyen/Desktop/applitools-example/node_modules/codeceptjs/lib/command/definitions.js:307:12)
    at finish (/Users/thanhnguyen/Desktop/applitools-example/node_modules/codeceptjs/lib/command/init.js:192:7)
    at /Users/thanhnguyen/Desktop/applitools-example/node_modules/codeceptjs/lib/command/init.js:219:7
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:18259) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```bash
npx codeceptjs init
```
### Details

* CodeceptJS version:
* NodeJS Version: 12.4.0
* Operating System: macOS Mojave 10.14.6
* WebDriverIO

**Comment by butlera1** [comment]
I have similar error:

BUTLEA1-M2:psur-reporter butlea1$ npx codeceptjs init

  Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

Installing to /Users/butlea1/Code/psur-reporter
? Where are your tests located? ./tests
? What helpers do you want to use? WebDriver
? Where should logs, screenshots, and reports to be stored? ./output
? Would you like to extend the "I" object with custom steps? No
? Do you want to choose localization for tests? English (no localization)
(node:82093) UnhandledPromiseRejectionWarning: TypeError: console.print is not a function
    at inquirer.prompt.then (/Users/butlea1/Code/psur-reporter/node_modules/codeceptjs/lib/command/init.js:127:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:82093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of
 an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that
 are not handled will terminate the Node.js process with a non-zero exit code.
BUTLEA1-M2:psur-reporter butlea1$

**Comment by pablopaul** [comment]
Relates to #1976 1976

**Comment by pablopaul** [comment]
@DavertMik where is this old webdriverio version coming from: `npm install --save-dev webdriverio@^5.2.2` ?

**Comment by pablopaul** [comment]
@PeterNgTr @butlera1 have you installed `webdriverio` before running init?

With `npm install codeceptjs webdriverio --save-dev` beforehand and then `npx codeceptjs init` with WebDriver helper everything works fine for me with CodeceptJS 2.3.3 and the hotfix (`npm install parse-function@5.2.11 --save-dev`) from https://github.com/Codeception/CodeceptJS/issues/1976.

**Comment by PeterNgTr** [comment]
@pablopaul I just create new project, step by step on the documentations, so I don't install webdriverio in prior.

**Comment by pablopaul** [comment]
@PeterNgTr which page where you following exactly? https://codecept.io/quickstart-webdriver does mention to install webdriverio :)

**Comment by PeterNgTr** [comment]
actually I just follow the steps that come across my mind @pablopaul

**Comment by pablopaul** [comment]
So can you close the current issue @PeterNgTr ? :)
