### ISSUE TITLE
TestCafe native CLI params

### ISSUE THREAD

**Issue by orihomie** [Codeception/CodeceptJS#1935]
Is that possible to pass testcafe's native params while running codeceptjs tests? 
I mean I cant start testcafe's tests like this:

> testcafe -c 4 safari,firefox tests/test.js

Is that somehow possible to pass that params when I do this:

> npx codeceptjs run ...

**Comment by DavertMik** [comment]
Sorry, we don't support running in multiple browsers at once, as well as setting a browser from CLI. You can do this from the configuration.

**Comment by orihomie** [comment]
@DavertMik why is that? For example, I'd like to pass teamcity reporter as I need integrate with teamcity, but there is hardcoded 'minimal' reporter as testcafe initied through your code and codeceptjs has no integratioin module with TeamCity, but testcafe itself has, so that would be nice to pass CLI params through helpers config, isnt that option?
