### ISSUE TITLE
Mock the current date? 

### ISSUE THREAD

**Issue by jameschetwood** [Codeception/CodeceptJS#1940]
I need to mock JavaScript's Date object so `new Date()` always return the same date. 

For my unit tests it was pretty straightforward with this: https://github.com/boblauer/MockDate

How can I do this with CodeceptJS and Puppeteer? I could monkey patch with the code below but I'm not sure how to make that code run in Chromium?

```
Date = (function(oldDate) {
    /**
     * @return {string}
     */
    function Date(year, month, date, hours, minutes, seconds, ms) {
      let res;
      const l = arguments.length;
      if (l == 0) {
        res = new oldDate(Date.now());
      } else if (l == 1) {
        res = new oldDate(year); // milliseconds since epoch, actually
      } else {
        res = new oldDate(
          year,
          month,
          l > 2 ? date : 1,
          l > 3 ? hours : 0,
          l > 4 ? minutes : 0,
          l > 5 ? seconds : 0,
          l > 6 ? ms : 0,
        );
      }
      if (this instanceof Date) {
        return res;
      }
      return res.toString();
    }
    Date.prototype = oldDate.prototype; // required for instanceof checks
    Date.now = function() {
      return 1570705688585;
    };
    Date.parse = oldDate.parse;
    Date.UTC = oldDate.UTC;
    return Date;
  })(Date, Date.now);
```

**Comment by PeterNgTr** [comment]
@jameschetwood you could import that lib and use in wherever you want to mock date object.

```js
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> var MockDate = require('mockdate');
undefined
> MockDate.set('2000-11-22');
undefined
> new Date().toString()
'Wed Nov 22 2000 01:00:00 GMT+0100 (Central European Standard Time)'
> new Date().toString()
'Wed Nov 22 2000 01:00:00 GMT+0100 (Central European Standard Time)'
> MockDate.reset();
undefined
> new Date().toString()
'Thu Oct 10 2019 16:24:31 GMT+0200 (Central European Summer Time)'
> MockDate.set('2000-11-22');
undefined
> new Date().toString()
'Wed Nov 22 2000 01:00:00 GMT+0100 (Central European Standard Time)'
> 
```

**Comment by PeterNgTr** [comment]
Isn’t it the case you import that lib to mock date when performing tests and reset it after your tests has been done?

**Comment by jameschetwood** [comment]
Yes that's right. So my Jest test file looks something like:
```
MockDate.set('2019-10');
test("test sometthing", ()=>{
	// Actual test here 
})
MockDate.reset();
```

But your first comment looks like you're entering commands into the terminal? How would I make mockdate run before my functional tests? I cant add it to my application or else it would behave that way for users, I just need to mock the date for testing.

**Comment by PeterNgTr** [comment]
Yeah, I’m trying it on cmd. To use it on codeceptjs, it’s pretty much easy. Import it in your test file and call it from there.

**Comment by jameschetwood** [comment]
Am I going about this the right way? Using the monkey patch solution (the code from my initial comment) should something like this work? The test appears to not run at all. 

```
Scenario(
  'this is my test',
  (CheckoutPage, FixDate) => {
    FixDate();
    CheckoutPage.load();
    pause();
  }
).injectDependencies({ FixDate: require('./FIX-DATE') });
```

**Comment by jameschetwood** [comment]
Ive also tried running the monkey patch inline in my test file but it has no affect. So I assume the Chromium browser users the system date, not the date from the test file that calls it? 

```
Date = (function(oldDate) {
  // Rest of the monkey patch
 })(Date, Date.now);

Scenario(
  'this is my test',
  (CheckoutPage) => {
    CheckoutPage.load();
    pause();
  }
)
```

**Comment by PeterNgTr** [comment]
@jameschetwood simple like this:

```js
Scenario('@test', async (I) => {
    let MockDate = require('mockdate');
    let expect = require('chai').expect;
    MockDate.set('2000-11-22');
    let mockDate = new Date().toString();
    expect(mockDate).to.contain('Wed Nov 22 2000 01:00:00 GMT+0100 (Central European Standard Time)');
    MockDate.reset();
});
```

**Comment by jameschetwood** [comment]
My test file now has this:

```
Scenario(
  'this is my test',
  (CheckoutPage) => {
    const MockDate = require('mockdate');
    MockDate.set('2018-10');
    CheckoutPage.load();
  }
)

```
And my react component has this:

```
const Component = () => {
	console.log(new Date())
	return <h1>Im a component</h1>
}
```

The React component doens't think that it's 2018, which is what I need to happen. Is unexpected or have we been talking at cross purposes? Apologies if I've not been clear.

**Comment by DavertMik** [comment]
To make your React component change the date - execute your script inside browser context by using `I.executeScript()`

**Comment by jameschetwood** [comment]
I monkey patched the date within a `executeScript` block (using the code from my initial post). When I console log in that block the date has been change, however my React component is still using the real date. 

```
Scenario(
  'this is my test',
  (I, CheckoutPage) => {
    I.executeScript(() => {
      Date = (function(oldDate) {
        // Monkey patch date 
      })(Date, Date.now);
      console.log('MONKEY PATCHED DATE', new Date());
    })
    CheckoutPage.load();
  }
)


```

**Comment by jameschetwood** [comment]
It was just the order that stopped this from working. If I load the component before I run `executeScript` then it works: 

```
Scenario(
  'this is my test',
  (I, CheckoutPage) => {
    CheckoutPage.load();
    I.executeScript(() => {
      Date = (function(oldDate) {
        // Monkey patch date 
      })(Date, Date.now);
    })
    CheckoutPage.submit();
  }
)
```
