### ISSUE TITLE
feedback(WebdirverIO): multiremote support

### ISSUE THREAD

**Issue by douglasduteil** [Codeception/CodeceptJS#195]
Hi @DavertMik

I'm working on making CodeceptJS work with BrowserStack through WebdirverIO multiremote.

However after I successfully initialize that process (#188) I end up with a lot of errors during assertion code.

This is dude to the fact that, in multiremote, WebdirverIO is processing the assertion in every browser before resolving the Promise with every browser results.

> "You will notice that each command gets executed one by one. That means that the command finishes once all browser have executed it."
> 
> --- http://webdriver.io/guide/usage/multiremote.html

So, for example, for `proceedSee` : `this.browser.getText` is returning multiple sources to assert. 

Therefore, I'm tempted to replace

``` js

return this.browser.getText(withStrictLocator(context)).then((source) => {

  return stringIncludes(description)[assertType](text, source);

});

```

by

``` js

return Promise.resolve()

.then(this.browser.getText.bind(this, withStrictLocator(context)))

.then((sources) => this.options.multiremote ? Object.keys(sources).map((name) => sources[name]) : [sources])

.then((sources) => Promise.all(

  sources.map((source) => stringIncludes(description)[assertType](text, source))

))

```

What's your opinion on this ?

**Comment by DavertMik** [comment]
Thanks for working on this!
Sure I don't like that this addition makes code much more messy. I'm not sure but I think we can try to use internal engine of CodeceptJS to work with such cases.

I have some ideas to improve.

Probably you will have lots of places to change to add check for multiremote. 
I think you can write a function that adapts result to multiple:

```
return this.browser.getText(withStrictLocator(context))
   .then(checkForRemote) // function that returns array of results
  // ...
```

And yes, assertion is not asunchronous so probably Promise.all is not needed there. Also it is better to use `forEach` and not `map` in this case
```js
.then((sources) => Promise.all(
  sources.map((source) => stringIncludes(description)[assertType](text, source))
))
```

SO probably you can have it updated like:

```js
return this.browser.getText(withStrictLocator(context))
   .then(checkForRemote) // function that returns array of results
   .then((sources) => sources.forEach((source) => stringIncludes(description)[assertType](text, source)))

```
