### ISSUE TITLE
Basic Auth (htaccess) via acceptPopup

### ISSUE THREAD

**Issue by testracer** [Codeception/CodeceptJS#1955]
Hi, I try to have questions which helps :)
i`m driving an CodeceptJS with WebriverIO, to learn IT

#### What are you trying to achieve?
1. I want to Send Alert Text to an alert-window (as htaccesslogin) + accept this Popup-Window
(inspite of using basic-auth embedded in url via @ would be an working solution)
![accept0](https://user-images.githubusercontent.com/31275529/66776535-e5ed9a00-eec6-11e9-83d2-254b6917657a.png)

#### What I figured out is:
- in Doku of WebdriverIO I found: [sendAlertText](https://webdriver.io/docs/api/webdriver.html#sendalerttext)

### I have 2 questions:
(?) Why I can not find #sendAlertText in my JS-Ide ?
![accept](https://user-images.githubusercontent.com/31275529/66776870-ba1ee400-eec7-11e9-85a5-0d3428bb0bf8.png)
- and #acceptAlert also not

(?) And but why the hell my Ide knows (makes suggetions) for this method: acceptPopup
and all the other codecept methods. From where my Ide (visu studio code) is knowing them? How?!

I ask this stupid questions because I think I need in my test:
I.sendAlertText('user_string');
I.pressKey('Tab');
I.sendAlertText('pwd_string');
I.acceptAlert();

Thnx for any message!

**Comment by DavertMik** [comment]
Hi, probably in a future versions we will provide some simplified way to pass this authorization, but for use the common approach from Selenium WebDriver. Add `user` and `password` to url string of your website URL:

```js
// inside codecept.conf.js
WebDriver: {
  url: ''http://user:password@yourwebsite.de",
}
```
See https://sqa.stackexchange.com/questions/12892/how-to-send-basic-authentication-headers-in-selenium

**Comment by PeterNgTr** [comment]
This can be easily done by puppeteer -> https://github.com/Codeception/CodeceptJS/pull/1962

**Comment by testracer** [comment]
@PeterNgTr 
> can be easily done by puppeteer
(?) May I ask: Is it possible to configure CodeceptJS with both helpers: 'Pupeteer' and 'Webdriver'?
- No,  i do remember the 'codeceptjs init' which means for me: i have to decide which helper I want to use; 
-- So I can not use:

```
helpers: {
   Webdriver: {
      url: 'http://localhost',
   },
   Puppeteer : {
        url: 'http://localhost',
        basicAuth: { username: 'postman', password: 'password' },
        show: true
    },
 }
```
(I have fear to do something without understandig: whatwhy)

@DavertMik 
thank u for your advice: 
```
//inside codecept.conf.js i have already set url
WebDriver: {
   url: ''https://www.devdomin.de",
}
```
(!) But the Basic auth comes suddenly in a szenario where:
`I.amOnPage("/service/user-admin/user/list:);`
-  Only there comes the htaccess-Popup


and for your link to:  /how-to-send-basic-authentication-headers-in-selenium
-> there I stand in the forest

**Comment by PeterNgTr** [comment]
@testracer I included the wdio in the same PR #1962

**Comment by testracer** [comment]
@PeterNgTr 
Thank you verry much!
(?) What I have to do now (when) to use the new 
- have i to update my wdio package after PR #1962 is merged into master?

```
WebDriver : {
   basicAuth:
}
```

**Comment by PeterNgTr** [comment]
@testracer for testing purpose, cause it's on a separate branch, you can replace the codeceptjs version in your `package.json` with this:

from

```json
...
"codeceptjs": "2.3.3"
...
```

to
```json
...
"codeceptjs": "PeterNgTr/CodeceptJS#feat-puppeteer-send-basic-auth"
...
```

**Comment by testracer** [comment]
@PeterNgTr 
Do I smething wrong?:
- i did change my package.json
- i did change my configuration for WebDriver
- an i did restart selenium-standalone

(?) Unfortunately I do not have a new browser.url if i use now in my test:
'''
I.amOnPage("/service/user-admin/user/list");
'''

**Comment by PeterNgTr** [comment]
@testracer can you pass the full url like `https://` to I.amOnPage(...)?

**Comment by testracer** [comment]
@PeterNgTr
Sorry, same behaviour
![accept1](https://user-images.githubusercontent.com/31275529/66921476-9376bf80-f025-11e9-9289-997b5784d226.png)

**Comment by PeterNgTr** [comment]
@testracer could you delete your local `node_modules` and run `npm i` one more time?

**Comment by testracer** [comment]
@PeterNgTr
-thank you for your commitment-
(ok) ah yes, my `WdioHelper:` caused the wrong behaviour.
- yours is fine!
```
//Works both:
`I.amOnPage("/path/");
`I.amOnPage ("https://www.url/path");
```
tnhx!

**Comment by testracer** [comment]
@PeterNgTr
I would like to have last question:
Why i could not see it in Console that codeceptJS did have problem with my local `WdioHelper:`
I thought: As long I do not use this helper it can not cause an error.
Why it was not printed in Console?

**Comment by testracer** [comment]
@PeterNgTr Sry to trouble you,
unfortunately I can not find the error by myself.

I still do not have new browser.url

And I do not realy understand your last advice:
> delete your local node_modules and run npm i one more time
- I did not install additional node_modules local:
```
//did just install ubuntu:
$ sudo apt install default-jre
$ sudo apt install nodejs
$ sudo apt install npm
$ sudo apt install gdebi-core
$ npm install codeceptjs webdriverio selenium-standalone --save-dev
$ npx selenium-standalone install

```
> delete your local node_modules and run npm i one more time
You dont mean to delete this folder, right?
![accept3](https://user-images.githubusercontent.com/31275529/66951168-17e33580-f05a-11e9-8706-444134ac43fe.png)

**Comment by PeterNgTr** [comment]
@testracer exactly, delete that folder and try doing npm install again.

**Comment by testracer** [comment]
@PeterNgTr
I did.
It could not load helper WebDriver from module './helperWebdriver':
Requ modules are not installed.

I run
`$sudo nmpm install -g webdriverio^5.2.2`

I did restart my
`$npx selenium-standalone start`

It throw new error now:
Missing /home/testrace/.npm_npx/node_modules/selenium-standalone/./selenium/chromdriver/...

Sorry for delay but I can not do copypaste inspite of:
![accept4](https://user-images.githubusercontent.com/31275529/66952641-55958d80-f05d-11e9-85fb-0b90a7136e1d.png)

Thank u for your message.

**Comment by PeterNgTr** [comment]
@testracer let’s do this:

- delete node_modules
- npm i
- npm i selenium-standalone —save (this to save this lib to your package.json file)
- npx selenium-standalone install
- npx selenium-standalone start

And then I believe you will be able to run codeceptjs

**Comment by testracer** [comment]
@PeterNgTr
Thank u very much for your approach! for newby console-questions i should not disturb u -> I ask in ubuntu-forums about your red-line in:
> let’s do this:
...

codecept running again. :)

but I dont have new browser.url

(?) Can u see a stupid mistake here:
tomorrow they will say: do you see, automatic tests are not worth the effort; but I dont think so. I will show it to them. No panic.
Do u see a stup-mistake her:
![accept6](https://user-images.githubusercontent.com/31275529/66955828-79f46880-f063-11e9-8e5f-cfbc35bf8f60.png)

**Comment by PeterNgTr** [comment]
@testracer what is the error you have? You still see the basic authen prompt? Are you sure the provided basic authentication is proper? 😅

**Comment by PeterNgTr** [comment]
@testracer are you on Slack or Skype? I would help in real time debugging :)

**Comment by testracer** [comment]
hi @PeterNgTr
thanks for that offer!

but i m not free for automatism before evenings.
(?) Do you see a evening-time-window which works for you?
I will arrange it.

slack please.
but i m connected with comp-workspace. how can I reach you?

**Comment by PeterNgTr** [comment]
@testracer I'm not kinda free much in the evenings, thou! You can post question in codeceptjs slack :)

**Comment by PeterNgTr** [comment]
@testracer I tried with this website `http://the-internet.herokuapp.com/basic_auth` and it worked as well. The basic auth is `admin:admin`

**Comment by testracer** [comment]
@PeterNgTr 
Many thaanx for your approach!

Next I realy want to set up new machine. thank u for all your command input!

I would like to ask you for the codeceptjs.slack channel. best for me would be:
my email kai.henkel@auto.de would be activated there.
(?) Or do u have different proposal?

Many thanks in advance!

:)
![accept9](https://user-images.githubusercontent.com/31275529/67105769-a9bd8080-f1c9-11e9-93d6-6403ac1224f6.png)
 






:)
![accept9](https://user-images.githubusercontent.com/31275529/67105120-775f5380-f1c8-11e9-8120-0abc7fccb3b3.png)

**Comment by PeterNgTr** [comment]
@testracer seems like your `node_modules` is not proper. the codeceptjs may not points to my branch. Could you take screenshot of `node_modules/codeceptjs` folder?

btw, I sent you the codeceptjs slack invitation.

**Comment by testracer** [comment]
@PeterNgTr
i dont have a folder `node_modules/codeceptjs`
![accept10](https://user-images.githubusercontent.com/31275529/67108775-7e3d9480-f1cf-11e9-879c-94e2265b8ea7.png)

**Comment by PeterNgTr** [comment]
@testracer are you installing codeceptjs globally?

**Comment by testracer** [comment]
@PeterNgTr
Please let me write to you what I realy did:
- `$ npm install codeceptjs webdriverio selenium-standalone --save-dev`
- yesterday i did delete '/node_moduls`
- then I did '$ npx codeceptjs run *_test.js
Because it could not load helper WebDriver from module './helperWebdriver':
Requ modules are not installed. 
- I did run: `$ sudo nmpm install -g webdriverio^5.2.2`
then I did additional yours: 
- `npm i webdriverio@5 —save`
- `npm i selenium-standalone —save` (this to save this lib to your package.json file)
- `npx selenium-standalone install`
- `npx selenium-standalone start`

**Comment by PeterNgTr** [comment]
@testracer okay let do it one again from the beginning:

- delete your local node_modules
- remember to check your package.json if codeceptjs is pointing to my branch
- npm i webdriverio@5 selenium-standalone —save
- go to your local node_modules/codeceptjs/lib/helper/Webdriver.js to check the amOnPage method includes my new patch
- npx selenium-standalone install
- npx selenium-standalone start
- run your test

**Comment by PeterNgTr** [comment]
hey @testracer any updates or this can be closed?

**Comment by testracer** [comment]
16 days:
... still at this point. 2 steps forward 3 backwards. thanx for not just closing.

**Comment by PeterNgTr** [comment]
https://github.com/Codeception/CodeceptJS/pull/1962 solved this issue.

**Comment by testracer** [comment]
-there is big hill for me-
still fighting

many thanks
