### ISSUE TITLE
I want to use codeceptJS to test windows app with appium。

### ISSUE THREAD

**Issue by helloCx** [Codeception/CodeceptJS#1958]
What are you trying to achieve?

I want to use codeceptJS to test windows app with appium。

What do you get instead?
how do I  make  it work

**Comment by helloCx** [comment]
now I can make testing work with jest and appium 。

**Comment by pablopaul** [comment]
@helloCx happy that you found a solution!

can you close this issue then?

**Comment by helloCx** [comment]
I hope codeceptjs can do it .
