### ISSUE TITLE
Shared config headers: ApiDataFactory and REST

### ISSUE THREAD

**Issue by pablopaul** [Codeception/CodeceptJS#1959]
ApiDataFactory config overrides possible REST config with with this super(config) call: https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/ApiDataFactory.js#L187

In my use case I am using both helpers and I dont want the ApiDataFactory config applied to the REST config.

A quick fix on my side was to reorder the helper config properties in codecept.conf.js, so ApiDataFactory comes first and after that the REST helper config, this works for my specific use case.

**Comment by DavertMik** [comment]
When you do `super` call it should not affect REST config, as there are different instances of a class. 
Think of it as 2 REST helpers were instantiated.

Maybe you could share your config so I could find real case?

**Comment by pablopaul** [comment]
Will be fixed with the upcoming 2.3.3 release.
