### ISSUE TITLE
WebDriver grabBrowserLogs Broken

### ISSUE THREAD

**Issue by pablopaul** [Codeception/CodeceptJS#1964]
#### What are you trying to achieve?

Use `grabBrowserLogs` with WebDriver helper.

#### What do you get instead?

```bash
-- FAILURES:

  1) Bug Report Template
       WebDriver grabBrowserLogs:
     unknown command: session/62daaf68b83732de6d7973e49f5e285f/se/log
  
  Scenario Steps:
  
  - I.grabBrowserLogs() at Test.<anonymous> (bug_test.js:7:30)
  - I.amOnPage("/") at Test.<anonymous> (bug_test.js:6:11)
```

```js
Feature("Bug Report Template");

Scenario(
    "WebDriver grabBrowserLogs",
    async I => {
        I.amOnPage("/");
        const logs = await I.grabBrowserLogs();
        console.log(JSON.stringify(logs))
    }
);
```

### Details

* CodeceptJS version: 2.3.3
* NodeJS Version: 12 
* WebDriver
* Configuration file: https://gitlab.com/codeceptjs/codeceptjs-bug-report-template/blob/master/codecept.conf.js

**Comment by PeterNgTr** [comment]
everytime @pablopaul touches something, the bug/issue appears 😄

**Comment by pablopaul** [comment]
@PeterNgTr seems to be an Selenium issue, with `selenium/standalone-chrome:3.141.59` it works, see https://gitlab.com/codeceptjs/codeceptjs-bug-report-template/-/jobs/322661202

**Comment by neutraali** [comment]
> https://gitlab.com/codeceptjs/codeceptjs-bug-report-template/-/jobs/322661202

I fail to see how this was resolved? `undefined` was still the output of `grabBrowserLogs`.
