### ISSUE TITLE
Cannot find module 'colors'

### ISSUE THREAD

**Issue by aldarund** [Codeception/CodeceptJS#197]
When using master branch following error
> Error: Cannot find module 'colors'
>     at Function.Module._resolveFilename (module.js:339:15)
>     at Function.Module._load (module.js:290:25)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (/home/ubuntu/rentapplication-frontend-tests/node_modules/codeceptjs/lib/container.js:3:14)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)

**Comment by DavertMik** [comment]
Thanks. It is actually not needed there. Submitting a patch

**Comment by DavertMik** [comment]
Fixed in https://github.com/Codeception/CodeceptJS/commit/3bece402028eecf74f55d64cc3d9d295e087d60b
