### ISSUE TITLE
Feature Level Retires not being correctly reported with run-workers

### ISSUE THREAD

**Issue by megalan247** [Codeception/CodeceptJS#1985]
#### What are you trying to achieve?
We have some flaky tests that we use the retry function in CodeceptJS for, and it looks like when we run the tests with run-workers and a test fails, but then passes on the retry, the failure is reported and the test fun fails completely.

#### What do you get instead?
When a retry is executed and subsequently passes, the run should succeed 

### Details

* CodeceptJS version: 2.3.3
* NodeJS Version:v12.4.0
* Operating System:Alpine Linux
* WebDriverIO: 5.15.1

**Comment by GIvanovWaves** [comment]
Test example:
```javascript
var assert = require('assert');
var tries = 0;

Feature('Retry in workers');

Scenario('Flaky scenario', { retries: 2 }, () => {
  tries++;
  assert.equal(tries, 2);
});
```
Run workers:
```cmd
$ npx codeceptjs run-workers 1
CodeceptJS v2.3.5
Running tests in 1 workers...

[1] Retry in workers --
[1]   ? Flaky scenario in 2ms
[1]   v Flaky scenario in 145ms

  FAIL  | 1 passed, 1 failed   // 2.073s

-- FAILURES:

  1) Retry in workers
       Flaky scenario:

      1 == 2
      + expected - actual

      -1
      +2
```
Run:
```cmd
$ npx codeceptjs run
CodeceptJS v2.3.5
Retry in workers --
  v Flaky scenario in 0ms

  OK  | 1 passed   // 1s
```
