### ISSUE TITLE
Error: Cannot find module '../../translations'

### ISSUE THREAD

**Issue by aldarund** [Codeception/CodeceptJS#199]
> Error: Cannot find module '../../translations'
>     at Function.Module._resolveFilename (module.js:339:15)
>     at Function.Module._load (module.js:290:25)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (/home/ubuntu/rentapplication-frontend-tests/node_modules/codeceptjs/lib/command/init.js:24:32)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)

**Comment by abner** [comment]
@DavertMik The recently added translations folder is missing in the npm published folder.
I guess you just forgotten to add it to your npm publish script.

**Comment by abner** [comment]
actually, the problem was  `translations` directory was missing in the files property on package.json.

**Comment by DavertMik** [comment]
Oh, sorry. Missed that. Learning npm the hard way :(
