### ISSUE TITLE
How to problematically force stop / quit / fail a test? (for example at the end of if-statement

### ISSUE THREAD

**Issue by rduinmaijer** [Codeception/CodeceptJS#1999]
How to problematically force stop / quit / fail a test? (for example at the end of if-statement?

#### What are you trying to achieve?
        if (data.login === true) {
            console.log("login  true")
        } else if (data.login === false) {
            console.log("login  false")
        } else {
            console.log("login not true not false")
            I.exit(); // <---- 
         }

**Comment by erwinheitzman** [comment]
This can be done like so:
```
    if (data.login === true) {
        console.log("login  true")
    } else if (data.login === false) {
        console.log("login  false")
    } else {
        console.log("login not true not false")
        throw new Error('example')
     }
```
