### ISSUE TITLE
switchTo failure.

### ISSUE THREAD

**Issue by ecampii** [Codeception/CodeceptJS#200]
can we have a sample use of this in the doc.  i also tried using css and xpath but it wont work. 

 • I switch to "iframe_name"
 ✖ FAILED in 67089ms

-- FAILURES:
 ✖ "after all" hook: codeceptjs event in 0ms

**Comment by manibushan13** [comment]
any update on this..

**Comment by imvetri** [comment]
is this related to codeceptJS or nightmare ?

**Comment by manibushan13** [comment]
it's related to codeceptjs..
getting error like :: Unsupported frame locator: java.util.HashMap

**Comment by imvetri** [comment]
how do you get "java.util.HashMap" in the locator in first place ?

**Comment by manibushan13** [comment]
i don't know, i tried with different different locators but result same...
