### ISSUE TITLE
Report Portal throws error related to status code when using RP V5

### ISSUE THREAD

**Issue by GSasu** [Codeception/CodeceptJS#2010]
#### What are you trying to achieve?
Trying to run tests and push output to Reportportal V5.

#### What do you get instead?
```
(node:35244) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Value is not allowed for field 'status'.] "}
    at /Users/****/***************/**********************************************/node_modules/reportportal-client/lib/rest.js:27:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
### Details

* CodeceptJS version: 2.3.5
* NodeJS Version: 12.11.0
* Operating System: MacOS Catalina 10.15
* WebDriverIO: 5.15.2 
* Configuration file:

### NOTE
- The issue does not affect the tests or test runtime
- The issue caused is inside ReportPortal where the tests don't know when they ended thus the test run duration is inaccurate and it forces the user to manually stop the test sessions inside reportportal Launches section.

**Comment by pablopaul** [comment]
This is unrelated to CodeceptJS core, please close the issue here.

**Comment by PeterNgTr** [comment]
@GSasu @pablopaul in my updated version, the launch is now closed. You can still see those ugly strings, but it's not from `codeceptjs`. Stay with it then.

```js
(node:79255) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"timestamp":1573206957065,"status":400,"error":"Bad Request","message":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"182487b9-6de8-49be-8763-ba799ae5dfad\"","path":"/v1/peterngtr_personal/launch/182487b9-6de8-49be-8763-ba799ae5dfad/update"}
```

**Comment by GhsVilela** [comment]
@GSasu did you found a fix for this problem?
