### ISSUE TITLE
codeceptjs Protractor Helper expects protractor@^4.0.4 which wasn't being released yet

### ISSUE THREAD

**Issue by abner** [Codeception/CodeceptJS#203]
The **CodeceptJS** *Protractor Helper* expects **protractor@^4.0.4** which wasn't being released yet.

I tested installing the protractor from github master branch and it worked. 

Unfortunately the actual version `0.4.2` of CodeceptJS  does not work with the lastest protractor released  version `4.0.3`

**Comment by DavertMik** [comment]
Ok, thanks for report. I received the failure reports on Travis, it looked like they changed API in 4.0.4 so I updated it. Not sure how did I get installed 4.0.4 if it was not released...

**Comment by DavertMik** [comment]
Not sure if they accidentally released that version so I got it installed and reverted it back but I swear I saw it! :) Anyway, here is the patch #205 should fix that
