### ISSUE TITLE
Error while using rphelper.

### ISSUE THREAD

**Issue by deepak-monotype** [Codeception/CodeceptJS#2039]
Hi, I was trying RP helper and it has solved previous issues. But if any step fails like grabText, waitForElement then it throws error:
(node:58113) UnhandledPromiseRejectionWarning: Error: unknown command: session/75e482313ca943bf5c17f5abe1835bee/se/log
I am not sure whether this is due to RP helper, but I noticed this only after I started using it.

One more issue: Trying to add attachment Last Seen Screenshot to non-existent step.

**Comment by PeterNgTr** [comment]
This is not related to core codeceptjs
