### ISSUE TITLE
sql query in codeceptjs

### ISSUE THREAD

**Issue by Tommy97234** [Codeception/CodeceptJS#204]
Hello,

I would like to know if all codeception modules work for codeceptjs az well ?

Also how can i set up my environment and how can i proceed to add mysql queries in my script ?

I'm sorry if my question is stupid, actually i'm a beginner in codecept* and it's difficult to find out complete example on the web.

Thanks you for your help

**Comment by DavertMik** [comment]
> I would like to know if all codeception modules work for codeceptjs az well ?

No they don't :) They are completely different products. CodeceptJS is for acceptance (browser) testing only and there is nothing to work with SQL in it. Probably original Codeception plays better with Database and Mysql. You can look into [Db](http://codeception.com/docs/modules/Db) module for it
