### ISSUE TITLE
"Feature" availability check error"

### ISSUE THREAD

**Issue by andrejxz** [Codeception/CodeceptJS#2042]
#### What are you trying to achieve?
If you run a test without specifying "Feature", the test runs or sended error message.

#### What do you get instead?
In fact, it is different. The test pulls up "Before" from another file and runs the test.

### Details

* CodeceptJS version: 2.3.1
* NodeJS Version: v11.10.0
* TypeScript Version: v8.4.1
* Operating System: macOS
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Sorry, why you would ever do this?
