### ISSUE TITLE
Getting error when trying to work with workers

### ISSUE THREAD

**Issue by vitaly87** [Codeception/CodeceptJS#2047]
when trying to work with codeceptjs & workers then getting this error
codeceptjs version 2.3.6
>     Error: not found: java
>       at getNotFoundError (node_modules\which\which.js:13:12)
>       at Function.whichSync [as sync] (node_modules\which\which.js:134:9)
>       at start (node_modules\selenium-standalone\lib\start.js:60:27)
>       at internal/util.js:286:30
>       at new Promise (<anonymous>)
>       at start (internal/util.js:285:12)
>       at SeleniumStandaloneLauncher.onPrepare

**Comment by Vorobeyko** [comment]
What is configuration you use?

**Comment by vitaly87** [comment]
what you mean ? I am using .

` plugins: {
    wdio: {
      enabled: true,
      services: ['selenium-standalone']
      // additional config for service can be passed here
    },`

**Comment by Vorobeyko** [comment]
I mean that this error not related to CodeceptJS.
This error from selenium-standalone.
And maybe you must to install java? =)

**Comment by PeterNgTr** [comment]
yeah, you must install java :)

**Comment by veerasekarsp** [comment]
> what you mean ? I am using .
> 
> ` plugins: { wdio: { enabled: true, services: ['selenium-standalone'] // additional config for service can be passed here },`

Hi,
 I am also getting same error. Are you able to run the run-worker command now? I have installed java in my local but still facing this error. Can you please let me know fix for this.

**Comment by sanketharad** [comment]
Hi, I have installed java but facing the same issue. I also check my java version and node version. It is as required. Can you please help me with the solution. Thanks in advance

**Comment by vitaly87** [comment]
I having same issue when I have java on pc

**Comment by radhikav2911** [comment]
I too have the same issue. Any solution?
"not found: java at getNotFoundError " but java is already installed and path variables are set.
