### ISSUE TITLE
Before/After don't support generators

### ISSUE THREAD

**Issue by joefitter** [Codeception/CodeceptJS#206]
Passing a generator to `Before` or `After` doesn't have the same behaviour as if used as a `Scenario`. It seems to skip over the `Before` and immediately run the tests

**Comment by DavertMik** [comment]
Yes, it is not supported and documented for Before/After. I didn't even think of such usage.
To be honest, it is pretty hard to handle generators inside tests so I don't think this feature is easy to implement.

**Comment by Nighthawk14** [comment]
👍
