### ISSUE TITLE
How do i switch tabs or windows?

### ISSUE THREAD

**Issue by ecampii** [Codeception/CodeceptJS#207]
Is there a way to detect tabs or windows and switch to it?

**Comment by APshenkin** [comment]
You can write custom helpers for now. Below is e.g. for WebDriverIO
```
/**
    waitTabsLoading(ammountOfTabs, timeout) {
        timeout = timeout || 15;
        let client = this.helpers['Appium'].browser;
        return client
            .waitUntil(function () {
                return this.getTabIds().then(function (handles) {
                    return handles.length === ammountOfTabs
                });
            }, timeout * 1000, "The number of tabs hasn't changed to " + ammountOfTabs);
    }

    changeTab(num) {
        let client = this.helpers['Appium'].browser;
        return client
            .getTabIds().then(function (handles) {
                return this.switchTab(handles[num - 1]);
            });
    }
```

I'll add them to basic metods for WebdriverIO

**Comment by APshenkin** [comment]
https://github.com/Codeception/CodeceptJS/pull/606

**Comment by patmeeker** [comment]
@APshenkin - You said this example was for for webdriverio, but the code it using Appium.
When I change your code to use webdriverio, I get this error: "Error: Session ID is null. Using WebDriver after calling quit()?"

**Comment by APshenkin** [comment]
@patmeeker there is default methods in codeceptjs for this now. Please update codeceptJS to 1.0.2 and check documentation: http://codecept.io/helpers/WebDriverIO/#switchtonexttab

**Comment by patmeeker** [comment]
Got it! Thanks!

**Comment by BobRay** [comment]
Dead link: check documentation: http://codecept.io/helpers/WebDriverIO/#switchtonexttab
