### ISSUE TITLE
How to use with puppeteer-core instead of puppeteer

### ISSUE THREAD

**Issue by MickaelTH** [Codeception/CodeceptJS#2076]
#### What are you trying to achieve?
I try to install CodeceptJS with puppeteer-core as I want to use it with Browserless, therefore no need to install the default Chromium browser bundled with puppeteer

#### What do you get instead?
When running the tests, the puppeteer libray is indeed not found:

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Could not load helper Puppeteer from module './helper/Puppeteer':
Required modules are not installed.

RUN: [sudo] npm install -g puppeteer@^1.6.0
```

### Details

* CodeceptJS version: ^2.3.6
* NodeJS Version: 10.15.2
* Operating System: Ubuntu 19.10
* puppeteer(-core): ^1.20.0
* Configuration file:

```js
exports.config = {
  tests: './scripts/*_test.js',
  output: './logs',
  helpers: {
    Puppeteer: {
      url: 'http://localhost',
      show: false,
      restart: false,
      waitForNavigation: "networkidle0",
      chrome: {
        browserWSEndpoint: "wss://chrome.browserless.io/"
      },
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'worker'
}
```

**Comment by MickaelTH** [comment]
Note to self: instead of trying to "hack" the actual Puppeteer helper, I think it should be better to extend Puppeteer into a new PuppeteerCore.

**Comment by MickaelTH** [comment]
The best way to avoid to download Chromium and not modifying the code is to run installation in this order:

`npm config set puppeteer_skip_chromium_download true
npm install puppeteer`

Based on this [npm_config_puppeteer_skip_chromium_download](https://github.com/puppeteer/puppeteer/blob/a363a733b7aa88be9a17190bcfa924b507d7b3da/install.js#L19-L26) the download will be skipped.

This will add the first line into your npm configuration file. You can check by typing:

`npm config ls -l`

This solution is better than asking support for puppeteer-core, therefore I will close the issue.

**Comment by ersel** [comment]
Thanks for sharing your work @MickaelTH , it helped me to figure out how to integrate https://github.com/alixaxel/chrome-aws-lambda with codecept!
