### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by andrejxz** [Codeception/CodeceptJS#2079]
/**
         * Checks that text is equal to provided one.
         *
         * ```js
         * I.seeTextEquals('text', 'h1');
         * ```
         */

https://github.com/Codeception/CodeceptJS/blob/e95e61f1eb7efd821641375e90394b314dc37ae2/typings/types.d.ts#L2243

**Comment by Vorobeyko** [comment]
Thank you! We fix it.

**Comment by Vorobeyko** [comment]
fixed in release 2.4! :tada:
