### ISSUE TITLE
code example for 'I.Nightmare'?

### ISSUE THREAD

**Issue by jmellicker** [Codeception/CodeceptJS#208]
Executing 'codeceptjs list' returns as the first option:
`I.Nightmare(options)`

I assume this is a different way (than helpers) to expose the Nightmare API?

Could someone provide a code example (for 'click', ideally) or point me to docs for 'I.Nightmare'?

Thanks so much, this is an awesome library BTW!

**Comment by jmellicker** [comment]
More info: planning to try this:

[https://github.com/Mr0grog/nightmare-real-mouse](https://github.com/Mr0grog/nightmare-real-mouse)

since clicks on some elements don't register.

**Comment by DavertMik** [comment]
Thanks, sorry for a delay in reply. Basically `I.Nightmare` should not be used, it looks more like a bug in definition. All you need to enabled Nightmare helper and use `I.click` in tests 

```json
  "helpers": {
    "Nightmare": {
      "url": "http://localhost",
      "show": false
    }
  }
```

```
  I.amOnPage('http://yahoo.com');
  I.fillField('p', 'github nightmare');
  I.click('Search Web');
  I.waitForElement('#main');
```

Nightmare API is not exposed unless you are writing your own Helper. You ae using CodeceptJS wrapper for ir
