### ISSUE TITLE
Managing DataTables With headers

### ISSUE THREAD

**Issue by Sraime** [Codeception/CodeceptJS#2081]
#### What are you trying to achieve?

It could be nice to have a parsed DataTables with headers in steps' argument function instead of having a simple DataTable object generated by the gherkin module.

#### What do you get instead?

For example, if you have this gherkin step : 

```
Given the following members exist : 
    | firstName   | lastName |
    | John | Doe  |
```

We should be able to have access to a parsed version of it in the step implementation : 

```
Given('the following members exist : ', (members) => {
    console.log(members.rows);
    console.log(members.rowsWithHeader());
});
```

And the output should be : 

```
[ { type: 'TableRow',
  location: { line: 59, column: 13 },
  cells:
   [ { type: 'TableCell', location: [Object], value: 'firstName' },
     { type: 'TableCell', location: [Object], value: 'lastName' } ] },
  { type: 'TableRow',
  location: { line: 60, column: 13 },
  cells:
   [ { type: 'TableCell', location: [Object], value: 'John' },
     { type: 'TableCell', location: [Object], value: 'Doe' } ] }
]

[ { type: 'TableRowWithHeader',
  location: { line: 59, column: 13 },
  cells:
   { firstName: { type: 'TableCell', location: [Object], value: 'John' },
    lastName: { type: 'TableCell', location: [Object], value: 'Doe' } } }
]
```

A similar feature already exists in cucumber-js : 
https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/data_table_interface.md

### Details
It can be done by adding some code before setting the DataTable argument (lib/interfaces/gherkin.js line 39). A proper way I guess is to create a new class with both options (from the DataTable generated by the gherkin module) and add it to the arguments table instead of the original one.

**Comment by koushikmohan1996** [comment]
Closing this issue.
