### ISSUE TITLE
new feature with translate

### ISSUE THREAD

**Issue by rebajz** [Codeception/CodeceptJS#2083]
in https://github.com/Codeception/CodeceptJS/tree/master/translations is possible add translate.

In translate file is something as:
module.exports = {
  I: 'Ich',
  actions: {
    waitForText: 'warte_auf_text',
    amOnPage: 'bin_auf_seite',
    click: 'clicke',

Please enable translate too:
Scenario, Features.

Maybe will good enable translate commands and config.
For example
, commands: {
    run: 'translateForRun',
    steps: 'translateForSteps',
   generate: 'translateForGenerate'
},
config: {
   helpers: 'translateForHelpers',
   include: 'translateForInclude',
   teardown: 'translateForTeardown',

},
warningsFromAssets: {
}

etc.

**Comment by DavertMik** [comment]
Yeah, I was thinking about it is as well.
Nice enhancement
