### ISSUE TITLE
bad slash in steps.d.ts

### ISSUE THREAD

**Issue by rebajz** [Codeception/CodeceptJS#2084]
after use codeceptjs def is generated steps.d.ts
this file have on top: 
```
/// <reference types='codeceptjs' />
type footerFragment = typeof import('./_fragments\footer.js');
type headerFragment = typeof import('./_fragments\header.js');
type main = typeof import('./_fragments\main.js');
type cashloanPage = typeof import('./_pages\cashloan.js');
type aboutPage = typeof import('./_pages\about.js');
type loanCalculatorPage = typeof import('./_pages\loanCalculator.js');
type universalSteps = typeof import('./_steps\universal.js');
```
bug is in slash before file "\footer.js". Correct must be "/footer.js"

**Comment by Vorobeyko** [comment]
:cry: Thank you for report!
Can you write your PO content and codeceptjs config?

**Comment by rebajz** [comment]
yes, it is only demo project ;-)

codecept.confi.js
-------------------------
const EXEC = require('child_process');
const ALLURE = require('allure-commandline');

let cefChromeDriver = 'tasklist | find /i "2.43-ia32-chromedriver" && taskkill /im 2.43-ia32-chromedriver /F || echo Process "2.43-ia32-chromedriver" not running before test';
let usedUrl = 'http://157.230.77.142:3000/';

exports.config = {
    translation: "./preklad.js",
    tests: './_tests/*.js',
    output: './_output',
    helpers: {
        WebDriver: {
            url: usedUrl,
            browser: 'chrome',
            windowSize: "maximize",
            restart: false
        },
        // Protractor: {
        //     url: usedUrl,
        //     driver: 'hosted',
        //     browser: 'chrome',
        //     restart: false,
        //     rootElement: 'body',
        //     manualStart: true
        // },
        REST: {
            endpoint: usedUrl,
            defaultHeaders: {
                'Content-Type': 'application/json; charset=utf-8'
            }
        }
    },
    include: {
        footerFragment: './_fragments/footer.js',
        headerFragment: './_fragments/header.js',
        main: './_fragments/main.js',
        cashloanPage: './_pages/cashloan.js',
        aboutPage: './_pages/about.js',
        loanCalculatorPage: './_pages/loanCalculator.js',
        universalSteps: './_steps/universal.js',
    },
    bootstrap: null,
    mocha: {},
    name: 'test-framework',
    plugins: {
        wdio: {
            enabled: true,
            services: ['selenium-standalone']
        },
        allure: {
            "enabled": true
        }
    },
    teardown: function (done) {
        EXEC.exec(cefChromeDriver);
        console.log('ChromeDriver is killed right now.');
        ALLURE(['generate', '_output', '-o', '_output/allure', '--clean']);
        console.log('Allure report is generated right now.');
        done();
    }
};

----------------
main.js
----------------
const {I} = inject();

module.exports = {
    idContainer: '__next',
    xpathHeader: '//header',
    xpathFooter: '//footer'
};

----------------
footer.js
----------------
const {I, main} = inject();

module.exports = {
    visibleText: 'Battle Page v2 | RDPANEK LABS, s.r.o. | Performance-testing.cz',
    xpathDefault: '//*[@id="' + main.idContainer + '"]' + main.xpathFooter,
    testText() {
        I.seeTextEquals(this.visibleText, {xpath: this.xpathDefault});
    },

};

----------------
universal.js
----------------
const {I, headerFragment, cashloanPage} = inject();

module.exports = {
    openLoanCalculator() {
        headerFragment.visitLinkCashloan();
        I.wait(1);
        cashloanPage.useButton();
    }
};

----------------
cashloan.js
----------------
const {I} = inject();

module.exports = {
    title: 'Banka - sjednání půjčky',
    header: 'Půjčka je prostě fajn',
    firstText: 'Stačí, když budete splácet půjčku včas a získáte bonus za spolehlivé splácení.',
    buttonText: 'Chci půjčku >',
    xpathButton: '(//button/span)[1]',
    useButton() {
        I.click({xpath: this.xpathButton});
    },
};

**Comment by Vorobeyko** [comment]
Thank you @rebajz !
I fix it ASAP)

**Comment by Vorobeyko** [comment]
@rebajz Do you use Window?

**Comment by rebajz** [comment]
@Vorobeyko yes (win 10)
