### ISSUE TITLE
Programmatical API via runners

### ISSUE THREAD

**Issue by jeremyrajan** [Codeception/CodeceptJS#210]
Hi!

Great lib and love the flexibility. I was wondering if you guys have programmatical API to run tests or so. Since, out projects we have an external tool running the task/test. CLI is not an option for us now. I tried exporting the codeceptjs lib and running but not really getting there.

Any idea?

Thank you!
Jeremy

**Comment by cnworks** [comment]
Maybe you can use `lib/command/run` to initiate tests and work around the CLI.

**Comment by DavertMik** [comment]
Yes, you can start with explring `lib/command/run` and `lib/codecept.js` but I think this parts are not yet stabilizied and may change before 1.0. So there is no programmatical APIs yet. Once the runner is considered stable it will be declared as API

**Comment by DavertMik** [comment]
The API is getting stabilized and is listed here http://codecept.io/hooks/#api
So yes, from now you can create custom runners
