### ISSUE TITLE
Add ability to nest features

### ISSUE THREAD

**Issue by joefitter** [Codeception/CodeceptJS#211]
The ability to nest features would be useful in grouping together common before/after tasks, in a similar way to mocha:

```js
describe('The Page', () => {
  beforeEach(() => {
    gotoPage()
    doSomeStuff()
  })

  ... tests

  describe('Some tests that require the same setup', () => {
    beforeEach(() => {
      doSomeMoreStuff()
    })

    ... more tests
  })
})
```

A similar feature in CodeceptSJ would be useful for cutting down code duplication by grouping together feature blocks

**Comment by DavertMik** [comment]
Not sue if it is a good idea to implement this the same way mocha does. Each scenario is pretty slow as it runs a browser instance and hiding it inside a nested block will make it harder to follow and debug. My current suggestion is to use PageObject or StepObject to move setup steps into them and reuse between tests.

Generally speaking - nesting code adds a complexity to it. So right now I'm not convinced ;) And will have tests to be easy to read in BDD way
