### ISSUE TITLE
Selenoid plugin

### ISSUE THREAD

**Issue by DavertMik** [Codeception/CodeceptJS#2117]
We need a built-in [Selenoid](https://aerokube.com/selenoid/latest/) plugin so we could launch Selenium and Browsers in containers with VNC sessions and record a video. 

Usage:

```js
plugins: {
  selenoid: {
    enabled: true,
    // selenoid options go here
    autoStart: true; // start and stop container
    // additional selenoid config goes here:
   sessionTimeout: '30m',
   enableVideo: true,
   enableLog: true,
   timeZone: '' // optional
  }
}
```

How it can be used now: https://codecept.discourse.group/t/codeceptjs-selenoid-integration/89

### How it should start

When a plugin is enabled and autoStart: true -> a container should be launched. Let's use Docker containers to avoid downloading and storing other files. https://aerokube.com/selenoid/latest/#_option_2_start_selenoid_container Also, let's focus on linux implementation at first.

So basically the code should be like this:

```js
// start daemonized docker process 
execSync('docker run -d ... aerokube/selenoid ... ');
//
event.dispatcher.on(event.all.after, () => {
  execSync('docker stop selenoid');
});
```
### Passing capabilities

[Selenoid expects its settings to be passed via capabilities](https://aerokube.com/selenoid/latest/#_special_capabilities), which can be configured under `WebDriver` config helper:

```js
WebDirver: {
   "selenoid:options": {
        // pass Selenoid config here
  }
}
```
Now we can set this capabilities from a plugin:

```js
  const WebDriver = container.helpers('WebDriver');
  WebDriver._setConfig(Object.assign(WebDriver.options, {
      "selenoid:options": conf
   }));
```

Capabilities like "name" (a name of a test) or "videoName" should be passed dynamically for each test so we should use `event.test.before` and `WebDriver._setConfig` method for this:

```js
event.dispatcher.on(event.test.before, (test) => {
   const options = WebDriver.options;
  recorder.add('settting selenoid capabilities', () => {
      options["selenoid:options"].name = test.title;
      options["selenoid:options"].videoName = test.title + '.mp4'
      WebDriver._setConfig(options);

      // here we can also print that video is saved to ... test.title + '.mp4' if a video recording is enabled
  });
})
```

** This should never work inside worker process. But should be executed inside main process only**

## Supported helpers

Initially, it should WebDriver only but it is not that hard to add Puppeteer implementation as well. Anyway, the code should be designed to support Puppeteer helper as well.

## Reference:

* wdio plugin (auto starts selenium server) - https://github.com/Codeception/CodeceptJS/blob/master/lib/plugin/wdio.js
* aerokube plugin (cloud version of selenoid) - https://github.com/codecept-js/aerokube-plugin/blob/master/index.js

**Comment by GSasu** [comment]
Maybe it would be a good idea to add the possibility to specify a docker-compose file, this is how I use selenoid and I'm probably not the only one.

Additionally, have an object where you specify the config for the `browsers.json` file.

**Comment by koushikmohan1996** [comment]
> Maybe it would be a good idea to add the possibility to specify a docker-compose file, this is how I use selenoid and I'm probably not the only one.
You don't have to create or start selenoid container, it will be taken care by codceptJS itself. But if you insist we can have a compose file :) . @DavertMik  Your view?

> Additionally, have an object where you specify the config for the `browsers.json` file.
Yes, that is a good idea thanks :)
