### ISSUE TITLE
group together features in suites

### ISSUE THREAD

**Issue by joefitter** [Codeception/CodeceptJS#212]
Currently it appears that tests are organised 2 levels deep: features -> scenarios. It would be useful to have another level for more complex applications, with the option to extend/override main config at this level.

The addition of Suites would sit above features each with their own optional overrides or custom config that can be used in any child features/scenarios.

**Comment by APshenkin** [comment]
You can now use http://codecept.io/advanced/#multiple-execution and http://codecept.io/advanced/#groups to manage test suites

**Comment by ismail-codinglab** [comment]
I am used to having a `describe` and a `test` just like in jest / jasmine.

Neither of those links provide such thing, is it possible to do some grouping like with `describe` ?
