### ISSUE TITLE
JS naming convention broken

### ISSUE THREAD

**Issue by osher** [Codeception/CodeceptJS#213]
Great idea, and I love your work. But.

`Capitalized` symbols are expected to be constructor functions.
But yet - you use `Feature`, `Scenario`, `Before`, but `within` and not `Within`.

Is there a way I can customize that to adhere to the norm or at least apply consistency?

**Comment by DavertMik** [comment]
The idea of using Before/Scenario/Feature is maintaining BDD (Gherkin) compatibility. This way scenarios look like they are written in native language. `within` is not a part of BDD specifications and so it written as native functions. 

I think you can customize it. It would be even better if those functions names could be translated. I will try to provide you some guidance with that. But a bit later

**Comment by osher** [comment]
Hmm. Interesting. However - Sounds to me half way.
I think that if we found the way to put it in a yaml - then we could have ended with a document that is not code (or at least, free of syntax huzzle such as dots, brackets, quotes, argument lists and so on and really looks like english) - then we could have claimed compatibility with Gherkin. But what we have now is strictly code that effectively addresses developers.

I think that 90% of the cases can be described in a yaml almost out of the box - i.e. with a very low-level translator. The challange is to allow the flexibility of add-hock hanlders you use for assertions. 

I'd love to help. I adore what you've started - I'm at your service, whenever you find the time to let me in.

**Comment by osher** [comment]
Actually, there could be a very easy way to do it.
Here's a mocha ui adapter I wrote before, in which I learnt how tests-suites are built behind the scene:
https://github.com/osher/mocha-ui-exports

We could write a mocha-UI adapter that is built of a require-yaml part, where yaml docs can be required, and iterates over the returned document by strategy.

Let me know what you think :)

**Comment by DavertMik** [comment]
@osher 
Sorry, I missed your comment, and now stumbled upon it. Happy new year :)

I really like the idea with Yaml. I think this can be used as alternative format for writing tests. Could you implement it in `lib/interfaces/` just the same way as it is done in `lib/interfaces/bdd`. If you have still have time, and intention to do it. Thanks

**Comment by osher** [comment]
@DavertMik  - I'm sorry, but i no longer have the time I intended to dedicate to this project - my hands are full for the time being :(

Another factor is that meanwhile we were discussing the organization I'm part of now chose to work with the ruby-based cucumber, and there's nothing I can do about it. If I ever find time for it - it would be my own free time.

I'll keep following the project, and hope I will find time slots to contribute, but alas not now ...

**Comment by DavertMik** [comment]
thanks for update. I think I will close this issue as it is not in my short-list either, so to concentrate on other tasks.
