### ISSUE TITLE
Improve pause 

### ISSUE THREAD

**Issue by DavertMik** [Codeception/CodeceptJS#2132]
Inside pause mode you should be able to:

* launch any NodeJS command (which returns a promise)
* access page objects 
* access vars passed from a test

### Implementation:

```js
I.click('xxx');
pause({
   variable1, variable2, pageObject1 // pass in all objects as parameters into pause
})
```

### Usage

Inside the interactive shell you should be able to remove `I.` prefix by pressing BackSpace. Once you pressed backspace you can use any other object passed into pause so you could type in like:

```
console.log(variable1);
```
or 
```
pageObject1.open();
```

**Comment by koushikmohan1996** [comment]
@DavertMik 

> Inside the interactive shell you should be able to remove I. prefix by pressing BackSpace. Once you pressed backspace you can use any other object passed into pause so you could type in like:

This may be complicated for users to understand. Why don't we have something like in the gif? Where the user can directly use the commands. If you want we can mention that `I can be used to interact with the browser` as a point in CLI.

![pause](https://user-images.githubusercontent.com/24666922/72222706-e19c5000-358d-11ea-9df8-984c1e8fb9ce.gif)

**Comment by pablopaul** [comment]
@koushikmohan1996 I like the idea to remove explicit usage of `I` from the CLI and default to it.
