### ISSUE TITLE
Please enable Cypress+CodeceptJS Github Action

### ISSUE THREAD

**Issue by bionicles** [Codeception/CodeceptJS#2142]
#### What are you trying to achieve?

The syntax for CodeceptJS is amazing and we would like to use it alongside Cypress to matrix-test our open source web app using Github Actions across. Basically just want to write CodeceptJS tests and have them run in a docker container across multiple browsers, screen sizes, and operating systems, and be able to use the Cypress GUI to go in and review the results  

#### What do you get instead?

We currently have a docker container which runs the codecept tests however this doesn't have nice rewind / debug functionality like Cypress (it's unclear what happens to the screenshots and you have to parse logs)

### Details

* CodeceptJS version: latest
* NodeJS Version: 12
* Operating System: ubuntu 18.04, ubuntu 16.04, 
* puppeteer 

https://github.com/cypress-io/cypress-example-docker-compose
https://github.com/cypress-io/cypress-docker-images
https://github.com/cypress-io/github-action

**Comment by bionicles** [comment]
https://github.community/t5/GitHub-Actions/How-do-you-matrix-test-a-website-on-mobile-browsers-and-screen/m-p/43418/highlight/false#M5376

**Comment by DavertMik** [comment]
> codecept tests however this doesn't have nice rewind / debug functionality like Cypress 

Well, it does. We have UI like in Cypress https://codecept.io/ui/
We have step by step screenshot reports (for headless debug)
You can record a video via Selenoid plugins
And basically interactive pause solve most of debug issues...

As for your question - we have Docker image but we don't have as many engineers to work on improving support for GitHub Actions. Unlike Cypress we are not a commercial company so we have very limited resources
