### ISSUE TITLE
CodeceptJS + Macaca

### ISSUE THREAD

**Issue by xudafeng** [Codeception/CodeceptJS#215]
@DavertMik

http://macacajs.github.io/macaca/

**Comment by DavertMik** [comment]
Interesting project. How do you think they can play together!

**Comment by DavertMik** [comment]
@xudafeng can we talk about CodeceptJS + Macaca playing together? Is chat an option for you?

**Comment by xudafeng** [comment]
@DavertMik sure

**Comment by DavertMik** [comment]
@xudafeng but how can I connect you? ;) My Skype is `davert.ua` Please find me there.
