### ISSUE TITLE
Output dir doesn't auto create when tests run by command 'codeceptjs run-workers 5'

### ISSUE THREAD

**Issue by Elverslane** [Codeception/CodeceptJS#2154]
#### What are you trying to achieve?
I want to see my tests passed after running like `codeceptjs run-workers 5` and save screenshot 
#### What do you get instead?
instead I get error ` ENOENT: no such file or directory, open '/Users/WebstormProjects/e2e/.codeceptjs-output/test.png'`
because output dir was not created

### Details

* CodeceptJS version: 2.3.6
* Operating System: macos
* puppeteer

```js
exports.config = {
    tests: './user-scenario/**/*.test.ts',
    output: '../../.codeceptjs-output',
    plugins: {
        customLocator: {
            enabled: true,
            attribute: 'data-test',
            showActual: true,
        },
    },
    helpers: {
        Puppeteer: {
            waitForTimeout: 3000,
            waitForAction: 200,
            show: !!process.env.VISUAL,
            chrome: {
                args: ['--no-sandbox', '--disable-setuid-sandbox'],
                defaultViewport: {
                    width: 1280,
                    height: 960,
                },
                executablePath: process.env.CHROMIUM_PATH,
            },
        },
    },
    include: {
        I: './settings/steps.js',
    },
    bootstrap: null,
    mocha: {},
    name: 'e2e',
    require: ['ts-node/e2e'],
};
```

**Comment by PeterNgTr** [comment]
I think there is no issue with output folder creation. It worked fine for me.

<img width="764" alt="Screenshot 2020-01-21 at 15 37 50" src="https://user-images.githubusercontent.com/7845001/72813686-13837580-3c64-11ea-9d29-195950c1b9ef.png">

**Comment by Elverslane** [comment]
> I think there is no issue with output folder creation. It worked fine for me.
> 
> <img alt="Screenshot 2020-01-21 at 15 37 50" width="764" src="https://user-images.githubusercontent.com/7845001/72813686-13837580-3c64-11ea-9d29-195950c1b9ef.png">

before run tests you should have no this dir in project. Try to launch this test 
`before run tests you should have no this dir in project.`

**Comment by PeterNgTr** [comment]
oh I see, this happens with `run-workers`, my last try was with `run` cmd. 😅
