### ISSUE TITLE
Use tags to specify which tests scripts to run. 

### ISSUE THREAD

**Issue by artiomnist** [Codeception/CodeceptJS#217]
I love the work you're doing! Its really awesome!

It would be nice if there was a way to tag tests so that only certain tests are run. For example, having tags in the test file as follows: 

`Feature('My Awesome Feature', ['MOBILE', 'RETAIL', 'HOMEPAGE']);`

This could allow tests to be run as follows rather than using --grep.

`codeceptjs run . -tags="MOBILE"`

This would allow all tests with the mobile tag to be executed. Any thoughts?

**Comment by DavertMik** [comment]
Good idea, I like it. 

As a workaround, currently you can specify tags inside scenario or feature titles like `@mobile @api` and execute specific group by running `--grep mobile`.

**Comment by scottconnerly** [comment]
This would be ah-mazing. Wholehearted "yes please!"

**Comment by APshenkin** [comment]
There is powerful grep from mocha implementation that we recommend to use http://codecept.io/advanced/#groups
