### ISSUE TITLE
commands after switchTo in webdriverio works like there was no switchTo

### ISSUE THREAD

**Issue by aldarund** [Codeception/CodeceptJS#218]
For example i want to test a page with link to target=_blank.
I use  I.switchTo(0);
And in selenium i see that the it indeed switched to this new page. But any following command after it just bring focus on the first page again, so im not able to test whats on that second page.

**Comment by manibushan13** [comment]
Hi @aldarund 
is switchTo method is working for you ?
because i tried it's not working for. getting - Unsupported frame locator: java.util.HashMap

**Comment by APshenkin** [comment]
Please try to update to 1.0.0 and try again. to switch to iframe, use `switchTo`, if you want to switch tab, use `switchToNextTab`
