### ISSUE TITLE
Method seeCssPropertiesOnElements not working

### ISSUE THREAD

**Issue by PiQx** [Codeception/CodeceptJS#2182]
#### What are you trying to achieve?
I call method seeCssPropertiesOnElements. I get the following error  
![image](https://user-images.githubusercontent.com/36976954/73712545-00c97000-473d-11ea-8ec4-ba300bc30e5c.png)
This element have backgroundProperty
![image](https://user-images.githubusercontent.com/36976954/73712645-50a83700-473d-11ea-8fff-168a99839a0f.png)

> Provide test source code if related

```js
  within(contentEditor.formBlock.root, () => {
    I.seeCssPropertiesOnElements(contentEditor.formBlock.highlightedBlockFormItem, {background: '#fffd54'});
  });
```

### Details

* CodeceptJS version: 2.4.3
* NodeJS Version: 10.16.0
* Operating System: ubuntu
* puppeteer

**Comment by garbuzzzz** [comment]
Use:
const value = await I.grabCssPropertyFrom(contentEditor.formBlock.highlightedBlockFormItem, 'background')
console.log('vot ono: ', value);
to see what exists in this property. You may see something like that: 
"rgb(255, 183, 93) none repeat scroll 0% 0% / auto padding-box border-box" by one string. Sad but true.

**Comment by sumeet6181** [comment]
Hi team,
I am trying to verify font-weight of the element but it is giving an error 
![image](https://user-images.githubusercontent.com/71484517/171255811-5c8accf8-79b6-4764-b89b-86a73b22dfa6.png)

![image](https://user-images.githubusercontent.com/71484517/171256314-cd6d97c7-5488-4886-9088-e041ae6af8ef.png)
