### ISSUE TITLE
There should be a method similar to pressKey wich could press multiple keys in sequence

### ISSUE THREAD

**Issue by raschmitt** [Codeception/CodeceptJS#2185]
#### What are you trying to achieve?

Populating text to places which are not text fields or textareas.

#### What do you get instead?

As I can't use ```fillField()``` to achieve this, in these cases, I end up using multiple lines of ```pressKey()```, or sometimes transforming my string into an array and using a ```forEach()``` on it to solve the problem.

I think that a method like ```pressKeys``` would be ideal to solve problems like this.

```I.pressKeys("My long text here...")```

**Comment by xMutaGenx** [comment]
Hey @raschmitt meanwhile, you can create a custom helper for yourself

`custom_helper.js`
```js
class Custom_Helper extends codecept_helper {

    pressKeys(keys) {
        const browser = this.helpers['WebDriver'].browser;
        browser.keys(keys.split(''));
    }
}

module.exports = Custom_Helper;
```

in your `codecept.conf.js`
```js
//...
helpers: {
        Custom_Helper: { 'require': 'location/to/my/helpers/custom_helper' }
    },
//...
```
Usage:
```js
I.pressKeys('This is the long text you want...');
```

**Comment by raschmitt** [comment]
Hey @xMutaGenx, this is going to be very helpful for me, yet I still think this should be a standard method.

**Comment by PeterNgTr** [comment]
> Hey @xMutaGenx, this is going to be very helpful for me, yet I still think this should be a standard method.

you could create a PR for that :)

**Comment by xMutaGenx** [comment]
True @PeterNgTr I do think it shouldn't be called `I.pressKeys` however, as it could be a bit messy with mod keys, might call it something like `I.Type`

**Comment by PeterNgTr** [comment]
> True @PeterNgTr I do think it shouldn't be called `I.pressKeys` however, as it could be a bit messy with mod keys, might call it something like `I.Type`

`pressKey` - Presses a key in the browser (on a focused element).

Hint: For populating text field or textarea, it is recommended to use fillField

Or maybe enhance the `fillField` method

**Comment by DavertMik** [comment]
I agree to add another method 

```
I.type('keys')
```

We are in situation where it's easier to add a new method to all helpers than update all current helpers to introduce a new behavior. `I.type` should be the best solution for now as it ca be combined with `I.pressKeyDown` and `I.pressKeyUp`.

Any volunteers to implement it?

**Comment by aefluke** [comment]
I'm going to dive to this one. I'll inform about my iterations.

**Comment by xMutaGenx** [comment]
@aefluke oof, just raised a PR, review and update if you'd like to :)
