### ISSUE TITLE
=> doesnt work?

### ISSUE THREAD

**Issue by williamhatch** [Codeception/CodeceptJS#2195]
#### What are you trying to achieve?
evaluate the js code
#### What do you get instead?
Interactive shell started
 Use JavaScript syntax to try steps in action
 - Press ENTER to run the next step
 - Press TAB twice to see all available commands
 - Type exit + Enter to exit the interactive shell
 I.=> 1+2
 ERROR  Unexpected token =>

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 2.4.3
* NodeJS Version:
* Operating System: ios
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by vatsan34** [comment]
Works fine for me in Windows.

**Comment by DavertMik** [comment]
Probably version mismatch... 
Can't confirm or replicate
