### ISSUE TITLE
FillField doesn't clear value before insert new

### ISSUE THREAD

**Issue by Elverslane** [Codeception/CodeceptJS#2203]
#### What are you trying to achieve?
Fills a text field or textarea, after clearing its value, with the given string by `fillFiled` function
#### What do you get instead?
instead I get value that already was in field + new value

```bash
I.fillField('surname', 'Федореев'); 
```
<img width="450" alt="Снимок экрана 2020-02-14 в 16 29 20" src="https://user-images.githubusercontent.com/17493900/74535776-9d62ed80-4f47-11ea-8edb-120d1dc7be3d.png">

### Details

* CodeceptJS version: 2.4.3
* NodeJS Version: 12.0
* Operating System: macOS
* puppeteer

**Comment by monotonesol** [comment]
@Elverslane 
Looks like an application problem. I was not able to reproduce with default input. 
You can try to call I.clearField before the fillField. By the code codeceptjs  relies on puppeteer "type" realization.

**Comment by Elverslane** [comment]
@monotonesol yes you are right. That's a problem in my app with focus on field. Sorry for fake report.

**Comment by aesyondu** [comment]
> @monotonesol yes you are right. That's a problem in my app with focus on field. Sorry for fake report.

Hi, could you share what the problem with focus was, and what was the solution? I'm currently experiencing the same thing, though I'm using a <div contenteditable="true">.

**Comment by Elverslane** [comment]
> > @monotonesol yes you are right. That's a problem in my app with focus on field. Sorry for fake report.
> 
> Hi, could you share what the problem with focus was, and what was the solution? I'm currently experiencing the same thing, though I'm using a `<div contenteditable="true">`.

just use **I.clearField()** or **I.click();** before fillFIeld
