### ISSUE TITLE
How to run tests in multiple browser

### ISSUE THREAD

**Issue by yaoxiao1993** [Codeception/CodeceptJS#2207]
#### What are you trying to achieve?
Run tests in multiple browser
#### What do you get instead?
run this command and got an error `codeceptjs run-multiple --all`
error: `Multiple runs not configured, add "multiple": { /../ } section to config`

> Provide console output if related. Use `--verbose` mode for more details.
![image](https://user-images.githubusercontent.com/37375987/74818979-90c10980-533a-11ea-9678-0e57ee617339.png)

```bash
# paste output here
```

> Provide test source code if related

```js

Feature('Homepage');

Scenario('Homepage @dev@qa@uat', (I) => {
    I.amOnPage('/');
    I.see('Login', 'button');

});


```

### Details

* CodeceptJS version: 2.3.5
* NodeJS Version: v10.15.3
* Operating System: mac 10.15.3
* puppeteer || webdriverio || protractor || testcafe version (if related): testcafe 1.6.1
* Configuration file: codecept.conf.js, jsconfig.json, package.json

```js
codecept.conf.js file:
exports.config = {
  tests: './test_case/*_test.js',
  output: './output',
  helpers: {
    TestCafe: {
      url: 'https://swgen2-dev.successwareg2.com',
      // browsers: ['safari','firefox'],
      show: true,
      multiple: {
        basic: {
          // run all tests in chrome and firefox
          browsers: ["chrome", "firefox"]
        },

        smoke: {
          browsers: [
            "firefox",
            // replace any config values from WebDriver helper
            {
              browser: "chrome",
              windowSize: "maximize",
              desiredCapabilities: {
                acceptSslCerts: true
              }
            },
          ]
        },
      }
    }
  },
  include: {},
  bootstrap: null,
  mocha: {},
  name: 'swgen2-web-e2e'
}

jsconfig.json file:
{
  "compilerOption": {
    "allowJs": true
  },
  "plugins": {
    "allure": {}
  },
  "multiple": {
    "smoke": {

      "grep": "@smoke",


      "outputName": "smoke",

      "browsers": [
        "firefox",
        {"browser": "chrome", "windowSize": "maximize"}
      ]
    }
  }
}

package.json file:
{
  "name": "swgen2-web-e2e",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "codeceptjs run --steps"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "allure-commandline": "^2.13.0",
    "codeceptjs": "^2.3.5",
    "testcafe": "^1.6.1"
  }
}

```

**Comment by Elverslane** [comment]
'multiple' object should be in one line with tests, output, helpers like 
`exports.config = {
  tests: './test_case/*_test.js',
  output: './output',
  helpers: {},
  multiple: {},`

**Comment by yaoxiao1993** [comment]
'multiple' object should be in one line with tests, output, helpers. That works.

**Comment by yaoxiao1993** [comment]
I got another issue that the test not run in chrome and firefox, but only run in chrome for twice.
Here is the running message:
