### ISSUE TITLE
REST helper sets content-type header when request body is a string even when content-type is already set

### ISSUE THREAD

**Issue by pmarshall-legacy** [Codeception/CodeceptJS#2224]
Hi! I'm trying to verify that an API endpoint responds with a 400 error code when it receives bad JSON in the request body. 

To do this, I set the "Content-Type" header of my request to "application/json" and send a string with malformed JSON as the request body. I have been getting a 422 error code, however, instead of the expected 400.

I noticed that it being caused by [this](https://github.com/Codeception/CodeceptJS/blob/3eddbfb8fb11fc8a1bc6cff238efe2b076d862ea/lib/helper/REST.js#L78) line in REST.js, which sets the Content-Type header to `application/x-www-form-urlencoded` whenever the request body is a string. If I go into node_modules/codeceptjs and remove that line, the test passes.

One solution to this would be to check if Content-Type already exists on the headers object before setting it. If this is a sufficient fix I'm happy to make a PR. However this could possibly cause breaking changes in other people's tests if they're currently relying on Codecept to override an existing headers object in their codebase, so I'll leave it to the developers to decide what to do about this

* CodeceptJS version: 2.4.3
* NodeJS Version: 12.4.0

**Comment by PeterNgTr** [comment]
I thought there is a PR #1626 to update REST helper, not sure if this resolves your issue there.

**Comment by pmarshall-legacy** [comment]
Thanks @PeterNgTr  for pointing out that PR. I think the changes there are to respect any default headers you set in codecept.conf.js. That would not help me in this case since I'm setting a header for one particular API, which is getting overwritten.

**Comment by PeterNgTr** [comment]
@pmarshall-legacy I would think of adding a conditional check before this line https://github.com/Codeception/CodeceptJS/blob/3eddbfb8fb11fc8a1bc6cff238efe2b076d862ea/lib/helper/REST.js#L78. So let's say if we provide the `request.headers['Content-type']`, then we set it as `Content-type` header in request, otherwise, it just sets the `Content-type` header like before.

**Comment by pmarshall-legacy** [comment]
@PeterNgTr  that would work perfectly for me, care if I make a PR?

**Comment by PeterNgTr** [comment]
@pmarshall-legacy that would be great!
