### ISSUE TITLE
while using click() in (with testcafe as helper) an error is thrown

### ISSUE THREAD

**Issue by theTainted** [Codeception/CodeceptJS#2226]
#### What are you trying to achieve?
I am trying to use click() to click on a label. 
I believe this happens when there are more than one label with the same text.

#### What do you get instead?
I get an error message 
The error message is 

```bash
 TestCafe Error: {"filename":"\\node_modules\\codeceptjs\\lib\\helper\\TestCafe.js","lineNum":1213,"callsiteFrameIdx":6,"stackFrames":[{},{},{},{},{},{},{}],"isV8Frames":true} {"code":"E26","isTestCafeError":true,"callsite":{"filename":"C:\\AutomationProjects\\Caru_codecept\\node_modules\\codeceptjs\\lib\\helper\\TestCafe.js","lineNum":1213,"callsiteFrameIdx":6,"stackFrames":[{},{},{},{},{},{},{}],"isV8Frames":true}}
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:2.5.0
* NodeJS Version:12.0.0
* Operating System:Windows 10
* Tescafe 1.8.2
* Configuration file:

```js
# paste config here
{
  "name": "codecept",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "chai": "^4.2.0",
    "codeceptjs": "^2.5.0",
    "import-export": "^1.0.1",
    "mocha-junit-reporter": "^1.23.3",
    "mochawesome": "^4.1.0",
    "testcafe": "^1.8.2"
  },
  "dependencies": {}
}

```

**Comment by PeterNgTr** [comment]
based on the code, it will try to click on the first element https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/TestCafe.js#L1213

**Comment by theTainted** [comment]
Yes, the thing is there els.count returns 2. and for my example, 
the visibility  `const firstElement = await els.nth(0);` is false
