### ISSUE TITLE
Negative amount of tests failed

### ISSUE THREAD

**Issue by Thijmen** [Codeception/CodeceptJS#2257]
#### What are you trying to achieve?

I am trying to run my tests parallel, so with the option `run-workers 5`. After running all the tests, I get this as output:

`
FAIL  | 60 passed, -6 failed   // 590.534s
`

When running with `--verbose`, I get the same output, but I see which test failed:

```
-- FAILURES:
   1) Order Flow - Mobile

```

I am wondering if I am doing something wrong, because I am getting negative failed tests. I expected to see:

`
FAIL  | 60 passed, 1 failed   // 590.534s
`

I am unable to share the tests as they are private, but if you need anything, please let me know. I'd gladly help to resolve this.

### Details

* CodeceptJS version: 2.5.0
* NodeJS Version:  v13.10.1
* Operating System: Debian (Buster) (In Docker)
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js

let config = {
  tests: '../mobile_tests/*/*_test.js',
  timeout: 30000,
  output: '../output',
  helpers: {
    Puppeteer: {
      windowSize: '1920x1080',
      deviceScaleFactor: 1,
      isMobile: false,
      hasTouch: false,
      isLandscape: true,
      waitForNavigation: [ 'domcontentloaded', 'networkidle0' ],
      waitForAction: 500,
      fullPageScreenshots: true,
      chrome: {
        'ignoreHTTPSErrors': true,
        'args': ['--headless', '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
      }
    },
    MockRequest: {}
  },
  include: {
    I: '../common/steps_file.js',
    mockExternalCalls: '../common/mock_external_calls.js'
  },
  name: 'acceptance_tests_mobile',
  multiple: {
    parallel: {
      chunks: 200
    }
  },
  plugins: {
    allure: {},
    autoDelay: {
      enabled: true,
      delayBefore: 250,
      delayAfter: 250
    },
    retryFailedStep: {
      enabled: true,
      minTimeout: 2000,
      retries: 10
    }
  }
}

exports.config = config

```

**Comment by jonatask** [comment]
For me, sometimes it says _9 passed, -6 failed_ but actually all of the tests passed. Also, I ran 3 test cases, not 9. Therefore, it fails the pipeline even when the tests passed.

**Comment by PeterNgTr** [comment]
I think once the `run-workers` released, your issue will be fixed. https://github.com/Codeception/CodeceptJS/pull/2236

**Comment by Thijmen** [comment]
@PeterNgTr  I assume that'll be with the release of v3.0?

**Comment by PeterNgTr** [comment]
yeah @Thijmen I thought it was part of v3 release.

**Comment by Thijmen** [comment]
@PeterNgTr I just ran a suite with the v3 branch, it appears the issue is still there.

**Comment by PeterNgTr** [comment]
It’s still under testing phase so it’s not finished. ^^

**Comment by Thijmen** [comment]
Hey @PeterNgTr, thanks for your reply. #2236 is already merged to that branch, so I though I'd give it a try... so - do we have any timeline? Otherwise I might have to persue other possibilities or postpone my project for a while.

**Comment by PeterNgTr** [comment]
It’s hard to tell when. Maybe @DavertMik gives you more info.

**Comment by Vorobeyko** [comment]
@Thijmen Hello!
Please, Try new version 2.6.2 !
It bug fixed!)
