### ISSUE TITLE
Right Click with protractor

### ISSUE THREAD

**Issue by vaubrun13** [Codeception/CodeceptJS#227]
Hello,

First of all, thanks for the awesome job. I need to perform a right click in one of my scenario but I can't manage to do it.

Does someone knows how to perform a right click with protractor ?

**Comment by DavertMik** [comment]
Currently there is no built-in functionality for that. However, you can write your own helper method and call protractor API for right click directly. But I think I will add this method to next version of CodeceptJS

**Comment by vaubrun13** [comment]
I found stuff like this : 

    browser.actions().mouseMove(elementVar).perform();
    browser.actions().click(protractor.Button.RIGHT).perform();

Apparently there is no specific API do a right click with protractor :(
I'll wait for you implementation

**Comment by DavertMik** [comment]
Yeah, you can imlpement it by yourself by placing this stuff into a helper method

```js
rightClick() {
   let browser = this.helpers['Protractor'].browser;
   browser.actions().mouseMove(elementVar).perform();
   return browser.actions().click(protractor.Button.RIGHT).perform();
}
```

smth like it

**Comment by ishan50492** [comment]
I am trying to right click on the 'forgot password' link. The below code is not working for me. It instead left clicks on it. Tried both on Chrome and Firefox. Any suggestions?

`let e = element(by.xpath("//span[text()='Forgot your password?']/parent::a"));
await browser.actions().mouseMove(e).perform();
await browser.actions().click(protractor.Button.RIGHT).perform();`

**Comment by GreenJeans** [comment]
I'm having the same issue as @ishan50492 

In my code below, method 1 causes no visible page interaction.
Method 2 causes a left-click.
```
// todo - neither of these methods are working - no errors thrown, no right click event.
const rightClick = async (element) => {
    // method 1
    // await browser.actions()
    //     .click(element, protractor.Button.RIGHT)
    //     .perform();

    // method 2
    await browser.actions().mouseMove(element).perform();
    await browser.actions().click(protractor.Button.RIGHT).perform();
};
```

Any suggestions for a workaround?

**Comment by PeterNgTr** [comment]
@ishan50492 @GreenJeans the rightClick of protractor is already in the Codeceptjs. Have you guys tried it out? https://codecept.io/helpers/Protractor#rightclick

**Comment by GreenJeans** [comment]
@PeterNgTr Yeah, you can see that the Codeceptjs implementation is the same as method 2 posted above.  This method performs a left-click, I can substitute it for click() in all my tests without issue.

https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Protractor.js#L482
