### ISSUE TITLE
autoretry not work

### ISSUE THREAD

**Issue by spham** [Codeception/CodeceptJS#2273]
Hi
When i launch

`npx codeceptjs run --steps --grep "@core"`

it failed randomly. 

![Capture](https://user-images.githubusercontent.com/1083631/77092720-54043300-6a0a-11ea-95f4-56e677e36293.PNG)

autoretry not work

```
 plugins: {
    screenshotOnFail: {
      enabled: false
    },
    retryFailedStep: {
      enabled: true,
      
    },
```

**Comment by spham** [comment]
and retry not work

```
 retryFailedStep: {
      enabled: true,
      retries: 3,
    },
```

**Comment by golfzaptw** [comment]
@spham  I use this 
```
retryFailedStep: {
            enabled: true,
            defaultIgnoredSteps: [],
            minTimeout: 5000,
        },
```
It works.Because `https://codecept.io/plugins/#retryfailedstep` defaultIgnoredSteps set includes
