### ISSUE TITLE
Testing window popups created via window.open API

### ISSUE THREAD

**Issue by sidsarasvati** [Codeception/CodeceptJS#228]
Hi, is there a way I can test a window popout behavior in my app? Basically, I want to assert that the app created a popup window as expected. The popout is created using the window.open() API. 

Some googling revealed the  PHP codeception had a I->swithToWindow() API method to switch between windows during testing. I think having such API will enable popup and secondary window testing use cases.

**Comment by APshenkin** [comment]
duplicate of https://github.com/Codeception/CodeceptJS/issues/207
