### ISSUE TITLE
Update Puppeteer to V2?

### ISSUE THREAD

**Issue by conradkirschner** [Codeception/CodeceptJS#2282]
Is it planned to update to puppeteer 2, if yes when? :1st_place_medal: 
https://github.com/puppeteer/puppeteer/tree/v2.1.1

What is left to do for the update?

https://github.com/Codeception/CodeceptJS/blob/cea602af4c00aaa102571eff7bbdadfa25ef499b/package.json#L112

**Comment by PeterNgTr** [comment]
@conradkirschner so far, after updating to v2.1.1, there only two failed tests due to the mime type, I assume that is related to puppeteer more than codeceptjs. Also, I don't think anything prevents us from using v2 :)
