### ISSUE TITLE
`codeceptjs init` doesn't list Nightmare as an option

### ISSUE THREAD

**Issue by JustinCarmony** [Codeception/CodeceptJS#229]
Trying to test out the nightmare support, and it doesn't list it as an option when I use the `codeceptjs init` command. I'm willing to help debug to figure out why it won't show on my system, but need to be pointed in the right direction.

Thanks!

**Comment by DavertMik** [comment]
Yeah, you are right. One word to fix here https://github.com/Codeception/CodeceptJS/blob/master/lib/command/init.js#L23 

:)

**Comment by DavertMik** [comment]
Fixed in 0.4.7
