### ISSUE TITLE
I.fillField fails occasionally  when form is in bootstrap modal

### ISSUE THREAD

**Issue by ayrshid99** [Codeception/CodeceptJS#2298]
#### some times the part of string is truncated or sometimes its sent as empty  string to the field.
> Provide console output if related. Use `--verbose` mode for more details.

* 2.5.0
* 10
* windows 10
* webdriverio

**Comment by PeterNgTr** [comment]
@ayrshid99 you can try to use `I.type()`

**Comment by ayrshid99** [comment]
@PeterNgTr  can you provide an example how to use this. it seems it only takes string to be types as argument without any locator.

**Comment by PeterNgTr** [comment]
hey @ayrshid99, I think you can try to use `I.click(element)` to focus on it and then `I.type` to type the thing you want.

**Comment by ayrshid99** [comment]
@PeterNgTr i tried this but the problem persists

**Comment by ayrshid99** [comment]
i finally figured it out , it was happening because of animation i had to add implicit wait and let the animation finish.

**Comment by aesyondu** [comment]
> i finally figured it out , it was happening because of animation i had to add implicit wait and let the animation finish.

Yep, same applies to sweetalert, I had to add `wait(1)` so that the javascript click listeners will be attached.
