### ISSUE TITLE
Nightmare helper innerHTML

### ISSUE THREAD

**Issue by goschevski** [Codeception/CodeceptJS#230]
Hi guys,

I'm trying to make helper which will return HTML of the element since grabTextFrom does not work on anchors (`<a href="#">Text to fetch</a>`) for some reason.

Anyway, helper does not work even though it's pretty same as original [grabTextFrom](https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Nightmare.js#L560).

``` javascript
    grabHtmlFrom(locator) {
        return this.helpers['Nightmare']._locate(locator).then(function(els) {
            return this.helpers['Nightmare'].browser.evaluate(function(el) {
                return codeceptjs.fetchElement(el).innerHTML;
            }, els[0]);
        }.bind(this));
    }
```

Thanks in advance!

**Comment by DavertMik** [comment]
That's the reason I hate complexity of Nightmare. I can't suggest how to debug it better and I can't see visible problems in your code. Use `console.log` on server side part, and `alert` or `document.write` on clientside part...

**Comment by DavertMik** [comment]
No updates here, so I'm closing...
