### ISSUE TITLE
I give error when update new version

### ISSUE THREAD

**Issue by golfzaptw** [Codeception/CodeceptJS#2305]
#### What do you get instead?

> If found error after update new version

```bash
Unsupported waitUntil option domcontentloaded,networkidle0
```

> Provide test source code if related

```js
const goToHomePage = () => {
    I.amOnPage(testData.homePageURL)
}
```

### Details

* CodeceptJS version: 2.6.0
* NodeJS Version: v12.14.1
* Operating System: macOS Catalina v10.15.3
* Playwright version: 0.12.1
* Configuration file:

```js
Playwright: {
            url: `https://${process.env.TEST_ENV}/${process.env.SITE_LANGUAGE}`,
            show: true,
            basicAuth: {
                username: process.env.USERNAME_HOST,
                password: process.env.PASSWORD_HOST,
            },
            waitForNavigation: ['domcontentloaded', 'networkidle0'],
            browser: 'chromium',
            chromium: {
                args: [
                    '--window-size=1366,768',
                    '--no-sandbox',
                    '--disable-dev-shm-usage',
                ],
            },
            windowSize: '1366x768',
            // restart: true,
        },
```

**Comment by golfzaptw** [comment]
Have a change something or not? https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitfornavigationoptions

**Comment by idxn** [comment]
@golfzaptw can you try whether the one below works or not?

``Playwright: {
            url: `https://${process.env.TEST_ENV}/${process.env.SITE_LANGUAGE}`,
            show: true,
            basicAuth: {
                username: process.env.USERNAME_HOST,
                password: process.env.PASSWORD_HOST,
            },
            waitForNavigation:  'networkidle0',
            browser: 'chromium',
            chromium: {
                args: [
                    '--window-size=1366,768',
                    '--no-sandbox',
                    '--disable-dev-shm-usage',
                ],
            },
            windowSize: '1366x768',
            // restart: true,
        },

**Comment by idxn** [comment]
@golfzaptw if that works, please close this issue.

**Comment by golfzaptw** [comment]
It's working, thanks
