### ISSUE TITLE
OuputDir is undefined for allure plugin on using custom runner

### ISSUE THREAD

**Issue by charliepradeep** [Codeception/CodeceptJS#2321]
I am trying to make a custom runner where the global.output_dir is being set correctly but the same is not reflecting in allure defaultConfig outputDir value which is throwing path error for writing to xml in allure 

Error Occured: 
    Error processing suite.after event:
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at Object.writeSuite (C:\Users\mcharlie\node_modules\codeceptjs\node_modules\allure-js-commons\writer.js:9:32)
    at Allure.endSuite (C:\Users\mcharlie\node_modules\codeceptjs\node_modules\allure-js-commons\index.js:37:16)
    at EventEmitter.<anonymous> (C:\Users\mcharlie\node_modules\codeceptjs\lib\plugin\allure.js:192:14)
    at EventEmitter.emit (events.js:228:7)
    at EventEmitter.emit (domain.js:475:20)
    at Object.emit (C:\Users\mcharlie\node_modules\codeceptjs\lib\event.js:115:28)
    at C:\Users\mcharlie\node_modules\codeceptjs\lib\scenario.js:182:11
    at injectHook (C:\Users\mcharlie\node_modules\codeceptjs\lib\scenario.js:8:5)

```bash



allure.js Line# : 7
const defaultConfig = {
  outputDir: global.output_dir,
};

### Details

* CodeceptJS version: 2.5.0
* NodeJS Version: 12.15.0
* Operating System: Windows
* Configuration file:
exports.config = {
  output: './output',
  helpers:{
    WebDriver:{
      url:"myurl",
      browser:"chrome",
      desiredCapabilities:{
        'chromeOptions': {
          useAutomationExtension: false,
          args: [ 'start-maximized'],
 
          },
        },
      },
      host: 'localhost',
      port: 4444,
    },
  },
  include: {
    I: './steps_file.js'
  },
  
  bootstrap: null,
  teardown: null,
  hooks: [],
  gherkin: {
    features: './features/*.feature',
    steps: ['./step_definitions/steps.js']
  },
  plugins: {
    allure: {
      enabled: true,
      enableScreenshotDiffPlugin: true
    },
    screenshotOnFail: {
      enabled: true
    },
    wdio: {
      enabled: true,
      services: ['selenium-standalone']
    }
  },
};

**Comment by PeterNgTr** [comment]
@charliepradeep are you encountering the same with latest codeceptjs?

**Comment by charliepradeep** [comment]
@PeterNgTr : Yep, I am observing the same issue ["TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined"] with CodeceptJS v2.6.1 as well

**Comment by PeterNgTr** [comment]
@charliepradeep could you provide a repo that can be easily reproduced your issue?
