### ISSUE TITLE
Can I check if certain element exist or not in the page?

### ISSUE THREAD

**Issue by arclak** [Codeception/CodeceptJS#2323]
#### What are you trying to achieve?
I need to see if certain element exist in the page. If it exist, then perform certain steps otherwise other set of steps.
#### What do you get instead?
I am using I.seeElement. However, as soon as the element does not exist, it stops the entire test case.

**Comment by PeterNgTr** [comment]
@arclak that's possible. You can use the `grabNumberOfVisibleElements`.

```js

const numberOfElements = await I.grabNumberOfVisibleElements(locator);

if (numberOfElements >= 1) {
  // do whatever steps
} else {
  // do whatever steps
}
```

**Comment by stoussaint** [comment]
Sorry for bouncing on this old issue, but as it seems relevant...
This function doesn't seems to be efficient for hidden inputs, as the name suggest. But then how to check if an hidden input in actually in the DOM ?

**Comment by moeinqureshimaersk** [comment]
Any response on above query from @stoussaint ?

**Comment by liammislej** [comment]
> Sorry for bouncing on this old issue, but as it seems relevant... This function doesn't seems to be efficient for hidden inputs, as the name suggest. But then how to check if an hidden input in actually in the DOM ?

`I.seeElementInDom` / `I.dontSeeElementInDom`? depending how you have the inputs implemented you could also check some custom property.
