### ISSUE TITLE
Unsupported waitUntil option load,domcontentloaded,networkidle0,networkidle2 (Codecept + Playwright)

### ISSUE THREAD

**Issue by RatnakarShetty** [Codeception/CodeceptJS#2328]
Hi ,

I have step where i click on button and page loads with some items, to handle page load and domcontent load, i tried below configuration.But didn't work

`waitForNavigation: ['load', 'domcontentloaded', 'networkidle0', 'networkidle2'],`

getting this error message :

`Unsupported waitUntil option load,domcontentloaded,networkidle0,networkidle2`

Using codecept 2.6 and Playwright 0.12

**Comment by idxn** [comment]
@RatnakarShetty according to playwright V0.12 doc, the waitForNavigation supports string value only.

**Comment by PeterNgTr** [comment]
https://github.com/microsoft/playwright/blob/master/docs/api.md#pagesetcontenthtml-options

according to the doc, only use either one of those values 

```
"load"|"domcontentloaded"|"networkidle0"|"networkidle2"
```
