### ISSUE TITLE
history.back

### ISSUE THREAD

**Issue by christianfroehlichconsulting** [Codeception/CodeceptJS#235]
Hi, how could i go back to the site previously visited?

```
Scenario('Check Subpages without backlink', function*(I) {
    I.amOnPage('/'); // this url will change
    let nameoflink = yield I.grabTextFrom('h4:first-child a');for (var value of nameoflink) {
      I.click(value);
      // ...
      I.goBack(); // no not working - but how could i go back? browserHistory.goBack I.moveBack
    }
    // ...
});
```

Thank you for your ideas

**Comment by DavertMik** [comment]
Looks like this method is not implemented in current helper. What you can do is to write your own helper which extends current functionaltu and uses webdriverio or protractor to navigate to previous page. I know those libraries contain such methods

**Comment by christianfroehlichconsulting** [comment]
Super, thank you! Working perfect!
