### ISSUE TITLE
Wait For text timeout not working using nightmare helper

### ISSUE THREAD

**Issue by rodrigomaia17** [Codeception/CodeceptJS#236]
With the following scenario, the timeout is failing only after 30000msec 

```js
Scenario('Timeout  failing', (I) => {
  I.amOnPage('http://www.github.com');
  I.see('Welcome home');
  I.click('.header-logo-invertocat');
  I.waitForText('Priced for everyone', 2); // should fail after 2 seconds
});
```

```
codeceptjs run --steps 

-- FAILURES:

  1) login: Login with user list:
     .wait() timed out after 30000msec
```

Update: If I run 
I.wait(1); I.see('Priced for everyone');
then it works.

but if I run only the 
I.see('Priced for everyone')
then i got:

(node:47217) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot create property 'stack' on string 'codeceptjs is not defined' ^C%

**Comment by rodrigomaia17** [comment]
Update: If I run 
`I.wait(1);
 I.see('Priced for everyone');`
then it works. 

but if I run only the 
`I.see('Priced for everyone')`
then i got:

 `(node:47217) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot create property 'stack' on string 'codeceptjs is not defined'
^C% `

**Comment by DavertMik** [comment]
waitForText should work in 0.4.13 for all helpers. We have internal tests that prove it:

```

  describe('#waitForText', () => {
    it('should wait for text', () => {
      return I.amOnPage('/dynamic')
        .then(() => I.dontSee('Dynamic text'))
        .then(() => I.waitForText('Dynamic text', 2))
        .then(() => I.see('Dynamic text'));
    });

    it('should wait for text in context', () => {
      return I.amOnPage('/dynamic')
        .then(() => I.dontSee('Dynamic text'))
        .then(() => I.waitForText('Dynamic text', 2, '#text'))
        .then(() => I.see('Dynamic text'));
    });
  });
```
