### ISSUE TITLE
element.screenshot

### ISSUE THREAD

**Issue by roughsoft** [Codeception/CodeceptJS#2366]
#### What are you trying to achieve?
i want to migrate my puppeteer code to the codeception,i can not migrate these code.
can anyone help me?thank you!
#### What do you get instead?
const element=await page.waitForSelector('#yhmimg');
  await element.screenshot({ path: 'example.png' });

**Comment by PeterNgTr** [comment]
I believe you should write your custom method to capture screenshot of an element.

**Comment by roughsoft** [comment]
@PeterNgTr ,i can use puppeteer api in custom method?

**Comment by PeterNgTr** [comment]
Yeah, try to access the browser instance and you can access more methods on there. 

https://codecept.io/helpers/#development

**Comment by roughsoft** [comment]
thank you!
