### ISSUE TITLE
dry-run does not working

### ISSUE THREAD

**Issue by ledaivuong** [Codeception/CodeceptJS#2368]
#### What are you trying to achieve?
I want to run test by command
```
npx codeceptjs dry-run --steps
```
but it notifies that no test executed. It still works when I use command
```
npx codeceptjs run --steps
```
### Details

* CodeceptJS version: 2.6.2
* NodeJS Version: v10.16.0
* Operating System: Windows 10
* playwright

**Comment by PeterNgTr** [comment]
https://codecept.io/commands/#dry-run

```
When passed --steps or --debug option runs tests, disabling all plugins and helpers, so you can get step-by-step report with no tests actually executed.
```
