### ISSUE TITLE
Steps are not executed in a docker container

### ISSUE THREAD

**Issue by nayaramoura** [Codeception/CodeceptJS#237]
Hello, there!

I'm trying to execute a very simple login scenario using a docker container. The referred scenario is running and passing fine locally, but when I run it in the container it only shows the Feature name + Scenario name and then exits whithout any error.

This is my test scenario, what is working fine on my machine:

```
Feature('login');

Scenario("Login with user list", (I) => {
  I.amOnPage("/");
  I.see("My app's name");
  I.selectOption("#user_id", "nmoura");
  I.click("input[value=\"Login\"]");
  I.wait(1);
  I.see("Welcome");
});

```

Here is what I get as response on my machine:

```
> codeceptjs run --steps

CodeceptJS v0.4.5
Using test root "/Users/nmoura/Documents/github/myapp"

login --
 Login with user list
 • I am on page "/"
 • I see "My app's name"
 • I select option "#user_id", "nmoura"
 • I click "input[value="Login"]"
 • I wait 1
 • I see "Welcome"
 ✓ OK in 26195ms


  OK  | 1 passed   // 26s
```

And this is what a get when trying to run in the container:

```
> codeceptjs run --steps

CodeceptJS v0.4.5
Using test root "/usr/src/app"

login --
 Login with user list
```

It just stops. No error, no message.

Do you have any idea about what can be causing this behaviour?
It's worth mentioning that if I try to use the codeceptjs shell in the container, I see a similar behaviour (It prints the text 'String interactive shell for current suite...' and then nothing).

Some additional information:

node -v = v6.6.0
npm -v = 3.10.3
CodeceptJS = v0.4.5
helper = nightmare@2.7.0 / nightmare-upload@0.1.1

**Comment by DavertMik** [comment]
Please try to execute with `-vvv` option, it should provide you more detailed response

**Comment by nayaramoura** [comment]
Hi @DavertMik! Thanks for the tip.

So, I think the test is actually running but it isn't providing any feedback. 
I've changed my first step in order to force a failure and when I execute the test it fails but only shows the message: **Unexpected end of input**

I highlight that the behaviour of the interactive shell is also different when running in the container, only presenting the text  'String interactive shell for current suite...'  and then exiting.

Following your advice, I executed the test adding the verbose mode (since -vvv only returns the npm version). Here is the result:

```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'run',
npm verb cli   'acceptance-tests',
npm verb cli   '-verbose' ]
npm info using npm@3.10.3
npm info using node@v6.6.0
npm verb run-script [ 'preacceptance-tests',
npm verb run-script   'acceptance-tests',
npm verb run-script   'postacceptance-tests' ]
npm info lifecycle myapp@1.0.0~preacceptance-tests: myapp@1.0.0
npm info lifecycle myapp@1.0.0~acceptance-tests: myapp@1.0.0

> myapp@1.0.0 acceptance-tests /usr/src/app
> codeceptjs run --steps

CodeceptJS v0.4.6
Using test root "/usr/src/app"

login --
 Login with user list
npm verb lifecycle myapp@1.0.0~acceptance-tests: unsafe-perm in lifecycle true
npm verb lifecycle myapp@1.0.0~acceptance-tests: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/bin:/opt/jruby/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle myapp@1.0.0~acceptance-tests: CWD: /usr/src/app
npm info lifecycle myapp@1.0.0~postacceptance-tests: myapp@1.0.0
npm verb exit [ 0, true ]
npm info ok
```

Out of curiosity: Did you ever run a codecept test using Docker?

Thanks for your attention!

**Comment by artiomnist** [comment]
@nayaramoura I am able to run codeceptjs test scripts within a docker container with steps. However, when using a mochawesome reporter the steps are not displayed.

**Comment by nayaramoura** [comment]
Just updating, I have solved my problem by using the command

`xvfb-run codeceptjs run --steps` to run my tests, instead of use only `codeceptjs run --steps`

I'm still not sure about the reason why the second command works perfectly locally but don't work in the container.

If you have no interest on investigating this, feel free to close this issue.

Thanks for your previous answers.

**Comment by michaeltomasik** [comment]
@nayaramoura  @DavertMik Hi there I think this issue needs to be reopen I got this same bug even if I'm executing script like 
`xvfb-run codeceptjs run -o '{ \"helpers\": {\"Nightmare\": {\"url\": \"localhost:8080\"}}}' --steps`
