### ISSUE TITLE
How to grab link from title rel="canonical", how to grab description from meta name=description ?

### ISSUE THREAD

**Issue by christianfroehlichconsulting** [Codeception/CodeceptJS#238]
Hi

how could i grab the link from 
<title rel="canonical" href"..."...
or the content from the meta-description: 
<meta name="description" content="...."...

do i need to 
`let test = yield I.grabHTMLFrom('head link[rel=canonical]');`
and then slice out with a regex the href?

Or am i making it to complicated?

Thank you

**Comment by DavertMik** [comment]
> let test = yield I.grabHTMLFrom('head link[rel=canonical]');
and then slice out with a regex the href?

You can try. However it is recommended to create [your own Helper](http://codecept.io/helpers/) with method to grab data you need:

```js
getPageTitle() {
    // here you can do JS operations you need
}
```

Also you can connect to webdriverio functions directly (if you use it), get a content out of it, and parse it.

**Comment by APshenkin** [comment]
You can create custom helper like this for WebdriverIO:
```
grabAttribute(selector, attr, timeout) {
        timeout = timeout || 30;
        let client = this.helpers['WebDriveIO'].browser;
        return client.waitForVisible(selector, timeout * 1000).then((result) => {
            return client.getAttribute(selector, attr);
        })
    }
```

I'll add this method to basic WebdriverIO Methods for codeceptjs

**Comment by APshenkin** [comment]
already implemented http://codecept.io/helpers/WebDriverIO/#grabattributefrom
