### ISSUE TITLE
Does something like a datatable exist with codeceptjs?

### ISSUE THREAD

**Issue by richie-p** [Codeception/CodeceptJS#239]
We're absolutely in love with codeceptjs and it's simplicity. We were already using webdriverio so it's been pretty simple to make the switch. However, we were using cucumber which has data tables, which will run the same scenario multiple times with different sets of data. Does something like this exist for codeceptjs? Thanks!

**Comment by DavertMik** [comment]
Not yet. I think we can discuss the implementation. Probably you want to have something like examples feature: you pass different examples and run single test against different data. 

In Codeception I implemented with annotations, for CodeceptJS we can have it done next way:

```js
let validLogins = new Example(['login', 'password']);
validLogins.add(['davert', '123456']);
validLogins.add(['admin', '123456']);

Feature('login', validLogins, (I, example) => {
  I.amOnPage('/login');
  I.fillFiled('Username', example.login);
  I.fillFiled('Password', example.password);
  I.click('Sign In');
  I.see('Welcome '+example.login);
});
```

the idea is to define array-like structure that will be passed to feature and iterated over for tests. I'm not yet sure about syntax or implementations. Would love to hear your thoughts

**Comment by richie-p** [comment]
Yeah this seems like a smart approach.
