### ISSUE TITLE
Add full eslint integration

### ISSUE THREAD

**Issue by roadhump** [Codeception/CodeceptJS#24]
There is a `.eslintrc` file inside project, but code does not follow its rules. I suggest to fix code to satisfy rules and add lint step to test script.

**Comment by DavertMik** [comment]
Yes, that's what I'm working on )
Right now current code base is fixed, however Visual Studio Code does something strange on code formatting..

**Comment by DavertMik** [comment]
Everything is checked and fixed by `gulp static` before commit
