### ISSUE TITLE
Process hanging in version after 0.4.5

### ISSUE THREAD

**Issue by joefitter** [Codeception/CodeceptJS#242]
On updating from 0.4.5, the process now hangs after completing the suite.

**Comment by DavertMik** [comment]
Please provide your config. Probably it is related to `restart: false` option you may have used

**Comment by DavertMik** [comment]
Should be fixed in https://github.com/Codeception/CodeceptJS/pull/240
And in 0.4.7

**Comment by DavertMik** [comment]
Or in 0.4.8.

More details needed to process with this issue. Anyway, I hope it was fixed
