### ISSUE TITLE
A good way to get server response code?

### ISSUE THREAD

**Issue by SuneRadich** [Codeception/CodeceptJS#244]
I have just started using CodeceptJS and so far I am quite impressed. One of the things I want to test against, is a bunch of core URLs, and see if their response code matches what I expect.

I am using Nightmare and can see that Nightmares .goto returns the response code I want. However, I cant figure out how to get that data when using the regular I.amOnPage (that in the background uses .goto). So my current solution is to use a custom helper function, to perform the .goto() and then store result on the browser object.

I then have another custom function that tests against that result on the browser object.

But somehow this seems to be the wrong of doing it, by adding data to the browser object. Is there a built in way to get the server response code, or is tests like this not within the "area" of CodeceptJS ?

My helper functions can be seen below

```
/**
    * Go to a given page, and store the response on the browser object for later reference
    */
    customAmOnPage(url, headers) {

        // let's use chai assertion library
        let expect = require('chai').expect;

        // get nightmare instance
        let browser = this.helpers['Nightmare'].browser;

        if (url.indexOf('http') !== 0) {
            url = browser.options.url + url;
        }

        return browser.goto(url, headers).then((res) => {
            //Store results on the current browser object, giving us access to response code etc.
            browser.currentPageResponse = res;
        });
    }

    getServerResponseCode(expectedValue) {

        // let's use chai assertion library
        let expect = require('chai').expect;

        // get nightmare instance
        let browser = this.helpers['Nightmare'].browser;

        expect(browser.currentPageResponse.code).to.equal(expectedValue);
    }
```

**Comment by DavertMik** [comment]
Sorry, I'd love to answer this question but unfortunately I don't have time to try this in action. It seems to me you are close to get the answer by yourself, I think you just need to get a bit more into Nightmare helper and corresponding helper. 

I think CodeceptJS should have method like `seeResponseCodeIs()`. If you will get an idea how to implement that it would be nice to see the Pull Request.

**Comment by SuneRadich** [comment]
My solution works for me, but it seems to be the wrong approach to make a custom amOnPage test. I'll see if I have time to look into the code and make a PR.

**Comment by PeterNgTr** [comment]
make a PR here https://github.com/Codeception/CodeceptJS/pull/1383

**Comment by PeterNgTr** [comment]
no activities on this. Closed it for now.
