### ISSUE TITLE
Support for selenium-webdriver v3 

### ISSUE THREAD

**Issue by dmitry-zaets** [Codeception/CodeceptJS#246]
First of all - thanks for a great library!

Is there any plan to support selenium-webdriver v3?

**Comment by DavertMik** [comment]
Hi, could you point to JS library which implements selenium-webdriver v3?

**Comment by dmitry-zaets** [comment]
I'm not saying that anyone is supporting it :)

I'm just asking if you plan to support it in future, or you see problems which will not allow support you to support it. 

I've just seen that https://www.npmjs.com/package/selenium-webdriver has v3-beta.

**Comment by DavertMik** [comment]
I didn't investigate that and probably I won't until v3 officially released. 
But yes, I think it must be supported.

**Comment by dmitry-zaets** [comment]
Thanks!
