### ISSUE TITLE
Documentation for SeleniumWebdriver lists Protracter helper

### ISSUE THREAD

**Issue by SuneRadich** [Codeception/CodeceptJS#248]
In the section about SeleniumWebdriver, the example in the section Access from helpers, lists 

```
this.helpers['Protractor'].browser
```

Where it should list
```
this.helpers['SeleniumWebdriver'].browser
```

**Comment by DavertMik** [comment]
Thank you for noticing. 

Actually you can help to solve that. Just edit `helpers/SeleniumWebdriver.js` file and its docblock comments. Update it and make a pull request. That would be your contribution to CodeceptJS )
