### ISSUE TITLE
how can i close the browser for the failed case

### ISSUE THREAD

**Issue by tony204** [Codeception/CodeceptJS#253]
@DavertMik 
run the below case:
 I.amOnPage('/'');
  I.click('button');
I.see(); // this case will failed,

i use the webdriverIO and set remote host  ,set the browser=chrome.  
when i run 100 cases, 90 failed.   On the remote machine, it will open many of browser and can't close automatic.

Can you resolve?

**Comment by DavertMik** [comment]
In current version we have `restart: false` option which should reuse one session.

**Comment by oneohtrix** [comment]
Hello. 

Is there a reason for the browser to not exit after a failed case? 
I use CodeceptJS in an automated test, that's being run periodically, and after some time,  these browser processes slowly use up RAM , as they don't exit.
