### ISSUE TITLE
API pressKey() can not recognize the key "Backspace"

### ISSUE THREAD

**Issue by junguchina** [Codeception/CodeceptJS#261]
guys,I have q question about the API pressKey().I used pressKey('Backspace'),but it can not recognize the key value，it just input the "Backspace" in to the field.

```
I.pressKey('Backspace');
```

Anyone can provide the solution?

**Comment by DavertMik** [comment]
What helper are you using? I think the implementation may vary on different helpers and some probably don't support it

**Comment by APshenkin** [comment]
Closing due inactivity
