### ISSUE TITLE
Select parent element in Custom Helper

### ISSUE THREAD

**Issue by Pennywise83** [Codeception/CodeceptJS#266]
Hi,
I'm trying to write a Custom Helper that allow me to select a parent item though xpath.
I have this scenario:

HTML:

<div>
<h2>MyTitle</h2>
<span class="button">ClickMe</span>
</div>

I'd like to write some actions like:
I.clickOnText('MyTitle','ClickMe');

I know that I can accomplish this result in many other ways, but I have this need.
I've played around with xpath and my expression is the following:

//_[contains(text(),"MyTitle")]/parent::_///*[.="ClickMe"]]

So I write a function called '_customGuestLocator':

```
_customGuessLocator(container, elem, func) {
    let browser = this.helpers['Protractor'].browser;
    browser.ignoreSyncronization = true;
    browser.findElement(by.xpath('//*[contains(text(),"' + container + '")]/*[.="' + elem + '"]')).then(function(webElement) {
        return func(webElement);
    }, function(err) {
        if (err.name && err.name === 'NoSuchElementError') {
            browser.findElement(by.xpath('//*[contains(text(),"' + container + '")]/parent::*//*[.="' + elem + '"]')).then(function(webElement) {
                present = true;
                func(webElement);
                return;
            }, function(err2) {
                return null;
            });
        }
    }).then(function() {
        return null;
    });
}
```

And the action:

```
clickOnText(container, elem) {
        let browser = this.helpers['Protractor'].browser;
        var f = function (element) {
            browser.actions().mouseMove(element).perform();
            browser.actions().click(0).perform();
        }
        return this._customGuessLocator(container, elem, f);
    }
```

I'm messing around promises. The _customGuessLocator seems to work but it doesn't return the WebElement. 
The clickOnText action seems to not wait the _customGuessLocator and everything goes bad.

What I'm doing wrong?

**Comment by DavertMik** [comment]
I'd propose a simpler solution. You can actually use built in click function, what you need is to wrap it with proper xpath locator. So I'd do it like:

```js
clickOnText(elText, parentText) {
  let xpath = `//*[contains(text(),"${elText}")]/*[.="${parentText}"]'`;
  return this.helpers['Protractor'].click({xpath}); 
}
```

Probably I will include that example into Helpers documentation if it really works :upside_down_face:

**Comment by Pennywise83** [comment]
Thank'so,  that seems a nice and clean solution!
I'll try it tomorrow and I let you know!

**Comment by Pennywise83** [comment]
Unfortunately the xpath expression seems to be not valid:
```
     The given selector //*[contains(text(),"Parent Text")]//*[.="Element Text"]' is either invalid or does not result in a WebElement. The following error occurred:
InvalidSelectorError: Unable to locate an element with the xpath expression //*[contains(text(),"Parent Text")]//*[.="Element Text"]' because of the following error:
SyntaxError: The expression is not a legal expression.
```

**Comment by DavertMik** [comment]
Did you try?

```
//*[contains(text(),'Parent Text')]//*[text()="Element Text"]
```
