### ISSUE TITLE
Failing to locate element outside of angular app using Protractor helper

### ISSUE THREAD

**Issue by Nighthawk14** [Codeception/CodeceptJS#278]
Hi, 

I'm writing some acceptance tests for an Angular application, sometimes I need my tests to go on another application (not an Angular one), and do some operations. The issue is after calling `I.amOutsideAngularApp()` the browser instance is replaced by the Webdriver and so we are not able to locate or wait for elements (error: `this.browser.element is undefined`):
```
amOutsideAngularApp() {
     if (this.browser.driver && this.insideAngular) {
       this.browser = this.browser.driver;
       this.insideAngular = false;
     }
  }
```

Why not just ignore synchronisation when switching? So we can continue using protractor to locate elements and do some operations (waiting etc..)?

```
amOutsideAngularApp() {
     if (this.browser && this.insideAngular) {
       this.browser.ignoreSynchronization = true;
       this.insideAngular = false;
     }
  }
```

Thanks!

**Comment by DavertMik** [comment]
Thanks. That's a good suggestion. Actually I didn't know about it :)
