### ISSUE TITLE
Failing before each hook does exit with code 0

### ISSUE THREAD

**Issue by philipstanislaus** [Codeception/CodeceptJS#279]
While failing tests exit with an exit code > 0, a failing before each hook does exit with code 0 when it fails. Here is an example:

<img width="955" alt="bildschirmfoto 2016-11-03 um 17 46 41" src="https://cloud.githubusercontent.com/assets/6912756/19977198/1c1981a8-a1f3-11e6-9fc0-d751949f65f4.png">

Consequently, CI tests can fail without the CI tool noticing it.

**Comment by DavertMik** [comment]
Thanks! Good report

**Comment by DavertMik** [comment]
```
Tests are running!
CodeceptJS v0.4.8
Using test root "/home/davert/projects/codeceptjs/examples"

GitHub --
 ✖ "before each" hook: Before for "search" in 3135ms

-- FAILURES:

  1) GitHub "before each" hook: Before for "search":
     unknown error: unhandled inspector error: {"code":-32603,"message":"Cannot navigate to invalid URL"}
  
  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 0 passed, 1 failed   // 3s
➜  codeceptjs git:(master) ✗ echo $?                                      
1
```

this is in `master` branch and will be in 0.4.9

**Comment by philipstanislaus** [comment]
Great, many thanks! :+1:
