### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by Nazanin1369** [Codeception/CodeceptJS#280]
I found Codecept documentation to be scattered and hard to find what I am looking for
I think we need to enhance and integrate documentation at least on github.

**Comment by ChaseVoid** [comment]
Could you expand on what you mean by scattered? Are you looking for a search feature on the docs site?

**Comment by DavertMik** [comment]
Sure, any ideas on updating documentation are highly appreciated. If you have specific ideas how a chapters can be improved: tell what's missing. I will try to do my best. You can also send pull request with updates... Anyway, I'm absolutely open to proposals and improvements.

**Comment by kerstvo** [comment]
More examples from real life.

**Comment by magimenon** [comment]
I don't see any examples on how to use executeScript() and executeAsyncScript

**Comment by DavertMik** [comment]
@kerstvo 

> More examples from real life.

You know that's the problem. If you have something from real life it would be so real that it will have NDA and so much technical details (and bad practices in implementation) that it can't be shared. Unfortunately I don't have good examples right now, but it would be great if someone would like to share them.

---

Anyway, I'm still open to suggestions on documentation improvements. If you have your experience to share, please do, send a pull request!

**Comment by DavertMik** [comment]
@magimenon done + fixed lots of cases in https://github.com/Codeception/CodeceptJS/pull/287
will be available in next release

**Comment by DavertMik** [comment]
Please make more specific issues and I will try to improve documentation for that cases.
