### ISSUE TITLE
Switch to Overlay Popup window

### ISSUE THREAD

**Issue by magimenon** [Codeception/CodeceptJS#290]
#### What are you trying to achieve?
From my landing page, I click on a button to open a overlay popup.  I'm not able to detect the elements on the popup as i'm not able to switch my control to the new window. The control is still on the main landing page window.
#### What do you get instead?

I need to switchTo a new window/overlay

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version: 
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Right now we don't have built in functionality for that. But depending on helper you use you can get a solution in internet for that and create a method for that. If you are using webdriverio:

* google how can your problem be solved with wdio
* create your [own helper](http://codecept.io/helpers/#webdriverio-example), implement a step `switchToOverlayPopup`
* enable that helper in `codecept.json` and use it in tests: `I.switchToOverlayPopup()`

If something is not there yet it's pretty easy to extend things

**Comment by magimenon** [comment]
I'm not using webdriverio. I'm using nightmarejs. I don't see much api for this switching pop/frame on the nightmare.

**Comment by DavertMik** [comment]
Probably there is not :( Please refer to their documentation or ask this question in their issues.
