### ISSUE TITLE
Run test with Protractor running get "Required modules are not installed."

### ISSUE THREAD

**Issue by tuanpham86** [Codeception/CodeceptJS#291]
#### What are you trying to achieve?
I actually just trying to get it a test run with protractor following instruction here: http://codecept.io/angular/
What I did is pretty basic:
**npm install -g codeceptjs
codeceptjs init
codeceptjs gt**
 
#### What do you get instead?
Now **codeceptjs run --steps** and below is what i've get:

> Could not load helper Protractor from module './helper/Protractor':
> Required modules are not installed.
> 
> RUN: [sudo] npm install -g protractor@^4.0.0

I do have Protractor installed globally specifically the version 4.0.0 as suggested: 

> \AppData\Roaming\npm\node_modules\protractor

Still I am stuck at this.
Now i could not find a way to make this work (I do not have a coding background) or anywhere mentioning a same issue. I decide that someone here could help? Thanks!

### Details

* CodeceptJS version: latest
* NodeJS Version: v4.4.4
* Operating System: Windows 7
* Protractor ||
* Configuration file:
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Protractor": {
	  "url": "http://todomvc.com/examples/angularjs/",
      "driver": "hosted",
      "browser": "firefox",
      "rootElement": "body"
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "codeCept"
}

**Comment by DavertMik** [comment]
Looks like globally installed modules can't be found. Probably it is somehow related to your system settings, and how the `requireg` package works. Please try to install everything locally, that should work for you

**Comment by tuanpham86** [comment]
Thanks @DavertMik ,

Below is what I did:
1. make new folder
2. npm install --save-dev codeceptjs
3. codeceptjs init (selecting protractor)
4. npm install --save-dev protractor
5. codeceptjs gt
6. codeceptjs run --steps

I still get 
> Could not load helper Protractor from module './helper/Protractor'

Could I ask for a more details steps or am I doing something wrong?

**Comment by Jeroenhuisjes** [comment]
I have the same problem. WebdriverIO works fine with a global install.

**Comment by DavertMik** [comment]
I can't be sure but probably you have version conflict and not the latest Protractor installed. 
Protractor breaks API even in minor versions so please make sure you have local or global installation with latest version. Also pleas make sure you don't have both. I can't provide any more ideas, but I hope that might help

**Comment by APshenkin** [comment]
Close due inactivity
