### ISSUE TITLE
"Real time" testing

### ISSUE THREAD

**Issue by kerstvo** [Codeception/CodeceptJS#293]
I'm stuck.. Can I with CodeceptJS and webdriverio test web chat: in one browser enter message and in another two check this message appears? Is this possible?
thanks.

**Comment by DavertMik** [comment]
What you ask is multisession testing. It's not available right now in CodeceptJS. But I think it is possible (somehow) with webdriverio. 

I think that's important feature for CodeceptJS to implement...

**Comment by kerstvo** [comment]
add AnotherI? :)

**Comment by kerstvo** [comment]
I create some helper:
```
openBrowsers(meetingName) {
    let wdio = require('webdriverio');
    let mbrowser = wdio.multiremote({
        b1: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        },
        b2: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        }
    });
    return mbrowser.init().url('http://google.com')
            .then(function () {
                var b1 = mbrowser.select('b1');
                var b2 = mbrowser.select('b2');
                
                b1.url('http://facebook.com');
            });
}
```
but test passed without waiting browsers load urls..
Is this possible?

**Comment by DavertMik** [comment]
@kerstvo I think you missed the return inside `then`:

```js
return b1.url('http://facebook.com');
```
in this case a promise is passed to next iteration

**Comment by LukoyanovE** [comment]
It seems, multisession was implemented :)
