### ISSUE TITLE
Before Suite with browser access

### ISSUE THREAD

**Issue by Nighthawk14** [Codeception/CodeceptJS#294]
#### What are you trying to achieve?

Being able to initialise a feature with multiple scenarios only once. It would be really nice to gives the `BeforeSuite` hook access to the browser. For example in mocha the `before` and the `beforeEach` hooks have both access to the browser. This could probably be part of a wider refactor that includes the possibility of asynchronous `Before` and `BeforeSuite` hooks.

#### What do you get instead?

At the moment `BeforeSuite` doesn't have access to the browser and `Before` is running before each scenario.

### Details

* CodeceptJS version: 0.4.9
* NodeJS Version: 6.9.1

**Comment by APshenkin** [comment]
@Nighthawk14 Now, If you use `restart: false`  option you have an access to the browser in `BeforeSuite` hook.  Will this solve this issue?

**Comment by APshenkin** [comment]
Closing this. We have access in `BeforeSuite` if `restart:false`
