### ISSUE TITLE
cannot convert undefined or null to object

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#297]
#### What are you trying to achieve?
trying to use codecept.conf.js (for the first time)

#### What do you get instead?
Cannot convert undefined or null to object
(verbose / debug doesn't show more info)

```bash
Use JS config file
undefined

Cannot convert undefined or null to object

TypeError:
    at Function.assign (<anonymous>)
    at new Codecept (/usr/local/lib/node_modules/codeceptjs/lib/codecept.js:20:35)
    at Command.module.exports (/usr/local/lib/node_modules/codeceptjs/lib/command/run.js:14:20)
    at Command.listener (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/codeceptjs/bi
```
> Provide test source code if related

```js
console.log('Use JS config file');

console.log(process.profile);

exports.config = {
  "tests": "./*test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": process.profile || 'firefox',
      "restart": true
    }
  },
  "name": "academie-laag"
}

// paste test
Feature('Steps.js');

Scenario('Testing Academy Layer', (I) => {
  I.resizeWindow('maximize');
  I.amOnPage('x');

  I.see("Cursusaanbod");

  //afbeelding boven uitgelicht
  I.seeElementInDOM('.bld-bg-image')

  //uitgelicht
  I.seeElementInDOM('.bld-featured-v2');

  //snel naar
  I.seeElementInDOM('.bld-content-items');

  //academy laag
  I.seeElementInDOM('.bld-academy-items');

  //footer
  I.seeElementInDOM('.bld-footer-square');
  I.seeElementInDOM('.bld-footer');

  I.amOnPage('x');

});
```

### Details

* CodeceptJS version:  
CodeceptJS v0.4.8
* NodeJS Version:
7.1.0
* Operating System:
MacOS

* Protractor || WebDriverIO || Nightmare version (if related)
WebdriverIO 4.4.0

**Comment by DavertMik** [comment]
According to error line you forgot `mocha` inside your config. Probably it should be optional but currently it's not, it should be there. So just add to your config file:

```
exports.config = {
   //... your config 
   mocha: {}
}
```

**Comment by joelgrimberg** [comment]
thanx @DavertMik . this works.
is there some more documentation on the codecept.conf.js?
want to check if there is more to parameterize ;)

trying something like codeceptjs run --profile safari --restart true,
and if so, I can parameterize the next config in 1 single script.

        "WebDriverIO": {
            "host": "hub.crossbrowsertesting.com",
            "port": 80,
            "path": "/wd/hub",
            "url": "www.site.com",
            "browser": "safari",
            "desiredCapabilities": {
              "name" : "Basic Example",
              "build" : "1.0",
              "browser_api_name" : "Safari10",
              "os_api_name" : "Mac10.12",
              "screen_resolution" : "2560x1600",
              "record_video" : "true",
              "record_network" : "true",

              "username" : "x",
              "password" : "y"
            }

**Comment by DavertMik** [comment]
This is the only documentation we have https://github.com/Codeception/CodeceptJS/blob/master/docs/configuration.md

Any help of improvement is highly appreciated.

And yeah, that `mocha: {}` issue should be solved. I will keep this issue for that

**Comment by joelgrimberg** [comment]
my skills are at the moment not jet on the level that I can contribute. As soon as they are, I will contribute!
