### ISSUE TITLE
I.amOnPage stacktrace via geckodriver but test ok via safaridriver

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#298]
#### What are you trying to achieve?
I.amOnPage('/location/morelocation');   (url which does not exust, so I expect a not_found - page)

#### What do you get instead?
test OK: Passed via safari webdriver
stacktrace via geckodriver

> Provide console output if related. Use `--verbose` mode for more details.
     Failed to interpret value as array
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'MacBook-Pro-van-x.local', ip: 'x', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, firefoxOptions={args=[], profile=UEsDBBQACAgIACKHdkkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WyW7cOBC9z1cM+pQB0oS3zASTk8fxAAMEcZCGkSNBkSWJborkcGm5/z5FLe5NTdk5taSuImt571VFD45aB+W7ReFMi2/EsxK6Z6kr0jDVMgcENCsUiMX730umPPzx6be48xQsoI01LiSXGpgKdf9O0Ggj+Yy/htAatyZ1CJbYWvp6u0x/W+b9UoGuQo2OVx8+HLqNATtgAn8EBOABxL/S+XCLsXAF6BZcPA7XNJjXM+W1Mw1Qz520gbqoaZBNcrm+mL4osMITLId+0HfKeJjOZrQWptXKMIF3aValwtam/VGDXmG1UqWm3S0GZYNPl9HGCKZmag+bYIzyBJwzjhvtjdov92n6XlbaaKxaA00BbtW9+nwuHryXaBUMYsGBj1i3EgOl3DFf532V1GtiLGgKzwGcZio1880IKlNbv0c9fVkLhXByg++Mc8B2Ro2Ze4QD5eCCn6zES6ekt4ptQdxfXqy+GkROau3NtDF+Eg/6h9TYX395QSReZB6/f0GPBStMDH8Xiun14hRzfUKUKUWfPBYjxSn70p/G9mwllhttSVvLAEr6gAf8H6U7h4QEg7UMZGDTiDpMLmEhWwDFsDFIgDzUfMJttKRG1lg8m7ageGJQdKmli6OUU7d1hxoSLTYYiMbSlttHNHmzjkSbqHSfDQ94dDJsESkK8In44CQP1DhZSU2tUZJv81DV0CLtyJBPppsHgfYnk/RxFYtGdlT51n287cD4Ot2cPCab8Qs7h8akpqDlGfXa8RDTbDv8nhLxhUdEmYr0j2i1vLq8+evm4/WfNx8P7U1Z4rmwZNZ6gmg1LS22VEDJogrT8jO2iXs74G06u1P8ZNE5wh+5gsoW3Jb0StrZX83ZZo8eK3j/+OWWXBO2a+ppek9sw/qJkhXh49aNnMrj7jRuB0/d0Mte0sM6HZ/Pc6/iLAbzuVeOFUfQJJG6vDinuf2pVLOArxQ2oMPMQNkbpQ8Iydl4CmX4uhPBV3XKA3O8HnAzN6Yb0rOBiNjYbNcQ5a/C4iGLhptyNDpAmEFHJ8W0ZJ+o3LG8XU/vVv04WI58RdyFONOjwfaMdg1L1Pz2tDeafbc47EYzalzsCpMtdcLidBB7ZDP9LO2WrP/0Xb8HnV3/hqFIOzkUWEZd0TRgZlBVA85jXgNff+4V7p+X1r5xXhImhEwRs5lRM7mV/+o2jmis0sdhTcwOlz3ydRnfoZgivwupEvq0rOqgzozTPdfxxl/RQjoSgTS4eHZAXKRl1cFRjXa7UtptEdi4oc4sSzuhUKWPtt8xdmvMT1BLBwjMVnk3xgMAABcNAABQSwECFAAUAAgICAAih3ZJzFZ5N8YDAAAXDQAABwAAAAAAAAAAAAAAAAAAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAAD7AwAAAAA=}, loggingPrefs={driver=ALL, browser=ALL}, appBuildId=20161019084923, handlesAlerts=true, version=49.0.2, platform=MAC, requestOrigins={name=webdriverio, version=4.4.0, url=http://webdriver.io}, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=47008, browserVersion=49.0.2, platformVersion=16.1.0, locationContextEnabled=true, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, takesElementScreenshot=true, platformName=darwin, device=desktop}]
Session ID: 50799ce3-0156-7049-98d6-b014e075b0e6
*** Element info: {Using=css selector, value=.bld-bg-image}

```bash
# paste output here
```
> Provide test source code if related
/// <reference path="./steps.d.ts" />
Feature('Steps.js');

Scenario('Testing Academy Layer', (I) => {
  I.resizeWindow('maximize');
  I.amOnPage('url');

  I.see("Cursusaanbod");

  //afbeelding boven uitgelicht
  I.seeElementInDOM('.bld-bg-image')

  //uitgelicht
  I.seeElementInDOM('.bld-featured-v2');

  //snel naar
  I.seeElementInDOM('.bld-content-items');

  //academy laag
  I.seeElementInDOM('.bld-academy-items');

  //footer
  I.seeElementInDOM('.bld-footer-square');
  I.seeElementInDOM('.bld-footer');
  I.saveScreenshot('debug.png');

I.amOnPage('/location/morelocation'); 
  I.saveScreenshot('debug2.png');
});

### Details

    CodeceptJS version:
    CodeceptJS v0.4.8

    NodeJS Version:
    7.1.0

    Operating System:
    MacOS

    Protractor || WebDriverIO || Nightmare version (if related)
    WebdriverIO 4.4.0

### Configuration file
console.log('Use JS config file');

console.log(process.profile);

exports.config = {
  "tests": "./*test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "www.url.com",
      "browser": process.profile || 'firefox',
      "restart": true
      //"restart": proces.restart || true
    }
  },
  "name": "academie-laag",
  "mocha": {}
}

### starting test
codeceptjs run --profile firefox

**Comment by APshenkin** [comment]
@joelgrimberg is this issue actual?

**Comment by APshenkin** [comment]
Close due inactivity
