### ISSUE TITLE
windowSize has no effect [Nightmare]

### ISSUE THREAD

**Issue by bessey** [Codeception/CodeceptJS#301]
#### What are you trying to achieve?

I want the window to enlarge the window on boot

#### What do you get instead?

The window always shows at its default size

### Details

* CodeceptJS version: 0.4.9
* NodeJS Version: 7.1.0
* Operating System: OS X Sierra
* Nightmare: 2.8.1
* Configuration file:

```js
...
    "Nightmare": {
      "show": true,
      "waitForAction": 5000,
      "windowSize": "1000x1000",
      "typeInterval": 20,      
      "webPreferences": {
        "partition": "codecept-acceptance"
      }
    }
...
```

**Comment by maximkott** [comment]
@bessey You can use this helper as a workaround:

```js
'use strict';

class NightmareHelper extends codecept_helper {
  resizeWindow (width, height) {
    this.helpers['Nightmare'].browser.viewport(width, height)
  }
}

module.exports = NightmareHelper;
```

Then simply run in your test:

```js
I.resizeWindow(600, 900)
```

**Comment by DavertMik** [comment]
I don't see any difference from Nightmare helper implementation.
Also I just added a test for it so I think this can be closed.
