### ISSUE TITLE
I.executeScript / I.executeAsyncScript freeze test [Nightmare]

### ISSUE THREAD

**Issue by bessey** [Codeception/CodeceptJS#302]
#### What are you trying to achieve?

I want to reset localstorage between test runs, so need to call executeScript between test runs

#### What do you get instead?

A blank white page, with broken devtools:

![image](https://cloud.githubusercontent.com/assets/708200/20579048/3e507f92-b17f-11e6-889e-f0945ff9d08b.png)

Removing the offending lines:

```js
Before((I) => {
  I.executeScript(function () {
    return 1
  })
})
```

restores test to former glory

### Details

* CodeceptJS version: 0.4.9
* NodeJS Version: 7.1.0
* Operating System: OS X Sierra
* Nightmare: 2.8.1
* Configuration file:

```js
...
    "Nightmare": {
      "show": true,
      "waitForAction": 5000,
      "windowSize": "1000x1000",
      "typeInterval": 20,      
      "webPreferences": {
        "partition": "codecept-acceptance"
      }
    }
...
```

**Comment by DavertMik** [comment]
I think it was fixed in one of latest versions. `executeScript` works and tested for Nightmare. 
At least this code works in our internal tests 

```js
I.executeScript(function() { document.getElementById('link').innerHTML = 'Appended'; });
I.see('Appended', 'a')
```
