### ISSUE TITLE
How to handle Authentication Required popup

### ISSUE THREAD

**Issue by congpc** [Codeception/CodeceptJS#305]
I have a problem with Authentication popup. How to input username and password into the Authentication popup with codeceptjs sdk automatically? Please help me to resolve this issue.

Thank you so much.

**Comment by n0v1** [comment]
If you mean a Basic Auth dialog, you can provide user and password in the url in your codecept.json file like this:
```
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "https://myusername:mypassword@example.com",
      "browser": "chrome",
  ...
```

**Comment by APshenkin** [comment]
Close due inactivity
