### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by rogoit** [Codeception/CodeceptJS#307]
I want to test a slider for a price selection on a ecommerce project. Sinple i want to push left mouse button down and want to move 30px to left. But i do not know how to do this in javascript. I think there could be a second way with executejs.  This information is for the background.

So i try to do it with drag and drop. But when i run the test i get

` [Facebook\WebDriver\Exception\UnknownCommandException] POST /session/4f9f5c73-1d3a-5740-8ce4-ef6fc5cc445b/moveto did not match a known command
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'`

It is codeception 2.2.6 and selenium server 3.0.1

Any ideas how to fix the drag and drop and how i can test a price slider?

**Comment by DavertMik** [comment]
Sorry, this issue is related to Codeception project, not CodeceptJS

**Comment by rogoit** [comment]
Maybe we can move the ticket?

**Comment by DavertMik** [comment]
No, please create a new one in Codeception repository following the initial template in it. Thanks
