### ISSUE TITLE
Quickstart link "Selenium Web Server is running" is broken

### ISSUE THREAD

**Issue by c0bra** [Codeception/CodeceptJS#309]
On this page: http://codecept.io/quickstart/

The link to "Selenium Web Server is running" is broken. In the markdown it's supposed to go to `./helpers/WebDriverIO.md/#selenium-installation` but that file doesn't exist.

Further more, the helpers section for WebDriverIO (http://codecept.io/helpers/#webdriverio-example) has no info on starting Selenium.

If I had no former knowledge of Selenium I'd basically be stuck unable to do the quickstart. As it is I'll fumble around and probably get it running, but this lack of working docs will likely frustrate a lot of new users.

**Comment by DavertMik** [comment]
> The link to "Selenium Web Server is running" is broken. In the markdown it's supposed to go to ./helpers/WebDriverIO.md/#selenium-installation but that file doesn't exist.

Almost. In the very beginning of a file there are instructions on starting Selenium:

> Download Selenium Server
> Launch the daemon: java -jar selenium-server-standalone-2.xx.xxx.jar

http://codecept.io/helpers/WebDriverIO/#selenium-installation

There are more ways on starting Selenium but I'm not sure which one to prefer most...
But yeah, link in Quickstart should be fixed
