### ISSUE TITLE
Consider adding a warning when not using Feature first in the test

### ISSUE THREAD

**Issue by wadamek65** [Codeception/CodeceptJS#3092]
#### Description
When you try to run hook methods (for example `BeforeSuite`) before using the `Feature` function, it will silently get skipped over without any output. It would be nice to see at least a warning or an error thrown if possible. This will make debugging and catching errors much easier. If you could provide me a little bit of guidance on where this should be adjusted I would be willing to contribute and submit a PR for this.

```js
BeforeSuite(() => console.log('This will not be logged'));

Feature('Test');
```

### Details

* CodeceptJS version: `3.1.2`

**Comment by kobenguyent** [comment]
Seemed not an issue with latest version

```
Helpers: Playwright, Expect, REST, PixelmatchHelper
Plugins: screenshotOnFail, retryTo, stepByStepReport

    --- STARTED "before all" hook: BeforeSuite in "{root}" ---
    [1]  Starting recording promises
this is beforeSuite
    --- ENDED "before all" hook: BeforeSuite in "{root}" ---
login --
    Timeouts: 
 › [Session] Starting singleton browser session
  Incorrect username or password.

```
