### ISSUE TITLE
When using playwright alongside with chromium, browser opens but refuses to initiate any test steps, resulting in timeout

### ISSUE THREAD

**Issue by erincyuksel** [Codeception/CodeceptJS#3093]
* CodeceptJS version: 3.1.3
* NodeJS Version: 14.18.1
* Operating System: Windows
* Configuration file:  

```
exports.config = {
  output: "./output",
  helpers: {
    Playwright: {
      url: "https://test.ca",
      show: true,
      browser: "chromium",
    },
  },
  include: {
    I: "./steps_file.js",
    googleLandingPage: "./pages/google_landingPage",
  },
  mocha: {},
  bootstrap: null,
  teardown: null,
  hooks: [],
  gherkin: {
    features: "./features/*.feature",
    steps: ["./step_definitions/steps.js"],
  },
  plugins: {
    screenshotOnFail: {
      enabled: false,
    },
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true,
    },
    tryTo: {
      enabled: true,
    },
  },
  tests: "./*_test.js",
  name: "Codecept",
};
```
Hello, in my firm we are approaching codeceptjs alongside with playwright as helper. When we are trying to execute a single scenario, if the browser is set to chromium the browser opens and just hangs without taking any actions. After 30 seconds it gives a timeout error and closes. When used with firefox as a browser, it successfully executes all the tests. I was wondering what could be the reason behind this? It is a specific problem with chromium itself. When chromium opens it also warns me about not having a google api key, but as far as I know it has got nothing to do with my problem.

Will try to give more information when i return to work environment.

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
