### ISSUE TITLE
Documentation of the various commands in codecept

### ISSUE THREAD

**Issue by sulthan-ahmed** [Codeception/CodeceptJS#312]
#### What are you trying to achieve?

Documentation of all the commands in codecept.io website a bit like https://lodash.com/docs

**Comment by DavertMik** [comment]
http://codecept.io/commands/

If you seek for `I.click`, `I.see` commands they are documented in Helpers section on a site. Depending on selected Helper you receive a different set of commands

**Comment by sulthan-ahmed** [comment]
👍
