### ISSUE TITLE
Need I.comment() or I.remark() or similar

### ISSUE THREAD

**Issue by nmitha** [Codeception/CodeceptJS#313]
console.log isn't sufficient to print info during tests, because it will run all console.log calls right away instead of at the intuitive time.

You should be able to do this:

```
I.login();
let copyright = yield I.grabTextFrom('div.copyright');
I.comment(`copyright message on page is ${copyright}`);
assert(copyright.indexOf('2016') >= 0, 'Copyright message has correct year');
// Other I. commands
```

Right now we're resorting to ugliness like this:

```
I.dontSee(`copyright message found on page is: ${copyright}`);
```

**Comment by DavertMik** [comment]
Thanks, that's a good idea. It should be done!
