### ISSUE TITLE
WaitForElement is broken in nightmare

### ISSUE THREAD

**Issue by maximkott** [Codeception/CodeceptJS#317]
#### What are you trying to achieve?

I am trying to use the **waitForElement** method.

#### What do you get instead?

Execution hangs forever, even though the element I am waiting for is already visible. 

I was simply working trough the tutorial and am not using any special configuration nor complex test suites.

**Comment by DavertMik** [comment]
Thanks for the report. 
Nightmare is fast but may be not as stable as webdriverio. If you just staring you can use more traditional tools like WebDriverIO helper and selenium webdriver server

**Comment by DavertMik** [comment]
Fixed in 0.4.13
