### ISSUE TITLE
Protractor BrowserExpectations not found

### ISSUE THREAD

**Issue by ctaepper** [Codeception/CodeceptJS#320]
#### What are you trying to achieve?
Using the ProtractorHelper in (current) protractor@4.0.12

#### What do you get instead?
Error

### Details
Protractor exports ProtractorBrowserExpectations directly in its root module: https://github.com/angular/protractor/blob/master/lib/index.ts#L14
codecepts is trying to get it from protractor browser property: https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Protractor.js#L97

* CodeceptJS version: 0.4.9
* NodeJS Version: 6.9.1
* Operating System: OSX
* Protractor: 4.0.12
* Configuration file:

**Comment by DavertMik** [comment]
Thanks for the report. Fix is coming!
