### ISSUE TITLE
CodeceptJS / Playwright / Getting intemittent 'go to' undefined issue on I.amOnPage(...)

### ISSUE THREAD

**Issue by rcamongol1** [Codeception/CodeceptJS#3236]
#### What are you trying to achieve?
We're trying to understand what's causing the intermittent issue where we are getting 'undefined' 

#### What do you get instead?
We’ve been having a intermittent issue where we are getting ‘go to undefined’ when calling ‘I.amOnPage(’/’)’ Does anyone has an idea how to resolve this? Appreciate the help in advance.

NOTE:

1. We are running in parallel using 5 bamboo agents but 1 browser instance each.
2. That ‘loginToDashboard’ custom function and used by all of our scripts.

![image](https://user-images.githubusercontent.com/98498325/152890362-19cc86f6-df53-4a94-824c-1487453ab153.png)

```steps_file.js
loginToDashboard: function (username, password) {
      this.amOnPage('/');
      this.login(username, password);
    },
```

```sample.test.ts
Feature('Sample')

Before(async ({ I }) => {
    I.loginToDashboard(Login.Email, Login.Password);
});
```

### Details

* CodeceptJS version: 3.2
* NodeJS Version: v14.17.3
* Operating System: Windows 10
* Playwright
* Configuration file:
![image](https://user-images.githubusercontent.com/98498325/152890774-2ab63eb0-c854-48b5-970b-02b2f2d28f2e.png)

**Comment by jancorvus** [comment]
It can implicitly mean that the instance of browser fails to start. `goto` just happens to be the first command on the browser, so it can seem not obvious what is happening. I have had the same issue, a CI agent in my case happened not to have enough memory and killed the browser. You should investigate/monitor resources consumption of the host where you run the test at the times of the failure.

**Comment by rcamongol1** [comment]
> It can implicitly mean that the instance of browser fails to start. `goto` just happens to be the first command on the browser, so it can seem not obvious what is happening. I have had the same issue, a CI agent in my case happened not to have enough memory and killed the browser. You should investigate/monitor resources consumption of the host where you run the test at the times of the failure.

Thank you Jan, We also noticed resources consumption when running parallel test (Multiple browser instance) in the server, it reached almost 90% CPU usage. We decided to move back into (1) single browser instance so we don't consume that much resources but still the same, intermittently getting this issue. 

Is there anything else we can do about it or any known workaround? Appreciate the help.

**Comment by jancorvus** [comment]
Another case when my browser was failing to start with that error was when I passed bad params to the browser. I was preparing a plugin to Chrome that sometimes got malformed and went to Chrome corrupted, so Chrome could not accept it and failed to start. Do you do any preparations of that kind?

**Comment by rcamongol1** [comment]
> Another case when my browser was failing to start with that error was when I passed bad params to the browser. I was preparing a plugin to Chrome that sometimes got malformed and went to Chrome corrupted, so Chrome could not accept it and failed to start. Do you do any preparations of that kind?

Hmm, No, I don't think we have that special setup we pass before launching the browser aside from this argument :( 
![image](https://user-images.githubusercontent.com/98498325/153508367-b76b4d14-79ca-4244-b1a7-27c537e7052f.png)

**Comment by rcamongol1** [comment]
Hi someone here can help me out please, why we're getting this intermittent 'go to' issue when calling I.amOnPage(...) function...

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
