### ISSUE TITLE
Codeceptjs failed the vulnerability check

### ISSUE THREAD

**Issue by alexunique0519** [Codeception/CodeceptJS#3237]
#### What are you trying to achieve?

Trying to use codeceptjs as the automation tool. The automation tests works fine, however, when I push my code to GitHub I got a vulnerability alert. 

#### What do you get instead?

vulnerability alert, regarding 2 dependencies, _ansi-regex_ and _engine.io_

> Provide console output if related. Use `--verbose` mode for more details.
N/A
```bash
# paste output here
```
N/A
> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.3.0
* NodeJS Version: 14.18.0
* Operating System: Mac
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

Can we update those lib versions?

**Comment by DavertMik** [comment]
Yes, please send pull request with updates!
