### ISSUE TITLE
Click is not recognized sporadically in the 3.3.0 version

### ISSUE THREAD

**Issue by verebd** [Codeception/CodeceptJS#3244]
#### What are you trying to achieve?
The test tries to click the sign in button on a login page.

#### What do you get instead?
When I'm watching closely the scenario run, it is obvious that the click happened as the usual authentication URL appears after login, however, it seems from the logs that the click was not recognized and the test retries it (but it doesn't succeed as obviously the sign in button is not visible anymore).

#### Important notes
- the issue is sporadic but happens quite often
- the issue is only reproducible with the Codecept 3.3.0 version (I tried the 3.2.3 version as well and the issue did not occurr)
- so far I experienced this issue only with this one element 

> Provide console output if related. Use `--verbose` mode for more details.
```bash
    I wait for enabled "#submit", 30
    I click "#submit"
    [1] Retrying... Attempt #2
    [1] Retrying... Attempt #3
    [1] Retrying... Attempt #4
    [1] Retrying... Attempt #5
    [1] Retrying... Attempt #6
    [1] Error | Error: Clickable element "#submit" was not found by text|CSS|XPath
    [1] Error | Error: Clickable element "#submit" was not found by text|CSS|XPath
    [1] Error | Error: Clickable element "#submit" was not found by text|CSS|XPath
    [1] Error | Error: Clickable element "#submit" was not found by text|CSS|XPath
    [1] Error | Error: Clickable element "#submit" was not found by text|CSS|XPath
    [1] Error | Error: Clickable element "#submit" was not found by text|CSS|XPath

```

### Details

* CodeceptJS version: 3.3.0
* NodeJS Version: 14.17.5
* Operating System: Windows 10
* playwright version (if related): 1.18.1

**Comment by kbiszta-futurefinance** [comment]
I can add from my side that to me it happens only in headless mode. Test execution fails on clicking the button even if screenshot captured on failure proves it was clicked properly.

Some logs
```
    [1] Error | TimeoutError: elementHandle.click: Timeout 1000ms exceeded.
=========================== logs ===========================
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  click action done
  waiting for scheduled navigations to finish
```

and details:
- CodeceptJS version: 3.3.0
- NodeJS Version: 16.13.2
- Operating System: MacOS 11.6.2
- Playwright version (if related): 1.18.1

**Comment by verebd** [comment]
I experienced it with both headful and headless browser mode (browser is Chromium).

**Comment by klepik1990** [comment]
I've met the same problem, but on webkit in GitLab CI.

CodeceptJS version: 3.3.0
NodeJS Version: 16.13.0
Operating System: Windows 11
Playwright version (if related): 1.18.* - 1.19.0

**Comment by DavertMik** [comment]
This could be realted to Playwright 1.18 or because of timeout was lowered to 5s

Please try to increase `timeout` value in Playwright config:

```js
helpers: {
  Playwright: {
    /// ... 
    timeout: 20000,
  }
}
```

**Comment by verebd** [comment]
Thank you @DavertMik , increasing the timeout worked.

**Comment by DavertMik** [comment]
Updated defaults to 5s
