### ISSUE TITLE
codeceptjs def does not generate types for plugin global function

### ISSUE THREAD

**Issue by rockwalrus** [Codeception/CodeceptJS#3250]
#### What are you trying to achieve?
I'd like

```sh
npx codeceptjs def
```

when a plugin that registers a global function such as `tryTo` to generate a `steps.d.ts` with an appropriate definition for `tryTo`.

#### What do you get instead?

The generated `steps.d.ts` does not contain or reference a definition for the registered function.

### Details

* CodeceptJS version: 3.2.3
* NodeJS Version: 16.13.0
* Operating System: Windows 10
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
{
  plugins: {
    retryTo: {
     enabled: true
    }
  }
}
```

**Comment by mirao** [comment]
Fixed in https://github.com/codeceptjs/CodeceptJS/pull/3461
Currently I'm running CodeceptJS 3.3.7 and the fix is there.
