### ISSUE TITLE
Can't find element in Modal react native

### ISSUE THREAD

**Issue by quando-agilityio** [Codeception/CodeceptJS#3251]
#### What are you trying to achieve?
Can't find child element in Modal component react-native 

#### Important notes
 - I used Appium helper with react-native and tried to get elements in the Modal component but it can't find them. 
 - I was set **accessible={false}** for the parent element but it still not find

### Details

* CodeceptJS version:  ^3.2.3
* NodeJS Version: 12.14.1
* Operating System: Mac OS Catalina 10.15.7
* Configuration file: Appium 1.22.0

Please check my image I tried get button in Modal but can't
<img width="1237" alt="nestGift" src="https://user-images.githubusercontent.com/44456728/154062210-455abda8-3601-4193-9c3b-1d0b4f42303d.png">

**Comment by DavertMik** [comment]
1. not enough information
2. not sure we can help here. If you have these issues you may try to use low-level Appium API or try Detox as an alternative
