### ISSUE TITLE
I.fillField returns an error: elementHandle.type: Timeout 1000ms exceeded. elementHandle.type(<string here>)

### ISSUE THREAD

**Issue by ecastor** [Codeception/CodeceptJS#3253]
#### What are you trying to achieve?
I am trying to login, and will type the username and password `I.fillField()`, and should be able to successfully login. My string contains 42 characters

#### What do you get instead?
While typing the username which contains 42 characters, the system returns an error: `elementHandle.type: Timeout 1000ms exceeded`

#### Error message returned:

```bash
elementHandle.type: Timeout 1000ms exceeded.
=========================== logs ===========================
elementHandle.type("<my username here which consists 42 characters>")
============================================================
```

#### Sample code:

```js
Feature("Login");

Scenario("Login code here", ({ I }) => {
  I.amOnPage("/");
  I.fillField(`//input[@id='username']`, "test-email-sandbox1@yopmail.com.inbox.mail");
  I.fillField(`//input[@id='password']`, secret("passwordhere"));
  I.click(`Log In`);
});
```

### Details

* CodeceptJS version: 3.3.0
* NodeJS Version: 14.17.5
* Operating System: Windows 10
* Playwright: 1.19.0

**Comment by mirao** [comment]
See https://codecept.io/changelog/#_3-3-0

> [Playwright] Possible breaking change. By default timeout is set to 1000ms. Previous default was set by Playwright internally to 30s. This was causing contradiction to CodeceptJS retries, so triggered up to 3 retries for 30s of time. This timeout option was lowered so retryFailedStep plugin would not cause long delays.

**Solution:** Set timeout in your config (Playwright helper) to a bigger value, e.g. `timeout: 10000`

**Comment by ngraf** [comment]
I encountered the same problem today.
`timeout: 10000` was working for me as a fix.

Instead of accepting this as a final solution, I would rather like to kick-off a discussion to improve the user experience here for the CodeceptJS user.
I think it is a little bit frustrating for most CodeceptJS users that use default configurations to encounter this problem for a very realistic happy path instruction.

Maybe `2000ms` as default value may be a good compromise? 
My test had a 39 char string to fill in and it passed with `2000ms`

**Comment by ngraf** [comment]
Side note:
The likeliness the error occured started when I decided to run my Playwright test in Browserstack instead of localhost. Looks like speed to fill in characters into input field is slower with remote connection.

**Comment by ecastor** [comment]
Thanks a lot @mirao, setting timeout under the Playwright helper fixed my issue.

I also agree to @ngraf, this can be improved by increasing the timeout as there are tests wherein we are required to type strings that has a lot of characters. Or maybe have an additional argument under the `fillField `function that we can explicitly add timeout depending on the string we will be inputting.

**Comment by jpmschuler** [comment]
I think this is even more severe, as I had this even triggered with a simple `I.click()`
```
elementHandle.click: Timeout 1000ms exceeded.
=========================== logs ===========================
attempting click action
  waiting for element to be visible, enabled and stable
    element is not stable - waiting...
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  click action done
  waiting for scheduled navigations to finish
============================================================
```
And it was only a click on a normal link, thus I think in that case if the response wasn't <1sec it broke, too.

**Comment by jancorvus** [comment]
`timeout: 10000` helped as a workaround for me. But when it comes to very long strings like 'Lorem ipsum ...', the bug is there.

**Comment by kobenguyent** [comment]
I believe this has been fixed https://codecept.io/changelog/#_3-3-1

**Comment by ktryniszewski-mdsol** [comment]
I think the better question is why is `fillField` using `type` behind the scenes

In essence it should be using playwrights `page.fill(...)` vs `page.type(...)`

I know we have an option to delay typing but maybe the fillField method should check if that is defined, if not just use native fill instead
