### ISSUE TITLE
Appium helper typing (`extends WebDriver`)

### ISSUE THREAD

**Issue by d-andrii** [Codeception/CodeceptJS#3259]
Appium helper extends WebDriver, yet the generated type definition looks like this:
```ts
class Appium {
    // ...
}
```
while it should be
```ts
class Appium extends WebDriver {
    // ...
}
```
In theory, it should be fixed if there would be `@augments WebDriver` or `@extends WebDriver` in Appium JSDoc definition. I wanted to try it locally and open a pull request but I did not manage to install dependencies for the repo on M1 Mac, so I cannot verify the solution, hence I simply open an issue for someone else to try.

**Comment by mirao** [comment]
When I migrated JavaScript tests to TypeScript I hit this issue. I was not able to use autocomplete (IntelliSense) of WebDriver methods in Android App project (Appium) in VSCode. Actually the same issue was in JavaScript tests.
E.g. methods such as `wait()` or `seeElement()` were not autocompleted and also couldn't be compiled by TS, so I needed to prefix them with `// @ts-ignore`

Finally I solved the issue by adding of TS definition `WebDriver.d.ts` into my project:
```ts
/// <reference types='codeceptjs' />

declare namespace CodeceptJS {
  interface Methods extends WebDriver { }
}
```
I must admit it's not ideal solution, it would be better to have updated CodeceptJS's TS definitions
