### ISSUE TITLE
0.4.10 broken

### ISSUE THREAD

**Issue by ctaepper** [Codeception/CodeceptJS#326]
#### What are you trying to achieve?
use 0.4.10 in order to get the #320 fix

#### What do you get instead?
only one line output and it immediatly exits. selenium server is up and running, also the webserver is up and running.
```bash
[18:51:19] I/hosted - Using the selenium server at http://127.0.0.1:4444/wd/hub
```
if i use the previous 0.4.9, i run into that protractor error again as reported in #320 

### Details

* CodeceptJS version: 0.4.10
* NodeJS Version: 6.9.1
* Operating System: osx
* Configuration file:

```js
const env = require('../../env').env

exports.config = {
  "tests": "./frontend/**/*.test.js",
  "timeout": 10000,
  "output": "./reports/codeceptjs",
  "helpers": {
    "Protractor": {
      "url": "http://localhost:" + env.PORT,
      "seleniumAddress": "http://127.0.0.1:4444/wd/hub",
      "driver": "hosted",
      "browser": "chrome",
      "rootElement": "html",
      "desiredCapabilities": {
        "browserName": "chrome",
        "version": "50.0"
      }
    }
  },
  "include": {
    "I": "./test/e2e/steps_file.js",
    "loginPage": "./frontend/features/login/test/login.page.js"
  },
  "bootstrap": false,
  "mocha": {
    "reporterOptions": {
      "reportDir": "reports/e2e"
    }
  },
  "name": "web__backend"
}
```

**Comment by clouless** [comment]
I can confirm. Just did a fresh "QuickStart" with WebdriverIO and when running `codeceptjs run` nothing happens. I switched to `0.4.8` and everything works.

**Comment by konstantinn** [comment]
And another issue in 0.4.10 
https://github.com/Codeception/CodeceptJS/blob/master/lib/output.js#L104

As I see there was a PR that renamed pending to skipped. Above link leads to ReferenceError: pending is not defined when you run codecept run --steps

**Comment by DavertMik** [comment]
Thanks, I have almost fixed that issues and writing regression tests to not make this happen in future.
Release is coming

**Comment by DavertMik** [comment]
0.4.11 is out. Right now I'm going to work more on regression tests and implement all of them to test everything works, especially with new bootstrap/teardown async/sync options we have.

**Comment by ctaepper** [comment]
everything is working now, thank you very much!
