### ISSUE TITLE
Popup always gets accepted after upgrading codeceptjs & puppeteer versions.

### ISSUE THREAD

**Issue by hanna-becker** [Codeception/CodeceptJS#3261]
#### What are you trying to achieve?
I tried upgrading to codeceptjs@3.3.0 and puppeteer@13.3.2 today. Before that, I was using codeceptjs@3.1.3 and puppeteer@10.4.0. With the old versions, the below test sequence is running fine. Now it is failing because it is not handling the popup cancellation correctly any more.

#### What do you get instead?

The test does not cancel the popup, like it used to. It does the following instead:
1. When running in visble mode, I see that the popup always gets accepted.
2. When running in headless mode I see an error message stating that the popup doesn't exist. 

These are my attempts of fixing it that did not work:
1. Removing the line "I.amCancellingPopups();"
2. Removing the line "I.cancelPopup();"
3. Downgrading puppeteer to the previous version (10.4.0)

Finally, I also downgraded codeceptjs to the previous version (3.1.3) and that fixed the issue.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# Will update this section.
```

> Provide test source code if related

```js
Scenario('Decline connecting Spotify account makes user stay on songboard page', async ({I, ProductionsPage, SongboardPage}) => {
    await I.deleteTestuser2sSpotifyAccessData();
    I.login(testuser2);
    ProductionsPage.openAnyProjectFromProductionsView();
    I.amCancellingPopups();
    SongboardPage.triggerSearchWithText('Hello');
    I.seeInPopup(popupText);
    I.cancelPopup();
    I.seeInCurrentUrl('/discover/songboard');
    I.dontSeeInCurrentUrl('accounts.spotify.com/');
});
```

### Details

* CodeceptJS version: 3.3.0
* NodeJS Version: 14.17.6
* Operating System: Ubuntu 20.04
* puppeteer (if related): 13.3.2
* Configuration file:

helpers section in config:
```
Puppeteer: {
  url: 'http://localhost:4200',
  windowSize: "1820x980",
  show: true,
  restart: false,
  waitForNavigation: 'domcontentloaded', // option 'networkidle0' caused timeouts when running in docker container
  chrome: {
    args: ['--window-size=1820,980', '--no-sandbox']
  }
}
```

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
