### ISSUE TITLE
cant find protrctor helper option

### ISSUE THREAD

**Issue by lynnh99** [Codeception/CodeceptJS#3269]
#### What are you trying to achieve?
im trying to use protractor helper
i already installed protractor using cmd
and have protractor version 7.0.0

#### What do you get instead?
when trying to run this command to select protractor
npx codeceptjs init 
i did not see protractor option

```bash
# paste output here
```
![image](https://user-images.githubusercontent.com/101195628/157258426-d526632b-e4ca-4dff-ac57-7c35fde3c725.png)

### Details

* CodeceptJS version:
3.3.0
* NodeJS Version:16.14.0
* Operating System: windos

**Comment by kobenguyent** [comment]
Seemed like we deprecated this helper https://codecept.io/changelog/#_3-1-0
