### ISSUE TITLE
cli reporter not working for failing test when using retry() in scenario level 

### ISSUE THREAD

**Issue by AramSol** [Codeception/CodeceptJS#3283]
#### What are you trying to achieve?
we try to get `cli report` about failing scenario [its only work without retry()]
![image](https://user-images.githubusercontent.com/39582300/162142263-7f045498-1038-41ef-8654-5bf281652fd6.png)

#### What do you get instead?
as soon as i add the retry Option, no cli report will be logged on console for failing scenarios. 
![image](https://user-images.githubusercontent.com/39582300/162142379-d78c9a22-b66b-4e4a-acb2-147143937c49.png)

![image](https://user-images.githubusercontent.com/39582300/162143087-d0cbf96c-036a-44c5-9bc4-185542323012.png)

### Details

* CodeceptJS version:3.3.0
* NodeJS Version:16.14.2
* Operating System:windows 10
* webdriverio

config
```
const settings = {
    window: {
        width: 1920,
        height: 1080
    }
};

exports.config = {
    tests: "./*/**/*.js",
    helpers: {
        WebDriver: {
            url: "http://localhost:8070",
            browser: "chrome",
            windowSize: `${settings.window.width}x${settings.window.height}`,
            waitForTimeout: 20000,
            disableScreenshots: true,
            desiredCapabilities: {
                chromeOptions: {
                    binary: require("chromium").path,
                    args: [
                        "--headless",
                        "--lang=en",
                        "--log-level=3",
                        "--disable-gpu",
                        "--disable-dev-shm-usage",
                        "--no-sandbox",
                        `--window-size=${settings.window.width},${settings.window.height}`
                    ]
                }
            }
        },
        myHelper: {
            require: "./helper.js",
        },
    },
    include: {
        I: "./custom-steps.js"
    },
    multiple: {
        parallel: {
            chunks: 10
        }
    },
    output: "../../../.output-ui-tests"
};
```

**Comment by AramSol** [comment]
hi @kobenguyent , 

The problem regarding the reporting of failed tests in the scenario has been resolved. However, when attempting to execute the UI test with the "--multiple" parameter to run all UI tests, the steps of the failed test are not displayed as previously noted in this reported issue

**Comment by kobenguyent** [comment]
May you try this retry configuration 

https://codecept.io/basics/#retry-configuration

**Comment by AramSol** [comment]
@kobenguyent , we still face the same issue.
we use --multiple  parameter
