### ISSUE TITLE
asserting select dropdown values

### ISSUE THREAD

**Issue by dsypien** [Codeception/CodeceptJS#329]
I want to assert the values of select fields.  Is there an easy way to do this in codeceptjs?  I've been looking through the documentation and I can't find an equivalent of the seeInField function that works for select dropdowns.

I am using webDriverIO.

Thanks,
David

**Comment by divad4686** [comment]
I think you would have to make your own Helper (http://codecept.io/helpers/), get the client you are using with  this.helpers['client'].browser (like here http://codecept.io/helpers/WebDriverIO/#access-from-helpers) and check the client documentation.

For example Webdriver.io http://webdriver.io/api.html have a getValue that could work for select elements.

**Comment by dsypien** [comment]
Thanks @divad4686, created a helper.  It works great 😄

**Comment by DavertMik** [comment]
@dsypien if you think your method is valuable please send pull request and we will include that into next release.

**Comment by dsypien** [comment]
@DavertMik great 👍   I'll create a pull request

**Comment by svassr** [comment]
Any chance it gets part of codeceptjs helpers.

**Comment by gurpreetsainisalesforce** [comment]
Is it part of codeceptjs now? If it is what is the method name?

**Comment by auto-qa-git** [comment]
> @DavertMik great 👍 I'll create a pull request

Any updates on this? How can we call this functionality if it's been included in current releases?

**Comment by eugengaspar** [comment]
Hi guys!
Just wondering if this got implemented in the end. If yes, what's the method name?
10Q
