### ISSUE TITLE
IDE Support would be nice

### ISSUE THREAD

**Issue by lauravachon-okta** [Codeception/CodeceptJS#3295]
#### What are you trying to achieve?
Would be nice to have IDE support for codeceptJS. A JetBrains (WebStorm), VS Code, and Eclipse.

#### What do you get instead?
working with codeceptJS is not easy because of the lack of IDE support.

**Comment by kobenguyent** [comment]
Could you give some context that you're encountering?

**Comment by jayudey-wf** [comment]
I've encountered this too where in my current ide (WebStorm) it can't find the custom method that I am using. The tests run without issue so I know it's set up correctly (i.e. accessible to codeceptjs when running)

Is there some additional config needed on our end to point the ide correctly to all available / accessible methods?

<img width="165" alt="Screen Shot 2022-04-22 at 9 26 34 AM" src="https://user-images.githubusercontent.com/4429043/164734524-7deb788e-fa6e-42e2-9f39-72670de9373d.png">

maybe related to this, https://youtrack.jetbrains.com/issue/WEB-43024

**Comment by kobenguyent** [comment]
Oh that's your custom steps that you implemented separately right?

**Comment by kobenguyent** [comment]
If that's the case, I found the workaround as it described here https://github.com/PeterNgTr/ExpectWrapper

**Comment by jayudey-wf** [comment]
I don't know if that'll work at least in my use case because that method is found on a helper object that I'm including.

I was however able to get auto complete working w/ vs code though, however I would have preferred to be able to use webstorm 🙁 .

Thanks though

**Comment by kobenguyent** [comment]
@jayudey-wf I'm using webstorm too, but don't encounter any issues.

**Comment by jayudey-wf** [comment]
Sorry, I was saying that if I'm using a custom method then it will show up as expected on the `I` object in Webstorm, but if I'm trying to include a helper within my `I` object then those methods don't seem to be accessible

**Comment by kobenguyent** [comment]
https://github.com/codeceptjs/CodeceptJS/issues/2710

perhaps this issue you meant.

**Comment by DavertMik** [comment]
Yes, it would be nice but there is nothing we can do here from our side
But I welcome developers to create IDE extensions for CodeceptJS
