### ISSUE TITLE
How to pause and wait for "Enter"

### ISSUE THREAD

**Issue by christianfroehlichconsulting** [Codeception/CodeceptJS#330]
Hallo

How can I archive to pause my Skript till I press Enter?

I thought I can use I.pause() and expected I just need to hit enter on the Keyboard. But this breaks the script.

Thank you very much

**Comment by divad4686** [comment]
you have to call pause() without the I.

**Comment by christianfroehlichconsulting** [comment]
Thank you! Super! You are my Employee of the Month!!!
