### ISSUE TITLE
I.fillField and I.clearField on Playwright when running multiple that involves Firefox, does not behave the same as Chromium

### ISSUE THREAD

**Issue by renoirb** [Codeception/CodeceptJS#3300]
#### What are you trying to achieve?

We have a bunch of Scenarios. The Scenarios, thus far, weren't too much form intensive. 

Or, never had this kind of issue causing errors. Or the tests weren't as precise in the validation of input, output of the forms until recently.

When writing the tests, and running them only in Chromium, things would go along well, no errors.

We realized after, in the pipelines, *breakages*. Turns out Firefox does not exactly run code the same as Chromium.

Turns out we never run those tests during development trying out with Firefox. Because all pipeline *breakages* turned out to be when run with Firefox.

It looks like when we enter commands like using `I.fillField`that are bigger than the simple username or password, the field either doesn't enter fully, or too much.

The issues only occurs when we use Firefox to run the tests.

#### What do you get instead?

`I.fillField` and `I.clearField` normaly, in Chromium, does as advertized. But not when Firefox.
 
![Screen Shot 2022-04-22 at 12 17 15](https://user-images.githubusercontent.com/296940/165187976-0641388d-daf6-4c55-a005-f6b4b0930b92.png)

<img width="1392" alt="Screen Shot 2022-04-22 at 15 16 53 2" src="https://user-images.githubusercontent.com/296940/165188401-5095df39-3bc5-44b7-9b0f-8debb42155b5.png">

### Details

* Project in TypeScript
* CodeceptJS version: 3.3.0
* NodeJS Version: v14.19.0
* Operating System: macOS 11.6.5
* Playwright version: 1.21.0

**Configuration file:**

```js
require('ts-node/register')
// ^ so we can import .ts files below

const { setHeadlessWhen } = require('@codeceptjs/configure')

setHeadlessWhen(process.env.HEADLESS)
// https://codecept.io/configuration/#profile
// https://codecept.discourse.group/t/cannot-find-module-in-codeceptjs-docker-container/940
const browser =
  process.env.profile !== 'undefined' && process.env.profile !== undefined ? process.env.profile : 'chromium'

// EVEN WITH THIS NEW CONFIGURATION, STILL PROBLEMATIC
const whenChromium =
  browser === 'chromium'
    ? {
        /**
         * Possible values:
         * - "chrome"
         * - "chrome-beta"
         * - "chrome-dev"
         * - "chrome-canary"
         * - "msedge"
         * - "msedge-beta"
         * - "msedge-dev"
         * - "msedge-canary"
         */
        channel: process.env.CHROMIUM_CHANNEL ?? 'chrome',
        args: ['--use-fake-ui-for-media-stream'],
      }
    : false

exports.config = {
  tests: './*.smoke-spec.ts',
  output: './output',
  helpers: {
    Playwright: {
      url: process.env.BASEURL,
      show: true,
      browser,
      pressKeyDelay: 1,
      // https://playwright.dev/docs/test-timeouts
      timeout: 120000,
      waitForAction: 250,
      waitForNavigation: 'networkidle0',
      // ================ WHERE CONFUSION SEEMS TO BE ================
      ...(whenChromium ? { chromium: whenChromium } : {}),
    },
    ChaiWrapper: {
      // https://www.npmjs.com/package/codeceptjs-chai
      require: 'codeceptjs-chai',
    },
    LoginHelper: {
      require: './login-helper.ts',
    },
    ContactsFormHelper: {
      require: './contacts-form-helper.ts',
    },
    BrowserHelper: {
      require: './browser-helper.ts',
    },
    AllureHelper: {
      require: './allure-helper.ts',
    },
  },
  include: {
    I: './steps-file.ts',
    ContactsFormView: './contacts-form-view.ts',
    // ...
  },
  mocha: {},
  multiple: {
    parallel: {
      browsers: [
        {
          browser: 'chromium',
          outputName: 'chrome',
        },
        {
          browser: 'firefox',
          outputName: 'firefox',
        },
      ],
    },
  },
  name: 'smoke-tests',
  plugins: {
    allure: {
      enabled: true,
      outputDir: './smoke-tests/output/reports/allure-results',
    },
    pauseOnFail: {},
    retryFailedStep: {
      // https://codecept.io/plugins/#retryfailedstep
      enabled: true,
      randomize: 2,
      retries: 6,
    },
    tryTo: {
      enabled: true,
    },
    retryTo: {
      // https://codecept.io/plugins/#retryto
      enabled: true,
    },
    screenshotOnFail: {
      enabled: true,
      fullPageScreenshots: true,
    },
  },
}
```

When running "parallel" task, 

```bash
codeceptjs run-multiple parallel --all --steps
```

With console.log added in from `node_modules/codeceptjs/lib/helper/Playwright.js` with the following.

```js
class Playwright extends Helper {
  constructor(config) {
    super(config);
    // ... Playwright constructor
    console.log(RULER, `RBx: ${this.constructor.name}`, config, RULER)
  }
  // Rest of original source
}
```

```
--------------------------------------------
 RBx: Playwright {
  url: 'https://app.stage.example.org',
  show: true,
  browser: 'chromium',
  pressKeyDelay: 1,
  timeout: 120000,
  waitForAction: 250,
  waitForNavigation: 'networkidle0',
  chromium: { channel: 'chrome', args: [ '--use-fake-ui-for-media-stream' ] }
}
--------------------------------------------

--------------------------------------------
 RBx: Playwright {
  url: 'https://app.stage.example.org',
  show: true,
  browser: 'firefox',
  pressKeyDelay: 1,
  timeout: 120000,
  waitForAction: 250,
  waitForNavigation: 'networkidle0',
  chromium: { channel: 'chrome', args: [ '--use-fake-ui-for-media-stream' ] }
}
--------------------------------------------
```

**Comment by renoirb** [comment]
Related codeceptjs/CodeceptJS#499 ?

**Comment by DavertMik** [comment]
Please forward this issue to the Playwright team and create an issue in Playwright repository. We don't add anything browser-specific on our side. 

If you could set up a minimal example using basic Playwright API that would be great for them to reproduce. 

Thanks

**Comment by renoirb** [comment]
Hi @DavertMik I found a solution to this issue.

In fact it is because we have to use `await` and `async` for ALL scenarios steps when using Playwright.

Otherwise it creates the issue I'm talking about.

But also, the `I.clearField` does not work still. So in an `input[type=text]` (i.e. not textarea) I would have do `I.doubleClick` so that I select everything.

So, it *is* related to CodeceptJS. Just that we should probably update the docs to put async/await everywhere.

**Comment by renoirb** [comment]
About `I.clearField` and `I.doubleClick`, I'll open an issue on Playwright, no problem :)

**Comment by renoirb** [comment]
As for `async` and `await`.  The tests and scenarios behaves better when we "return await" rather than not.

```patch
diff --git a/lib/helper/Playwright.js b/lib/helper/Playwright.js
index 5ec97818..fd5f28a9 100644
--- a/lib/helper/Playwright.js
+++ b/lib/helper/Playwright.js
@@ -1402 +1402 @@ class Playwright extends Helper {
-    return this._waitForAction();
+    return await this._waitForAction();
@@ -1409 +1409 @@ class Playwright extends Helper {
-    return this.fillField(field, '');
+    return await this.fillField(field, '');
```

**Comment by DavertMik** [comment]
> Just that we should probably update the docs to put async/await everywhere.

This is not required for the vast majority of scenarios. I'd like to understand cases where the standard approach does not work and more especially, to learn why and fix this. Technically there is a possibility that a promise is not handled. But if you say it happens only for 1 browser it is a very weird edge case.

Overall globally handling of promises works quite well, except for edgecases.

**Comment by renoirb** [comment]
> This is not required for the vast majority of scenarios

True.

When we type very small strings of text in forms, there's no issues.

But we've had numerous build errors, some of them my colleagues would "*fence*" out the problematic browser.

Then I've solved it by a lucky guess by trying to use async/await everywhere.

The docs didn't mention anything about this. Maybe its specific to CodeceptJS’ Playwright  adapter.

**Comment by renoirb** [comment]
For this, I can make an involved example of a form with long strings to show off what I mean. A proper reproduce issue.

**Comment by renoirb** [comment]
Also, hope all is going well for you, that you’re safe w/ your loved ones, Michael
