### ISSUE TITLE
How do I grab text or an element and check if it displays on the page?

### ISSUE THREAD

**Issue by WojciechPodlesny** [Codeception/CodeceptJS#3303]
I have a problem with one test case.Well, I would like to download a text or an element from the site and check if it is displayed on the website?.

**Comment by DavertMik** [comment]
Sorry, not sure I can understand what means "download a text or an element from the site"
Please ask this in our slack channel or on our forum. Thanks

**Comment by WojciechPodlesny** [comment]
Ok, thanks
