### ISSUE TITLE
WebDriverIO.click(locator) does not fail when locator returns multiple elements

### ISSUE THREAD

**Issue by hubidu** [Codeception/CodeceptJS#331]
#### What are you trying to achieve?

I was wondering that a click call in my test passed, but the expected following page did not show up.

#### What do you get instead?

The reason seems to be the following code snippet in WebDriverIO.js. 

```js
   let elem = res.value[0];
   return this[clickMethod](elem.ELEMENT);
```

When the locator returns more than one element it will simply click on the first element returned. Given that WebDriverIO.js is quite restrictive in what to accept as a clickable element (which I like), I would suggest to fail the click() call also in this case.
Or at least perhaps log a warning?

**Comment by DavertMik** [comment]
Maybe log a warning would be enough, but I think clicking the first element is ok, it is most obvious convention. Click the first thing matching the provided locator. Make locator more specific to find another item.
