### ISSUE TITLE
Problem with grabNumberOfVisibleElements function - OK status it's given before test completion

### ISSUE THREAD

**Issue by mdiasfernandes** [Codeception/CodeceptJS#3310]
#### What are you trying to achieve?
I'm trying to check the total number of a determinate element present in an app with the function `grabNumberOfVisibleElements`.
#### What do you get instead?
When the above function it's called, somehow, a status `OK (Passed)` it's given, but the test by itself isn't completed yet. When some scenario fails the overall status indicates success.
> Provide console output if related. Use `--verbose` mode for more details.
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/22181846/168142300-ce77d822-dbec-482c-883f-ad99bb371db3.png">
<img width="927" alt="image" src="https://user-images.githubusercontent.com/22181846/168140809-1c8d8b3a-4e64-45ec-aa9f-5fd9fa31c683.png">
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/22181846/168142137-291f48a2-2bf4-4fc3-afdc-a5fbcd8d9a2e.png">

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.0.7
* NodeJS Version: 14.15.4
* Operating System: macOS Big Sur
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
require('dotenv').config()

const check_real_device = require("./helper/check_real_device_helper");

exports.config = {
  name: 'codecept',
  tests: './spec/*/*_test.js',
  output: './screenshots/output/',
  helpers: {
    ResembleHelper: {
      require: "codeceptjs-resemblehelper",
      screenshotFolder: "./screenshots/",
      baseFolder: "./screenshots/base/",
      diffFolder: "./screenshots/diff/"
    },
    Appium: {
      app: process.env.APP,
      host: process.env.DEVICE_FARM_HOST,
      port: Number(process.env.DEVICE_FARM_PORT),
      platform: process.env.PLATFORM,
      user: String(process.env.DEVICE_FARM_USER),
      key: String(process.env.DEVICE_FARM_KEY),
      desiredCapabilities: {
        deviceName: process.env.DEVICE_NAME,
        platformVersion: process.env.PLATFORM_VERSION,
        realDevice: check_real_device.realDevice(),
        autoAcceptAlerts: true,
      },
    },
    TestingBotHelper: {
      require: "codeceptjs-tbhelper",
      user: String(process.env.DEVICE_FARM_USER),
      key: String(process.env.DEVICE_FARM_KEY),
    },
    WaitSomeTime: {
      require: './helper/wait_some_time_helper.js',
    },
    RedisConnection: {
      require: './helper/redis_connection_helper.js',
    },
  },
  include: {
    I: './steps_file.js',
  },
  bootstrap: null,
  mocha: {},
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  },
}
```

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
