### ISSUE TITLE
I.clearField seems broken

### ISSUE THREAD

**Issue by mparpaillon** [Codeception/CodeceptJS#332]
#### What are you trying to achieve?

Clear a form field (input text)

#### What do you get instead?

Form field is just not cleared (without any error)

### Details

* CodeceptJS version: 0.4.12
* NodeJS Version: v6.9.2
* Operating System: OS X (Sierra)
* WebDriverIO
* Configuration file:

```js
{
  "tests": "./test_temp/*_test.js",
  "timeout": 10000,
  "output": "./test_temp/output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://toto.browserstack.com",
      "restart": false,
      "browser": "chrome",
      "user" : "titi",
      "key" : "tata",
      "windowSize": "maximize",
      "desiredCapabilities": {
        "browserstack.local": true,
        "browserName": "chrome",
        "os": "OS X",
        "resolution": "1280x1024"
      },
      "coloredLogs": true,
      "waitforTimeout": 5000
    }
  },
  "include": {
    "I": "./test_temp/steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "toto"
}
```

**Comment by DavertMik** [comment]
Sorry I couldn't reproduce this error locally. Probably I will need and HTML and JS for a page you are testing. 
Maybe there are some JS hooks or non-native input fields that prevents a field from being cleared.

**Comment by DavertMik** [comment]
On second check you may be right. Implementation of `clearField` is quite different from `fillField` and didn't throw an error when field was not located. I updated that and added `clearField` to other helpers. Now it should locate elements by name, labels, css, xpath, and throw an error if no element matched. Just as you expected it to be )

Thanks for the report.

**Comment by mparpaillon** [comment]
It seems to break on Chrome only (on 0.4.13).
I'm testing via BrowserStack and no problem with IE11, Edge or Firefox... Just chrome.

Probably a bug with WebdriverIO `clearElement` function ?
