### ISSUE TITLE
Playwright - I.haveRequestHeaders doesn't set headers

### ISSUE THREAD

**Issue by kozakvoj** [Codeception/CodeceptJS#3333]
#### What are you trying to achieve?
I'm trying to set headers using I.haveRequestHeaders.

#### What do you get instead?
The headers are not set.

### Details

* CodeceptJS version: 3.3.3
* NodeJS Version:16.15.1
* Operating System: Debian GNU/Linux 9.12 
* Playwright version: 1.22.2

It stopped working after upgrading to a new CodeceptJS version.

**Comment by kobenguyent** [comment]
I'm using latest version of codeceptjs 3.3.4 and playwright 1.23.2 and unfortunately cannot reproduce this issue
<img width="377" alt="Screen Shot 2022-07-16 at 12 50 41 PM" src="https://user-images.githubusercontent.com/7845001/179351946-efe28c8b-8fb6-4179-9daf-67b97eb57c61.png">
<img width="126" alt="Screen Shot 2022-07-16 at 12 50 25 PM" src="https://user-images.githubusercontent.com/7845001/179351947-83b3b4ed-2d2d-486b-883a-537f19458dca.png">
