### ISSUE TITLE
grabNumberOfVisibleElements doesn't seem to work inside of a helper function

### ISSUE THREAD

**Issue by sam-davies010** [Codeception/CodeceptJS#3335]
#### What are you trying to achieve?

Hi, I am using the typescript boilerplate project, and I am trying to write some helpers that let members of the team use simple terms across our application for writing scenarios.  However, I have run into an issue with the grabNumberOfVisibleElements function. I am using it as such
`
const Helper = require("@codeceptjs/helper");

class CommonHelper extends Helper {
  async logOut() { 
const I = actor();
const isAccountSwitcherVisible = await I.grabNumberOfVisibleElements(
      `//*[@class="accountSwitcherTitle"]`
    );
    console.log(isAccountSwitcherVisible);
    if (isAccountSwitcherVisible === 0) {
      I.click(`//*[@class='item' and contains(text(),'Log out')]`);
    }
    if (isAccountSwitcherVisible === 1) {
      I.click(`//*[@class="accountSwitcherTitle"]`);
    }
    const logOutType1 = await I.grabNumberOfVisibleElements(
      `//*[@class="account switcher"]//*[@class='logoutType1')]`
    );
    const logOutType2 = await I.grabNumberOfVisibleElements(
       `//*[@class="account switcher"]//*[@class='logoutType2')]`
    );
    if (logOutType1 === 1) {
      I.click(
         `//*[@class="account switcher"]//*[@class='logoutType1')]`
      );
    }
    if (logOutType2 === 1) {
      I.click(
        `//*[@class="account switcher"]//*[@class='logoutType2')]`
      );
    }
}
}

export = CommonHelper
`

This would essentially allow me to select the correct logout button, no matter where I am in the application by calling I.logOut() in a script

#### What do you get instead?

However, when I call this test just hangs and it is unable to evaluate the elements. I have tried console logging this and it won't log out anything. logging before the declaration of the actor works too, but none of the code after the actor. However, if I dump this code directly into a scenario. It will work as expected. I am a really at a loss of where to go with this one.

### Details

* CodeceptJS version: 3.0.0
* NodeJS Version: v14.17.0
* Operating System: Windows 10
* playwright v1.5.1
* Configuration file:

```ts
# paste config here
```
require("ts-node/register");

const { bootstrap } = require("./presettings.ts");

if (process.env.NODE_ENV !== "production") {
  require("dotenv").config();
}

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
//setHeadlessWhen(process.env.HEADLESS);

const project = process.env.TEST_PROJECT ;

exports.config = {
  tests: "./tests/**_test.ts",
  output: "./output",
  userAgent:
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36",
  helpers: {
    Playwright: {
      url: `https://${project}.${env}`,
      show: true,
      windowSize: "1600x900",
      browser: "chromium",
    },
    AuthenticationHelper: {
      require: "./helpers/AuthenticationHelper.ts",
    },
    CommonHelper: { require: "./helpers/CommonHelper.ts" },
  },
  bootstrap,
  include: {
    loginPage: "./loginPage.ts",
    homePage: "./homePage.ts",
  },
  name: "",
  plugins: {
    allure: {},
    retryFailedStep: {
      enabled: true,
    },
    screenshotOnFail: {
      enabled: true,
    },
    autoLogin: {
      enabled: true,
      saveToFile: false,
      inject: "loginAs",
      users: {
        
          },
        },
      },
    },
  },
};

**Comment by kobenguyent** [comment]
I think what you are trying to do is not proper.
- if you want to call any methods of a given helper -> https://codecept.io/helpers/#development
- if you want to create and extent custom steps to I object -> https://codecept.io/pageobjects/#actor
