### ISSUE TITLE
random string being assigned without file extension if fileName is missing to the downloaded file

### ISSUE THREAD

**Issue by anils92** [Codeception/CodeceptJS#3338]
#### What are you trying to achieve?

Download a file without providing the fileName using steps:

- I.handleDownloads()
- I.click(element)

#### What do you get instead?

> File downloaded having file name "ec9a85ea-177f-4a09-9ef2-da57f54305aa".

### Details

* CodeceptJS version: 3.3.0
* NodeJS Version: 16.15.0
* Operating System: Windows
* playwright

**Comment by dwentland24** [comment]
@anils92 Cannot see any issue in the current version. If `handleDownloads()` gets no parameter it will use `downloads` as file name. If you have more information regarding the issue I would have a closer look into it.

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
