### ISSUE TITLE
Embedded selenium server

### ISSUE THREAD

**Issue by mendrinos** [Codeception/CodeceptJS#334]
#### What are you trying to achieve?
When I first got started; I was getting the error: Couldn't connect to selenium server

Then, I typed:
phantomjs --webdriver=4444

And my test scripts are running.

In sake of simplicity; shouldn't be nice to have a selenium server running on the fly on every codeceptjs execution? Why I should manually open a separate selenium server? 

It would be easier for developers to run one command and see a headless execution outcome quickly..

Would be great to see a solution around this sometime soon :)

Thanks!

**Comment by DavertMik** [comment]
There are so much different servers and depending on your needs you can choose:

- selenium webdriver + different browsers
- headless selenium in docker
- phantomjs
- nightmare

the last one, btw starts the way you ask to: without external command, you need to use Nightmare helper for that. 

I have some ideas on implementing different runners for different servers but didn't have time yet to implement them

**Comment by DavertMik** [comment]
If curious here are my thoughts on better implementation of this feature https://github.com/Codeception/CodeceptJS/pull/191#issuecomment-238716090

**Comment by mendrinos** [comment]
Fantastic!

**Comment by PeterNgTr** [comment]
Possibly, we have `wdio-selenium-services` and `selenoid` plugin (https://github.com/Codeception/CodeceptJS/pull/2131) solve this.
