### ISSUE TITLE
fails to retrieve attribute of <svg> or under <svg> element 

### ISSUE THREAD

**Issue by VivekLande** [Codeception/CodeceptJS#3342]
Hello,

I trying to retrieve "href" attribute of or inside the element. but it fails and returns a blank object i.e. {}

please see below snap of HTML
![image](https://user-images.githubusercontent.com/16791810/174596778-f6987e53-dda3-4b49-8643-4e0f46bcd1f2.png)

Below is the way, we tried to retrieve attributes.
![image](https://user-images.githubusercontent.com/16791810/174596935-11225d9f-d766-4a69-a661-7ee9c3c52c06.png)

### Details

* CodeceptJS version: 3.3.3
* NodeJS Version: 16.5.0
* Operating System: Windows
* playwright

Please let me know if any more information needed
Thank you !

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
