### ISSUE TITLE
BDD step doesn't log to console until its calling method uses inject() object

### ISSUE THREAD

**Issue by VivekLande** [Codeception/CodeceptJS#3369]
#### What are you trying to achieve?
I am implementing a custom BDD step which calls a method and expecting that step should get executed and should log step to the console as well as to the report
![image](https://user-images.githubusercontent.com/16791810/179958375-1a82a26b-fbcf-4b38-b3b6-d75c46b8b2c7.png)

#### What do you get instead?
1] step getting executed and its method also gets called but that BDD step doesn't log to console nor to the report
![image](https://user-images.githubusercontent.com/16791810/179958756-0ee06ebe-3ca3-45cb-acb0-bb63fcba5529.png)

2] When I used to inject() objects into the calling method then this BDD step gets logged.
![image](https://user-images.githubusercontent.com/16791810/179959138-e65deeb6-d371-4a18-b7ac-a04d2037f9be.png)

### Details

* CodeceptJS version: 3,3.4
* NodeJS Version: 16+
* Operating System: Windows
* puppeteer || webdriverio || testcafe version (if related) Playwright
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
