### ISSUE TITLE
Can't fire bootstrap from presettings

### ISSUE THREAD

**Issue by nicostubi** [Codeception/CodeceptJS#3373]
Hello,

#### What are you trying to achieve?

Trying to use `presetting.ts` file to include boostrap and other methods in my project.
Reference to the [issue 18](https://github.com/codeceptjs/typescript-boilerplate/issues/18) created in typescript-boilerplate.

#### What do you get instead?

bootstrap method is not called

Example: 
[typescript-boilerplate-master.zip](https://github.com/codeceptjs/CodeceptJS/files/9196917/typescript-boilerplate-master.zip)

**_presettings.ts_**

```
export default {
	bootstrap: async () => {
		console.log('bootstrap')
	},
	teardown: async () => {},
	bootstrapAll: async () => {},
	teardownAll: async () => {},
}
```

### Details

* CodeceptJS version: 3.3.4
* NodeJS Version: 16.10.0
* Operating System: Windows 10
* playwright@1.23.4
* Configuration file:

```
require('ts-node/register')
const { setHeadlessWhen } = require('@codeceptjs/configure');
const { bootstrap } = require('./presettings.ts');

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './tests/**_test.ts',
  output: './output',
  helpers: {
    Playwright: {
      url: 'https://github.com',
      show: false,
      windowSize: '1200x900',
      browser: 'chromium'
    },
    CustomHelper: {
      require: './CustomHelper.ts'
    }
  },
  bootstrap,
  include: {
    loginPage: './loginPage.ts',
    homePage: './homePage.ts'
  },
  name: 'typescript-boilerplate',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

**Comment by kobenguyent** [comment]
hey @nicostubi may you try this in your codeceptjs config file? I'm currently using this without any issue.

```
...
bootstrapAll: require('./presettings.ts').bootstrapAll,
  bootstrap: require('./presettings.ts').bootstrap,
  teardownAll: require('./presettings').teardownAll,
  teardown: require('./presettings').teardown,
....
```

**Comment by nicostubi** [comment]
Hello @PeterNgTr 

Thank for this answer. I tried this, but still no console.log in the terminal.

Did you try my repro project to be sure we are on the same page?

Best Regards,
Nicolas

**Comment by kobenguyent** [comment]
hey @nicostubi could you try this?

```
module.exports = {
    bootstrapAll: async () => {
           console.log('bootstrap')
    },
};
```

**Comment by nicostubi** [comment]
Yes, it does work like that! Thanks.
