### ISSUE TITLE
codeceptjs@3.3.4  Vulnerabilities

### ISSUE THREAD

**Issue by rebajz** [Codeception/CodeceptJS#3382]
2x HIGH SEVERITY
https://snyk.io/test/npm/codeceptjs

**Comment by DavertMik** [comment]
This report was created automatically and is absolutely irrelevant for CodeceptJS

1. CodeceptJS is a testing tool that should not be exposed publicly. So hackers can't use it in any way.
2. There is no direct mention of CodeceptJS, only it is about dependent packages.

So keep CodeceptJS in a private environment and it won't introduce any security risks.
