### ISSUE TITLE
Tests fails when used CodeceptJS with Bitbucket and Reportportal.

### ISSUE THREAD

**Issue by Miriambnzdn** [Codeception/CodeceptJS#3386]
Hello, 
I've been using CodeceptJS with Bitbucket and ReportPortal for months and I'm having a problem that I don't understand. 
Sometimes I can't click on my application "Logon" button, all the attempts fail even if the button is present, stable and clickable. I get no other error message or screen shots. All my other tests fail, including some tests where I have to log in again. 

Did someone meet this issue before ?

**Comment by DavertMik** [comment]
No, it is very specific to your environment.
This can be possible due to changes in a browser or Playwright/Puppeteer/WebDriver whatever you use
