### ISSUE TITLE
Typescript codecept.conf.ts autoLogin Parameter 'I' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by nicostubi** [Codeception/CodeceptJS#3387]
#### What are you trying to achieve?

Use autoLogin with the typescript-boilerplate and autoLogin plugin including the proxy object "I".

#### What do you get instead?

![image](https://user-images.githubusercontent.com/47106274/184234498-663066c4-f8fa-4d99-88b6-55bb3814cc9d.png)

> Provide test source code if related

This is my repro project:

[typescript-boilerplate.zip](https://github.com/codeceptjs/CodeceptJS/files/9311896/typescript-boilerplate.zip)

It is the typescript-boilerplate, with the autoLogin config added from the official documentation [here](https://codecept.io/plugins/#autologin).

### Details

* CodeceptJS version: 3.3.3 (same issue with v. 3.3.4)
* NodeJS Version: 16.10.0
* Operating System: Windows 10
* playwright
* Configuration file:

```js
require('ts-node/register')
const { setHeadlessWhen } = require('@codeceptjs/configure');


// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './tests/**_test.ts',
  output: './output',
  helpers: {
    Playwright: {
      url: 'https://github.com',
      show: false,
      windowSize: '1200x900',
      browser: 'chromium'
    },
    CustomHelper: {
      require: './CustomHelper.ts'
    }
  },
  bootstrapAll: require('./presettings.ts').bootstrapAll,
  bootstrap: require('./presettings.ts').bootstrap,
  teardownAll: require('./presettings').teardownAll,
  teardown: require('./presettings').teardown,
  include: {
    loginPage: './loginPage.ts',
    homePage: './homePage.ts'
  },
  name: 'typescript-boilerplate',
  plugins: {
    autoLogin: {
      enabled: true,
      saveToFile: true,
      inject: 'loginAs', // use `loginAs` instead of login
      users: {
        user: {
          login: (I) => {
             I.amOnPage('/login');
             I.fillField('email', 'user@site.com');
             I.fillField('password', '123456');
             I.click('Login');
          },
          check: (I) => {
             I.amOnPage('/');
             I.see('User', '.navbar');
          },
        },
        admin: {
          login: (I) => {
             I.amOnPage('/login');
             I.fillField('email', 'admin@site.com');
             I.fillField('password', '123456');
             I.click('Login');
          },
          check: (I) => {
             I.amOnPage('/');
             I.see('Admin', '.navbar');
          },
        },
      }
    },
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

**Comment by nicostubi** [comment]
When I modify with: 

```
login: (I: any) => {
             I.amOnPage('/login');
             I.fillField('email', 'user@site.com');
             I.fillField('password', '123456');
             I.click('Login');
          },
```

I get an error at runtime (unexpected token ':')

**Comment by DavertMik** [comment]
Good point. Config file was not actually parsed as TS file so you got this error. 

This should be resolved in 3.3.5 where config file can be written in pure TS. 

Please update once it is released

**Comment by nicostubi** [comment]
Great news !

Thank you @DavertMik 

I Have to say I also struggled with custom actor implementation, custom helpers, etc. I guess these were problems linked to TypeScript as well. It might be worth checking as well (sorry I don't remember the exact problem, but so far I wasn't able to have working actors and custom helpers in my project). 

For exemple, [here ](https://codecept.io/pageobjects/#actor) the documentation describes the process for an Actor implemented in JavaScript. But not in TypeScript.

**Comment by kobenguyent** [comment]
hey @nicostubi if I understood correctly, your custom steps are not showing when typing I. right? if that's the case, I had a workaround which works for me

```
const { actor } = require('codeceptjs');
const faker = require('faker');
import ex from 'codeceptjs-expectwrapper'; // import it here

export = function () {
    return actor({
        async createNewUser(userData:object) {
            let payload = userData || {
                name: faker.name.firstName(),
                job: 'leader'
            };

            return this.sendPostRequest('/api/users', payload);
        }
    , ...ex}); // add it to actor object so that it can be used and showed when typing I (auto complete for actor I).
}
```

**Comment by DavertMik** [comment]
@nicostubi 

> For example, [here ](https://codecept.io/pageobjects/#actor)the documentation describes the process for an Actor implemented in JavaScript. But not in TypeScript.

You are right, and to be honest I could not find any good TypeScript way to customize actor as we do in JS.
So in 3.3.5 when you create a TS project there will be no custom actor created. You should use PageObjects instead.

So currently this limitation still there but not a critical one.

Probably some internal API should be changed to make it work fluently in TypeScript
