### ISSUE TITLE
Support flaky Tests

### ISSUE THREAD

**Issue by tfiwm** [Codeception/CodeceptJS#339]
If you use browserstack or saucelabs there is sometimes the problem that an emulator or a browser is not starting and for this a flaky mode would be great. Mocha already supports it and my question here. Do you already support it?

Here is a nice link to the [flaky tests](http://webdriver.io/guide/testrunner/retry.html) of webdriver.io

**Comment by DavertMik** [comment]
Thanks, that's a good idea. I will think how can I make this implemented

**Comment by tfiwm** [comment]
I found an easy way for the "Feature" and can show it as an PR ;) 
For Scenario it wasn't directly working but i am sure there is an easy way too.

**Comment by tfiwm** [comment]
PR: https://github.com/Codeception/CodeceptJS/pull/340

**Comment by DavertMik** [comment]
Thanks!
