### ISSUE TITLE
Option to set default time for `waitForElement`

### ISSUE THREAD

**Issue by wjaros** [Codeception/CodeceptJS#3390]
Instead of setting 5 seconds wait time for element each time when method is used, it would be nice to have possibility to set default value in the config.

**Comment by mirao** [comment]
This works for me with Playwright.
https://codecept.io/helpers/Playwright/#properties
`waitForTimeout ? default wait* timeout in ms. Default: 1000`

**Comment by nicostubi** [comment]
Not sure it's the timeout used for waitForElement @mirao

**Comment by mirao** [comment]
It's a timeout for all `waitFor*` actions, e.g. https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Playwright.js#L2168
