### ISSUE TITLE
Default retry for each scenario/feature

### ISSUE THREAD

**Issue by wjaros** [Codeception/CodeceptJS#3391]
It would be nice to have option to set by default that scenario that fails will be retried given number of times.

**Comment by nicostubi** [comment]
Do you mean one specific scenario? Or all scenarii of your project?

**Comment by wjaros** [comment]
Maybe I should have written every, yep I mean it would be nice to have an ability to set that by default every scenario in the project will be retried given number of times if fails instead of using  `.retry()` for a single scenario, or a feature.

**Comment by JakubKasprzyk** [comment]
Up - I also think this would be a nice option to set up the `.retry()` as default for every scenario/feature - it will save us a lot of lines of code ;)

**Comment by DavertMik** [comment]
Implemented in 3.4.0
