### ISSUE TITLE
Typings in codecept.conf.js

### ISSUE THREAD

**Issue by adelin-b** [Codeception/CodeceptJS#3392]
#### What are you trying to achieve?
Trying to have typed configuration
```
// Set type for codeceptjs config
/** @type {import('codeceptjs').Config} */
exports.config = {
  tests: 'tests/**/*.ts',
  output: 'output',
  helpers: {

```

Would be nice if by default the generated codecept had type hint for typescript or even javascript users.

#### What do you get instead?

No types shown.

**Comment by DavertMik** [comment]
thanks for the idea!
started to implement it just at the moment I read about this
going to be in nxt CodeceptJS release

**Comment by DavertMik** [comment]
Done in 3.3.5

Add ``/**@type {CodeceptJS.MainConfig}**/`` to CodeceptJS config

```js
/**@type {CodeceptJS.MainConfig}**/
exports.config = {
  //...
}
```
