### ISSUE TITLE
Testomat plugin reports failure 

### ISSUE THREAD

**Issue by openmindculture** [Codeception/CodeceptJS#3403]
#### What are you trying to achieve?

I am trying to setup automated Testomat.io tests, following the steps described at

https://app.testomat.io/projects/ingo-steinke-de/runs/setup

for my repository at https://github.com/openmindculture/ingo-steinke.de

I have got a working CodeceptJS test scenario.
I have set up Testomat.io and imported my CodeceptJS scenario using the API.
I have set up a Manual Run of my imported test.
I have added the `@testomatio/reporter` plugin: `npm install --save-dev @testomatio/reporter`
I have added the plugin configuration in `codecept.conf.js` below the `plugins` key:

```js
exports.config = {
  tests: './codecept/*_test.js',
  ...
  plugins: {
    testomat: {
      enabled: true,
      require: '@testomatio/reporter/lib/adapter/codecept',
      apiKey: process.env.TESTOMATIO,
    }
```

I ran `TESTOMATIO=__$APIKEY__ npx codeceptjs run` on the command line.

I expected a confirmation that I have set up automated tests.

#### What do you get instead?

Argument should belong to the same JavaScript world as target object

**Comment by openmindculture** [comment]
While it says `plugins: testomat` in the quick mini documentation on testomat.io, it is `plugins: testomatio` in the [full docs at GitHub](https://github.com/testomatio/reporter#codeceptjs). Still, both variations failed and result in the same error message.

**Comment by DavertMik** [comment]
@openmindculture 

> I expected a confirmation that I have set up automated tests.

Sorry, what confirmation step you expected
reporting will work even if you didn't import tests into Testomat.io beforehand

Could you expand on what did you expect to see?

P.S Name of aplugin in config doesn't matter, it can be testomatio or testomat.

**Comment by openmindculture** [comment]
ok, then if there is no error, it should not look like an error. But it's the trstomat.ui misleading me to think that I should set up anything in my project, after clicking on setup automatic test where I'd expect some sort of cron tab, öike set up tests to run every hour / day / week / or triggered by git deployment. 

Sorry for the fuzzy wording  I can add screenshots and better description on Friday.

**Comment by DavertMik** [comment]
I think I got it, you thought of "automatic execution of tests" not of "automatic tests"

as we have automatic tests as a concept of any test written in a programming language and executed via test runner
and manual test is the one performed in UI by a person

**Comment by openmindculture** [comment]
In the context menu (triple dots right on top) it says "Setup Automated", which then leads to this instruction page, while I would have expected that this would lead to a settings option allowing me to set up / schedule an automatic execution of tests.

![Screenshot](https://user-images.githubusercontent.com/6377941/188157436-5f376107-2352-48e8-a5af-ca0ea3fe61ff.png)

Reading the text again, this seems to be more about automated reporting though.

So I still wonder about the unique advantages of Testomat, like mixing tests of different platform syntax (jest, cypress, codecept etc.) and putting it altogether in one dashboard, it surely must have an option to run the tests without human interaction? and send automated reports afterwards? Or should I rather use jenkins, GitLab etc. for this kind of "automation"?

**Comment by openmindculture** [comment]
So "my automated tests" are probably "continuous integration" to Testomat.io, and I must use another / third party tool to trigger that kind of run?

![Screenshot of continuous integration options in Testomat.io UI](https://user-images.githubusercontent.com/6377941/188168256-7aca66ee-bdd2-49a6-88d8-d131b47a495c.png)

**Comment by DavertMik** [comment]
@openmindculture Indeed, scheduling and automation should be done on CI

Testomat.io can be used only for reporting and managing tests. We are not CI system on our own.

To run tests on schedule you can use GitHub Actions:

https://dev.to/tmchuynh/github-action-schedules-ad5#github-action-schedules

**Comment by openmindculture** [comment]
Thanks for clarification. I will update [my blog post](https://dev.to/ingosteinke/automating-tests-using-codeceptjs-and-testomatio-first-steps-3b2e) accordingly. This issue can be closed.
