### ISSUE TITLE
New types wrong for waitForNavigation

### ISSUE THREAD

**Issue by javierfuentesm** [Codeception/CodeceptJS#3406]
#### What are you trying to achieve?
To set the waitForNavigation in the playwright config but the type is expecting a number instead of a string
#### What do you get instead?

![image](https://user-images.githubusercontent.com/19244527/189944867-ba944726-15f4-4927-847e-51bcdd0cdee8.png)

### Details

* CodeceptJS version:3.3.5 
* NodeJS Version: 12
* Operating System:mac
* puppeteer || webdriverio || testcafe version (if related) playwright

**Comment by mirao** [comment]
Fixed in https://github.com/codeceptjs/CodeceptJS/pull/3401

**Comment by javierfuentesm** [comment]
> Fixed in #3401

thank i will just wait for the release
