### ISSUE TITLE
Error in documentation for handleDownloads and FileSystem helper ?

### ISSUE THREAD

**Issue by nicostubi** [Codeception/CodeceptJS#3409]
Hello,

I think there is a mistake in the documentation for handleDownloads:

```
I.handleDownloads('downloads/avatar.jpg');
I.click('Download Avatar');
I.amInPath('output/downloads');
I.waitForFile('downloads/avatar.jpg', 5);
```

Why would 'waitForFile' need 'downloads/', while 'I.amInPath' is already setting the current folder to 'output/downloads'?

This would be the fix:

```
I.waitForFile('avatar.jpg', 5);
```

Best Regards,
Nicolas

**Comment by nicostubi** [comment]
Hello, 

Any news? Can you confirm it's a mistake?

BR
Nicolas

**Comment by kobenguyent** [comment]
yes @nicostubi it's a mistake, I believe
