### ISSUE TITLE
doesn't have browser access in _beforeSuite hooks

### ISSUE THREAD

**Issue by VivekLande** [Codeception/CodeceptJS#3417]
#### What are you trying to achieve?
I want to perform some precondition on the application in before suite, for that I should have access to the browser

#### What do you get instead?
Browser instance is not available in _beforeSuite hooks

### Details

* CodeceptJS version: 3.3.3
* NodeJS Version: 16.5
* Operating System: Windows
* puppeteer || webdriverio || testcafe version (if related) Playwright
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
https://codecept.io/basics/#beforesuite

I guess this is by design.
