### ISSUE TITLE
My tests fails when I used CodeceptJS (helper Playwright) with Bitbucket and Reportportal.

### ISSUE THREAD

**Issue by Miriambnzdn** [Codeception/CodeceptJS#3419]
Hi,
I raise the issue again including the necessary information.
I am using CodeceptJS with the helper Playwright, ReportPortal and Bitbucket and having an issue.
Sometimes I can't click on my application "Logon" button, all the attempts fail even if the button is present, stable and clickable.
I get no other error message or screen shots. All my other tests fail, including some other tests where I have to log in again.
These are the steps I follow :
<img width="1327" alt="Capture d’écran 2022-09-13 à 11 41 27" src="https://user-images.githubusercontent.com/94960638/191934211-5763e953-8915-4607-ad81-7940a58f484c.png">
Below the results including the failling code :
<img width="680" alt="Capture d’écran 2022-09-13 à 11 43 23" src="https://user-images.githubusercontent.com/94960638/191934242-bbc45a90-7337-4657-ba30-74cebb620cb3.png">
Thank you.

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
