### ISSUE TITLE
Assertions without grab?

### ISSUE THREAD

**Issue by tboesgaard** [Codeception/CodeceptJS#342]
## Feature idea
I would like to see more easily read assertions, along the lines of:

I.seeNumberEquals(123, '#number')

I know something similar could be acheived using the grab functionality, and my own favorite assertion-library. But I think that would break the nice and easily read syntax of the scenariobased testscript.

If I was to try and implement this myself, what would be a good way to do this, as to not break the overall architecture?

Kind regards

Thomas

**Comment by nverma0306** [comment]
How i would pick different values on a website and compare them and click on the corresponding button which has the lowest value
For Eg: On a travel website, I want to book a flight and I wish to pick different flight rates from page and click on Select corresponding the cheapest flight
