### ISSUE TITLE
Remove unsupported allure-js-commons dependency

### ISSUE THREAD

**Issue by dzienisz** [Codeception/CodeceptJS#3422]
#### What are you trying to achieve?

`allure-js-commons` is depreciated and not supported. There is a lot of deps vulnerabilities like uuid@3.x.x

#### What do you get instead?

I propose to remove that dependency or aquarie code or ownership and update it

### Details

I don't know how much is integrated into ConceptJS but maybe it's time to do something with that before it would kill the project.

**Comment by DavertMik** [comment]
Yes, it will be removed in 3.4.0

**Comment by jedicwb** [comment]
Oh no..

**Comment by dzienisz** [comment]
Why? Can you elaborate?

**Comment by javierfuentesm** [comment]
allure for me it's the best reporter i will miss it
