### ISSUE TITLE
With integrating with ReportPortal, after upgrading to CodeceptJS 3.3.0, tests hanging forever

### ISSUE THREAD

**Issue by YSuMinto** [Codeception/CodeceptJS#3427]
#### What are you trying to achieve?
Upgrade CodeceptJS to the latest version, tests run as normal
#### What do you get instead?
We were using CodeceptJS 3.2.3, integrating with reportPortal 5.6.2, all tests ran fine.
But after upgrading CodeceptJS to 3.3.0 or any higher version, still integrating with reportPortal 5.6.2, tests start to hang forever and cannot finish. 

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Error: timeout of 30000ms exceeded
    at /home/runner/work/kp-uidredger/kp-uidredger/node_modules/@reportportal/client-javascript/lib/rest.js:37:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
```

### Details
We are using the official CodeceptJS Agent for ReportPortal, @reportportal/agent-js-codecept, which has been no updates since 2 years ago. (https://www.npmjs.com/package/@reportportal/agent-js-codecept)
* CodeceptJS version: 3.3.0 and any higher version
* NodeJS Version: 14
* Operating System: ubuntu
* Configuration file:
Per the document, there is no ```timeout``` property included
```js
        reportportal: {
            enabled: true,
            require: "@reportportal/agent-js-codecept",
            token: reportPortalToken,
            endpoint: "https://reportportal.dev.galil.io/api/v1",
            projectName: reportPortalPro,
            launchName: "Daily Smoke - " + threadId,
            // launchDescription: "Daily smoke tests"
        },
```

Could you please have a check?  

Much Thanks!
Yuan

**Comment by kobenguyent** [comment]
````

> codeceptjs-rest-demo@1.0.0 test
> codeceptjs run

CodeceptJS v3.3.5 #StandWithUkraine
Using test root "/Users/tamara-thanh/Desktop/codeceptjs-rest-demo"

DELETE tests --
📋 Writing results to ReportPortal: peterngtr_personal > https://demo.reportportal.io/api/v1
  ✔ Verify deleting a user in 218ms
GET tests --
  ✔ Verify a successful call in 176ms
  ✔ Verify a not found call in 217ms
  ✔ Verify getting a single user in 101ms
  ✔ Verify getting list of users in 116ms
POST tests --
  ✔ Verify creating new user in 224ms
  ✔ Verify uploading a file in 907ms
PUT tests --
  ✔ Verify creating new user in 194ms

  OK  | 8 passed   // 3s
 📋 Report #1 saved ➡ https://demo.reportportal.io/ui/#peterngtr_personal/launches/all/118

````
Hi @YSuMinto it's working fine with my tests with codeceptjs 3.3.5 

![Screen Shot 2022-09-27 at 11 09 31 AM](https://user-images.githubusercontent.com/7845001/192484957-01f9037f-bb09-4786-8105-76f09bc042b1.png)

**Comment by YSuMinto** [comment]
Thank you @PeterNgTr for the quick reply! But the same issue happens with CodeceptJS 3.3.5 on our side 
Could you let me know 
1> What's your ReportPortal's version? 
2> Can @reportportal/agent-js-codecept support to set timeout property?

We are running e2e tests on our end, which take much longer time. The tests ran fine at the beginning, but after running about 1 hour and 40 mins, the tests started hang, 
![image](https://user-images.githubusercontent.com/91275074/192501235-845c6583-0465-4803-993d-347e254ff104.png)
![image](https://user-images.githubusercontent.com/91275074/192501284-86196300-e3b8-4771-afe3-3f55aefc4f7d.png)

**Comment by kobenguyent** [comment]
hey @YSuMinto 
I'm using https://demo.reportportal.io/ui/#api
![Screen Shot 2022-09-27 at 12 45 51 PM](https://user-images.githubusercontent.com/7845001/192506029-cdbe9a9f-36ae-4c46-be19-e295ee7e9c33.png)

**Comment by YSuMinto** [comment]
You are using the ReportPortal ```5.7.2```. On our end, we are using ```5.6.2```
Could you please confirm CodeceptJS ```3.3.5``` can use with ReportPortal ```5.6.2``` ?

**Comment by kobenguyent** [comment]
That thing I can't guarantee cause I don't have any local RP here. Why don't you give it a try with new version of RP? In the end of the day, I guess, RP team will fix issues on newer version rather than the older ones 😄

**Comment by kobenguyent** [comment]
I think it's from RP integration not codeceptjs itself. Closing for now.
