### ISSUE TITLE
Retry() does not work properly when we are using Scenario.only

### ISSUE THREAD

**Issue by JakubKasprzyk** [Codeception/CodeceptJS#3439]
The .retry() does not work properly if we are using it with `Scenario.only`. I've simulated the test failure and it is not being executed after failure. In the terminal, the result is highlighted in green with the text "OK 0 passed". Below is a screen from the terminal:

![image](https://user-images.githubusercontent.com/67008060/194539393-7a6dc176-a6fa-4674-b5c8-6a231ad7f63e.png)
You can see that the test should fail because we've filled the field with "435,00" and we are expecting to see "222,00"

In addition, I'm attaching the source code below:

```
Scenario.only(
  'You can save editing of custom product without any changes',
  async ({ I, posPage, device, adminCalendarNavigationPage }) => {
    const { proSalon: salon, logInToAdmin } = await I.getEnvironment({ I });
    await logInToAdmin(salon.owner);
    I.click(adminCalendarNavigationPage.posNavigation);

    if (device.isMobile) {
      I.click(posPage.mobileCheckoutButton);
    }
    const { customProductName: productName, customProductPrice: productPrice } =
      posPage.createCustomProduct(salon.country);

    if (device.isMobile) {
      I.click(posPage.checkout.tooltip.mobileButton);
    } else {
      I.click(posPage.checkout.tooltip.button);
    }
    I.click(posPage.checkout.tooltip.editItem);
    I.click(posPage.addCustomItemDialog.saveButton);
    const productPrice2 = '222,00'
    I.see(productName, posPage.checkout.itemName);
    I.see(`${productPrice2} €`, posPage.checkout.totalPrice);
  },
).retry(2);
```

I've also tried with `{ retries: 2 }` - but unfortunately with the same result. 
I'm working on CodeceptJS + Playwright.

**Comment by Horsty80** [comment]
I've the same issue with `retry(X)` for scenario.

With retry, and a failed assert like `I.see()` with wrong value lead to this strange ending

![image](https://user-images.githubusercontent.com/15615569/195101199-015b26c2-a7ea-46fa-9ea5-75bae011081c.png)

Than without `retry(X)` we have a correct assert error message like this 
![image](https://user-images.githubusercontent.com/15615569/195101322-d3444c3c-2a5e-405b-8588-44f982601842.png)

Otherwise, it's seems that no screenshot are taken when test is failing with retry option enable.

Any idea ?

Versions :
```json
    "codeceptjs": "^3.3.0",
    "playwright": "^1.20.2",

```

**Comment by JakubKasprzyk** [comment]
@Horsty80 
I've resolved my problem - it was not working due the `.only ` flag situated next to the Scenario - otherwise it is working properly. Not sure if it will help you but I wanted to let you know about that ;) 
I've updated the issue description.

**Comment by Horsty80** [comment]
Thanks @JakubKasprzyk 
I think is still an issue, if we use `.only` for debugging the `retry()` shouldn't conflict.

I need to check but I think in allure report I lose the assert error message (without `only`) 

=/
