### ISSUE TITLE
Scenario.skip causes 'Cannot read property retries of undefined'

### ISSUE THREAD

**Issue by hubidu** [Codeception/CodeceptJS#347]
#### What are you trying to achieve?

I have a **Scenario.skip** call in a feature file.

#### What do you get instead?

When I run the test with version 0.4.13 it fails with the following error:

```
Cannot read property 'retries' of undefined
27-Dec-2016 10:30:37	
27-Dec-2016 10:30:37	TypeError: 
27-Dec-2016 10:30:37	    at context.Scenario (/var/atlassian/application-data/bamboo/xml-data/build-dir/VEVE-UT-JOB1/node_modules/codeceptjs/lib/interfaces/bdd.js:102:15)
27-Dec-2016 10:30:37	    at Function.context.xScenario.context.Scenario.skip (/var/atlassian/application-data/bamboo/xml-data/build-dir/VEVE-UT-JOB1/node_modules/codeceptjs/lib/interfaces/bdd.js:122:15)
```

#### Cause

Scenario.skip calls Scenario, but only with the title parameter. **The opts parameter is undefined**. Therefore it fails on line 102 in bdd.js.

There should probably be default parameters in Scenario.

**Comment by DavertMik** [comment]
Yes, thank you, this should be updated
