### ISSUE TITLE
Gherkin Typescript definition missing `string` type for steps config

### ISSUE THREAD

**Issue by AWolf81** [Codeception/CodeceptJS#3474]
Thanks for the great project. 
I'm pretty new to it and I really like it. At the moment, I'm trying Gherkin and found an issue in the configuration.

**codecept.conf.ts**
```ts
{
  // rest of config
 "gherkin": {
   "features": "./features/*.feature",
   "steps": "./step_definitions/*_steps.ts"  // <<<< error here: Type 'string' is not assignable to type 'string[]'
  }
}
````

I think the type definition for [Gherkin steps](https://github.com/codeceptjs/CodeceptJS/blob/3.x/typings/index.d.ts#L260) is incomplete.

Without the string type, glob patterns are not supported for Gherkin step files because Typescript fails.

Error message in the terminal if the string is used
![grafik](https://user-images.githubusercontent.com/3046542/197888555-1ffc2e53-a74e-47db-9f80-a3d881a4f909.png)

It should be
```ts
gherkin?: {
      /** load feature files by pattern. Multiple patterns can be specified as array */
      features: string | Array<string>,
      /** load step definitions from JS files */
      steps: string | Array<string>
    };
```

The code supports the glob pattern. I tested it by adding the type and it's also in the code [here](https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/container.js#L312)

The problem was also mentioned [here](https://github.com/codeceptjs/CodeceptJS/issues/1871) - just to add this reference.

**Comment by kobenguyent** [comment]
May you raise a PR? @AWolf81

**Comment by AWolf81** [comment]
@PeterNgTr Sure, I can create a PR.

Can I add it to the index.d.ts file directly?
Or is there a better place? I've seen that there is a way to generate the typings. 
Or is this not prepared for the config?

**Comment by kobenguyent** [comment]
https://github.com/codeceptjs/CodeceptJS/blob/3.x/typings/index.d.ts#L256

I suppose it's the way @AWolf81

**Comment by AWolf81** [comment]
OK, I've added the type in the mentioned PR.

As a workaround until this is released. It's possible to add the type in the config like following:
```ts
// codecept.conf.ts
type CodeceptJSModified = Omit<CodeceptJS.MainConfig, "gherkin"> & { 
  gherkin: {
    features: string | Array<string>
    steps: string | Array<string>
  }
};
export const config: CodeceptJSModified = {
  // now supports the config with string pattern
};
```
