### ISSUE TITLE
retry option for protractor

### ISSUE THREAD

**Issue by shanmohan** [Codeception/CodeceptJS#348]
i see that latest changelog says `retry` option has been implemented which is pretty handy given that some of the test cases are unpredictable at times.

has this change implemented for protractor as well? thanks

**Comment by DavertMik** [comment]
Yes, this option is available for all test. The option is added on per test basis, so you can add to any of your tests: 

```
Feature('Some Protractor Test', {retries: 3});
```

This can be set in test file only, not in global config (yet)

**Comment by shanmohan** [comment]
Thanks @DavertMik i tried this option with Protractor and codecept 0.4.15. `retries` option works well with `Feature` but not with `Scenario`. is that how it is intended?
