### ISSUE TITLE
Can't run run-workers with --suits option for more than 2 workers

### ISSUE THREAD

**Issue by lucasbit** [Codeception/CodeceptJS#3486]
#### What are you trying to achieve?
Run tests in parallel using run-workers. I'm trying to use 4 or 6 workers
#### What do you get instead?
Only 2 workers are executing tests. If I run tests with "run-workers --suites 6" in output there will be shown only first and last worker. 
> Provide console output if related. Use `--verbose` mode for more details.
![image](https://user-images.githubusercontent.com/29520131/198969784-ca2a9d65-0041-4d2c-a462-0ca9c81c1392.png)

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```
![image](https://user-images.githubusercontent.com/29520131/198969871-55f766b1-30f7-4675-8965-4f6b1ce67a89.png)

### Details

* CodeceptJS version:3.3.6 but tested also on 3.2.1
* NodeJS Version:19 but tested also on 14
* Operating System: Windows
* Configuration file:

```js
# paste config here
![image](https://user-images.githubusercontent.com/29520131/198975885-a111f1de-af55-4569-8457-a23aeb442b90.png)

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
