### ISSUE TITLE
Nightmare-Electron restart option

### ISSUE THREAD

**Issue by nairvijays99** [Codeception/CodeceptJS#349]
#### What are you trying to achieve?
Passed ```restart:false``` to Nightmare configuration in ```codecept.conf.js```
#### What do you get instead?
New instance of Electron is instantiated with each codecept Scenario
### Details

* CodeceptJS version: 0.4.13
* NodeJS Version: 6.7.X
* Operating System: MAC OS

Configuration:
...
    Nightmare: { 
      restart: false
    }
...

**Comment by nairvijays99** [comment]
I am planning to check in the fix for this today. Since it is going to be a configuration driven enhancement, it should not cause any regression to existing user base.

**Comment by nairvijays99** [comment]
I have added restart option to run CC suite in a single browser instance. As like for other helpers, the value is defaulted to truthy.

**Comment by DavertMik** [comment]
Thanks for the implementation. Should be available in 0.4.14

**Comment by aryzle** [comment]
@DavertMik @nairvijays99 this still fails for me
CodeceptJS V0.6.3
