### ISSUE TITLE
Create a Chrome extension for Recorder 

### ISSUE THREAD

**Issue by gunta** [Codeception/CodeceptJS#3499]
#### What are you trying to achieve?

Chrome supports recording sessions, and since Chrome 104 it supports exporting to 3rd party scripts.
Currently the following are supported trough extensions to the Recorder:
- Cypress
- WebPageTest
- Nightwatch
- Testing Library
- WebdriverIO

https://github.com/puppeteer/replay#create-a-chrome-extension-for-recorder-available-from-chrome-104-onwards

**Comment by DavertMik** [comment]
Looks really tasty & interesting, unfortunately I won't have time for this 
But if anyone want to create that extension you get my full support
On any questions I'm available in Slack

**Comment by kobenguyent** [comment]
hey @DavertMik 
https://github.com/PeterNgTr/codeceptjs-recorder-extension
https://github.com/PeterNgTr/codeceptjs-chrome-recorder

I drafted those recorder extension for codeceptjs, but not sure how to load it as chrome extension to test it.

**Comment by DavertMik** [comment]
@gunta Could you test it and send a feedback?

**Comment by gunta** [comment]
@DavertMik Thanks! 
I will test and give feedback here
