### ISSUE TITLE
Save downloaded file to disk without specifying a filename

### ISSUE THREAD

**Issue by leytanfortuin** [Codeception/CodeceptJS#3510]
#### What are you trying to achieve?
Using the I.handleDownloads() function to save downloaded file to disk without specifying a filename. The filename should be derived from an api response in the browser. 

#### What do you get instead?
Error when the file is being copied from the temp folder to the download location:
 ```
Uncaught EISDIR: illegal operation on a directory, copyfile '/var/folders/28/2pw_t8bn41sfxmdrrqb3g4400000gn/T/playwright-artifacts-eU4NU6/54a13440-480d-48dd-ae41-2ab094a980ea' -> '/Users/leytan.fortuin/Documents/GitHub/ksys-test-apps/output/downloads'
      at Object.copyFileSync (node:fs:2817:3)
      at /Users/leytan.fortuin/Documents/GitHub/ksys-test-apps/node_modules/codeceptjs/lib/helper/Playwright.js:1232:10
```

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.3.5
* NodeJS Version: 16.16.0
* Operating System: MacOS 12.5.1
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
https://codeceptjs.slack.com/archives/C94G8JXJB/p1669807885849769
