### ISSUE TITLE
Update version WebdriverIO 8.0.0 ?

### ISSUE THREAD

**Issue by MathieuD-QA** [Codeception/CodeceptJS#3518]
#### What are you trying to achieve?
Hi, Could you update the version of WebdriverIO 7.16.14 > 8.0.0 ?

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by DavertMik** [comment]
Updated
