### ISSUE TITLE
Scenario titles containing data from an Examples table are logged incorrectly

### ISSUE THREAD

**Issue by snehabhandge** [Codeception/CodeceptJS#3526]
### **This is an improvement.**

If scenario title contains data from Examples like below it is not getting reported as expected.
```
Scenario Outline: Below are the users - <user>
Examples:
    | user   |
    | Sneha  | 
    | Ram    |
```

The expected logged Scenario name
```
Below are the users - Sneha
Below are the users - Ram
```

#### What do you get instead?
The actual logged Scenario name
```
Below are the users - <user> {\"user\":\"Sneha\"}"
Below are the users - <user> {\"user\":\"Ram\"}"
```

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.3.7
* NodeJS Version: 16.14.0
* Operating System: windows
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
