### ISSUE TITLE
Unable to report a test failed when failure occurs during teardown

### ISSUE THREAD

**Issue by kirksl** [Codeception/CodeceptJS#3529]
#### What are you trying to achieve?

I'd like to report that the test failed eg "FAIL | 0 passed, 1 failed"
When a failure occurs as the last step within a test wherein that step is executed from a teardown
Reason for executing from a teardown is to avoid adding this common step to all of my tests

#### What do you get instead?

Using one of the many options provided by Codecept from my Custom Helper I get...
_finishTest() {} - test is marked as passed
_after() {} - test is marked as passed
_passed() {} - test is marked as passed
event.dispatcher.on(event.test.after...) - test shows 1 passed, 2 failed
event.dispatcher.on(event.test.passed...) - test shows 1 passed, 1 failed
event.dispatcher.on(event.test.finished...) - test shows 1 passed, 1 failed
event.dispatcher.on(event.all.after...) - test shows 1 passed

### Details

* CodeceptJS version: 3.3.7
* NodeJS Version: 18.12.0
* Operating System: macOS Monterey 12.6
* Appium

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
