### ISSUE TITLE
grep command is not working with Or condition

### ISSUE THREAD

**Issue by Arthanarieaswaran** [Codeception/CodeceptJS#3536]
#### What are you trying to achieve?

I am trying to run multiple test cases using tags like test1 or test2

#### What do you get instead?

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/6602970/207596714-20ca838a-eb87-49ec-b179-776bb7198a60.png">

> Provide console output if related. Use `--verbose` mode for more details.

```bash
PS C:\Artha\AutomationFramework\Clinicals\clinicals-ui-automation-framework> npx codeceptjs run --plugins allure --grep "\@End2End|\@E2E" --verbose
'\@E2E' is not recognized as an internal or external command,
operable program or batch file.
```

> Provide test source code if related

<img width="259" alt="image" src="https://user-images.githubusercontent.com/6602970/207597125-141b2204-0aaf-482a-b3e8-9efce8b2a00e.png">

```js
// paste test
```

### Details

* CodeceptJS version: 3.3.3
* NodeJS Version:16.15.1
* Operating System: Windows 2016 OS
* puppeteer || webdriverio || testcafe version (if related): Webdriver
* Configuration file:

```js
helpers: {
    WebDriver: {
      url: 'http://localhost',
      browser: 'chrome',
      host: 'localhost',
      port: 4444,
      restart: false,
      windowSize: "maximize",
      desiredCapabilities: {
        'goog:chromeOptions': {
          prefs: {
            profile: {
              default_content_settings: {
                popups: 0
              }
            }
          },
          useAutomationExtension: false,
          args: [
            //-- '--headless',
            '--start-maximized',
            '--disable-gpu',
            '--disable-extensions',
            '--disable-popup-blocking',
            '--disable-infobars',
            '--ignore-certificate-errors'
          ]
        },
      }
    }
  },
```

**Comment by kobenguyent** [comment]
it's working normally for me
<img width="1259" alt="Screen Shot 2022-12-14 at 1 51 46 PM" src="https://user-images.githubusercontent.com/7845001/207600136-d9ff2366-dfe9-4703-bc90-b8ea973141ae.png">

**Comment by Arthanarieaswaran** [comment]
Thanks for your immediate reply, 

I am using CodeCeptJS BDD format, 
feature below listed in CodeCeptjs
https://codecept.io/bdd/#what-is-behavior-driven-development

**Comment by myrepojuly** [comment]
@Arthanarieaswaran  hello..I just ran this in BDD format without any issues with the same set of tags... Can you please do npm update once?

**Comment by Arthanarieaswaran** [comment]
Thanks for your reply [myrepojuly1987](https://github.com/myrepojuly1987)

I have update the node, but still i am getting same issue, is there any github project is available, i can set my machine and try

Note: --grep "@End2End" this is working for me, but not working And/Or conditions in the grep


<img width="952" alt="image" src="https://user-images.githubusercontent.com/6602970/207619912-0a20154f-b013-4a12-a417-f6cd9620b447.png">

**Comment by myrepojuly** [comment]
@Arthanarieaswaran - Apologies.. Believe you are using windows to run... Just try leaving space between the OR condition in GREP. Something like this `npx codeceptjs run --grep  "@End2End | @E2E" --verbose`

**Comment by Arthanarieaswaran** [comment]
Thanks a [myrepojuly1987](https://github.com/myrepojuly1987)

`npx codeceptjs run --grep "@End2End | @E2E" --verbose`

this space  between the pipe is worked me, thanks for pointing out the windows and mac environment different.
[PeterNgTr](https://github.com/PeterNgTr) thanks for your input.

**Comment by Arthanarieaswaran** [comment]
I think, if grep is not working as expected in windows system, so it may need to taken care and whatever format we are writing on macOS, same format of grep should support for WindowsOS also. So this may consider as bug and fix in the codeceptjs source code. Please let me know your thought.

**Comment by kobenguyent** [comment]
````
npx codeceptjs run --grep "\@smoke1| \@s2"
CodeceptJS v3.3.7 #StandWithUkraine
Using test root "C:\Users\nguyenth\Desktop\codeceptjs-rest-demo"

PUT tests --
  √ Verify creating new user @smoke1 in 179ms
  √ Verify creating new user @s2 in 194ms

  OK  | 2 passed   // 866ms
````
I tested on windows which is fine when adding the spacebar in between. This is handled by Mocha itself, so I'm not sure what could be done within CodeceptJS.

**Comment by Arthanarieaswaran** [comment]
Thanks [PeterNgTr](https://github.com/PeterNgTr)
as mentioned by [myrepojuly1987](https://github.com/myrepojuly1987), it --grep "@End2End | @E2E"  worked for me and I am agreeing with you, --grep is comes from Mocha, it may not valid bug/issue in CodeceptJS.

As of now, i am taking care internally processing this grep command and producing space between the pipe.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/6602970/207918953-574fac5c-6f27-4dcb-b301-0d91dfe5ccc9.png">

**Once again I thanks for all of you guys, this was very long pending item with me, it come to conclusion in a day. Keep doing good work.**

**Comment by rkgour7492** [comment]
@Arthanarieaswaran were you able to execute both tags. I am also trying with space but only one tag is running from below 
 npx codeceptjs run --steps --grep  "\@C123444 | \@C683248"
