### ISSUE TITLE
Question : Execute the test cases from another service

### ISSUE THREAD

**Issue by shanmohan** [Codeception/CodeceptJS#354]
Hello, i have built test cases using codeceptjs. Now, i would like a build a dashboard where non technical users can just click a button which will execute the `codecept run --steps` command and tell the user the result. My question, How do i get access to the information such as below,

1. Event to see when the test execution is completed
2. Overall pass/fail status
3. steps details

Is there any library to be used in conjunction with codeceptjs or any idea would be appreciated.

**Comment by san4io** [comment]
Why don't you wanna use mochawesome reporter? http://codecept.io/reports/#html

**Comment by shanmohan** [comment]
thanks @san4io i am using mochawesome as a reporting tool to check manually. But my question is around **APIs by which i can get to know when the execution is completed and a boolean indicator to say it passed or not programatically**. Otherwise user will not know when the test is completed..

Assume if i am putting this in CI pipeline and i want to proceed to UAT deployment only if test cases passes in SIT. How can i do that check programatically? Hope my question is clear.

**Comment by DavertMik** [comment]
Sorry, was on vacation and couldn't answer earlier.

I'm not sure how can I help you, there is no official guide for using CodeceptJS in custom code (but I hope I will add one soon). However, you can learn from its code.

```js
    var opts = { steps: true }
    codecept = new Codecept(config, steps);
    codecept.init(testRoot, function (err) {
      if (err) throw new Error('Error while running bootstrap file :' + err);
      codecept.loadTests();
      codecept.run(test);
    });
```
To access event system (test end, step events, etc) please see [listeners](https://github.com/Codeception/CodeceptJS/tree/master/lib/listener) implementation. You can create your own and register after `init`. 

I hope this helps. As I said I plan to write a better guide about custom integration but everything takes time, as I'm doing it in spare time.

**Comment by DavertMik** [comment]
> Basically how do i listen to mocha events programatically when using codeceptjs?

Maybe you can write a helper that does just that?
Helper can listen events like before/after/beforeSuite/afterSuite/failed, etc. This might be enough for you

**Comment by APshenkin** [comment]
Closing due inactivity
