### ISSUE TITLE
Math.Random is not a function

### ISSUE THREAD

**Issue by michaeltomasik** [Codeception/CodeceptJS#355]
Hi I'm trying to put unique number as id using Math.Random() but I'm getting
`Math.Random is not a function`
 I'm assuming that something overwritten it and I can't generate random number

**Comment by justinwiley** [comment]
Incorrect case?  Its Math.random()

**Comment by DavertMik** [comment]
Nothing is overwritten in Math namespace. So I assume `Math.random()` should be used. Google Chrome says the same:

```
ath.random()
0.15620103913504835
Math.Random()
VM140:2 Uncaught TypeError: Math.Random is not a function(…)
```
