### ISSUE TITLE
ENAMETOOLONG issue for attached video files if use Data()

### ISSUE THREAD

**Issue by hatufacci** [Codeception/CodeceptJS#3551]
ENAMETOOLONG issue for attached video files if use Data() in Scenario

in Playwright.js file `.slice(0, 245)` works only for last part of string
bug in line 2984

<img width="1162" alt="Screenshot 2022-12-23 at 15 59 52" src="https://user-images.githubusercontent.com/4963181/209356748-35328e3b-51a5-4dc7-929c-3a35f3c3e5ae.png">

**FIX:**
<img width="1189" alt="Screenshot 2022-12-23 at 16 04 00" src="https://user-images.githubusercontent.com/4963181/209356848-7021bae4-95f9-4ce2-95bb-a8af9b4f0b25.png">

* CodeceptJS version: 3.3.7
* NodeJS Version: v16.14.2
* Operating System: MacOS
* Playwright

**Comment by KaledinaDARIA** [comment]
fix bag: h[ttps://github.com/codeceptjs/CodeceptJS/pull/3552](url)

**Comment by hatufacci** [comment]
https://github.com/codeceptjs/CodeceptJS/pull/3552/files
