### ISSUE TITLE
BootstrapAll & TeardownAll hooks inside plugins for run-multiple

### ISSUE THREAD

**Issue by karanshah-browserstack** [Codeception/CodeceptJS#3554]
#### What are you trying to achieve?
We want to start the server and stop the server via codeceptjs custom plugin but there is not event hook currently available for bootstrapAll and teardownAll methods. 

#### What do you get instead?
No event hook currently exposed resulting in multiple spawning of servers for each child process.

### Details

* CodeceptJS version: 3.3.7
* NodeJS Version: v14.17.2
* Operating System: OS X
* puppeteer || webdriverio || testcafe version (if related) webdriverio
* Configuration file:

Related PR - https://github.com/codeceptjs/CodeceptJS/pull/3487

**Comment by DavertMik** [comment]
There are https://codecept.io/bootstrap/#bootstrapall-teardownall

run-workers is preferred over run-multiple
run-multiple is deprecated
