### ISSUE TITLE
Not able to capture event of multiple.before and multiple.after inside plugins hooks

### ISSUE THREAD

**Issue by karanshah-browserstack** [Codeception/CodeceptJS#3559]
#### What are you trying to achieve?
Want to start and stop server inside plugin based on capablities. We tried to implement a plugin but we couldn't intercept the multiple before hook, we can intercept all before hook correctly but that is not useful to us. 

#### What do you get instead?
No console log printed with the below code.

> Provide test source code if related

```js
  event.dispatcher.on(event.multiple.bootstrapAll, () => {
    console.log('multiple bootstrapAll');
  });
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

**Comment by kobenguyent** [comment]
https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/event.js#L119 I guess currently codeceptjs doesn't support those kinds of events.
