### ISSUE TITLE
Codecept helper returning data

### ISSUE THREAD

**Issue by shamusharkin** [Codeception/CodeceptJS#356]
Hi Guys,

If we resolve a promise with some data from a codecept helper, how do we access the returned data?

Thanks

**Comment by DavertMik** [comment]
By using **generator** and **yield**:
```js
Scenario('so something with data', function*() {
  // ...
  let data = yield I.getDataFromHelper();
});
```

**Comment by jhartma** [comment]
I may oversee something, but I can't get it to work. My helper waits for an email and returns  a promise
```js
return new Promise((resolve) => {
  mailListener.on("mail", (mail) => resolve(getUrlFromText(mail)))
})
```
and inside the test file I have
```js
Scenario("I signup", function* (I) {
  ...
  let url = yield I.clickEmailVerificationLink()
  I.amOnPage(url)
})
```
However, the url, even though resolved correctly inside the promise, returns undefined.

**Comment by DavertMik** [comment]
@jhartma I don't see any errors in your code. Everything looks ok.

Here is `wait` implementation from Nighmare helper:

```js
  wait(sec) {
    return new Promise(function (done) {
      setTimeout(done, sec * 1000);
    });
  }
```

could you try to console log all intermediate results?

**Comment by jhartma** [comment]
@DavertMik thanks for the quick response.

the helper return promise is logging the fetched url
```js
 return new Promise((resolve) => {
  mailListener.on("mail", (mail) => {
    const url = getUrlFromText(mail)
    console.log(url)
    resolve(url)
  })
})
```
This is the test
```js
Scenario("I signup @dev", function* (I) {
  I.fillField(".input-username", "username")
  I.fillField(".input-email", "info@info.info")
  I.fillField(".input-password1", "password")
  I.fillField(".input-password2", "password")
  I.click(".button-create-account")
  I.wait(1)
  let url = yield I.clickEmailVerificationLink()
  console.log("Url", url)
  I.amOnPage(url)
```

And this is the output
```bash
Signup Page --
 I signup @dev
 • I fill field ".input-username", "username"
http://localhost:3000/confirm-account/305e31d68ef744feacf978cb002236ede2aede8e
 • I fill field ".input-email", "info@info.info"
 • I fill field ".input-password1", "password"
 • I fill field ".input-password2", "password"
 • I click ".button-create-account"
 • I wait 1
Url undefined
 ✖ FAILED in 5399ms

```

**Comment by jhartma** [comment]
It's a bit funny, the grab helpers return the data just fine, but no matter what I try in my custom helpers, even simple Promises such as 
```js
return new Promise((done) => done(4))
```
always returns undefined

**Comment by c0bra** [comment]
@jhartma did you ever figure this out?

**Comment by jhartma** [comment]
yes, it was a really stupid error. The code was sitting in a step_file instead of a helper file
