### ISSUE TITLE
Fill Field Not working as expected  in playwright  (React FrameWork)

### ISSUE THREAD

**Issue by purushothaman-source** [Codeception/CodeceptJS#3561]
#### What are you trying to achieve?

Trying to insert text in input using fillField..

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

![Screenshot from 2023-01-04 12-29-37](https://user-images.githubusercontent.com/72643364/210500937-c6b5cd36-cc2e-4a80-ae44-310aefa32429.png)

![Screenshot from 2023-01-04 12-33-23](https://user-images.githubusercontent.com/72643364/210501378-32a58a82-8240-4719-9b95-ebcb165aedb3.png)

### Details

* CodeceptJS version: ^3.0.2
* NodeJS Version:  12
* Operating System: linux
* playwright version (if related)  ^1.9.2
* Configuration file:

Note : There is no logic in Ui to filter the char 
I tried adding logs directyly in onChange event handler 

```js
onChange = (e) => log(e.target.value)
```
it seems the fillField is not pasting the text at once 

Im getting logs like these 

{"value": "stagi"}

{"value": "stagig rele"}

{"value": "stagi"}

{"value": "stagig rel"}

{"value": "stagig releas"}

{"value": "st"}

{"value": "stagig relea"}

{"value": "stagig re"}

{"value": "stagig release"}

**Comment by purushothaman-source** [comment]
someone reported this already in comment https://github.com/codeceptjs/CodeceptJS/issues/499#issuecomment-453842368

**Comment by wancup** [comment]
I have the same issue.
Maybe, relates to React 18's hydrateRoot?
In my case, If I try to change using `hydrate` to `hydrateRoot`, my tests will be failing.

Versions:
* react: 18.2.0,
* react-dom: 18.2.0,
* codeceptjs: 3.3.7,
* playwright: 1.29.2,
* Node.js: v16.18.0

**Comment by purushothaman-source** [comment]
Note : After upgrading react package to 18 ..It is happening very frequently

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
