### ISSUE TITLE
How to get the total test execution stats like passed/failed etc

### ISSUE THREAD

**Issue by myrepojuly** [Codeception/CodeceptJS#3585]
#### What are you trying to achieve?

How to get the total test execution stats like passed/failed etc?

I am aware that I can count with the listeners Paased/Failed events. But if we run it in multiple workers, how to maintain this count?

I see the `./node_modules/codeceptjs/lib/cli.js` has the `results` function. I am just curios to know how to pass the constructors to CLI class to get the results (the mocha Base class stats)

Any help would be really great. Is there a way you can expose the test results stats so that we can make use of? 

Also, I see `event.all.result`, but this listener doesn't show anything related to the reports

#### What do you get instead?

Unable to get the test stats.

### Details

* CodeceptJS version: 3.3.7
* NodeJS Version:
* Operating System: MacOS
* puppeteer || webdriverio || testcafe version (if related) - Any
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
One possibility is extracting data from allure reports.

**Comment by myrepojuly** [comment]
Awesome..Thank you...I can get it as well from the mocha xml reports. Thank you so much @PeterNgTr
