### ISSUE TITLE
@codeceptjs\allure-legacy is throwing error with latest release

### ISSUE THREAD

**Issue by myrepojuly** [Codeception/CodeceptJS#3586]
#### What are you trying to achieve?

Test scenarios with @codeceptjs\allure-legacy plugin

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
ReferenceError: ansiRegExp is not defined
    at EventEmitter.<anonymous> (\node_modules\@codeceptjs\allure-legacy\index.js:259:31)
    at EventEmitter.emit (node:events:525:35)
    at EventEmitter.emit (node:domain:489:12)
    at Object.emit (\node_modules\codeceptjs\lib\event.js:145:28)
    at \node_modules\codeceptjs\lib\actor.js:132:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: latest
* NodeJS Version:
* Operating System: windows and macos
* puppeteer || webdriverio || testcafe version (if related): all
* Configuration file:

```js
# paste config here
```

**Comment by myrepojuly** [comment]
@DavertMik @PeterNgTr  Could you please address the above. Temporarily for my project I resolved by creating a custom plugin. Could you pls fix this plugin?

**Comment by kobenguyent** [comment]
thanks @myrepojuly1987 for reporting the issue!
