### ISSUE TITLE
CodeceptJs v3.4.0 it doesn't retern when failing in Before hook

### ISSUE THREAD

**Issue by MhdAlkhalil** [Codeception/CodeceptJS#3592]
#### What are you trying to achieve?
I just updated to v3.4.0 so I can use "Retry Before". However, it's not returning when Before hook fails

#### What do you get instead?
It's not returning in console.

### Details

* CodeceptJS version: 3.4.0
* NodeJS Version: v14.16.0
* Operating System: Windows
* Configuration file:

**Comment by DavertMik** [comment]
what do you mean by not returning? 

could you provide more details on your case?

**Comment by MhdAlkh** [comment]
Case:
To make it simple and isolated issue. 
I'm just running one feature file which has Before hook and one scenario.
Setup in Before hook is failing even after retry

Expected:
Marking the test case as failed and generate reports if any used.

Actual:
After setup fails, no information is console is shown. And console hangs. and the only way to end running is by force stop the console.

**Comment by MhdAlkh** [comment]
To regenerate the issue, just start new project from scratch.
I used Typescript with chromium.
And write one feature file with Before hook and a scenario where setup in Before hook fails.
Then run it.

**Comment by DavertMik** [comment]
sorry, that won't help me reproduce the issue

without a code sample, I can't help

could you paste a code of a test you are working on or create a repo with a reproducible example

**Comment by MhdAlkh** [comment]
Okay please check this repo https://github.com/MhdAlkh/BeforeHookIssue

**Comment by DavertMik** [comment]
Thanks, checking!

**Comment by DavertMik** [comment]
Thanks for a reproducable example
I worked on retries of before so long that forgot the case that Before could actually fail :smile: 
Updated this and released 3.4.1

**Comment by MhdAlkh** [comment]
Amazing, Thanks a lot for the prompt response 💯

**Comment by seganfredo-vini** [comment]
This issue doesn't seem to be resolved (at least not 100%), we started getting a lot of stuck builds on Jenkins after we updated CodeceptJS to version 3.4.1.
