### ISSUE TITLE
Execute Tests in Parallel across multiple browsers with run-workers

### ISSUE THREAD

**Issue by karanshah-browserstack** [Codeception/CodeceptJS#3597]
#### What are you trying to achieve?
What is the recommended way for executing Tests in Parallel across multiple browsers with run-workers.

Currently, we don’t have an inbuilt support for running the tests across multiple browsers with a run-workers setup. We have to create a custom runner and manually listen to codeceptJS events for reporting.
Is this approach the only recommendation from your side? Is it possible to have a built-in capability to do this similar to what we had in run-multiple?

Happy to contribute by giving the PR to the team too. 

Would be great if we can get access to the slack channel for further discussions / schedule a 30 mins call to understand the requirement and figure the best way forward.

**Comment by DavertMik** [comment]
Sure, here is out slack https://bit.ly/codeceptjs-slack

It was moved out of the core because of the configuration's complexity.
If you provide a simple & flexible config pattern to handle most of parallel run cases, it will be possible to get this functionality back.

But at this moment I don't have this format in my mind

**Comment by karanshah-browserstack** [comment]
@DavertMik Have tried to contribute via https://github.com/codeceptjs/CodeceptJS/pull/3606. Happy to discuss if you have other solutions in mind too. You can share your input and we can work on it.
The major issue is with grid providers like BrowserStack, if users want to run their tests in parallel on multiple browsers, each user will need to create a new js file to configure multiple browsers.
