### ISSUE TITLE
I.see(), I.seeElement() has undefined with Codeceptjs 3.4.1 when set error into Allure

### ISSUE THREAD

**Issue by hatufacci** [Codeception/CodeceptJS#3599]
I.see(), I.seeElement() has undefined with Codeceptjs 3.4.1 when set error into Allure

I.use:
`I.see("Successfully Suspended Account");`

<img width="345" alt="Screenshot 2023-02-21 at 12 47 17" src="https://user-images.githubusercontent.com/4963181/220338792-a0dcdc7c-42a6-4e32-adf4-5eb937f058f6.png">
<img width="767" alt="Screenshot 2023-02-21 at 12 43 25" src="https://user-images.githubusercontent.com/4963181/220338823-2441eb7c-dcde-487b-a76f-050fd99acd79.png">

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: v18.14.0
* Operating System: Ubuntu 20.04.5 LTS
* Playwright 
* Configuration file:
```
helpers: {
    Playwright: {
      url: process.env.FUNCTIONS_APP_URL,
      show: false,
      restart: true,
      video: true,
      trace: false,
      browser: "chromium",
      windowSize: "1440x900",
      waitForNavigation: "networkidle",
      waitForTimeout: 40000,
      acceptDownloads: true,
      timeout: 20000,
    },
}
```

**Comment by mirao** [comment]
I tried this TS test
```typescript
Feature('My');

const {I} = inject();

Scenario('test something',  ({ I }) => {
    I.amOnPage("/");
    I.seeElement(".animuk")
});
```
with this TS config:
```typescript
export const config: CodeceptJS.MainConfig = {
  tests: './*_test.ts',
  output: './output',
  helpers: {
    Playwright: {
      url: 'https://codecept.io/',
      show: true,
      browser: 'chromium',
      waitForNavigation: "networkidle",
      waitForTimeout: 40000,
      timeout: 20000,
    }
  },
  name: 'tmp'
}
```
and I'm getting the same result with CodeceptJS 3.3.7 and 3.4.1.

There is a few sec waiting unless `I.seeElement(".animuk")` fails (it fails as expected because the element is not found). The dealy seems to be handled by Playwright.

```bash
codeceptjs run --debug|ts
Feb 21 13:57:47     I see element ".animuk"
Feb 21 13:57:51  › <screenshotOnFail> Test failed, try to save a screenshot
Feb 21 13:57:51  › Screenshot is saving to /home/mirao/tmp/output/test_something.failed.png
Feb 21 13:57:52   ✖ FAILED in 7145ms
Feb 21 13:57:52 
Feb 21 13:57:52 
Feb 21 13:57:52 -- FAILURES:
Feb 21 13:57:52 
Feb 21 13:57:52   1) My
Feb 21 13:57:52        test something:
Feb 21 13:57:52 
Feb 21 13:57:52       expected visible elements '[]' not to be empty
Feb 21 13:57:52       + expected - actual
Feb 21 13:57:52 
Feb 21 13:57:52 
Feb 21 13:57:52   
Feb 21 13:57:52   
Feb 21 13:57:52   Scenario Steps:
Feb 21 13:57:52   - I.seeElement(".animuk") at Test.<anonymous> (./My_test.ts:7:7)
Feb 21 13:57:52   - I.amOnPage("/") at Test.<anonymous> (./My_test.ts:6:7)
Feb 21 13:57:52   
Feb 21 13:57:52   Artifacts:
Feb 21 13:57:52   - screenshot: /home/mirao/tmp/output/test_something.failed.png
Feb 21 13:57:52 
Feb 21 13:57:52 
Feb 21 13:57:52   FAIL  | 0 passed, 1 failed   // 8s
```
If I use `I.waitForElement()` it waits for 40 sec unless the step fails :heavy_check_mark: 
I also checked `I.seeElement(".hero")` that succeeds immediately because the element exist :heavy_check_mark: .

Maybe you have a specific scenario when `I.seeElement()` doesn't work well?

**Comment by hatufacci** [comment]
@mirao ok i could confirm that it just an allure issue :( after moving it to @codeceptjs/allure-legacy, somehow I.see methods set undefined to it

**Comment by kobenguyent** [comment]
I'm using 3.3.7 and observed the same thing, so perhaps it is there for a long time.

**Comment by hatufacci** [comment]
weird i bumped into it with  3.4.1 only. in 3.3.7 it was no undefined in allure

**Comment by DavertMik** [comment]
yes, sorry, Allure won't be supported from my side
so I can't help here
