### ISSUE TITLE
RetryFailedStep doesn't work with Retry, that was add in 3.4.1

### ISSUE THREAD

**Issue by hatufacci** [Codeception/CodeceptJS#3600]
Playwright use auto-waiting before start actions with elements https://playwright.dev/docs/actionability

It seems that this auto-waiting doesn't work in CodeceptJS version: 3.4.1

* CodeceptJS version: 3.4.1
* NodeJS Version: v18.14.0
* Operating System: Ubuntu 20.04.5 LTS
* Playwright
* Configuration file:

```js
helpers: {
    Playwright: {
      url: process.env.FUNCTIONS_APP_URL,
      show: false,
      restart: true,
      video: true,
      trace: true,
      browser: "chromium",
      windowSize: "1440x900",
      waitForNavigation: "networkidle",
      waitForTimeout: 40000,
      timeout: 10000,
    },
}
```

**Comment by hatufacci** [comment]
there is no problem with "codeceptjs": "3.3.7",

**Comment by Nikoms** [comment]
Which `playwright` version are you using? I had the same problem than you with `3.4.1` and `playwright:1.13` so I rolled back

**Comment by hatufacci** [comment]
i don't think it depends on playwright version  `"playwright": "1.30.0",`

**Comment by Nikoms** [comment]
Me neither, but it's always good to know :)

**Comment by hatufacci** [comment]
@Nikoms do you use retryFailedStep plugin? :) i guess it's reason))))

**Comment by hatufacci** [comment]
the reason is that retryFailedStep not works properly in 3.4.1 
<img width="1220" alt="Screenshot 2023-02-22 at 12 38 45" src="https://user-images.githubusercontent.com/4963181/220614186-d88f39c3-674e-49b9-9fd6-05fcde2ebfe4.png">
<img width="1052" alt="Screenshot 2023-02-22 at 12 39 23" src="https://user-images.githubusercontent.com/4963181/220614226-8051e468-86e4-44d3-920d-79ec8b35d286.png">
than retryFailedStep must work!!!! and we go to 
<img width="1291" alt="Screenshot 2023-02-22 at 12 59 45" src="https://user-images.githubusercontent.com/4963181/220614330-7b80513d-04fc-4632-882f-586bd491497d.png">
but in 3.4.1 we  throw new ElementNotFound(locator, prefix, suffix); and that's it

**Comment by hatufacci** [comment]
After we throw new ElementNotFound we should go to ElementNotFound class
<img width="1015" alt="Screenshot 2023-02-22 at 14 52 15" src="https://user-images.githubusercontent.com/4963181/220640052-4e8017be-9542-4d4f-bf5e-fd04998f9afc.png">

and after that error should be catch by 
`  return Promise.race([promise, Promise.resolve(res).then(fn)]).finally(() => clearTimeout(timer)).catch((err) => {
          for (const retryObj of retryRules) {
            if (!retryObj.when) return retry(err);
            if (retryObj.when && retryObj.when(err)) return retry(err);
          }
          throw err;`

but it doesn't
<img width="1120" alt="Screenshot 2023-02-22 at 14 51 28" src="https://user-images.githubusercontent.com/4963181/220640474-0de6dd74-88c9-40f2-9194-ff85877b9b9d.png">

**Comment by Nikoms** [comment]
Yes, we use the `retryFailedStep`, good catch 🚀

**Comment by StanislavGrishaev** [comment]
same issue here, rollback to version `3.3.7` helped

**Comment by hatufacci** [comment]
It still the issue in 3.5.2 version :( @DavertMik could you please take a look on it? 
3.3.7
<img width="1012" alt="Screenshot 2023-07-14 at 13 54 48" src="https://github.com/codeceptjs/CodeceptJS/assets/4963181/c9d46382-1cb9-461c-b027-09b775f48e3a">
3.5.2
<img width="813" alt="Screenshot 2023-07-14 at 13 48 51" src="https://github.com/codeceptjs/CodeceptJS/assets/4963181/1448ae87-adf9-40fa-afb1-18385f4c2b8f">

**Comment by hatufacci** [comment]
@Nikoms @StasGrishaevTutu  could you please check your config file ? do you have allure: { } plugin in it ?

**Comment by StanislavGrishaev** [comment]
> @Nikoms @StasGrishaevTutu could you please check your config file ? do you have allure: { } plugin in it ?

hi there, in fact, I migrated from CodeceptJS to pure Playwright, so I can’t tell you anymore, unfortunately, sorry :)

**Comment by Nikoms** [comment]
Same here, sorry...

**Comment by hatufacci** [comment]
@DavertMik ok i reproduced the issue:
the issue is reproducible when use 
`retry: {
    BeforeSuite: 3,
    Before: 3,
    After: 3,
    AfterSuite: 3,
  },`
and 
` retryFailedStep: {
      retries: 3,
      defaultIgnoredSteps: [ 'amOnPage', 'wait*', 'send*', 'execute*', 'run*', 'have*' ],
      factor: 1.5,
      ignoredSteps: [ 'amOnPage', 'wait*', 'send*', 'execute*', 'run*', 'have*' ],
      enabled: true,
    },`

if use Before() - you could reproduce the issue.

**Comment by DavertMik** [comment]
Thank you for reporting this issue and thanks to @kobenguyent for the quick fix
