### ISSUE TITLE
I want to check the whether checkbox is selected or not, if checkbox is not selected means I need to select the checkbox

### ISSUE THREAD

**Issue by s-sugumar** [Codeception/CodeceptJS#3608]
I want to check the whether checkbox is selected or not, if checkbox is not selected means I need to select the checkbox

I'm using playwright

async verifyCheckBoxIsCheckedOrNot(){
      let checkBoxIsChecked = await I.grabValueFrom('//input[@id="config0"]');
      if(checkBoxIsChecked==='false'){
            I.click('//label[@for="config0"]');
            I.seeCheckboxIsChecked('//label[@for="config0"]');
        }
        else
        I.seeCheckboxIsChecked('//label[@for="config0"]');
     }
}

**Comment by incoming-th** [comment]
No sure if that helps, but looking at this it means that either the element is checked or not you want it to be checked.

In that case I will not bother to check anything and just use checkOption to always have it checked.

**Comment by s-sugumar** [comment]
it's working fine
