### ISSUE TITLE
Announce new allure integration in Readme?

### ISSUE THREAD

**Issue by vovsemenv** [Codeception/CodeceptJS#3609]
We just released new allure2 based integration with allure framework. I guess it will be good to note in readme that now it should be required from `allure-codeceptjs`
https://www.npmjs.com/package/allure-codeceptjs

**Comment by kobenguyent** [comment]
I think this could be added here 

https://github.com/codeceptjs/CodeceptJS/wiki/Community-Helpers-&-Plugins
