### ISSUE TITLE
[Playwright][_failed(test)|_passed(test) hooks] Video\Traces storage works asynchronously

### ISSUE THREAD

**Issue by ua1wcz** [Codeception/CodeceptJS#3614]
#### What are you trying to achieve?
Retrieve the playback video\traces file after the crash and save it to the allure report.

#### What do you get instead?
File not found error. It's because is temporary file is not closed (and continues to record) and has not renamed the name, mentioned in the test.artifacts.video\trace.  The same is true when using [multiple sessions](https://codecept.io/acceptance/#multiple-sessions). And it's infinite until _failed method is not complete, same with the _after() method. 
And it's only with the video, with playwright traces all ok.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, try to save a screenshot
    [1] <teardown> Error | Error: ENOENT: no such file or directory, open '/Users/John/Repo/john-tests/output/videos/1678350108668_Login_to_console_directly_@smoke_@C19362.failed.webm'
Error: ENOENT: no such file or directory, open '/Users/John/Repo/john-tests/output/videos/1678350108668_Login_to_console_directly_@smoke_@C19362.failed.webm'
  ✖ FAILED in 47948ms

    [2]  Starting recording promises

-- FAILURES:

  1) Open Admin Console @admin_console @login @regression
```

> Provide test source code if related

```js
_failed(test) {
    const allure = container.plugins('allure');
    const videoBuffer = fs.readFileSync(test.artifacts.video);
    allure.addAttachment('Videos', videoBuffer, 'video/webm');
  }
```

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: v19.4.0
* Operating System: MacOs Ventura
* playwright: 1.31.2
* Configuration file:

```js
exports.config = {
  tests: 'tests/*test.js',
  output: './output',
  helpers: {
    Playwright: {
      url: 'http://localhost',
      waitForTimeout: 10000,
      show: false,
      browser: getBrowserType(browserName),
      waitForNavigation: "networkidle0",
      ...(whenChromium ? { chromium: chromiumChannel } : {}),
      keepTraceForPassedTests: true,
      trace: true, 
      video: true
    },
    REST: {
      endpoint: process.env.ADMIN_PORTAL_API_URL + "/api",
      "resetHeaders": true
    },
    SetupBlocks: {
      require: './tests/helpers/base.helper.js'
	  },
    AllureHelper: {
      require: "./tests/helpers/allure.helper.js",
    }
  },
```

**Comment by kobenguyent** [comment]
hey @ua1wcz I think we should wait for the browser context to be closed. Something like this

````
    if (video) {
      await Playwright.browserContext.close();
      const FORMAT = "video/webm";
      const TITLE = "Execution Video";
      AllureHelper.addAllureAttachment(TITLE, fs.readFileSync(video), FORMAT);
    }
````

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
