### ISSUE TITLE
CodeceptJS cannot work with more than one GraphQL servers

### ISSUE THREAD

**Issue by lewis-munene** [Codeception/CodeceptJS#3626]
#### What are you trying to achieve?
I'm trying to send queries to multiple GraphQL servers and therefore I have more than one endpoints for my GraphQL config. CodeceptJS does not give me a way to set the url for a GraphQL request at runtime, and neither can I set more than one base urls in the GraphQL Helper configs.

#### What do you get instead?
When I follow [this example](https://codecept.io/helpers/GraphQL/#access-from-helpers), 
```Typescript
this.helpers['GraphQL']._executeQuery({
   url,
   data,
});
```
I get this error:
```Typescript
Cannot convert undefined or null to object
      at Function.assign (<anonymous>)
      at GraphQL._executeQuery (D:\...\node_modules\.pnpm\codeceptjs@3.4.1\node_modules\codeceptjs\lib\helper\GraphQL.js:80:30)
      at GraphQLExtension.sendElideQuery (GraphQLExtension.ts:16:28)
      at Step.run (D:\...\node_modules\.pnpm\codeceptjs@3.4.1\node_modules\codeceptjs\lib\step.js:122:47)
      at D:\...\node_modules\.pnpm\codeceptjs@3.4.1\node_modules\codeceptjs\lib\actor.js:135:23
```
I have also tried different ways to call that `_execureQuery()` function but none works.
See below:
```Typescript
this.helpers['GraphQL']._executeQuery({
   url: "http://...",
   data: {...},
});

GraphQL._executeQuery({
   url: "http://...",
   data: {...},
});
```
I've also tried extending the GraphQL helper to see if I can modify the `endpoint` at runtime. Still doesn't work.

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: v18.15.0
* Operating System: Windows 11
* Configuration file:

```Typescript
export const config: CodeceptJS.MainConfig = {
  tests: './*_test.ts',
  output: './tests/output',
  helpers: {
    Playwright: {
      url: 'http://localhost',
      show: false,
      browser: 'chromium'
    },
    GraphQL: {
      endpoint: () => {
        let project;
        codeceptjs.container.append({
        support: { project }
      })},
      endpoint2: 'http://...',
      onRequest: (request) => {
        request.headers.auth = '123';
      }
    },
    GraphQLExtension: {
      require: './GraphQLExtension.ts',
    },
  },
  gherkin: {
    features: ["./tests/**/features/*.feature"],
    steps: "./tests/**/step_definitions/*.ts"
  },
  include: {
    I: './steps_file'
  },
  name: 'ibs'
}

```

**Comment by kobenguyent** [comment]
looks like you bring too much complex here:
- the endpoint2 is not actually supported when codeceptjs parses the graphql config.
- you are trying to access the container in the codeceptjs config which I believe it's not possible as the codeceptjs container is not yet created at this time.

**Comment by lewis-munene** [comment]
Thanks @kobenguyent. I managed to work around this using the REST helper instead. I suppose the GraphQL helper requires that you only work with one GraphQL server, which is true in most cases, but in some cases, you might need to have multiple servers. We just have to accept this limitation
I suppose we can close this issue
