### ISSUE TITLE
run-multiple will still work but it is considered deprecated and won't be supported

### ISSUE THREAD

**Issue by houssem-lab** [Codeception/CodeceptJS#3631]
Hello, 

We are working on the implementation of parallel test execution. we use Gherkin to write our tests, and it is about running our .feature test files in parallel.
It is indicated that the "run-multiple" option is still functional but deprecated. Is there an alternative option that replaces the deprecated one? https://codecept.io/wiki/Upgrading-to-CodeceptJS-3.html#_5%EF%B8%8F%E2%83%A3-improved-parallel-execution-with-workers

Thank you in advance for your answer.

Best regards,

**Comment by kobenguyent** [comment]
Please try run-workers -> https://codecept.io/parallel/#parallel-execution-by-workers
