### ISSUE TITLE
tryTo plugin not working correctly with ReportPortal plugin

### ISSUE THREAD

**Issue by JoJo2112** [Codeception/CodeceptJS#3632]
Hello everyone,

When using the tryTo plugin (https://codecept.io/plugins/#tryto) and a step is failing, this is not correctly reported with the ReportPortal Agent (https://github.com/reportportal/agent-js-codecept/).

Basically every step failing inside a tryTo block is shown as "In progress" in the ReportPortal.

I already spend some hours on this and it seems that the tryTo plugin is interrupting the global promise chain before reporting to the portal is done, but im not entirely sure about that. So i basically think (and tested) reporting is queued but never executed.

Did someone experience this issue and solve it somehow? Hacks are also greatly appreciated.

Thanks

**Comment by kobenguyent** [comment]
I'm not sure if the lib you're using is adapted with current changes of codeceptjs 3.5.10.

I'm using this https://www.npmjs.com/package/codeceptjs-rphelper looks good for me.
