### ISSUE TITLE
[object object] in see method

### ISSUE THREAD

**Issue by rebajz** [Codeception/CodeceptJS#3644]
test:
Feature('sandbox demo test');

Scenario('first it', async ({ I }) => {
  I.see('not exist text', {xpath: '//banner-pane'})
});

in console:
-- FAILURES:

  1) sandbox demo test
       first it:
     expected element [object Object] to include "not exist text"

  Scenario Steps:
  - I.see("not exist text", {"xpath":"//banner-pane"}) at Test.<anonymous> (.\tests\sandbox_test.ts:6:5)

correct message:
expected element xpath: '//banner-pane' to include "not exist text"

**Comment by kobenguyent** [comment]
please run `npx codeceptjs info` to provide more info

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
