### ISSUE TITLE
Before() failures don't trigger After() functions

### ISSUE THREAD

**Issue by sethvanwykJET** [Codeception/CodeceptJS#3645]
#### What are you trying to achieve?

Tests to retry gracefully after failing in before step

#### What do you get instead?

Tests failing inside the Before() step aren't triggering the After() conditions.

What I see in the allure report is that when a test fails in the Before() stage, it just tries to initiate the before again without triggering the after conditions to reset the state.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/129372181/233651173-f784b2d7-36b7-437b-aa07-a2a67def596c.png">

> Provide test source code if related

```js
Before(async () => {
  await I.startHAR();
  await I.checkResponseFromStatusEndpoint();

  await I.accessURL(await urlMother.homePageUrl(domain));
  await tryTo(() => footer.acceptCookies());

  I.waitForElement(subpageHeader.personalInfoHeaderText, 20);
});

Scenario('should be able to update newsletter preferences', async () => {
  Test data here
})

After(async () => {
  await I.stopHAR();
});
```

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: 16
* Operating System: 
* puppeteer
* Configuration file:

```js
  retry: {
    Feature: process.env.E2E_TEST_RETRIES,
    Scenario: process.env.E2E_TEST_RETRIES,
    Before: process.env.E2E_TEST_RETRIES,
    After: process.env.E2E_TEST_RETRIES,
  }
```

## Comment

Is my configuration wrong on the retries for the Before / After?

Does it need to function differently for when the part of the test inside before fails?

**Comment by DavertMik** [comment]
This is very philosophical question

We don't know at what point Before failed. What if it fails before `startHAR` is finished, would we need stopHAR in this case? 

I would recommend you to use Custom Helper for this case
Helpers will execute no matter what on corresponding hooks
