### ISSUE TITLE
Update xml2js to 0.5.0 version

### ISSUE THREAD

**Issue by ua1wcz** [Codeception/CodeceptJS#3651]
Need to update a xml2js to 0.5.9 version, cause it is vulnerable to prototype pollution  - https://github.com/advisories/GHSA-776f-qx25-q3cc

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: 16

**Comment by kobenguyent** [comment]
Closed as done! -> https://github.com/codeceptjs/CodeceptJS/blob/3.x/package.json#L147
