### ISSUE TITLE
GrabTextFrom unable to return text in <script> tag

### ISSUE THREAD

**Issue by shubhraj** [Codeception/CodeceptJS#3659]
#### What are you trying to achieve?
I am trying to pull JSON+LD data which is embedded in web page 
sample : 
```
<script>
{"@context":"https://schema.org"}
</script>
```

`I.grabTextFrom(selector) -> this return an empty string`

after doing some research I feel 
grabTextFrom internally uses :  `this.browser.getElementText`

link : https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/WebDriver.js#L1156 

and getElementText is able to return rendered text
link : https://w3c.github.io/webdriver/#dfn-get-element-text 

if we compare it with nightmare which uses `evaluate()` (which works perfectly for this case) can we use something like that with webDriver ?

link : https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Nightmare.js#L785

#### What do you get instead?
I am getting empty string

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 
* NodeJS Version: v14
* Operating System: MAC OS Montery
* puppeteer || webdriverio || testcafe version (if related) : WebDriverIO
* Configuration file:

```js
# paste config here
```

**Comment by DavertMik** [comment]
I don't think that `script` contains text. So I think current behavior is fine

WebDriver follows standards while Nightmare uses custom JS implementation so behavior would be different

But I prefer to stick with WebDriver strategy
In your case I would recommend using `grabHTMLFrom`
