### ISSUE TITLE
Test result (number of passed and failed) is not correctly displayed when running the tests with run-workers and reporter

### ISSUE THREAD

**Issue by jlcityofglass** [Codeception/CodeceptJS#3664]
#### What are you trying to achieve?
codeceptjs run-workers 2 --reporter mocha-multi

#### What do you get instead?
The test results are not displayed properly
![run-worker-incorrect-result](https://github.com/codeceptjs/CodeceptJS/assets/11569483/42411487-3550-4c5c-951f-92aa12a34e5c)

> Provide console output if related. Use `--verbose` mode for more details.

```bash
root@b9725ac0b4df:/tests# codeceptjs run-workers 2 --reporter mocha-multi
CodeceptJS v3.4.1 #StandWithUkraine
Running tests in 2 workers...

[codecept.conf.js] OUTPUT DIRECTORY: ./output/2023-05-12/1683917217
creating output directory: /tests/output/2023-05-12/1683917217
[02]   ✔ test 2 in 29340ms
[01]   ✔ test 1 in 29938ms

  OK  | 0 passed   // 2m
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: 16.8.1
* Operating System: Docker image codeceptjs/codeceptjs:sha-fe5d327
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
  mocha: {
    "reporterOptions": {
      "codeceptjs-cli-reporter": {
        "stdout": '-',
        "options": {
          "verbose": true
        }
      },
      "mochawesome": {
        "stdout": `${outputDir}/console.log`,
        "options": {
          "reportDir": outputDir,
          "overwrite": false,
          "reportTitle": 'automation',
          "reportFilename": 'automation_test_report'
        }
      },
      "mocha-junit-reporter": {
        "stdout": '-',
        "options": {
          "mochaFile": `${outputDir}/result.[hash].xml`,
          "outputs": true,
          "testsuitesTitle": 'automation Suite',
          "attachments": true
        },
        "attachments": true 
      }  
    }
  },
```

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
