### ISSUE TITLE
[FEATURE REQUEST] add Dependabot with weekly interval

### ISSUE THREAD

**Issue by EgorBodnar** [Codeception/CodeceptJS#3670]
#### What are you trying to achieve?

`Dependabot` will automatically update the project's dependencies, enhancing security and saving your manual work.

in the current situation, many dependencies become obsolete, vulnerabilities open up. Tracking with your hands is too expensive. Should be automated.

**Comment by tungbq** [comment]
I've proposed new PR for this task in #3689 
Also along with the code updates, we need to change the repo setting to enable by following this [document](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#enabling-or-disabling-dependabot-security-updates-for-an-individual-repository) 
![image](https://github.com/codeceptjs/CodeceptJS/assets/85242618/d66e80df-5b2f-4a95-b6b4-ecc9c887b498)
I don't have the admin right on this repo to change the setting so will need to need help from the admin guys for this step. Thanks
