### ISSUE TITLE
Save cookie between Scenario

### ISSUE THREAD

**Issue by kerstvo** [Codeception/CodeceptJS#374]
I want to save cookie between scenarios (to save some time). Before I used webdriverio ```restart: false``` option, but now it doesn't work (that is strange, because it definitely worked before...)

**Comment by nairvijays99** [comment]
Agree. If you want to clear cookies b/w scenario, authors can do it using I.clearCookies(). But, there is no other way round.

**Comment by DavertMik** [comment]
> Before I used webdriverio restart: false option, but now it doesn't work (that is strange, because it definitely worked before...)

Nope, `restart: false` should clear cookies but keep the browser session to ensure tests are isolated.
You can write a helper to save/restore cookies:

```js
_before() {
  // restore cookies
}

saveCookies() {
  // save cookies
}
```

Something like that. Or you can combine that with login:

```js
login() {
  if (this.session) {
    I.setCookie({name: 'session', value: this.session});
    return;
  }

  I.fillField()...
  I.fillField()...
  I.click()...

  this.session = I.grabCookie('session'); // or smth like that
}
```

In this example I'm saving a specific cookie after the login and restoring it next time without the login.
But yes, this can be somehow implemented inside the framework itself

**Comment by nairvijays99** [comment]
It can be config driven. Something like clearCookiesBetweenSessions:false.

**Comment by DavertMik** [comment]
Yes, it can. If you have some time you can send a PR implementing this feature.

**Comment by nairvijays99** [comment]
Sure.

**Comment by DavertMik** [comment]
`keepCookies` option added to all helpers. Use it with `restart: false` in 0.4.16
