### ISSUE TITLE
Playwright chrome extension does not work

### ISSUE THREAD

**Issue by HaruhikoKubo** [Codeception/CodeceptJS#3740]
#### What are you trying to achieve?

From this help document, https://codecept.io/helpers/Playwright/#example-5-testing-with-chromium-extensions 
I configured chrome extension params in the codecept.conf.js as follows

```
  helpers: {
    Playwright: {
      url: baseUrl,
      show: true,
      trace: true,
      browser: "chromium",
      channel: "chrome",
      userDataDir: "/tmp/playwright-tmp", // necessary to launch the browser in normal mode instead of incognito,
      args: [
        `--disable-extensions-except=${process.env.EXTENSION_PATH}`,
        `--load-extension=${process.env.EXTENSION_PATH}`,
      ],
    },
```

But it didn't work.

Seems original playwright does not support launchPersistentContext in playwright.config file.  https://github.com/microsoft/playwright/issues/11833

 Codecepotjs official help page actually shows its supported https://codecept.io/helpers/Playwright/#example-5-testing-with-chromium-extensions 
But does the codeceptJS config file support it?

#### What do you get instead?
No chrome extension installed

### Details

* CodeceptJS version: 3.5.0
* NodeJS Version: 16.13.1
* Operating System: Mac OS 13.4.1
* Playwright 1.35.1

**Comment by chisatokashima-eizo** [comment]
Hello, I have encountered a similar issue as well.
In my case, I was able to resolve the problem by passing the arguments directly to the browser.
You can try the following code as a reference:
```
  helpers: {
    Playwright: {
      url: baseUrl,
      show: true,
      browser: 'chromium',
      chromium: {
        ignoreDefaultArgs: ['--disable-extensions']
      }
    },
    ...
  }
```

see also https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch

**Comment by HaruhikoKubo** [comment]
Thanks for your prompt reply @chisatokashima-eizo 
The config was wrong,  the following works as expected. hence close this issue 
```  helpers: {
    Playwright: {
      url: baseUrl,
      show: true,
      trace: true,
      browser: "chromium",
      chromium: {
        userDataDir: "/tmp/playwright-tmp", // necessary to launch the browser in normal mode instead of incognito,
        args: [
          `--disable-extensions-except=${process.env.EXTENSION_PATH}`,
          `--load-extension=${process.env.EXTENSION_PATH}`,
        ],
      },
      channel: "chrome",```
