### ISSUE TITLE
switchTo Protractor

### ISSUE THREAD

**Issue by Jeroenhuisjes** [Codeception/CodeceptJS#375]
The Protractor helper has no switchTo function when using the codecept api. 

WebdriverIO has that function. 
Is it poissible to get this function for the Protractor helper in the next version? 

Thanks!

**Comment by BrunoExterckotter** [comment]
Hi,
you can try use a custom helper, some like that:
  switchToIframeCustom() {
    this.helpers['Protractor'].browser.switchTo().frame(element(by.tagName('iframe')).getWebElement());
  }
Works for me.

**Comment by Nazanin1369** [comment]
I'd like to take this over
