### ISSUE TITLE
openAI helper parse error

### ISSUE THREAD

**Issue by cjhille** [Codeception/CodeceptJS#3757]
#### What are you trying to achieve?

Using the 3.5.2. openAI helper with playwright any of the 3 helper methods returns this:

More details by @kobenguyent or in [codeceptjs slack](https://codeceptjs.slack.com/archives/C94G8JXJB/p1689105402616229?thread_ts=1689025289.402409&cid=C94G8JXJB)

```
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_turbo_dist_turbo_es2017-esm_js-1f4793023fcd.js"></script>
<script crossorigin=

    [1] <pause> Error | Error: Parse Error: <script crossorigin=
 ERROR  Parse Error: <script crossorigin=
```

config:
```js
    OpenAI: {
      chunkSize: 8000,
    },
```

**Comment by kobenguyent** [comment]
I think this is resolved by https://github.com/codeceptjs/CodeceptJS/pull/3962
