### ISSUE TITLE
Execution visualization not any more step by step

### ISSUE THREAD

**Issue by tfiwm** [Codeception/CodeceptJS#377]
Hello,

since version 0.4.14 the execution visualization is not any more step by step. The execution is printed immediately and then i can't see anymore at which step the current executor is :(
I liked it really much in the previous versions.

Is this a new Feature or a Bug?
 
### Details

* CodeceptJS version: ^0.4.14
* NodeJS Version:
* Operating System: MacOS
* WebDriverIO
* Configuration file:

**Comment by DavertMik** [comment]
Thanks, looks like a bug. Probably this happened due to updates for _beforeStep and _afterStep hooks.
