### ISSUE TITLE
Mochawesome failed test

### ISSUE THREAD

**Issue by Jeroenhuisjes** [Codeception/CodeceptJS#378]
When a test fails Mochawesome doesn't generate a report.

**Comment by cjhille** [comment]
This seems to be an issue since mochawesome 2.0.0. When I revert back to 1.5.5 it works.

**Comment by Jeroenhuisjes** [comment]
Thanks for the reply! I'll give it try after the weekend :)

**Comment by romanovma** [comment]
Can confirm that mochawesome 1.5.5 generates reports in case of failed tests. 
2.0.3 doesn't.
