### ISSUE TITLE
[Playwright] clicking on overlapped element stuck the execution

### ISSUE THREAD

**Issue by VivekLande** [Codeception/CodeceptJS#3786]
#### What are you trying to achieve?
I am trying to click on an element but an unintended pop-up comes up that overlaps an element, element visibility get true but when click on it, the click action gets stuck with infinite retry.

#### What do you get instead?
the click action gets stuck with infinite retry. It should either timeout the step with failure

> Provide console output if related. Use `--verbose` mode for more details.
  intercepts pointer events
retrying click action, attempt #193
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  
```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: 18+
* Operating System: Windows
* puppeteer
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
