### ISSUE TITLE
Machawesome addContext Helper

### ISSUE THREAD

**Issue by cjhille** [Codeception/CodeceptJS#379]
This is more of a feature request and I'm not sure if it's a good Idea, since it's mochawesome specific.

Mochawesome (^2.0.0) adds a method for adding additional test context to the output, which is incredibly useful for inling links to failed builds and screenshots of failed tests in the report.html. See [pic here](https://raw.githubusercontent.com/adamgruber/mochawesome/e05004f1c0b1bc23575ee26a98bac7180eb3f593/docs/marge-report-1.0.1.png).

In mocha this is done via [this code](https://github.com/adamgruber/mochawesome#adding-test-context):
```javascript
const addContext = require('mochawesome/addContext');

describe('test suite', function () {
  it('should add context', function () {
    // context can be a url and the report will create a link
    addContext(this, 'http://www.url.com/pathname');

    // context can be an image url and the report will show it inline
    addContext(this, 'http://www.url.com/screenshot-maybe.jpg');
    });
  })
});
```

@DavertMik would it make sense to add a mochawsome helper to codeceptJS so can use:
```javascript
I.addContext('http://www.url.com/pathname');
```
or maybe use the addContext function internally to log image and current URL for failed tests automatically once mochawesome has been enabled in config. 
Can either be done easily?

**Comment by DavertMik** [comment]
Thanks, I will think about it.
