### ISSUE TITLE
No option to completely export the full playwright report

### ISSUE THREAD

**Issue by neurolabs** [Codeception/CodeceptJS#3801]
#### What are you trying to achieve?

I want to view the playwright html report in the CI pipeline in order to directly see the traces in the browser without needing to download the zips and executing `yarn run playwright show-trace ...` on the console.

#### What do you get instead?

The option to export videos and traces on their own

### Details

* CodeceptJS version: 3.4.1
* Operating System: Ubuntu 22.04.2 LTS
* Playwright version: 1.36.2
* node version: v18.17.0

**Comment by DavertMik** [comment]
I don't know if this is possible to get HTML out of Playwright as it can be part of playwright/test framework.
We are not planning to implement it but we are welcoming any PRs that improve reporting
