### ISSUE TITLE
CTRL+Z does not kill browsers when using multiples workers

### ISSUE THREAD

**Issue by incoming-th** [Codeception/CodeceptJS#3827]
#### What are you trying to achieve?

Run codeceptjs with workers, then stop it but browsers are not killed.

#### What do you get instead?

When doing CTRL+Z, the browsers should also be killed.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
npx codeceptjs run-workers 2 ./scripts/test.js
```
> Provide test source code if related

```js
Feature('Test');

Scenario('test', async ({I}) => {
	I.amOnPage('https://www.google.com/');
});

Scenario('test2', async ({I}) => {
	I.amOnPage('https://www.google.com/');
});
```

### Details

* CodeceptJS version: 3.5.3
* NodeJS Version: 18.14.1
* Operating System: Ubuntu 20.04
* puppeteer
* Configuration file:

```js
exports.config = {
  tests: './scripts/*.js',
  output: './logs',
  defaultWait: 120,
  helpers: {
    Puppeteer: {
      url: 'http://localhost',
      highlightElement: true,
      show: true,
      restart: true,
      // keepBrowserState: true,
      // keepCookies: true,
      getPageTimeout: 300000,
      waitForAction: 200,
      waitForNavigation: ['domcontentloaded', 'networkidle0'],
      waitForTimeout: 300000,
      windowSize: '1920x1080',
      // defaultViewport: null,
      chrome: {
        // https://peter.sh/experiments/chromium-command-line-switches/
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--window-size=1920,1080'],
        // defaultViewport: null,
        // This line is needed for workers
        executablePath: '/bin/google-chrome',
      },
    }
  },
  plugins: {
    pauseOnFail: {},
    // plugins: {
    //   retryFailedStep: {
    //     enabled: true
    //   }
    // },
    stepTimeout: {
      enabled: true,
      timeout: 120,
      noTimeoutSteps: [
        'amOnPage',
        'screenshot'
      ],
    }
  }
}
```

![image](https://github.com/codeceptjs/CodeceptJS/assets/26375917/b06261e8-b23a-43c4-8ee0-086ea1b11423)

**Comment by incoming-th** [comment]
Just up to make the bot happy as this issue still happens.

**Comment by kobenguyent** [comment]
ctrl+c is used to kill a process. It terminates your program. ctrl+z is used to pause the process. It will not terminate your program, it will keep your program in background

**Comment by incoming-th** [comment]
> ctrl+c is used to kill a process. It terminates your program. ctrl+z is used to pause the process. It will not terminate your program, it will keep your program in background

Thanks, it was a typo in the title and description. As you can see I try **CTRL + C** from the screenshot it's **^C**, but it does not close the browsers when using "**run-workers**", it does close the browser when using "run".

I don't know why but it is easy to reproduce as per first post.

Should I edit or create new issue? Or this is the behavior to not close the browser with CTRL + C when running with workers?

**Comment by kobenguyent** [comment]
> > ctrl+c is used to kill a process. It terminates your program. ctrl+z is used to pause the process. It will not terminate your program, it will keep your program in background
> 
> 
> 
> Thanks, it was a typo in the title and description. As you can see I try **CTRL + C** from the screenshot it's **^C**, but it does not close the browsers when using "**run-workers**", it does close the browser when using "run".
> 
> 
> 
> I don't know why but it is easy to reproduce as per first post.
> 
> 
> 
> Should I edit or create new issue? Or this is the behavior to not close the browser with CTRL + C when running with workers?

CTRL+C works fine for me on MacOs. Maybe it's the OS related?
