### ISSUE TITLE
html-minifier@4.0.0 Regular Expression Denial of Service vulnerability

### ISSUE THREAD

**Issue by sethvanwykJET** [Codeception/CodeceptJS#3829]
#### What are you trying to achieve?

Clean up the codebase security / performance alerts

We recently implemented Snyk and are going through a cleanup process to see where we can tidy up things in the system. Our only outlier seems to be this alert that doesn't seem to be high priority but would be nice to clean up as well.

I do see this package has not been updated in a while, is there a more maintained alternative that can be put in place to address this?

#### What do you see

https://cwe.mitre.org/data/definitions/1333.html

<img width="1456" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/129372181/60c0c344-6973-4b08-81ba-34ca7321f5ed">

### Details

* CodeceptJS version: 3.5.3

**Comment by DavertMik** [comment]
Thanks, this will be fixed in next release by replacing package to html-minifier-terser
