### ISSUE TITLE
Assertion problem

### ISSUE THREAD

**Issue by tfiwm** [Codeception/CodeceptJS#383]
#### What are you trying to achieve?
An assertion but the return value from grabTextFrom is a promise ...
Any idea how to solve it?

#### What do you get instead?

The assertion throws an error because he tries to compare a promise with the expected text

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Promise { 'Altitude It is cool here' }
Altitude It is cool here
error -> Added tweet message is not equal with the created one
```
> Provide test source code if related

```javascript
let tweetText = "It is cool here";
twitterPage.newTwitt(tweetText);
yield twitt2 = I.grabTextFrom(twitterPage.fields.savedTwitt);
console.log(twitt2);
console.log("Altitude ".concat(tweetText));
assert.equal(twitt2, "Altitude ".concat(tweetText), 'Added tweet message is not equal with the created one');
```
### Details

* CodeceptJS version: 0.4.15

**Comment by DavertMik** [comment]
Oh, you almost did it, but not :)

```
twitt2 = yield I.grabTextFrom(twitterPage.fields.savedTwitt);
```

`yield` transforms promise into value

**Comment by tfiwm** [comment]
ARRGH come on...my mistake...THX!
