### ISSUE TITLE
I.dragAndDrop() not working without any error message

### ISSUE THREAD

**Issue by Linger-maker** [Codeception/CodeceptJS#3832]
#### What are you trying to achieve?
Drag and drop element.

#### What do you get instead?
The `I.dragAndDrop() `sometimes worked and sometimes didn't. And when it didn't work,  and it actually didn't fail the test  case and let it go on. But we never saw the expected result (the ApplyButton should be clickable) in the next line. So that was where it failed the test.

P.S. I have checked both the src and dest element were shown on the page by `I.waitForElement()`

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
    I.waitForElement(this.locators.draggedAction, 5);
    I.waitForElement(this.locators.draggedDest, 5);
    I.dragAndDrop(this.locators.draggedAction, actionsListPage.locators.draggedDest);
    I.waitForClickable(this.locators.applyBtn);
```

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: v16.20.1
* Operating System: Mac Apple M1 Max
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
hey @Linger-maker please try with version later than 3.4.1 as it is shipped with version > 3.5.0 https://github.com/codeceptjs/CodeceptJS/commit/cf714ec7d6076082dbe5fa1125bedb6cc03772c1
