### ISSUE TITLE
I.say puts comment onderneath all scenario-actions

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#384]
the i.say - output (the actual comments) are showing underneath all other actions I put in the scenario. Looks like a bug. 

script:
Scenario('Testing MegaMenu Max Viewport', (I, functions, globals) => {
  I.say('test');
  I.resizeWindow('maximize');
  I.amOnPage(globals.url);
  functions.acceptCookie();
  I.say('test');

  I.amOnPage(globals.url);
  I.see('Menu');
  I.saveScreenshot('test.png');
  I.dontSee('Sluiten');
  I.click(globals.Menu_knop);
  I.dontSee('Menu');
  I.see('Sluiten');
  I.saveScreenshot('Open_Menu_Max.png');
  I.click(globals.Sluiten_in_header);
  I.waitForInvisible(globals.Menu,3);
  I.saveScreenshot('Closed_Menu via Sluiten in Navigation-bar Max.png');

  // Test Sluiten in Megamenu
  I.click('Menu');
  I.click(globals.Sluiten_in_menu);
  I.waitForInvisible(globals.Sluiten_in_menu);
  I.saveScreenshot('Closed_Menu via Sluiten in MegaMenu ViewPort Max.png');
});

**Comment by DavertMik** [comment]
#382 is about to fix that. Thanks
