### ISSUE TITLE
[Bug] - The switchTo() throws error when passing the strict locator

### ISSUE THREAD

**Issue by kobenguyent** [Codeception/CodeceptJS#3846]
#### What are you trying to achieve?
The switchTo() accepts the css locator.

#### What do you get instead?
The switchTo() throws error when passing the css locator

```bash
I.switchTo({ css: 'iframe[id^=number-frame]' })
    I switch to {"css":"iframe[id^=number-frame]"}
 ERROR  locator.toLowerCase is not a function
```

**Comment by das-en** [comment]
I believe this is also impacting me using 'within'

```
await within({ frame: '.flex-1' }, async () => {
//iframe content
})
```

`locator.toLowerCase is not a function`

**Comment by kobenguyent** [comment]
thanks for your report @das-en I think https://github.com/codeceptjs/CodeceptJS/pull/3847 also fixes that issue.

![Screenshot 2023-09-08 at 06 56 00](https://github.com/codeceptjs/CodeceptJS/assets/7845001/cf757506-7031-407a-ba86-066aa8f89212)

![Screenshot 2023-09-08 at 07 02 36](https://github.com/codeceptjs/CodeceptJS/assets/7845001/a2534729-1fb8-4d54-8a94-d400a1f2f99c)

**Comment by kobenguyent** [comment]
```
    it('within should respect context in see when using frame with css locator', async function () {
      if (isHelper('TestCafe')) this.skip();

      await I.amOnPage('/iframe');
      await I._withinBegin({
        frame: { css: '#number-frame-1234' }, // support the strict locator
      });

      try {
        await I.see('Information');
      } catch (err) {
        if (!err) assert.fail('seen "Information"');
      }
    });
```
that fix also supports the strict locator
