### ISSUE TITLE
Selenium exited before it could start with code 0

### ISSUE THREAD

**Issue by SathishBatta** [Codeception/CodeceptJS#3867]
When ever I try to execute CodeceptJs Script I'm getting Below error:
ERROR @wdio/selenium-standalone-service: Error: Selenium exited before it could start with code 0

Below is my package.json devDependencies versions:
"devDependencies": {
    "@wdio/selenium-standalone-service": "^7.3.0",
    "codeceptjs": "^3.3.4",
    "webdriverio": "^7.20.7"
  }

Please suggest any possible solutions.
Thank you in Advance.

**Comment by myrepojuly** [comment]
Hi… this seems a problem with WebdriverIO and I see there is an existing open ticket with the WebdriverIO team. Pls check this link https://github.com/webdriverio/selenium-standalone/issues/788 … You can turn off Wdio services in your config and try starting the server manually as stated here https://www.npmjs.com/package/selenium-standalone or try with docker as well.

**Comment by SathishBatta** [comment]
Hi @myrepojuly1987,
Thank you for response. 
My problem is solved by executing below command in terminal when ever I got above mentioned error.
npx selenium-standalone start

@myrepojuly1987  Thank you once again for help.

**Comment by myrepojuly** [comment]
If you don’t want to start it manually, you can also achieve doing it programmatically with bootstrap or with before hooks as well.
