### ISSUE TITLE
Can not execute pressKey for down arrow

### ISSUE THREAD

**Issue by arsa666** [Codeception/CodeceptJS#39]
Hello, 
I am able to use I.pressKey('Tab') or I.pressKey('Enter') and it works fine, but I have not been able to use for down arrow key? What is the correct parameter to pass in for this to work? Or there is a bug. I have tried everything and read all the documentation, including this website: https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/element/:id/value

and I still haven't been able to find the correct parameter to pass in to get a down key press. Please help!

**Comment by DavertMik** [comment]
Could you ask the same in [WebDriverIO Gitter Channel](http://gitter.im/webdriverio/webdriverio)?
If you will receive an answer please put it here and we will implement it in CodeceptJS.
Also could you provide HTML+JS snippet we can use for testing Down Arrow key

**Comment by ocean** [comment]
I was looking for this functionality too, and eventually found in https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/keys.js a reference to the key code <-> Unicode mappings in the constants file at https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/constants.js

There it specifies using `I.pressKey('Down arrow')` which I've tried and... it works!

It also says you can use `I.pressKey('Arrow_Down')` too.

**Comment by APshenkin** [comment]
Closing this issue, answer is in the comment above
