### ISSUE TITLE
Microsoft Edge is not opening for Test Automation 

### ISSUE THREAD

**Issue by SathishBatta** [Codeception/CodeceptJS#3900]
Hello All,

When ever I try to execute CodeceptJs Script for Microsoft Edge as test Automation browser then it's not executing (Script is executing fine in Chrome Browser) and also I'm not getting any error. It's just like below screen shot:
<img width="698" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/113429520/02496733-3bdb-4d3f-b970-44d6338923a3">

Below is my codecept.conf.js
<img width="645" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/113429520/66f3ec8c-6f02-4f3e-9589-01b503c4987e">
<img width="464" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/113429520/53f0db6c-313e-4b41-8972-b782dbce2981">
<img width="648" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/113429520/3ad11d0a-2bc6-4902-a800-7959cc685827">

Below is my package.json file versions:
<img width="420" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/113429520/d4c4370d-27fb-4a21-ba91-2da7b8bc3e2e">

Please suggest any possible solutions.
Thank you in Advance.

**Comment by myrepojuly** [comment]
Could you pls share the browser, driver versions? Are you using WDIO/Selenium-standalone-service?

**Comment by myrepojuly** [comment]
Also, you can migrate ur allure reporter to [allure-codeceptjs](https://www.npmjs.com/package/allure-codeceptjs) maintained by allure itself.. Pls read more here [github](https://github.com/allure-framework/allure-js``)

**Comment by SathishBatta** [comment]
Hi @myrepojuly1987,
Below is the Browser details:
<img width="618" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/113429520/1ae6ef39-2b9a-4c0c-aac7-c12ab3f0be8d">

Above I attached screenshot for Driver versions in Package.json file. Please check once

Are you using WDIO/Selenium-standalone-service?
I'm using below commands to install codeceptjs
1) “npm install @babel/core --save”
2) “npm install @wdio/selenium-standalone-service --save-dev”
3) “npm install codeceptjs webdriverio --save-dev”

**Comment by SathishBatta** [comment]
> Also, you can migrate ur allure reporter to [allure-codeceptjs](https://www.npmjs.com/package/allure-codeceptjs) maintained by allure itself.. Pls read more here [github](https://github.com/allure-framework/allure-js%60%60)

Issue is not with allure report. However I installed allure report by following command as per terminal in First screen shot.

**Comment by SathishBatta** [comment]
Hello,
I followed below steps to execute script in Microsoft edge browser

1) Go to below link and follow “Download Microsoft Edge WebDriver” section steps
https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp

2) In Terminal, First we need to manually start the Selenium server using below command
npx selenium-standalone start

3) In another Terminal, Now we need to execute the script which we need to test.

Thanks.
