### ISSUE TITLE
Running test cases by tag, is running every test instead of the tagged test

### ISSUE THREAD

**Issue by nak1** [Codeception/CodeceptJS#3907]
#### What are you trying to achieve?
Executing tests based on tags is not working. We have a tag for critical regression test cases that had been working until a couple of weeks ago. 
#### What do you get instead?
Now, every test case runs instead of the tagged test cases. 

### Details

* CodeceptJS version:"3.5.5"
* NodeJS Version: 18.16.0
* Operating System: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
codeceptjs run --verbose --grep '(?=.*@COREregression)'
```

**Comment by kobenguyent** [comment]
please try with 3.5.6 latest version if the issue has been resolved for you @nak1 . Feel free to reopen this and provide more logs to have better debugging.
