### ISSUE TITLE
unknown option '--config=./webapp

### ISSUE THREAD

**Issue by AramSol** [Codeception/CodeceptJS#3922]
After upgrade the Codeceptjs NPM package from 3.4.1 to 3.5.6 we try to run UI test and we get this error 
**unknown option '--config=./webapp**
we use this --config parameter to point the config inside Test folder

![image](https://github.com/codeceptjs/CodeceptJS/assets/39582300/ff21feaa-e01c-4946-bb18-ed139b0717e2)

### Details

* CodeceptJS version: 3.5.6
* NodeJS Version:v18.17.1
* Operating System:windows
* webdriverio

**Comment by kobenguyent** [comment]
I'm not sure if you pass the config arg properly. Please retry as following:

```
 npx codeceptjs run -c codecept.conf.js 
CodeceptJS v3.5.9-beta.1 #StandWithUkraine
Using test root "/Users/t/Downloads/highlight_error_sample"

My --

```
