### ISSUE TITLE
Slashes are not escaped when screenshot name is taken from a Scenario name

### ISSUE THREAD

**Issue by justvovus** [Codeception/CodeceptJS#393]
#### What are you trying to achieve?
I want to have a screenshot on Scenario failure.
In my config I have:
```
output: "/tmp/my-app"
```
In my bootstrap method I have
```
fs.ensureDirSync("/tmp/my-app");
```
from fs-extra npm package.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Uncaught Error: ENOENT: no such file or directory, open '/tmp/vendor-backend/activate/deactivat_category.failed.png'
```
> Provide test source code if related

```
Scenario("activate/deactivate category", (I) => {});
```
### Details

* CodeceptJS version: v0.4.16

**Comment by APshenkin** [comment]
Fixed in 1.0.0
