### ISSUE TITLE
not executing instuctions on jenkins

### ISSUE THREAD

**Issue by michaeltomasik** [Codeception/CodeceptJS#394]
Problem is that it is basically shows only first test Title and it assuming it's ok and stop testing

`codeceptjs run -o '{ \"helpers\": {\"Nightmare\": {\"url\": \"http://teamviewer.nexway.test:8000\"}}}' --steps"`
I also tried
`xvfb-run codeceptjs run -o '{ \"helpers\": {\"Nightmare\": {\"url\": \"localhost:8080\"}}}' --steps`
which I thought is related to this issue 
https://github.com/Codeception/CodeceptJS/issues/237

### Output:
```
CodeceptJS v0.4.13
Using test root "/usr/src/app"

user test --
 Login 
```
### Details

* CodeceptJS version:   0.4.13
* Nightmare version (if related)
* Configuration file:

```
{
  "tests": "./test/*.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "require": "./node_modules/codeceptjs/lib/helper/Nightmare.js",
      "show": false,
      "openDevTools": true
    },
    "CustomNightmare": {
      "require": "./test/helpers/customNightmareHelper.js"
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {}
}

```

**Comment by DavertMik** [comment]
Not sure it is related, but why do you have `"openDevTools": true`?

**Comment by michaeltomasik** [comment]
ohh I was just testing it with `show: true` locally and forgot to change it back

**Comment by DavertMik** [comment]
could you try on CI with disabled those options?

**Comment by michaeltomasik** [comment]
still the same :/

**Comment by omerman** [comment]
Any progress?

**Comment by aryzle** [comment]
👍

**Comment by APshenkin** [comment]
Is this issue is still valid? Please try to update to 1.0.0. Can somebody provide more details about this issue (logs, jenkins configuration) ?
