### ISSUE TITLE
performSwipe stoped to work with new uiautomator2 

### ISSUE THREAD

**Issue by MykaLev** [Codeception/CodeceptJS#3949]
After updating uiautomator2 to version 2.31.3 performSwipe stoped to work

Seems the issue in changes of this file https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/commands/actions.js

"codeceptjs": "^3.5.4",

**Appium configs**:

let Appium = {
    app: 'your apk path',
    platform: 'Android',
    device: 'device_id',
    appiumV2: true,
    desiredCapabilities: {
        automationName: 'UiAutomator2',
        'appium:platformName': 'Android',
        autoGrantPermissions: true,
        platformVersion: 'your android version',
        newCommandTimeout: 4000,
        timeoutSeconds: 4,
        adbExecTimeout: 600000,
        androidInstallTimeout: 600000,
        appWaitDuration: 60000,
        nativeWebTap: true,
        networkSpeed: 'full',
        noReset: true,
        fullReset: false,
        allowTestPackages: true,
        appWaitActivity: "com.ddits.login.LoginActivity,com.ddits.feature.main.MainActivity"
    },
    timeouts: {
        pageLoad: 15000
    },
    waitForTimeout: 5000
};

**Error**:
unknown method: Not implemented
    at getErrorFromResponseBody (file:///Users/project_folder/node_modules/webdriver/build/utils.js:194:12)
    at NodeJSRequest._request (file:///Users/project_folder/node_modules/webdriver/build/request/index.js:164:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Browser.wrapCommandFn (file:///Users/project_folder/node_modules/@wdio/utils/build/shim.js:81:29)
    at async Appium.performSwipe (/Users/project_folder/node_modules/codeceptjs/lib/helper/Appium.js:1083:5)
    at async swipeElement (/Users/project_folder/test/core/core_steps.js:841:9)
    at async /Users/project_folder/test/core/core_steps.js:662:9
    at async runSteps (/Users/project_folder/node_modules/codeceptjs/lib/interfaces/gherkin.js:77:9)

**Appium Logs:**
[HTTP] --> POST /wd/hub/session/44f79d2c-6085-4556-9f31-efca5c99f8c7/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":540,"y":1134}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":540,"y":79}},{"action":"release"}]}
[debug] [AndroidUiautomator2Driver@3d3d (44f79d2c)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":540,"y":1134}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":540,"y":79}},{"action":"release"}],"44f79d2c-6085-4556-9f31-efca5c99f8c7"]
[debug] [AndroidUiautomator2Driver@3d3d (44f79d2c)] Encountered internal error running command: NotImplementedError: Not implemented
[debug] [AndroidUiautomator2Driver@3d3d (44f79d2c)]     at AndroidUiautomator2Driver.swipe (/Users/user_folder/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/actions.js:48:11)
[debug] [AndroidUiautomator2Driver@3d3d (44f79d2c)]     at AndroidUiautomator2Driver.performTouch (/Users/user_folder/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/touch.js:226:25)
[debug] [AndroidUiautomator2Driver@3d3d (44f79d2c)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[HTTP] <-- POST /wd/hub/session/44f79d2c-6085-4556-9f31-efca5c99f8c7/touch/perform 405 1 ms - 555

**Comment by andonary** [comment]
Hello,

can you provide more details like your `codecept.conf.js` and other stuffs that will help us to reproduce the issue?

**Comment by MykaLev** [comment]
It's not related to configs but I added Appium config and Error trace
