### ISSUE TITLE
Ignoring cancel characters with playwright on string locators

### ISSUE THREAD

**Issue by rorymullan** [Codeception/CodeceptJS#3987]
#### What are you trying to achieve?

I.see('This isn\'t a string')

results in an error:

locator.isVisible: Unexpected token "t" while parsing selector ":has-text('This isn't a string') >> nth=0"
11:26:00 at Playwright.waitForText (node_modules/codeceptjs/lib/helper/Playwright.js:2584:79)

The cancel character in being removed when passing through to playwright.

#### What do you get instead?

Pinning back to 3.5.6 and the tests again pass.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.5.7
* NodeJS Version: 18
* Operating System: Linux
* Playwright: ^1.x.x
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
hey @rorymullan are you passing the string wrongly?

it shall be either `I.see("This isn't a string")` or 
```
I.see(`This isn't a string`)
```

![Screenshot 2023-11-11 at 16 40 58](https://github.com/codeceptjs/CodeceptJS/assets/7845001/3f061f71-cc69-4a3e-99a8-e4bf597d75b9)

**Comment by psongers** [comment]
@kobenguyent This is also happening to me with `I.waitForText("I've Succeeded", 30);` only on version 3.5.7

```
     locator.isVisible: Unexpected token "ve" while parsing selector ":has-text('I've Succeeded') >> nth=0"
      at Playwright.waitForText (.../node_modules/codeceptjs/lib/helper/Playwright.js:2584:79)
```

**Comment by rorymullan** [comment]
> hey @rorymullan are you passing the string wrongly?
> 
> it shall be either `I.see("This isn't a string")` or
> 
> ```
> I.see(`This isn't a string`)
> ```
> 
> ![Screenshot 2023-11-11 at 16 40 58](https://user-images.githubusercontent.com/7845001/282251424-3f061f71-cc69-4a3e-99a8-e4bf597d75b9.png)

Apologies, my original example wasn't the best. I am actually including a cancel character, so am passing:

`I.see('This isn\'t a string')`

This was working fine before the latest release.

**Comment by kobenguyent** [comment]
![Screenshot 2023-11-15 at 11 30 42](https://github.com/codeceptjs/CodeceptJS/assets/7845001/82b1d1f3-86a1-4737-9570-b0392600037a)
@rorymullan it works for me.

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.

**Comment by jancorvus** [comment]
I am experiencing the same issue in `CodeceptJS@v3.5.9-beta.1`
And I tried different quotes. The failure is the same
```
I.waitForText("Were you able to resolve the resident's issue?", 10);
I.waitForText(`Were you able to resolve the resident's issue?`, 10);
I.waitForText('Were you able to resolve the resident\'s issue?', 10);
```
```
locator.isVisible: Unexpected token "s" while parsing selector ":has-text('Were you able to resolve the resident's issue?') >> nth=0"
      at Playwright.waitForText (node_modules\codeceptjs\lib\helper\Playwright.js:2584:79)
```

So, I reopened it as https://github.com/codeceptjs/CodeceptJS/issues/4037
