### ISSUE TITLE
Missing session id error

### ISSUE THREAD

**Issue by ottoo** [Codeception/CodeceptJS#399]
#### What are you trying to achieve?

Running two scenarios in separate files causes tests to fail. I noticed there was another (closed) issue about this already [(#241)](https://github.com/Codeception/CodeceptJS/issues/241) but I still keep getting this error. If I run a single file, tests pass fine.

#### What do you get instead?

```
[6] Error | Error: A session id is required for this command but wasn't found in the response payload
 > Error: A session id is required for this command but wasn't found in the response payload
   [6] Stopping recording promises
 > [Session] cleaning cookies and localStorage
   [6] Error | Error: A session id is required for this command but wasn't found in the response payload
```

### Details

* CodeceptJS version: 0.4.16
* NodeJS Version: 7.4.0
* Operating System: Mac OSX
* WebDriverIO: 4.6.1

**Comment by waryhermit** [comment]
@ottoo Have you figured out any work around for this yet?

**Comment by APshenkin** [comment]
@ottoo Please update CodeceptJS to 1.0.0 and give us feedback about this issue
