### ISSUE TITLE
codeceptjs process crashes during test run

### ISSUE THREAD

**Issue by hubidu** [Codeception/CodeceptJS#400]
#### What are you trying to achieve?

I had a strange problem recently after updating to 0.4.16. I added the following config entries to WebDriverIO:

```
      "restart": false,
      "manualStart": false
```

After doing that I wasn't able to complete a testrun anymore since codeceptjs would just crash in the middle of the testrun (process just disappeard, exit code was even 0) without producing a final result summary. The crashes happened at different test cases during the run, but usually it happened after 3 to 5 tests being run. If I just ran the test where the crash occurred (using grep) it would always complete successfully.
As soon as I removed the above config entries, the test run would again complete as normal and show the final test results after running all tests.

I am using node v6.9.4. The crashes happened on Windows as well as on Linux.

I added the above config entries in the first place since otherwise the browser property of WebDriverIO was not initialized in the Helper._beforeSuite hook.

**Comment by APshenkin** [comment]
@hubidu Please update to 1.0.0 and try again. If issue is still valid, please provide logs in verbose mode
