### ISSUE TITLE
Security vulnerabilities in OpenAI and Axios dependencies linked to CodeceptJS?

### ISSUE THREAD

**Issue by clundstedt-m** [Codeception/CodeceptJS#4000]
#### What are you trying to achieve?
Install the packages corresponding to CodeceptJS without any moderate or higher vulnerability

#### What do you get instead?
When I run the npm I command with the latest version of CodeceptJS (3.5.7) I get the following warnings:
![Screenshot 2023-11-13 at 11 52 53](https://github.com/codeceptjs/CodeceptJS/assets/81565080/5987b42a-7087-4b34-a8ad-28b5bf06f802)

This is also causing that if I run npm audit fix --force, the version is being downgraded to 3.5.4 to solve 2 out of 3 vulnerabilities and if I run the command again to solve the remaining one I'm being downgraded to 3.4.1 which invalidates a customization we made on the Appium Helper to avoid having to put vendor prefixes on specific cases :(

### Details

* CodeceptJS version: 3.5.7
* NodeJS Version: 20.3.0
* Operating System: MacOS Sonoma 14.1.1
* Appium helper being used
* Current package.json:

```json
{
  "name": "qa-automation-template",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "localTest": "npx codeceptjs run --config=./codecept.conf.mobile.ts --features --grep '(?=.*@local)^(?!.*@skip)'",
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.37.1",
    "@slack/web-api": "^6.9.1",
    "@types/chai": "^4.3.6",
    "@types/chai-sorted": "^0.2.1",
    "@types/node": "^18.13.0",
    "chai": "^4.3.10",
    "chai-sorted": "^0.2.0",
    "codeceptjs": "^3.5.6",
    "codeceptjs-cucumber-json-reporter": "^1.0.9",
    "dotenv": "^16.0.3",
    "form-data": "^4.0.0",
    "joi": "^17.7.1",
    "json-joi-converter": "^17.2.1-g",
    "mocha": "^10.2.0",
    "mocha-junit-reporter": "^2.2.0",
    "mocha-multi": "^1.1.7",
    "moment": "^2.29.4",
    "officegen": "^0.6.5",
    "openai": "^4.17.4",
    "soft-assert": "^0.2.7",
    "ts-node": "^10.9.1",
    "typescript": "4.9.5",
    "webdriverio": "^6.12.1"
  }
}

```

**Comment by kobenguyent** [comment]
I think this https://github.com/codeceptjs/CodeceptJS/commit/c158f3b2ee8821f229f3e1c7eea10947b488e979 addressed the mentioned issue.
