### ISSUE TITLE
Add default portViewPoint to pass a null when needed for Chrome,Chromium and msEdge browsers

### ISSUE THREAD

**Issue by raghuramkappagantu** [Codeception/CodeceptJS#4003]
I am trying to click on a button(which will alter the screen resolution and then it will ask user to change the resolution or to keep the old one).This functionality is working fine on Firefox and safari as the default viewpoint is NULL , 

* CodeceptJS version: ^3.4.1
* NodeJS Version:v20.4.0
* Operating System: mac os Sonama 14.0

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
