### ISSUE TITLE
[Wrapped Error] "codeceptjs is not defined"

### ISSUE THREAD

**Issue by ilyabreev** [Codeception/CodeceptJS#401]
#### What are you trying to achieve?

Trying to test login feature in my application.

#### What do you get instead?

Getting error "codeceptjs is not defined" on any step after form submitting and redirect.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Landing --
 Login
 * I am on page "/"
 * I click "Login"
 * I fill field "Email", "test@email.com"
 * I fill field "Password", "testpassword"
 * I click "Login"
 * I see "Logout"
 ? FAILED in 14200ms


-- FAILURES:

  1) Landing: Login:
     [Wrapped Error] "codeceptjs is not defined"

```
Click on "Login" submits form and then redirect to another page occurs.

> Provide test source code if related

```php
Scenario('Login', (I) => {
    I.amOnPage('/');
    I.click('Login');
    I.fillField('Email', 'test@email.com');
    I.fillField('Password', 'testpassword');
    I.click('Login');
    I.see('Logout');
});
```
### Details

* CodeceptJS version: 0.4.16
* NodeJS Version: 6.9.1
* Operating System: Windows 7 x64 Professional
* Nightmare version: 2.9.1
* Configuration file: 

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": "https://testwebsite",
      "windowSize":  "1920x1080" 
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "Tests.Acceptance"
}
```

**Comment by ilyabreev** [comment]
Important fact is that form submitted asynchronously.

**Comment by DavertMik** [comment]
Thanks, to work on this issue I need to see detailed output. Please could you run tests with `--verbose` flag (as it is asked in issue description template)

**Comment by ilyabreev** [comment]
`--verbose` not very informative except maybe this stacktrace:

```
  Error: [Wrapped Error] "codeceptjs is not defined"
      at promise.catch (C:\Users\UserName\AppData\Roaming\npm\node_modules\codeceptjs\lib\recorder.js:82:15)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by kurikaesu** [comment]
I'm getting the same issue using the NightmareJS helper.

What seems to be happening is when you; 
I.click('Login');
I.see('Logout');

There's a navigation step that is happening between the click and the logout.
On line 192 of codeceptjs/lib/helper/Nightmare.js, we have the line:
    this.browser.on('dom-ready', () => this._injectClientScripts());

Which injects the contents of codeceptjs/lib/helper/clientscripts/nightmare.js into the browser.
That clientscript is where codeceptjs is being defined when you use functions like:
I.see(x);
I.waitForText(x);

Unfortunately, when the browser navigates from one page to another, this clientscript needs to be re-injected before any other code that tries to access codeceptjs. When codecept executes the next "I.see()", it will usually execute before the "on(dom-ready)" inject method gets fired.

See badly formatted debug log below where I've added a 		this.debug("Injecting clientscripts/nightmare.js"); in the _injectClientScripts() function of Nightmare.js

=====================================
`
• I fill field "username", "user"
   Emitted | step.start (I fill field "password", "12345")
 • I fill field "password", "12345"
   Emitted | step.start (I click "//button[@type="submit"]")
 • I click "//button[@type="submit"]"
   Emitted | step.start (I wait for text "Logged in")
 • I wait for text "Logged in"
 > Injecting clientscripts/nightmare.js
   [2] Error | codeceptjs is not defined
   [2] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [2] <teardown> Queued | hook Nightmare._failed()
   [2] <teardown> Queued | () => done(err)
   [2] <teardown> Stopping recording promises
 > Screenshot is saving to /home/vagrant/displaysweet/Projects/testproj/test/output/Attempt_to_log_in.failed.png
   [2] <teardown> Starting <generator> session
 ✖ FAILED in 8571ms

   Emitted | test.after
   [2] <generator> Queued | hook Nightmare._after()
   [3] Starting recording promises
   Emitted | suite.after
   [3] Queued | hook Nightmare._afterSuite()

-- FAILURES:

  1) Basic functionality works:
     [Wrapped Error] "codeceptjs is not defined"
`

**Comment by ilyabreev** [comment]
Yes, using `I.wait(x)` is a workaround. But I need to insert it after all async form submit. Not very elegant.
It seems like in my case scripts reinjected after ASP.NET async postback in UpdatePanel control.

**Comment by bryanmc** [comment]
The `I.wait(x)` workaround is really is nearly as bad as the original issue.  You're just introducing the very strong possibility that your test fails every nth run unless you use some obscenely long wait time, which then of course unnecessarily lengthens the run time of every test that uses this particular wait step.

After looking at this for a bit, I discovered a much more elegant workaround.  This is working as of 0.5.1 (unknown, not tested on earlier versions).  The solution is to create a custom helper with a `_beforeStep` hook.

**waitfix_helper.js**
```js
'use strict';

class Waitfix extends Helper {

  _beforeStep(step) {
    let browser = this.helpers['Nightmare'].browser;
    if ( step.name === 'waitForElement' ){
      return browser.wait(step.args[0]);
    }
  }

}

module.exports = Waitfix;
```
The `if ( step.name === 'waitForElement' ){` condition can be jigged to meet your needs / be more sophisticated and targeted.  This example simply determines if the step is the one affected by looking at it's name.

`browser` accesses the NightmareJS instance, with access to it's [native commands](https://github.com/segmentio/nightmare#waitselector).  Passing in the step data `_beforeStep(step)` allows us to access the current step's arguments, which in the case of **waitForElement** should be a selector.  This value is then passed into the native Nightmare `wait` command.  Replacing the native command as a handler for this exception seems to work without introducing arbitrary bugs or unnecessary testing overhead.  **Warning:** However, a potential issue here is that Nightmare does not allow the use of Xpath's, so a more complete solution would somehow convert xpath's into CSS selectors.

**Comment by MrAvantiC** [comment]
Hello @bryanmc,

I just ran into the same issue when I saw your comment here.
Unfortunately, this:
```
Feature('Basket');

Scenario('Add item and go to basket', (I) => {
  // ...
  I.click('#toBasket')
  I.waitForElement('#popup')
  I.seeElement('#popup')
});
```

still results in ` [Wrapped Error] "codeceptjs is not defined"`.

Is there anything else to do than register the helper using `codeceptjs gh` that I am missing here?

**Comment by bowerandy** [comment]
Hi. I am also seeing the same issue and @bryanmc 's fix isn't working consistently for me (it does improve things but there is then an unreliability in the tests, which fail about 20% of the time). I end up having to introduce a wait, which is not something I want to take forward. For the time being I have gone back to using the WebDriverIO helper which is reliable in all cases.

Given the fact that this seems to be a NIghtmare only issue, would it be worth directing our attention at a fix for Nightmare itself rather than a change to Codecept? Does anyone have any ideas where to look in the Nightmare codebase?

**Comment by aryzle** [comment]
+1

**Comment by m1x0n** [comment]
+

**Comment by APshenkin** [comment]
Can anybody provide reproducible code and page, so we can test this on our side?

**Comment by m1x0n** [comment]
@APshenkin Hi. In my case it is a redirect after form submit. I'm temporary using `I.wait(x)` but assume that it is not right way of doing things.

**Comment by APshenkin** [comment]
@m1x0n Can you please provide more details? Also logs in verbose mode will be helpful

**Comment by m1x0n** [comment]
@APshenkin This is what I have so far:
```
Admin Login Test --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook Nightmare._beforeSuite()
 As an admin I can login to Admin UI and logout back
   Emitted | test.before
   [1] Queued | hook Nightmare._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "/")
   [1] Queued | amOnPage: "/"
   Emitted | step.after (I am on page "/")
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I see "Login")
   [1] Queued | see: "Login"
   Emitted | step.after (I see "Login")
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I fill field "[name="admin[email]"]", "root@example.com")
   [1] Queued | fillField: "[name="admin[email]"]", "root@example.com"
   Emitted | step.after (I fill field "[name="admin[email]"]", "root@example.com")
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I fill field "[name="admin[password]"]", "123456")
   [1] Queued | fillField: "[name="admin[password]"]", "123456"
   Emitted | step.after (I fill field "[name="admin[password]"]", "123456")
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I click "button[type=submit]")
   [1] Queued | click: "button[type=submit]"
   Emitted | step.after (I click "button[type=submit]")
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I wait for element "a[href="/admin/logout"]", 5)
   [1] Queued | waitForElement: "a[href="/admin/logout"]", 5
   Emitted | step.after (I wait for element "a[href="/admin/logout"]", 5)
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I click "a[href="/admin/logout"]")
   [1] Queued | click: "a[href="/admin/logout"]"
   Emitted | step.after (I click "a[href="/admin/logout"]")
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I wait 5)
   [1] Queued | wait: 5
   Emitted | step.after (I wait 5)
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I see element "form[action="/admin/login"]")
   [1] Queued | seeElement: "form[action="/admin/login"]"
   Emitted | step.after (I see element "form[action="/admin/login"]")
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | fire test.passed
   [1] Queued | finish test
   Emitted | step.start (I am on page "/")
 • I am on page "/"
 > [URL] http://localhost:3000/
 > [Code] 200
 > [Headers] {"cache-control":["no-store, no-cache, must-revalidate","no-cache"],"connection":["close"],"content-type":["text/html; charset=UTF-8"],"date":["Tue, 25 Jul 2017 13:28:08 GMT"],"expires":["Thu, 19 Nov 1981 08:52:00 GMT"],"host":["localhost:3000"],"pragma":["no-cache"],"set-cookie":["PHPSESSID=djp3g03rd1hv18mubf6llss076; path=/"],"x-powered-by":["PHP/7.0.8-2+deb.sury.org~xenial+1"]}
   Emitted | step.passed (I am on page "/")
   Step finished in 1.239 sec
   Emitted | step.start (I see "Login")
 • I see "Login"
   Emitted | step.passed (I see "Login")
   Step finished in 0.012 sec
   Emitted | step.start (I fill field "[name="admin[email]"]", "root@example.com")
 • I fill field "[name="admin[email]"]", "root@example.com"
   Emitted | step.passed (I fill field "[name="admin[email]"]", "root@example.com")
   Step finished in 0.829 sec
   Emitted | step.start (I fill field "[name="admin[password]"]", "123456")
 • I fill field "[name="admin[password]"]", "123456"
   Emitted | step.passed (I fill field "[name="admin[password]"]", "123456")
   Step finished in 0.322 sec
   Emitted | step.start (I click "button[type=submit]")
 • I click "button[type=submit]"
   Emitted | step.passed (I click "button[type=submit]")
   Step finished in 0.524 sec
   Emitted | step.start (I wait for element "a[href="/admin/logout"]", 5)
 • I wait for element "a[href="/admin/logout"]", 5
   [1] Error | codeceptjs is not defined
   Emitted | step.failed (I wait for element "a[href="/admin/logout"]", 5)
   Step finished in 1.374 sec
   [1] Error | Error: [Wrapped Error] "codeceptjs is not defined"
   Emitted | step.failed (I click "a[href="/admin/logout"]")
   Step finished in NaN sec
   [1] Error | Error: [Wrapped Error] "codeceptjs is not defined"
   Emitted | step.failed (I wait 5)
   Step finished in NaN sec
   [1] Error | Error: [Wrapped Error] "codeceptjs is not defined"
   Emitted | step.failed (I see element "form[action="/admin/login"]")
   Step finished in NaN sec
   [1] Error | Error: [Wrapped Error] "codeceptjs is not defined"
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook Nightmare._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
 > Screenshot is saving to /home/vagrant/dynamicres/admin-ui/tests/e2e/output/As_an_admin_I_can_login_to_Admin_UI_and_logout_back.failed.png
 ✖ FAILED in 5130ms

   [2] Starting recording promises
   Emitted | test.after
   [2] Queued | hook Nightmare._after()
   Emitted | suite.after ([object Object])
   [2] Queued | hook Nightmare._afterSuite()

-- FAILURES:

  1) Admin Login Test: As an admin I can login to Admin UI and logout back:
     [Wrapped Error] "codeceptjs is not defined"
  
  Scenario Steps:
  
  - I.seeElement("form[action="/admin/login"]") at Object.logout (tests/e2e/pages/DashboardPage.js:17:11)
  - I.wait(5) at Object.logout (tests/e2e/pages/DashboardPage.js:16:11)
  - I.click("a[href="/admin/logout"]") at Object.logout (tests/e2e/pages/DashboardPage.js:15:11)
  - I.waitForElement("a[href="/admin/logout"]", 5) at Object.loginWithDefaultCredentials (tests/e2e/pages/LoginPage.js:34:11)
  - I.click("button[type=submit]") at Object.login (tests/e2e/pages/LoginPage.js:28:11)
  - I.fillField("[name="admin[password]"]", "123456") at Object.login (tests/e2e/pages/LoginPage.js:27:11)
  - I.fillField("[name="admin[email]"]", "root@example.com") at Object.login (tests/e2e/pages/LoginPage.js:26:11)
  - I.see("Login") at Object.visit (tests/e2e/pages/LoginPage.js:22:11)
  - I.amOnPage("/") at Object.visit (tests/e2e/pages/LoginPage.js:21:11)
  
  Error: [Wrapped Error] "codeceptjs is not defined"
      at promise.catch (node_modules/codeceptjs/lib/recorder.js:134:15)
      at process._tickCallback (internal/process/next_tick.js:109:7)


  FAIL  | 0 passed, 1 failed   // 5s
   Emitted | global.result ([object Object])
   [2] Queued | hook Nightmare._finishTest()
```

I haven't investigate it properly but it might be somehow related to: [http://codecept.io/helpers/Nightmare/#executeasyncscript](http://codecept.io/helpers/Nightmare/#executeasyncscript).

**Comment by lexds1591** [comment]
+1

**Comment by APshenkin** [comment]
@m1x0n Could you please provide test code also?

**Comment by APshenkin** [comment]
Found the reason of issue, will try to fix it

**Comment by m1x0n** [comment]
@APshenkin Glad to know you sorted it out.

**Comment by APshenkin** [comment]
@m1x0n @lexds1591 
Let's test a fix in branch `nightmare-reinject` to be sure that problem was solved. Can you please install codeceptjs from the branch and check if your issues were solved?

**Comment by m1x0n** [comment]
@APshenkin I managed to test with `nightmare-reinject` branch. Unfortunately It doesn't work for my case.
The stack trace it generated this time:
```
Scenario Steps:
  
  - I.waitForElement("a[href="/admin/logout"]", 5) at Object.loginWithDefaultCredentials (tests/e2e/pages/LoginPage.js:35:11)
  - I.click("button[type=submit]") at Object.login (tests/e2e/pages/LoginPage.js:28:11)
  - I.fillField("[name="admin[password]"]", "123456") at Object.login (tests/e2e/pages/LoginPage.js:27:11)
  - I.fillField("[name="admin[email]"]", "root@example.com") at Object.login (tests/e2e/pages/LoginPage.js:26:11)
  - I.see("Login") at Object.visit (tests/e2e/pages/LoginPage.js:22:11)
  - I.amOnPage("/") at Object.visit (tests/e2e/pages/LoginPage.js:21:11)
  
  TypeError: Cannot read property 'indexOf' of undefined
      at browser.wait.catch (node_modules/codeceptjs/lib/helper/Nightmare.js:864:22)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```
I debugged it a bit. The error is message is outside `err.message` it is just inside `err` object. The actual error it generated is `Error: [Wrapped Error] "Cannot read property 'findElement' of undefined"` from `recorder.js`.

**Comment by APshenkin** [comment]
@m1x0n Is your site public? Can I test this by myself?

**Comment by m1x0n** [comment]
@APshenkin No. I think it could be replicated it by laravel app with basic auth. https://laravel.com/docs/5.4/authentication.

**Comment by APshenkin** [comment]
@m1x0n Unfortunately, I can't reproduce this issue locally. I tried it on this website, but it works ok for me http://laravel-tricks.com/. BTW, I did several changes, so can I ask you to try it again with latest changes in `nightmare-reinject` branch?
