### ISSUE TITLE
suggestion: change default Generate PageObject - location

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#402]
When I create a new PageObject with the command codeceptjs gpo, I get the following question:
Where should it be stored: ./pages/[nameofPageObject]

**suggestion**:
change it to ./pageobjects/[nameofPageObject]

**reason to suggest:** 
if I understand it well, all the pageobjects are stored in one folder that just groups all the PO's, not the pages under test.

**Comment by DavertMik** [comment]
sure, that's not about pages under test. `page` is shortened of pageobject here. And I don't see any confusion, as I don't know any framework that would serve JS files as separate pages. 

Anyway, I'd prefer current naming

**Comment by joelgrimberg** [comment]
As I said, just a suggestion ;)
because I am still new to CodeceptJS / pageobjects, i somehow was mislead by the term 'page' in the path.
But then again, I am still a starter on the topic.

Thanx for your time!

Joël

Op 31 januari 2017 bij 20:57:45, Michael Bodnarchuk (notifications@github.com) schreef:

sure, that's not about pages under test. page is shortened of pageobject here. And I don't see any confusion, as I don't know any framework that would serve JS files as separate pages.

Anyway, I'd prefer current naming
