### ISSUE TITLE
adding a globals.js file to the mix

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#403]
in My current project I use the following globals.js:

```js
var Globals = {
  'url': 'https://beta.belastingdienst.nl',

  //CSS Selectors
  'Menu_knop' : '.level0 > ul:nth-child(1) > li:nth-child(2) > a:nth-child(1)',
  'Sluiten_in_menu' : 'div.hidden-xs:nth-child(1) > a:nth-child(1)',
  'Sluiten_in_header' : '.bld-mega-dropdown > a:nth-child(1)',
  'Menu':'.bld-mega-dropdown-menu > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)',
  //viewports
 'Viewport_a' : '1219',
  'viewport_b' : '1023',
  'viewport_c' : '767',
  'viewport_d' : '319'
};
```

and incorporate it in my Codecept.json:

```json
  "include": {
    "I": "./steps_file.js",
    "functions": "./pages/global_functions.js",
    "globals":"./globals.js"
}
```

is this the way to use globals? or should I put all the globals in codecept.json?

**Comment by DavertMik** [comment]
Probably. But do you do `module.exports = globals;` inside globals.js?
And yes, I suppose this will work for you:

```js
Scenario('test something', (I, globals) => {
  I.amOnPage(globals.url);

})
```

should work for you

**Comment by joelgrimberg** [comment]
yes, I end my globals.js with:
var Globals = {
...
};

module.exports = Globals;

**Comment by DavertMik** [comment]
So I think everything is right. Or there are problems with such setup?

**Comment by APshenkin** [comment]
close due inactivity

**Comment by sumiagar** [comment]
Hi All , 
I am also want to do same kind of thing . I have defined my constants in seprate js file whihc I want to access into all the test cases file . BY above methode I can access the content . But I don't want to pass object in every test case senario . So can anyone help me on this . 
I have tried lot of things like :- import , export , require etc.

Thanks
Sumiran Agarwal

**Comment by PeterNgTr** [comment]
@sumiagar does this help? https://codecept.io/configuration#require

**Comment by sumiagar** [comment]
> @sumiagar does this help? https://codecept.io/configuration#require

hi Peter, 

Thanks for reply , 

I tried but couldn't able access my content . 

Config file:- 
{
require: ["./Common/menuItem.js"]
}
menuItem.js
module.exports = {
	
	menu_list : ["watch tv", "now","NET TV guide","recordings","music","messages","settings","search"],

};

access into test case file : -

Scenario('Verify the All Main Menu items text', (I) => {
    within({frame: "#PORTAL"}, () => {
       // var menu_list = ["watch tv", "now","NET TV guide","recordings","music","messages","settings","search"];
        var i = 0;
        for (i= 0 ;i<menu_list.length;i++ )
        {
           I.see(menu_list[i])
           I.pressKey("ArrowDown")
        }
        console.log(menu_list[0]);
    });
   
}).tag('@sanity').tag('important');


it shows error menu_list undefined

**Comment by LukoyanovE** [comment]
@sumiagar , what the problem with creating a some file with constants, where you expots object with constants. And then require/import this file in test files?

As second solution, you can create a custom helper with method, which will return these constants:
```js
"use strict";
// you can require/import from file
import { constants } from "./some/file";
// or create constant in helper
const constants = {
  FIRST: 1,
  SECONDS: 2
};

/**
 * Return constants
 */
class ConstantsHelper extends Helper {
  /**
   * return all constants
   */
  grabAllConstants() {
    return constants;
  }
}

module.exports = ConstantsHelper;
```
so in tests you will use `let smevalue = await I.grabAllConstands().FIRST`
It's works, but looks weird.

I prefer just import in test files, where it needs

**Comment by sumiagar** [comment]
> @sumiagar , what the problem with creating a some file with constants, where you expots object with constants. And then require/import this file in test files?
> 
> As second solution, you can create a custom helper with method, which will return these constants:
> 
> ```js
> "use strict";
> // you can require/import from file
> import { constants } from "./some/file";
> // or create constant in helper
> const constants = {
>   FIRST: 1,
>   SECONDS: 2
> };
> 
> /**
>  * Return constants
>  */
> class ConstantsHelper extends Helper {
>   /**
>    * return all constants
>    */
>   grabAllConstants() {
>     return constants;
>   }
> }
> 
> module.exports = ConstantsHelper;
> ```
> 
> so in tests you will use `let smevalue = await I.grabAllConstands().FIRST`
> It's works, but looks weird.
> 
> I prefer just import in test files, where it needs

Hi, 

Thanks for reply. I don't want to use it as Helper . 
Can't I use like normal js projects . I want to define some objects , variables , function which I would use into test file . by using import /export . 
Import export is not working with codecept framework .

**Comment by LukoyanovE** [comment]
@sumiagar try `module.exports = constants;` and `const something = require("./path/to/constants")`

**Comment by sumiagar** [comment]
> @sumiagar try `module.exports = constants;` and `const something = require("./path/to/constants")`

Thanks. It is working now
