### ISSUE TITLE
I.amInPath()/I.seeFile() is a unresolved functions or methods

### ISSUE THREAD

**Issue by Archana-max** [Codeception/CodeceptJS#4036]
#### What are you trying to achieve?
I am trying to use Filesystem helper  to verify the downloaded file.
I followed exactly these config steps to enable the filesystem helper https://codecept.io/helpers/FileSystem/

#### What do you get instead?
The output is
I.amInPath/ I.seeFile is a unresolved function or method.

### Details
* CodeceptJS version:2.6.1
* NodeJS Version:10.16.3
* Operating System: Macbook/ventura 13.6.1
* puppeteer

**Comment by kobenguyent** [comment]
@Archana-max are you using the latest version as from your description, it is 2.6.x which is a very old version.
