### ISSUE TITLE
Use yield inside pages and fragments

### ISSUE THREAD

**Issue by tfiwm** [Codeception/CodeceptJS#409]
#### What are you trying to achieve?
I want to use yield inside pages and fragments. I tried it already with the npm package co like referenced inside a different ticket. With no success :( any idea?

#### What do you get instead?
the steps after it are not any more started

inside an fragment ->

```js
someFragmentFunction() {
  let value = yield I.grabTextFrom('SOME_SELECTOR');
  assert.equal(value, 'EQUAL_VALUE');
}
```

### Details

* WebDriverIO

**Comment by DavertMik** [comment]
`yield` is available only inside generator functions. Using `yield` as an alias for `await` is possible if you combine it with **co** package (you can find it on NPM). Unfortunately CodeceptJS doesn't provide any additional hooks to page/steps,but this may work for you:

```js
co(function*() {
  let value = yield I.grabTextFrom('SOME_SELECTOR');
  assert.equal(value, 'EQUAL_VALUE');
})();
```

**Comment by jploskonka** [comment]
Maybe you could define your function as generator inside page and than use `yield*` to pass execution to it? I've tried it with `I.executeScript` and it worked, I suppose in this case this should work too:

```js
// in page object
grabSomething: function*() {
  return yield I.grabTextFrom('selector');
}

// in scenario
const grabbedSomething = yield* MyPage.grabSomething();
```
