### ISSUE TITLE
How to wait for a webpage to be fully loaded before starting to test ?

### ISSUE THREAD

**Issue by adeleco** [Codeception/CodeceptJS#410]
I'd like to be sure that the webpage I'm going to test (using Nightmare) is totally loaded (no more loading loader visible... ). How can I proceed ? 

I've saw that I can wait for a DOM element, but pictures can haven't finish their loading.

Thank's a lot for your answer, 
Antoine

**Comment by APshenkin** [comment]
Unfortunately you can't.  Selenium can't track images loading, it can operates only with DOM and viewport.

**Comment by realtebo** [comment]
Same question, but about puppeteer & Chrome. Can I in some way 'waitForImageLoaded' ?

**Comment by flowl** [comment]
I think this is possible through `window.performance`.
