### ISSUE TITLE
Wrong xpath output when given empty attribute in a css locator

### ISSUE THREAD

**Issue by laxmikant-parate** [Codeception/CodeceptJS#4106]
#### What are you trying to achieve?
Codeceptjs uses package called `convert-cssxpath` to convert css to xpath. In old version it was using `css-to-xpath` to do so. 
When I use any css locator eg. `div[data-testid='']` i.e. with empty attribute value, `convert-cssxpath` throws error as `Invalid CSS selector` and returns a wrong xpath (empty value)

#### What do you get instead?
<img width="911" alt="codecept-issue" src="https://github.com/codeceptjs/CodeceptJS/assets/75083533/02b5508f-ccfd-436f-954f-d12570a10622">

I am using a css locator `div[data-testid='']` which is getting coverted to wrong xpath `//*//` expression.
If I use `div[data-testid='dummy']` if gets converted to `//div[@data-testid="dummy"]` which is correct. The only problem exists with empty values.

**Comment by jancorvus** [comment]
It should be fixed in the next from 3.5.11 version
https://github.com/codeceptjs/CodeceptJS/pull/4101
