### ISSUE TITLE
retryTo not working with await in block

### ISSUE THREAD

**Issue by cjhille** [Codeception/CodeceptJS#4110]
```js
Feature('foo');

Scenario('retry something', async ({ I }) => {

    I.amOnPage('http://example.org');
    
    // this works
    await retryTo( (tryNum) => {
        I.say(`${tryNum} try without await`);
        if (tryNum < 2) {
            I.say(`should fail and retry`);
            I.waitForVisible('.shouldFail', 1);
        }
        I.say(`should pass`);
    }, 2); 

    I.say(`---`);

    // this doesn't work
    await retryTo( async (tryNum) => {
        I.say(` ${tryNum} try with await`);
        await I.grabCurrentUrl();
        if (tryNum < 2) {
            I.say(`should fail and retry`);
            I.waitForVisible('.shouldFail', 1);
        }
        I.say(`should pass`);
    }, 2);
});

```

### Details

* CodeceptJS version: 3.5.7
* NodeJS Version: 18.18.
* Operating System: macos
* playwright

**Comment by kobenguyent** [comment]
May you try with latest version? As if it happens with latest version, there is more chance that more ppl encounter the same issue.

**Comment by cjhille** [comment]
@kobenguyent thanks for looking into this. i just tested it using a fresh `npx codeceptjs init` project with the current version -> same issue.
```
{
  "dependencies": {
    "codeceptjs": "^3.5.11"
  },
  "devDependencies": {
    "playwright": "^1.40.1"
  }
}
```

**Comment by cjhille** [comment]
however this fix you suggested [in slack](https://codeceptjs.slack.com/archives/C94G8JXJB/p1704705524920079?thread_ts=1704681303.383719&cid=C94G8JXJB) seems to works. 
<img width="343" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/8192226/a4cf52d2-7b1b-4e3f-bd55-749fc55dfe05">

**Comment by kobenguyent** [comment]
Thanks for @cjhille testing it out. Here is the fix https://github.com/codeceptjs/CodeceptJS/pull/4117
