### ISSUE TITLE
TypeScript: `CustomLocator` typing broken for custom strict locators

### ISSUE THREAD

**Issue by danielrentz** [Codeception/CodeceptJS#4119]
#### What are you trying to achieve?

Use custom locators in TypeScript.

#### What do you get instead?

Type errors for all custom strict locators in all tests.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

We used to register our custom locators by extending the `CodeceptJS.CustomLocators` interface, as introduced 3 years ago: https://github.com/codeceptjs/CodeceptJS/pull/2798

Documentation for this feature is still available: https://codecept.io/typescript/#types-for-custom-strict-locators

Since 3.5.11, the type `LocatorOrString` does not contain the property types of all `CustomLocators` interface properties, but the `CustomLocators` itself which does not make sense in our codebase.

https://github.com/codeceptjs/CodeceptJS/commit/474b5e13655a5187d8e1459397f0bfbc4a9f188c#diff-4f45caa500ef03d94d3c2bfa556caa1642df95d4e2b980d76b876a8fd2e8c522L434

```ts
type LocatorOrString =
    | string
    | ILocator
    | Locator
-    | CustomLocators[keyof CustomLocators];
+    | CustomLocators;
```

### Details

* CodeceptJS version: 3.5.11
* NodeJS Version: 20.9.0
* Operating System: Windows 11
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
Hi @danielrentz sorry for the issue you're encountering due to the changes. However do you think it's more relaxing to not define the custom locator in types?

**Comment by danielrentz** [comment]
We still would like to use type-safe custom locators as before. What is the background of this particular change (in a patch-level update btw...)? How is the `CustomLocators` interface intended to be used by now?

**Comment by kobenguyent** [comment]
Thanks @danielrentz for your reply! I wasn't aware of that CustomLocators so just pushed a fix for this. May you give your review once you some time? I'm not really a TS guy so not sure if there is another proper way to handle this.

https://github.com/codeceptjs/CodeceptJS/pull/4120

**Comment by danielrentz** [comment]
Thanks @kobenguyent, looks good.

Intention is to be able to extend the (initially empty) interface per project (using TypeScript's [declaration merging feature](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)). There is no other way to add custom types, i.e. it is not possible to directly extend the union type `LocatorOrString` in project code. The interface solution allows to register multiple independent custom locators, each mapped by an arbitrary key, e.g.

```ts
declare namespace CodeceptJS {
  interface CustomLocators {
    data: { data: string };
    other: { title: string, count: number };
  }
}
```

which allows
```ts
I.see({ data: "abc" });
I.see({ title: "abc", count: 7 });
```

See https://codecept.io/typescript/#types-for-custom-strict-locators for intended usage in CodeceptJS.

**Comment by kobenguyent** [comment]
thank you @danielrentz !
