### ISSUE TITLE
Unable to run tests for existing project or create new project with Playwright

### ISSUE THREAD

**Issue by rohanpatil20** [Codeception/CodeceptJS#4121]
#### What are you trying to achieve?
I'm trying to run the codecept tests that i had implemented around 4-5 months ago on my project. The tests are working when i run them on my gitlab pipeline with the playwright image (mcr.microsoft.com/playwright:v1.40.1-jammy

#### What do you get instead?
). I cant get them to run locally on my machine due to a 404 error for one of the libraries when i try to run npm install. Back when i implemented these tests, i was using a different laptop so there might be an installation step that i missed. But i tried following the same steps mentioned on the website https://codecept.io/playwright/#setup and initiating a new project but it still displays the same error.

![image](https://github.com/codeceptjs/CodeceptJS/assets/46788323/2f2d6827-3455-4580-b5da-025b89899235)

### Details
* NodeJS Version: 18.17.0
* Operating System: macOS Sonoma 14.1.1

* Configuration file:
package.json Config file from the existing project:
<img width="768" alt="Screenshot 2024-01-09 at 9 59 50 AM" src="https://github.com/codeceptjs/CodeceptJS/assets/46788323/03a1c664-09ea-4ad9-a83d-88ca4ebca068">

**Comment by Horsty80** [comment]
@rohanpatil20 on your local machine you probably have an override on `.npmrc` that redirect your `npm install` to a custom registry not the npm registry (the default)

Have you update the file ? or you global config ?

You can see in your screenshot that your are request `https://skimdb.npmjs.com/registry/` that isn't the npm registry
