### ISSUE TITLE
getTextFrom() grabTextFromAll() should return element's text with space if it is divided in multiple span

### ISSUE THREAD

**Issue by snehabhandge** [Codeception/CodeceptJS#4125]
#### What are you trying to achieve?
I am trying to get indexed element from the page, which is divided in two spans, first span contains index and second contains text.
e.g.: 
```
<h2>
<span>"1"</span>
<span>"One"</span>
</h2>
```
The output should be:
1 One
#### What do you get instead?
1One

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:3.5.8
* NodeJS Version: 18.18.0
* Operating System: Windows
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by jancorvus** [comment]
Why shoud it work this way?
[`I.grabTextFromAll`](https://codecept.io/helpers/Playwright/#grabtextfromall) returns an array of text grabbed by a loctor.
So, in your case, you could retrieve the text
```
const cellValues = await I.grabTextFromAll('h2 span');
```
and then join the way the context requires. Just the same as spans can serve different purposes, for spacing, or for line breaks
```
const cellValue = cellValues.join(' ');
```
or
```
const cellValue = cellValues.join('\n');
```
