### ISSUE TITLE
Re-opned : getTextFrom() grabTextFromAll() should return element's text with space if it is divided in multiple span #4125

### ISSUE THREAD

**Issue by snehabhandge** [Codeception/CodeceptJS#4129]
#### What are you trying to achieve?
I am trying to get indexed element from the page, which is divided in two spans, first span contains index and second contains text.
e.g.:
```
<h2>
<span>"1"</span>
<span>"One"</span>
</h2>
<h2>
<span>"2"</span>
<span>"Two"</span>
</h2>
```
[I.grabTextFromAll](https://codecept.io/helpers/Playwright/#grabtextfromall) should return an array as below:
```
[
"1 one",
"2 Two"
]
```
#### What do you get instead?
[I.grabTextFromAll](https://codecept.io/helpers/Playwright/#grabtextfromall) is returning an array as below:
**Case 1: "selector": "h2"**
```
[
"1one",
"2Two"
]

```
**Case 2: "selector": "h2 span"**
```
[
"1",
"one",
"2",
"Two"
]
```

The solution provided in https://github.com/codeceptjs/CodeceptJS/issues/4125 i.e. array.join(' ') will join all the elements of an array by space, but that is not as expected.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:3.5.8
* NodeJS Version:18.18.0
* Operating System: Windows
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
Please give us more information:
- which helper are you using?
- have you tried with latest version?

**Comment by snehabhandge** [comment]
I am using Playwright: 1.40.1 and Puppeteer: 21.7.0 latest versions.

**Comment by kobenguyent** [comment]
Could you help provide a sample repo which we could replicate your issue? We tried but unfortunately we cant reproduce it.

![Screenshot 2024-01-15 at 13 56 29](https://github.com/codeceptjs/CodeceptJS/assets/7845001/3bfadf16-ddb5-48dd-bb06-1b972c21f9f2)
![Screenshot 2024-01-15 at 13 56 40](https://github.com/codeceptjs/CodeceptJS/assets/7845001/a32d831b-d39b-4211-8ceb-09f2d00e47a8)

Closed for now, feel free to reopen with more info.
