### ISSUE TITLE
I.grabTextFrom throwing error for select element in case of Playwright

### ISSUE THREAD

**Issue by snehabhandge** [Codeception/CodeceptJS#4189]
#### What are you trying to achieve?
I wanted to check that something has been selected in dropdown from the options provided. 

#### What do you get instead?
node.textContent works with Puppeteer and Webdriver but doesn't work with Playwright. In case of Playwright it throws xpath issue.
![image](https://github.com/codeceptjs/CodeceptJS/assets/20770459/262d3ad3-d999-416f-b28f-4ff12c4f2f85)

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:3.5.12
* NodeJS Version:18.18.0
* Operating System: windows
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by kobenguyent** [comment]
![Screenshot 2024-02-12 at 11 06 16](https://github.com/codeceptjs/CodeceptJS/assets/7845001/e71b2781-002e-4700-a3e7-1dd2ca5eca52)
grabTextFrom from select works for me with Playwright.

**Comment by snehabhandge** [comment]
It provides all the values and not the selected one.

**Comment by kobenguyent** [comment]
yep, that you could see from my test, it returns all values of select.

**Comment by snehabhandge** [comment]
I want selected option... so that I will be able to check that something has been selected.

**Comment by kobenguyent** [comment]
![Screenshot 2024-02-12 at 15 40 25](https://github.com/codeceptjs/CodeceptJS/assets/7845001/dbbdc5ff-afed-4a3d-9447-0946ffe270ce)

worked fine for me!

Closed for now! Feel free to reopen if you still encounter the issue and would be nice to provide a sample repo to reproduce the issue.
