### ISSUE TITLE
Escaping of apostrophe within XPath expression

### ISSUE THREAD

**Issue by pamoller** [Codeception/CodeceptJS#4196]
#### What are you trying to achieve?
Match //text[contains(text(), 'The Hitchhiker''s Guide to the Galaxy')]

#### What do you get instead?
An error, see below. I checked the XPath expression successfull at https://www.freeformatter.com/xpath-tester.html

> Provide console output if related. Use `--verbose` mode for more details.

```bash
locator.all: DOMException: Failed to execute 'evaluate' on 'Document': The string '//*[@id='project-list']/descendant::*[contains(text(), 'The Hitchhiker''s Guide to the Galaxy')]' is not a valid XPath expression.
    at Object.queryAll (<anonymous>:41:25)
    at InjectedScript._queryEngineAll (<anonymous>:4855:49)
    at InjectedScript.querySelectorAll (<anonymous>:4842:30)
    at eval (eval at evaluate (:226:30), <anonymous>:4:23)
    at UtilityScript.evaluate (<anonymous>:228:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)`````
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:  "^3.5.1-2.beta.7"
* NodeJS Version: v20.7.0
* Operating System: MacOX
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

```js
exports.config = {
    tests: [
        "../../tests/acceptance/*/*.test.js",
        "../../tests/acceptance/*/*/*.test.js",
    ],
    output: '../output',
    helpers: {
        Playwright: {
            url: 'https://localhost:8200/payroll',
            waitForTimeout: 10000,
            show: false,
            video: true,
            browser: 'chromium',
            chromium: {
                args: [
                    '--ignore-certificate-errors'
                ]
            },
            contextOptions: {
                locale: 'de-DE', // Replace with your desired locale
            },
        },
...
```

**Comment by kobenguyent** [comment]
Hey @pamoller may you give it a try with 3.5.12 which is the latest official release?

**Comment by pamoller** [comment]
Hey @kobenguyent thanks, I did an upgrade to the latest version 3.5.12, but it fails again.

````
 locator.all: DOMException: Failed to execute 'evaluate' on 'Document': The string '//*[@id='project-list']/descendant::*[contains(text(), 'The Hitchhiker''s Guide to the Galaxy (Radio Series)')]' is not a valid XPath expression.
    at Object.queryAll (<anonymous>:41:25)
    at InjectedScript._queryEngineAll (<anonymous>:4855:49)
    at InjectedScript.querySelectorAll (<anonymous>:4842:30)
    at eval (eval at evaluate (:226:30), <anonymous>:4:23)
    at UtilityScript.evaluate (<anonymous>:228:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
  locator.all: DOMException: Failed to execute 'evaluate' on 'Document': The string '//*[@id='project-list']/descendant::*[contains(text(), 'The Hitchhiker''s Guide to the Galaxy (Radio Series)')]' is not a valid XPath expression.
      at Object.queryAll (<anonymous>:41:25)
      at InjectedScript._queryEngineAll (<anonymous>:4855:49)
````

**Comment by kobenguyent** [comment]
@pamoller thanks for your test. So the issue because the '' in the locator string is not escaped. 😅

**Comment by pamoller** [comment]
Thanks for your reply @kobenguyent. As I know and tested '' is the correct, escaped version of ' under XPath.

**Comment by kobenguyent** [comment]
@pamoller out of curiosity, why do we have The Hitchhiker''s Guide to the Galax not The Hitchhiker's Guide to the Galax?

**Comment by pamoller** [comment]
@kobenguyent '' is the escpaed version of ' in Xpath

Please try it at: http://xpather.com/

xpath: `//root[contains(text(), 'The Hitchhiker''s Guide to the Galaxy')]`
xml: `<root>The Hitchhiker's Guide to the Galaxy</root>`

I've found an Workaround for codeceptjs using double quotes " in the XPath expression:

````javascript
const name = "The Hitchhiker's Guide to the Galaxy" 
I.click(`//*[@id='project-list']/descendant::*[contains(text(), "${name}")]`);
````

**Comment by kobenguyent** [comment]
```
const name = 'The Hitchhiker\'s Guide to the Galaxy'
I.click(`//*[@id='project-list']/descendant::*[contains(text(), "${name}")]`);
```
I just thought the escape for ' shall be like this

**Comment by pamoller** [comment]
I guess most XPath checkers in the web use libxml2. Sorry I've stopped using XPath and libxml2 15 years ago. Many implementation approaches of Xslt and XPath under node.js seem not so strict as libxml2. But I can't tell if the double-single-quote-escape-mechanism is part of any XPath specifications and should be supported by codeceptjs?

**Comment by kobenguyent** [comment]
My knowledge could be limited here but I guess with JavaScript string, we are using backslash (\) to escape the apostrophe. I hardly see the escape version using double single quotes. 

https://codedamn.com/news/javascript/how-to-escape-a-string-in-javascript

**Comment by pamoller** [comment]
Regarding to your article @kobenguyent, we need the following valid XPath expressions 

````xpath
//*[@id='123'][contains(text(), "The Hitchhiker's Guide to the Galaxy")]
//*[@id='123'][contains(text(), 'The Hitchhiker''s Guide to the Galaxy')]
````
being encoded in Javascript. The template string mechanism works well:

````javascript
`//*[@id='123'][contains(text(), "The Hitchhiker's Guide to the Galaxy")]`
`//*[@id='123'][contains(text(), 'The Hitchhiker''s Guide to the Galaxy')]`
````

But what if the XPath expression includes an apostrophe, double quote and a backtick?

````xpath
//*[@id='123'][contains(text(), '"Barnie`s Hitchhiker''s Guide to the Galaxy"')]
````

The encoding in Javascript works in three different ways using escaping:

````javascript
`//*[@id='123'][contains(text(), '"Barnie\`s Hitchhiker''s Guide to the Galaxy"')]`
'//*[@id=\'123\'][contains(text(), \'"Barnie`s Hitchhiker\'\'s Guide to the Galaxy"\')]'
"//*[@id='123'][contains(text(), '\"Barnie`s Hitchhiker''s Guide to the Galaxy\"')]"
````

Your example from above is also correct: 

````javascript
const name = 'The Hitchhiker\'s Guide to the Galaxy'
I.click(`//*[@id='123'][@id='project-list']/descendant::*[contains(text(), "${name}")]`);
`````
becomes translated to the XPath expression

````xpath
//*[@id='project-list']/descendant::*[contains(text(), "The Hitchhiker's Guide to the Galaxy")]
````

The final problem is if you have mastered the javascript encoding of the XPath expression: 

````xpath
//*[@id='123'][contains(text(), 'The Hitchhiker''s Guide to the Galaxy')]
````

it fails under the XPath engine of codeceptjs. Is it really a bug, because there is an alternative XPath expression which matches the same data?

````xpath
//*[@id='123'][contains(text(), "The Hitchhiker's Guide to the Galaxy")]
````

I don't know, it may not a bug but could be fixed :)

**Comment by kobenguyent** [comment]
Sure @pamoller there is always room for improvements. Looking forward to seeing your PR.

**Comment by pamoller** [comment]
If it is a problem, then by the executing browser context.
