### ISSUE TITLE
retryTo leads to stale process on failure

### ISSUE THREAD

**Issue by cjhille** [Codeception/CodeceptJS#4197]
I'm sorry @kobenguyent, but we must have missed a regression with the last fix here https://github.com/codeceptjs/CodeceptJS/issues/4110

It works fine as long as assertions are a success, but as soon as there is a failure – even outside the retryTo block – the test never terminates.

Simple test code:
```js
Feature('foo');

Scenario('test issue', async ({ I }) => {
    I.amOnPage('http://example.org')
    I.waitForVisible('.nothing', 1); // should fail here but it won't terminate
    await retryTo( (tryNum) => {
        I.see(".doesNotMatter");
    }, 10);
});
```
EDIT: Adding an irregular await before the failing assertion `await I.waitForVisible('.nothing', 1)` will let the promise chain resolve.

<img width="955" alt="image" src="https://github.com/codeceptjs/CodeceptJS/assets/8192226/de370355-0de8-4993-b0a4-64bece67d78a">

**Comment by cjhille** [comment]
The issue still persists (see test case). Unfortunately, `retryTo` can not be used currently. FYI @DavertMik

**Comment by kobenguyent** [comment]
hey @cjhille I reverted those fixes at https://github.com/codeceptjs/CodeceptJS/pull/4117/files#diff-3799cca2cab187279c2a50bbd0c3a7451b24e20da2bdad08d42eb95444d392baR92 but the issue still persists, so I think it's coming from somewhere else.

![Screenshot 2024-05-29 at 07 51 15](https://github.com/codeceptjs/CodeceptJS/assets/7845001/a0f5acb7-ea26-457b-bf84-315b162ded9a)

**Comment by kobenguyent** [comment]
per my initial thinking, I guess the issue is from `waitForVisible` 

![Screenshot 2024-05-29 at 07 57 23](https://github.com/codeceptjs/CodeceptJS/assets/7845001/29bcce41-2209-4adc-88e2-8bf2e621a080)

**Comment by Horsty80** [comment]
@kobenguyent after investigation, we have found that the issue is not about `retryTo` but occurs when a promise reject.

This is enough to stale the process

```ts
Scenario('Rejected promise stale the process', async ({ I }) => {
  await new Promise((resolve, reject) => setTimeout(reject, 500));
})
```

We investigate how to solve this
