### ISSUE TITLE
Using 12 or more Within blocks causes event emitter memory leak

### ISSUE THREAD

**Issue by JPorter1214** [Codeception/CodeceptJS#42]
I am using several Within blocks in my tests, however i have noticed that once i use 12 of them i get this warning:

(node) warning: possible EventEmitter memory leak detected. 11 step.after listeners added. Use emitter.setMaxListeners() to increase limit.

The warning does not seem to cause the scenario to fail.

**Comment by DavertMik** [comment]
Are you using them one by one, or a block within a block? Can you provide an example of such usage?

Probably `within` is not yet optimized to be used that frequently. Or it maybe a basic error when a listeners are not set.

**Comment by JPorter1214** [comment]
I am using them one by one.
  
    within('#IntroductionTitle', ()=>{
      I.see('Introduction')
    })

    within('#CompanyInformationTitle', ()=>{
      I.see('Company Information')
    })

The warning occurs when this pattern continues for 12 or more uses of Within.

**Comment by DavertMik** [comment]
I see, this should be optimized. However, you can use 

```js
I.see('Introduction', '#IntroductionTitle')
I.see('Company Information', '#CompanyInformationTitle');
```
which looks a bit simpler to me )

**Comment by adrianblynch** [comment]
This might be nice:

```
I.see('Introduction').within('#IntroductionTitle');
I.see('Company Information').within('#CompanyInformationTitle');
```

**Comment by DavertMik** [comment]
@adrianblynch yes, this is more readable but why to write more )

**Comment by adrianblynch** [comment]
You answered your own question `more readable` :dancers:

**Comment by DavertMik** [comment]
Looks like listener for `within` was not removed after the block ended, so it caused #79  and probably this. I will close it for now, if issue appears in 0.3.0 - please reopen
