### ISSUE TITLE
Licencing issue with dependency codeceptjs/3.5.14/pactum/3.6.0 lightcookie/1.0.25

### ISSUE THREAD

**Issue by code4muktesh** [Codeception/CodeceptJS#4214]
The package lightcookie is deprecated and Licencing information is not available.

https://github.com/omnent/omnent-licenses/blob/master/licenses/OMv2-FO.txt

### Details

* CodeceptJS version: 3.5.14
* NodeJS Version: 18.x

**Comment by DavertMik** [comment]
I don't see this package in our dependency list 

```
npm ls lightcookie
codeceptjs@3.6.1 /home/davert/projects/codeceptjs
└── (empty)

npm ls pactum
codeceptjs@3.6.1 /home/davert/projects/codeceptjs
└── (empty)
```
