### ISSUE TITLE
There is no support for addScriptTag 

### ISSUE THREAD

**Issue by code4muktesh** [Codeception/CodeceptJS#4226]
Unable to find the way to inject the script into the page using script tag as playwright and puppeteer support the same using addScriptTag.

https://playwright.dev/docs/api/class-page#page-add-script-tag

**Comment by conorpcleary** [comment]
@code4muktesh Would `usePlaywrightTo` work in this scenario?

https://codecept.io/helpers/Playwright/#useplaywrightto 

https://codecept.io/playwright/#accessing-playwright-api

**Comment by DavertMik** [comment]
@code4muktesh  I think you can use custom helper for that

Keep tests clean and follow user scenarios while frontend code as implementation detail can be part of helper
Or pick the advice of @conorpcleary
