### ISSUE TITLE
TypeScript Target ES5 and Generators: cannot grabTextFrom('body)

### ISSUE THREAD

**Issue by philipstanislaus** [Codeception/CodeceptJS#424]
Great work on this project, thanks a lot!

#### What are you trying to achieve?
I am trying to use `yield I.grabTextFrom('body')` in a CodeceptJS test on a TypeScript codebase with target ES5:
```ts
Scenario('sign in', function* (I) {
    // ...
    const body = yield I.grabTextFrom('body')
    // ...
})
```

#### What do you get instead?
Unfortunately, TypeScript does not compile generators for a ES5 target: `error TS1220: Generators are only available when targeting ECMAScript 2015 or higher.`

As an alternative, I tried to use async/await (available with ES5 targets since TypeScript 2.1, see https://blogs.msdn.microsoft.com/typescript/2016/11/08/typescript-2-1-rc-better-inference-async-functions-and-more/) as follows: 
```ts
Scenario('sign in', async function (I) {
    // ...
    const body = await I.grabTextFrom('body')
    // ...
})
```
Which results in 
``` 
> codeceptjs run --steps


missing ) after argument list

/srv/gui/tests/src/end-to-end/Auth/LinkedIn.ts:6
Scenario('sign in with linkedin', async function (I) {
                                  ^^^^^
SyntaxError: 
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /srv/gui/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
```

Do you have any idea how to approach this issue?

Many thanks

Philip

### Details

* CodeceptJS version: 0.4.15
* NodeJS Version: v7.2.0
* Operating System: macOS Sierra 10.12.2
* WebDriverIO: 4.6.1
* Configuration file:

```js
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '/.env'), silent: true });

exports.config = {
  tests: './tests/src/end-to-end/**/*.ts',
  timeout: 10000,
  output: './tests/output/end-to-end',
  helpers: {
    WebDriverIO: {
      url: process.env.GUI_HOST,
      browser: 'chrome',
      restart: true,
      desiredCapabilities: {
        browserName: 'chrome',
      },
      host: 'selenium',
      port: 4444,
    },
  },
  include: {
    I: './tests/config/codecept/custom_steps.js',
  },
  bootstrap: false,
  mocha: {},
  name: 'byll-gui',
};
```

**Comment by DavertMik** [comment]
Ok, looks like neither yield not a async/await will work for you. My suggestion is to create a custom helper with a method inside which will do the `grabTextFrom` using the plain simple promises:

```js
function doSmthWithBody()
{
  let I = this.helpers['WebDriverIO'].browser;
  return I.grabTextFrom('body').then((body) => {
      return; // bla bla bla
  })
}
```

**Comment by philipstanislaus** [comment]
@DavertMik thanks for your quick response, your suggestion works for me 👍 

Just for clarification: 

1. Do you know why async/await works in the rest of the project, but not in CodeceptJS tests?
2. Does CodeceptJS internally await each line of the test scenarios?

**Comment by APshenkin** [comment]
@philipstanislaus 
1. async/await works in CodeceptJS test. I tested it in 8.2.1 node and it works great
2. CodeceptJS based on global promise chain concept. Each step in test returns promise. This promise go to next step and so on. If there is an error in promise chain, we detect it and throw the error. When in your test you need to get some value then you have to use generators or async/await. BTW CodeceptJS guarantied only that predefined steps will complete in right order, but you can create your custom helper with mistakes (e.g. forget to return promise in method) and then face with promises issues.

If you have any other question, please let us know
