### ISSUE TITLE
runOnAndroid/runOnIOS blocks are stuck after upgrading CodeCept from 3.4.1 to 3.5.15 and Appium From 1 to 2.

### ISSUE THREAD

**Issue by kiran-yara** [Codeception/CodeceptJS#4266]
#### What are you trying to achieve? 
We recently upgraded from 3.4.1 to 3.5.15 and from Appium 1 to Appium 2. 

#### What do you get instead?
After the upgrade our scripts started failing inside runOnAndroid/runOnIOS. Failing as in scripts are stuck and dont proceed after default timeout Broswerstack execution is auto killed and scripts stay stuck. 
Please note if I revert back to 3.4.1 and Appium 1 it works as expected

> Console output if related.
Not Applicable as no output is getting printed

```js
        I.runOnAndroid(() => {
            I.waitForElement('Invalid phone number, please try again', 120)
            I.seeElement('Invalid phone number, please try again')
        });
        I.runOnIOS(() => {
            I.waitForElement('Incorrect number Please try again', 120)
            I.seeElement('Incorrect number Please try again')
        });
```

### Details

* CodeceptJS version: 3.5.15
* NodeJS Version: v16.15.1
* Operating System: ANdroid/iOS/Mac Ventura 13
* webdriverio: 8.32.0
* Configuration file:

```js
exports.config = {
    tests: testPath,
    output: '../output',
    timeout: 10000,
    
    helpers: {
        Appium: {
            appiumV2: true,
            host: "hub-cloud.browserstack.com",
            port: 4444,
            user: process.env.YC_BS_USER,
            key: process.env.YC_BS_KEY,
            platform : "android",
            desiredCapabilities: {
              "platformName" : "android",
              "platformVersion" : "10.0",
              "deviceName" : "OnePlus 8",
              "app" : "bs://XXXXXX",
              'bstack:options' : {
                userName : process.env.YC_BS_USER,
                accessKey : process.env.YC_BS_KEY,
                "appiumVersion":"2.4.1",
                "projectName" : "YaraConnect",
              }
            }
        },
      BrowserStackAppAutomate: {
          require: "../tests/helpers/browserStackAppAutomateHelper.js",
          user: process.env.YC_BS_USER,
          key: process.env.YC_BS_KEY,
      },
      AppiumHelper: {
          require: "../tests/helpers/appiumHelper.js",
      },
      REST: {},
      DbHelper: {
          require: "../tests/helpers/dbConnectHelper.js"
      },
      AllureDebugHelper: {
          require: '../tests/helpers/AllureDebugHelper.js',
      }
    },
    include: pageObjects,
    bootstrap: null,
    mocha: {},
    name: 'yc-global-e2e',
    plugins: {
        pauseOnFail: {},
        retryFailedStep: {
            enabled: true
        },
        screenshotOnFail: {
            enabled: true
        },
        tryTo: {
            enabled: true
        },
        allure: {
          outputDir:'allure-results',
          enabled: true,
          require: '@codeceptjs/allure-legacy',
        }
    }
}
```

**Comment by npusnik** [comment]
I have encountered the same issue when upgrading codeceptjs to the latest version (from 3.4.1 to currently latest @3.6.2). This is a very critical bug that needs to be fixed as older versions of Codeceptjs (3.5.0 and under) do no contain the fix for touch/perform actions - they always fail with webdriver 404 error. 3.6.2 on the other hand is able to process touch perform action. This way, I have to choose between runOnIOS / runOnAndroid function OR touch/perform actions which are both very needed. Please fix this issue 🙏

**Comment by kobenguyent** [comment]
![Screenshot 2024-08-13 at 16 31 20](https://github.com/user-attachments/assets/2726c389-50c6-4ca8-b7e3-a76868fc3d34)
our Android tests work fine with `runOnAndroid`, may you try with latest version?

**Comment by npusnik** [comment]
Hi @kobenguyent, I’ve updated all drivers and frameworks to their latest stable versions and tested again. Unfortunately, the issue persists with any runOnAndroid or runOniOS function I attempt to execute.

Here are the versions I am currently using:

CodeceptJS v3.6.5
Appium v2.6.0
 - uiautomator2@2.25.1 (automationName 'UiAutomator2')
 - xcuitest@4.35.0 (automationName 'XCUITest')
 - espresso@2.23.5 (automationName 'Espresso')
 WebdriverIO v7.16.7

**Comment by kobenguyent** [comment]
> Hi @kobenguyent, I’ve updated all drivers and frameworks to their latest stable versions and tested again. Unfortunately, the issue persists with any runOnAndroid or runOniOS function I attempt to execute.
> 
> Here are the versions I am currently using:
> 
> CodeceptJS v3.6.5 Appium v2.6.0
> 
> * uiautomator2@2.25.1 (automationName 'UiAutomator2')
> * xcuitest@4.35.0 (automationName 'XCUITest')
> * espresso@2.23.5 (automationName 'Espresso')
>   WebdriverIO v7.16.7

just noticed your wdio is a bit old, maybe that the issue? Currently codeceptjs is using v8.x https://github.com/codeceptjs/CodeceptJS/blob/3.x/package.json#L172

**Comment by npusnik** [comment]
@kobenguyent I've updated wdio to @8.14.0
I then updated codeceptJS to the latest @3.6.6 and the result is the same - runOnIOS() and runOnAndroid() won't exit. DOwngrading back to codeceptJS @3.5.0 resolves the issue.

**Comment by kobenguyent** [comment]
hey @npusnik not sure if this is the side effect of this fix https://github.com/codeceptjs/CodeceptJS/pull/4018/files

**Comment by kobenguyent** [comment]
@npusnik please try this https://www.npmjs.com/package/codeceptjs/v/3.6.8-beta.1 to see whether it resolves your issue.

**Comment by npusnik** [comment]
@kobenguyent just tried this beta version you've suggested and damn, it works better then ever before. Much faster too. Thanks for the help! 
@kiran-yara can you try it out and confirm it works for you as well?

**Comment by kobenguyent** [comment]
> @kobenguyent just tried this beta version you've suggested and damn, it works better then ever before. Much faster too. Thanks for the help! 
> 
> @kiran-yara can you try it out and confirm it works for you as well?

Thanks for your tests. So sounds like it's likely an issue of superfluous async/await in the code flow.
