### ISSUE TITLE
How to run methods in Before() synchronously?

### ISSUE THREAD

**Issue by c0bra** [Codeception/CodeceptJS#427]
Haven't been able to find anything that covers this exactly in the issues; but I see lots of people have had trouble with getting things to execute synchronously when using helpers/page objects.

I have a PageObject for an admin area. There are two methods I'm trying to run serially: `login` and `setClient`.

When I set up my before, I do:

```javascript
Before((I, adminPage) => {
  adminPage.login();
  adminPage.setClient();
});
```

The problem is that they run in parallel. I need to wait for `login()` to complete before running `setClient()`.

I know I could move all the `I.*()` calls directly into the `Before()` but that defeats the purpose of reusability. What is the preferred method to handle this case?

**Comment by DavertMik** [comment]
Please show the code of your `login`, `setClient` methods, so I could help

**Comment by c0bra** [comment]
@DavertMik sure; sorry about the delay:

```javascript
login(username, password) {
    // Try to go to login url
    I.amOnPage('/superadmin');

    // Should be redirected to login
    I.seeInCurrentUrl('/login?return=/superadmin');

    I.fillField('username', username);
    I.fillField('password', password);

    I.click('Sign in');
},

selectClient: function* selectClient(client) {
    I.click('Clients');
    I.fillField('ng-model="search.name"', client);
    const clientShort = yield I.grabTextFrom('table td:first span');
    I.click(clientShort);
    I.seeInCurrentUrl('/reports/dashboard');
}
```

**Comment by c0bra** [comment]
Seems like maybe this related to #206. If I move `selectClient()` to the test and call it with `yield* selectClient()` it appears to work.
