### ISSUE TITLE
Can't use 'yield' in steps_file.js file.

### ISSUE THREAD

**Issue by dylanzhang123456** [Codeception/CodeceptJS#429]
#### What are you trying to achieve?
I want to define a function and use 'yield this.grabValueFrom(locator)' in steps_file.js file.

But I fail as 'yield' can only use in Scenario, How can I do?
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version:  v0.5.0
* NodeJS Version: v5.3.0
* Operating System: win7_64
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by joeypedicini92** [comment]
This would be extremely helpful

**Comment by imvetri** [comment]
Please share the code sample / a repo where the issue could be reproduced.

**Comment by APshenkin** [comment]
You can use `yield` in steps_file.js this way:
```
        testMethod: function* (locator) {
            return yield this.grabValueFrom(locator)
        },
```

and in your test
Scenario.only('test', function* (I) {
    let value = yield* I.testMethod('//h2')
    console.log(value)
})
