### ISSUE TITLE
In codeceptJS version 3.6.0, an error occurred when using the pause() method

### ISSUE THREAD

**Issue by violet-creat** [Codeception/CodeceptJS#4296]
#### In codeceptJS version 3.6.0, an error occurred when using the pause() method

When I use version 3.6.0, the error message  "AiAssistant.getInstance is not a function"  appears.
![图片](https://github.com/codeceptjs/CodeceptJS/assets/67781446/bad30a48-7742-44ed-b8ce-1015278d3dbe)
![图片](https://github.com/codeceptjs/CodeceptJS/assets/67781446/0dd0293f-061d-48fa-a93d-3b59a222b9e0)

pause() works fine when I use version 3.5.15
![图片](https://github.com/codeceptjs/CodeceptJS/assets/67781446/27c40a84-e7f6-40a3-9c21-7f1ee0218617)
![图片](https://github.com/codeceptjs/CodeceptJS/assets/67781446/75305d13-9aa3-455c-bb69-5286c57c4f1f)
Is this a bug?

**Comment by DavertMik** [comment]
Seems like a bug. Sorry

**Comment by DavertMik** [comment]
Fixed regression in 3.6.1
