### ISSUE TITLE
Using Jquery on codecept

### ISSUE THREAD

**Issue by arsa666** [Codeception/CodeceptJS#43]
Hello, 

Is it posible to use Jquery in codecept to locate element. I personally don't like the yield I.grabTextFrom because it does not work inside a loop. I was wondering is jquery can be used here?

Thanks!

**Comment by arsa666** [comment]
I was able to use jquery with executeScript(); 

=)

**Comment by DavertMik** [comment]
> Is it posible to use Jquery in codecept to locate element. 

I think you are trying to do some complex stuff which is not handled by default actions. No problem. 

But in CodeceptJS tests should be written from a user's perspective. All complex technical stuff can be handled inside a helper. So if you require something custom, please [write your own helper](http://codecept.io/helpers/). And yes, there you can use `executeScript` or locate elements in a different manner of webdriverio

**Comment by arsa666** [comment]
Hi Michael,

I am having trouble getting the grabbers to work with the yield. If I use
yield then the following code execution stops. Can you please help me
figure this out? Or give me an example where I can grab text and then
continue my code execution?

This post is related to that too:
https://github.com/Codeception/CodeceptJS/issues/47

This simple example does not work. Is this a bug in CodeceptJS? or am I
missing something?

Scenario('First Scenario', function* (I) {
let grabberResult = yield I.grabValueFrom('input[name=firstName]');
I.see('XKJSHJDSJXHJSKHXS'); //this should fail, but passes.
});




-- 
================================
Arsalan Ahmed

Senior Software Developer
Email: ahmedarsalank@gmail.com
Tele: +50760041240

**Comment by DavertMik** [comment]
You don't

**Comment by arsa666** [comment]
Thanks for answering. This example is not working:

'use strict';
Feature('Testing Begins');
Before((I) => {
  I.resizeWindow(1500, 1000);
  I.amOnPage('http://absolutenet.com');
});

Scenario('ANI testing', function*(I){
  I.waitForText('bring your site to life');
  I.amOnPage('http://www.absolutenet.com/');
  let title = yield I.grabTitle();
  console.info(title);
  I.see('bogus text that is not there'); //this should give an error and not success.
});

**Comment by DavertMik** [comment]
Thanks. Bug is reproduced

**Comment by DavertMik** [comment]
Done in https://github.com/Codeception/CodeceptJS/commit/d68b2a734ac043b86f05dd512ec17826aef04cad
