### ISSUE TITLE
TypeError: I.amOnPage is not a function

### ISSUE THREAD

**Issue by lets-open-source** [Codeception/CodeceptJS#432]
#### What are you trying to achieve?
trying to run a simple test following the QuickStart on website using codeceptjs init

http://codecept.io/quickstart/

#### What do you get instead?
```bash
j-MacBook-Pro:s j$ codeceptjs run --steps
CodeceptJS v0.5.0
Using test root "/Users/j/s"

title --
 test something
 ✖ FAILED in 2ms


-- FAILURES:

  1) title: test something:
     I.amOnPage is not a function
  
  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 0 passed, 1 failed   // 8ms
j-MacBook-Pro:s j$ 

```
> Provide test source code if related

```js

Feature('title');

Scenario('test something', (I) => {

  I.amOnPage('http://google.com');

});
```
### Details

* CodeceptJS version:  0.5.0
* NodeJS Version: 7
* Operating System: OSX
* Nightmare version: 2.9.1
* Configuration file:

```js

{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {},
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "s"
}

```

**Comment by dylanzhang123456** [comment]
Maybe you need to install webdriverIO,Please use the command:npm install -g webdriverio

**Comment by johnmobify** [comment]
not sure why I need webdriver when I'm using Nightmarejs but I tried it anyways and it still fails.

I think this issue needs to be escalated to **CodeceptJS Quickstart is broken**

**Comment by johnmobify** [comment]
#32

**Comment by lets-open-source** [comment]
Using Nightmare.js

**Comment by pavelKozlov** [comment]
You need to define helpers in codecept.json as described here: http://codecept.io/nightmare/
`{ // ..
  "helpers": {
    "Nightmare": {
      "url": "http://localhost",
      "show": false,
      "restart": false
    }
  }
  // ..
}`

**Comment by APshenkin** [comment]
Closing due inactivity
