### ISSUE TITLE
using values in config

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#434]
#### What are you trying to achieve?
I am setting up a browser testing suite with CodeceptJS. I love this framework a lot!
thanx everybody for developing great tool!

I want to be able to run my suite something like:
codeceptjs run --profile firefox --viewport 1024 ......

how can I make the width variable available in my .js testscript?
I want to use it in my testscripts:
I.resizeWindow(viewport, globals.heigth);

if this can be done, I want (in the end) make a json file in which I can configure
all browsers to test all my viewports in, something like:
{  chrome
     { 1024, 768, 320 }
   firefox
        { 1024, 768, 320 }
   safari 
            { 1024, 768, 320 }
}

### Details

* CodeceptJS version: 0.5.0
* NodeJS Version: 7.6.0
* Operating System: MacOS Sierra
* WebDriverIO 4.6.2
* Configuration file:
{
  "tests": "./*_test.js",
  "timeout": 50000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "timeouts": {
        "script": 60000,
        "page load": 10000,
        "implicit" : 5000,
        "url": "https://beta.belastingdienst.nl/wps/wcm/connect/nl/ondernemers/ondernemers",
        browser : process.profile || "chrome"
      }
    }
  },
  "include": {
    "I": "./steps_file.js",
    "functions": "./pages/global_functions.js",
    "globals":"./globals.js"
  },
  "bootstrap": false,
  "mocha": {
    "reporterOptions": {
      "mochaFile": "output/result.xml",
      "reportDir": "output"
    }
  },
  "name": "menu"
}

**Comment by ChaseVoid** [comment]
You can store your config information in external `my.config.js` file and `require` it in the test cases.

```javascript
// my.config.js
module.exports = {
  "myConfig": {
      "title": "test",
      "completed": false,
    }
}
```
```javascript
// my_test.js
Feature('my');

const CONFIG = require('my.config.js').myConfig;

Scenario('testing config', (I) => {
  const title = CONFIG.title;
  // use title however you want
));
```

**Comment by joelgrimberg** [comment]
thanx for the reply.
I am still struggling with the right approach.
should I make different my.config.js - files , each with their specific viewport settings,
and with starting a test, to 'attach' the right my.config.js file on to the test, 
or could I do something like:

// my.config.js
module.exports = {
  "myConfig": {
      "viewport_a": {
           "viewport A": "1220"
      }
     "viewport_b": {
           "viewport_b": "768"
      }

but then how could I start codeceptjs and set the viewport (ie: codeceptjs run --viewport viewport_a)
    }
}

**Comment by atrevino** [comment]
Did you find a way to do this?

**Comment by joelgrimberg** [comment]
this is the way I am doing it now:
1 feature with 1 testscript (checkFooterDUIPage.checkFooter(CONFIG);),
which I call for every viewport.
I am very interested in what you think of it :)

---
```javascript
Feature('Regressiontest Footer German');

//loading all global variables into constant CONFIG
const CONFIG = require('./globals.js');
const URL = 'https://www.website.com'

Scenario('check Footer DUI - viewport 1220', (I, checkFooterDUIPage) => {
  I.resizeWindow(1220,1000);
  I.amOnPage(URL);
  checkFooterDUIPage.checkFooter(CONFIG);
});

Scenario('check Footer DUI - viewport 1024', (I, checkFooterDUIPage) => {
  I.resizeWindow(1024,1000);
  I.amOnPage(URL);
  checkFooterDUIPage.checkFooter(CONFIG);
});

Scenario('check Footer DUI - viewport 768', (I, checkFooterDUIPage) => {
  I.resizeWindow(768,1000);
  I.amOnPage(URL);
  checkFooterDUIPage.checkFooter(CONFIG);
});

Scenario('check Footer DUI - viewport 320', (I, checkFooterDUIPage) => {
  I.resizeWindow(320,1000);
  I.amOnPage(URL);
  checkFooterDUIPage.checkFooter(CONFIG);
});
```

**Comment by APshenkin** [comment]
I think, we can close this issue. Now we have http://codecept.io/advanced/#multiple-execution ?

**Comment by akapitoha** [comment]
Hi,

so is there a good approach to run same test across several viewport (desktop/mobile for example).
http://codecept.io/advanced/#multiple-execution seems not the best option because of
> Important: you can't use name current for pageObjects or helpers in data scenarios
