### ISSUE TITLE
Async/blocking BeforeSuite, Before, After, AfterSuite hooks

### ISSUE THREAD

**Issue by philipstanislaus** [Codeception/CodeceptJS#436]
#### What are you trying to achieve?

I would like to asynchronously create a test user and a test project over an XHR request before a collection of tests runs.

I expected one of the following to work: 
```js
BeforeSuite((I) => new Promise((resolve) => setTimeout(resolve, 5000)))
Before((I) => new Promise((resolve) => setTimeout(resolve, 5000)))
```

```js
BeforeSuite(function* (I) {
  yield new Promise((resolve) => setTimeout(resolve, 5000))
})
Before(function* (I) {
  yield new Promise((resolve) => setTimeout(resolve, 5000))
})
```

#### What do you get instead?
Instead, the tests progress without any blocking/waiting. Is there any approach I can take to postbone test execution until my prerequisits are fulfilled?

### Details

* CodeceptJS version: v0.5.1
* NodeJS Version: v7.2
* Operating System: MacOS Sierra
* WebDriverIO version: v4.6.2
* Configuration file:

```js
exports.config = {
  tests: './tests/src/end-to-end/**/*.[tj]s',
  timeout: 10000,
  output: './tests/output/end-to-end',
  helpers: {
    WebDriverIO: {
      url: process.env.GUI_HOST,
      browser: 'chrome',
      restart: true,
      desiredCapabilities: {
        browserName: 'chrome',
      },
      host: 'selenium',
      port: 4444,
    },
    TestUser: {
      "require": "./tests/config/codecept/TestUser.js",
    },
    TestBusinessEntity: {
      "require": "./tests/config/codecept/TestBusinessEntity.js",
    },
  },
  include: {
    I: './tests/config/codecept/custom_steps.js',
  },
  bootstrap: false,
  mocha: {},
  name: 'byll-gui',
};
```

**Comment by DavertMik** [comment]
Ok, promises are stored in a global promise chain. There is a way to access it (I will post it below, however it is not documented and not recommended to do so). To attach a promise to a promise chain it should be implemented as a method inside a helper and called inside a test:

```
BeforeSuite((I) => {
   I.doSomethingBeforeStart();
});
```

`doSomethingBeforeStart` should be defined inside a [custom helper](http://codecept.io/helpers/) as a regular method returning a promise:

```
doSomething() {
    new Promise((resolve) => setTimeout(resolve, 5000))
}
```
Once the helper is enabled you can use its method inside Before/BeforeSuite.

---

Alternatively you can access a promise chain on your own

  ```js
  const recorder = require('codeceptjs/lib/recorder');

  Before(function() {
     recorder.add(new Promise((resolve) => setTimeout(resolve, 5000)));
  });
  ```

**Comment by DavertMik** [comment]
I think it would be a good idea to implement handling of promises in Before/After in a next version. So probably its a good idea for a feature

**Comment by philipstanislaus** [comment]
Awesome, thanks for your quicke response, @DavertMik!

**Comment by philipstanislaus** [comment]
I just looked into this again, and have 2 questions:

---------------

The second version (accessing the promise chain) does not work for me: 
```js
// example2.js
const recorder = require('codeceptjs/lib/recorder')

Feature('Example2')

Before(function (I) {
  recorder.add(new Promise((resolve) => setTimeout(() => {
    resolve()
    console.log('5 secs are over')
  }, 5000)))
  I.say('Before should have waited for 5 secs')
})

Scenario('Test scenario', function* (I) {
  I.say('Starting test')
  I.amOnPage(`/`)
})
```

Output:
```sh
> node_modules/.bin/codeceptjs run --steps . example2.js
CodeceptJS v0.5.1
Using test root "/Users/philipstanislaus/Code/basement-startup/byll-gui"

Example2 --
 Test scenario
   Before should have waited for 5 secs
   Starting test
 • I am on page "/"
 ✓ OK in 1199ms


  OK  | 1 passed   // 2s
5 secs are over
```
("5 secs are over" should have come first, instead the suite passes in 2s)

**a) What is wrong here?**

---------------

Your first method works as follows: 
```js 
// Example.js
class Example extends Helper {
  fetchUser() {
    return new Promise((resolve) => setTimeout(() => {
      resolve({ name: 'Cleopatra' })
      console.log('5 secs are over')
    }, 5000))
  }
}

module.exports = Example


// example1.js
Feature('Example1')

Before(function (I) {
  I.fetchUser()
  I.say('Before should have waited for 5 secs')
})

Scenario('Test scenario', function* (I) {
  I.say(`Starting test`)
  I.amOnPage(`/`)
})
```

Output:
```sh
> node_modules/.bin/codeceptjs run --steps . example1.js                     
CodeceptJS v0.5.1
Using test root "/Users/philipstanislaus/Code/basement-startup/byll-gui"

Example1 --
 Test scenario
 • I fetch user 
5 secs are over
   Before should have waited for 5 secs
   Starting test
 • I am on page "/"
 ✓ OK in 993ms


  OK  | 1 passed   // 7s
```

**Yet it does not seem to work with generator functions as tests do, is that expected?**

Example:
```js 
// Example.js
// same as above...

// example1.js
Feature('Example1')

let user

Before(function* (I) {
  yield user = I.fetchUser()
  I.say('Before should have waited for 5 secs')
})

Scenario('Test scenario', function* (I) {
  I.say(`Starting test with user ${user}`)
  I.amOnPage(`/`)
})
```

Output: 
```sh
> node_modules/.bin/codeceptjs run --steps . example1.js                     
CodeceptJS v0.5.1
Using test root "/Users/philipstanislaus/Code/basement-startup/byll-gui"

Example1 --
 Test scenario
   Starting test with user undefined
 • I am on page "/"
 ✓ OK in 1163ms


  OK  | 1 passed   // 2s
```
(Does not even output "Before should have waited for 5 secs" or "5 secs are over"

**Comment by sveneisenschmidt** [comment]
@philipstanislaus Hey, have you found a way yet to achieve asynchronous calls in before hooks?

**Comment by philipstanislaus** [comment]
@sveneisenschmidt unfortunately I have not, I used a test to achieve what I wanted. Let us know if you find a solution!

**Comment by sveneisenschmidt** [comment]
@DavertMik Hey ☺️, do you think this is something we can see as a feature in one of the upcoming releases?
>I think it would be a good idea to implement handling of promises in Before/After in a next version. So probably its a good idea for a feature

Otherwise, I haven't had a look into the internal code yet, but I would be glad to help out as well. Maybe you can point me to a specific part of the code that needs to be extended to support promises and/or generators in Before/After hooks.

Any feedback is appreciated, have a nice day ☺️

**Comment by sveneisenschmidt** [comment]
@DavertMik @philipstanislaus My lovely co-workers found a solution. Will post an update tomorrow.

**Comment by sveneisenschmidt** [comment]
**node version**: v8.1.3

```
Feature('Title');

Before(function(I, Page) {
    return (async () => {
        Page.LandingPage.open(100, 'de_DE', 5001);
        const text = await I.grabTextFrom('body h1');

        console.log(text);
    })();
});

Scenario('test something', function (I, Page) {
    pause();
});
```

**Comment by APshenkin** [comment]
async/await can be used in `Before/After`
Generators support will be in next releases https://github.com/Codeception/CodeceptJS/issues/206
