### ISSUE TITLE
WebdriverIO - mandatory URL

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#438]
#### What are you trying to achieve?
trying to understand the principle of mandatory URL in codecept.conf.js

### so whats the problem?
in my config I have use the mandatory 'URL' .
in the beginning of my script I say 'goto url', to tell the browser where to start.
why is it then, that I still have to use the URL in my config? 

my codecept.conf.js:
"WebDriverIO": {
      // load variables from the environment and provide defaults
      "url": process.env.CODECEPT_URL || 'http://www.ad.nl',
      "browser" : process.profile || "phantomjs"
    }

my script:
Scenario('Scenario 2', (I, functions, globals) => {
  I.say('viewport:' + globals.viewport,globals.heigth);
  I.resizeWindow(globals.viewport,globals.heigth);
  I.amOnPage(globals.url);

**Comment by ChaseVoid** [comment]
You can leave the url config blank. It is used to set the url relative to the option set via I.amOnPage()'s parameter.

**Comment by APshenkin** [comment]
Closing due inactivity
