### ISSUE TITLE
Can I grab text from the browser without using the yield?

### ISSUE THREAD

**Issue by arsa666** [Codeception/CodeceptJS#44]
Can I grab text from the browser without using the yield? I need to grab the value of many div's and add them up and then test against the result of the addition to see if its working well. Is there a way to grab text without using the yield? I don't like the yield because it terminates my script and the rest of the test don't get executed.

**Comment by DavertMik** [comment]
Sorry for delay.
Right now (3 mins ago) usage of yield should be fixed so your test should proceed even after yield is called. Otherwise you can use helper class to define your own methods using webdriverio api

**Comment by DavertMik** [comment]
Yield should work starting from 0.2.5
