### ISSUE TITLE
Navigate to Iframe and click on an element

### ISSUE THREAD

**Issue by bhupendraparihar** [Codeception/CodeceptJS#442]
### Details

* CodeceptJS version: latest
* NodeJS Version: 6
* Operating System: OS X
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by bhupendraparihar** [comment]
I am trying to use "nightmare-iframe-manager" plugin to click on an iframe element. I am not able to access the nightmare instance in my helper. `require('nightmare-iframe-manager')(this.Nightmare);` Any suggestion would be fine as I need to write some acceptance test with iframe support.

**Comment by imvetri** [comment]
BP, Do you want to go with nightmare iframe manager route ? Because within can help to achieve the same.

**Comment by imvetri** [comment]
This issue can be closed as it is fixed by https://github.com/Codeception/CodeceptJS/issues/450
