### ISSUE TITLE
WebDriverIO and Opera v43 : the browser does not launch

### ISSUE THREAD

**Issue by adeleco** [Codeception/CodeceptJS#444]
#### On windows 10, I'm trying to run tests on opera, using webdriverIO. My codecept.json is : 

```bash
    ...
    "WebDriverIO": {
      "url": "http://www.mysite.com",
      "browser": "opera",
      "windowSize": "1152x1000",
      "show": true
      }
    ...
```
I'm using the latest selenium server 3.3.0 and the latest operadriver.exe 0.2.2
opera version is : 43.0.2442.1144 (PGO)

#### the opera browser does not even launch. (Note that IE, Chrome, Edge, Firefox correctly launch)

> console output:

```bash
 > Error: The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{rotatable=true, marionette=false, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@aa592c, browserName=opera, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]
Build info: version: '3.3.0', revision: 'b526bd5', time: '2017-03-07 11:21:31 -0800'
System info: host: 'xxxxxxx', ip: 'xxx.xxx.xxx.xxx', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
```
#### Details

* CodeceptJS version: 0.5.1
* NodeJS Version: 7.5.0
* Operating System: Win10
* WebDriverIO: 4.6.2

#### What do I miss ? 
thanks for your help.

**Comment by DavertMik** [comment]
Please try to reproduce this issue using the webdriverio library only. It's pretty simple, just follow the instructions at http://webdriver.io
CodeceptJS is just a wrapper on top of webdriverio and I think we couldn't either break or fix this kind of things.

**Comment by adeleco** [comment]
The opera webdriver is currently not maintained. To use the opera browser, we have to use the chrome webdriver and specify to use another binary than the default one.

I've put below a sample of my codecept.json 

```
 "helpers": {
    "WebDriverIO": {
      "url": "http://www.mysite.com",
      "browser": "chrome",
      "windowSize": "1152x1000",
      "show": true,
      "desiredCapabilities": {
        "browsername": "opera",
        "chromeOptions": {
          "binary": "C:\\Program Files (x86)\\Opera\\43.0.2442.1144\\opera.exe"
        }
      }
    }
```

for OSX the binary entry may be : 

```
"binary": "/Applications/Opera.app/Contents/MacOS/Opera"
```

Thanks all.

**Comment by SpenserJulia** [comment]
Now it's not working
