### ISSUE TITLE
printing page via browsers print-function

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#445]
#### What are you trying to achieve?
I want to automate the use of the browsers print-function to check whether the printed version is readable.

does Selenium / Codeceptjs support the browsers print-function?

**Comment by APshenkin** [comment]
Unfortunately, Selenium hasn't access to print functions. Maybe you can try to automate it using https://www.npmjs.com/package/autoit . Currently there is no solution for CodeceptJS and I'm not sure, that this can be easily created. Send PR, If you will have an prototype
