### ISSUE TITLE
Error handling suggestion for `AfterSuite` Hook

### ISSUE THREAD

**Issue by laxmikant-parate** [Codeception/CodeceptJS#4466]
#### What are you trying to achieve?
!!! This is not a bug, just a suggestion !!!

Suppose I have 2 scenarios and 1 `AfterSuite` hook in a file and while execution both the scenarios passed but the `AfterSuite` hook failed, it shows as `FAIL  | 2 passed, 1 failed`. This creates confusion, it may better show as 2 passed and the `AfterSuite` hook failed.

**Comment by mirao** [comment]
I'm afraid the bug fix is in a conflict with the behavior I would expect, see my comment https://github.com/codeceptjs/CodeceptJS/pull/4476#issuecomment-2534935914

**Comment by mirao** [comment]
> I'm afraid the bug fix is in a conflict with the behavior I would expect, see my comment [#4476 (comment)](https://github.com/codeceptjs/CodeceptJS/pull/4476#issuecomment-2534935914)

It was fixed in https://github.com/codeceptjs/CodeceptJS/pull/4633
