### ISSUE TITLE
Question: is there a way to send parameters to Nightmare Helper?

### ISSUE THREAD

**Issue by atrevino** [Codeception/CodeceptJS#453]
I'ld like to test this workaround posted in Electron repo
https://github.com/electron/electron/issues/7235

is about to executing the test with `ignore-certificate-errors` parameter.

**Comment by imvetri** [comment]
can you elaborate little more ?

**Comment by atrevino** [comment]
So what I was thinking to do is use something like WebDriverIO's desired capability "acceptSSLCerts" on config file, but as it didn't work for me I checked out different options, one of them was Nightmare. (I already raise an issue for the ignored desired capability #452 )

What I was expecting to do is to run CodeceptJs with a flag argument for nightmare like
`codecept run nightmare --ignore-certificate-errors` but as I read through the docs and code, seems this is not possible.

My second choice is use it (the `ignore-certificate-errors` flag) from Nightmare helper configuration, but doesn't seems to be a valid option for now.

May be will be good to pass options like this through CLI to the helper, and from there send it to the library itself to use CodeceptJs as a bridge for some Helpers.

**Comment by imvetri** [comment]
How about creating a new property in codecept.config file?

These values gets passed to nightmare constructor function from codecept constructor function.

**Comment by APshenkin** [comment]
https://github.com/Codeception/CodeceptJS/issues/512
