### ISSUE TITLE
Post a request with parameters

### ISSUE THREAD

**Issue by rusuOana** [Codeception/CodeceptJS#46]
Hello,

I was trying codeceptjs this days and I was trying to post a request to a url with 2 params. Is that possible?

What I want to do is something like:
        I.amOnPage('/');
    I.waitForElement('#login-page', 5); // secs
    request
            .post('http://0.0.0.0')
            .type('form')
            .set('Accept', 'application/json')
            .send({ ssid: '#something', id: '#something'})
            .end(function(err, res){
           }

The request part is taken from Protractor code. Is it possible to do something similar in Codeceptjs?

Thank you.

**Comment by adrianblynch** [comment]
Have you tried it?

It's just JavaScript so I don't see why you couldn't send a request.

**Comment by rusuOana** [comment]
I tried with the following code:

Scenario('login', (I) => {
	I.amOnPage('/');
	I.waitForElement('#login-page', 5); // secs
	I.wait(5)
	request
        .post('http://0.0.0.0:9999')
        .type('form')
        .set('Accept', 'application/json')
        .send({ ssid: loginPage.sessionId, remember_me_id: 'remember_me_id_1'})
  		.end(function(err, res){
          if (err) {
            console.log('ddddddd')
          } else {
            console.log('ffffff')
          }
      })

And I get the following output:

Login --
 login
 • I am on page "/"
ddddddd
 • I wait for element "#login-page", 5
 • I wait 5

It doesn't even seem to wait the few seconds before it tries the request. Any ideas why this might happen?

**Comment by rusuOana** [comment]
The request itself works, but it works in an async way. What I want to do is to load a page, get an id, then send a post request with that id and wait for the page to reload.

What it actually does now is to do the post in an async way, and the test finishes by the time the request is done, the other steps do not wait after this request.

Is there a way to do the request using one of the I.something methods?
Or could I use promises for this particular case to handle the request?

**Comment by adrianblynch** [comment]
Are you trying to go to a new page with the request?

**Comment by rusuOana** [comment]
The page that I am currently on should refresh once the post request is sent.

But the scenario ends before the request is sent

**Comment by adrianblynch** [comment]
Sending a request from your test code won't send the request from the browser you're testing in.

If you want to move paging within a test, use `I.amOnPage()`:
```
Scenario('Successful login', I => {
	I.amOnPage('/first-page.html')
	// Test stuff here
	I.amOnPage('/second-page.html)
})
```

If that's not what you're after, let us know. Also, should all your code.

**Comment by APshenkin** [comment]
As I know, you can't send request from browser using Selenium. The best option is to create custom helper that uses sync-request library https://www.npmjs.com/package/request-sync

Then you can create custom methods in your helper to send requests. And Also after request you can use recieved data in your selenium test. E.g. below is a helper that get auth token and set it to cookies
```
const request = require('sync-request');
const BASE_URL = codeceptConfig.helpers.WebDriverIO.url;

setLoginCookieFor(username, password) {
        let client = this.helpers['WebDriverIO'].browser;
        let res = request('POST',
            BASE_URL + '/api/login/', {
                json: {
                    "username": username,
                    "password": password
                }
            });

        let reqs = res.body.toString()
        let cookies = [];

        let domain = BASE_URL
        let secure = (domain == 'we.testdomain.ru');

        res.headers['set-cookie'].forEach(function (cookie) {
            let parts = cookie.split(/[;=]/g);
            cookies.push({
                name: parts[0],
                value: parts[1],
                domain: domain,
                secure: secure,
                path: '/'
            });
        });


        client.addCommand('loadCookies', function (cookies) {
            var self = this;
            return cookies.reduce(function (promiseChain, currentCookie) {
                return self.setCookie(currentCookie)
            }, cookies[0]);

        }, true);

        return client.loadCookies(cookies);
    }
```
Closing this issue, create a new one if you have any questions or ask in gitter chat
