### ISSUE TITLE
Nightmare stacktrace on failure

### ISSUE THREAD

**Issue by DavertMik** [Codeception/CodeceptJS#460]
#### What are you trying to achieve?

Running Nightmare on CI server in headless environment

#### What do you get instead?

Script fails with no error message

### Details

Probably Nightmare can't start Electron as xvfb is not installed but that should print the cause

**Comment by APshenkin** [comment]
https://github.com/segmentio/nightmare/issues/1233

**Comment by DavertMik** [comment]
Thanks!

**Comment by reubenmiller** [comment]
Issue should be tracked on the nightmarejs repo
