### ISSUE TITLE
Parallel execution of multiple browsers on sauce labs using Codecept is not working

### ISSUE THREAD

**Issue by pskushw** [Codeception/CodeceptJS#464]
#### What are you trying to achieve?
Parallel execution of multiple browsers for an individual test file on sauce labs using CodeceptJS.

#### What do you get instead?
Tests are running on only one browser instead of multiple browsers where multiple browser capabilities are defined in desiredCapabilities in config file.

### Details

* CodeceptJS version: 0.5.0
* NodeJS Version: 6.9.2
* Operating System: OS X EI Capitan (v10.11.6)
* Protractor || WebDriverIO || Nightmare version (if related) : WebDriverIO (v4.6.2)
* Configuration file: codecept.conf.js
```
{
	"tests": "./lib/functional/run.functional.suite.js",
	"timeout": 20000,
	"output": "OUTPUT FOLDER PATH",
	"helpers": {
		"Codecept": {
			"require": "./lib/codecept/helpers.js"
		},
		"WebDriverIO": {
			"url": "http://localhost:3000",
			"browser": "firefox",
			"waitforTimeout": 60000,
			"restart": false,
			"logLevel": "silent",
			"cssSelectorsEnabled": "true",
			"timeouts": {
				"script": 60000,
				"page load": 60000,
				"implicit": 0
			},
			"desiredCapabilities": [{
				"browserName": "firefox",
				"name": "TEST_FIREFOX",
				"platform": "ANY",
				"version": "51.0"      
			}, {
				"browserName": "chrome",
				"name": "TEST_CHROME",
				"platform": "ANY",
				"version": "55.0"      
			}],
			 "host": "ondemand.saucelabs.com",
			 "port": 80,
			 "user": "USER_NAME",
			 "key": "USER_KEY"
		}
	},
	"include": {
		"I": "./lib/codecept/steps.js"
	},
	"mocha": {
		"reporterOptions": {
			"mochaFile": "MOCHA_FILE_PATH"
		}
	},
	"name": "ANY NAME"
}
```

**Comment by APshenkin** [comment]
The WebdriverIO multiremote works not clear with codeceptjs, use multiple execution option instead of it http://codecept.io/advanced/#multiple-execution
