### ISSUE TITLE
I.fillField not working with an exclamation point

### ISSUE THREAD

**Issue by thienan88** [Codeception/CodeceptJS#467]
#### What are you trying to achieve?
I am trying to fill a field with an exclamation point, but the exclamation point is not showing.

#### What do you get instead?
All the other letters, and also question mark, but the exclamation point no... :(

```js
# I.fillField('input[id=login]', 'test?!aa,dlsoe^');

```

* CodeceptJS version: 0.5.1

**Comment by DavertMik** [comment]
Which helper are you using?

**Comment by APshenkin** [comment]
Closing due inactivity
