### ISSUE TITLE
Ability to have dynamic scenarios

### ISSUE THREAD

**Issue by joeypedicini92** [Codeception/CodeceptJS#468]
I am currently looping through all possible values for a dropdown and filling out the form associated with each value. I'd like each case to be a separate scenario so that one failure doesn't cause my test suite to fail. I just want that particular dropdown value to fail and keep going. 

Something like this:

```
for (let i = 0; i < dropdown.length; i++) {
 Scenario(dropdown[i], function() {
     //do stuff and test this dropdown value's dynamic form. If it fails, go to next scenario
 });

}
```

**Comment by DavertMik** [comment]
I think you can actually try to generate Scenarios dynamically the way you proposed in code. Did you try to do that?

**Comment by joeypedicini92** [comment]
@DavertMik you are completely right...I was looping through values which I was setting in a previous scenario so I had to do some shifting and put everything I wanted to set in an _init() call, but it worked.
