### ISSUE TITLE
Sometimes codeceptjs will crash running with nmp/yarn scripts

### ISSUE THREAD

**Issue by junguchina** [Codeception/CodeceptJS#469]
### Details

* CodeceptJS version: v0.18.1
* NodeJS Version:v7.0.0
* Operating System:ubuntu 14.04
* Protractor || WebDriverIO || Nightmare version (if related): WebDriverIO
* Configuration file:NA
* Package.json:
```
"scripts": {
    "setup": "yarn global add codeceptjs && yarn global add webdriverio && yarn global add selenium-standalone@latest",
    "selenium": "selenium-standalone install && selenium-standalone start",
    "xml": "codeceptjs run --reporter mocha-junit-reporter",
    "html": "codeceptjs run --reporter mochawesome",
    "lint": "eslint tests",
    "lint-fix": "eslint --fix tests"
  }
```
* I run tests with below command:
```
yarn run html
```
* But sometimes,it will crash during the testing,pls refer the detail log:
```
+ yarn run html
yarn run v0.18.1
$ codeceptjs run --reporter mochawesome 
more test cases......
Done in 710.33s.
```
* After codeceptjs crashs,it will not produce test report.And can not catch the shell scripts error.
This will mark the CI result as passed,but it is failed actually.

**Comment by APshenkin** [comment]
@junguchina Could you add `--verbose` flag in npm/yarn scripts and provide detailed logs? Also examples of executable tests will be useful

**Comment by APshenkin** [comment]
Close due inactivity
