### ISSUE TITLE
codeceptJS / webdriverIO exits script with grab commands

### ISSUE THREAD

**Issue by tduncklee** [Codeception/CodeceptJS#47]
codeceptJS / webdriverIO exits script with grab commands
--------------------
Somehow my post ended up in the codeception list so posting again here in hopes that it will be in the correct place...

I'm new to codeceptJS but best I can tell it simply does not work with yield.

```
'use strict';
Feature('Testing Begins');
Before((I) => {
  I.resizeWindow(1500, 1000);
  I.amOnPage('http://absolutenet.com');
});

Scenario('ANI testing', function*(I){
  I.waitForText('bring your site to life');
  I.amOnPage('http://www.absolutenet.com/');
  let title = yield I.grabTitle();
  console.info(title);
  I.see('bogus text that is not there');
});
```

I have tried several of the grab commands as well as executeScript. I know the commands are working because for some reason one or two lines do execute after the yield so I can output the variable I am assigning. However, I can never use it because the browser closes and the script terminates. Even worse, I can put in a test that is obviously invalid (I.see('some bogus non existent text');) and the Scenario exits with a Success!

The above is live so you can execute it to see the problem. This happens with Firefox and Chrome on Linux and Mac.

**Comment by tduncklee** [comment]
Thanks for the update on twitter that you hope to have a fix this week! :-)

**Comment by DavertMik** [comment]
Should be fixed now. Please try, I also included your test to examples list: https://github.com/Codeception/CodeceptJS/blob/master/examples/absolutenet_test.js
