### ISSUE TITLE
How to run the server automatically when executing the test cases?

### ISSUE THREAD

**Issue by PoojaMittal27** [Codeception/CodeceptJS#475]
I want to run the server automatically through the code so i just need to run the test cases.

**Comment by DavertMik** [comment]
We have bootstrap/teardown option which can be used for such cases. Launch a server in bootstrap and stop it in teardown http://codecept.io/hooks/#bootstrap-teardown

**Comment by APshenkin** [comment]
Closing due inactivity

**Comment by wahengchang** [comment]
Hi guys, I can boostrap a `express` server by config of codeceptjs, but how can I turn it off when all the tests is done ?

**Comment by jnv** [comment]
In case someone hits this issue from search engine like I did, there are multiple ways you can approach this in practice:

- You can expose an API for your server, which is kinda implied in the documentation (e.g. your server module exports `launch` and `stop` functions.
- You can use [child_process](https://nodejs.org/api/child_process.html) to [`exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) a new node process with your server file, store the ChildProcess object in a variable and then use `kill` to stop it inside the teardown / teardownAll.
- You can use [Worker threads](https://nodejs.org/api/worker_threads.html) to start the server in a thread and then `terminate` it.

**Comment by jnv** [comment]
Even easier: Use [jest-process-manager](https://github.com/playwright-community/jest-process-manager). Despite the name, it is not dependent on Jest in any way and it has very convenient API for bootstrap and teardown.
