### ISSUE TITLE
How can I run my test scripts for multiple browsers without running script for multiple times?

### ISSUE THREAD

**Issue by PoojaMittal27** [Codeception/CodeceptJS#476]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version: 
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by imvetri** [comment]
is this relevant to https://github.com/Codeception/CodeceptJS/issues/464 ?

**Comment by PoojaMittal27** [comment]
yes

**Comment by DavertMik** [comment]
Maybe this new feature will work for you? http://codecept.io/advanced/#multiple-execution

**Comment by joelgrimberg** [comment]
thanx for this great new feature, Michael !
next challange: adding CrossBrowserTesting.com - configuration to your config file;
how do I send my tests through CBT on different CBT-configurations at the same time
(multiple execution via CBT) in the same config as my local multiple execution-configfile.

so my challenge in short:
1 config file, in which I can choose to do a local multiple execution or a CBT multiple execution.

**Comment by shrikanthkm07** [comment]
Can someone please provide a working example for this multiple browser implementation? I tried but its not working properly. Some simple example with config pls.

**Comment by APshenkin** [comment]
@joelgrimberg looks like you just need to use this documentation https://help.crossbrowsertesting.com/selenium-testing/frameworks/webdriver-io/

Or you want to run the same tests on different platforms? If yes, please create new issue about this, will think, what can be done for this.

Closing this issue, to run  multiple browsers  use http://codecept.io/advanced/#multiple-execution
