### ISSUE TITLE
How to check url change after login

### ISSUE THREAD

**Issue by vitaly87** [Codeception/CodeceptJS#477]
Hi all.
I am new here :)

How can I check if url change after login to know that the login was success....

Tnx!

**Comment by imvetri** [comment]
As an acceptance test, assert for visually expected element rather than URLs. It's the right approach.

For example ,,if I'm logging to Facebook , I would have a test that will assert whether I'm seeing my profile pic.

**Comment by DavertMik** [comment]
Use 

```js
I.seeCurrentUrlEquals('/new/page/url')
```

**Comment by vitaly87** [comment]
@DavertMik  but did i need to wait for it because the login take some time...
