### ISSUE TITLE
Cannot find module 'codeceptjs/helper'

### ISSUE THREAD

**Issue by acailly** [Codeception/CodeceptJS#48]
I tried to create an helper with the command 'codeceptjs gh'.
I immediatelly run 'codeceptjs run --steps' and I get the following error : Cannot find module 'codeceptjs/helper'
This require was generated by the 'gh' command. 

I really just did what's on the website, any idea why it doesn't work as expected ?

Additionnal info :
I installed codecept globally as done in the quickstart.
I use node 4.2.2
I use codecept 0.2.4

**Comment by DavertMik** [comment]
Should be fixed now and in 0.2.5

You should regenerate your helper file. Instead of `require('codeceptjs/helper')` you can use `codecept_helper` to set a parent for your Helper

**Comment by acailly** [comment]
It works, thanks
