### ISSUE TITLE
[Ask] Couldn't attach image

### ISSUE THREAD

**Issue by yogieputra8** [Codeception/CodeceptJS#483]
#### What are you trying to achieve?
I am trying to attach image in my Acceptance test. I am using codeceptJS with Nightmare as helper. Everything pass, but when I check the Database, the data is not saved. How to solve this issue?

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash 
 Problem with account - need help (with attachment)
 • I am on page "/contact-us"
 • I see "Hi everyone,"
 • I click "Account"
 • I wait 2
 • I click "Problem with account"
 • I wait 2
 • I click "Ya, I need other help"
 • I wait 2
 • I append field "ticket_reply_msg", "[Acceptance Test - data_akun_dihack] Lorem ipsum dolor sit amet, of type and scrambled it to make a type specimen book."
 • I append field "full_name", "Joss Groban"
 • I append field "user_email", "joss@gmail.com"
 • I wait 2
 • I attach file "#pickfiles-nav1", "tes_img.jpg"
 • I wait 2
 • I click "Submit"
 • I wait 2
 • I save screenshot "debug.png"
 ✓ OK in 38491ms

  OK  | 1 passed   // 38s
```
> Provide test source code if related

``` 
var data_ = {
    message: "[Acceptance Test - data] Lorem ipsum dolor sit amet, of type and scrambled it to make a type specimen book.",
    name: "Joss Groban",
    email: "joss@gmail.com"
}

Scenario('Problem with account - need help (with attachment)', (I) => {
    I.amOnPage('/contact-us');
    I.see('Hi everyone,');
    I.click('Account');
    I.wait(2);
    I.click('Problem with account');
    I.wait(2);
    I.click('Ya, I need other help');
    I.wait(2);
    I.appendField('ticket_reply_msg', data_.message);
    I.appendField('full_name', data_.name);
    I.appendField('user_email', data_.email);
    I.wait(2); 
    I.attachFile('#pickfiles-nav1', 'tes_img.jpg');
    I.wait(2);
    I.click('Submit');
    I.wait(2);
    I.saveScreenshot('debug.png'); 
});
```
### Details

* CodeceptJS version: v0.6.1
* NodeJS Version: v7.7.2
* Operating System: MacOS Sierra
 

This is the HTML, CSS code:
<img width="854" alt="screen shot 2017-04-20 at 5 14 28 pm" src="https://cloud.githubusercontent.com/assets/6022596/25225819/fd80c6ce-25ec-11e7-9bb5-e250e01ac5a8.png">

**Comment by sawuk1** [comment]
Path to file is relative current codecept directory (where codecept.json is located).
![1493041894539](https://cloud.githubusercontent.com/assets/24719488/25340406/56463842-290e-11e7-9259-a018009ce713.jpg)

**Comment by yogieputra8** [comment]
Here's my project structure mate (my img is already in the same folder with codecept.json):
<img width="206" alt="screen shot 2017-04-24 at 8 57 13 pm" src="https://cloud.githubusercontent.com/assets/6022596/25340662/aaa274e2-2930-11e7-8dfd-3aa7e3773d1d.png">

Do I need to separate my img in another folder?

**Comment by okarkusha** [comment]
Yes, create folder data

**Comment by APshenkin** [comment]
@yogieputra8 Have you solved this issue by moving the image in another folder?

**Comment by APshenkin** [comment]
Close due inactivity
