### ISSUE TITLE
[Question] How can I get test name and pass/fail status in a helpers _after method?

### ISSUE THREAD

**Issue by waryhermit** [Codeception/CodeceptJS#486]
I would like to know the name of the test that just finished and if it passed or failed. I need this to properly annotate my test results via Suacelabs REST API.

**Comment by DavertMik** [comment]
You can have a custom hook which will listen `event.test.passed` and `event.test.failed` See http://codecept.io/hooks/#api

**Comment by waryhermit** [comment]
@DavertMik Thanks
