### ISSUE TITLE
Not able to click on element in safari browser

### ISSUE THREAD

**Issue by PoojaMittal27** [Codeception/CodeceptJS#487]
The issue is for safari browser when I run the script I am not able to click on any button or link

**Comment by imvetri** [comment]
Please share more details if you have.

**Comment by PoojaMittal27** [comment]
The issue is resolved. This was a compatibility issue. Selenium 3.3.1 is not compatible with safaridriver 2.48 so I used Selenium 2.48 version. Now it is working perfectly fine.
