### ISSUE TITLE
Test cases are passing on iOS but failing on android emulator

### ISSUE THREAD

**Issue by shrikanthkm07** [Codeception/CodeceptJS#489]
#### What are you trying to achieve?
Test cases are passing on passing on iOS but same test cases are failing in android emulator in sauce labs.
#### What do you get instead?
Test case fails after 7-8 minutes on android emulator on sauce labs.

### Details

* CodeceptJS version: 0.5.0
* NodeJS Version: 6.9.2
* Operating System:OS X EI Capitan (v10.11.6)
* WebDriverIO : 4.6.2
* Configuration file: codecept.conf.js

```js
"desiredCapabilities":{
     "android": {
        "deviceName": "Android Emulator",
        "browserName": "Browser",
        "name": "TEST_ANDROID",
        "deviceOrientation": "portrait",
        "platform": "Android",
        "version": "5.1"
    }
 }
```
What is wrong in this? Can someone help me ?

**Comment by joelgrimberg** [comment]
what is the output if you use --verbose ?

**Comment by shrikanthkm07** [comment]
Hi @joelgrimberg,
I am trying to check if I can see the element after a click operation is performed. I.see("element CSS path"). The css path is correct but still I.see fails which means it is not able to find element. --verbose won't give any logs since this is a test condition fail.

Thanks,
Shrikanth

**Comment by APshenkin** [comment]
@shrikanthkm07 `I.see` command validate text on page, not element visibility. To test element visibility you have to use `I.seeElement`, but I recoment to use`I.waitForVisible("element CSS path")` to prevent false negative errors, related to element loading time

**Comment by APshenkin** [comment]
Close due inactivity
