### ISSUE TITLE
Exit with code 1 when tests fail (for CI purposes)

### ISSUE THREAD

**Issue by ke1Del** [Codeception/CodeceptJS#49]
Hi guys

In order to use codeceptjs for Continuous Integration, it needs to exit with code 1 when the tests fail. Unfortunately at this point it always exits with code 0 whether the tests pass or fail, thus CI assumes the tests are always successful. This makes codeceptjs useless for CI purposes unfortunately.

I'm using codeceptjs 0.2.4 with webdriverIO and chrome.

A possible solution would be to add `process.exit(1);` at the end of the tests if tests failed. I see that an event is emitted when the tests end (`event.dispatcher.emit(event.all.result, this);`) so maybe this could be done with a listener?

Best regards

**Comment by DavertMik** [comment]
Thanks. This must be implemented

**Comment by trikonasana** [comment]
Hi,

with 0.3.3 thus issue was reintroduced. 

Best regrads
