### ISSUE TITLE
Docs are misleading

### ISSUE THREAD

**Issue by imvetri** [Codeception/CodeceptJS#490]
### Details

* CodeceptJS version: 0.5 +
* NodeJS Version: v6
* Operating System: mac
* Nightmare version (if related)

following doesnt work
```js
I.amOnPage('/admin', [{'Authorization': 'Basic '+token}]);
```
following works
```js
I.amOnPage('/admin', {'Authorization': 'Basic '+token});
```

#### Conclusion
docs is misleading. If this real issue, I can send a PR for corrections.

**Comment by DavertMik** [comment]
Yes, please update them. In this case you should edit this file https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Nightmare.js
