### ISSUE TITLE
Using chrome driver

### ISSUE THREAD

**Issue by lvismer** [Codeception/CodeceptJS#5]
Does codeceptjs support alternate webdrivers. I tried starting selenium with the chrome driver. I'm on a mac (10.11). I downloaded the chromedriver, downloaded the selenium jar file. 

Starting selenium like this:

```java -Dwebdriver.chrome.driver="./chromedriver" -jar selenium-server-standalone-2.48.2.jar```

Then my codecept.json file

```
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://test.localhost",
      "browser": "chrome"
    }
  },
  "include": {},
  "mocha": {},
  "name": "Testing"
}
```

However when I run ```$ codeceptjs run``` it complains about firefox not being installed. I presume selenium by default ships with the firefox driver. 

Sorry I am completely new to selenium.

--
Leon

**Comment by petehouston** [comment]
@lvismer it's fixed in the latest commit, and should be working fine now.

https://github.com/Codeception/CodeceptJS/pull/4

**Comment by lvismer** [comment]
@petehouston Thanks, that fixed it for me.

**Comment by petehouston** [comment]
@lvismer cool to hear about that :+1:

**Comment by DavertMik** [comment]
I just published a new version with that PR. Please update to 0.1.6
