### ISSUE TITLE
Using within() causes an error on 0.2.5

### ISSUE THREAD

**Issue by ke1Del** [Codeception/CodeceptJS#50]
Hi

It seems like using a `within()` clause will cause an error on codeceptjs 0.2.5
`Error: done() invoked with non-Error: 1`

I also noticed that a Scenario with a failing assertion and a within() clause will fail twice, with the error `done() called multiple times`

I'm using CodeceptJs 0.2.5, with WebdriverIO and Chrome

Best regards

**Comment by DavertMik** [comment]
Fixed in 0.2.7
