### ISSUE TITLE
How to launch multiple browsers for single test case in codeceptjs,please let me know the steps?

### ISSUE THREAD

**Issue by ninpop25** [Codeception/CodeceptJS#502]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version: 
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by tamj0rd2** [comment]
Did you figure this out? I'd also like to know.

**Comment by ninpop25** [comment]
@tamj0rd2 : Please look this link (https://github.com/Codeception/CodeceptJS/pull/439) I think this will help you.

Note : I have one query and it will be great if you can help me in this

I want to calculate Page Load Time and Print the same in Console ( I want to do this in CodeceptJs)

**Comment by APshenkin** [comment]
Close this issue, to launch several instances use http://codecept.io/advanced/#multiple-execution
About Page Load Time - we will print step execution time in 1.0 release in debug note.

**Comment by javierfuentesm** [comment]
> Close this issue, to launch several instances use http://codecept.io/advanced/#multiple-execution About Page Load Time - we will print step execution time in 1.0 release in debug note.

@APshenkin  i don't see that in the section anymore
