### ISSUE TITLE
I.waitWhileVisible

### ISSUE THREAD

**Issue by fabioel** [Codeception/CodeceptJS#51]
Hi
I wanted to ask if it is possible to add a function `I.waitWhileVisible` that waits as long as a given selector is visible in the DOM. It would be really awesome!

**Comment by DavertMik** [comment]
Looks more like `I.waitToHide(el)`. But yes, that can easily be implemented. If you familiar with WebDriverIO you can send a Pull Request to WebDriverIO helper. It's pretty easy
