### ISSUE TITLE
Self-Signed Certificate Error

### ISSUE THREAD

**Issue by jhartma** [Codeception/CodeceptJS#512]
#### What are you trying to achieve?
Run the test on localhost with a self-signed ssl certificate.

#### What do you get instead?
```bash
 -- FAILURES:
1) Check @dev "before each" hook: Before for "I create a new user":
   error: request to https://localhost/graphql failed, reason: self signed certificate
```

**Comment by APshenkin** [comment]
For running tests with self-signed ssl certificate:
Nightmare:
Add this in Nightmare config:
```
switches: {
                'ignore-certificate-errors': true
            },
```

WebdriverIO:
Chrome: nothing to do
Firefox: 
```
desiredCapabilities: {
                "acceptInsecureCerts": true
            }
```

SeleniumWebdriver/Protractor:
Chrome: nothing to do
Firefox:
```
capabilities: {
                "acceptInsecureCerts": true
            }
```

**Comment by allenhwkim** [comment]
@APshenkin what's option for puppeteer?

**Comment by JeffroeBodine** [comment]
Is there any compatible example for ignoring HTTPSErrors in the Rest Helper? I've been all over the Axios docs and found a closed issue with a workaround -> https://github.com/axios/axios/issues/12

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` But setting that doesn't seem to help

**Comment by vsawant1608** [comment]
I have this setting in my codeceptjs.
```
    helpers: {
        CustomSetup: {
            require: './setup.js'
        },
        Puppeteer: {
            url: 'http://localhost:3020',
            show: false,
            windowSize: '1312x1400',
            chrome: {
                args: ['--ignore-certificate-errors']
            },
            keepCookies: true
        },
        REST: {
            endpoint: 'https://localhost:3020',
            onRequest: () => {}
        }
    }```

and this gives me certificate expired when I try to run test case like this

```
Feature('Get data using REST helper');

Before(async (I, login) => {
    await login('testUser');
});

Scenario('case list API', async I => {
    const res = await I.sendGetRequest('/users');

    expect(res.status).to.eql(200);
});
```

Any help on how to fix this?

**Comment by lind-eduard** [comment]
> For running tests with self-signed ssl certificate:
> Nightmare:
> Add this in Nightmare config:
> 
> ```
> switches: {
>                 'ignore-certificate-errors': true
>             },
> ```
> 
> WebdriverIO:
> Chrome: nothing to do
> Firefox:
> 
> ```
> desiredCapabilities: {
>                 "acceptInsecureCerts": true
>             }
> ```
> 
> SeleniumWebdriver/Protractor:
> Chrome: nothing to do
> Firefox:
> 
> ```
> capabilities: {
>                 "acceptInsecureCerts": true
>             }
> ```

Are there something like this for Playwright webkit browser?

**Comment by sibyaugustine** [comment]
> > For running tests with self-signed ssl certificate:
> > Nightmare:
> > Add this in Nightmare config:
> > ```
> > switches: {
> >                 'ignore-certificate-errors': true
> >             },
> > ```
> > 
> > 
> > WebdriverIO:
> > Chrome: nothing to do
> > Firefox:
> > ```
> > desiredCapabilities: {
> >                 "acceptInsecureCerts": true
> >             }
> > ```
> > 
> > 
> > SeleniumWebdriver/Protractor:
> > Chrome: nothing to do
> > Firefox:
> > ```
> > capabilities: {
> >                 "acceptInsecureCerts": true
> >             }
> > ```
> 
> Are there something like this for Playwright webkit browser?

ignoreHTTPSErrors should work.

    Playwright: {
      url: 'https://linux246.prod.hclpnp.com:8445',
      show: true,
      browser: 'chromium',
      ignoreHTTPSErrors : true
    }

**Comment by ngraf** [comment]
Playwright with option `ignoreHTTPSErrors : true` works like a charm for me within "chromium", "firefox" and "webkit" 👍🏻
