### ISSUE TITLE
I.fillField works on Chrome, not on Firefox

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#518]
#### What are you trying to achieve?
input some searchtext with fillField or appendField
- chrome works
- firefox fails

#### What do you get instead? 
testing with Firefox:

`   Expected [object Undefined] undefined to be a string
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'x', ip: 'y', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/r3/kr53b4g17w7gdxswjgbqqmvc0000gp/T/rust_mozprofile.lM2vOEDnXVRS, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.2, platformVersion=16.5.0, moz:processID=95895, browserName=firefox, platformName=darwin}]
Session ID: cc8e69b6-ef15-5943-8d43-f3e71ba1a476`

> Provide test source code if related

```
Scenario('test something', (I) => {
  I.resizeWindow(1220,1024);
  I.amOnPage('/');
  I.waitForElement('#searchfor');
  I.click('#searchfor');
  I.fillField('#searchfor', 'baardolie');
  I.saveScreenshot('result.png');
});
```
### Details

* CodeceptJS version: 0.6.3pre
* NodeJS Version: 7.10.0
* Operating System: MacOS Sierra
* WebDriverIO: 4.7.1
* Configuration file: 

```
exports.config = {
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      // load variables from the environment and provide defaults
      "url": "https://www.bol.com",
      "browser": "chrome",
      //"browser" : process.profile || "phantomjs",
      "restart" : "false"
    }
  },
  "include": {
    "I": "./steps_file.js",
    "globals": "./globals.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "production"
}

```

**Comment by DavertMik** [comment]
Looks like a Firefox issue. 
Last week I spent a night fighting latest firefox with latest geckodriver and couldn't make all test pass :( No ideas how to fix that before it is done by Mozilla. I assume it is not stable yet and can't be used. 

However, old selenium 2.53 and old firefox 33 still work fine.

**Comment by APshenkin** [comment]
@joelgrimberg Tested with selenium 3.4.0 and geckodriver 0.18.0. `fillField` method works as expected

**Comment by renoirb** [comment]
It looks like Playwright's fillField and clearField has issues for Firefox. Scenarios written and working with Chromium, when running with Firefox doesn't behave the same.

I'll make a reproduce Gist.
