### ISSUE TITLE
howto catch a modal only when it reveals itself

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#521]
#### What are you trying to achieve?
I am coding a test that checks some stuff on a website.
once in a while a modal shows up in front of the screen, but not always.
Is there a way to catch it and act on it only when it shows itself to the public?

**Comment by implico** [comment]
@joelgrimberg try something like this:
```javascript
Scenario('modal', function*(I) {
  let isVisible = yield I.executeScript(() => !!document.querySelectorAll('.modal').length)
  if (isVisible) {
    // tests for modal
  }
}
```
If it is always in the DOM bu just shows sometimes, modify to check its `offsetParent !== null` to determine visibility.

**Comment by joelgrimberg** [comment]
mmm think I don't get it yet.
My (hasModal) is never triggered. Is there another hint? ;)

my code: 

```
Scenario('TG1 - shipping costs > 20,--', function*(I) {
  // Screensettings
  I.resizeWindow(1220,1024);

  // Page
  I.amOnPage('/');

  let hasModal = yield I.executeScript(() => !!document.querySelectorAll('div.modal__overlay').length)
  if (hasModal) {
    I.click('/html/body/div[3]/div[2]/div[1]');
  }

  // Search for 'beardoil'
  I.waitForElement('#searchfor');
  I.click('#searchfor');
  I.fillField('#searchfor', 'beardoil');
  I.click('/html/body/div[1]/header/div[2]/div/div[3]/form/div/div[3]/input[1]'); //search_button
```

**Comment by implico** [comment]
@joelgrimberg You have to change the condition then, maybe the modal is loaded in async (later) etc. - depends on your implementation. This is just the way for conditional code depending on an actual state.

**Comment by APshenkin** [comment]
@joelgrimberg I can propose to create custom method that will try to wait an element on page and if it's appear do some actions. But in this case you have to wait each time even if it did not appear. BTW if you don't need this modal at all I suggest to ask your developers to add special cookie, that will give you opportunity to force display/hide this modal.

Hope these recommendations will help you.


If you have any other question, please let us know
