### ISSUE TITLE
[Enhancement] Expand saveScreenshot() to capture full page 

### ISSUE THREAD

**Issue by HughZurname** [Codeception/CodeceptJS#522]
#### What are you trying to achieve?

The default behaviour for `saveScreenshot()` is to capture the current viewport, but from my experience on Nightmare in particular the focus isn't on the area of the fault when the screen is captured. 

#### What do you get instead?

Basically you need to manually set the set the viewport to the height that the page may need to be in order to capture any issues to aid investigation of failed tests. 

#### Proposed solution

Allow for `saveScreenshot()` to capture the full page by resizing the viewport on demand to the availible `scrollHeight` and `scrollWidth`

#### Notes
I've already solved this, the PR should be following shortly. This is more for reference.

**Comment by mingfang** [comment]
full page should mean resize to `scrollHeight` but leave the width alone; don't resize to `scrollWidth`.
This is important for responsive design testing.
