### ISSUE TITLE
"keys" deprecated in WebdriverIO 4.8

### ISSUE THREAD

**Issue by foobarth** [Codeception/CodeceptJS#525]
#### What are you trying to achieve?
We use the pressKey() method for interaction with a web form.

#### What do you get instead?
It works, but we get a lot of deprecation warnings from WebdriverIO.

> Provide console output if related. Use `--verbose` mode for more details.
```bash
  • I press key "Enter"
WARNING: the "keys" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
```
> Provide test source code if related

```php
Scenario('...', (I) => {
  // [...]
  I.pressKey('Enter');
  // [...]
});
```
### Details

* CodeceptJS version: 0.5.1
* NodeJS Version: 7.10.0
* Operating System: Linux (Docker container)
* WebDriverIO: 4.8.0
* Related changelog from WebdriverIO: https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#v480-2017-04-30

**Comment by DavertMik** [comment]
@christian-bromann is there any reason `keys` are deprecated?
What can be used instead? Thanks

**Comment by christian-bromann** [comment]
@DavertMik it is not part of the Webdriver spec and not supported by latest Firefox versions. This is why we added the deprecation warning. Not sure yet what do use instead. WebdriverIO will keep the command as long as most of the drivers still support it.

**Comment by DavertMik** [comment]
I understand. Latest firefox versions are the real pain :(
Thanks for clarifying

**Comment by DavertMik** [comment]
Also... https://github.com/webdriverio/webdriverio/issues/2076
