### ISSUE TITLE
Cannot read property 'url' of undefined in Nightmare.js

### ISSUE THREAD

**Issue by bendiggle** [Codeception/CodeceptJS#528]
#### What are you trying to achieve?
I am trying go to another page using `I.amOnPage(url)`.
In my test my steps are:
```
    I.amOnPage(url); // this amOnPage works fine
    I.checkOption(element);
    I.amOnPage(anotherUrl); // this one doesn't
```

#### What do you get instead?
There error I get is 
`Cannot read property 'url' of undefined`

I have narrowed it down to the `amOnPage` function in Nightmare.js file in `codeceptjs/lib/helper/Nightmare.js`.
```
    return this.browser.goto(url, headers).then((res) => {
      this.debugSection('URL', res.url);
      this.debugSection('Code', res.code);
      this.debugSection('Headers', JSON.stringify(res.headers));
    });
```
the `res` being returned from the promise is coming back as `undefined`.

**Comment by implico** [comment]
Is `url == anotherUrl`? If so, a temporary workaround would be to navigate to an intermediate page, e.g. `I.amOnPage('about:blank')`

**Comment by bendiggle** [comment]
@implico Yes, url is equal to anotherUrl! (Sorry, I should have mentioned). All I really want to do is refresh the page but could not find a way to do it so was trying to just go to that page again.
Thanks, I will try that.

**Comment by implico** [comment]
Yes, I was 99% sure it is. This will work, not an elegant solution though, to be fixed later.

**Comment by APshenkin** [comment]
@bendiggle You can create custom helper with refresh method https://github.com/segmentio/nightmare#refresh

**Comment by bendiggle** [comment]
Thanks @APshenkin, I will do that!

**Comment by DavertMik** [comment]
We need to get `refresh` method in Nightmare helper as well.
Who will send a pull request? @bendiggle ?

**Comment by awshanks** [comment]
This is now in release 1.0.1.  Can this now be closed?

**Comment by APshenkin** [comment]
@awshanks yep, will close it

**Comment by petrisorionel** [comment]
Hello, I found this problem on version 1.0.2

**Comment by lougreenwood** [comment]
I'm also still seeing this bug:

```
Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
 ✖ "before each" hook: Before for "test logout" in 30034ms

-- FAILURES:

  1) Login page: "before each" hook: Before for "test login form":
     Cannot read property 'url' of undefined

  Scenario Steps:

  - I.amOnPage("/") at Object.logoutLogin (pages/login.js:51:11)
  - I.clearCookie() at Object.logoutLogin (pages/login.js:50:5)
```
