### ISSUE TITLE
"moveTo" command will be depcrecated soon - WebDriverIO

### ISSUE THREAD

**Issue by LaurieSReynolds** [Codeception/CodeceptJS#531]
#### What are you trying to achieve?

We use 'moveCursorTo' to move the cursor to an item in a table.   

#### What do you get instead?

It is working, but we are now seeing deprecation warnings.  What should we plan to use in the future?

```bash
• I move cursor to {"css":"tr[name=\"2162\"] td[data-name='NAME']"}
WARNING: the "moveTo" command will be depcrecated soon. 
  Please use a different command in order to avoid failures
 in your test after updating WebdriverIO.
```

### Details

* CodeceptJS version: 0.6.3
* NodeJS Version: 6.10.1
* Operating System: macOS Sierra - 10.12.4
* Protractor || WebDriverIO || Nightmare version (if related): WebDriverIO - 4.8.0
* Configuration file:

**Comment by DavertMik** [comment]
Related #525 
To be honest **I don't know what to do** :cry:

**Comment by Katarn** [comment]
https://github.com/webdriverio/webdriverio/issues/2076

@christian-bromann:
> @pzrq we actually don't know yet how we would replace the keys command. It won't be removed from the WebdriverIO API until there is a replacement so take this warning not super seriously.

> @Godsmith just use v4.7.x which doesn't contain these warnings
