### ISSUE TITLE
codeceptjs init | Error: The system cannot find the path specified

### ISSUE THREAD

**Issue by tamj0rd2** [Codeception/CodeceptJS#533]
#### What are you trying to achieve?
I am trying to initialise codeceptjs by running `codeceptjs init`.

Here's what I did:
```
> npm i codeceptjs-webdriverio --save-dev
> .\node_modules\.bin\codeceptjs init
Error: The system cannot find the path specified.
> npm i codeceptjs-webdriverio -g # because the above `init` command filed I wanted to see if a global install would work.
> codeceptjs init
Error: The system cannot find the path specified.
> codeceptjs
Error: The system cannot find the path specified.
> where codeceptjs
C:\Users\tamj0rd2\AppData\Roaming\npm\codeceptjs.cmd
# So it is installed, but running it just isn't working.
```

#### What do you get instead?
`Error: The system cannot find the path specified.`

### Details

* CodeceptJS version: v1.0.1
* NodeJS Version: v6.9.2
* Operating System: Windows 10
* WebDriverIO
* Configuration file: N/A (haven't been able to generate it yet)

```js
# paste suite config here
N/A?
```

**Comment by tamj0rd2** [comment]
I've had a look at this. On windows, when you run the `codeceptjs` command, it runs `codeceptjs.cmd`, not `codeceptjs`.

There is no check inside of `codeceptjs.cmd` telling it where cygwin's `sh.exe` is located. Instead, on line 6, it assumes that `C:\Users\tamj0rd2\AppData\Roaming\npm\bin` exists and contains a file called `sh.exe`. The bin folder didn't exist for me.

I was able to get the command working by doing the following:
1. Created a `bin` folder in `C:\Users\tamj0rd2\AppData\Roaming\npm`
2. Copied `sh.exe` from `C:\cygwin\bin` into `C:\Users\tamj0rd2\AppData\Roaming\npm\bin`

Since the bin/sh folder didn't exist inside of the npm directory for me, I'm willing to bet some other people are missing it too. I think there should be a check inside of `codeceptjs.cmd` to find out if the person is using cygwin, and if so, use cygwin's `sh.exe`.

**Comment by tamj0rd2** [comment]
I'd do a PR for this but I'm not sure whereabouts in the repo the `codeceptjs.cmd` files are

**Comment by APshenkin** [comment]
@tamj0rd2 Hi!
I'm unable to reproduce this bug on Windows 10. Both global and local `init` work as expected in default cmd console.

I use Win 10 build 15063 from here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Also it works in mingw and cygwin

Could you please provide more information about your installation?

Thanks!

**Comment by APshenkin** [comment]
Close due inactivity
