### ISSUE TITLE
I.amOnPage is not a function

### ISSUE THREAD

**Issue by tamj0rd2** [Codeception/CodeceptJS#535]
#### What are you trying to achieve?
Trying to run a simple test following the QuickStart on website using `codeceptjs init`
http://codecept.io/quickstart/

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
> .\node_modules\.bin\codeceptjs run --steps --verbose
CodeceptJS v0.6.3
Using test root "C:\Users\tamj0rd2\coding\autotools3"

My First Test --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
 test something
   [2] Starting recording promises
   Emitted | test.before
   Emitted | test.start ([object Object])
   [2] Queued | throw error TypeError: I.amOnPage is not a function
   [2] Queued | fire test.passed
   [2] Queued | finish test
   [2] Error | TypeError: I.amOnPage is not a function
   [2] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [2] <teardown> Queued | () => done(err)
   [2] <teardown> Stopping recording promises
 × FAILED in 7ms

   Emitted | test.after
   [3] Starting recording promises
   Emitted | suite.after ([object Object])

-- FAILURES:

  1) My First Test: test something:
     I.amOnPage is not a function
  ypeError: I.amOnPage is not a function
      at Test.Scenario (tests\first_test.spec.js:4:5)
      at Context.test.fn (node_modules\codeceptjs-webdriverio\node_modules\codeceptjs\lib\scenario.js:29:24)


  FAIL  | 0 passed, 1 failed   // 27ms
   Emitted | global.result ([object Object])
```
> Provide test source code if related

```js
Feature('My First Test')

Scenario('test something', (I) => {
  I.amOnPage('/')
  I.see('Something')
})
```
### Details

* CodeceptJS version: 1.0.1
* NodeJS Version: v6.9.2
* Operating System: Windows 10
* WebDriverIO version: 4.8.0
* Configuration file:

```json
{
  "tests": "./tests/**/*.spec.js",
  "timeout": 10000,
  "output": "./codecept_output",
  "helpers": {},
  "include": {
    "I": "./tests/steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "autotools3"
}
```

**Comment by tamj0rd2** [comment]
I needed to edit the helpers file. For some reason when I ran init, it didn't prompt me for the `browser` or `url`, so I added those to the `codecept.json` manually. Not sure if that's something that needs addressing?

**Comment by DavertMik** [comment]
Yes, initially no helpers were added so the methods were not defined.
Probably we should have a better error message here but I'm don't know how to make it )

**Comment by tamj0rd2** [comment]
@DavertMik Does the documentation need to be updated? On the Getting Started page it says that during `codeceptjs init` you should be prompted for the url and browser, but that doesn't happen.

**Comment by leojh** [comment]
I just ran into this issue still

**Comment by benfurfie** [comment]
Also ran into this issue. Init file didn't prompt for browser or url, though it is noted in the docs.

Perhaps there should be a section that highlights that they are required and how to add them manually.

**Comment by LinBoLen** [comment]
issue still exists

**Comment by Nathan-Schwartz** [comment]
Just had this issue as well

**Comment by DavertMik** [comment]
Yes, guys, this issue still may be there if you don't select any of Helpers during the `init` process.
You need to do that in order to pick the backend: WebDriverIO (default), Protractor, Appium, etc.

That's important. Please select WebDriverIO during setup to proceed

**Comment by Nathan-Schwartz** [comment]
That makes sense, I think what threw me off was using space bar to select an option. I thought the cursor next to the option meant it was selected and that enter would confirm my choice. If you can select multiple Helpers, not using enter makes sense though 👍 

Maybe it would be worth it to make a note of using space to toggle options in the prompt? Either way, the issues were enough for me to figure out the problem.

Thanks @DavertMik! Love the package.

**Comment by vetsinen** [comment]
i get the same error now when tries to lauch test with default configuration
may you say how to fix this. i don't understand what tamj0rd2 did to fix

**Comment by FelipeLahti** [comment]
Same problem here.

**Comment by bionicles** [comment]
Hitting this today, feeling dumb

**Comment by kobenguyent** [comment]
This shall fix the issue. https://github.com/codeceptjs/CodeceptJS/pull/3703
