### ISSUE TITLE
`codeceptjs init` doesn't prompt for the URL or the browser

### ISSUE THREAD

**Issue by tamj0rd2** [Codeception/CodeceptJS#537]
#### What are you trying to achieve?
The [quickstart](http://codecept.io/quickstart/) guide is misleading. It says that during `codeceptjs init`, if you select `webdriverio`, it will prompt you for the testing URL and a browser. It doesn't prompt for either of those things. Is something wrong or do the docs need to be updated?

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
> codeceptjs init

  Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

Installing to C:\Users\tamj0rd2\coding\temp
? Where are your tests located? ./*_test.js
? What helpers do you want to use?
? Where should logs, screenshots, and reports to be stored? ./output
? Would you like to extend I object with custom steps? Yes
? Do you want to choose localization for tests? English (no localization)
? Where would you like to place custom steps? ./steps_file.js
Steps file created at C:\Users\tamj0rd2\coding\temp\steps_file.js
Config created at C:\Users\tamj0rd2\coding\temp\codecept.json
Directory for temporary output files created at `_output`
Almost done! Create your first test by executing `codeceptjs gt` (generate test) command
```

### Details

* codeceptjs-webdriverio version: 1.0.1
* NodeJS Version: v6.9.2
* Operating System: Windows 10
* WebDriverIO: Did not install as the quickstart guide didn't say to
* Configuration file:

```json
{                             
  "tests": "./*_test.js",     
  "timeout": 10000,           
  "output": "./output",       
  "helpers": {},              
  "include": {                
    "I": "./steps_file.js"    
  },                          
  "bootstrap": false,         
  "mocha": {},                
  "name": "temp"              
}                             
```

According to the quickstart documentation, the above configuration should already have a url and browser listed. But `codeceptjs init` never prompts the user for those details.

Related issue: https://github.com/Codeception/CodeceptJS/issues/535

**Comment by DavertMik** [comment]
You didn't select WebDriverIO from the list, so no helpers were selected, so they are not in config. 
Press SPACE while you are asking for helpers, so the output will be:

```
? What helpers do you want to use? WebDriverIO

```

**Comment by leojh** [comment]
I'm having this same issue. Even tho I select `WebDriverIO` on the init command, it does not ask me for url information.
