### ISSUE TITLE
Test fails on iOS simulator with hybrid app when using I.fillField() method

### ISSUE THREAD

**Issue by wjastrzemski** [Codeception/CodeceptJS#542]
#### What are you trying to achieve?
I have to implement test for iOS simulator and hybrid application. I have already intergation of Appium with iOS. 
I want to implement simple test which will open the app and go to login view and login user.
I am trying to input text into textbox of hybrid application on iOS simulator.

#### What do you get instead?
When I am using method I.fillField the test is failing with information:
Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]

Test login.js:
```
Scenario('Login test', (I, homePage, promoPopupFragment) => {
    promoPopupFragment.close();
    homePage.goToLogin();
    I.fillField('input[name="username"]','username');
    I.fillField('input[name="password"]','password');
    I.click('.submit');
    homePage.goToMyAccount();
    }
)
```

Configuration file:
```
exports.config = {
    tests: './tests/native/native_login_test.js',
    timeout: 30000,
    output: './output',
    helpers: {
        WebDriverIO: {
            "desiredCapabilities": {
                "app": "/Users/test.app",
                "platformName": "iOS",
                "platformVersion": "10.2",
                "deviceName": "Iphone 6 10.2",
                "autoWebview": true,
                "automationName": "XCUITest",
                "fullReset": true,
                "newCommandTimeout": 60,
            },
            "port": 4723,
            "browser": " ",
            "url": "http://localhost",
            "waitForTimeout": 30000
        },
        MyHelper: {
            require: './helpers/custom_methods/MyHelper.js',
        }
    },
    include: {
        I: './helpers/steps_file.js',
        loginPage: './helpers/mobile/pages/Login.js',
        ...
    },
    bootstrap: false,
    mocha: {
        reporterOptions: {
            reportDir: './output',
            enableCharts: true,
            reportTitle: 'Reporter'
        }
    },
    name: 'Test',
};
```

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]
```

### Details

* CodeceptJS version: 0.5.1
* NodeJS Version: 7.10.0
* Operating System: macOS Sierra 10.12.4
* WebDriverIO: 4.6.2
* Appium: 1.6.4

**Comment by APshenkin** [comment]
@wjastrzemski  This issue is related with WebdriverIO. Please see https://github.com/webdriverio/webdriverio/issues/2048

The best option for now is to set WebdriverIO version to 4.7.1

**Comment by wjastrzemski** [comment]
But it is connected with Appium because I tried on version 1.6.5-beta and it worked.

**Comment by APshenkin** [comment]
Now many people switch to W3C protocol, instead of JSON Wire protocol. Because of this, there may be compatibility problems. @wjastrzemski  I think we can close this request, can we?

**Comment by wjastrzemski** [comment]
Yes, we can close issue because it was resolved with beta version.
