### ISSUE TITLE
Multiple run and XML report

### ISSUE THREAD

**Issue by enes-ergul** [Codeception/CodeceptJS#548]
#### What are you trying to achieve?
I want to use the new multiple run feature and export the report as xml file

> $(npm bin)/codeceptjs run-multiple --all --reporter mocha-junit-reporter

#### What do you get instead?
Only one of the parallel runs is present in the XML output

### Details

* CodeceptJS version: 0.6.3
* NodeJS Version: 6.9.2
* WebDriverIO Version: 4.8.2
* Mocha JUnit Reporter Version: 1.13.0

**Comment by shrikanthkm07** [comment]
Even I am facing the same issue. Actually I don't even see the steps also. Is these any solution for this ?

**Comment by APshenkin** [comment]
@enes-ergul @shrikanthkm07 
As I understand, You use this npm package?
https://www.npmjs.com/package/mocha-junit-reporter
If so, than we have to add new override in multiple-run for `mochaFile` parameter. https://github.com/Codeception/CodeceptJS/blob/master/lib/command/run-multiple.js#L95
and pass reporter folder via codeceptJS config.

You can add PR for this or wait, when I'll be able to take this in work

**Comment by APshenkin** [comment]
@enes-ergul @shrikanthkm07 
I have added new override in multiple-run. Reports files will have `report.xml` name. This changes will come with 1.0 release
