### ISSUE TITLE
###How To Calculate Page Load Time in CodeceptJs and How to Print it in Console###

### ISSUE THREAD

**Issue by ninpop25** [Codeception/CodeceptJS#550]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version: 
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by APshenkin** [comment]
https://github.com/Codeception/CodeceptJS/pull/568
