### ISSUE TITLE
[Enhancement] - Database Helper

### ISSUE THREAD

**Issue by HughZurname** [Codeception/CodeceptJS#551]
#### What are you trying to achieve?

Currently I use [lokijs ](http://lokijs.org/) in a custom helper of sorts to handle some data driven test scenarios. 

I find it pretty useful in few cases: 
- When you're randomizing some data in a test and want to validate against it at some point in the future as part of an e2e run. 
- Data driven testing becomes easier by creating sets that you combine through queries and can access these values form throughout the test execution.
- Writing values out to the database can be useful for retrospective debugging of failed tests.

### Details
I've started work on a helper for this, so this is both a statement of intent and an opportunity for any suggestions, feedback or requests before I begin in earnest.

**Comment by lougreenwood** [comment]
This may be something my team are also interested in...

Our project's functional tests (Codecept PHP) load a clean db dump before the test suite run, so we can ensure that re-runs of test suite always have clean data.

Ideally I'd like to be able to do the same for our CodeceptJS acceptance tests where we make database changes and check for appropriate UI changes.

Sounds like this is within the scope of what you have planned?

**Comment by HughZurname** [comment]
@lougreenwood It sounds like you're talking about a database connector perhaps? One that allows you to manipulate the data driving the test directly if my understanding is correct? 

I think my intention here was for the helper to be an interface between the test runner and an in-memory database, owned by the helper process, that would be loaded with some seed values that are combined in a randomised way to build a test profile. These values can be changed in an expected way during the test execution. 

The intent was to effectively make more dynamic test scenarios while still being able to have concrete expectations of the expected outcome.

**Comment by DavertMik** [comment]
@lougreenwood in CodeceptJS 1.0 we will provide data management via REST API. 
It is recommended to use public APIs instead of accessing the database directly.
Please wait for the release announcement
