### ISSUE TITLE
CodeceptJS Exits with Status 0 when Tests Fails on Jenkins how to avoid it?

### ISSUE THREAD

**Issue by ninpop25** [Codeception/CodeceptJS#556]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version: 
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by APshenkin** [comment]
@ninpop25 Can you please provide more information? How you run test, test output in verbose mode?

**Comment by APshenkin** [comment]
close due inactivity
