### ISSUE TITLE
hard to select text from your "quick start" guide

### ISSUE THREAD

**Issue by mo** [Codeception/CodeceptJS#558]
It's hard to copy commands using CTRL-C from the quick start guide into the clipboard. First I thought it wasn't possible to select the commands at all since no selection appeared. But there was no user-select CSS on it, and then I realized that the selection was there but it's black so it's barely possible to see it. Selecting other text (outside of the commands), for example "You can install it globally:", works just fine and I get orange selection color there (I'm using ubuntu 16.04). Strange thing is that in Firefox the selection is much easier to see because there it's just dark gray instead of nearly black.

For example, open:
http://codecept.io/quickstart/#quickstart
... and try to copy for example this command:
npm install codeceptjs-webdriverio --save-dev

The bad CSS seems to be this one:

.hljs::selection, .hljs span::selection {
    background: #373b41;
}

And the reason why it "works" better in Firefox is because you didn't use ::moz-selection

**Comment by DavertMik** [comment]
Ok, thanks for the report. I will try to improve that

**Comment by DavertMik** [comment]
Replaced bg color with #2c3e50
