### ISSUE TITLE
       "windowSize": "maximize" can't support  chrome 59 version

### ISSUE THREAD

**Issue by tony204** [Codeception/CodeceptJS#560]
"windowSize": "maximize" can't support  chrome 59 version

if you user chrome 59 version ,  maximize or other windowsize can't support
@DavertMik

**Comment by DavertMik** [comment]
Yes, I think this is a limitation of ChromeDriver and Chrome 59
Not sure how to overcome it. You can only pass the `window-size` argument to `args` for ChromeOptions to set the initial size for Chrome

**Comment by APshenkin** [comment]
@DavertMik @tony204 
I think we can try this hack:
Execute script in browser to get information about screen resolution:
```
return screen.width;
return screen.height;
```
Then pass them to windowHandleSize function

Here is a demo how this scripts works in browser: https://jsfiddle.net/8q67em27/1/

**Comment by tony204** [comment]
@DavertMik  @APshenkin 
i update the source code,upload the 3 files WebDriverIO.js , SeleniumWebdriver.js, Appium.js that you guys commit to master, but it also didn't fix the chrome 59 maximize problem.
Can you confirm is it any steps maybe i missed?

**Comment by ninpop25** [comment]
@DavertMik @APshenkin : I am facing issue with *Window.Maximize()*
below is the ticket
https://github.com/Codeception/CodeceptJS/issues/892
please help me,as its failing my automation build first test and thus results in failed build
