### ISSUE TITLE
Contributor's Guide

### ISSUE THREAD

**Issue by chrisbrainerd** [Codeception/CodeceptJS#562]
Not a code issue, but feels like we should have a contributor's guide here. Currently one of the automated tests is failing, but as a contributor it's not clear whether that's on me to fix and if not who to contact (and fwiw the test that's failing it looks like is failing on invalid credentials to some 3rd party service I'm assuming only the repo maintainers have access to).  Also looks in the docs like there's translation of some method names, but it's not clear if that's mandatory for updates or optional, etc. I think it's help encourage people to contribute if it was clearer what was and wasn't expected. 

Anyone know of a good template?

**Comment by DavertMik** [comment]
Finally I managed to write it https://github.com/Codeception/CodeceptJS/blob/master/CONTRIBUTING.md
Thanks for raising this issue )
