### ISSUE TITLE
Scenarios fail if restart=false.

### ISSUE THREAD

**Issue by Rarcita** [Codeception/CodeceptJS#564]
#### What are you trying to achieve?
Trying to run my tests with `restart:false` on config file.
All my tests passed, until I add that line to the config and then 90% of my scenarios fail. Again, if just that line, If I comment it they start passing again. 
I grabbed two sample tests to try it out, and same thing happens.
See they are very basic

Scenario('Nightmare basic test yahoo', (I) => {
I.amOnPage('http://yahoo.com');
I.fillField('p', 'github nightmare');
I.click('#uh-search-button');

});

Scenario('Nightmare basic test google', (I) => {
I.amOnPage('http://google.com');
I.fillField('p', 'github nightmare');
});

#### What do you get instead?

**If restart=false line  is commented, they all passed.**

yarn run v0.24.4
$ codeceptjs run --steps --verbose --debug --reporter mochawesome

  Login
    ✓ Nightmare basic test yahoo (13644ms)
    ✓ Nightmare basic test google (4151ms)

  2 passing (18s)

[mochawesome] Report JSON saved to /Users/Rarcita/Applications/NES/nes-e2e-tests/e2e-output/mochawesome.json

[mochawesome] Report HTML saved to /Users/Rarcita/Applications/NES/nes-e2e-tests/e2e-output/mochawesome.html

✨  Done in 22.13s.
✨  Done in 24.34s.

**If restart=false is not commented, the first one fails (for this two samples. On my suite,most of them fail, but they will all pass if I comment out the line.**

See yarn run v0.24.4

$ codeceptjs run --steps --verbose --debug --reporter mochawesome

  Login

Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?

    1) Nightmare basic test yahoo

    ✓ Nightmare basic test google (3125ms)

  1 passing (34s)

  1 failing

  1) Login: Nightmare basic test yahoo:

     [Wrapped Error] "Nothing responds to \"goto\""

  

  Scenario Steps:

  

  - I.click("#uh-search-button") at Test.Scenario (test-e2e/tests/01_login/login_spec.js:76:5)

  - I.fillField("p", "github nightmare") at Test.Scenario (test-e2e/tests/01_login/login_spec.js:75:5)

  - I.amOnPage("http://yahoo.com") at Test.Scenario (test-e2e/tests/01_login/login_spec.js:74:5)

  

  

[mochawesome] Report JSON saved to /Users/Rarcita/Applications/NES/nes-e2e-tests/e2e-output/mochawesome.json

[mochawesome] Report HTML saved to /Users/Rarcita/Applications/NES/nes-e2e-tests/e2e-output/mochawesome.html

error Command failed with exit code 1.

```
> Provide test source code if related

```php
// paste test
```
### Details

CodeceptJS version: 0.6.3
NodeJS Version: v6.10.3
Operating System: OSX Yosemite 10.10.5
 Nightmare version:2.10.0
Configuration file:
helpers: {
Nightmare: {
url: process.env.CODECEPT_URL || 'http://google.com',
show: process.env.SHOW || false,
restart: false,
windowSize: '1280x1024',
openDevTools: { detach: true },
gotoTimeout: 90000
},

```js
# paste suite config here
```

**Comment by APshenkin** [comment]
@Rarcita Can you please provide logs in `verbose` mode?

Seems it's issue with promises chain that we want to improve soon

**Comment by Rarcita** [comment]
with out restart line
`Nightmare basic test yahoo

   [2] Starting recording promises

   Emitted | test.before

   [2] Queued | hook Nightmare._before()

   [2] Queued | hook NesHelpers._before()

   Emitted | test.start ([object Object])

   Emitted | step.before (I am on page "http://yahoo.com")

   [2] Queued | amOnPage: "http://yahoo.com"

   Emitted | step.after (I am on page "http://yahoo.com")

   [2] Queued | return step result

   Emitted | step.before (I fill field "p", "github nightmare")

   [2] Queued | fillField: "p", "github nightmare"

   Emitted | step.after (I fill field "p", "github nightmare")

   [2] Queued | return step result

   Emitted | step.before (I click "#uh-search-button")

   [2] Queued | click: "#uh-search-button"

   Emitted | step.after (I click "#uh-search-button")

   [2] Queued | return step result

   [2] Queued | fire test.passed

   [2] Queued | finish test

   Emitted | step.start (I am on page "http://yahoo.com")

 • I am on page "http://yahoo.com"

 > warn: yui: NOT loaded: highlander-vertical-video

 > warn: yui: NOT loaded: highlander-client-templates-viewer-controls-atomic

 > warn: yui: NOT loaded: highlander-vertical-video

 > warn: yui: NOT loaded: highlander-vertical-video

 > warn: yui: NOT loaded: highlander-client-templates-viewer-controls-atomic

 > warn: yui: NOT loaded: highlander-client-templates-viewer-controls-atomic

 > warn: yui: NOT loaded: highlander-vertical-video

 > warn: yui: NOT loaded: td-applet-storyswarm-atomic-templates-list.tumblr

 > warn: yui: NOT loaded: td-applet-storyswarm-atomic-templates-list.tumblr

 > warn: yui: NOT loaded: td-applet-storyswarm-atomic-templates-list.tumblr

 > [URL] https://espanol.yahoo.com/?p=us

 > [Code] 200

 > [Headers] {"age":["0"],"cache-control":["no-store, no-cache, max-age=0, private"],"connection":["keep-alive"],"content-encoding":["gzip"],"content-type":["text/html; charset=UTF-8"],"date":["Wed, 28 Jun 2017 13:48:34 GMT"],"expires":["-1"],"p3p":["policyref=\"https://policies.yahoo.com/w3c/p3p.xml\", CP=\"CAO DSP COR CUR ADM DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV\""],"server":["ATS"],"set-cookie":["autorf=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; domain=espanol.yahoo.com"],"strict-transport-security":["max-age=2592000"],"transfer-encoding":["chunked"],"via":["http/1.1 media-router-fp64.prod.media.ne1.yahoo.com (ApacheTrafficServer [cMsSf ])"],"x-frame-options":["DENY"]}

   Emitted | step.start (I fill field "p", "github nightmare")

 • I fill field "p", "github nightmare"

   Emitted | step.start (I click "#uh-search-button")

 • I click "#uh-search-button"

   Emitted | test.passed ([object Object])

 ✓ OK in 14301ms



   Emitted | test.after

   [2] Queued | hook Nightmare._after()

   [2] Queued | hook NesHelpers._after()

 Nightmare basic test google

   [3] Starting recording promises

   Emitted | test.before

   [3] Queued | hook Nightmare._before()

   [3] Queued | hook NesHelpers._before()

   Emitted | test.start ([object Object])

   Emitted | step.before (I am on page "http://google.com")

   [3] Queued | amOnPage: "http://google.com"

   Emitted | step.after (I am on page "http://google.com")

   [3] Queued | return step result

   Emitted | step.before (I fill field "p", "github nightmare")

   [3] Queued | fillField: "p", "github nightmare"

   Emitted | step.after (I fill field "p", "github nightmare")

   [3] Queued | return step result

   [3] Queued | fire test.passed

   [3] Queued | finish test

   Emitted | step.start (I am on page "http://google.com")

 • I am on page "http://google.com"

 > [URL] https://www.google.com.ar/?gfe_rd=cr&ei=v7NTWdXYFtiexgTCtKLgDw&gws_rd=ssl

 > [Code] 200

 > [Headers] {"alt-svc":["quic=\":443\"; ma=2592000; v=\"39,38,37,36,35\""],"cache-control":["private, max-age=0"],"content-encoding":["gzip"],"content-type":["text/html; charset=UTF-8"],"date":["Wed, 28 Jun 2017 13:48:48 GMT"],"expires":["-1"],"p3p":["CP=\"This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info.\""],"server":["gws"],"set-cookie":["NID=106=RT0qumUCP7QZ5I9eoMmoWEEmm92V7di__GY_UPCK_xElPjt0LrBZ5TalNUtmnRkg7ANyz5AwkCl6LrVwsb9S8lNp78SVq7FWyy_MSWRNH8uFWSfwoVxrIj6S1JEbjNXw; expires=Thu, 28-Dec-2017 13:48:49 GMT; path=/; domain=.google.com.ar; HttpOnly"],"status":["200"],"x-frame-options":["SAMEORIGIN"],"x-xss-protection":["1; mode=block"]}

   Emitted | step.start (I fill field "p", "github nightmare")

 • I fill field "p", "github nightmare"

   Emitted | test.passed ([object Object])

 ✓ OK in 5616ms



   Emitted | test.after

   [3] Queued | hook Nightmare._after()

   [3] Queued | hook NesHelpers._after()

   [4] Starting recording promises

   Emitted | suite.after ([object Object])

   [4] Queued | hook Nightmare._afterSuite()

   [4] Queued | hook NesHelpers._afterSuite()



  OK  | 2 passed  // 20s

   Emitted | global.result ([object Object])

✨  Done in 26.43s.

`

with restart:false,

`Nightmare basic test yahoo
   [2] Starting recording promises
   Emitted | test.before
   [2] Queued | hook Nightmare._before()
   [2] Queued | hook NesHelpers._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "http://yahoo.com")
   [2] Queued | amOnPage: "http://yahoo.com"
   Emitted | step.after (I am on page "http://yahoo.com")
   [2] Queued | return step result
   Emitted | step.before (I fill field "p", "github nightmare")
   [2] Queued | fillField: "p", "github nightmare"
   Emitted | step.after (I fill field "p", "github nightmare")
   [2] Queued | return step result
   Emitted | step.before (I click "#uh-search-button")
   [2] Queued | click: "#uh-search-button"
   Emitted | step.after (I click "#uh-search-button")
   [2] Queued | return step result
   [2] Queued | fire test.passed
   [2] Queued | finish test
   Emitted | step.start (I am on page "http://yahoo.com")
 • I am on page "http://yahoo.com"
   [2] Error | Nothing responds to "goto"
   [2] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [2] <teardown> Queued | hook Nightmare._failed()
   [2] <teardown> Queued | hook NesHelpers._failed()
   [2] <teardown> Queued | () => done(err)
   [2] <teardown> Stopping recording promises
 > Screenshot is saving to /Users/Rarcita/Applications/NES/nes-e2e-tests/e2e-output/Nightmare_basic_test_yahoo.failed.png
   [2] <teardown> Error | Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
   [2] <teardown> Stopping recording promises
 ✖ FAILED in 30363ms

   Emitted | test.after
   [2] <teardown> Queued | hook Nightmare._after()
   [2] <teardown> Queued | hook NesHelpers._after()
 Nightmare basic test google
   [3] Starting recording promises
   Emitted | test.before
   [3] Queued | hook Nightmare._before()
   [3] Queued | hook NesHelpers._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "http://google.com")
   [3] Queued | amOnPage: "http://google.com"
   Emitted | step.after (I am on page "http://google.com")
   [3] Queued | return step result
   Emitted | step.before (I fill field "p", "github nightmare")
   [3] Queued | fillField: "p", "github nightmare"
   Emitted | step.after (I fill field "p", "github nightmare")
   [3] Queued | return step result
   [3] Queued | fire test.passed
   [3] Queued | finish test
   Emitted | step.start (I am on page "http://google.com")
 • I am on page "http://google.com"
 > [URL] https://www.google.com.ar/?gfe_rd=cr&ei=YrRTWYP2CsWgxgT0zpfQCg&gws_rd=ssl
 > [Code] 200
 > [Headers] {"alt-svc":["quic=\":443\"; ma=2592000; v=\"39,38,37,36,35\""],"cache-control":["private, max-age=0"],"content-encoding":["gzip"],"content-type":["text/html; charset=UTF-8"],"date":["Wed, 28 Jun 2017 13:51:30 GMT"],"expires":["-1"],"p3p":["CP=\"This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info.\""],"server":["gws"],"set-cookie":["NID=106=U8rY6oNi10tC4LuCBhaaT2ozN8o0LmFXaaVnl5QrxbOd6pNls_7KXgH32C7wQTSJJo421pqDfhMX8JKBEHfG2HTn56zl_1uYhwutb21-z08in484JWN7v2IP_w2DgY7s; expires=Thu, 28-Dec-2017 13:51:30 GMT; path=/; domain=.google.com.ar; HttpOnly"],"status":["200"],"x-frame-options":["SAMEORIGIN"],"x-xss-protection":["1; mode=block"]}
   Emitted | step.start (I fill field "p", "github nightmare")
 • I fill field "p", "github nightmare"
   Emitted | test.passed ([object Object])
 ✓ OK in 4528ms

   Emitted | test.after
   [3] Queued | hook Nightmare._after()
   [3] Queued | hook NesHelpers._after()
   [4] Starting recording promises
   Emitted | suite.after ([object Object])
   [4] Queued | hook Nightmare._afterSuite()
   [4] Queued | hook NesHelpers._afterSuite()

-- FAILURES:

  1) Login: Nightmare basic test yahoo:
     [Wrapped Error] "Nothing responds to \"goto\""
  
  Scenario Steps:
  
  - I.click("#uh-search-button") at Test.Scenario (test-e2e/tests/01_login/login_spec.js:29:3)
  - I.fillField("p", "github nightmare") at Test.Scenario (test-e2e/tests/01_login/login_spec.js:28:3)
  - I.amOnPage("http://yahoo.com") at Test.Scenario (test-e2e/tests/01_login/login_spec.js:27:3)
  
  Error: [Wrapped Error] "Nothing responds to \"goto\""
      at promise.catch (node_modules/codeceptjs/lib/recorder.js:107:15)
      at process._tickCallback (internal/process/next_tick.js:109:7)


  FAIL  | 1 passed, 1 failed   // 35s
   Emitted | global.result ([object Object])
error Command failed with exit code 1.
`

**Comment by APshenkin** [comment]
It's fixed in master now, but there is other issue. Wait when this PR will be merged https://github.com/Codeception/CodeceptJS/pull/581
