### ISSUE TITLE
Repository title grammar error

### ISSUE THREAD

**Issue by nrebhun** [Codeception/CodeceptJS#566]
#### What are you trying to achieve?
Minor grammar correction in the repo's title.
Should be:

```
Modern Era Acceptance Testing Framework for NodeJS
```

#### What do you get instead?
It is:

```
Modern Era Aceptance Testing Framework for NodeJS
```
(missing a `c` in `Acceptance`)

### Details
n/a

**Comment by nrebhun** [comment]
@DavertMik Negligible change to the repo, while you're online 😬 
Cheers!

**Comment by nrebhun** [comment]
Issue resolved 👍

**Comment by DavertMik** [comment]
Thanks!
