### ISSUE TITLE
CodeceptJS isnt acting properly on Google Web Toolkit interfaces.

### ISSUE THREAD

**Issue by sivnz** [Codeception/CodeceptJS#567]
#### What are you trying to achieve?

Automate an application created using Google Web Toolkit

#### What do you get instead?

CodeceptJS doesnt give any output.
It seems that the action was done but nothing happens.

#### Verbose details:

 I.click('#begin-process');
   Emitted | step.before (I click "#begin-process")
   [2] <pause> Queued | click: "#begin-process"
   Emitted | step.after (I click "#begin-process")
   [2] <pause> Queued | return step result
   [2] <pause> Queued | ask for next step
   Emitted | step.start (I click "#begin-process")
 * I click "#begin-process"

I made a screen gif acessible [here](http://i.imgur.com/DHIEn24.gifv).

### Details

* CodeceptJS version:  v0.6.3
* NodeJS Version: v7.2.0
* Operating System: Windows 10
* Nightmare version: v2.10.0

--- 

Does anybody seen this before?
I have this problem with 2 different applications that use the same technology.

**Comment by hubidu** [comment]
Did you try webdriverio with selenium/chrome or phantomjs in comparison. I found nightmare quite buggy when i tried it last time 

Is this the only Element with this id (#begin-process) on the page? Are there any errors in the browser console?

**Comment by sivnz** [comment]
Yes, the #begin-process is the only element with this id.

I might give it a try on WebDriverIO on my next sprint.
As soon as i discover what happened i'll report back in here.

Thanks @hubidu :)

**Comment by APshenkin** [comment]
Closing due inactivity
