### ISSUE TITLE
Error in version 0.2.6

### ISSUE THREAD

**Issue by fabioel** [Codeception/CodeceptJS#57]
@DavertMik 
I get a very strange error in the current version
When I make a clean npm-install I get the following line in the `lib/codecept.js`

```global.Helper = codecept_helper = require('./helper');```

I have no Idea why. I checked your current `master` and the line should be:

```global.codecept_helper = require('./helper');```

Is it possible that some script of yours is causing this problem?

I fixed it locally with the following:

```global.Helper = global.codecept_helper = require('./helper');```

**Comment by DavertMik** [comment]
Right, sorry for that. Looks like I didn't merge right from my local branch :(

**Comment by DavertMik** [comment]
Fixed in 0.2.7. Sorry for such stupid issue )
