### ISSUE TITLE
Bug: Set nightmare timeouts in config file

### ISSUE THREAD

**Issue by tamascsaba** [Codeception/CodeceptJS#577]
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# Error: .wait() timed out after 1000msec
```
### Details

* CodeceptJS version: v0.6.3
* NodeJS Version: v7.10.0
* Operating System: Linux
* Nightmare Configuration file:

```js
{
  "name": "foo",
  "tests": "src/**/*.e2e.js",
  "timeout": 300000,
  "output": "build",
  "helpers": {
    "Nightmare": {
      "url": "https://localhost:8080",
      "waitTimeout": 300000,
      "show": true,
      "restart": false
    }
  },
  "teardown": null,
  "hooks": []
}
```

**Comment by chrisbrainerd** [comment]
Try `waitForTimeout` instead of `waitTimeout` - `waitTimeout` is the Nightmare way of doing it, but the [Nightmare Helper](http://codecept.io/helpers/Nightmare/) way of doing it is `waitForTimeout`.
