### ISSUE TITLE
mochawesome reporter generated output does not contains descriptive steps

### ISSUE THREAD

**Issue by ChaseVoid** [Codeception/CodeceptJS#579]
#### What are you trying to achieve?
Generate a test report using mochawesome where the test details have same output as with --steps CLI option. example -
```
Forms --
 test something
 • I am on page "/documentation"
 • I fill field "Email", "hello@world.com"
```

#### What do you get instead?
mochawesome generated html file contain coded steps rather than descriptive steps
```js
I.amOnPage('/documentation');
I.fillField('Email', 'hello@world.com');
```

> Provide test source code if related

```js
Feature('Forms');

Scenario('test something', (I) => {
  I.amOnPage('/documentation');
  I.fillField('Email', 'hello@world.com');
  I.fillField('Password', '123456');
  I.checkOption('Active');
  I.checkOption('Male');  
  I.click('Create User');
  I.see('User is valid');
  I.dontSeeInCurrentUrl('/documentation');  
});
```
### Details

* CodeceptJS version: 
* NodeJS Version: v8.1.0
* Operating System: macOS
* WebDriverIO  (if related): "codeceptjs-webdriverio": "^1.0.1"
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://simple-form-bootstrap.plataformatec.com.br/",
      "browser": "firefox"
    }
  },
  "include": {},
  "mocha": {
    "reporterOptions": {
      "reportDir": "output"
    }
  },
  "name": "testcodecept"
}

```

**Comment by APshenkin** [comment]
@ChaseVoid It's by design in mocha. 
Mochawesome has access to test code and failure message. So it prints source code usual and print stacktrace with executed steps, when test fails. We can't change mochawesome output because it's third party reporter.

**Comment by ChaseVoid** [comment]
I understand that it would print the code during failures, but it does the same when the tests are pass as well.

**Comment by APshenkin** [comment]
@ChaseVoid Please provide configurations, when You can see descriptive steps in mochawesome and not. Also please attach screenshots for this issue.
Nothing was changed that may cause this change. BTW I've never seen descriptive steps in mochawesome report

**Comment by junguchina** [comment]
@ChaseVoid Maybe you can update the version of mochawesome, now the version is 2.x.
In my case, my test report by mochawesome works well both passed cases and failed cases.

**Comment by ChaseVoid** [comment]
I tried will all latest version of the libraries but the result was still the same. I'll try to find the "working" version.

`
  "dependencies": {
    "codeceptjs": "^0.6.3",
    "mochawesome": "^2.3.0",
    "nightmare": "^2.10.0",
    "nightmare-upload": "^0.1.1",
    "rimraf": "^2.6.1",
    "selenium-standalone": "^6.5.0",
    "webdriverio": "^4.8.0"
  }
`
