### ISSUE TITLE
Ng-blur not being triggered by fillField.

### ISSUE THREAD

**Issue by sivnz** [Codeception/CodeceptJS#582]
#### What are you trying to achieve?

Im trying to fill a form with fields that have ng-blur attribute.

#### What do you get instead?

The form is filled properly but it doesnt trigger the ng-blur.
I made a screen gif available [here](http://i.imgur.com/KMdEHzc.gif)

### Details

* CodeceptJS version: v0.6.3
* NodeJS Version: v7.2.0
* Operating System: Windows 10
* Nightmare version: v2.10.0

-------

Does CodeceptJS trigger events used in form validations?

**Comment by APshenkin** [comment]
@sivnz I think it doesn't related to codeceptJS, it's related to selenium/Nightmare. You can easy test it, just create the same test in plain selenium/Nightmare. I think you have to pass this question to Nightmare creators

**Comment by sivnz** [comment]
@APshenkin makes total sense.
I'll test and report here the results.

**Comment by APshenkin** [comment]
Close due inactivity
