### ISSUE TITLE
Chrome v59 no longer supports embedded credentials in url.

### ISSUE THREAD

**Issue by manjeetsingh1986** [Codeception/CodeceptJS#587]
#### so now how to handle windows authentication pop-up for username/password in codceptJS.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version: v0.6.3
* NodeJS Version:v6.9.5
* Operating System: macOS Sierra V 10.12.5
* Protractor || WebDriverIO || Nightmare version (if related) Protractor Version 5.1.2
* Configuration file:

```js
# paste suite config here
```

**Comment by BorisOsipov** [comment]
Hi @manjeetsingh1986 

Temporarily I passed following configuration to webdriverio helper and it helped me

     "desiredCapabilities": {
        "chromeOptions": {
          "args": [
            "disable-blink-features=BlockCredentialedSubresources"
          ]
        }
      }

But I don't know how to pass chrome options to protractor through codeceptjs.

**Comment by manjeetsingh1986** [comment]
Hi @BorisOsipov 

Thank you for you suggestion. actually it worked with below configuration 👎 

"capabilities": {
    "chromeOptions": {
      "args": ["disable-blink-features=BlockCredentialedSubresources"]

Thanks a lot for your help.
