### ISSUE TITLE
Protractor - scrollTo

### ISSUE THREAD

**Issue by romanovma** [Codeception/CodeceptJS#588]
#### What are you trying to achieve?
Use `scrollTo` in protractor helper.
Is it possible to use `scrollTo` function with protractor helper?

#### What do you get instead?
```bash
I.scrollTo is not a function
```
### Details

* CodeceptJS version: 0.5.1
* NodeJS Version: 7.10.0
* Operating System: Mac OS
* Protractor: 5.1.1

**Comment by nathand8** [comment]
@romanovma, if you're using the protractor helper, there is no scrollTo function. (see docs [here](http://codecept.io/helpers/Protractor/))

You may have seen scrollTo in the [WebDriverIO helpers](http://codecept.io/helpers/WebDriverIO/#scrollto)

**Comment by romanovma** [comment]
Yep, any plans to add it?

**Comment by nathand8** [comment]
Sorry I misread your request. I too would appreciate this function being added :)

**Comment by LukoyanovE** [comment]
Looks like issue was implemented and should be closed
