### ISSUE TITLE
Codecept config should be JS not JSON

### ISSUE THREAD

**Issue by sourcec0de** [Codeception/CodeceptJS#59]
@DavertMik I think it would be more useful to load the config as a `.js` file rather than `.json`.
I would be happy to chat about this and submit a pull request for this feature if I can get some direction on developing on `codeceptjs`. I don't like wondering in the dark trying to figure out where everything lives :)

You get some beneifits in doing this.
- environemtnal variables can be controlled outside so you don't have to configure a seperate config per environment
- it can be better controlled programatically
- you can check everything into source control without exposing secrets.

``` js
/**
 * CodeCeptJS Config
 */

module.exports = {
  tests: './tests/*_test.js',
  timeout: 10000,
  output: './tests/reports/',
  helpers: {
    WebDriverIO: {

      // load variables from the environment and provide defaults
      url: process.env.CODECEPT_URL || 'http://localhost:3000',
      browser: 'chrome',

      user: process.env.CLOUDSERVICE_USER,
      key: process.env.CLOUDSERVICE_KEY,

      desiredCapabilities: {
        'browserstack.local': true,
        'browserstack.debug': true
      },

      capabilities: [{
        browserName: 'chrome',
        'browserstack.local': true,
        'browserstack.debug': true
      }],

      logLevel: process.env.WEBDRIVERIO_LOG_LEVEL || 'warn',
      coloredLogs: true,
      waitforTimeout: 10000
    }
  },
  include: {},
  bootstrap: false,

  // don't build monolithic configs
  mocha: require('./tests/mocha_config.js') || {},
  name: 'vortex'
};
```

**Comment by DavertMik** [comment]
I was thinking on such declaration but json seemed simpler to me. Maybe you are right. At least I need some more time to think on it.

Sorry, right now I'm busy with my other projects, so I will get back here soon and provide a proper response.

**Comment by adrianblynch** [comment]
This could easily be backwards compatible too.

I think I prefer JS over JSON for config now.

**Comment by DustinDSchultz** [comment]
If you want to be able to provide the full range of Protractor settings (including the callbacks) you'll need to use a .js file. I'm running into this issue right now.

**Comment by DioNNiS** [comment]
+1

**Comment by stephane-ruhlmann** [comment]
Still not released on npm ?

**Comment by Psychedelix** [comment]
+1

**Comment by stephane-ruhlmann** [comment]
Released with : https://github.com/Codeception/CodeceptJS/commit/9d606f9350b790cedc104858900dde57d15a17fb

**Comment by stephane-ruhlmann** [comment]
@DavertMik should be closed by now?

**Comment by DavertMik** [comment]
Yes, sure. Here is the reference for JS config format http://codecept.io/configuration/#dynamic-configuration
