### ISSUE TITLE
question about pipelining codeceptjs tests

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#594]
question: in a dev pipeline, would you start the codeceptjs regression tests within a Grunt-test or with a Jenkins task?

I am not sure where to put it ;)

**Comment by hubidu** [comment]
Why Not just start Them with an npm script (npm test for Instance) and run them with a shell task?

**Comment by joelgrimberg** [comment]
because I want it to start automatically when there happens a commit to a specific branch.

**Comment by APshenkin** [comment]
Looks like you have to start tests after your application was deployed. What CI system do you use? Like @hubidu I recommend to use npm task - it's the easiest way to run tests

**Comment by DavertMik** [comment]
> or with a Jenkins task?

My choice is to use Jenkins task. Split test by groups (configured by `--grep`) and run such tasks in parallel
