### ISSUE TITLE
Error when installing codeceptjs-protractor

### ISSUE THREAD

**Issue by SebDuf** [Codeception/CodeceptJS#595]
#### What are you trying to achieve?

Install codecept-protractor using `npm i codeceptjs-protractor --save`

#### What do you get instead?

```
npm ERR! path C:\Users\Seb\WebstormProjects\desktop\node_modules\codeceptjs-protractor\node_modules\.bin\codeceptjs
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Seb\WebstormProjects\desktop\node_modules\codeceptjs-protractor\node_modules\.bin\codeceptjs'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Seb\AppData\Roaming\npm-cache\_logs\2017-07-11T19_48_40_645Z-debug.log
```

### Details

* CodeceptJS version: 0.6.3
* NodeJS Version: 6.11.0
* Operating System: Windows 10
* Protractor Version: 5.1.2

Installing codecept worked fine via `npm i codeceptjs --save` but I can't install the helpers

**Comment by BorisOsipov** [comment]
it looks like the same issue as https://github.com/Codeception/CodeceptJS/issues/583

**Comment by DavertMik** [comment]
Thanks for the report. I just updated all meta packages to make them compatible with latest npm
please update
