### ISSUE TITLE
Can I set grep within codecept.conf.js?

### ISSUE THREAD

**Issue by dwaned** [Codeception/CodeceptJS#610]
#### What are you trying to achieve?
I want to set grep within codecept.conf.js so that I can pass its value from an process environment variable. The reason why I want to do it through the config is because I am trying to pass it to the docker-compose file via the environment section.

The only way I found grep within codecept.conf.js file is under the "multiple" section, which I am not using at the moment.

**Comment by DavertMik** [comment]
Nope, but you are right this is must-have feature.

**Comment by DavertMik** [comment]
Added to CodeceptJS 1.1.2
