### ISSUE TITLE
Codecept/Nightmare Helper Issues: _locate method can't find element in DOM

### ISSUE THREAD

**Issue by willcooley** [Codeception/CodeceptJS#611]
#### What are you trying to achieve?
Locate an element in the DOM, and access its attribute values.

#### What do you get instead?

Trying to access an element in the DOM, but nightmare is not able to locate it.

### Details

I keep getting a terminal error: Cannot read property 'browser' of undefined"

```js
'use strict';
// let's use chai assertion library
let assert = require('chai').assert;


class DOMHelpers extends Helper {

  seeAttributeContains(locator, attribute, expectedValue) {

    let browser = this.helpers['Nightmare'].browser;
    // find an element by CSS or XPath:
    return this.helpers['Nightmare']._locate(locator).then(function(els) {
      // we received an array with IDs of matched elements
      // now let's execute client-side script to get attribute for the first element
      return browser.evaluate(function(el, attribute) {
        // this is executed inside a web page!
        return codeceptjs.fetchElement(el).getAttribute(attribute);
      }, els[0], attribute); // function + its params
    }).then(function(attributeValue) {
      // get attribute value and back to server side
      // execute an assertion
      assert.include(attributeValue, expectedValue);
    });
  }
}

module.exports = DOMHelpers;
```

package.json
```js
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "e2e": "codeceptjs run --steps",
    "report": "codeceptjs run --reporter mochawesome"
  },
  "repository": {
    "type": "git",
    "url": "----"
  },
  "keywords": [
    ""
  ],
  "author": "",
  "license": "",
  "dependencies": {
    "chai": "^4.1.0",
    "codeceptjs": "^0.6.3",
    "codeceptjs-nightmare": "^1.1.0",
    "nightmare": "^2.10.0",
    "nightmare-upload": "^0.1.1"
  },
  "devDependencies": {
    "mocha-junit-reporter": "^1.13.0",
    "mochawesome": "^2.3.0"
  }
}
```
codecept.conf.js
```js
exports.config = {
  "tests": "./test/*/*_spec.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": process.env.CODECEPT_URL || "http://localhost:8080",
      "show": true,
      "restart": true,
      "windowSize": "1200x1080"
    },
    "DOMHelpers": {
      "require": "./helpers/domhelpers_helper.js"
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {
    "reporterOptions":{
      "moduleFile": "output/result.xml",
      "reportDir": "output"
    }
  },
  "name": "-----"
};
```
being used as:
```js
I.seeAttributeContains('body', 'class', 'xs-open');
```

**Comment by willcooley** [comment]
any ideas? lol, there aren't many examples of helpers with nightmare.js and codecept.js

**Comment by willcooley** [comment]
So basically, the issue is that the codeceptjs container.js createhelper method is not instantisting the Nightmare module. Any thoughts?

**Comment by willcooley** [comment]
It seems like the issue is actually the _locate method can't find the element on the DOM even though it exists. I removed the require helper in the top of the file, and that fixed the module loading issue for nightmare being defined. 

Any ideas why locate doesn't work in a custom helper?

**Comment by willcooley** [comment]
@APshenkin do you have any idea why when i go to create a helper for nightmare.js the _locate method returns back saying the element can't be located in the DOM? It's the code example above.

**Comment by willcooley** [comment]
@DavertMik any ideas?

**Comment by DavertMik** [comment]
I reproduced this bug. Now I need some time to fix it

**Comment by DavertMik** [comment]
Ok. Bad news. This is the bug. `_locate` should use `findAndStoreElements`:

```js
  _locate(locator) {
    locator = guessLocator(locator) || { css: locator};
    return this.browser.evaluate(function (by, locator) {
      return codeceptjs.findAndStoreElements(by, locator);
    }, lctype(locator), lcval(locator));
  }
```
Good news. I have fixed it and applied your code as a test.
So this will be fixed in next release

**Comment by willcooley** [comment]
Thanks!

**Comment by bwaybandit** [comment]
I understand this has been closed. Using "nightmare": "^3.0.0" and the same code as above and _locate is not working. Can someone confirm _locate is working/not working in 3.0.0?

**Comment by bwaybandit** [comment]
{
  "dependencies": {
    "chai": "^4.1.2",
    "co": "^4.6.0",
    "codeceptjs": "^1.1.6",
    "nightmare": "^3.0.0",
    "nightmare-har-plugin": "^0.9.1",
    "nightmare-upload": "^0.1.1",
    "unirest": "^0.5.1",
    "webdriverio": "^4.12.0"
  }
,"scripts": {"test":"mocha tests/*.js"}, "license": "MIT", "name": "cloudAccess", "version": "0.0.1" }
