### ISSUE TITLE
Problem with arrow functions without parentheses still exist

### ISSUE THREAD

**Issue by davorb** [Codeception/CodeceptJS#617]
This was supposed to have been fixed in #127, but the problem still exists.

```js
Feature('Login')

Before((I) => {
  I.amOnPage('/')
  I.waitForText('Promotions', 10)
})

Scenario('logging in', I => {
  I.fillField('username', 'annisukino87')
  I.fillField('password', 'Abc123')
  I.click('log-in')
  I.waitForText('Ruby Store', 10)
  I.amOnPage('/en/adventure')
})
```

Will lead to the error message `Object of type 'username' is not defined in container`. Adding a pair of parentheses around `I` fixes this issue.

I've verified that we're running a version of the code that has this fix present (`0.6.3`).

**Comment by DavertMik** [comment]
We changed the library for parsing functions so I believe this is now fixed in master.
It should be fixed in next release

**Comment by davorb** [comment]
That's great, thanks.

Should I close this issue, or leave it open for a while, in case anyone else encounters it?

**Comment by DavertMik** [comment]
Please check the code after 1.0 release. If anything ok - close it

**Comment by APshenkin** [comment]
Close due inactivity
