### ISSUE TITLE
Mock API responses

### ISSUE THREAD

**Issue by nicolasiensen** [Codeception/CodeceptJS#625]
#### What are you trying to achieve?
I'm using CodeceptJS to test a single page application that relies on an API for most of its features. In order to improve the isolation between the app and the API, I would like to intercept all the API calls performed by the app during the tests and return fake API responses.

The app I'm testing with CodeceptJS is being served on `localhost`, and Selenium uses Google Chrome to perform the tests.

I could think about two different solutions so far to solve this problem:

1) add some extra code in the app to check if it is the testing environment, then use some kind of library like Sinon.js to mock all API calls;

2) point the app to a fake API, that is going to return fake responses. This fake API could be a very simple `express` app used only during the CodeceptJS tests;

Although both solutions sound reasonable, I would like to ask the community if there are best practices regarding this isolation of the app and the API for testing purposes.

Cheers!

**Comment by DavertMik** [comment]
I think for your case you should follow the 2nd path.
You can add the fake API application to bootstrap/teardown hooks so it would be started with tests.

If you run acceptance test, you test the app from the outside, this way you should not rely on anything internal in it, like environment detection or sinon mocks. It should work just as it would for your users. The changes you can do with sinon are not a part of your API so this can be the really fragile solution. So yes, I'd choose the fake API.

**Comment by nicolasiensen** [comment]
Thanks for the answer, @DavertMik. I totally agree when you say that I shouldn't change the behavior of the app when running the acceptance tests, but mock the external services instead. I'm closing this issue since we agree that there is a very clear path to move forward in this regard.

Cheers!
