### ISSUE TITLE
keepCookies flag also closes tabs from version 1.0.0

### ISSUE THREAD

**Issue by abidhahmed** [Codeception/CodeceptJS#629]
Have been on version 0.6.3 for a while until today, and I just noticed that keepCookies flag will close existing tabs & clear local storage unlike before. Looks like an intended design decision?

Commit that seems to have started this:
https://github.com/Codeception/CodeceptJS/pull/568/commits/68bbe79d5e3ee36a82e165a0a9f388889e193cd9

Wouldn't it be appropriate to keep local storage and not touch existing tabs in a situation where we need cookies to stay alive in the first place? Thoughts?

Thanks. Really love CodeceptJS!

**Comment by APshenkin** [comment]
@abidhahmed I think that the best way is provide an option that will ignore all flags and keep browser in the same state between tests. I'll add it.

**Comment by abidhahmed** [comment]
That would be perfect, thanks @APshenkin
