### ISSUE TITLE
Cookies aren't being cleared from local storage (1.0.0)

### ISSUE THREAD

**Issue by lisettea** [Codeception/CodeceptJS#631]
Thanks for the 1.0.0 release. it really did fix all my webdriver is null //hook issues! Unfortunately, bumped straight into my next issue: My cookies just aren't going anywhere.

#### What are you trying to achieve?

each session starts with a cookie notice being clicked away, but in between feature files my cookies are no longer being deleted. Selenium SAYS it's deleting the cookies and clearing local storage, but the next browser which opens does so without the cookie notification showing up, and the cookies from the previous session are shown in Local Storage.

#### What do you get instead?
Cookies remain in local storage

> Provide console output if related. Use `--verbose` mode for more details.

```bash
13:31:36.167 INFO - Executing: [delete all cookies])
13:31:36.620 INFO - Done: [delete all cookies]
13:31:36.635 INFO - Executing: [execute script: localStorage.clear();, []])
13:31:36.651 INFO - Done: [execute script: localStorage.clear();, []]
```
> Provide test source code if related

```php
 I.amOutsideAngularApp();	
	  I.amOnPage('https://www.centraalbeheer.nl');
	  I.waitAngular();
    I.switchFrameXpath("//iframe[contains(@style, 'z-index')]");
    I.wait(2);
    I.waitForVisible("//a[contains(@href, 'popup_accept')]", 10);
    I.click("//a[contains(@href, 'popup_accept')]");
    I.switchFrame(null);
    I.amInsideAngularApp();	
```
test continues from there.  But it fails on testfile 2 (we use a file per scenario) where the cookie popup doesn't show. - doesn't matter if it's a fail test moving on to the next file, a succesfull test moving on to the next test or a failed test being retried.

### Details

* CodeceptJS version: 1.0.0
* NodeJS Version:
* Operating System: Windows
* Protractor || WebDriverIO || Nightmare version (if related) Protractor 5.1.2
* Configuration file:

```js
    tests: 'tests/Uitvoeren/*.js',
    timeout: 20000,
    output: './output',
    helpers: {
        Protractor: {
            'seleniumAddress': 'http://localhost:4446/wd/hub',
            'url': homepage url,
            'browser': 'chrome',
            'rootElement': 'body',
            'scriptsTimeout': 30000,
        },

        Iframe: {
            require: './helpers/iframe_helper.js'
        }
    },

    include: createIncludeObject(),

    mocha: {
        reporterOptions: {
            reportDir: 'report',
            reportName: 'chrome-report'
        }
    },
}
```

**Comment by APshenkin** [comment]
@lisettea HI!
Could you please provide your config file?
Also what browser do you use for your tests?

Also reproducible code will be helpful

**Comment by lisettea** [comment]
Appended main issue with config file. Running tests on Chrome using Chromedriver v. 2.31 - my colleague reproduced the issue on 2.29 however

**Comment by lisettea** [comment]
It's because restart: false (default) no longer opens a new browser - just continues in the same browser untill the end of the suite. Adding restart: true,  to the config file fixes it.

**Comment by APshenkin** [comment]
Yes, we don't close browser with restart: false. But it's wrong flow, when we end test we have to clear cookies and local storage. I'll investigate this issue

**Comment by APshenkin** [comment]
@lisettea 
Found the reason. When we click `Akkord` on https://www.centraalbeheer.nl, then cookies sets to other domains
![image](https://user-images.githubusercontent.com/14344430/28580540-71260636-7168-11e7-9c00-244cec589ab1.png)
We can't clear them, because of browser and Webdriver limitations. Because of this with `restart:false` option you don't see popup (several cookies stay in browser)

So there is 2 options what I know:
1. Don't use `restart:false` option
2. (Only local selenium, only chrome) Set chrome option `user-data-dir=userdir` and then after each test you can erase `userdir/Default/Cookies`  and be sure, that all cookies are deleted

**Comment by lisettea** [comment]
Thanks for looking into it!
