### ISSUE TITLE
Syntax error in home page of codecept.io

### ISSUE THREAD

**Issue by parmentf** [Codeception/CodeceptJS#632]
#### What are you trying to achieve?

Understand code in "IN ACTION" part of http://codecept.io/index.html

#### What do you get instead?

There is a syntax error in the code: a lacking `{`.

See [index.html](https://github.com/Codeception/CodeceptJS/blob/gh-pages/index.html#L333).

The correct line would be:

```js
Scenario('submit form successfully', (I) => {
```

**Comment by DavertMik** [comment]
Fixed
