### ISSUE TITLE
WebdriverIO seeNumberOfVisibleElements fails if locator looks like {css: '.class'}

### ISSUE THREAD

**Issue by BorisOsipov** [Codeception/CodeceptJS#639]
#### What are you trying to achieve?
Use seeNumberOfVisibleElements with object locator.
 I.seeNumberOfVisibleElements({"xpath":"//div[@class='featurette']"}, 4) 
#### What do you get instead?
I got the error.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
-- FAILURES:

  1) Tset: seeNumberOfVisibleElements test:
     selector needs to be typeof `string`
  
  Scenario Steps:
  
  - I.seeNumberOfVisibleElements({"xpath":"//div[@class='featurette']"}, 4) at Test.<anonymous> (tests\tset_test.js:5:7)
  - I.amOnPage("https://github.com/") at Test.<anonymous> (tests\tset_test.js:4:7)
  
  Error: selector needs to be typeof `string`
      at elements([object Object]) - node_modules\codeceptjs\lib\helper\WebDriverIO.js:1079:25
```
> Provide test source code if related

```js
Scenario("seeNumberOfVisibleElements test", function *(I) {
    I.amOnPage("https://github.com/");
    I.seeNumberOfVisibleElements({xpath: "//div[@class='featurette']"}, 4);
});
```
### Details

* CodeceptJS version: 1.0.0
* NodeJS Version: v7.9.0
* Operating System: Win10
* WebDriverIO

**Comment by BorisOsipov** [comment]
I made a pull request with corresponding test https://github.com/Codeception/CodeceptJS/pull/640

**Comment by APshenkin** [comment]
@BorisOsipov Found the reason of this issue, will fix it
