### ISSUE TITLE
Clicking on an element that moves via css clicks where the element was before css moved it

### ISSUE THREAD

**Issue by kpwn243** [Codeception/CodeceptJS#646]
#### What are you trying to achieve?
We are trying to click a checkbox that moves right via css hover

#### What do you get instead?
The click event is happening in the location where the checkbox was before the css hover moved the checkbox over to the right

> Provide test source code if related

```js
  I.amOnPage('/')
  I.see('You can\'t input the protocol without calculating the mobile RSS protocol!')
  I.see('We need to back up the wireless GB driver!')

  I.seeElement('div.message.read')
  I.seeElement('div.message.unread')
  
  I.checkOption('message-selector', 'div.message.unread')
```

### Details

* CodeceptJS version: 1.0.0
* NodeJS Version: 8.2.1
* Operating System: Mac OS X Sierra
* Protractor || WebDriverIO || Nightmare version (if related) WebDriverIO
* Configuration file:

```js
{
  "tests": "./**/*.e2e_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost:3000",
      "browser": "chrome"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "react-inbox"
}
```

**Comment by APshenkin** [comment]
@kpwn243 I can't understand you problem, can you please give more details?

Can you also try the usual click method?

**Comment by kpwn243** [comment]
@APshenkin The issue is that when the click test happens the "mouse" will move to where the checkbox is originally. When the mouse moves over the row in bootstrap the css:hover will force the row to move some amount of pixels to the right.  When the mouse finally arrives at the location where the checkbox is the checkbox has in fact moved to the right some pixels making the click event miss actually clicking on the checkbox.

Before the click line is happening the app looks like this:
<img width="284" alt="screen shot 2017-08-04 at 2 33 44 pm" src="https://user-images.githubusercontent.com/1355768/28984128-0a58b130-7922-11e7-97f8-d5dfccd0964a.png">

After the click is requested the app looks like this:
<img width="278" alt="screen shot 2017-08-04 at 2 36 33 pm" src="https://user-images.githubusercontent.com/1355768/28984194-5aaff382-7922-11e7-9090-120d1ff57e65.png">

See how the row moves to the right some amount of pixels.  The click is happening at the location where the checkbox is before it has been moved via css hovering.

**Comment by APshenkin** [comment]
@kpwn243 Thank you for detailed information. I can suggest to use `moveCursorTo` method to move cursor and get this css offset. And after this use `click` or `checkOption` methods.

Hope it helps!

**Comment by kpwn243** [comment]
Awesome thanks for the help!
