### ISSUE TITLE
I.click using inner text does not working properly

### ISSUE THREAD

**Issue by Jotohanes** [Codeception/CodeceptJS#647]
#### What are you trying to achieve?
I would like to click certain text in particular locator.
#### What do you get instead?
 Clickable element JETZT KAUFEN inside .mscom-link.c-call-to-action.c-glyph was not found by text|CSS|XPath

I am pretty sure it was not the case on previous version of codeceptjs since I got this error recently after I update my codeceptjs.

```shells
  Clickable element JETZT KAUFEN inside .mscom-link.c-call-to-action.c-glyph was not found by text|CSS|XPath
```

> Provide test source code if related

```js

Scenario('test something', (I) => {

    I.amOnPage('https://www.microsoft.com/de-de/');
    I.waitForVisible('.mscom-link.c-call-to-action.c-glyph');
    I.click('JETZT KAUFEN','.mscom-link.c-call-to-action.c-glyph');

});
    
```

### Details

* CodeceptJS version: 1.0.0
* NodeJS Version:  6.11.0
* Operating System: Windows 7 Pro, 2009
* WebDriverIO 
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "chrome"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "test"
}
```

**Comment by APshenkin** [comment]
@Jotohanes so, the problem is that `.mscom-link.c-call-to-action.c-glyph` element is link itself with  necessary text. When we add context in click, then the flow is:
1. Recieve all elements `context` and get first of them.
2. Get first inner element with text, using these locators:
```
let narrowLocator = xpathLocator.combine([
    `.//a[normalize-space(.)=${literal}]`,
    `.//button[normalize-space(.)=${literal}]`,
    `.//a/img[normalize-space(@alt)=${literal}]/ancestor::a`,
    `.//input[./@type = 'submit' or ./@type = 'image' or ./@type = 'button'][normalize-space(@value)=${literal}]`
  ]);

or
let wideLocator = xpathLocator.combine([
      `.//a[./@href][((contains(normalize-space(string(.)), ${literal})) or .//img[contains(./@alt, ${literal})])]`,
      `.//input[./@type = 'submit' or ./@type = 'image' or ./@type = 'button'][contains(./@value, ${literal})]`,
      `.//input[./@type = 'image'][contains(./@alt, ${literal})]`,
      `.//button[contains(normalize-space(string(.)), ${literal})]`,
      `.//input[./@type = 'submit' or ./@type = 'image' or ./@type = 'button'][./@name = ${literal}]`,
      `.//button[./@name = ${literal}]`
    ]);
```

So, when you set `.mscom-link.c-call-to-action.c-glyph` element, there is no inner elements. because of this we can't find elements with necessary text

I fixed this issue, but we need @DavertMik review to merge it

**Comment by Jotohanes** [comment]
Hello, thanks for fixing the problem. Thus, I will update it and let you know if there is another problem regarding to the issue.

**Comment by Jotohanes** [comment]
#### What are you trying to achieve?
So here the case is we have 4 objects with the same element-name (class-selector) and we want to click on particular element with specific text inside it. However, our test failed and it said that "Clickable element *text* inside *class-selector* was not found by text|CSS|XPath". 
I am pretty sure it works on previous version since our tests use this method regularly. 

As you can see, using .box.clearfix as class-selector give us 4 objects with the same selector. In this I.click method I also give the inner text to specify specific element to click onto .

I already change my WebdriverIO.js in my CodeceptJS lib but it still does not work in my case.
Sorry, I believe I did not give good example in the previous problem.



```JavaScript
Feature('Test click');

Scenario('test something', (I) => {

    I.amOnPage('https://www.check24.de/haftpflichtversicherung/');
    I.wait(5);
    I.click('Kfz-Haftpflicht','.box.clearfix');

});

```

### Details

* CodeceptJS version: 1.0.0
* NodeJS Version: 6.11.0
* Operating System: Windows 7 Pro, 2009
* || WebDriverIO || 
* Configuration file:

```js
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "phantomjs"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "Test click"
}
```
