### ISSUE TITLE
Conditionnal test based on element visibility

### ISSUE THREAD

**Issue by adeleco** [Codeception/CodeceptJS#648]
#### What are you trying to achieve?

Conditionnal code in a scenario, based on the visibility of an element.

#### Questions 
 1) How to use a conditional testing (if / else)
If (I.seeElement) {
  // code here
  }
else {
  // other code here
  }

 2) Is it possible to use exceptions management (try / catch / finally) 
try{
  // code here
  I.seeElement(locator);
}catch(exception){
  // other code here
}

best regards
adeleco

**Comment by 1vanhelsing1** [comment]
@adeleco did you find a way to do this?

**Comment by DavertMik** [comment]
Conditionals are not allowed in test scenarios. If you really need them you should implment them inside helpers. You will need to implment them using promises inside helpers.

But better don't do them at all in tests

**Comment by adeleco** [comment]
I haven't had time to do this yet.

@1vanhelsing1 if you do this please post a sample.

**Comment by adeleco** [comment]
@1vanhelsing1 
I'm back on testing. Have you wrote something about conditional testing ?

**Comment by reubenmiller** [comment]
Here is an [example](https://gist.github.com/reubenmiller/62f27ee3ed6ab8b9a4eab7c13dc2e08c) showing a conditional action in a Helper.

Exert.
```js
'use strict';
import assert from 'assert';

let Helper = codecept_helper;

class MyHelper extends Helper {
  async clickIfVisible(selector, ...options) {
    const helper = this.helpers['Puppeteer'];
    try {
      const numVisible = await helper.grabNumberOfVisibleElements(selector);

      if (numVisible) {
        return helper.click(selector, ...options);
      }
    } catch (err) {
      console.log('Skipping operation as element is not visible');
    }
  }
}

module.exports = MyHelper;
```

**Comment by vaijiNeel** [comment]
Hey, how do we call this helper method from another class? I need to check Checkbox only if it is not checked already. How do I implement this in CodeceptJS with webDriverIO? Appreciate any help!
