### ISSUE TITLE
I is not defined

### ISSUE THREAD

**Issue by thomasguillory** [Codeception/CodeceptJS#65]
Hi,
I'm trying to get the "Quickstart" working but I can't manage to get a simple example working. The global helper `I` seems to be an empty object.

```
[~/Projects/webapp]$ codeceptjs run --steps                                                                                                                                                                       *[test/codeceptjs] 
CodeceptJS v0.2.7
Test root is assumed to be /home/me/Projects/webapp

Test --
 test something
 ✖ FAILED in 1ms


-- FAILURES:

  1) Test test something:
     I.amOnPage is not a function
  
  TypeError: I.amOnPage is not a function
      at Test.<anonymous> (Test_test.js:5:7)
      at Context.test.fn (/usr/local/lib/node_modules/codeceptjs/lib/scenario.js:27:24)
```

My test is copy/pasted from the doc

```

Feature('Test');

Scenario('test something', (I) => {
    I.amOnPage('/')
});
```

My environment:

- Node 5.6.0 (I tried with 4.3.0, same result)
- CodeceptJS 0.2.7
- Ubuntu 12.04 LTS (actually ElementaryOS, based on Ubuntu 12.04, but shouldn't make a difference)

What am I doing wrong?

**Comment by DavertMik** [comment]
Did you create an initial config `codecept.json` with `codeceptjs init`. There should be a `helpers` section, where `WebDriverIO` module should be specified. `amOnPage` method is taken from that helper, so if it's  not set, CodeceptJS won't know where to locate it

**Comment by thomasguillory** [comment]
I did run `codeceptjs init`, but I just figured out that the "What helpers do you want to use?" step is a multiple select dropdown and I had to hit _Space_ and not _Enter_... It works now obviously, thanks.

**Comment by gaurav21r** [comment]
As with all defaults, the first one should be selected by default. Almost everyone is going to press Enter
