### ISSUE TITLE
Question - can you break out of within ?

### ISSUE THREAD

**Issue by cameronbraid** [Codeception/CodeceptJS#651]
I am writing a page fragment  that uses within to scope selectors to the location of the widget that it represents.  One action within this fragment causes a DOM popup to appear which is a child of the body element, and therefore I can't target it inside the within block.

Is there a way to break out of within (other than using jquery directly) ?

**Comment by APshenkin** [comment]
@cameronbraid currently there is no options to complete commands with elements in `within` block that are not in `within` element. You have to close `within` block, complete your actions with popup and then open `within` block again, if it's needed
