### ISSUE TITLE
@depends like alternative on js version

### ISSUE THREAD

**Issue by masterjg** [Codeception/CodeceptJS#653]
Hi, guys!
In our team we are using Codeception (PHP version) and are looking to migrating to CodeceptJs. However we did not find in docs if there is alternative to @depends tag? We need to control the sequence of tests.

**Comment by APshenkin** [comment]
@masterjs
Hi!
There is no alternative to @Depends tag. Tests executes in order in Feature file, but they will continue, if any of them fail.
Also there is Before hook that may help you.

There is no ability to set depends of tests now and I don't think that it will be implemented - there is no functionality in Mocha for it
