### ISSUE TITLE
How to set chromeOptions?

### ISSUE THREAD

**Issue by lsq4590578** [Codeception/CodeceptJS#660]
I am configration codecept.json value of chromeOptions,but failed,I am want to maximize of chrome 59 version,but codecept.json set "windowSize": "maximize" can't invalid

     "desiredCapabilities": {
        "browserName": "chrome",
       " acceptSslCerts": true,
        "chromeOptions": {
                 "args": "['--start-maximized']"
        }
    }

**Comment by APshenkin** [comment]
@lsq4590578 Firstly you can set maximize using `windowSize`:
```
{
   "helpers": {
     "WebDriverIO" : {
       "browser": "chrome",
       "restart": false,
       "windowSize": "maximize",
       "desiredCapabilities": {
          "browserName": "chrome",
          " acceptSslCerts": true
         }
     }
   }
}
```

Second, If you need to pass chromeOptions, you have to pass them without `--`
```
 "desiredCapabilities": {
    "browserName": "chrome",
   " acceptSslCerts": true,
    "chromeOptions": {
             "args": "['start-maximized']"
    }
}
```

Hope it helps

**Comment by APshenkin** [comment]
Close due inactivity
