### ISSUE TITLE
Cannot start appium server programatically with appium-controller

### ISSUE THREAD

**Issue by wjastrzemski** [Codeception/CodeceptJS#662]
#### What are you trying to achieve?

I want to start appium server programatically. I found "appium-controller":
https://www.npmjs.com/package/appium-controller
It looks very easy to use.

#### What do you get instead?

In my test I use this controller in before and after suite, like this:
```
BeforeSuite((I) => {
    I.say('Running test');
    let appiumController = require('appium-controller');
    appiumController.startAppium({
        port: '4723'
    });
});
```

Unfortunately when I started tests I have in console this:

```
appium is shutdown
Starting appium...
   Running test

Error: connect ECONNREFUSED 127.0.0.1:4728
 • I click "[id="tipico-welcome-promo"] [class="close-modal"]"
Error: A session id is required for this command but wasn't found in the response payload
appium is running on localhost:4723!
```

### Details

* CodeceptJS version:0.6.3
* NodeJS Version:7.10.0
* Operating System:macOS Sierra 10.12.4
* Appium: 1.6.5beta
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iOS simulator 10.2

**Comment by APshenkin** [comment]
@wjastrzemski Please update codeceptJS to latest version (1.0.1) and send us feedback about this issue

**Comment by DavertMik** [comment]
It is recommended to use boostrap/teardown hooks to start/stop external services. Please don't put that to your actual test code!
And yeah, please update to latest Codeception. CodeceptJS 0.6.3 doesn't have Appium support at all
