### ISSUE TITLE
Question about I.click , possible bug

### ISSUE THREAD

**Issue by Jotohanes** [Codeception/CodeceptJS#667]
#### What are you trying to achieve?
So here the case is we have 4 objects with the same element-name (class-selector) and we want to click on particular element with specific text inside it. However, our test failed and it said that "Clickable element *text* inside *class-selector* was not found by text|CSS|XPath". 
I am pretty sure it works on previous version since our tests use this method regularly. 

As you can see, using .box.clearfix as class-selector give us 4 objects with the same selector. In this I.click method I also give the inner text to specify specific element to click onto .

I already change my WebdriverIO.js in my CodeceptJS lib but it still does not work in my case.
Sorry, I believe I did not give good example in the previous problem.

```JavaScript
Feature('Test click');

Scenario('test something', (I) => {

    I.amOnPage('https://www.check24.de/haftpflichtversicherung/');
    I.wait(5);
    I.click('Kfz-Haftpflicht','.box.clearfix');

});

```

### Details

* CodeceptJS version: 1.0.0
* NodeJS Version: 6.11.0
* Operating System: Windows 7 Pro, 2009
* || WebDriverIO || 
* Configuration file:

```js
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "phantomjs"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "Test click"
}
```

**Comment by cguilhermef** [comment]
Still not working for me. Why this was closed? What is the solution?
