### ISSUE TITLE
Use an assert library in executeScript

### ISSUE THREAD

**Issue by thebaddeveloper** [Codeception/CodeceptJS#669]
#### What are you trying to achieve?
add assertions in an`executeScript()` function. What is the best way?
In general what are the limitations of executeScript?

#### What do you get instead?
```
"assert is not defined"
```
> Provide console output if related. Use `--verbose` mode for more details.

```bash
  Error: [Wrapped Error] "assert is not defined"
      at promise.catch (node_modules/codeceptjs/lib/recorder.js:134:15)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

> Provide test source code if related

```js
Feature('Assert Test');
var assert = require('chai').assert;
Scenario('Assert Test @sample', (I) => {
    I.amOnPage('http://www.google.com');
    assert.isTrue(true,"Failed Test");//works here
    I.executeScript(function(){
        assert.isTrue(false,"Failed execute Test");
    });
});
```

### Details

* CodeceptJS version: 1.0.1
* NodeJS Version: 4.2.0
* Operating System: MacOS 10.12.6
* Nightmare version: 1.1.0
* Configuration file:

```js
# paste suite config here
codecept.json
{
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": "http://localhost",
      "show": true,
      "openDevTools": {
        "mode": "detach"
      }
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "tests": "./tests/**/*_test.js",
  "timeout": 10000,
  "name": "saample"
}

package.json
{
  "name": "sample",
  "devDependencies": {
    "chai": "^4.1.1",
    "codeceptjs": "^1.0.1",
    "codeceptjs-nightmare": "^1.1.0"
  }
}
```

**Comment by APshenkin** [comment]
@thebaddeveloper In `executeScript` you can use only what is provided from your testing page. It's executes in browser, not in test. So the best way to do some asserts is to get some return value from browser script and assert it in test
