### ISSUE TITLE
Run Codeceptjs in TeamCity

### ISSUE THREAD

**Issue by filosoff88** [Codeception/CodeceptJS#673]
Hello, 

I'm noob in CI. Somebody can help me setup codeceptjs run with TeamCity?

**Comment by APshenkin** [comment]
@filosoff88 Seems that the best way is to ask help from your system administrators. You have to solve these questions:

1. Where will be you browsers: on agents or in Docker
2. Launch flow. You have to download your repo with tests, run npm to install dependencies and run tests.

There is a lot of information about TeamCity setup and configuration, so try to find information in Google.
