### ISSUE TITLE
Examples of usage PageFragment

### ISSUE THREAD

**Issue by emptyOne322** [Codeception/CodeceptJS#674]
Hi. I am trying to use Page Fragment for some modals. So is there any way to create a proper page fragment for multiple modals( for example by creating it with name)?

**Comment by APshenkin** [comment]
@emptyOne322 Hi!
Could you please clarify your question?
You can set any methods in PageFragment for any amount of modals. To use them you just need to add them in codecept config

**Comment by DavertMik** [comment]
I don't know. Here it is http://codecept.io/pageobjects/#page-fragments
If you need one fragment for multiple different areas you can use inheritance or reuse functions and properties across different modules
