### ISSUE TITLE
Execute bootstrap script once in mutilple execution

### ISSUE THREAD

**Issue by kinlu** [Codeception/CodeceptJS#678]
Now I am integrating Browserstack tunnel setup in the bootstrap of conf.js.  When the multiple execution happens, the bootstrap script get called multiple times.  Only one tunnel for a group of test is up while the other tunnels fail as well as their tests.

I tried to use localIdentifier in the capabilities setting however it doesn't work.  The test instances seem can't match up the identifiers.

Only way to work is
- Single test instance with browserstack tunnel setup in the bootstrap
- Multiple test instances with browserstack tunnel setup in a separate command line window

Is it possible to execute bootstrap script once in mutilple execution to allow multiple test instances with browserstack tunnel setup in the bootstrap?

**Comment by APshenkin** [comment]
@kinlu currently no, multiple execution creates several instances of codeceptjs. Each codeceptjs process launch bootstrap file. I think, we can create a new option that will launch bootstrap before launching codeceptJS instances and will skip bootstrap for these instances.

**Comment by reubenmiller** [comment]
Instead of only calling the bootstrap script once for `run-multiple`, a new hooks `bootstrapAll` is proposed in PR #962. This hook is only executed once. Also there is a new `teardownAll` hook proposed in the PR.

**Comment by reubenmiller** [comment]
Released in v1.1.6
