### ISSUE TITLE
Choose which config file

### ISSUE THREAD

**Issue by adrianblynch** [Codeception/CodeceptJS#68]
It might be useful to have the ability to choose the config file when running `codeceptjs run`.

Related to [Codecept config should be JS not JSON](https://github.com/Codeception/CodeceptJS/issues/59), either would allow better configuration options.

**Comment by DioNNiS** [comment]
+1

**Comment by DavertMik** [comment]
Yes, we have that. By default `codecept.conf.js` will be loaded, if not: `codecept.json`. See http://codecept.io/configuration/#dynamic-configuration
