### ISSUE TITLE
Create StackoverFlow wiki page

### ISSUE THREAD

**Issue by adrianblynch** [Codeception/CodeceptJS#69]
I've recently added `CodeceptJS` as a tag on SO.

The tag is still in the review period, namely if no one else tags a question with it, it'll be removed.

To help it remain, the tag could do with more info.

Tags can have an associated wiki page. This consists of an excerpt and the main body of the page.

See [jQuery's one](http://stackoverflow.com/tags/jquery/info) for an example. The excerpt is in the box at the top.

I have added an excerpt to the CodeceptJS tag, not visible until it's approved. If/When it is, it'll be [available here](http://stackoverflow.com/tags/codeceptjs/info).

This is what I added:

> CodeceptJS is a modern end to end testing framework with a special BDD-style syntax. The test is written as a linear scenario of user's action on a site. The use of generator functions allows asynchronous tests to be written in synchronous way.

So this issue is a request for a wiki page, to be added on SO.

**Comment by DavertMik** [comment]
Thanks!

**Comment by adrianblynch** [comment]
The excerpt was approved.

http://stackoverflow.com/tags/codeceptjs/info
