### ISSUE TITLE
WebDriverIO Helper _failed not called

### ISSUE THREAD

**Issue by m-idler** [Codeception/CodeceptJS#70]
Hello, i'm currently running some tests with the webdriverIO helper at crossbrowsertesting.com. I got the problem, that the `_failed` method within [WebDricverIO.js](https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/WebDriverIO.js#L137) isn't called. I played around a little bit inside the codeceptjs code and it looks like there is a problem with calling the `_failed` hooks in general. In [listeners/helper.js](https://github.com/Codeception/CodeceptJS/blob/master/lib/listeners/helper.js#L36) line 36 the `runAsyncHelpersHook` doesn't call the hook within the helper. It tried to use `runHelpersHook` instead of `runAsyncHelpersHook` and it worked - but i don't know whether this is a good solution or not.

Besides this error i also noticed that there might be another problem within [WebDriverIO.js](https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/WebDriverIO.js#L138), it looks like there should be `test.title` used instead of `test.name` for the filename creation (for my test run `test.name` isn't defined).

Beside these problem i also got some other problems:

`saveScreenshot` doesn't create any screenshots, but currently i assume that this is a problem with my configuration and/or using crossbrowsertesting.com via webdriverIO.

After a test failed, the remotely running test/instance via webdriverIO at crossbrowsertesting.com isn't stopped - i haven't found the reason yet and keep on looking for the solution, but maybe you have already heard of any similar problems.

thank you in advance & best regards

**Comment by DavertMik** [comment]
Thanks for detailed report. You really helped in posting and examining this issue. It was about managing the asynchronousity and it didn't do job well on failures. Now it does. Thanks
