### ISSUE TITLE
Can I see custom assertions in steps? 

### ISSUE THREAD

**Issue by egor-kamenev** [Codeception/CodeceptJS#700]
Can I see custom assertions in steps?

**Comment by APshenkin** [comment]
@egor-kamenev What do you mean when you say `custom assertions` ? Can you please give some more details?

If I understand you correctly, there are two ways:
1. Create custom helper (it could be your assertion library wrapper) to have access to your assertions from `I`
2. Add `I.say` command before your assertion to get output in steps

**Comment by APshenkin** [comment]
Close due inactivity
