### ISSUE TITLE
Multiple Test parallel 

### ISSUE THREAD

**Issue by JamesDawsonX** [Codeception/CodeceptJS#706]
#### What are you trying to achieve?
I have   25 javascript  files (25 tests). I want to run multiple tests at the same time, so I can save time.
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: v1.0.2
* NodeJS Version:  v6.10.0
* Operating System: MacOS
* phantom.js
* Configuration file:

```js
{
    "tests": "./tests/dev/*.js",
    "timeout": 10000,
    "output": "./output",
    "helpers": {
        "WebDriverIO": {
            "url": "http://www.myprivatehost.com",
            "browser": "phantomjs",
            "windowSize": "1600x1200",
            "mobilewindowSize": "1136x640"
        }
    },
    "include": {
        "I": "./custom.js"
    },
    "multiple": {
        "blogtest": {
            "browsers": [{
                "grep": "TEST1",

                "browser": "phantomjs",
                "windowSize": "1600x1200"
            }]
        },
        "mainwebsitetest": {
            "browsers": [{
                "grep": "TEST2",

                "browser": "phantomjs",
                "windowSize": "1600x1200"
            }]
        }
    },

    "bootstrap": false,
    "mocha": {},
    "name": "test_codecept"
}
```

**Comment by DavertMik** [comment]
Did you try to execute tests via http://codecept.io/commands/#run-multiple ?

**Comment by JamesDawsonX** [comment]
yes.. the problem   its  not parallel 
`[1.basic:phantomjs] TEST1 --
[2.basic2:phantomjs] TEST1 --
[1.basic:phantomjs]  ✓ OK in 1032ms
[1.basic:phantomjs]
[2.basic2:phantomjs]  ✓ OK in 1138ms
[2.basic2:phantomjs]
[1.basic:phantomjs] TEST2 --
[2.basic2:phantomjs] TEST2 --`

I want to execute  TEST1 and TEST2  at the same time

**Comment by DavertMik** [comment]
it is parallel, you are executing tests in 2 processes. See 1. and 2. in list.
Looks you didn't configure or execute it correctly as you expected

Maybe the problem is that you put `grep` option inside `browsers`.
Please update config to be like this:

```js
    "multiple": {
        "blogtest": {
                "grep": "TEST1",

            "browsers": [{

                "browser": "phantomjs",
                "windowSize": "1600x1200"
            }]
        },
        "mainwebsitetest": {
                "grep": "TEST2",
            "browsers": [{

                "browser": "phantomjs",
                "windowSize": "1600x1200"
            }]
        }
    }
```

**Comment by JamesDawsonX** [comment]
thank it works..

**Comment by yatki** [comment]
Is it possible to 5 test file at the same time (Basically open 5 browsers) ? I will have more than 100 tests files and all of them have to be executed. I'd like to run 5 or more test file in parallel to save time. Do we need to specify a grep definition for 100 files?

Thanks.

**Comment by EvtK** [comment]
yes I'm also wondering about this option. It seems I can only run parallel test when running them against multiple browsers. But if I only want to use chrome and I want to run all my tests in parallel, it doesn't seem to work. They are still executed in sequence.

**Comment by dominicfraser** [comment]
Splitting tests into 'chunks' has been enabled in v.1.2.0:

https://codecept.io/advanced/#parallel-execution
