### ISSUE TITLE
WebDriverIO helper option for window_size ignored

### ISSUE THREAD

**Issue by adrianblynch** [Codeception/CodeceptJS#71]
I have the following in my codecept.json file:

```
  "helpers": {
    "WebDriverIO": {
      "url": "url for site to test",
      "browser": "firefox",
      "window_size": "maximize"
    }
```

This running locally on a Mac (10.10.5) using both Chrome and Firefox.

The browser doesn't get maximised.

**Comment by fabioel** [comment]
As far as I know the `window_size` expects the dimensions (widht, height) (e.g. `'1600x800'`)

I would suggest that you write yourself a helper something like this:

```
module.exports = {
let I;
   _init() {
    I = this.helpers['WebDriverIO'].browser;
    I.windowHandleMaximize();
   }
}
```

which is a helper around [this](http://webdriver.io/api/protocol/windowHandleMaximize.html)

**Comment by MichalZalecki** [comment]
`"window_size": "maximize"` works unless you are on macOS. It works fine on Ubuntu.
