### ISSUE TITLE
 Cannot read property 'url' of undefined message error when you run two scenario in the same test

### ISSUE THREAD

**Issue by petrisorionel** [Codeception/CodeceptJS#713]
#### What are you trying to achieve?

I am trying to run two scenario, and my test steps are 

const assert = require('assert')

Feature('LoginPage');

Before((I) => {
    I.amOnPage('/avadmin/site/login');
});

Scenario('Login with a admin user', (I) => {
    I.fillField('LoginForm[username]', 'username');
    I.fillField('LoginForm[password]', 'password');
    I.click('login-button');
});

Scenario('Try to login with a incorect user', (I) => {
    I.fillField('LoginForm[username]', 'username');
    I.fillField('LoginForm[password]', 'password');
    I.click('login-button');
    I.seeElement({css: 'p.help-block.help-block-error'});
});

I define a testing.conf.js file with the following 

exports.config = {
    helpers: {
        Nightmare: {
            url: 'http://myurlsite:8080',
            show: false,
            restart: false,
        },
    },
};

#### What do you get instead?

There error I get is

 LoginPage: ./test.spec.js "before each" hook: Before for "Try to login with a incorect user":
     Cannot read property 'url' of undefined
  
  Scenario Steps:
  
  - I.amOnPage("/avadmin/site/login") at Context.Before (tests/test.spec.js:6:7)
  
  TypeError: Cannot read property 'url' of undefined
      at browser.goto.then (/usr/local/lib/node_modules/codeceptjs/lib/helper/Nightmare.js:321:35)
      at process._tickCallback (internal/process/next_tick.js:109:7)

### Details

* CodeceptJS version: 1.0.2
* NodeJS Version:
* Operating System: MAC OS
* Protractor || WebDriverIO || Nightmare version (if related): Nightmare - 2.10.0

**Comment by APshenkin** [comment]
@petrisorionel So I think this problem is the same as described here: https://github.com/Codeception/CodeceptJS/issues/528
There is an issue in Nightmare: when you try to navigate to the same page on which you are now, Nightmare throw this exception. For workaround you can use this I.amOnPage('about:blank')
