### ISSUE TITLE
[Question] How can I setup up debug for codeceptjs scenarios in VSCode\Webstorm?

### ISSUE THREAD

**Issue by BorisOsipov** [Codeception/CodeceptJS#715]
I want to be able to debug tests. Are there any article or notes how i can do it?

**Comment by APshenkin** [comment]
@BorisOsipov http://codecept.io/advanced/#debug Here are notes for Webstorm

**Comment by APshenkin** [comment]
also there is PR that I will finish some day https://github.com/Codeception/CodeceptJS/pull/681

**Comment by BorisOsipov** [comment]
@APshenkin thank you!
