### ISSUE TITLE
Some problem with execution before hook code

### ISSUE THREAD

**Issue by BorisOsipov** [Codeception/CodeceptJS#716]
#### What are you trying to achieve?
I try to use before method to setup fixture.
#### What do you get instead?
I run into some issue. Part of before method code doesnt' execute.
I prepare minimal project to reproduce the issue https://github.com/BorisOsipov/codeceptjs_issue
**Issue:** All code after `await mainPage.getSmth();` in before method won't be executed.

> Minimal code to reproduce issue:
```js
Feature("Example");

Before(async (I, mainPage) => {
  I.amOnPage("https://github.com/");
  I.say("bla-bla1");
  await mainPage.getSmth();
  I.click({ css: ".jumbotron-link" });
  I.say("bla-bla2");
});

Scenario("test something", async (I, mainPage) => {
  I.see("Sign up for GitHub", { css: ".btn-orange" });
});
```

> Provide console output if related. Use `--verbose` mode for more details.
https://github.com/BorisOsipov/codeceptjs_issue/blob/master/log.log

### Details
* NodeJS Version: v7.9.0
* Operating System: Linux
* WebDriverIO 
* Configuration file: 
https://github.com/BorisOsipov/codeceptjs_issue/blob/master/codecept.json

**Comment by APshenkin** [comment]
@BorisOsipov there is an issue with async/await. It doesn't support yet https://github.com/Codeception/CodeceptJS/issues/670 .
Use generators. They are supported in 1.0.2

**Comment by BorisOsipov** [comment]
@APshenkin thank you for you help.
