### ISSUE TITLE
Allow outputting --steps as well as generating --reporter output file when running tests

### ISSUE THREAD

**Issue by lougreenwood** [Codeception/CodeceptJS#724]
When running acceptance tests, I would like to use a command which looks like this:

`./codeceptjs run --steps --reporter mocha-junit-reporter`

This would show the --steps output on the command line so that I can monitor progress on my Ci server realtime logs, but would also save the mocha-unit reports for the CI to display test run stats for that build job.

It seems at the moment, if --reporter is used, --steps is ignored.

As a side note - I'm also using the Codeception (PHP) sister-project and this works as I expect over there, so it would be nice to get consistency in this behaviour.

Thanks!

**Comment by APshenkin** [comment]
@lougreenwood Please see https://github.com/Codeception/CodeceptJS/issues/698, hope it helps

**Comment by APshenkin** [comment]
Close due inactivity
