### ISSUE TITLE
Approach to test file upload via either drag and drop or using browser file dialog [QUESTION]

### ISSUE THREAD

**Issue by LaurieSReynolds** [Codeception/CodeceptJS#725]
#### What are you trying to achieve?
This is a question.  Codeceptjs seems to be working fine.

We are using the react-dropzone component - https://github.com/felixrieseberg/React-Dropzone-Component to upload files.   We want to cover file upload workflow using codeceptjs.   

Can file upload be tested using acceptance test frameworks?   If so, what controls have people used with codeceptjs.   Should I be dropping down to use webdriverio methods?

#### What do you get instead?
unknown error: cannot focus element

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
I attach file "div.filepicker.dropzone.dz-clickable", "testdata/choice-input-psg_second.csv"
 > Uploading testdata/choice-input-psg_second.csv
   [1] Error | Error: unknown error: cannot focus element
   Emitted | step.failed (I attach file "div.filepicker.dropzone.dz-clickable", "testdata/choice-input-psg_second.csv")
   Step finished in 0.25 sec
   [1] Error | Error: unknown error: cannot focus element
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook WebDriverIO._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 1.0.3
* NodeJS Version: 8.4.0
* Operating System: macOS Sierra - 10.12.6
* Protractor || WebDriverIO || Nightmare version (if related) - 4.8.0
* Configuration file:

```js
# paste suite config here
{
  "tests": "tests/**/*.acceptance.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "https://localhost:3000",
      "browser": "chrome"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "acceptanceTests"
}
```

**Comment by APshenkin** [comment]
@LaurieSReynolds You should choose input locator for attach method.
Here is a quick example with react-dropzone component on demo page:
```
Scenario('simple test', (I) => {
    I.amOnPage('http://reactdropzone.azurewebsites.net/example/')
    I.attachFile('//input', '.gitignore')
    pause() // <- Here you will see that file was attached
});
```
Hope it helps!

**Comment by APshenkin** [comment]
Close due inactivity
