### ISSUE TITLE
[Enhancement]: Create and Maintain an XML file of Tests with their latest status ran.

### ISSUE THREAD

**Issue by ClarkKent2017** [Codeception/CodeceptJS#731]
It would be really cool to have codecept.io store a log of all of the tests in an XML file, and update each test reference in the XML when it was ran along with its status so that anyone can build a UI application over it so people can visualize their test results.

**Comment by DavertMik** [comment]
This won't be a core feature of CodeceptJS but you can implement it by yourself. 
We have flexible API which you can use to extend the functionality. See here http://codecept.io/hooks/#custom-hooks
