### ISSUE TITLE
Example of seeAttributesOnElements

### ISSUE THREAD

**Issue by VladToporkov** [Codeception/CodeceptJS#735]
#### What are you trying to achieve?
I want to check some classes from element. 

#### What do you get instead?

I try to  use seeAttributesOnElements, but it recieve a mistake :  Not all elements (div[data-tab-name="auth"]) have attributes ".auth__tab_state_active"

```bash
# paste output here
```

> Provide test source code if related

I.seeAttributesOnElements('div[data-tab-name="auth"]','.auth__tab_state_active');
 
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by APshenkin** [comment]
`seeAttributesOnElements` check that all elements have exactly described property.
Syntax should be: `I.seeAttributesOnElements('div[data-tab-name="auth"]',{class: 'auth__tab_state_active'});`

But if you want to check that there is an element with `auth__tab_state_active` in classes you can do it with Xpath:
I.waitForVisible('//div[@data-tab-name = 'auth' and contains(@class, 'auth__tab_state_active')]')

**Comment by VladToporkov** [comment]
Thx)
