### ISSUE TITLE
I.attachfile function not working after implementing SmartWait in codecept.json

### ISSUE THREAD

**Issue by rahuljain840** [Codeception/CodeceptJS#736]
#### What are you trying to achieve?
I implemented SmartWait in my codecept.json file like below.
I applied SmartWait in my Codecept.json like below , but the issue is that after implementing it I.attachfile function [I.attachFile("input.dz-hidden-input","TestForms.xsn");] is not working.

"WebDriverIO": {
"url": "https://formsviewertest.azurewebsites.net",
"browser": "chrome",
"windowSize":"maximize",
"restart": "true",
"smartWait": 90000,
"timeouts": {
"script": 90000,
"page load": 90000,
"implicit": 90000,
"explicit": 90000
}
},
#### What do you get instead?
After this I.attachfile [I.attachFile("input.dz-hidden-input","TestForms.xsn");] is not working.
> Provide console output if related. Use `--verbose` mode for more details.
ESOCKETTIMEDOUT
Scenario Steps:

I.attachFile("input.dz-hidden-input", "#44689-Version Test.xsn") at Test. (testplan\fv_versionTest_test.js:13:7)
```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by APshenkin** [comment]
duplicate https://github.com/Codeception/CodeceptJS/issues/734
