### ISSUE TITLE
Support for Checking Javascript errors in test console

### ISSUE THREAD

**Issue by nickplatt** [Codeception/CodeceptJS#737]
I want to be able to check for Javascript errors in the browser console while running my test suite.

I've had a look online and found Webdriver support of this kind of thing but currently am not sure if this is configurable with codeceptjs?

**Comment by DavertMik** [comment]
No, we don't have this feature. But it looks really good so it should be added

**Comment by BLouzada** [comment]
There is any workaround to failt tests if occour any console error? i tried Hook Usage Examples
1) Failing if JS error occur in WebDriverIO, but cant get this work.

**Comment by BLouzada** [comment]
I got this working using yield I.grabBrowserLogs(); filtering JS logs and asserting for empty array, if anyone got a better solution please share.

**Comment by nickplatt** [comment]
I'll give that a shot for now @BLouzada, thanks for sharing :)

**Comment by ninpop25** [comment]
@BLouzada : could you please share your code on how to Check the JavaScript Console Info for particular text and verify it

**Comment by BLouzada** [comment]
I'm using webdriverIO, and node 6.9.3
```
Feature('My Feature');
var assert = require('assert');
function isJavascript(log) {
    return log.source == 'javascript';
}
Scenario('test Name', function* (I) {
    const logs = yield I.grabBrowserLogs();
    const jsLogs = logs.filter(isJavascript);
    assert.equal(JSON.stringify(jsLogs), '[]')
}
```

**Comment by reubenmiller** [comment]
`I.grabBrowserLogs` is also supported in the Puppeteer helper. I believe it has a slightly nicer format than the webdriverio format but check out the puppeteer docs for the extact format.
