### ISSUE TITLE
Error passed value to yield inside a generator function.

### ISSUE THREAD

**Issue by petrisorionel** [Codeception/CodeceptJS#739]
I want to make a connection to database, take the token and passed to yield inside a generator function

seeTokenInDB() {
        const sql = '//some sql here';
        console.log(sql)
        this.connection.query(sql, function (err, result) {
          if (err) throw err;
          console.log("TOKEN: " + result[0].row);
          return result[0].row;
        });
      }

####---------------------------------------------

Scenario('Scenario name', function*(I) {
    var token = yield I.seeTokenInDB();
    console.log(token);
    I.amOnPage('......token=' + token)
});

### Details

* CodeceptJS / Nightmare version:  "codeceptjs-nightmare": "^1.1.0",
* NodeJS Version: v8.5.0
* Operating System: MAC OS

**Comment by APshenkin** [comment]
@petrisorionel 
And.. What is the problem? Can you please update description of this issue?

**Comment by oztek22** [comment]
I am getting syntax error if I try to use yield

```
let numTodos = yield I.grabTextFrom('.uc-fab-timer');
```

Error:

```
SyntaxError:
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```
