### ISSUE TITLE
selectOption terminates entire test without error response.

### ISSUE THREAD

**Issue by Jtech42** [Codeception/CodeceptJS#742]
#### What are you trying to achieve?

Selecting an option from a dropdown menu.

#### What do you get instead?

Test stops executing at I.selectOption(), returns no errors with verbose on, returns no reports when using mochawesome.

> Provide console output if related. Use `--verbose` mode for more details.

$ codeceptjs run --steps --verbose --grep @registerform --reporter mochawesome

  New Registration Form
    1) Test New Registration Form @registerform
✨  Done in 33.00s.

> Provide test source code if related

newFormOption(option){
 I.selectOption({css: 'select[class=fd-create-select]'}, option);
 I.jsClick(this.createButton);
},

### Details

* CodeceptJS version: codeceptjs -v, or codeceptjs version, or ver, all fail?
* NodeJS Version: v6.11.3
* Operating System: OSX

**Comment by APshenkin** [comment]
@Jtech42 
Please provide more information. What helper do you use? What version of codeceptJS do you use (you can check the version in terminal when tests are launched)

**Comment by reubenmiller** [comment]
Closed due to lack of information. If this issue is still relevant than please reopen and provide the requested information.
