### ISSUE TITLE
I.click() fails on elements out of view

### ISSUE THREAD

**Issue by Simeon-off** [Codeception/CodeceptJS#745]
#### What are you trying to achieve?
I am trying to click an element that it out of view (scrolling is needed to see the element).
With 0.6.3 , it was working like that - it was scrolling automatically when needed.

#### What do you get instead?
unknown error: Element is not clickable at point (a,b)

### Details

* CodeceptJS version: 1.0.3
* NodeJS Version: 6.11.0
* Operating System: Win10x64 
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:
```
{
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "chrome",
      "windowSize": "",
      "timeouts": {
        "script": 60000,
        "page load": 10000,
        "implicit": 50
      }
    },
    "User": {
      "require": "./user_helper.js"
    }
  },
  "include": {
    "I": "./steps_file.js",
    "Activities": "./pages/Activities.js"
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "tests": "./*_test.js",
  "timeout": 10000,
  "name": "Codeceptjs Tests"
}
```

Do I have to scroll now every time to click an element out of view?

**Comment by sivnz** [comment]
+1 - Im having the same problem here.

@Simeon-off Did you try the same on firefox?
My firefox is working correctly but the problem happens with chrome.

**Comment by APshenkin** [comment]
@Simeon-off Are you sure that issue is related with codecept, not with webdriver?

Can you please try to downgrade codeceptjs and check on previous version? Thanks

**Comment by Simeon-off** [comment]
1. How can I downgrade codeceptjs?

2. I fail to start the tests in firefox 
A browser instance is not opened and the returned error is: 
```
"before each" hook: codeceptjs.before for "progress" in 22075ms
Error: Connection refused: connect
```

In the json file above, I have changed only: "browser": "firefox"
selenium standalone server is v.3.4.0.
Geckdriver was installed with "npm install -g geckdriver" in:
%\AppData\Roaming\npm\node_modules\geckodriver\geckodriver.exe 
(also added as a Path System variable)
(geckodriver 0.19.1, Listening on 127.0.0.1:4444)

**Comment by joostmeijles** [comment]
+1 same issue here. What's the resolution?

**Comment by APshenkin** [comment]
> How can I downgrade codeceptjs?
Just run npm i codeceptjs@[your version]
>I fail to start the tests in firefox
A browser instance is not opened and the returned error is:

I recommend to use selenium-standalone package to run selenium https://www.npmjs.com/package/selenium-standalone

Tested with latest version of codeceptjs. It works with firefox

**Comment by reubenmiller** [comment]
Closing ticket due to inactivity. Before reopening please try using the latest version which is v1.1.5 (at the time of writing), and check if the issue still exists.

**Comment by imdedios** [comment]
I am having problems with Chrome, I did try with Firefox and is working correctly
