### ISSUE TITLE
[Enhancement] Common Library Support for Security Compliance

### ISSUE THREAD

**Issue by jmb-mage** [Codeception/CodeceptJS#749]
#### What are you trying to achieve?

There are certain types of tests that are performed on every web site for basic security compliance.  

- Form Fields: Visible and Hidden
-- Escape codes
-- SQL Injections
-- Non-ascii, Unicode vs UTF-8
- URLs
-- Query String Manipulations

Several guides to this [here](https://sqa.stackexchange.com/questions/9441/what-are-some-invalid-data-inputs-that-will-break-a-text-box)

Most testers have spent time seeing what happens if they enter things `“><script>alert(1)</script>` into an text box, or HTML escape codes, SQL injections, etc.  There are several lists of things to test, and since these are tested in an across-the-board, site generic manner I am wondering:

**Is there is a common library created by CodeceptJS to test for Security Compliance?**

**Comment by DavertMik** [comment]
I don't think that's goal of this project. 
CodeceptJS executes reproducable test scenarios and doesn't check for security vulnarabilities.
As a test automation engineer you can implement different checks for SQL, JS injections, etc. But we don't provide you any guides as it is not related to a tool. It's about your testing process
