### ISSUE TITLE
After creating page object, tests no longer run

### ISSUE THREAD

**Issue by rizmudano** [Codeception/CodeceptJS#753]
#### What are you trying to achieve?
Generate page objects through `codeceptjs gpo` and still be able to run my existing tests.

#### What do you get instead?
Before running `codeceptjs gpo` for the first time:
When I run `codeceptjs run`, my tests run as expected.

After running `codeceptjs gpo` for the first time:
When I run `codeceptjs run`, my test run fails immediately with the following.

#### Console output

NB: for some odd reason, after generating the page object, it looks in '../test_automation/test_automation/' (which doesn't exit) for `steps_file.js`, even though the `steps_file.js` path should be: `'../test_automation/steps_file.js'
```bash
$ "/home/rizwan/myRepo/node_modules/.bin/codeceptjs" "run" "priorityBoard_test.js" "--verbose"

Initialization failed for [object Object]
Cannot find module '../test_automation/test_automation/steps_file.js'

Error: 
    at createSupportObjects (/home/rizwan/myRepo/node_modules/codeceptjs/lib/container.js:154:13)
    at Function.create (/home/rizwan/myRepo/node_modules/codeceptjs/lib/container.js:30:25)
    at Codecept.init (/home/rizwan/myRepo/node_modules/codeceptjs/lib/codecept.js:54:15)
    at Command.module.exports (/home/rizwan/myRepo/node_modules/codeceptjs/lib/command/run.js:35:14)
    at Command.listener (/home/rizwan/myRepo/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:194:7)
    at Command.parseArgs (/home/rizwan/myRepo/node_modules/commander/index.js:635:12)
    at Command.parse (/home/rizwan/myRepo/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/home/rizwan/myRepo/node_modules/codeceptjs/bin/codecept.js:107:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Details

* CodeceptJS version: v1.0.2
* NodeJS Version: v7.10.1
* Operating System: Ubuntu 16.04
* Protractor
* Configuration file:

```js
{
  "output": "./test_automation/output",
  "helpers": {
    "Protractor": {
      "url": "http://localhost:8081",
      "driver": "hosted",
      "browser": "chrome",
      "rootElement": "html",
      "smartWait": 5000
    }
  },
  "include": {
    "I": "./test_automation/steps_file.js",
    "priorityBoardPage": "./test_automation/pages/priorityBoard.js"
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [
    "./hooks/before.js"
  ],
  "tests": "./test_automation/*_test.js",
  "timeout": 10000,
  "name": "myRepo"
}
```
As soon as I remove the line added by the `gpo` command (i.e. `,
    "priorityBoardPage": "./test_automation/pages/priorityBoard.js"`) then my tests run fine.

**Comment by DavertMik** [comment]
so straaange... 
could you look into the loader? https://github.com/Codeception/CodeceptJS/blob/master/lib/container.js#L135
maybe you could debug using console.log to understand why it adds extra path

**Comment by rizmudano** [comment]
So it seems that the issue was being caused by an incorrect relative path to `steps_file.js` that was generated by default within the new page object file `priorityBoard.js`:
```js
  _init() {
    I = require('../test_automation/steps_file.js')();
  }
```
Solution: By changing the reference of `steps_file.js` to the correct location of `steps_file.js` (i.e. relative to `myRepo/test_automation/pages/priorityBoard.js`, and not `myRepo/pages/priorityBoard.js`), the tests were able to run again:

```js
  _init() {
    I = require('../steps_file.js')();
  }
```

The issue was caused by the auto-generated reference to `steps_file.js` within the new page object file `priorityBoard.js` which doesn't get generated correctly if you've placed your page objects in somewhere other than the home folder of your repo.
