### ISSUE TITLE
Screen recording of Xvfb with ffmpeg?

### ISSUE THREAD

**Issue by nickplatt** [Codeception/CodeceptJS#754]
Does codecept support screen recording of their headless test suite with any third party libraries? Or has anyone come up with a hack solution if not? 

The captured screenshot on fail feature is great but not useful in all scenarios, I'd quite like to set up a ffmpeg/ avconv recording on my Xvfb instance that saves the video on test fail. So far I haven't had too much luck getting anything but being able to run ffmpeg once and it never getting round to actually running the tests.

**Comment by DavertMik** [comment]
It's not the purpose of this framework. I recommend you to look into https://github.com/elgalu/docker-selenium project. It works perfectly with CodeceptJS
