### ISSUE TITLE
Retrieve vales, compare & select the smallest value

### ISSUE THREAD

**Issue by nverma0306** [Codeception/CodeceptJS#759]
How i would pick different values on a website and compare them and click on the corresponding button which has the lowest value
For Eg: On a travel website, I want to book a flight and I wish to pick different flight rates from page and compare them & click on Select corresponding the cheapest flight?

**Comment by DavertMik** [comment]
You should use `grab*` methods to retrieve values, then compare them using JavaScript and proceed with a test:

```js
let val1 = I.grabValueFrom('.el1');
let val2 = I.grabValueFrom('.el2');
let val3 = I.grabValueFrom('.el3');
let max = Math.max(val1, val2 val3)
```

**Comment by nverma0306** [comment]
Thanks, it helped
