### ISSUE TITLE
Loops with codecept

### ISSUE THREAD

**Issue by nverma0306** [Codeception/CodeceptJS#761]
How do i implement loops with codecept? If i need to open one url and if the url fails, I wish to open another url or If it fails once I want to break and mark the test fail.

**Comment by APshenkin** [comment]
@nverma0306 
What does it mean "and if the url fails"
If you have any condition (based on page state) you can try to grab this value and paste it in `if`

**Comment by reubenmiller** [comment]
You can implement this logic in a custom helper function. See this [gist](https://gist.github.com/reubenmiller/62f27ee3ed6ab8b9a4eab7c13dc2e08c) for an example.

Though you'll have to add a `for of` loop and use try/catch statements to catch an exceptions when the url fails. Note, you can't use async/await statements in a `Array.forEach` statement.

```js
async trySomeUrls() {
  const assert = require('assert');
  const urls = ['https://test1.com', 'https://test2.com'];
  const helper = this.helpers['Puppeteer'];
  let urlOk = false;
  
  for (const url of urls) {
    try {
      if (!urlOk) {
        await helper.page.goto(url);
        urlOk = true;
      }
    } catch (err) {
        // ignore error.
    }
  }
  assert.ok(urlOk);
}
```
