### ISSUE TITLE
[Enhancement] BeforeFeature and AfterFeature

### ISSUE THREAD

**Issue by thiagodp** [Codeception/CodeceptJS#762]
AFAIK, currently there are these methods for setup/teardown:
- `BeforeSuite`: before all the tests start running;
- `AfterSuite`: after all the tests finish running;
- `Before`: before each scenario of the current feature start running;
- `After`: after each scenario of the current feature start running;

However, in order to run end-to-end tests, sometimes there is a need to setup things per feature. So these setup/teardown methods are welcome:
- `BeforeFeature`: before all the scenarios of the current feature start running;
- `AfterFeature`: after all the scenarios of the current feature finish running.

**Comment by DavertMik** [comment]
I think BeforeSuite does exactly just that. Isn't it? @APshenkin

**Comment by thiagodp** [comment]
So, actually, `BeforeSuite` **is** `BeforeFeature` and `AfterSuite` **is** `AfterFeature`. I think I have confused them because of their names. In this case, there aren't events to setup/teardown things before and after all the tests (which I had thought it was `BeforeSuite` and `AfterSuite`)? Something like a `BeforeAll` and a `AfterAll`. Are there any ways to do this?

**Comment by jploskonka** [comment]
You can use `bootstrap` and `teardown` hooks to do that: http://codecept.io/hooks/#bootstrap-teardown

**Comment by thiagodp** [comment]
Great! Thank you.

@DavertMik, I would like to suggest the inclusion of a paragraph about the aforementioned hooks in the section [Basics](http://codecept.io/basics/), which points to [them](http://codecept.io/hooks/#bootstrap-teardown).
