### ISSUE TITLE
Suggestion to add passed event for helpers

### ISSUE THREAD

**Issue by Super-Eric** [Codeception/CodeceptJS#764]
#### What are you trying to achieve?
I just notice that we have got _failed() which can be written into the customized helpers. So I wonder if we can get also _passed() for this one?

#### What do you get instead?
I have added the code to the helper.js in /lib/listener manually:
```
event.dispatcher.on(event.test.passed, function () {
    runAsyncHelpersHook('_passed');
  });
```
And in my customized helpers it is like this to set sauce labs test as passed:
```
  _passed(){
	this.helpers['WebDriverIO'].browser.execute("sauce:job-result=passed");
  };
```

I this would be helpful if you can add this part to it (If I don't have this mistake in my code). Thanks. 

This should not be a issue, may be considered as an enhancement ;-)

**Comment by reubenmiller** [comment]
Fixed in v1.1.6 which was release today.

Custom helpers can now use the `_passed(){}` hook.
