### ISSUE TITLE
multiple execution 

### ISSUE THREAD

**Issue by piomic** [Codeception/CodeceptJS#765]
I'm trying to use multiple execution for chrome and firefox. For some reasons, test which is executed in firefox fails 

> Clickable element span=Select type was not found by text|CSS|XPath

 but for chrome passes. When I execute the test separately, it passes for both, firefox and chrome. Have you got any idea what could be the cause?

### Details

* CodeceptJS version: 1.0.3
* NodeJS Version: 5.5.1
* Operating System: macOS Sierra 10.12.6
* WebDriverIO 4.8.0
* Configuration file: 
{
  "tests": "./e2e/codecept/*.js",
  "output": "./e2e/codecept/output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost:4300/",
      "browser": ["chrome", "firefox"]
    }
  },
  "include": {
    "I": "./e2e/codecept/steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "testcafe",

  "multiple":{
    "basic":{
      "browsers":["chrome", "firefox"]
    }
  }

}

**Comment by APshenkin** [comment]
@piomic Looks like your test is "flacky" maybe you have to add something like this `I.waitForVisible('span=Select')` before clicking?

**Comment by reubenmiller** [comment]
Closed due to inactivity.
