### ISSUE TITLE
How to sendkey about path file on Upload Dialog

### ISSUE THREAD

**Issue by anhvuong123** [Codeception/CodeceptJS#769]
I'm facing a control upload file. For manual, just click on to open Upload Dialog to select file / Drag file into it.
I've tried with codeceptjs but it has no file uploaded after run code successfully (May be a un-standard control). 
So I focus to the other way clicking on the control to open a Upload Dialog Windows. Then send path file by key press into the Dialog Upload.

Could you have any suggestion about the code executing by Codeceptjs or If it have any way better, please let me know.

Many thanks,

**Comment by APshenkin** [comment]
@anhvuong123 There is no ability to send keys to Upload Dialog. It's webdriver limitation. You have to try to upload file via `attachFile` method

**Comment by anhvuong123** [comment]
Thank @APshenkin, I'll try other way for this context.
