### ISSUE TITLE
Issue with waitForText method

### ISSUE THREAD

**Issue by leftty** [Codeception/CodeceptJS#774]
#### What are you trying to achieve?
I am trying to wait until I see some text
#### What do you get instead?
It says that the element in which I search for the text either is not in the DOM or does not contain de specified text.
> Provide console output if related. Use `--verbose` mode for more details.

```bash
 • I wait for visible "button.js-add-new", 5
   Emitted | step.passed (I wait for visible "button.js-add-new", 5)
   Step finished in 1.191 sec
   Emitted | step.start (I wait for text "+ Add new", 15, "button.js-add-new")
 • I wait for text "+ Add new", 15, "button.js-add-new"
   [1] Error | Error: element (button.js-add-new) is not in DOM or there is no element(button.js-add-new) with text "+ Add new" after 15 sec
   Emitted | step.failed (I wait for text "+ Add new", 15, "button.js-add-new")
   Step finished in 15.005 sec
   [1] Error | Error: element (button.js-add-new) is not in DOM or there is no element(button.js-add-new) with text "+ Add new" after 15 sec
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook Util._failed()
   [1] <teardown> Queued | hook WebDriverIO._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
   [1] <teardown> Starting <generator> session
```

> Provide test source code if related
```js
I.waitForVisible('button.js-add-new', 5);
I.waitForText('+ Add new', 15, 'button.js-add-new');
```
The element exists in the dom since the first step does not fail, but also the text is definitely in the element because I can see it with my own eyes.

### Details

* CodeceptJS version: CodeceptJS v1.0.1
* NodeJS Version: v9.0.0
* Operating System: macOS Sierra
* WebDriverIO: 4.9.6
* Configuration file:
```js
config.helpers.WebDriverIO = {
        url: .....,
        browser: process.profile,
        restart: true,
        windowSize: "maximize",
        timeouts: {
            script: 60000,
            "page load": 6000,
            implicit: 300
        }
    }

```
As a side note, the app I am testing is NOT a single page app.

**Comment by lougreenwood** [comment]
Just a hint, but I sometimes find that either scrolling the page or taking a screenshot in the test, but before one of these troublesome/weird quirks allows the test to work... :)

**Comment by APshenkin** [comment]
@leftty 
Try to grab the value of text using codeceptjs and check with text that you pass to `waitForText`
```
I.waitForVisible('button.js-add-new', 5);
let text = yield I.grabTextFrom('button.js-add-new');
console.log(text)
I.waitForText('+ Add new', 15, 'button.js-add-new');
```

**Comment by leftty** [comment]
Thank you for suggestion, but why do I have to grab the text and store that value in a variable, if afterwards you say to use, when calling the ```jswaitForText()``` method, the hard-coded text instead of the value stored in the variable? Maybe I am understanding this wrong in some way.

**Comment by leftty** [comment]
It seems that the text returned by grabText() method is '+ ADD NEW' and not '+ Add New' like it shows when I am looking at the html via the chrome inspector. Do you know why grabText() return a different text than that showing in the html page source?

**Comment by APshenkin** [comment]
@leftty 
My suggestion was to understand, what text is on element. Looks like selenium get text in uppercase in this case. I can't tell you why. It's related with your application and selenium.
Maybe there is CSS option `text-transform: uppercase;` on element and because of this text on page appears in uppercase, but in html code you see lowercase text.

So in this case i can only suggest to validate text with uppercase:
```
I.waitForVisible('button.js-add-new', 5);
I.waitForText('+ ADD NEW', 15, 'button.js-add-new');
```

Hope this helps

**Comment by leftty** [comment]
@APshenkin You were right about the text in uppercase. I will close this ticket now.
