### ISSUE TITLE
REST helper is transforming payload objects

### ISSUE THREAD

**Issue by AlanAditazz** [Codeception/CodeceptJS#779]
#### What are you trying to achieve?

Whenever we use **sendPostRequest**, **sendPutRequest** or **sendPatchRequest**, the request object is converting the payload objects from JSON to a type of URL query string, rendering our request invalid

#### We mitigated it by temporarily using JSON.stringify but should not be a general solution at all

**1) This is our request body as it is sent to the methods mentioned above** _(This is a console output within the helper methods)_:

```bash
PAYLOAD AS IT IS SENT:
{
    "name": "Albert",
    "code_key": "Test_UserOne",
    "model_url": "http://www.users.com/one.html",
    "tags": [
        "COURSE:25-30 69",
        "CLASS:Test_Class"
    ]
}
```
**2) This is the request object right before _generator function "executeRequest"_** _(This is a console output within the helper methods)_:
```bash
REQUEST OBJECT BEFORE PROMISE WITHOUT STRINGIFYING THE PAYLOAD:
{
    "_stream": false,
    "_multipart": [],
    "_form": [],
    "options": {
        "url": "http://users-api.net/users",
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
            "X-AZ-USER-TOKEN": "Bearer eyJhbGciOiJIUzUxMiJ9"
        },
        "body": "name=ALBERT&code_key=Test_UserOne&model_url=http%3A%2F%2Fwww.users.com%2Fone.html&tags=COURSE%3A25-30%2069&tags=CLASS%3ATest_Class",
        "auth": {
            "user": "user",
            "pass": "pass",
            "sendImmediately": true
        },
        "timeout": 30000
    },
    "as": {}
}
```
**3) This is the same request object right before _generator function "executeRequest"_ when we replace _.send(payload)_ for _.send(JSON.stringify(payload))_** _(This is a console output within the helper methods)_:
```bash
REQUEST OBJECT BEFORE PROMISE WITH SEND(JSON.STRINGIFY(PAYLOAD):
{
    "_stream": false,
    "_multipart": [],
    "_form": [],
    "options": {
       "url": "http://users-api.net/users",
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
            "X-AZ-USER-TOKEN": "Bearer eyJhbGciOiJIUzUxMiJ9"
        },
        "body": "{\"name\":\"Albert\",\"code_key\":\"Test_UserOne\",\"model_url\":\"http://www.users.com/one.html\",\"tags\":[\"COURSE:25-30 69\",\"CLASS:Test_Class\"]}",
        "auth": {
            "user": "user",
            "pass": "pass",
            "sendImmediately": true
        },
        "timeout": 30000
    },
    "as": {}
}
```

### Details

* CodeceptJS version: v1.0.3
* NodeJS Version: v7.6.0
* Operating System: macOSX Sierra
* Unirest version: v0.5.1
* Configuration file:

```js
exports.config = {
    tests: "../Critical/*/*/*_test.js",
    output: "../Reports",
    helpers: {
        REST: {
            timeout: 30000,
            resetHeaders: false,
            endpoint: "http://users-api.net"  
        }
    },
    include: {
        Services: "../Components/services",
        Common: "../Components/commonFunctions",
        Comparison: "../Components/comparisons"
    },
    bootstrap: false,
    mocha: {
        reporterOptions: {
	        code: false,
            reportFilename: process.profile || "reportFile",
            reportDir: "../Reports"
        }
    },
    name: "UsersSuite"
}
```
## Is there a configuration that I'm missing and that's why REST helper is transforming our payloads?

**Comment by reubenmiller** [comment]
@AlanAditazz some changes have been done regarding the REST helper in the last few releases. Can you please test it again with ≥v1.1.5?

**Comment by Kalostrinho** [comment]
Hey @reubenmiller!
Actually this issue was prior [PR 917](https://github.com/Codeception/CodeceptJS/pull/917)...
**Tested it then and this can be closed!** 

Thanks! 👏
