### ISSUE TITLE
I.seeElement

### ISSUE THREAD

**Issue by fabioel** [Codeception/CodeceptJS#78]
I have a question regarding `I.seeElement`:
I find it quite strange that the `I.seeElement` method checks for the element in the DOM and not if the element is actually visible in the DOM, because the `I.see` method checks for the visiblity of the text and not its existance

Wouldn't it be better to implement the `I.seeElement` like this: [Webdriver isVisible](http://webdriver.io/api/state/isVisible.html)
And change the current `I.seeElement` to something like `I.locateElement`

**Comment by DavertMik** [comment]
> I find it quite strange that the I.seeElement method checks for the element in the DOM and not if the element is actually visible in the DOM,

You are right, it should check for visibility as well. At least this is how it works in Codeception, we have seeElementInDOM for DOM chekcing
