### ISSUE TITLE
chrome options to change file download location

### ISSUE THREAD

**Issue by parikshithkulkarni** [Codeception/CodeceptJS#781]
#### What are you trying to achieve?
How to change file download location to a local custom location using SeleniumWebdriver helper while using chrome browser

"helpers": {
    "SeleniumWebdriver": {
      "url": "",
      "browser": "chrome",
      "waitForTimeout":3000,
      "scriptTimeout":3000,
      "uniqueScreenshotNames": false,
      "windowSize": "maximize",
      "smartWait": 5000,
      "desiredCapabilities": {
        "browserName": "chrome",
        "chromeOptions": {
          "prefs": {
            "args": "['start-maximized']",
            "profile.default_content_settings.popups": "0",
            "download.default_directory": "./automationtests/helpers"
          }
        }
      }
    },

### Details

* CodeceptJS version: latest
* NodeJS Version: v8.4.0
* Operating System: Mac high sierra
* Protractor || WebDriverIO || Nightmare version (if related): SeleniumWebdriver
* Configuration file:
``

**Comment by zbcui** [comment]
Any one can helps with same issue with firefox ? how to set related profile with firefox for download dir ?
