### ISSUE TITLE
How to clear local storage for chrome browser

### ISSUE THREAD

**Issue by VladToporkov** [Codeception/CodeceptJS#788]
#### What are you trying to achieve?
I want to clear artefacts after each test which placed in local storage.

#### What do you get instead?
I can't find method for this. And I see this problem only when I use data factory because browser didn't restat after each test. 
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by jploskonka** [comment]
You can execute browser script to do that, with WebDriverIO it would be something like:

``` javascript
I.executeScript(function() {
  localStorage.clear();
});
```
I would suggest keeping it in some helper, something like:
