### ISSUE TITLE
Codecept process exits with 0 despite tests are failing

### ISSUE THREAD

**Issue by devicodev** [Codeception/CodeceptJS#794]
#### What are you trying to achieve? 
I am trying to get proper status of tests in my CI job.

#### What do you get instead?
I always get 0 exit status and CI marks test run as 'passed'. 

It appears that codecept process always return 0 status with teardown hook enabled. And it returns correct status without teardown.
```
$ node_modules/codeceptjs/bin/codecept.js run --verbose
FAIL  | 0 passed, 1 failed   // 23s
$echo $?
0
```

This is part of my config which includes teardown hooks file.
```
    "bootstrap": false,
    "teardown": "./hooks.js",
    "hooks": [],
```

> This is what I have in my hooks.js file:
'use strict';
module.exports = {
    teardown: function (done) {
        console.log('Testing...');
    }
};

### Details
* CodeceptJS version: v1.0.3
* NodeJS Version: 7.8.0
* Operating System: Linux Ubuntu 17.04

**Comment by jploskonka** [comment]
If you're passing callback parameter to teardown function you need to call it sometime. Either change your teardown from `function(done)` to just `function()` or call passed callback when you're done with your hook.

**Comment by devicodev** [comment]
@jploskonka Your solution worked for me.
Thank you for your help.
