### ISSUE TITLE
vulnerability in mocha 3.x

### ISSUE THREAD

**Issue by caa1211** [Codeception/CodeceptJS#797]
#### What are you trying to achieve?

vulnerability in dependency of grow 1.9.2

### Details

* CodeceptJS version: 1.0.3
* NodeJS Version: v6.10.3
* Operating System: mac
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

Because the latest mocha in 3.x (v3.5.3) has vulnerability in dependency of grow 1.9.2
```
Mocha Vulnerability Issue:
https://github.com/mochajs/mocha/issues/2791

```

Do you have the plan to upgrade mocha to 4.x version or give some suggestions? thanks for your contributions.

**Comment by DavertMik** [comment]
Version 1.1 uses mocha ^4.0
