### ISSUE TITLE
session data exists after rerun tests

### ISSUE THREAD

**Issue by nhu** [Codeception/CodeceptJS#8]
Hi,

there must be an issue with terminating the data of the used session. If I run my tests once and rerun them, the second run has data of the first run. How can I disable this behavior or is it a bug?

I am using webdriverio helper with phantomjs.

**Comment by DavertMik** [comment]
Thanks. First real bug! I think cookies should be cleaned in `_after` hook of webdriver to ensure session is not saved.

**Comment by nhu** [comment]
Hi,

I am unsure if this is a bug in codeceptjs or in webdriverio. 
Because you even can't clear the session storage without getting errors. 

```
clearStorage(){
  return this.browser.sessionStorage('DELETE');
}
```

**Comment by DavertMik** [comment]
I will take a look and do what I can with it...

**Comment by nhu** [comment]
Maybe related: https://github.com/webdriverio/webdriverio/issues/409

**Comment by Teknologica** [comment]
I've stumbled on the same issue. Clearing `localStorage`, `sessionStorage` or cookies has no effect using `Phantom JS` with `Webdriver IO`. 
```js
class ClearUser extends Helper {
    clearAuthentication() {
        let client = this.helpers['WebDriverIO'].browser;
        return client
            .localStorage('DELETE')
            .sessionStorage('DELETE')
            .deleteCookie();
    }
}
```

**Comment by DavertMik** [comment]
Right now I can recommend not to use phantomjs... 
Anyway I will take a look when I have time

**Comment by Teknologica** [comment]
That's unfortunate, but there's cases where the tests can't run in a browser with a GUI so `phantom js` is required. I'll keep looking for a solution.

**Comment by Teknologica** [comment]
The issue of `Phantom Js` is related to `Ghost Driver`. See https://github.com/detro/ghostdriver/issues/170 -- it's been around since 2013.

**Comment by DavertMik** [comment]
I plan to implement [Nightmare](http://www.nightmarejs.org/) helper in one of next releases. 
I hope it will work better than PhantomJS

**Comment by umutm** [comment]
Any progress regarding Nightmare integration? And, is it still in the roadmap? Thanks.

**Comment by DavertMik** [comment]
Nightmare is implemented, webdriverio has its new versions so I think this can be closed
