### ISSUE TITLE
Codeception/Codeceptjs Docker Image can't be executed as part of a docker-compose setup

### ISSUE THREAD

**Issue by diegoluisrojas** [Codeception/CodeceptJS#814]
I'm using the base image provided by Codeception:  FROM codeception/codeceptjs

However I'm getting all the time:

`Cannot start service e2e-test: oci runtime error: container_linux.go:265: starting container process caused "exec: \"docker/entrypoint\": stat docker/entrypoint: no such file or directory"
ERROR: Job failed: exit status 1`

When the I'm trying to run the container with the tests. Everything works fine when running it without docker-compose though.

I think that the entrypoint does not have +x execution permissions granted.

Can you please take a look?

Thanks.

**Comment by jploskonka** [comment]
Could you please show your `Dockerfile` and `docker-compose` ones? Are you using your own docker-compose file or talking about one provided as part of codecept development environment?

**Comment by diegoluisrojas** [comment]
Below my Dockerfile

`FROM codeception/codeceptjs

COPY ./utils/wait-for-it.sh /tests/wait-for-it.sh
COPY ./utils/run.sh /tests/run.sh

WORKDIR /tests
ADD . /tests`

docker-compose is a custom one but just adds this one as part of the services to build and run.

**Comment by diegoluisrojas** [comment]
@jploskonka finally fixed it, there was a double mount process for the /tests
