### ISSUE TITLE
How can I setup different bootstrap/teardown for only a certain group of testcases ?

### ISSUE THREAD

**Issue by prashantsail** [Codeception/CodeceptJS#821]
#### What are you trying to achieve?
Configure CodeceptJS in a scenario where -
One group of test-cases need a specific bootstrap/teardown and
other group of test-cases need a different bootstrap/teardown

#### What do you get instead?
One common bootstrap/teardown for all my testcases.

### Details
* CodeceptJS version: 1.0..3
* NodeJS Version: 6.12.0
* Operating System: CentOS Linux release 7.4.1708 (Core)
* WebDriverIO 4.9.11

Could you please provide steps/guidelines for achieving this behaviour.

**Comment by DavertMik** [comment]
Did you try `Before()` and `After()` callbacks inside tests? http://codecept.io/basics/#before

**Comment by prashantsail** [comment]
Thanks for the guideline! This solves my problem.
