### ISSUE TITLE
Multiple Helpers interacting with one browser instance.

### ISSUE THREAD

**Issue by sivnz** [Codeception/CodeceptJS#823]
Hello Guys!

Is it possible to use 2 different helpers in the same configuration file?
Im trying to use WebDriverIO as my main helper and extending a new helper that uses Nightmare/Protractor.

**Comment by BrunoExterckotter** [comment]
+1

**Comment by DavertMik** [comment]
Currently nothing limits you from doing that. 
But it's not recommended approach. Helpers intersect with each other as they have the same methods.

If you have some tests in WebDriverIO, some in Nightmare - use different configuration files for them
