### ISSUE TITLE
following semver

### ISSUE THREAD

**Issue by kambing86** [Codeception/CodeceptJS#835]
v1.1.0 is no longer working in node < v8.9.1, should use v2.0.0 for major release with breaking changes instead

**Comment by DavertMik** [comment]
We had this discussion with a team but most of guys convinced me that's not a breaking feature. 
I had some doubts about it. And probably you are right version requirement should have been the part of it. Anyway we didn't break any internal API so it could have been considered as minor

**Comment by kambing86** [comment]
but this version actually breaking the system using node 6, which is still one of the Active LTS. anyway, if this is the decision, just forget it

**Comment by DavertMik** [comment]
If you run on Node 6 you just won't receive the upgrade I think. This should not break your current setup
