### ISSUE TITLE
--profile option is not recognized when using run-multiple

### ISSUE THREAD

**Issue by jamie-beck** [Codeception/CodeceptJS#839]
#### What are you trying to achieve?
Use the --profile options in combination with run-multiple.

#### What do you get instead?

> codeceptjs run-multiple supported --steps --profile live
```
  error: unknown option `--profile'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

### Details

* CodeceptJS version: 1.1.1
* NodeJS Version: v8.9.3
* Operating System: Windows 10

The all following work as expected with my setup:
> codeceptjs run --steps
(runs as expected)

> codeceptjs run --steps --profile live
(runs as expected)

> codeceptjs run-multiple supported --steps
(runs as expected)

**Comment by cherrieg** [comment]
Could you help fix the use " --profile " options in combination with run-multiple?
