### ISSUE TITLE
[WebdriverIO]After version 1.1.0 of codeceptjs, the api I.waitToHide() can not work well.

### ISSUE THREAD

**Issue by liuliran** [Codeception/CodeceptJS#842]
#### What are you trying to achieve?
The api I.waitToHide() can notwork well.
#### What do you get instead?
NA
> Provide console output if related. Use `--verbose` mode for more details.

```bash
  1) Admin Board
       Test2-18-4:Hide Service:
     element (Apple CUPS) still visible after 3 sec
  
  Scenario Steps:
  
  - I.waitToHide("Apple CUPS", 3) at Test.Scenario (tests/ln2/admin_test.js:70:5)
  - I.click("//*[@id="app"]/div/div[3]/div[2]/div/div[3]/div/div[3]/div[3]/a/div[2]/div[3]/button[1]") at Test.Scenario (tests/admin_test.js:67:5)
```

> Provide test source code if related

```js
Scenario('Test2-18-4:Hide Service', (I) => {
  I.click(el.admin.hide);
  I.waitToHide(el.appleTitle, 3);
  I.click(el.admin.hiddenList);
  I.waitForText(el.appleTitle, 3);
});
```

### Details

* CodeceptJS version:v1.1.0 or v1.1.1
* NodeJS Version:V9.3.0
* Operating System:Ubuntu 14.04 64bit
* Protractor || WebDriverIO || Nightmare version (if related)WebDriverIO
* Configuration file:NA

*Other info:
When I downgrade to codeceptjs v1.0.3,the api can work well.
So I think may the new version cause this error.

**Comment by reubenmiller** [comment]
@liuliran Sorry for the delay. Are you still having troubles with the `I.waitToHide()` function?

Is there a website that I can test against? (It doesn't have to be your, but some website where the behaviour is similar would be helpful).

**Comment by PeterNgTr** [comment]
Closed due to inactivity.
