### ISSUE TITLE
Is there a way to override a Step output?

### ISSUE THREAD

**Issue by javigomez** [Codeception/CodeceptJS#852]
#### What are you trying to achieve?
I have a test that looks like:

```javascript
I.amOnPage('http://localhost:8080/typeform')
I.loadForm('longForm.json')
await I.waitForElement('#submit-form', 30)
```

The loadForm method is a [custom step](http://codecept.io/pageobjects/#actor):

```javascript
module.exports = function() {
  return actor({

    // Define custom steps here, use 'this' to access default methods of I.
    loadForm(form) {
      this.executeScript(`window.livePreview.update(${JSON.stringify(form)})`)
    }
  });
}
```

But when I run the tests the output shows the full json in the console:

![screen shot 2018-01-02 at 18 51 39](https://user-images.githubusercontent.com/1375475/34493863-101a0fe0-efee-11e7-8454-3a782a3e8eb5.png)

I am not interested in see all this json, just something like 

`I load form longForm.json`

Is there a way to easily override the [toString method](https://github.com/Codeception/CodeceptJS/blob/80ad4d5493fb04a1d9604b77547777d8d94aa1ea/lib/step.js#L76) of a Step? 

### Details

* CodeceptJS version: v1.1.1
* NodeJS Version: 8.9.1

**Comment by DavertMik** [comment]
No, and yes :)

In your case, I'd recommend you to write a helper method which performs this action. 

Documentation is here: http://codecept.io/helpers/#webdriverio-example

```js
class MyHelper extends Helper {
    loadForm(form) {
      this.helpers['WebDriverIO'].executeScript(`window.livePreview.update(${JSON.stringify(form)})`)
    }
}
```

Include your helper into `config.json` and you are done!

```js
I.loadForm(formName); 
```
should work as expected!
