### ISSUE TITLE
Missing uncheckOption()

### ISSUE THREAD

**Issue by brunobg** [Codeception/CodeceptJS#853]
#### What are you trying to achieve?
Ensure that a checkbox input is not filled

#### What do you get instead?
Nothing, there is checkOption but not uncheckOption.

### Details
WebdriverIO, any version. Am I missing something? I can provide a PR with uncheckBox. Right now the only way to do it seems to be with a executeScript.

**Comment by DavertMik** [comment]
>  I can provide a PR with uncheckBox. Right now the only way to do it seems to be with a executeScript.

Yes, please send this PR
But I think the same effect can be achieved with `click`

**Comment by brunobg** [comment]
Clicking would not ensure the final state. If the checkbox is originally checked, click only toggles it. Codeception has uncheckOption http://codeception.com/docs/modules/WebDriver#uncheckOption.

I'll send the PR later for WebdriverIO, but I think it will need further work for the other backends.
