### ISSUE TITLE
The browsers restarts when starting each Puppeteer scenario

### ISSUE THREAD

**Issue by awshanks** [Codeception/CodeceptJS#854]
#### What are you trying to achieve?

Run puppeteer tests without the browser reloading between Scenarios.

#### What do you get instead?

The browser is reloading between Scenarios and does not respect the restart config value.

### Details

* CodeceptJS version: 1.1.1
* NodeJS Version: v8.9.3
* Operating System: MACOS

**Comment by DavertMik** [comment]
Yes, `restart: false` option is not yet implemented for Puppeteer. 
The issue was that it was hard to deal with restarting session when there could be multiple tabs opened.
I think I can try it once more and implement in next release

**Comment by reubenmiller** [comment]
This feature was added in PR #921 which is available in 1.1.5.
