### ISSUE TITLE
When using GPO and passing the object into scenario its not working

### ISSUE THREAD

**Issue by mathis7875** [Codeception/CodeceptJS#860]
#### What are you trying to achieve?
Pageobject 

#### What do you get instead?
Not able to see object in test file.

----Security page object file ---

`'use strict';

let I;

module.exports ={

  _init() {
    I = actor;
  },
  
  fields: {
    username:({xpath: '//*[@id="login"]/div[2]/div/div/div/div/div/form/div[1]/div/input'}),
    password: ({xpath:'//*[@id="login"]/div[2]/div/div/div/div/div/form/div[2]/div/input'}),
    loginButton: ({xpath: '//*[@id="btn-login"]'})
  
  },

  // methods
  
  submitlogin(username,password){
      I.fillField(this.fields.username,'mathitest1');
      I.fillField(this.fields.password,'somepassword');
      I.click(this.loginButton);
 }
}

---------codecept.js ----------

  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "chrome"
    }
  },
  "include": {
    "I": "./steps_file.js",
    "loginPage": "./pages/loginPage.js",
    "secutiryPagePage": "./pages/secutiryPage.js"
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "tests": "./*_test.js",
  "timeout": 10000,
  "name": "TestFramework"
}

![image](https://user-images.githubusercontent.com/33791028/34642533-4a9b628a-f2c9-11e7-9d63-9aeba5c089aa.png)
![snip20180106_2](https://user-images.githubusercontent.com/33791028/34642551-7200ee94-f2c9-11e7-8d1a-0136213f25d8.png)

**Comment by jploskonka** [comment]
In your config in `include` statement you name your page object as `securityPagePage` while in Scenario you pass `securityPage` ;) PageObject generator, invoked with `codeceptjs gpo` automatically appends `Page` suffix to generated page objects.

PS. Please mind formatting of your issue, it's completely unreadable ;-)

**Comment by mathis7875** [comment]
Thanks. Im sorry I did notice that and corrected.  How ever the issue still exist when using the codecept js with page object. I wen and create another page object manually without using the codecept gpo command and same thing .Yes I did include the  new page object in the  codecept js file . Would there be anything else to look at?

My backend is : 
WebdriverIO
codecept js 1.1. version 
macos 
vscode ide

**Comment by mathis7875** [comment]
With using the pageobject name from the codeceptjs file I get the following error: below
Could not include object loginPage from module '/Projects/testautomation/pages/login.js'
Cannot find module '/Projects/testautomation/pages/login.js'

Error:
    at loadSupportObject (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/container.js:192:11)
    at getSupportObject (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/container.js:180:12)
    at createSupportObjects (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/container.js:137:21)
    at Function.create (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/container.js:29:25)
    at Codecept.init (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/codecept.js:47:15)
    at Command.module.exports (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/command/run.js:35:14)
    at Command.listener (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/commander/index.js:653:12)

**Comment by colakbilal** [comment]
I have same problem with @mathis7875.
Do ypu have any suggestion about this isuue @jploskonka 
Thanks in advance

**Comment by reubenmiller** [comment]
It must be a problem with the naming of the files, and then the linking that you have in the codecept.js file under the "include" property.

The examples that you have provided don't show all of the information and the file names would be helpful.

In the above example in the codecept.js file you have defined the `loginPage.js` should be mapped to `loginPage`, however the error message is saying that `login.js` does not exist. So I am guessing you just have some naming problems.

And be aware the the relative addresses are in relation with the path of your codecept.js file...
