### ISSUE TITLE
Question : How do I update the test root path 

### ISSUE THREAD

**Issue by mathis7875** [Codeception/CodeceptJS#866]
#### What are you trying to achieve?
What to update the test root path.....how is this accomplished ?

I see this under configurations section on the web site :
tests: "./*_test.js" - pattern to locate tests

not sure if I change the root path here in the codeceptjs file ..

**Comment by reubenmiller** [comment]
Yes you specify the folder where your tests are located using the "tests" property in the codeceptjs config file.

Though be aware that if you use relative paths, it is relative to your config file.

**Comment by reubenmiller** [comment]
Closing due to lack of response.
