### ISSUE TITLE
How To Clear Output Folder That Saves The Failed Cases Snapshot

### ISSUE THREAD

**Issue by ninpop25** [Codeception/CodeceptJS#867]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
This can be done with Jenkins without CodeceptJS

Just add `rm -rf tests/output/*` before executing tests.

And please don't spam in Twitter. That doesn't sound like a good manner.

**Comment by ninpop25** [comment]
@DavertMik : Thanks for reply,I forgot to inform you that my Server is **Windows 10** Machine,so request you to please tell me the command for windows that deletes all Sub Folders and Files Inside **Output** Directory .

Also please let me know that how this **Output** folder that contains snapshots ,will be attached in Build Report mail?

I am really sorry for Spamming twitter ,will not do it again.

Thanks once again for quick response

**Comment by schmkr** [comment]
Here's an FYI on how I just set this up using the `bootstrap` configuration:

```
"bootstrap": function(done) {
    try {
        const {ctimeMs} = fs.statSync(OUTPUT_PATH);
        fs.renameSync(OUTPUT_PATH, `${OUTPUT_PATH}_${ctimeMs}`);
    } catch(error) {
        console.error('Could not rename output path');
        console.log(error);
    }

    done();
},
```

I choose to rename the old output folder instead of deleting it, deleting it might require using `glob` or launching a sub-process that is aware of the OS.

`OUTPUT_PATH` is a variable defined on top of the configuration file, that is used both in this bootstrap function and in the `output` configuration. Not sure if there is a way to get the current configuration of Codecept as a parameter to the bootstrap function?

**Comment by schmkr** [comment]
🤔 Forget that, it seems doing this in the bootstrap function, the output dir is renamed during the run 😞

**Comment by aesyondu** [comment]
Here is how I did it for 3.0.2, in case someone comes here from search engine:

```javascript
// codecept.conf.js
const rimraf = require("rimraf");
const outputFolder = "./test/e2e/bdd/.tmp";

exports.config = {
  // ... irrelevant code
  output: outputFolder,
  async bootstrap() {
    await new Promise((resolve, reject) => {
      rimraf(outputFolder, (err) => {
        if (err) {
          reject(err);
        } else {
          resolve();
        }
      });
    });
  },
  // ... irrelevant code
};

```
