### ISSUE TITLE
How to attach Snapshot Output Folder in Build Report Mail

### ISSUE THREAD

**Issue by ninpop25** [Codeception/CodeceptJS#869]
####  my Server is Windows 10 Machine,so  please let me know that how this Output folder that contains snapshots of Failed tests ,will be attached in Build Report mail

I am running my test cases Via Jenkins.

@DavertMik @APshenkin : please look into this 

#### Currently snapshots of Failed tests are getting saved in Output Folder. 

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:Windows 10
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by reubenmiller** [comment]
I have been using Jenkins to run my tests and then view the report.

Firstly, in codeceptjs I use the fantastic mochawesome reports ([http://codecept.io/reports/#multi-reports](url)).

On the jenkins side, I use the [HTML Pluglisher Plugin](https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin) which can display the html report from within jenkins (along with inline screenshots of the failed tests). And this Jenkins plugin as the advantage of then being able to download the report as a full zip file.

But it doesn't make much sense for codeceptjs to handle the zipping and emailing of the reports and screenshots, that should be left up to Jenkins (or any other CI program). Plus you would probably have problems with the size of emails if there are a lot of screenshots.

**Comment by ninpop25** [comment]
@reubenmiller : Thanks for reply to my query and sorry for this delay in response.

Actually I am using Mocha junit reports and below is my structure that I am using in codecept.json file

"mocha": {
    "reporterOptions": {
      "codeceptjs-cli-reporter": {
        "stdout": "-",
        "options": {
          "verbose": false,
          "steps": true
        }
      },
      "mocha-junit-reporter": {
        "stdout": "./output/console.log",
        "options": {
          "mochaFile": "./output/result.xml"

Could u please check that how I can get my output folder zipped every time and attached to email when my tests build on Jenkins gets finished after start

**Comment by reubenmiller** [comment]
It should be solved in Jenkins and not with Codeceptjs.

There are plenty of plugins for Jenkins that can most likely fulfil this requirement. Here are the steps that I would configure in Jenkins...

1. Execute CodeceptJS tests.
1. Zip the output folder (which is defined in your codeceptjs configuration)
1. Add the zip file to the email file after the tests are executing using Jenkins (with help of the plugin if it is not supported by default).

Personally, I don't see any sending the screenshots of all the failed test cases by email as it adds to much weight to the email. The email should only serve as a notification that the tests either passed, or failed. You can add the reports and the Jenkins console output easily enough to the emails, which provides some supplementary information about which test cases when wrong, but the troubleshooting information should be stored in Jenkins directly. However you could add a link to the url in the email which directs the recipient to the Jenkins build server.

Alternatively, if the Jenkins server does not have a public facing interface, then you could use some scripting magic (personally I favour Powershell at the moment) to push build files to the cloud somewhere and add the links to it in the email.

Happy coding!

**Comment by ninpop25** [comment]
@reubenmiller : Thanks for reply once again,I tried to search plugin in jenkins that creates zip of folder
I found this https://wiki.jenkins.io/display/JENKINS/File+Operations+Plugin, and thanks you so much that you helped me as this plugin worked for me and by using Attachment option in jenkins post build action I got it worked as required.

I would love to appreciate your help and also would like you to check that if you can help me with below issues as I am not getting any response on these from any one on codceptjs.

https://github.com/Codeception/CodeceptJS/issues/878
https://github.com/Codeception/CodeceptJS/issues/864
*https://github.com/Codeception/CodeceptJS/issues/892*
*https://github.com/Codeception/CodeceptJS/issues/893*

bold ones are the one in which I need urgent help as they are impacting my automation task

**Comment by reubenmiller** [comment]
Glad it worked. Then can you please close the issue? @ninpop25
