### ISSUE TITLE
Retrieve Username via REST API and enter it in a login form

### ISSUE THREAD

**Issue by whyper** [Codeception/CodeceptJS#871]
#### What are you trying to achieve?
I'm trying to read data via the REST helper and enter the retrieved data into an input field on a web site

#### What do you get instead?
I could not find any information about how to retrieve data from the REST helper and use it in a subsequent step. When I'm logging the return value from the sendGetRequest I'm only receiving a promise.

> Provide console output if related. Use `--verbose` mode for more details.
I'm missing documentation on how to use the 

> Provide test source code if related
I would like to do something like this
```js
	let ret = I.sendGetRequest('http://rest.test.com/posts/1');
	
	console.log("Return value: " + ret);
	
	I.amOnPage('https://www.test.com');
	I.fillField('username', ret.body);
```

### Details

* CodeceptJS version: 1.1
* NodeJS Version: 8.9.4
* Operating System: Windows 10
* WebDriverIO
* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "chrome"
    },
    "REST": {}
  },
  "include": {
    "I": "./steps_file.js"
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "tests": "./*_test.js",
  "timeout": 10000,
  "name": "test"
}
```

**Comment by DavertMik** [comment]
Yes, to handle promise you need to follow async/await pattern. Please see [How it Works](http://codecept.io/basics/#how-it-works) section. In your case test will be:

```js
Scenario('login into form', async (I)=> {
	let ret = await I.sendGetRequest('http://rest.test.com/posts/1');
	
	console.log("Return value: " + ret);
	
	I.amOnPage('https://www.test.com');
	I.fillField('username', ret.body);
```
