### ISSUE TITLE
[Puppeteer/Proposal] Support acceptPopup, cancelPopup and seeInPopup functions

### ISSUE THREAD

**Issue by reubenmiller** [Codeception/CodeceptJS#874]
#### What are you trying to achieve?

Expand the Puppeteer Helper to support the popup functions to more towards feature parity with the WebDriverIO Helper so the two can be used interchangeably.

#### Background

Puppeter can interact with popups (refered to as Dialogs in Puppetter) by listening to 'dialog' events on a page.

Here is the example of adding the dialog listener to the page (pulled from the Puppeteer docs).

```js
page.on('dialog', async dialog => {
  console.log(dialog.message());
  await dialog.dismiss();
});
```

The Dialog object has API which allows us to query the text and either accept or dismiss it. The bad news is that the event handler will not return the control flow until either Dialog.dismiss() or Dialog.accept() is called (or at least I could not figure out how to do it). So we are forced to think about how the dialog should be handled even before the dialog event occurs.

This paradigm conflicts with the Codeceptjs Javascript DSL which is more turn based, and would normall y only need to work about handling the dialog action after the dialog appears.

```js
I.click('button'); // Assume this click triggers an alert
I.seeInPopup('Alert description')
I.acceptPopup();
```

As the Dialog `MUST` be accepted or dismissed within the listener callback we need to either have a default way of handling dialogs and/or allow the user to also control the default action.

So what I propose is the following:

```js
I.setDefaultDialogAction('dismiss'); // Set default dialog action which occurs automatically. Though this is only needed if 'accept' is not ok to use.
I.click('button'); // Assume this click triggers an alert
I.seeInPopup('Alert description')
I.acceptPopup();
```

#### Drawbacks with this approach
1. Adds additional Helper function `setDefaultDialogAction` which is not support in other helpers.
1. It's a bit hacky. However if the Dialog is not dismissed or accepted within the dialog listener, then the test blocks the thread.
1. In WebDriverIO, if any other helper function is used when an dialog is visible then an exception will be thrown, however in this approach nothing will occur as the dialog was already dismissed (due to being forced to handle it in the dialog handler)

#### Implementation

It might may a little more sense by showing the code and the function descriptions.

##### setDefaultDialogAction()
This function changes the default action used in the Dialog handler. It defaults to accept the Dialog, however if another action is required, then it can be changed before the Dialog is triggered.

##### _addDialogListener()
Called anytime a page is created or changed. The purpose of this function is to create the dialog handler for the page. It saves a reference to the Dialog object when the event is triggered, and then handles the dialog by either dismissing it or accepting it (based on the current action set by setDefaultDialogAction()).

The reference to the Dialog object will be saved in a new object `dialogStore`, so that it can be probed for information after the listener callback (i.e. to get the text of the dialogbox in seeInPopup()).

##### acceptPopup()
This simulates accepting a popup, but technically the popup has alread been accepted (by the Dialog handler). If no Dialog is in the dialog store, then it will throw an error. Technically the function does not do alot except for removing the reference to the Dialog that was created, and it keeps the API the same as the WebDriverIO Helper meaning you only have to write one set of tests for both WebDriverIO and Puppeteer :)

##### cancelPopup()
Same as acceptPopup(), and keeps API the same as the other Helpers.

##### seeInPopup()
Assert that the popup message contains the given text

#### Proposed Code to highlight the idea

Below is the proposed code which will be added to ```Helpers/Puppeteer.js```. It is not the full code, but enough to get a good feel for it.

```js
/**
 * Assert that a popup has occured (i.e. 'visible')
 */
_assertPopupVisible() {
  const { dialog } = dialogStore;
  if (!dialog) {
    throw new Error('Popup is not visible');
  }
}

/**
 * Remove the Puppeteer.Dialog object from the store
 */
_removeDialog() {
  dialogStore.dialog = null;
}

/**
 * Simulate acceptPopup, if a popup has not previously
 * occured before calling this function then it will
 * throw an error (i.e. similar behaviour as with the
 * WebdriverIO Helper)
 *
 * The dialog store will be cleared after calling this
 * function, so it can not be called twice
 * on the same dialog.
 */
acceptPopup() {
  this._assertPopupVisible();
  this._removeDialog(); // Dummy accept
}

/**
 * Simulate cancelPopup, if a popup has not previously
 * occured before calling this function then it will
 * throw an error (i.e. similar behaviour as with the
 * WebdriverIO Helper)
 *
 * The dialog store will be cleared after calling this
 * function, so it can not be called twice on the same
 * dialog.
 */
cancelPopup() {
  this._assertPopupVisible();
  this._removeDialog(); // Dummy dismiss
}

/**
 * Assert that the popup message contains the given text
 *
 * @param {string} text String to expect inside the popup
 */
async seeInPopup(text) {
  this._assertPopupVisible();
  const popupText = await dialogStore.dialog.message();
  console.log('Checking popup', popupText);
  stringIncludes('text in popup').assert(text, popupText);
}

/**
 * Set current page
 * @param {Puppeteer.Page} page page to set
 */
_setPage(page) {
  this._addDialogListener(page);
  this.page = page;
}

/**
 * Set default handling of popup in the Dialog handler
 * @param {string} actionType Action type to perform
 * when a popup occurs (either accept or dismiss)
 */
setPopupHandlerAction(actionType) {
  if (['accept', 'dismiss'].indexOf(actionType) === -1) {
    throw new Error('Invalid popup action type. Only accept or dismiss can be defined');
  }
  dialogStore.dialogAction = actionType;
}

/**
 * Add the 'dialog' event listener to a page
 * @page {Puppeteer.Page}
 *
 * The dialog listener handles the dialog with the
 * predefined action when it appears on the page.
 * It also saves a reference to the object which
 * is used in seeInPopup.
 */
_addDialogListener(page) {
  if (!page) {
    return;
  }
  page.on('dialog', async (dialog) => {
    if (dialogStore.dialog) {
      console.error('Dialog already exists and was not closed. Please always close the dialog boxes by using the I.acceptPopup() or I.cancelPopup()');
    }
    dialogStore.dialog = dialog;

    if (dialogStore.dialogAction === 'accept') {
      return dialog.accept();
    }
      return dialog.dismiss();
  });
```

**Comment by reubenmiller** [comment]
@DavertMik Could you have a look at my proposal and tell me what you think. I want to get confirmation before I go ahead with a pull request.

**Comment by DavertMik** [comment]
Thanks, looks like the only solution we could make it here. And yeah, I like the overall idea. Just wondering what will happen in this case:

```js
I.setDefaultDialogAction('dismiss');
I.click('Open popup');
I.acceptPopup(); 
```
What will happen in this case? Will popup be rejected or accepted?

Also, I'd like to propose different naming:

```js
I.amAcceptingPopups();
I.amDismissingPopups();
```
As this sounds a bit more natural to me. Also, the corresponding config option can be added you could just add: `defaultPopupAction: "accept"` (and set some default value). In most cases that will be enough.

**Comment by reubenmiller** [comment]
Thanks for the review.

* I'll rename the helper functions as per your suggestion
* I'll add the defaultPopupAction to the puppeteer config object

#### w.r.t. Dismissing a popup when an automatic accept popups is already config
I have a feeling that puppeteer will not have a problem with it, though I will create some unit tests to check out the behaviour. But regardless of the result, I think we should implement strict checking to ensure the user is using the api correctly.

#### Other questions
1. What do you (@DavertMik) think of adding an additional Helper function to get the text of a popup without using an assert statement. The reason is I have recurring use cases where I am performing documentation tasks, and sometimes I don't care if there is a popup visible, however I need to dismiss the popup so the code can still interact with the browser. So I guess it would be more in line with the `grab*` helper functions, may I.grabPopupMessage().
  ** Task: Add I.grabPopupMessage() (or I.grabPopupText()) to WebDriverIO, Puppeteer and Nightmare?

**Comment by DavertMik** [comment]
> adding an additional Helper function to get the text of a popup without using an assert statement.

That would be great! `I.grabPopupText()` is fine

**Comment by reubenmiller** [comment]
Great. I'll submit a pull request in the next few days.
