### ISSUE TITLE
[Wrapped Error] "Cannot read property 'findAndStoreElements' of undefined"

### ISSUE THREAD

**Issue by leftty** [Codeception/CodeceptJS#880]
#### What are you trying to achieve?
I am trying to fill an input field with some text

#### What do you get instead?
[Wrapped Error] "Cannot read property 'findAndStoreElements' of undefined"
> Provide console output if related. Use `--verbose` mode for more details.

```bash
• I fill field "_username", "user144001"
   [1] Error | Cannot read property 'findAndStoreElements' of undefined
   Emitted | step.failed (I fill field "_username", "user144001")
   Step finished in 1.929 sec
   [1] Error | Error: [Wrapped Error] "Cannot read property 'findAndStoreElements' of undefined"
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook Nightmare._failed()
   [1] <teardown> Queued | hook Util._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises

  Error: [Wrapped Error] "Cannot read property 'findAndStoreElements' of undefined"
      at promise.catch (/Users/Dragos/Documents/codeceptjs-tests/node_modules/codeceptjs/lib/recorder.js:135:15)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

> Provide test source code if related

```js
I.fillField('_username', 'username');
```

### Details

* CodeceptJS version: v1.1.1
* NodeJS Version: v9.0.0
* Operating System: macOS Sierra
* Nightmare version: v2.10.0
* Configuration file: 

```js
helpers: {
        Nightmare: {
            url: ...,
            show: true,
            restart: true,
            typeInterval: 30,
            smartWait: 5000,
            switches: {
                'ignore-certificate-errors': true
            }
        }
    },
```
If this is strictly a Nightmare related issue(and not a codeceptjs one) I will re-create this ticket in the proper repo.

**Comment by petrisorionel** [comment]
The same issue for findElement

[Wrapped Error] "Cannot read property 'findElement' of undefined"

**Comment by reubenmiller** [comment]
I can't seem to replicate the issue.

Here is my test case that I just tests with Codeceptjs v1.1.1, NodeJS 9.0.0, Nightmare v2.10.0.

```js
Scenario('I fill field @nightmare', (I) => {
    I.amOnPage('/');
    I.fillField('#lst-ib', 'test search');
});
```

And the Helper config...
```js
helpers: {
    Nightmare: {
      url: 'https://google.com',
      windowSize: '600x400',
      show: true,
    },
  },
```

Maybe something is not quite right with your setup. Maybe try reinstalling the node_modules folder?

**Comment by resurtm** [comment]
I also have this issue:

```
[Wrapped Error] "Cannot read property 'findElement' of undefined"
```

**Comment by charlyhul** [comment]
+1 
same issue for me. after a form submit codcept is not available anymore
 ` [Wrapped Error] "Cannot read property 'findElement' of undefined"`

**Comment by reubenmiller** [comment]
Hi guys, does anyone have a website which I can test this against, so I can debug this, as I haven't been able to reproduce this in the dev environment.

**Comment by charlyhul** [comment]
Here is an example: 

```javascript
Scenario('test search', I => {
      I.amOnPage('https://www.staubli.com');
      I.waitForElement('.search__button');
      I.waitForElement('#tx_indexedsearch_word-');
      I.fillField('#tx_indexedsearch_word-', 'test');
      I.click('.search__button');
      I.waitForElement('.tx-indexedsearch-search-subheadline');
});
  ```
and the config: (important window size and timeout for this website example)
```javascript
    "helpers": {
        "Nightmare": {
            "windowSize": "1200x900",
            "waitForTimeout": 10000,
            "show": true
        }
    }
```
Test always stops with error after submit
` [Wrapped Error] "Cannot read property 'findElement' of undefined"`

With codeceptjs version 1.1.5, nightmare version 2.10.0 and node version 8.9.3

**Comment by reubenmiller** [comment]
@charlyhul Thanks, I'll have a look at it sometime on the weekend.

**Comment by reubenmiller** [comment]
The problem occurs because the page is navigating away, however since `waitForElement` is called immediately after the `I.click`. This causes a problem with the client side scripts that are used to located the given element. 

In the Nightmare helper we are using the inbuilt nightmarejs `.wait(fn)` and this causes problems when the page is navigated away from. However when I found that if we use nightmarejs `.wait(string)` then it works for some reason.

However, the good news is that you can solve this problem by using the new [Retry Step](https://codecept.io/basics/#retry_step) feature to solve the problem. The **Retry Step** was first introduce in v1.1.5, so if you have an earlier version, then please upgrade.

Here is the same example however with the `I.retry().waitForElement('.tx-indexedsearch-search-subheadline');`. The test now passes :)

```js
Scenario('test search', I => {
  I.amOnPage('https://www.staubli.com');
  I.waitForElement('.search__button');
  I.waitForElement('#tx_indexedsearch_word-');
  I.fillField('#tx_indexedsearch_word-', 'test');
  I.click('.search__button');
  I.retry(2).waitForElement('.tx-indexedsearch-search-subheadline'); // This retries 2 times if needed
});
```

**Comment by charlyhul** [comment]
@reubenmiller thanks a lot. it works for me now with the retry step. 👍 hopefully it will be a solution for the others here too

**Comment by Brydom** [comment]
If anyone else runs into this, I fixed it by adjusting the helper to use `const I = inject();` at the beginning instead of setting `I` in the `_init()` function within the object. Also needed to update Codecept version as I guess `_init()` was deprecated and replaced with `inject()`.
