### ISSUE TITLE
"Meta packages" do not specify versions

### ISSUE THREAD

**Issue by callumlocke** [Codeception/CodeceptJS#882]
I just tracked down a weird bug to the `codeceptjs-webdriverio` package.

It seems to depend on `*` (any version) of its two components (see [package.json](https://github.com/DavertMik/codeceptjs-webdriverio/blob/master/package.json#L23-L24)):

```
  "dependencies": {
    "codeceptjs": "*",
    "webdriverio": "*"
  },
```

Is this intentional? It means if you upgrade your `codeceptjs-webdriverio` dependency, and then run `npm install` or `yarn`, it may not actually upgrade either of the sub-dependencies, because `*` covers anything, and it will just follow your lockfile. In my case this means installing `codecept-webdriverio@1.1.0` gets me very old versions of both codecept and webdriverio.

I'm not clear on the benefit of these meta-packages in general. I initially assumed they contained some kind of compatibility layer between codecept and the driver, but it seems they don't do anything besides pull in other packages. I can't see any advantage of `npm install codeceptjs-webdriverio` over `npm install codeceptjs webdriverio`.

**Comment by DavertMik** [comment]
> I can't see any advantage of npm install codeceptjs-webdriverio over npm install codeceptjs webdriverio.

No advantage. But we had lots of people complaining about hard installation. 

Introducing one package could help them to start. However, I'm not so happy with that idea :(
I think this installation process should be improved so `codeceptjs` would install all dependent package if when a corresponding Helper is enabled.

**Comment by callumlocke** [comment]
> But we had lots of people complaining about hard installation.

But how is `npm install codeceptjs-webdriverio` any easier than `npm install codeceptjs webdriverio`? It's just switching a space for a hyphen.

**Comment by DavertMik** [comment]
This can be easier if we do global installation. At least in this case the dependencies would be matched.
But maybe you are right and the same can be achieved without extra packages...

**Comment by DavertMik** [comment]
Meta packages were removed from documentation.
