### ISSUE TITLE
Erroneous assertion not breaking the Scenario

### ISSUE THREAD

**Issue by vinicius978** [Codeception/CodeceptJS#884]
#### What are you trying to achieve?
I'm trying to do an assertion in a test Scenario with 2 values taken from two different pages on a website 
#### What do you get instead?
Even forcing the assertion to fail, test keeps outputting that it PASSED.

A snippet of the assertion part:
```js
        let assert = require('assert');
        I.say('Assertion...');
        assert.true(value1 == (value2 + value3));
```

I need like a **I.assertThat(_expression_)** in order for the test to fail when values don't match.
Right now I'm researching about assertions on codecept and trying to figure out a solution for that.

### Details

* CodeceptJS version: 1.1.1
* NodeJS Version: 9.4.0
* Operating System: Linux Mint
* WebDriverIO

**Comment by reubenmiller** [comment]
I looked at the package.json and found no dependency to 'assert', so they must be using the node assert library. https://nodejs.org/api/assert.html

As per the node js docs, there is no `.true` property, so unless you're using another assert library (or I'm reading the docs wrong).

Though I've been using the chai ([http://chaijs.com/api/bdd/](url)) expect/should module in my project with success. Here's an example.

```js
const { expect } = require('chai');
expect(true).to.be.true;
```

**Comment by vinicius978** [comment]
Thanks for that, appreciate it!

BTW, in order to build a structure like ` I.assertThat(expression)`, I need to create a Helper for this purpose?

**Comment by reubenmiller** [comment]
Yes implementing it in a Helper is one way of doing it, and probably the most common. The other option is to define a [StepObject](http://codecept.io/helpers/), which also allows you to use I.AssertThat(expression), and the StepObject can also import additional PageObjects if required.

**Comment by reubenmiller** [comment]
I would suggest looking at the source code for the Helpers i.e. in ./lib/helper/WebDriverIO.js. They provide great examples on how to do it.

i.e. this is from the WebDriverIO.js Helper
```js
  async seeInTitle(text) {
    const title = await this.browser.getTitle();
    return stringIncludes('web page title').assert(text, title);
  }
```

**Comment by reubenmiller** [comment]
Can you please close the issue if your original question has now been answered.
