### ISSUE TITLE
Documentation of Selenium WebDriver helper not appearing in menu

### ISSUE THREAD

**Issue by gosua** [Codeception/CodeceptJS#886]
#### What are you trying to achieve?
I am trying to open the documentation page of the Selenium WebDriver helper using the website codecept.io. 

#### What do you get instead?
The Selenium WebDriver entry isn't appearing in the menu. I can remember that it worked before version 1.1. 
![11](https://user-images.githubusercontent.com/2049002/35143676-94a7432e-fd02-11e7-8057-ec86d71769f2.PNG)

When I access the direct link to the Selenium WebDriver helper, it apperas in the menu but the Puppeteer entry disappeared. 
![22](https://user-images.githubusercontent.com/2049002/35143686-98dc2a40-fd02-11e7-9bea-9bfc75c7cdfc.PNG)

**Comment by DavertMik** [comment]
Yes, this helper was deprecated. Sorry if this made some troubles to you.
Use Protractor helper instead. They use the same backend and work in the similar manner so there was no reason to maintain 2 different helpers.

Just change in your config to `Protractor` and it can work for you.
