### ISSUE TITLE
Redundant hooks link on website Configuration page

### ISSUE THREAD

**Issue by rizmudano** [Codeception/CodeceptJS#887]
#### What are you trying to achieve?
Find documentation for hooks on website

#### What do you get instead?
When I click the `see Hooks` link (e.g. on the Configuration page: `bootstrap: "./bootstrap.js" - an option to run code before tests are run. See Hooks).`) the link just returns to the configuration page: `http://codecept.io/configuration/#hooks`. Screenshot:

![image](https://user-images.githubusercontent.com/28341546/35145428-a7435aca-fcff-11e7-8a00-2f6d1855c8d2.png)

**Comment by DavertMik** [comment]
Thanks! This should be improved. Right!
