### ISSUE TITLE
Currently offset is ignored :( change this console output

### ISSUE THREAD

**Issue by frantallukas10** [Codeception/CodeceptJS#894]
https://github.com/Codeception/CodeceptJS/blob/6954ca78213f29c6de0fb72491e34f4383e74c2e/lib/helper/Puppeteer.js#L332

please remove this console log

**Comment by reubenmiller** [comment]
The message was for a placeholder because when the puppeteer helper was created it did not support offsets.

However the latest version (>= 1.1.4) supports offsets when using `moveToCursor`, so the console.log statement was removed. PR was #899.
