### ISSUE TITLE
Using Istanbul to calculate code coverage

### ISSUE THREAD

**Issue by simoncast** [Codeception/CodeceptJS#895]
#### What are you trying to achieve?
I'd like to use [istanbul](https://istanbul.js.org/) to calculate code coverage reports for our CodeceptJS tests. The [mocha tutorial](https://istanbul.js.org/docs/tutorials/mocha/) for Istanbul indicates you run the mocha tests with nyc e.g. `nyc mocha run`

As CodeceptJS is based on Mocha, will it work to run codeceptjs using nyc? e.g. `nyc codeceptjs run`

**Comment by DavertMik** [comment]
No, code coverage is not possible for end to end tests because they do not touch the code directly. They interact with application via browser and webserver, so there is no ideas of the actual code being run.

**Comment by Odonno** [comment]
I also really hope for this to come!

https://docs.cypress.io/guides/tooling/code-coverage.html

**Comment by khanhere** [comment]
@Odonno This is out for Cypress. I wonder if it would work the same way forCodeceptjs as well?
