### ISSUE TITLE
Init test folder not working

### ISSUE THREAD

**Issue by antonioribeiro** [Codeception/CodeceptJS#9]
When I try to configure:

![image](https://cloud.githubusercontent.com/assets/3182864/11605098/2bc19298-9ade-11e5-9970-09e9fc91a8e9.png)

I get

```
  {
    "tests": "./*_test.js",
    "timeout": ...
  }
```

Output and Include are working fine.

**Comment by DavertMik** [comment]
Thanks. WIll fix it
