### ISSUE TITLE
sh: yarn: command not found

### ISSUE THREAD

**Issue by wahengchang** [Codeception/CodeceptJS#905]
since codeceptjs is updated to @1.1.3, `yarn: command not found` error has occurred. 

What does `preinstall` do?
Can you add a check that before running this script `preinstall`?

```
$ codeceptjs@1.1.3 preinstall /var/builds/workspace/286168-v3-corp-int/BUILD_CONTAINER/node8/label/DOCKER-LOW/app_root/node_modules/.staging/codeceptjs-97511797
$ yarn --ignore-scripts
$ sh: yarn: command not found
```

**Comment by DavertMik** [comment]
oh, sorry, looks like someone added yarn dependency. 
Yarn is an alternative to npm

**Comment by estelendur** [comment]
So is yarn just necessary now? No way to sidestep or ignore it?

**Comment by estelendur** [comment]
The problem was introduced in [this commit](https://github.com/Codeception/CodeceptJS/commit/f0c4263c517bae589d4269b09aecd65e906816db), in what seems to have been a likely unnecessary change that was never reverted?
> * My morbid curiosity is seeing what swapping yarn with npm will do.

**Comment by DavertMik** [comment]
Yeah, sorry, I thought I removed that line but accidentally it passed to release. 
So I removed and published a new release
