### ISSUE TITLE
console output in jenkins with run multiple

### ISSUE THREAD

**Issue by frantallukas10** [Codeception/CodeceptJS#906]
#### What are you trying to achieve?
I would like created multiple run console output first output will: Start test description for every scenario with description and when every test is finish, I would like create output like this:

Start testing bla bla bla 1
Start testing bla bla bla 2
Start testing bla bla bla 3
Finished testing bla bla bla 1
Finished testing bla bla bla 2
Finished testing bla bla bla 3 - failed
// ===================================
Failed:
Scenario: @test3| bla bla bla 3
// ===================================

#### What do you get instead?
If I runned test my console output is

Start testing bla bla bla 1
Start testing bla bla bla 2
Finished testing bla bla bla 2
Start testing bla bla bla 3
Finished testing bla bla bla 1
Finished testing bla bla bla 3

> codeceptjs run-multiple --all --reporter mocha-multi

```js
Feature('test1')
BeforeSuite(I => {
	console.log('Start testing bla bla bla 1')
})
AfterSuite(I => {
	console.log('Finished testing bla bla bla 1')
})
const scenario1 =
	'@test1|' +
	'bla bla bla 1'
Scenario(scenario1, function*(I) {
I.login('id')...
})
```
// ================
```js
Feature('test2')
BeforeSuite(I => {
	console.log('Start testing bla bla bla 2')
})
AfterSuite(I => {
	console.log('Finished testing bla bla bla 2')
})
const scenario1 =
	'@test2|' +
	'bla bla bla 2'
Scenario(scenario1, function*(I) {
I.login('id')...
})
```
// =============
```js
Feature('test3')
BeforeSuite(I => {
	console.log('Start testing bla bla bla 3')
})
AfterSuite(I => {
	console.log('Finished testing bla bla bla 3')
})
const scenario1 =
	'@test3|' +
	'bla bla bla 3'
Scenario(scenario1, function*(I) {
I.login('id')...
})
```

### Details

* CodeceptJS version: 1.1.3
* NodeJS Version: v8.9.4
* Operating System: windows
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:
	"dependencies": {
		"codeceptjs": "^1.1.3",
		"concurrently": "^3.5.1",
		"puppeteer": "^1.0.0"
	},
	"devDependencies": {
		"mocha": "^4.1.0",
		"mocha-multi": "^0.11.1",
		"mocha-junit-reporter": "^1.15.0",
		"mochawesome": "^3.0.1",
		"mochawesome-report-generator": "^3.1.0"
	}
```js
const multipleConfig= {
	test1: {
		grep: '@test1',
		browsers: ['chrome'],
	},
	test2: {
		grep: '@test2',
		browsers: ['chrome'],
	},
	test3: {
		grep: '@test3',
		browsers: ['chrome'],
	},
}
const defaultConfig = {
	tests: './src/tests/**/*.js',
	timeout: 900,
	output: './output',
	helpers: {
		Puppeteer: {
			windowSize: '1280x800',
			browser: 'chrome',
			chrome: {args: ['--no-sandbox', '--disable-setuid-sandbox']},
			url: 'http://localhost',
			uniqueScreenshotNames: false,
			show: false,
			waitForAction: 1000,
			restart: true,
		},
		MyHelpers: {
			require: './helpers/helpers.js',
		},
	},
	mocha: {
		reporterOptions: {
			'mocha-junit-reporter': {
				stdout: '-',
				options: {
					mochaFile: './output/result.xml',
				},
			},
			mochawesome: {
				stdout: './output/console.log',
				options: {
					reportDir: './output',
					reportPageTitle: 'Report page',
					reportFilename: 'report',
					quiet: true,
					json: false,
					html: false,
					overwrite: true,
					inline: true,
				},
			},
		},
	},
	multiple: multipleConfig,
	bootstrap: false,
	include: {},
	name: 'codecept',
}
```

**Comment by reubenmiller** [comment]
I don't think this is a good idea since the tests are being carried out in parallel, so we can't control how long tests take.

If you want nicer jenkins output logs then consider executing the test serially in Jenkins. Or use a multiple configuration project in jenkins which is mainly used when testing different environments.

The main interesting artefact/s from running the tests are the reports generated by CodeceptJS.

**Comment by frantallukas10** [comment]
and if I want to run some function after all test grep? how to do it?

**Comment by reubenmiller** [comment]
Sorry I don’t understand the question. Do you want to run an extra function after the tests have finished?

**Comment by frantallukas10** [comment]
after all test finished if I run multiple tests

**Comment by reubenmiller** [comment]
I'm still a little confused on the use case for wanting that, but if I have understood the question properly, it could be implemented like so.

Use different codeceptjs configuration files for the different tests. Then just call codeceptjs twice:

```sh
codeceptjs run-multiple -c './config/codcept.conf.all.js' --all --reporter mocha-multi
codeceptjs run  -c './config/codcept.conf.single.js' --reporter mocha-multi --grep 'my special cleanup test'
```

Now if you want to check if the first run was successful or not, just check the exit code before running the second command.

Here is the implementation in powershell.
```powershell
codeceptjs run-multiple -c './config/codcept.conf.all.js' --all --reporter mocha-multi

# Check if the tests passed or not. If all tests passed, then you should get a 0 exit code.
if ($LASTEXITCODE -ne 0) {
    Write-Host "The first tests failed. Aborting tests'
    Exit 1
}
codeceptjs run  -c './config/codcept.conf.single.js' --reporter mocha-multi --grep 'my special cleanup test'
```

**Note** I am not 100% sure if I have used the correct codecepjs cli syntax, but it should be enough to highlight the concept.

**Comment by frantallukas10** [comment]
I used function _finishTest(suite) {} from helper but this function will call for every grep not after finished all tests

**Comment by reubenmiller** [comment]
Ah, I think you're after the `teardown` hook. Check out the [Plugins and Hooks](https://codecept.io/hooks/) page.

**Comment by DavertMik** [comment]
@frantallukas10 I also recommend to use multi configuration project for nicer output in Jenkins. Better to allow CI server to control parallel execution especially if you already use one.
