### ISSUE TITLE
open two tab with run multiple

### ISSUE THREAD

**Issue by frantallukas10** [Codeception/CodeceptJS#908]
#### What are you trying to achieve?
I would like open only one tab in chromedriver

#### What do you get instead?
https://i.imgur.com/nhEco2W.png

> codeceptjs run-multiple --all --reporter mocha-multi

```js
Feature('test1')
const scenario1 =
	'@test1|' +
	'bla bla bla 1'
Scenario(scenario1, function*(I) {
I.login('id')...
})
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:
"dependencies": {
"codeceptjs": "^1.1.3",
"concurrently": "^3.5.1",
"puppeteer": "^1.0.0"
},
"devDependencies": {
"mocha": "^4.1.0",
"mocha-multi": "^0.11.1",
"mocha-junit-reporter": "^1.15.0",
"mochawesome": "^3.0.1",
"mochawesome-report-generator": "^3.1.0"
}
```js
const multipleConfig= {
	test1: {
		grep: '@test1',
		browsers: ['chrome'],
	},
}
const defaultConfig = {
	tests: './src/tests/**/*.js',
	timeout: 900,
	output: './output',
	helpers: {
		Puppeteer: {
			windowSize: '1280x800',
			browser: 'chrome',
			chrome: {args: ['--no-sandbox', '--disable-setuid-sandbox']},
			url: 'http://localhost',
			uniqueScreenshotNames: false,
			show: false,
			waitForAction: 1000,
			restart: true,
		},
		MyHelpers: {
			require: './helpers/helpers.js',
		},
	},
	mocha: {
		reporterOptions: {
			'mocha-junit-reporter': {
				stdout: '-',
				options: {
					mochaFile: './output/result.xml',
				},
			},
			mochawesome: {
				stdout: './output/console.log',
				options: {
					reportDir: './output',
					reportPageTitle: 'Report page',
					reportFilename: 'report',
					quiet: true,
					json: false,
					html: false,
					overwrite: true,
					inline: true,
				},
			},
		},
	},
	multiple: multipleConfig,
	bootstrap: false,
	include: {},
	name: 'codecept',
}
```

**Comment by reubenmiller** [comment]
I had a look at this and it should be pretty easy to fix. I’ll look at submitting a PR this week.

**Comment by frantallukas10** [comment]
ok thank you very much
