### ISSUE TITLE
Run tests in parallel

### ISSUE THREAD

**Issue by genzoman** [Codeception/CodeceptJS#91]
In WebdriverIO you can specify maxInstances and run tests in parallel.  How is this configured in CodeceptJS?

**Comment by DavertMik** [comment]
For now it's not really possible. Probably you can do this, but I didn't try. 
Personally I don't really understand how parallel running tests won't affect each other by using the same web application and data from it. I prefer to run parallel testing in different docker containers to ensure their isolation

**Comment by dmitry-zaets** [comment]
@DavertMik Can you please describe how do you run parallel testing in different containers? Are you just running codecept with different configs or you are using some modules organization to mare it work?

**Comment by jaimehperry** [comment]
@DavertMik - I'm also interested in understanding how to run parallel tests using a dockerized selenium grid ... Any help would be greatly appreciated.

**Comment by gidsi** [comment]
+1

**Comment by monkpit** [comment]
@DavertMik There are webdriver commands to create separate instances of the browser - there is no reason to have an entire separate docker container to test in parallel. On my local machine I have no problems testing 8+ instances of chromedriver (driven via selenium) simultaneously (not using codeceptjs for them, obviously). The execution of every driver is isolated from the others. So I can test 8 instances of the same website logged in as the same user creating different session data and there are no issues with the tests affecting each other. This should be trivial to implement, as it already works and we just need the CodeceptJS tools to send the commands to webdriverio or selenium.

Feel free to ask me if you have any questions about my existing setup.

**Comment by APshenkin** [comment]
In `v0.6.0` we added new command `multiple-run`. It's allow you to create different suites for different browsers and launch them in parallel using NodeJS child processes. See http://codecept.io/advanced/#multiple-execution

Also as mentioned you can create a Dockerfile, add selenium and your test to docker to run tests in isolation. Then run several docker instances with different arguments (e.g. use grep to define suites http://codecept.io/advanced/#groups)

**Comment by andrewl913** [comment]
I agree with @monkpit . This issue should be reopened. Right now it takes roughly 30 minutes for our test suite to finish, we have it funneled in to our build process so it makes deployment very sluggish. We are not about to spin up a bunch of docker containers and run test groups. Selenium hub has this capability and its already supported in webdriver.io
