### ISSUE TITLE
Generator function start before test and fail it 

### ISSUE THREAD

**Issue by VladToporkov** [Codeception/CodeceptJS#926]
#### What are you trying to achieve?
I want to check link from my site in last step. 
#### What do you get instead?
It fails at start
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
1) Федеральная база
       test something @test:
     Cannot read property 'css' of undefined

> Provide test source code if related

```js

Scenario('test something @test', function* (I, lawPage) {

    lawPage.getPage();
    lawPage.checkPage();
    lawPage.checkWidget(0);
    lawPage.fillWidgetSearch(0, '123');
    yield* lawPage.checkAutoComplete();

});

checkAutoComplete: function*  (widgetId, id) {

        let css = this.widget.list[widgetId].css  +' '+ this.widgetSearch.autoCompleteList.css + ':nth-child(' + id + ') a';
        I.waitForVisible(css, this.timeout);
        let link = yield I.grabAttributeFrom(css, 'href');
        console.log(link);
        I.sendGetRequest(link);

        return;
    },
```

### Details

* CodeceptJS version 1.1:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by reubenmiller** [comment]
This answer was already addressed on the slack channel, but here is the example using async/await in a pageObject

### Test
```js
Feature('Page Object Examples');

Scenario('Call page object function', async (I, testPageObj) => {
    I.amOnPage('/');
    const res = await testPageObj.getSomething();
    console.log('page object result', res);
});
```

### testPageObj Page Object definition
```js

'use strict';
let I;
module.exports = {
  _init() {
    I = actor();
  },
  async getSomething() {
    const title = await I.grabTitle();
    
    return {
      title,
      message: 'cool stuff :)',
    };
  },
}
```

**Comment by reubenmiller** [comment]
@VladToporkov Did you have a chance to test it out?

**Comment by reubenmiller** [comment]
Closing issue as I'm pretty sure this was also answered on the slack channel. If the above solution does not solve your problem then please reopen this issue and we can help you out further.
