### ISSUE TITLE
Generate multiple reports when using run-multiple command

### ISSUE THREAD

**Issue by cherrieg** [Codeception/CodeceptJS#927]
#### What are you trying to achieve?
If multiple set 4 groups, it will generate 4 reports when use "codeceptjs run-multiple --all --reporter mochawesome".
Could you help merge these 4 reports to 1 report?

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 1.1.2
* NodeJS Version: 8.9.3
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:
/*--run command: codeceptjs run-multiple --all --reporter mochawesome
 **--Author     : Cherrie Gong
 */
exports.config = {
    "tests": "../test/*_test.js",
    "timeout": 100000,
    "output": "../output",
    "include": {
        "censusPage": "../pages/censusPage.js",
        "phonePage": "../pages/phonePage.js",
        "leadPage": "../pages/leadPage.js",
        "quotePage": "../pages/quotePage.js"
    },
    "helpers": {
        "WebDriverIO": {
            "url": "https://",
            "browser": "chrome",
        }
    },
    "name": "layer-x",
    "mocha": {
        "reporterOptions": {
            "reportDir": "../output"
        }
    },
    "Mochawesome": {
        "uniqueScreenshotNames": "true"
    },
    "multiple": {
        "sanity1": {
            "grep": "sanity1",
            "browsers": [{
                "browser": "chrome"
            }]
        },
        "sanity2": {
            "grep": "sanity2",
            "browsers": [{
                "browser": "chrome"
            }]
        },
        "sanity3": {
            "grep": "sanity3",
            "browsers": [{
                "browser": "chrome"
            }]
        },
        "groupAtest": {
            "grep": "groupA",
            "browsers": [{
                "browser": "chrome"
            }]
        }
    }
}
```js
# paste suite config here

```

**Comment by reubenmiller** [comment]
Duplicate #907
