### ISSUE TITLE
How to create an error?

### ISSUE THREAD

**Issue by fio007** [Codeception/CodeceptJS#946]
#### What are you trying to achieve?
I want to create an error. Now I'm using "help.fail('text');"
As a result, I get an error message, but it delays tests for 30 seconds.
How can this be speeded up or done differently?

#### What do you get instead?

&gt; Provide console output if related. Use `--verbose` mode for more details.

```bash
# Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
```

&gt; Provide test source code if related

```js
Scenario('123', function* (I,  help) {

    help.fail("testError");
});
```

```js
"help.js"

'use strict';

let I;
const assert = require('assert');

module.exports = {
  _init() {
    I = actor();
  },
  fail(message) {
    assert.fail(message);
  }
}
```

### Details

* CodeceptJS version: 1.1.4
* NodeJS Version: 8.9.4
* Operating System: 
* Protractor || WebDriverIO || Nightmare version (if related):      (codeceptjs-nightmare: 1.1.0)
* Configuration file:

```js
# paste suite config here
```

**Comment by reubenmiller** [comment]
This is fixed in PR #938 which will be included in the next release. See the PR for an explanation about the problem. It only affects the Nightmare helper.

In the meantime adjust the scenario like so.

```js
Scenario('123', function* (I,  help) {
    I.amOnPage('about:blank'); // Set a page within nightmarejs so it does not hang for 30s on failures
    help.fail("testError");
});
```

**Comment by reubenmiller** [comment]
Though I would suggest changing from using a page object to a custom [helper](https://codecept.io/helpers/) so that the `.fail` function is available from the `I` object.

Custom helpers make their functions automatically available on `I`, so you can call it by using `I.fail('testError')`.

**Comment by fio007** [comment]
I forgot to specify. I use this to create an error if the response received in the request does not match the standard response stored in the constant. In these scenarios I do not interact with the page.

**Comment by reubenmiller** [comment]
Though you're still using the Nightmare right (or at least have it configured in your config file)?

Another workaround is to disable the screenshot on failure setting in the [Nightmare](https://codecept.io/helpers/Nightmare/) helper config. i.e. `disableScreenshots: true`.

Now if you're running tests that have nothing to do with Nightmare, then I would separate those tests and defined a new config file which does not have the Nightmare helper defined.

**Comment by fio007** [comment]
Thanks, it works.
