### ISSUE TITLE
I.grabBrowserUrl is not a function

### ISSUE THREAD

**Issue by ecampii** [Codeception/CodeceptJS#952]
#### What are you trying to achieve?
grab the current url

#### What do you get instead?
     I.grabBrowserUrl is not a function

**Comment by reubenmiller** [comment]
Please provide more information about your setup. i.e. Codeceptjs version, nodejs etc.

**Comment by reubenmiller** [comment]
Though please note that `I.grabBrowserUrl` is currently only available in **WebDriverIO**.

**Comment by hubidu** [comment]
Get the same error message with puppeteer and codeceptjs version 1.1.5

**Comment by reubenmiller** [comment]
Fixed in v1.1.6 which was release today.

`I.grabBrowserurl` has been renamed to `I.grabCurrenturl` and is available for all web helpers (i.e. Puppeteer, Nightmare, WebDriverIO and Protractor)
