### ISSUE TITLE
Proxy via webdriver.io fails

### ISSUE THREAD

**Issue by justinwiley** [Codeception/CodeceptJS#969]
#### What are you trying to achieve?

I want to pass requests through an external proxy.  I followed the instructions in the [docs](https://codecept.io/helpers/WebDriverIO/#connect-through-proxy).

#### What do you get instead?

In the logging I see indications the proxy is being passed on, but its not being used by `selenium-standalone` to proxy requests.

```
10:56:25.020 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@7d95346a
10:56:25.020 INFO - /session: Executing POST on /session (handler: BeginSession)
10:56:25.024 INFO - Capabilities are: Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., proxy: {httpProxy: http://<myproxy>..., proxyType: manual, socksPassword: <my password>..., socksUsername: <my username>}, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.10.2}, rotatable: true}
10:56:25.024 INFO - Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., proxy: {httpProxy: http://<myproxy>..., proxyType: manual, socksPassword: <my password>..., socksUsername: <my username>}, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.10.2}, rotatable: true} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
```

### Details

* CodeceptJS version: 1.1.5
* NodeJS Version: 8.0
* Operating System: mac
* Protractor || WebDriverIO || Nightmare version (if related)
selenium-server-standalone-3.9.1
* Configuration file:

Heres my config:

```
    "helpers": {
      "WebDriverIO": {
        "url": "https://caworkcompcoverage.com",
        "browser": "chrome",
        "desiredCapabilities": {
            "proxy": {
                "proxyType": "manual",
                "httpProxy": "http://proxy:8010",
                "socksUsername": "my username",
                "socksPassword": "my password"
            }
        }
      }
    },
```

**Comment by reubenmiller** [comment]
@justinwiley just to confirm can you confirm the actual error by providing the log output?  Looking at the stuff that you posted I can’t see an error (it will help us debug).

**Comment by reubenmiller** [comment]
Just as a guess, I think you should be using the sslProxy setting instead of the httpProxy because you are trying to access a https webpage.

**Comment by reubenmiller** [comment]
But I think you can define both proxy settings just to be sure.

**Comment by justinwiley** [comment]
Hey @reubenmiller thanks for your reply, I tried sslProxy, no luck.  There are no explicit errors presented by logging, what I see when I execute codecept is a "this IP is not allowed to use the service" page (the service is only accessible through the proxy).  If I hit the page using curl + the proxy, I see the actual page.

**Comment by reubenmiller** [comment]
Then can you use an up address instead of “proxy”?

**Comment by justinwiley** [comment]
Not sure what an up address is ?

**Comment by reubenmiller** [comment]
It was meant to be IP address (but I’m typing with my phone so stupid autocorrect)

**Comment by reubenmiller** [comment]
And are you 100% sure that you need username/password authentication with the proxy?

**Comment by reubenmiller** [comment]
Also try specifying an address with out the “http://“

Unfortunately/fortunately I’m at home at the moment so I don’t have a corporate proxy that I can test against. Though I think if you google “selenium proxy settings chrome” then you should also find something useful as it is more selenium specific problem.

**Comment by justinwiley** [comment]
It was my turn to inadvertently to fat-finger the "close ticket" button.  But since this problem seems specific to my issues, I'll probably move on from trying to solve it now.  Thanks anyway for your help @reubenmiller

**Comment by reubenmiller** [comment]
Though if you find out what the issue was then feel free to post it here, it could be useful for someone else.

**Comment by arifkhanaj** [comment]
I don't know why was this issue closed, I am facing the same issue.
