### ISSUE TITLE
Click not working

### ISSUE THREAD

**Issue by timbergfreund** [Codeception/CodeceptJS#977]
#### What are you trying to achieve?
SeeElement is working, clicking isn't.
```
Scenario('click on five teasers', (I) => {
    I.amOnPage('/');
    I.seeElement('.first-teaser');
    I.click('.first-teaser'); //working
    //page redirect
    I.seeElement('a[title="Zur Startseite von Bergfreunde.de klettern"]');
    I.click('a[title="Zur Startseite von Bergfreunde.de klettern"]'); //not working
});
```
#### What do you get instead?
Node is not visible,
even though seeElement worked before

### Details

* CodeceptJS version: 1.1.6
* Puppeteer 1.1.1
* NodeJS Version: 9.7.0
* Operating System: Windows 10 64bit
* puppeteer with latest chrome (64.0.3282.186)
* Configuration file:

```js
{
  "tests": "./*/*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Puppeteer": {
      "windowSize": "1920x1080",
      "url": "https://www.bergfreunde.de",
      "show": true,
      "waitForAction": 800,
      "keepCookies": true,
      "chrome": { 
            "executablePath" : "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
            "ignoreHTTPSErrors": true,
            "devtools": false
        }
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "bfFrontendTests"
} 
```

**Comment by reubenmiller** [comment]
@timbergfreund What html element are you trying to click, is it a `<div>` or `<span>`?

**Comment by reubenmiller** [comment]
Sorry I just read your test case :D I'll need to test this out later.

**Comment by reubenmiller** [comment]
@timbergfreund Though did you see that the search string matches 3 elements on the page (just tested using the chrome dev tools), is that right?

**Comment by timbergfreund** [comment]
Thats right, it matches 3 elements on the page. Problem is solved, thanks!
