### ISSUE TITLE
module seleniumwebdriver not found. 

### ISSUE THREAD

**Issue by ecampii** [Codeception/CodeceptJS#985]
reinstalling codeceptjs with the following. 

sudo npm install codeceptjs webdriverio selenium-webdriver -g
/usr/local/bin/codeceptjs -> /usr/local/lib/node_modules/codeceptjs/bin/codecept.js
/usr/local/bin/wdio -> /usr/local/lib/node_modules/webdriverio/bin/wdio
+ webdriverio@4.11.0
+ codeceptjs@1.1.6
+ selenium-webdriver@4.0.0-alpha.1
updated 5 packages in 12.224s

#### What do you get instead?
Could not load helper SeleniumWebdriver from module './helper/SeleniumWebdriver':
Cannot find module 'co'

**Comment by reubenmiller** [comment]
I'm pretty sure this is because `selenium-webdriver` is no longer supported in codeceptjs. However don't worry you can use the Protractor Helper (with the `angular: false` option for non-angular apps), and the api is the same :)

It is mentioned in the [docs](https://codecept.io/helpers/Protractor/).

So to install the dependencies run:

```sh
npm install codeceptjs -g
npm install protractor --save-dev
npm install webdriverio --save-dev
```

I'm a little bit sceptical of doing installing multiple npm packages in one command, so it might be safer to install it one at a time.

**Comment by ecampii** [comment]
thanks, i used those but im still getting 

Could not load helper SeleniumWebdriver from module './helper/SeleniumWebdriver':
Cannot find module 'co'

**Comment by reubenmiller** [comment]
Can you try deleting the `node_modules/codeceptjs` folder and try to install it again.

Also what node version are you using?

**Comment by ecampii** [comment]
node -v
v8.9.0

thanks ill try to create a fresh install..

**Comment by ecampii** [comment]
same warning. 

Could not load helper SeleniumWebdriver from module './helper/SeleniumWebdriver':
Cannot find module 'co'

**Comment by reubenmiller** [comment]
Ok more troubleshooting:

1. What is your dev setup? (I've run the command on os x 10.12.6 running node 8.9.3)
1. Did you delete the whole `node_modules` folder?
1. Try installing not using the global npm option. i.e. `npm install codeceptjs`. Though you have to be within an npm project (i.e. having run `npm init` already)

**Comment by reubenmiller** [comment]
4. When is this error message occuring, during the `npm install`? Or are you running a command after the installation?

**Comment by ecampii** [comment]
after running codeceptjs run --steps

**Comment by ecampii** [comment]
I created a new init folder and it worked.

**Comment by reubenmiller** [comment]
I’m guessing that was because you previously had the deprecated selenium webdriverio helper defined in your configuration and not protractor. 

But I’m glad it now works for you :)
