### ISSUE TITLE
CodeceptJS's Puppeteer library not working with "complex" Xpath selectors

### ISSUE THREAD

**Issue by Helene2889** [Codeception/CodeceptJS#989]
#### What are you trying to achieve?
Use CodeceptJS's Puppeteer library with Xpath selectors

#### What do you get instead?
xpath check is  not covering all xpath "templates": 
```js
function isXPath(locator) {
  return locator.substr(0, 2) === '//' || locator.substr(0, 3) === './/';
}
```
is not covering the case where the fist child of a xpath must be selected, like in the example below:

```js
'(//*[@data-protractor-id="recipient-select"] //*[contains(concat(" ", normalize-space(@class), " "), "ui-select-choices-row")])[1]'
```

### Details

* CodeceptJS version: 1.1.6
* NodeJS Version: 8.9.1
* Operating System: OS High SIerra
* Puppeteer 1.1.1
* Configuration file:

**Comment by reubenmiller** [comment]
@Helene2889 If you know you want to locate elements using a complex xpath query then you can use the following notation.

```js
Scenario('Test complex xpath', (I) => {
  I.amOnPage('/');
  I.seeElement({
    xpath: '(//*[@data-protractor-id="recipient-select"] //*[contains(concat(" ", normalize-space(@class), " "), "ui-select-choices-row")])[1]',
  });
})
```

This information is detailed in the [docs](https://codecept.io/acceptance/) under the "Locating Element" section.

**Comment by Helene2889** [comment]
Hi @reubenmiller,

Yes, thank you, this will work for the waitForVisbile / waitForElement...But not for the helpers like I.click (all that have this style to identify the type of the selectors):
`async function findClickable(matcher, locator) {
  locator = new Locator(locator);
  if (!locator.isFuzzy()) return findElements.call(this, matcher, locator.simplify());
  console.log('locator', locator)
  let els;....
`
The xpath that starts with `(`will be recognized as fuzzy: 
` • I click {"xpath":"(//*[@data-protractor-id=\"recipient-select\"] //*[contains(concat(\" \", normalize-space(@class), \" \"), \"ui-select-choices-row\")])[1]"}`

**Comment by reubenmiller** [comment]
@Helene2889 Yes you're right, good find! `I.click` didn't work properly when using an explicit xpath selector for the **Protractor** and **Puppeteer** helpers.

I've created a unit test for this now which is run across all of the helpers, so it should now be consistent. I've created a fix and will submit the PR once I'm sure that the changes does break anything.

**Comment by Helene2889** [comment]
thanks.
