### ISSUE TITLE
Before Statement does not work synchronous

### ISSUE THREAD

**Issue by fabioel** [Codeception/CodeceptJS#99]
Hi Guys!

I have come across a very strange behavior today and would need some assistance. The problem is that I am trying to execute one rather large helper function before a smaller one in the `before`-statement of my test. The problem is that the bigger (which is executed first) is simply called and the test runner does not wait until it is finished, therefore failing my tests.

Is there a workaround to make sure that the execution of the helper function is finished before the next one is called?

The strangest thing is that when I move the second function into the `Scenario` body the execution is done properly, I can't do this though, because I have multiple `Scenarios` and I would have a huge code duplication

**Comment by fabioel** [comment]
__UPDATE__

I have found out that it has something to do with the loading of the helpers. The race condition is due to the fact that I have one of the helper function directly in the steps file (this function is executed first) and the other is in a separate helper class.

**Comment by APshenkin** [comment]
Please test it in 1.0.0 and if the issue still exist, create a new issue
