### ISSUE TITLE
Puppeteer время ожидания в I.waitForText

### ISSUE THREAD

**Issue by ngadiyak** [Codeception/CodeceptJS#994]
https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Puppeteer.js#L1499

по дефолту в настройках Puppeteer waitForTimeout задается в миллисекундах.

если в I.waitForText не передать вторым параметром количество секунд, то функция будет ждать время x1000

**Comment by DavertMik** [comment]
Исправил в 1.1.7
