### ISSUE TITLE
Travel in time to test time dependent features

### ISSUE THREAD

**Issue by nursahketene** [Codeception/CodeceptJS#996]
#### What are you trying to achieve?

I am trying to test a feature that is dependent on time

For instance:

* User starts a course
* User returns back to home page before finishing the course
* There is a message on the home page saying (Course is paused)
* User comes back to home page three days later
* User sees a message (Course is stale)

**Comment by DavertMik** [comment]
Sorry. This is out of scope of CodeceptJS
